{
 id:"w2d1", day:8, cat:"품질·리스크", level:"B2+",
 title:"The Recall Nobody Wants to Own",
 titleKo:"아무도 떠안기 싫은 리콜 — 결함과 책임의 경계",
 names:{A:"Grace (품질보증)", B:"Diego (구매·공급망)"},
 brief:[
  "제조 현장에서 결함이 나오면 가장 먼저 정해지는 것은 책임이 아니라 순서다. <b>봉쇄(containment)</b>가 먼저고 <b>시정(corrective action)</b>이 그다음이며, 책임 배분은 마지막이다. 원인을 다 밝히기 전에도 확산은 멈춰야 하기 때문이다.",
  "책임을 가르는 실질적 기준은 <b>입증책임(the burden of proof)</b>이 어디에 놓이느냐다. 공급사는 도면과 규격을 들고 오고, 완성품 업체는 실제 사용 조건을 든다. 계약서의 <b>책임한도(liability cap)</b>가 이 다툼의 상한을 미리 정해 둔다.",
  "리콜의 비용 구조는 <b>확실한 비용 대 불확실한 비용</b>의 대결이다. 지금 회수하면 금액이 확정되고, 미루면 확률은 낮지만 손실이 큰 <b>꼬리위험(tail risk)</b>이 남는다. 둘을 같은 저울에 올리는 순간 판단이 쉬워진다.",
  "그래서 실무에서 진짜로 다투는 것은 「리콜을 하느냐」가 아니라 <b>범위(scope)</b>다. 어느 로트까지, 어느 일련번호까지 포함할 것인가. 이 선을 예산이 아니라 <b>증거</b>로 그어야 나중에 방어할 수 있다."
 ],
 lines:[
  {s:"A",en:"We've traced the cracking to a single supplier's batch, though the design tolerance we specified was tight to begin with.",
   ko:"균열을 한 공급사의 특정 로트까지 추적했어요. 다만 우리가 지정한 설계 공차 자체가 애초에 빡빡했죠.",
   notes:[{t:"trace A to B",k:"phrasal",m:"A의 원인을 B까지 거슬러 찾아내다",tip:"We traced the leak to a faulty valve. 원인 규명 보고의 표준 동사입니다."},
          {t:"the tolerance we specified",k:"grammar",m:"우리가 지정한 그 공차",tip:"접촉절입니다. 책임의 절반이 우리에게 있다는 사실을 명사 안에 조용히 넣었습니다."},
          {t:"to begin with",k:"idiom",m:"애초에, 처음부터",tip:"문장 끝에 붙여 '원래부터 그랬다'는 뜻을 답니다. in the first place와 바꿔 쓸 수 있습니다."}]},
  {s:"B",en:"Hold on. You're already framing this as ours in a report that goes out tomorrow, and the analysis isn't finished.",
   ko:"잠깐요. 내일 나갈 보고서에서 벌써 우리 책임으로 몰고 계신데, 분석이 끝나지도 않았어요.",
   notes:[{t:"Hold on.",k:"colloquial",m:"잠깐만요 (말을 끊고 제동)",tip:"Wait보다 부드럽고 회의에서 훨씬 자주 씁니다. Hold on, let me finish."},
          {t:"frame A as B",k:"business",m:"A를 B인 것처럼 규정하다",tip:"프레임을 씌운다는 뜻. Don't frame this as a failure. 논쟁에서 상대의 전제를 걷어낼 때 씁니다."},
          {t:"a report that goes out tomorrow",k:"grammar",m:"내일 나갈 보고서",tip:"관계절 안의 현재시제가 확정된 미래를 나타냅니다. 일정이 잡힌 일에는 will을 쓰지 않습니다."}]},
  {s:"A",en:"I'm not assigning blame. I'm saying the burden of proof is going to land on whoever specified the tolerance, which was us.",
   ko:"책임을 떠넘기는 게 아니에요. 입증책임이 공차를 지정한 쪽에 떨어질 거라는 말이고, 그게 우리라는 겁니다.",
   notes:[{t:"the burden of proof",k:"business",m:"입증책임",tip:"The burden of proof is on the supplier. 계약·품질 회의의 핵심 단어입니다."},
          {t:"whoever specified ~, which was us",k:"grammar",m:"~을 지정한 사람이 누구든, 그게 우리였다",tip:"복합관계대명사로 열어 두고 which로 정답을 밝히는 2단 구성입니다. 자기 책임을 인정하는 세련된 방식입니다."},
          {t:"land on ~",k:"phrasal",m:"(부담이) ~에게 떨어지다",tip:"The cost landed on our division. 의도치 않게 떠안게 됐다는 뉘앙스."}]},
  {s:"B",en:"It always does. The supplier will point at the drawing we sent them, and we'll be on the hook for a batch we never made.",
   ko:"늘 그렇죠. 공급사는 우리가 보낸 도면을 가리킬 테고, 우리가 만들지도 않은 로트를 우리가 뒤집어쓰게 될 겁니다.",
   notes:[{t:"be on the hook (for)",k:"idiom",m:"(비용·책임을) 떠안다",tip:"We're on the hook for the repair cost. 한국인이 잘 안 쓰는데 원어민은 매우 자주 씁니다."},
          {t:"a batch we never made",k:"grammar",m:"우리가 만들지도 않은 로트",tip:"접촉절 하나로 억울함을 압축했습니다. 감정을 형용사로 말하지 않고 사실로 말하는 화법입니다."},
          {t:"point at ~",k:"phrasal",m:"~을 (책임 근거로) 들이대다",tip:"point to the contract / point at the drawing. 문서를 근거로 삼는다는 뜻으로 확장됩니다."}]},
  {s:"A",en:"Which is why we contain first and argue later: stop shipments, quarantine the lot, and have the argument once we know what we're arguing about.",
   ko:"그래서 봉쇄가 먼저고 논쟁이 나중인 겁니다. 출하 중단, 로트 격리, 그리고 무엇을 두고 다투는지 알게 된 뒤에 다투는 거죠.",
   notes:[{t:"Which is why ~",k:"grammar",m:"바로 그래서 ~인 겁니다",tip:"앞 문장 전체를 받아 결론으로 잇는 연결어. That's why보다 논증적으로 들립니다."},
          {t:"contain",k:"business",m:"(확산을) 봉쇄하다",tip:"품질 용어로 containment action = 봉쇄 조치. 원인 규명 전에 하는 응급 처치입니다."},
          {t:"once we know what we're arguing about",k:"grammar",m:"무엇을 두고 다투는지 알게 되면",tip:"once절 + 간접의문문의 조합입니다. once 뒤에는 미래 대신 현재를 씁니다."}]},
  {s:"B",en:"Containment I can live with. A public recall is a different animal entirely, and it's the one that ends up in the trade press.",
   ko:"봉쇄까지는 받아들일 수 있어요. 공개 리콜은 완전히 다른 이야기고, 업계지에 실리는 건 그쪽이죠.",
   notes:[{t:"I can live with ~",k:"idiom",m:"~ 정도는 감수할 수 있다",tip:"완전히 만족하진 않지만 수용한다는 뜻. 협상에서 부분 합의를 표시할 때 최고의 표현입니다."},
          {t:"a different animal",k:"idiom",m:"성격이 전혀 다른 것",tip:"That's a different animal altogether. 규모나 종류가 다르다는 뜻으로 씁니다."},
          {t:"the one that ends up in ~",k:"grammar",m:"결국 ~에 실리게 되는 쪽",tip:"end up in ~ = 결국 ~에 이르다. the one that ~ 으로 둘 중 하나를 지목합니다."}]},
  {s:"A",en:"Agreed, but if we sit on this and it surfaces through a customer rather than through us, it comes back to bite us twice.",
   ko:"동의해요. 그런데 이걸 깔고 앉아 있다가 우리가 아니라 고객을 통해 드러나면, 두 배로 되돌아옵니다.",
   notes:[{t:"sit on ~",k:"phrasal",m:"~을 묵혀 두다, 깔고 앉다",tip:"They sat on the report for months. 알고도 조치를 미뤘다는 부정적 뉘앙스."},
          {t:"come back to bite us",k:"idiom",m:"나중에 부메랑으로 돌아오다",tip:"That shortcut will come back to bite us. 미룬 결정의 대가를 말할 때."},
          {t:"through A rather than through B",k:"grammar",m:"B가 아니라 A를 통해",tip:"전치사를 두 번 반복해 대비를 또렷하게 만들었습니다. 생략하면 문장이 흐려집니다."}]},
  {s:"B",en:"You're assuming it surfaces at all. Most of the parts in that batch will never see a load anywhere near what we tested for.",
   ko:"애초에 드러난다는 걸 전제하시는 거잖아요. 그 로트 부품 대부분은 우리가 시험한 하중 근처에도 못 가 볼 겁니다.",
   notes:[{t:"You're assuming ~",k:"business",m:"~을 전제하고 계시잖아요",tip:"상대 논리의 숨은 가정을 끄집어내는 토론 필수 표현. 공격적이지 않게 반박됩니다."},
          {t:"anywhere near what we tested for",k:"grammar",m:"우리가 시험한 수준 근처에도",tip:"anywhere near는 부정문에서 '근처에도 못 미친다'는 강조입니다. what절이 목적어로 붙었습니다."}]},
  {s:"A",en:"That's a gamble on tail risk. The odds are low, but the downside is large enough to swallow every saving we'd make by waiting.",
   ko:"그건 꼬리위험에 거는 도박이에요. 확률은 낮지만, 손실이 기다려서 아낀 돈을 전부 삼킬 만큼 큽니다.",
   notes:[{t:"tail risk",k:"business",m:"확률은 낮지만 손실이 큰 위험",tip:"금융에서 온 말이 품질·안전 회의로 넘어왔습니다. low-probability, high-impact와 같은 뜻."},
          {t:"the downside",k:"business",m:"최악의 경우 손실",tip:"upside(잘 됐을 때 이익)와 짝입니다. What's the downside? 는 회의에서 매일 나옵니다."},
          {t:"every saving we'd make by waiting",k:"grammar",m:"기다려서 아끼게 될 모든 절감액",tip:"접촉절 + 가정법 would + by -ing. 세 요소가 한 명사구에 들어간 고밀도 표현입니다."}]},
  {s:"B",en:"Fair. Still, somebody in this room has to weigh a certain cost against an uncertain one, and that person signs either way.",
   ko:"일리 있어요. 그래도 이 방의 누군가는 확실한 비용과 불확실한 비용을 저울에 올려야 하고, 어느 쪽이든 그 사람이 서명합니다.",
   notes:[{t:"weigh A against B",k:"collocation",m:"A와 B를 견주어 판단하다",tip:"compare보다 '득실을 따진다'는 뜻이 강합니다. weigh the risks against the benefits."},
          {t:"either way",k:"idiom",m:"어느 쪽이든 간에",tip:"결과가 갈려도 부담은 같다는 뜻을 두 단어로 담습니다. 문장 끝에 붙이세요."}]},
  {s:"A",en:"Then let's price both of them honestly, instead of dressing the cheaper option up as prudence and hoping nobody checks the reasoning.",
   ko:"그럼 둘 다 정직하게 값을 매기죠. 싼 쪽을 신중함으로 포장해 놓고 아무도 논리를 안 따지길 바라지 말고요.",
   notes:[{t:"dress ~ up as …",k:"idiom",m:"~을 …인 것처럼 포장하다",tip:"They dressed a budget cut up as a strategy. 비판할 때 아주 잘 드는 표현입니다."},
          {t:"price ~",k:"business",m:"~에 값을 매기다, 비용으로 환산하다",tip:"동사로 씁니다. price the risk / price it in(가격에 이미 반영하다)."},
          {t:"instead of -ing and -ing",k:"grammar",m:"~하고 ~하는 대신에",tip:"전치사 뒤 동명사 두 개를 and로 이었습니다. 두 번째에 of를 다시 붙이지 않습니다."}]},
  {s:"B",en:"Careful. That cuts the other way, because erring on the side of caution isn't free either once you count the lines we'd stop.",
   ko:"조심하세요. 그 논리는 반대로도 작동합니다. 멈추게 될 라인을 세어 보면, 안전하게 가는 것도 공짜가 아니거든요.",
   notes:[{t:"That cuts the other way.",k:"idiom",m:"그 논리는 반대편에도 똑같이 적용됩니다",tip:"상대의 무기를 그대로 돌려줄 때. cut both ways = 양날의 검이다."},
          {t:"err on the side of caution",k:"idiom",m:"안전한 쪽으로 판단을 기울이다",tip:"통째로 외우세요. err는 /ɜːr/로 읽습니다. 회의에서 매우 자주 나옵니다."},
          {t:"once you count ~",k:"grammar",m:"~을 세어 보면",tip:"once가 '일단 ~하고 나면'이라는 조건을 만듭니다. 숨은 비용을 드러낼 때 잘 쓰입니다."}]},
  {s:"A",en:"No, and I'd never pretend it is. But a quiet field fix buys us credibility that we can't purchase any other way.",
   ko:"맞아요, 공짜인 척할 생각도 없습니다. 다만 조용한 현장 수리는 다른 방법으로는 살 수 없는 신뢰를 벌어 줘요.",
   notes:[{t:"buy (someone) ~",k:"idiom",m:"~을 벌어 주다, 확보해 주다",tip:"buy us time / buy us credibility. 돈이 아니라 시간·신뢰를 목적어로 씁니다."},
          {t:"field fix",k:"business",m:"현장 조치, 출고 후 수리",tip:"in the field = 고객 현장에서. field failure / field data 세트로 쓰입니다."},
          {t:"credibility that we can't purchase any other way",k:"grammar",m:"다른 방법으로는 살 수 없는 신뢰",tip:"buy와 purchase를 한 문장에 나란히 써서 비유를 끝까지 밀고 갔습니다. 영어다운 문장 운용입니다."}]},
  {s:"B",en:"A silent recall, you mean. Regulators have a name for that, and it's the sort of thing that turns a defect into a case.",
   ko:"그러니까 은밀한 리콜이란 말이죠. 규제 당국도 그걸 부르는 이름이 있고, 결함을 사건으로 바꿔 놓는 게 딱 그런 겁니다.",
   notes:[{t:"~, you mean.",k:"colloquial",m:"그러니까 ~라는 말씀이죠",tip:"상대 표현을 더 노골적인 말로 바꿔 되받는 기법. 토론에서 아주 강력합니다."},
          {t:"the sort of thing that turns A into B",k:"grammar",m:"A를 B로 바꿔 놓는 그런 종류의 일",tip:"the sort/kind of thing that ~ 은 범주로 경고할 때 쓰는 완곡하면서 강한 표현입니다."}]},
  {s:"A",en:"Then we notify properly. My point was never whether we own it; my point is how wide the scope has to be.",
   ko:"그럼 제대로 신고하죠. 제 요지는 우리가 책임지느냐가 아니었어요. 범위를 얼마나 넓게 잡아야 하느냐입니다.",
   notes:[{t:"My point is ~",k:"business",m:"제 요지는 ~입니다",tip:"논점이 흐려졌을 때 되돌리는 문장. That's not my point. 도 함께 외우세요."},
          {t:"own it",k:"idiom",m:"책임을 인정하고 떠맡다",tip:"We should just own it. 잘못을 인정한다는 뜻으로 현대 비즈니스 영어에서 매우 흔합니다."},
          {t:"how wide the scope has to be",k:"grammar",m:"범위를 얼마나 넓게 잡아야 하는지",tip:"간접의문문이라 how wide 뒤가 주어+동사입니다. how wide has the scope로 쓰면 틀립니다."}]},
  {s:"B",en:"Scope is where this gets expensive. Every extra lot we include widens a bill that somebody upstairs will read line by line.",
   ko:"비싸지는 지점이 바로 범위예요. 로트를 하나 더 넣을 때마다, 윗선에서 한 줄 한 줄 읽을 청구서가 넓어집니다.",
   notes:[{t:"where this gets ~",k:"grammar",m:"바로 이 지점에서 ~해진다",tip:"That's where it gets tricky. 문제의 핵심을 짚는 구어 골격입니다."},
          {t:"a bill somebody will read line by line",k:"grammar",m:"누군가 한 줄씩 읽어 볼 청구서",tip:"접촉절로 '감시받는다'는 압박을 명사에 실었습니다. line by line은 꼼꼼한 검토를 뜻합니다."}]},
  {s:"A",en:"So we draw the line on evidence rather than on budget, because the moment the number drives the engineering, we can't defend either one.",
   ko:"그러니 선은 예산이 아니라 증거로 긋죠. 숫자가 기술 판단을 끌고 가는 순간, 둘 다 방어할 수 없게 되니까요.",
   notes:[{t:"draw the line",k:"idiom",m:"한계선을 긋다",tip:"draw the line at ~ = ~까지는 허용하고 그 이상은 안 된다."},
          {t:"the moment ~",k:"grammar",m:"~하는 순간",tip:"as soon as와 같은 뜻인데 훨씬 극적입니다. 접속사처럼 절을 이끕니다."},
          {t:"A drives B",k:"collocation",m:"A가 B를 좌우하다",tip:"Cost is driving the design. 주객이 전도됐다는 비판에 자주 씁니다."}]},
  {s:"B",en:"That's fair. Let's ring-fence the serial range the test data actually covers, and defend that boundary rather than a convenient one.",
   ko:"타당하네요. 시험 데이터가 실제로 덮는 일련번호 구간만 따로 떼어 놓고, 편한 경계가 아니라 그 경계를 방어합시다.",
   notes:[{t:"ring-fence",k:"business",m:"(대상을) 울타리 쳐 따로 떼어 두다",tip:"ring-fence the budget / the affected units. 영국식이지만 이제 널리 쓰입니다."},
          {t:"the range the test data actually covers",k:"grammar",m:"시험 데이터가 실제로 덮는 그 구간",tip:"접촉절 안의 actually가 '편의가 아니라 사실'이라는 기준을 실어 줍니다."}]},
  {s:"A",en:"And we front-load the supplier conversation, in good faith, before the lawyers on either side start deciding what we're allowed to say.",
   ko:"그리고 공급사와의 대화를 앞당깁시다. 선의로요. 양쪽 변호사들이 우리가 무슨 말을 해도 되는지 정하기 시작하기 전에요.",
   notes:[{t:"front-load",k:"business",m:"앞쪽에 몰아서 하다, 앞당기다",tip:"front-load the work / the cost. 반대는 back-load. 일정 회의에서 자주 나옵니다."},
          {t:"in good faith",k:"business",m:"선의로, 성실하게",tip:"계약 용어이면서 일상 표현입니다. We acted in good faith. 라고 하면 방어가 됩니다."},
          {t:"what we're allowed to say",k:"grammar",m:"우리가 말해도 되는 것",tip:"what절 + 수동태 조합입니다. 통제받는 상황을 명사 하나로 표현합니다."}]},
  {s:"B",en:"Good. I'd rather split the difference on cost with a supplier we trust than kick this can down a road that only gets narrower.",
   ko:"좋습니다. 갈수록 좁아지기만 하는 길로 이 문제를 미루느니, 믿는 공급사와 비용을 반씩 나누는 편이 낫죠.",
   notes:[{t:"split the difference",k:"idiom",m:"차액을 반씩 나눠 절충하다",tip:"협상 마무리의 정석 표현입니다. Let's split the difference and move on."},
          {t:"kick the can down the road",k:"idiom",m:"결정을 뒤로 미루다",tip:"통째로 외우세요. 미룬다는 뜻의 표현 중 가장 자주 쓰입니다."},
          {t:"a road that only gets narrower",k:"grammar",m:"갈수록 좁아지기만 하는 길",tip:"관용구의 마지막 단어(road)에 관계절을 붙여 비유를 되살렸습니다. 영어 글쓰기의 고급 기술입니다."}]}
 ],
 keys:[
  {en:"be on the hook for ~",ko:"~의 책임·비용을 떠안다",ex:"If the test fails, we're on the hook for the rework."},
  {en:"the burden of proof",ko:"입증책임",ex:"The burden of proof sits with whoever claims the defect."},
  {en:"come back to bite us",ko:"나중에 부메랑으로 돌아오다",ex:"Skipping the audit will come back to bite us."},
  {en:"err on the side of caution",ko:"안전한 쪽으로 판단하다",ex:"With safety parts, we err on the side of caution."},
  {en:"That cuts the other way.",ko:"그 논리는 반대편에도 적용됩니다",ex:"That cuts the other way — speed has a cost too."},
  {en:"ring-fence ~",ko:"~만 따로 떼어 보호하다",ex:"Let's ring-fence next year's maintenance budget."},
  {en:"split the difference",ko:"차액을 반씩 나눠 절충하다",ex:"Neither side moved, so we split the difference."},
  {en:"kick the can down the road",ko:"결정을 뒤로 미루다",ex:"Another review just kicks the can down the road."}
 ],
 out:[
  {q:"Describe a defect or complaint your team handled. What did you contain first, and what did you fix later?",hint:"contain / trace it to / on the hook for"},
  {q:"Argue that acting late is more expensive than acting early, then argue the opposite.",hint:"tail risk / err on the side of caution / that cuts the other way"},
  {q:"Your supplier blames your drawing. Respond without accepting blame and without escalating.",hint:"the burden of proof / in good faith / front-load"}
 ]
},
{
 id:"w2d2", day:9, cat:"환경·통상", level:"B2+",
 title:"Paying for Carbon at the Border",
 titleKo:"국경에서 탄소값을 치르다 — 배출 규제와 수출 경쟁력",
 names:{A:"Lena (환경·규제 대응)", B:"Hugo (수출영업)"},
 brief:[
  "배출에 값이 매겨지면 원가 구조가 바뀐다. 지금까지 원가는 원료와 에너지였지만, <b>탄소 가격(carbon pricing)</b>이 붙는 순간 배출량 자체가 비용 항목이 된다. 같은 제품, 같은 공정이라도 어디서 어떻게 만들었는지가 값을 가른다.",
  "국경에서 조정이 일어나는 이유는 <b>탄소 누출(carbon leakage)</b> 때문이다. 규제가 강한 나라의 공장이 규제가 약한 나라로 옮겨 가면 배출은 그대로인 채 산업만 빠져나간다. 그래서 수입품에도 같은 값을 물려 <b>공정한 경쟁 조건(a level playing field)</b>을 맞추려 한다.",
  "실무의 난점은 규제가 아니라 <b>측정</b>이다. 한 톤에 들어 있는 배출량(embedded emissions)을 어떻게 셈하느냐에 따라 누가 얼마를 내는지가 달라진다. 그래서 다툼은 늘 방법론에서 벌어지고, <b>검증(verification)</b>을 거친 숫자만 값을 인정받는다.",
  "영업 쪽에서 갈리는 것은 <b>전가(pass-through)</b>다. 늘어난 비용을 가격에 얹을 수 있는 고객이 있고, 얹는 순간 떠나는 고객이 있다. 검증된 데이터가 있으면 <b>친환경 프리미엄(green premium)</b>이 붙지만, 없으면 그냥 값만 오른 제품이 된다."
 ],
 lines:[
  {s:"A",en:"Once emissions carry a price at the border, our cost base stops being just steel and energy and starts including how we made it.",
   ko:"국경에서 배출에 값이 붙는 순간, 우리 원가는 철과 에너지만이 아니라 어떻게 만들었느냐까지 포함하게 됩니다.",
   notes:[{t:"carry a price",k:"collocation",m:"값이 매겨지다, 대가가 따르다",tip:"Everything carries a price now. carry a risk / carry a penalty 로도 확장됩니다."},
          {t:"cost base",k:"business",m:"원가 구조, 비용 기반",tip:"lower our cost base = 원가 구조를 낮추다. 경영진 보고의 단골 표현입니다."},
          {t:"stops being A and starts including B",k:"grammar",m:"A이기를 멈추고 B를 포함하기 시작하다",tip:"stop과 start 뒤에 나란히 동명사를 붙여 변화를 한 문장에 담았습니다."}]},
  {s:"B",en:"In theory. In practice, nobody can agree on how to measure what's embedded in a ton, which is where every negotiation stalls.",
   ko:"이론상은요. 현실에선 한 톤에 뭐가 들어 있는지 재는 방법부터 합의가 안 되고, 협상은 늘 거기서 멈춥니다.",
   notes:[{t:"In theory. In practice, ~",k:"idiom",m:"이론상은 그렇고, 현실은 ~",tip:"두 문장으로 끊어 던지는 반박 리듬입니다. 토론에서 아주 강하게 들립니다."},
          {t:"embedded",k:"business",m:"(제품 안에) 내재된",tip:"embedded emissions / embedded cost. 겉으로 안 보이지만 안에 들어 있다는 뜻."},
          {t:"which is where ~ stalls",k:"grammar",m:"바로 거기서 ~이 멈춘다",tip:"앞 절을 which로 받고 관계부사 where로 '지점'을 짚습니다. 병목을 지목하는 세련된 형태입니다."}]},
  {s:"A",en:"That's the whole fight. Measurement decides who pays, so everyone argues about method while pretending to argue about principle.",
   ko:"싸움의 전부가 거기예요. 측정이 누가 낼지를 정하니, 다들 원칙을 두고 다투는 척하면서 방법론을 두고 다투는 거죠.",
   notes:[{t:"That's the whole fight.",k:"colloquial",m:"바로 그 지점이 쟁점의 전부입니다",tip:"That's the whole point. 의 변형. 핵심을 한마디로 못 박을 때 씁니다."},
          {t:"while pretending to ~",k:"grammar",m:"~하는 척하면서",tip:"분사구문입니다. 주어가 같으므로 while 뒤에 주어를 다시 쓰지 않습니다."}]},
  {s:"B",en:"And meanwhile my customers want a number today, not a methodology paper next year that three consultants will disagree with anyway.",
   ko:"그러는 동안 제 고객들은 오늘 숫자를 원해요. 어차피 컨설턴트 셋이 서로 반대할 내년 방법론 보고서가 아니라요.",
   notes:[{t:"And meanwhile ~",k:"colloquial",m:"그러는 사이에 (현실은)",tip:"이상론을 현실로 끌어내릴 때 씁니다. 영업이 기획을 반박하는 전형적인 시작입니다."},
          {t:"a paper that consultants will disagree with",k:"grammar",m:"컨설턴트들이 반대할 보고서",tip:"관계절 끝에 전치사 with가 남습니다. disagree with ~ 의 with가 사라지지 않도록 주의하세요."}]},
  {s:"A",en:"Give them a range and the assumptions behind it. A precise number that turns out to be wrong costs more than an honest range.",
   ko:"구간으로 주고 그 뒤의 전제도 밝히세요. 정밀했다가 틀린 숫자가 정직한 구간보다 비싸게 먹힙니다.",
   notes:[{t:"the assumptions behind it",k:"business",m:"그 숫자가 딛고 선 전제",tip:"What are the assumptions behind this? 는 숫자를 검증할 때 가장 좋은 질문입니다."},
          {t:"a number that turns out to be wrong",k:"grammar",m:"나중에 틀린 것으로 드러나는 숫자",tip:"turn out to be ~ = 결국 ~로 밝혀지다. 관계절 안에 넣으면 위험을 명사에 붙일 수 있습니다."}]},
  {s:"B",en:"Try selling a range to a buyer whose own boss wants one figure. They read uncertainty as risk and price it against us.",
   ko:"자기 상사가 숫자 하나를 원하는 구매자한테 구간을 한번 팔아 보세요. 불확실성을 위험으로 읽고 우리한테 불리하게 값을 매깁니다.",
   notes:[{t:"Try ~ing.",k:"colloquial",m:"(비꼬듯) 그거 한번 해 보시죠",tip:"Try explaining that to a customer. 실현 불가능함을 지적하는 반어법입니다."},
          {t:"a buyer whose own boss wants ~",k:"grammar",m:"자기 상사가 ~을 원하는 구매자",tip:"소유격 관계대명사 whose입니다. 사람의 사정을 한 문장에 접어 넣을 때 매우 유용합니다."},
          {t:"price it against us",k:"business",m:"우리에게 불리하게 가격에 반영하다",tip:"price A in(가격에 반영하다) / price A against B(불리하게 매기다) 를 짝으로 외우세요."}]},
  {s:"A",en:"Then we verify early and get certified, because verification is what turns a claim anyone can make into a discount only we can offer.",
   ko:"그럼 일찍 검증받고 인증까지 받죠. 누구나 할 수 있는 주장을 우리만 줄 수 있는 할인으로 바꾸는 게 검증이니까요.",
   notes:[{t:"turn A into B",k:"phrasal",m:"A를 B로 바꾸다",tip:"What turns a claim into evidence? 처럼 씁니다. 문장을 힘 있게 만드는 골격입니다."},
          {t:"a claim anyone can make / a discount only we can offer",k:"grammar",m:"누구나 할 수 있는 주장 / 우리만 줄 수 있는 할인",tip:"같은 접촉절 구조를 두 번 써서 대구를 만들었습니다. 차별성을 설명하는 데 최적입니다."}]},
  {s:"B",en:"Certification costs money we'd have to pass through, and the thin-margin customers who make up half our volume will simply walk.",
   ko:"인증에는 우리가 전가해야 할 돈이 들고, 물량의 절반을 차지하는 마진 얇은 고객들은 그냥 떠날 겁니다.",
   notes:[{t:"pass ~ through",k:"business",m:"(비용을) 가격에 전가하다",tip:"pass the cost through to customers. 명사형 pass-through도 그대로 씁니다."},
          {t:"customers who make up half our volume",k:"grammar",m:"우리 물량의 절반을 차지하는 고객들",tip:"make up = 구성하다, 차지하다. 관계절로 비중을 밝혀 반박의 무게를 실었습니다."},
          {t:"walk",k:"colloquial",m:"(거래를 접고) 떠나다",tip:"If we raise it, they'll walk. walk away from the deal의 줄임으로 쓰입니다."}]},
  {s:"A",en:"Some will. Others will pay a premium the moment their own reporting depends on numbers that somebody has actually audited.",
   ko:"일부는 떠나겠죠. 하지만 자기네 보고가 누군가 실제로 감사한 숫자에 걸리는 순간, 웃돈을 낼 고객도 있습니다.",
   notes:[{t:"pay a premium",k:"collocation",m:"웃돈을 지불하다",tip:"pay a premium for quality. 반대는 at a discount. 한 세트로 외우세요."},
          {t:"numbers that somebody has actually audited",k:"grammar",m:"누군가 실제로 감사한 숫자",tip:"현재완료 관계절입니다. 검증 여부가 가치를 가른다는 논지를 명사 안에 넣었습니다."}]},
  {s:"B",en:"You're betting their regulators bite before ours do, which is a big assumption to build a capital plan on.",
   ko:"그쪽 규제가 우리 쪽보다 먼저 조여든다는 데 거시는 거죠. 자본 계획을 얹기엔 큰 가정입니다.",
   notes:[{t:"bite",k:"idiom",m:"(규제·정책이) 실제로 아프게 작용하다",tip:"When do the rules start to bite? 발효는 됐지만 아직 체감되지 않을 때 씁니다."},
          {t:"a big assumption to build a plan on",k:"grammar",m:"계획을 얹기에는 큰 가정",tip:"명사 + to부정사 + 문미 전치사 on 구조입니다. build A on B의 on이 그대로 남습니다."}]},
  {s:"A",en:"It's not a bet on timing. It's a bet that a direction which every major buyer is already moving in doesn't reverse.",
   ko:"시점에 거는 게 아니에요. 주요 구매자들이 이미 그쪽으로 움직이고 있는 방향이 되돌아가지 않는다는 데 거는 겁니다.",
   notes:[{t:"It's not A. It's B.",k:"grammar",m:"A가 아니라 B입니다",tip:"상대의 규정을 고쳐 잡는 대조 골격. 짧게 끊어 말할수록 힘이 실립니다."},
          {t:"a direction which everyone is moving in",k:"grammar",m:"모두가 그쪽으로 움직이고 있는 방향",tip:"관계절 끝에 전치사 in이 남습니다. move in a direction의 in을 빠뜨리지 마세요."}]},
  {s:"B",en:"Fair enough. Still, if we move first we carry the cost alone for years while everyone else watches to see what it does to us.",
   ko:"일리 있어요. 그래도 먼저 움직이면 몇 년을 혼자 비용을 짊어지고, 나머지는 우리가 어떻게 되나 구경할 겁니다.",
   notes:[{t:"Fair enough. Still, ~",k:"idiom",m:"일리는 있습니다. 그래도 ~",tip:"인정하고 반박으로 넘어가는 다리. 토론에서 가장 자주 쓰는 전환입니다."},
          {t:"move first",k:"business",m:"선제적으로 나서다",tip:"first mover advantage와 짝. move first / wait and see 가 대립 구도를 만듭니다."},
          {t:"watch to see what it does to us",k:"grammar",m:"그게 우리한테 어떤 결과를 내는지 지켜보다",tip:"watch to see + 의문사절 구조입니다. 관망하는 태도를 정확히 묘사합니다."}]},
  {s:"A",en:"And if we move last we buy the same equipment at panic prices alongside everyone who waited exactly as long as we did.",
   ko:"마지막에 움직이면, 우리만큼 기다린 사람들과 나란히 똑같은 설비를 값이 치솟은 상태로 사게 되죠.",
   notes:[{t:"at panic prices",k:"collocation",m:"수요가 몰려 값이 치솟은 상태로",tip:"buy at panic prices / sell in a panic. 시장 심리를 한 단어로 표현합니다."},
          {t:"everyone who waited exactly as long as we did",k:"grammar",m:"우리만큼 딱 그만큼 기다린 모든 사람",tip:"as long as + 주어 + did 구조입니다. 끝의 did가 waited의 반복을 대신합니다."}]},
  {s:"B",en:"That argument holds water. I just don't want us dressing up a cost as strategy in a deck that somebody quotes back at us later.",
   ko:"그 논리는 설득력이 있네요. 다만 나중에 누가 그대로 되읊을 장표에서 비용을 전략인 척 포장하는 건 원치 않습니다.",
   notes:[{t:"hold water",k:"idiom",m:"(논리가) 말이 되다, 설득력이 있다",tip:"That doesn't hold water. 부정문으로 훨씬 자주 씁니다."},
          {t:"dress up A as B",k:"idiom",m:"A를 B인 것처럼 포장하다",tip:"8일차에도 나온 표현입니다. 비판할 때 반복해서 쓰게 됩니다."},
          {t:"a deck somebody quotes back at us",k:"grammar",m:"누군가 나중에 그대로 들이밀 장표",tip:"quote it back at someone = 남의 말을 그대로 인용해 되받다. 회의에서 흔한 위험입니다."}]},
  {s:"A",en:"Then let's be blunt about it. Part of this spend is compliance we can't avoid, and part is positioning we're choosing to buy.",
   ko:"그럼 솔직하게 말하죠. 이 지출의 일부는 피할 수 없는 규제 대응이고, 일부는 우리가 사기로 선택한 포지셔닝입니다.",
   notes:[{t:"be blunt about it",k:"idiom",m:"에두르지 않고 솔직히 말하다",tip:"Let me be blunt. 로 문장을 열면 '돌직구 갑니다'라는 신호가 됩니다."},
          {t:"compliance we can't avoid / positioning we're choosing to buy",k:"grammar",m:"피할 수 없는 규제 대응 / 사기로 선택한 포지셔닝",tip:"같은 접촉절 구조로 두 항목을 나눴습니다. 예산을 정직하게 쪼개 보이는 화법입니다."}]},
  {s:"B",en:"I can sell that. What I can't sell is a green premium with nothing behind it except a logo and a promise.",
   ko:"그건 팔 수 있어요. 못 파는 건 로고와 약속 말고는 뒷받침이 없는 친환경 프리미엄입니다.",
   notes:[{t:"I can sell that.",k:"idiom",m:"그 정도면 (고객·윗선을) 설득할 수 있습니다",tip:"sell = 설득하다. sell it upstairs / sell it internally 로 확장됩니다."},
          {t:"What I can't sell is ~",k:"grammar",m:"내가 못 파는 것은 ~이다",tip:"what절을 주어로 세운 강조구문입니다. 앞 문장과 대구를 이루며 조건을 분명히 합니다."},
          {t:"with nothing behind it",k:"colloquial",m:"뒷받침할 근거가 없는",tip:"a promise with nothing behind it. 실체 없음을 지적하는 짧은 꼬리표입니다."}]},
  {s:"A",en:"Nobody's asking you to. The premium only sticks if the verified data behind it survives the first customer who audits us.",
   ko:"아무도 그러라고 안 합니다. 프리미엄은 우리를 감사하는 첫 고객 앞에서 그 데이터가 버텨야만 유지돼요.",
   notes:[{t:"stick",k:"idiom",m:"(가격·주장이) 자리를 잡고 유지되다",tip:"The price increase didn't stick. 올렸다가 도로 내렸다는 뜻이 됩니다."},
          {t:"survives the first customer who audits us",k:"grammar",m:"우리를 감사하는 첫 고객 앞에서 버티다",tip:"survive를 '견뎌 내다'로 쓰는 용법입니다. 뒤에 사람이 목적어로 올 수 있다는 점이 포인트입니다."}]},
  {s:"B",en:"Then get me the data early enough to write it into next year's contracts, because after signing it becomes somebody else's problem.",
   ko:"그럼 내년 계약서에 넣을 수 있을 만큼 일찍 데이터를 주세요. 서명하고 나면 그건 다른 사람 문제가 되니까요.",
   notes:[{t:"early enough to ~",k:"grammar",m:"~할 수 있을 만큼 충분히 일찍",tip:"형용사 + enough to 구조. 마감을 압박할 때 부드럽지만 분명합니다."},
          {t:"write it into ~",k:"phrasal",m:"~에 조항으로 넣다",tip:"write it into the contract / into the spec. 구두 합의를 문서로 못 박는다는 뜻."}]},
  {s:"A",en:"Deal. And we should hedge by locking in the low-emission route for the accounts whose own targets depend on ours.",
   ko:"좋습니다. 그리고 자기네 목표가 우리 것에 걸려 있는 거래처부터 저배출 공정을 확보해 두는 식으로 헤지하죠.",
   notes:[{t:"hedge",k:"business",m:"위험을 나눠 걸다",tip:"hedge our bets = 한쪽에 다 걸지 않다. 전략 회의의 필수 동사입니다."},
          {t:"lock in ~",k:"phrasal",m:"~을 미리 확정해 두다",tip:"lock in the price / the capacity. 나중에 바뀌지 않게 묶어 둔다는 뜻입니다."},
          {t:"accounts whose own targets depend on ours",k:"grammar",m:"자기네 목표가 우리 것에 달린 거래처",tip:"소유격 관계대명사 whose로 이해관계의 사슬을 한 문장에 담았습니다."}]},
  {s:"B",en:"That works. Bite the bullet where it counts, and let the rest follow the market once somebody else has paid for the learning.",
   ko:"괜찮네요. 중요한 데서는 감수하고, 나머지는 누가 학습 비용을 대신 치른 뒤에 시장을 따라가게 두죠.",
   notes:[{t:"bite the bullet",k:"idiom",m:"싫지만 감수하고 실행하다",tip:"We had to bite the bullet and raise prices. 통째로 외우는 표현입니다."},
          {t:"where it counts",k:"idiom",m:"정말 중요한 곳에서는",tip:"Spend where it counts. 선택과 집중을 한마디로 표현합니다."},
          {t:"pay for the learning",k:"collocation",m:"시행착오 비용을 치르다",tip:"먼저 움직인 쪽이 치르는 값을 뜻합니다. learning curve와 함께 알아 두세요."}]}
 ],
 keys:[
  {en:"pass the cost through",ko:"비용을 가격에 전가하다",ex:"We can't pass the whole increase through to buyers."},
  {en:"a level playing field",ko:"공정한 경쟁 조건",ex:"Importers want a level playing field, not a subsidy."},
  {en:"hold water",ko:"(논리가) 설득력이 있다",ex:"That explanation doesn't hold water."},
  {en:"In theory. In practice, ~",ko:"이론상은 그렇고, 현실은 ~",ex:"In theory it's automated. In practice, someone still checks it."},
  {en:"hedge our bets",ko:"한쪽에 다 걸지 않다",ex:"Let's hedge our bets and qualify a second supplier."},
  {en:"lock in ~",ko:"~을 미리 확정해 두다",ex:"We locked in the freight rate for two years."},
  {en:"bite the bullet",ko:"싫지만 감수하고 실행하다",ex:"At some point we bite the bullet and replace the line."},
  {en:"That's a big assumption.",ko:"그건 큰 가정입니다",ex:"That's a big assumption — demand could fall instead."}
 ],
 out:[
  {q:"Explain to a customer why your product costs more this year, without sounding defensive.",hint:"pass the cost through / verified / a level playing field"},
  {q:"Argue for moving first on an expensive change, then argue for waiting.",hint:"move first / hedge our bets / that's a big assumption"},
  {q:"Someone calls your environmental spending a marketing exercise. Answer them honestly.",hint:"be blunt about it / part is A, part is B / with nothing behind it"}
 ]
},
{
 id:"w2d3", day:10, cat:"인구·노동", level:"B2+",
 title:"The Shift Nobody Can Fill",
 titleKo:"채울 수 없는 교대조 — 고령화와 현장의 기술 전수",
 names:{A:"Ines (인사)", B:"Karl (제조 현장 반장)"},
 brief:[
  "숙련 인력의 은퇴는 인원 문제로 보이지만 실제로는 <b>지식 문제</b>다. 사람이 나가면 자리는 채울 수 있어도, 그 사람 머릿속에만 있던 판단은 함께 나간다. 이것을 <b>암묵지(tacit knowledge)</b>라고 부른다.",
  "암묵지가 어려운 이유는 <b>말로 옮겨지지 않기 때문</b>이다. 소리로 이상을 알아채고, 손끝으로 온도를 가늠하는 판단은 매뉴얼에 담기지 않는다. 그래서 전수는 문서가 아니라 <b>같이 서 있는 시간</b>으로만 일어난다.",
  "현장이 이 문제를 미루는 방식은 대개 <b>초과근무</b>다. 당장은 돌아가지만 격차를 감출 뿐 좁히지는 못한다. 이런 임시 대응을 <b>stopgap</b>이라 하고, 반복되면 은퇴가 몰리는 시점에 한꺼번에 터진다.",
  "자동화는 이 문제의 해답이면서 동시에 함정이다. 기계가 공정을 대신해도 <b>결과가 이상할 때 알아채는 판단</b>은 사람에게 남는다. 그래서 채용과 훈련의 기준이 「손」에서 「판단」으로 옮겨 간다."
 ],
 lines:[
  {s:"A",en:"Three of your senior operators retire within a year, and we have nobody shadowing them who could take a shift alone tomorrow.",
   ko:"반장님 쪽 숙련 오퍼레이터 세 분이 1년 안에 은퇴하는데, 내일 혼자 교대를 설 수 있을 만큼 붙어 배우는 사람이 없어요.",
   notes:[{t:"shadow (someone)",k:"business",m:"옆에 붙어 따라다니며 배우다",tip:"job shadowing = 현장 밀착 학습. 명사로도 동사로도 씁니다."},
          {t:"nobody shadowing them who could ~",k:"grammar",m:"~할 수 있을 만큼 붙어 배우는 사람이 아무도 없다",tip:"현재분사와 관계절이 같은 명사에 이어 붙었습니다. 조건을 겹쳐 놓아 부족함을 정확히 규정합니다."}]},
  {s:"B",en:"You can't shadow forty years of feel in twelve months, and anyone who tells you otherwise has never stood on the floor.",
   ko:"40년 몸에 밴 감각을 열두 달 붙어서 배울 순 없어요. 된다고 말하는 사람은 현장에 서 본 적이 없는 겁니다.",
   notes:[{t:"feel",k:"colloquial",m:"(설명 못 하는) 감각, 손맛",tip:"He has a feel for the machine. 명사로 쓰면 경험에서 온 직관을 뜻합니다."},
          {t:"anyone who tells you otherwise",k:"grammar",m:"그렇지 않다고 말하는 사람은 누구든",tip:"otherwise = 그와 다르게. 반박을 미리 봉쇄하는 정형 표현입니다."},
          {t:"the floor",k:"business",m:"(공장의) 현장",tip:"on the shop floor = 생산 현장에서. 사무실과 대비되는 말입니다."}]},
  {s:"A",en:"I know. But if we do nothing, that knowledge walks out the door with them and there's no version of it left behind.",
   ko:"압니다. 그런데 아무것도 안 하면 그 지식이 그분들과 함께 걸어 나가고, 남는 판본은 하나도 없어요.",
   notes:[{t:"walk out the door",k:"idiom",m:"(사람과 함께 지식·고객이) 빠져나가다",tip:"Our best accounts walked out the door with him. 퇴사 리스크를 말할 때의 정석입니다."},
          {t:"there's no version of it left behind",k:"grammar",m:"남겨진 판본이 하나도 없다",tip:"과거분사 left가 명사를 뒤에서 꾸밉니다. leave behind = 남겨 두다."}]},
  {s:"B",en:"It already is. We papered over the last two retirements with overtime and luck, neither of which is a plan I'd write down.",
   ko:"이미 그러고 있어요. 지난 두 번의 은퇴는 초과근무와 운으로 덮었는데, 둘 다 제가 문서로 쓸 만한 계획은 아니죠.",
   notes:[{t:"paper over ~",k:"phrasal",m:"~을 임시로 덮어 감추다",tip:"paper over the cracks = 균열을 벽지로 덮다. 근본 해결이 아님을 지적합니다."},
          {t:", neither of which ~",k:"grammar",m:"그런데 그 둘 다 ~이 아니다",tip:"수량사 + of which의 계속적 용법입니다. 앞의 두 항목을 한 번에 묶어 평가할 때 씁니다."}]},
  {s:"A",en:"Overtime is a stopgap. It hides the gap from anyone reading the report instead of closing it on the floor.",
   ko:"초과근무는 임시방편이에요. 현장에서 격차를 좁히는 게 아니라, 보고서 읽는 사람 눈에서 가리는 거죠.",
   notes:[{t:"a stopgap",k:"business",m:"임시방편, 땜질 처방",tip:"a stopgap measure / a stopgap solution. band-aid solution과 같은 뜻입니다."},
          {t:"close the gap",k:"collocation",m:"격차를 좁히다",tip:"close/narrow/widen the gap 세트로 외우세요. 실적 보고에 매일 나옵니다."},
          {t:"hide A from B instead of -ing",k:"grammar",m:"~하는 대신 A를 B에게서 감추다",tip:"전치사 from과 instead of가 한 문장에 들어갔습니다. 두 행위를 대비시키는 구조입니다."}]},
  {s:"B",en:"Then give me apprentices who stay. The last three picked it up quickly and left for shifts that didn't start at five in the morning.",
   ko:"그럼 남아 있을 견습생을 주세요. 지난 세 명은 빨리 익히고는 새벽 다섯 시에 시작하지 않는 교대조로 떠났어요.",
   notes:[{t:"pick it up",k:"phrasal",m:"(기술을) 어깨너머로 익히다",tip:"He picked it up on the job. 정식 교육 없이 배웠다는 뜻으로 아주 자주 씁니다."},
          {t:"shifts that didn't start at five",k:"grammar",m:"새벽 다섯 시에 시작하지 않는 교대조",tip:"관계절로 이직 사유를 구체적으로 밝혔습니다. 불평을 사실로 바꾸는 화법입니다."}]},
  {s:"A",en:"That's a retention problem, and I'll own it. But pay alone won't fix a pipeline that has been thin for five years.",
   ko:"그건 잔류 문제고, 제가 책임지겠습니다. 그런데 5년째 얇은 인력 파이프라인이 급여만으로 고쳐지진 않아요.",
   notes:[{t:"retention",k:"business",m:"(직원) 잔류·유지",tip:"retention rate / a retention problem. 반대는 turnover(이직률)입니다."},
          {t:"a pipeline that has been thin for five years",k:"grammar",m:"5년째 얇았던 파이프라인",tip:"현재완료 관계절이 '지금까지 계속'을 표시합니다. 문제의 만성을 문법으로 드러냅니다."}]},
  {s:"B",en:"Money helps more than you think when the work is hot, loud, and scheduled at hours that make a family life awkward.",
   ko:"덥고 시끄럽고 가정생활이 어려워지는 시간대에 배치되는 일이라면, 돈이 생각보다 훨씬 큽니다.",
   notes:[{t:"more than you think",k:"colloquial",m:"생각하시는 것보다 더",tip:"문장 뒤에 붙이는 짧은 강조. It matters more than you think."},
          {t:"hours that make a family life awkward",k:"grammar",m:"가정생활을 곤란하게 만드는 시간대",tip:"make + 목적어 + 형용사 구조가 관계절 안에 들어갔습니다. 교대 근무의 부담을 구체화합니다."}]},
  {s:"A",en:"It does, up to a point. Past that, people leave because nobody ever taught them properly and they got tired of guessing.",
   ko:"어느 선까지는 그렇죠. 그 선을 넘으면, 제대로 가르쳐 준 사람이 없어서 짐작하는 데 지쳐 떠납니다.",
   notes:[{t:"up to a point",k:"idiom",m:"어느 정도까지는",tip:"부분 동의의 대표 표현입니다. I agree, up to a point."},
          {t:"get tired of -ing",k:"grammar",m:"~하는 데 지치다",tip:"of 뒤라 동명사입니다. get tired of waiting / of explaining."}]},
  {s:"B",en:"Fair. Half of what I know I picked up watching a man who never once explained why he did anything.",
   ko:"인정합니다. 제가 아는 것의 절반은, 왜 그렇게 하는지 한 번도 설명해 준 적 없는 사람을 보면서 익힌 거예요.",
   notes:[{t:"Half of what I know",k:"grammar",m:"내가 아는 것의 절반",tip:"what절을 목적어로 쓰는 구조. 회화에서 문장을 길고 자연스럽게 늘려 줍니다."},
          {t:"a man who never once explained ~",k:"grammar",m:"한 번도 설명해 준 적 없는 사람",tip:"never once는 '단 한 번도'라는 강조입니다. 관계절 안에서 원망을 담담하게 실어 줍니다."}]},
  {s:"A",en:"That's exactly the problem — tacit knowledge that nobody ever wrote down because writing it down was never anyone's job.",
   ko:"바로 그게 문제예요. 아무도 적어 두지 않은 암묵지죠. 적어 두는 게 누구의 일도 아니었으니까요.",
   notes:[{t:"tacit knowledge",k:"business",m:"암묵지, 말로 옮기지 못한 지식",tip:"explicit knowledge(형식지)와 짝입니다. 지식경영의 기본 용어입니다."},
          {t:"That's exactly the problem.",k:"colloquial",m:"바로 그게 문제입니다",tip:"상대의 말을 받아 내 논점으로 끌어오는 전환 문장입니다."},
          {t:"because -ing was never anyone's job",k:"grammar",m:"~하는 것이 누구의 업무도 아니었기 때문에",tip:"동명사를 주어로 세웠습니다. 책임의 공백을 지적하는 조직 화법입니다."}]},
  {s:"B",en:"Some of it can't be written down. You feel a bad weld through the handle before anything shows up on a screen.",
   ko:"그중 일부는 적을 수가 없어요. 화면에 뭐가 뜨기 전에 손잡이로 불량 용접이 느껴지거든요.",
   notes:[{t:"before anything shows up on a screen",k:"grammar",m:"화면에 뭐가 뜨기도 전에",tip:"감각이 계측을 앞선다는 뜻을 시간 접속사로 표현했습니다. 현장 설명에 잘 어울립니다."}]},
  {s:"A",en:"Agreed, but the other half can. Let's capture what's teachable and stop pretending that everything a veteran knows is art.",
   ko:"동의해요. 그런데 나머지 절반은 가능합니다. 가르칠 수 있는 건 담아 두고, 숙련자가 아는 게 전부 예술인 척은 그만두죠.",
   notes:[{t:"capture",k:"business",m:"(지식을) 붙잡아 기록으로 남기다",tip:"capture the process / capture lessons learned. 문서화를 뜻하는 세련된 동사입니다."},
          {t:"what's teachable",k:"grammar",m:"가르칠 수 있는 것",tip:"what절이 목적어가 됐습니다. -able 형용사를 붙이면 범위를 정확히 자를 수 있습니다."},
          {t:"stop pretending that ~",k:"colloquial",m:"~인 척하는 걸 그만두다",tip:"직설적이지만 무례하지 않은 압박. Let's stop pretending this is temporary."}]},
  {s:"B",en:"Fine. Give me protected time on the schedule for it, not another folder that nobody opens after the first week.",
   ko:"좋아요. 그럼 일정에 보호된 시간을 주세요. 첫 주 지나면 아무도 안 여는 폴더 하나 더 말고요.",
   notes:[{t:"another folder that nobody opens",k:"grammar",m:"아무도 열지 않는 문서 하나 더",tip:"형식적 산출물을 비꼬는 관용적 표현. 관계절이 냉소를 담는 자리입니다."},
          {t:"protected time",k:"business",m:"(다른 일에 뺏기지 않는) 확보된 시간",tip:"protected hours라고도 합니다. 교육·개선활동 예산을 지킬 때 쓰는 말입니다."}]},
  {s:"A",en:"You'll get it. In exchange, I want each of the seniors paired with two juniors whose names go on the schedule with theirs.",
   ko:"드리겠습니다. 대신 숙련자마다 후배 둘씩 짝지어 주시고, 그 이름들이 일정표에 같이 올라가야 합니다.",
   notes:[{t:"In exchange, ~",k:"business",m:"그 대신에",tip:"조건부 합의를 만드는 연결어. 협상에서 주고받기를 명시할 때 씁니다."},
          {t:"juniors whose names go on the schedule",k:"grammar",m:"이름이 일정표에 오르는 후배들",tip:"소유격 관계대명사 whose입니다. 약속을 문서에 묶는다는 뜻을 문법으로 표현했습니다."}]},
  {s:"B",en:"Two is a lot. One learns while the other watches the first one make the mistakes that nobody wants repeated.",
   ko:"둘은 많아요. 하나는 배우고, 다른 하나는 첫째가 아무도 반복되길 원치 않는 실수를 하는 걸 구경하게 됩니다.",
   notes:[{t:"watch someone do ~",k:"grammar",m:"~가 …하는 것을 지켜보다",tip:"지각동사 뒤 원형부정사. watch him make / see her leave. 한국인이 자주 틀리는 곳입니다."},
          {t:"mistakes that nobody wants repeated",k:"grammar",m:"아무도 반복되길 원치 않는 실수",tip:"want + 목적어 + 과거분사 구조입니다. want them to be repeated를 줄인 형태로 보면 쉽습니다."}]},
  {s:"A",en:"That's still learning, and it gives us a backup for the day one of them moves on without much notice.",
   ko:"그것도 배움이고, 둘 중 하나가 별 예고 없이 떠나는 날을 대비한 여유가 생기죠.",
   notes:[{t:"move on",k:"phrasal",m:"(회사를) 떠나다, 다음 자리로 가다",tip:"leave보다 완곡합니다. She moved on last spring. 퇴사를 부드럽게 말할 때."},
          {t:"the day one of them moves on",k:"grammar",m:"그중 하나가 떠나는 그날",tip:"시간 명사 뒤 관계부사 when이 생략된 접촉절입니다. 현재시제가 미래의 그날을 가리킵니다."}]},
  {s:"B",en:"The writing's on the wall anyway. Automation will take some of these stations, probably the ones we've just agreed to train for.",
   ko:"어차피 흐름은 뻔합니다. 자동화가 이 공정 자리 몇 개는 가져갈 텐데, 하필 우리가 방금 훈련하기로 한 자리들이겠죠.",
   notes:[{t:"The writing's on the wall.",k:"idiom",m:"흐름은 이미 정해져 있다",tip:"피할 수 없는 변화를 뜻합니다. 다소 비관적인 어감이라 자리를 가려 씁니다."},
          {t:"the ones we've just agreed to train for",k:"grammar",m:"우리가 방금 훈련하기로 합의한 그 자리들",tip:"the ones that ~ 으로 앞 명사를 받고 문미에 for가 남습니다. 아이러니를 얹는 자리입니다."}]},
  {s:"A",en:"Some, not all. The machines still need somebody who knows when the output looks wrong before the alarm decides it is.",
   ko:"일부지 전부는 아니에요. 기계도 경보가 울리기 전에 결과가 이상하다는 걸 아는 사람이 여전히 필요합니다.",
   notes:[{t:"Some, not all.",k:"colloquial",m:"일부지 전부는 아닙니다",tip:"두 단어로 과장을 잘라내는 반박. 토론에서 아주 경제적인 문장입니다."},
          {t:"knows when the output looks wrong",k:"grammar",m:"결과가 이상해 보이는 때를 알다",tip:"know 뒤의 when절은 간접의문문이라 주어+동사 어순입니다. 판단력을 정의하는 문장입니다."}]},
  {s:"B",en:"Then let's train for that judgment and stop hiring for a pair of hands that the next machine will make unnecessary.",
   ko:"그럼 그 판단력을 겨냥해 훈련하고, 다음 기계가 필요 없게 만들 손 한 쌍을 뽑는 건 그만두죠.",
   notes:[{t:"train for ~",k:"collocation",m:"~을 겨냥해 훈련하다",tip:"train for judgment / hire for attitude. 목표를 명시하는 전치사 for를 씁니다."},
          {t:"hands that the next machine will make unnecessary",k:"grammar",m:"다음 기계가 필요 없게 만들 손",tip:"make + 목적어 + 형용사가 관계절 안에 들어갔습니다. 목적어가 앞으로 빠져 hands가 됐습니다."}]}
 ],
 keys:[
  {en:"walk out the door",ko:"(사람과 함께 지식이) 빠져나가다",ex:"When he retires, thirty years walk out the door."},
  {en:"paper over the cracks",ko:"근본 문제를 임시로 덮다",ex:"Hiring temps just papers over the cracks."},
  {en:"a stopgap",ko:"임시방편, 땜질 처방",ex:"Overtime is a stopgap, not a plan."},
  {en:"pick it up on the job",ko:"일하면서 어깨너머로 익히다",ex:"Nobody trained me; I picked it up on the job."},
  {en:"tacit knowledge",ko:"암묵지, 말로 옮기지 못한 지식",ex:"Most of our tacit knowledge sits with five people."},
  {en:"up to a point",ko:"어느 정도까지는",ex:"I agree, up to a point — but not on cost."},
  {en:"move on",ko:"(회사를) 떠나다",ex:"Two of the juniors moved on within a year."},
  {en:"The writing's on the wall.",ko:"흐름은 이미 정해져 있다",ex:"The writing's on the wall for manual inspection."}
 ],
 out:[
  {q:"Describe one thing you learned at work that nobody could have written in a manual.",hint:"tacit knowledge / pick it up on the job / feel"},
  {q:"Your team lost an experienced colleague. Explain what actually left with them.",hint:"walk out the door / paper over the cracks / a stopgap"},
  {q:"Argue that automation makes training more important, not less.",hint:"train for judgment / some, not all / up to a point"}
 ]
},
{
 id:"w2d4", day:11, cat:"협상·계약", level:"B2+",
 title:"The Price Is Not the Price",
 titleKo:"가격은 가격이 아니다 — 장기계약의 조정 조항과 원가 전가",
 names:{A:"Marta (계약·법무)", B:"Joon (수출영업)"},
 brief:[
  "장기 공급계약에서 표지에 적힌 가격은 실제로 받는 값이 아니다. 몇 년을 묶는 계약에서 원가만 움직이고 값이 고정되어 있으면 한쪽이 반드시 무너진다. 그래서 원가가 움직이면 값도 따라 움직이도록 <b>가격 조정 조항(escalation clause)</b>을 넣어 둔다.",
  "조정의 기준은 대개 공개된 지수다 — <b>지수 연동(index-linked)</b>. 양쪽이 임의로 다투지 않아도 되니 깔끔해 보이지만, 지수는 현실을 몇 주 늦게 반영한다. 그 <b>시차(lag)</b> 동안 벌어진 손실은 계약서에 적힌 대로 누군가가 <b>떠안는다(eat the cost)</b>.",
  "그래서 위험을 나누는 장치가 붙는다. 값이 오를 때의 상한이 <b>cap</b>, 상한과 하한을 함께 두는 것이 <b>collar</b>다. 상한만 주고 하한을 못 받으면 오를 때의 부담은 우리가 지고 내릴 때의 이익은 상대가 가져간다 — 흔히 놓치는 자리다.",
  "물량 쪽의 장치는 <b>take-or-pay</b>다. 안 가져가도 약정한 값은 낸다. 설비 투자를 회수하려면 필요하지만 수요가 꺾이면 분쟁의 씨앗이 된다. 그래서 실무에서는 물량을 조금 풀어 주고 분기마다 차액을 맞추는 <b>정산(true-up)</b>으로 절충한다."
 ],
 lines:[
  {s:"A",en:"Before you sign a three-year supply deal, walk me through what happens to that price when energy costs move against us.",
   ko:"3년짜리 공급계약에 서명하기 전에, 에너지 값이 우리한테 불리하게 움직일 때 그 가격이 어떻게 되는지부터 짚어 주세요.",
   notes:[{t:"walk someone through ~",k:"phrasal",m:"~을 처음부터 차근차근 설명해 주다",tip:"explain보다 훨씬 실무적입니다. Walk me through the numbers. 회의에서 자료 설명을 청할 때의 정석."},
          {t:"move against someone",k:"idiom",m:"(시세·비용이) ~에게 불리하게 움직이다",tip:"The exchange rate moved against us. 반대는 move in our favour."}]},
  {s:"B",en:"It's index-linked, so the quarterly average feeds straight into the invoice and neither of us eats the whole swing alone.",
   ko:"지수 연동입니다. 분기 평균이 곧바로 청구서에 반영되니까 변동분을 어느 한쪽이 통째로 떠안지는 않아요.",
   notes:[{t:"index-linked",k:"business",m:"공개 지수에 연동된",tip:"index-linked pricing = 지수 연동 가격. 계약서에서 통째로 한 덩어리로 씁니다."},
          {t:"eat (a cost)",k:"colloquial",m:"(손실·비용을) 떠안다",tip:"We'll eat the freight this time. 한국인이 잘 안 쓰지만 원어민은 매우 자주 씁니다."},
          {t:"swing",k:"collocation",m:"(값의) 급한 오르내림",tip:"a price swing / a swing in demand 로 붙습니다."}]},
  {s:"A",en:"Index-linked sounds tidy on paper, but the index lags reality by weeks, and somebody carries the loss during that gap.",
   ko:"지수 연동은 서류상으로는 깔끔해 보이죠. 그런데 지수는 현실을 몇 주 늦게 따라오고, 그 틈의 손실은 누군가 집니다.",
   notes:[{t:"on paper",k:"idiom",m:"서류상으로는 (실제와 다를 수 있다는 뉘앙스)",tip:"It works on paper. 뒤에 but이 따라오는 것이 거의 공식입니다."},
          {t:"lag",k:"business",m:"뒤늦게 따라가다, 시차를 두다",tip:"동사와 명사 둘 다. with a lag = 시차를 두고."}]},
  {s:"B",en:"Fair enough, but a lagging index still beats a fixed price that goes underwater the moment the market turns on us.",
   ko:"일리 있습니다. 그래도 늦게 따라오는 지수가, 시장이 등을 돌리는 순간 물에 잠기는 고정가보다는 낫죠.",
   notes:[{t:"Fair enough, but ~",k:"idiom",m:"그 말도 일리는 있는데, 다만 ~",tip:"상대를 인정하고 반박으로 넘어가는 다리. 토론 필수 표현입니다."},
          {t:"go underwater",k:"idiom",m:"(계약·자산이) 손실 구간에 빠지다",tip:"원래 대출이 담보가치를 넘긴 상태를 뜻하다가 널리 쓰이게 됐습니다."},
          {t:"turn on someone",k:"phrasal",m:"~에게 등을 돌리다, 불리하게 돌아서다",tip:"turn to(의지하다)와 헷갈리지 마세요. 뜻이 정반대입니다."}]},
  {s:"A",en:"Agreed. My real worry is the cap — you've given them a ceiling with no floor, which hands over the upside for free.",
   ko:"동의합니다. 진짜 걱정은 상한이에요. 천장은 주고 바닥은 못 받았는데, 그건 내려갈 때의 이익을 공짜로 넘긴 겁니다.",
   notes:[{t:"a ceiling with no floor",k:"business",m:"상한만 있고 하한은 없는 (구조)",tip:"price ceiling / price floor. 계약 협상에서 통째로 외워 두면 바로 씁니다."},
          {t:"the upside",k:"business",m:"유리하게 풀렸을 때의 이익",tip:"반대는 the downside. share the upside = 이익을 나누다."}]},
  {s:"B",en:"The ceiling is what got the deal done. Their procurement team wouldn't budge without some certainty on the worst case.",
   ko:"그 천장이 있어서 계약이 성사된 겁니다. 상대 구매팀은 최악의 경우에 대한 확실성 없이는 꿈쩍도 안 했어요.",
   notes:[{t:"get the deal done",k:"collocation",m:"계약을 성사시키다",tip:"close the deal도 같은 뜻입니다. get ~ done 은 「어떻게든 끝냈다」는 뉘앙스."},
          {t:"budge",k:"colloquial",m:"(입장을) 조금이라도 움직이다",tip:"거의 부정문으로만 씁니다. wouldn't budge = 요지부동이었다."}]},
  {s:"A",en:"Then ask for a collar. A floor alongside that ceiling costs them nothing today and protects us when prices crater.",
   ko:"그럼 collar를 요구하세요. 천장 옆에 바닥을 하나 두는 건 오늘 상대에게 비용이 안 들고, 값이 폭락할 때 우리를 지켜 줍니다.",
   notes:[{t:"a collar",k:"business",m:"상한과 하한을 함께 두는 구조",tip:"a cap and a collar 로 짝지어 외우세요. 금융·구매 계약에서 그대로 씁니다."},
          {t:"crater",k:"colloquial",m:"(값이) 곤두박질치다",tip:"drop보다 훨씬 극적입니다. Sales cratered after the recall."}]},
  {s:"B",en:"I can table that, though reopening price this late tends to unravel the parts we already nailed down.",
   ko:"안건으로 올릴 수는 있어요. 다만 이 시점에 가격을 다시 여는 건 이미 못 박아 둔 부분까지 풀어 버리기 십상입니다.",
   notes:[{t:"table (something)",k:"business",m:"안건으로 올리다",tip:"미국식으로는 「보류하다」라는 정반대 뜻도 됩니다. 상대가 미국인이면 put it on the agenda 로 말하는 편이 안전합니다."},
          {t:"unravel",k:"idiom",m:"(합의가) 실밥 풀리듯 무너지다",tip:"The deal unravelled over one clause. 협상이 깨지는 과정을 묘사하는 정석 동사."},
          {t:"nail down",k:"phrasal",m:"확정 짓다, 못 박다",tip:"nail down the date / the scope. 구어에서 대단히 자주 씁니다."}]},
  {s:"A",en:"Better to unravel it now than to litigate it in year two, when the numbers are real and nobody is friendly.",
   ko:"지금 풀어지는 게, 숫자가 진짜가 되고 아무도 우호적이지 않은 2년 차에 소송으로 가는 것보다 낫습니다.",
   notes:[{t:"Better to A than to B",k:"grammar",m:"B 하느니 A 하는 편이 낫다",tip:"It is 를 생략한 구어체입니다. 회의에서 결단을 촉구할 때 매우 자주 나옵니다."},
          {t:"litigate",k:"business",m:"소송으로 다투다",tip:"명사는 litigation. go to court 보다 격식 있는 말입니다."}]},
  {s:"B",en:"Point taken. What about volume? They pushed take-or-pay hard, and I held out until they settled for something softer.",
   ko:"인정합니다. 물량은요? 상대가 take-or-pay를 강하게 밀었는데, 제가 버텨서 좀 더 무른 조건으로 합의했어요.",
   notes:[{t:"Point taken.",k:"idiom",m:"지적 인정합니다.",tip:"짧게 인정하고 다음 주제로 넘어가는 말. You're right 보다 어른스럽게 들립니다."},
          {t:"hold out",k:"phrasal",m:"양보하지 않고 버티다",tip:"hold out for a better price = 더 좋은 값을 받으려 버티다."},
          {t:"settle for ~",k:"phrasal",m:"(원하던 것보다 못한) ~으로 타협하다",tip:"settle on(결정하다)과 다릅니다. for 는 아쉬움이 섞입니다."}]},
  {s:"A",en:"How soft? Take-or-pay is how we recover the line investment, and a soft commitment recovers nothing if demand dries up.",
   ko:"얼마나 무르게요? take-or-pay는 우리가 설비 투자를 회수하는 방법인데, 무른 약정은 수요가 마르면 아무것도 회수하지 못합니다.",
   notes:[{t:"take-or-pay",k:"business",m:"가져가지 않아도 값은 내는 약정",tip:"에너지·원자재 장기계약의 기본 장치입니다. 하이픈까지 한 덩어리로 씁니다."},
          {t:"dry up",k:"phrasal",m:"(수요·자금이) 말라붙다",tip:"Orders dried up overnight. 서서히 사라지는 것이 아니라 끊기는 느낌입니다."}]},
  {s:"B",en:"Eighty percent of nominated tonnage, with a quarterly true-up. Anything harder and they'd have walked to a competitor.",
   ko:"지정 물량의 80퍼센트에 분기 정산을 붙였습니다. 그보다 세게 갔으면 경쟁사로 넘어갔을 겁니다.",
   notes:[{t:"nominated tonnage",k:"business",m:"사전에 지정해 통보한 물량",tip:"nominate = 물량을 지정·통보하다. 해운·원자재 계약의 표준 용어입니다."},
          {t:"a true-up",k:"business",m:"차액 정산",tip:"동사로도 씁니다 — true up the numbers at quarter end."},
          {t:"walk (to a competitor)",k:"colloquial",m:"(협상장을 떠나) 다른 데로 가 버리다",tip:"walk away from the table = 협상을 깨고 나가다."}]},
  {s:"A",en:"That's workable, provided the true-up nets against shortfalls instead of sitting there as a credit they never use.",
   ko:"그건 됩니다. 단, 정산이 부족분과 상계되어야지, 상대가 쓰지도 않을 크레딧으로 남아 있으면 안 됩니다.",
   notes:[{t:"provided (that) ~",k:"grammar",m:"~라는 조건이라면",tip:"if보다 조건을 못 박는 힘이 셉니다. 계약서와 회의 발언 양쪽에서 씁니다."},
          {t:"net against ~",k:"business",m:"~과 상계하다",tip:"net off 도 같은 뜻. 회계·정산 대화에서 반드시 나옵니다."}]},
  {s:"B",en:"Now you're the one reopening things. Let's write it plainly so neither side needs a lawyer to read the schedule.",
   ko:"이제는 계약을 다시 여는 쪽이 그쪽이네요. 어느 쪽도 부속서를 읽는 데 변호사가 필요 없도록 평이하게 씁시다.",
   notes:[{t:"you're the one ~ing",k:"grammar",m:"정작 ~하는 사람은 당신이다",tip:"가볍게 되받아치는 강조 구문입니다. 농담 섞인 반박에 잘 어울립니다."},
          {t:"the schedule",k:"business",m:"(계약의) 부속서·별표",tip:"일정이 아닙니다. Schedule 2 to the agreement 처럼 씁니다. 실무에서 자주 오해하는 단어."}]},
  {s:"A",en:"That's my whole job — writing it plainly. Most disputes I see aren't bad faith, they're two honest readings of one sentence.",
   ko:"그게 제 일 전부입니다, 평이하게 쓰는 것. 제가 보는 분쟁 대부분은 악의가 아니라 한 문장에 대한 정직한 두 가지 해석이에요.",
   notes:[{t:"bad faith",k:"business",m:"악의, 신의를 저버린 태도",tip:"반대는 in good faith = 선의로. 계약서에 그대로 등장하는 말입니다."},
          {t:"a reading (of)",k:"business",m:"(문구에 대한) 해석",tip:"interpretation의 구어형입니다. That's one reading of the clause."}]},
  {s:"B",en:"Then let's kill the force majeure boilerplate. It came off a template and it doesn't mention anything we actually face.",
   ko:"그럼 불가항력 조항의 정형 문구는 없앱시다. 템플릿에서 그대로 가져온 거라 우리가 실제로 맞닥뜨리는 건 하나도 안 들어 있어요.",
   notes:[{t:"boilerplate",k:"business",m:"관행적으로 복사되는 정형 문구",tip:"원래 인쇄판을 뜻하던 말입니다. 「읽지도 않고 넣는 조항」이라는 경멸이 섞입니다."},
          {t:"come off a template",k:"colloquial",m:"양식에서 그대로 가져오다",tip:"off 하나로 「출처」를 나타냅니다. It came off the shelf. 도 같은 구조."}]},
  {s:"A",en:"It has to stay, but I'll narrow it. A clause that excuses everything ends up excusing them, not us.",
   ko:"조항은 남아야 하지만 범위를 좁히겠습니다. 모든 것을 면책하는 조항은 결국 우리가 아니라 상대를 면책합니다.",
   notes:[{t:"narrow (a clause)",k:"business",m:"(조항의) 범위를 좁히다",tip:"반대는 broaden. 계약 협상에서 가장 많이 오가는 동사 쌍입니다."},
          {t:"end up ~ing",k:"grammar",m:"결국 ~하게 되다",tip:"의도하지 않은 결과에 씁니다. end up with + 명사 형태도 함께 외우세요."}]},
  {s:"B",en:"Fine. And the pass-through — I want it spelled out that verified cost increases flow through within one billing cycle.",
   ko:"좋습니다. 그리고 원가 전가 조항은, 확인된 원가 상승분이 한 번의 청구 주기 안에 반영된다고 명시해 주세요.",
   notes:[{t:"pass-through",k:"business",m:"원가를 값에 그대로 넘기는 것",tip:"명사는 하이픈, 동사는 pass through 로 띄웁니다. 청구서 대화의 필수어."},
          {t:"spell out",k:"phrasal",m:"오해 없게 낱낱이 명시하다",tip:"Spell it out for me. 는 「알아듣게 풀어 달라」는 뜻도 됩니다."}]},
  {s:"A",en:"That I can draft. Just don't promise them a formula you haven't run against the last three years of costs.",
   ko:"그건 제가 초안 잡겠습니다. 다만 지난 3년치 원가에 돌려 보지 않은 산식을 상대에게 약속하지는 마세요.",
   notes:[{t:"That I can draft.",k:"grammar",m:"그거라면 제가 쓸 수 있습니다",tip:"목적어를 앞으로 뺀 도치입니다. 앞말과 대비를 줄 때 원어민이 자주 씁니다."},
          {t:"run (numbers) against ~",k:"collocation",m:"~에 대입해 검증해 보다",tip:"run the model against last year's data. 데이터 검증의 정석 표현."}]},
  {s:"B",en:"I've run it. It holds up in every scenario except the one where energy and freight spike in the same quarter.",
   ko:"돌려 봤습니다. 에너지와 운임이 같은 분기에 함께 치솟는 경우만 빼면 모든 시나리오에서 버팁니다.",
   notes:[{t:"hold up",k:"phrasal",m:"(검증을) 버텨 내다, 유효하게 남다",tip:"The argument holds up. 지연시키다(hold up the line)라는 다른 뜻도 있으니 문맥으로 가르세요."},
          {t:"spike",k:"collocation",m:"급등하다",tip:"명사로도 씁니다 — a spike in freight rates."}]}
 ],
 keys:[
  {en:"index-linked",ko:"공개 지수에 연동된",ex:"The tariff is index-linked, so it resets each quarter without anyone renegotiating."},
  {en:"eat the cost",ko:"손실·비용을 떠안다",ex:"If the shipment misses the vessel, we eat the cost, not the customer."},
  {en:"a cap and a collar",ko:"상한, 그리고 상한과 하한을 함께 두는 구조",ex:"We took a cap on price and gave them a collar on volume."},
  {en:"take-or-pay",ko:"가져가지 않아도 값은 내는 약정",ex:"The contract is take-or-pay, so an idle plant still generates invoices."},
  {en:"a true-up",ko:"차액 정산",ex:"We bill on estimates monthly and do a true-up at the end of the quarter."},
  {en:"pass-through",ko:"원가를 값에 그대로 넘기는 것",ex:"The fuel surcharge is a straight pass-through to the buyer."},
  {en:"boilerplate",ko:"관행적으로 복사되는 정형 문구",ex:"Half the agreement is boilerplate that nobody has questioned in years."},
  {en:"unravel",ko:"(합의가) 풀려 무너지다",ex:"Reopening one clause can unravel a deal that took months to build."}
 ],
 out:[
  {q:"Explain why an index-linked price can still leave one side carrying a loss.",hint:"index-linked / lag / eat the cost"},
  {q:"Your counterpart offers a price ceiling but refuses a floor. Push back.",hint:"a cap and a collar / the upside / hands it over for free"},
  {q:"Argue that take-or-pay must stay in a long-term supply contract.",hint:"recover the line investment / nominated tonnage / a true-up"}
 ]
},
{
 id:"w2d5", day:12, cat:"안전·현장", level:"B2+",
 title:"The Accident That Was Waiting",
 titleKo:"예고되어 있던 사고 — 아차사고와 기준이 무너지는 방식",
 names:{A:"Dana (안전보건)", B:"Victor (생산 관리)"},
 brief:[
  "큰 사고는 어느 날 갑자기 오지 않는다. 그 앞에는 다치지 않고 지나간 <b>아차사고(near miss)</b>가 수없이 있다. 결과만 달랐을 뿐 원인은 같으므로, 아차사고는 값을 치르지 않고 얻는 교훈이다.",
  "기준은 한 번에 무너지지 않고 조금씩 밀린다. 급할 때 한 번 건너뛴 절차가 통하면 다음에도 건너뛰고, 예외가 반복되어 정상이 된다. 이것을 <b>일탈의 일상화(normalization of deviance)</b>라 부른다. 누구도 규칙을 어기기로 결심하지 않았는데 규칙이 사라져 있다.",
  "그래서 안전은 한 겹으로 설계하지 않는다. 방호장치, 절차, 점검, 교육을 <b>여러 겹으로 쌓아(layers of defence)</b> 한 겹에 난 구멍이 다른 겹에 막히게 한다. 사고는 구멍들이 한 줄로 늘어서는 드문 순간에 일어난다.",
  "지표는 둘로 나뉜다. 사고 건수처럼 이미 벌어진 뒤를 세는 <b>후행지표(lagging indicator)</b>와, 점검 이행률이나 아차사고 신고 건수처럼 앞을 내다보는 <b>선행지표(leading indicator)</b>다. 신고가 줄었다고 안전해진 것이 아니다 — 사람들이 말하기를 그만둔 것일 수도 있다."
 ],
 lines:[
  {s:"A",en:"Your line reported zero near misses last quarter, and that's the number in this whole report that worries me most.",
   ko:"그쪽 라인은 지난 분기 아차사고 신고가 0건이었는데, 이 보고서 전체에서 제일 걱정되는 숫자가 바로 그겁니다.",
   notes:[{t:"a near miss",k:"business",m:"아차사고 — 다치지 않고 지나간 사고",tip:"「거의 놓쳤다」가 아니라 「거의 사고였다」입니다. 한국인이 뜻을 반대로 잡기 쉬운 말."},
          {t:"the number that worries me most",k:"grammar",m:"가장 걱정스러운 그 숫자",tip:"관계절 + 최상급. 자료를 놓고 한 곳을 짚을 때의 정형입니다."}]},
  {s:"B",en:"Zero is good news. My people are careful, the guards are all in place, and nothing has gone wrong for months.",
   ko:"0건은 좋은 소식이죠. 우리 사람들은 조심하고, 방호장치도 다 제자리에 있고, 몇 달째 아무 일 없었습니다.",
   notes:[{t:"in place",k:"idiom",m:"제자리에 갖춰져 있는",tip:"have the controls in place = 통제 장치를 갖추다. 감사·점검 대화의 필수 표현."},
          {t:"go wrong",k:"phrasal",m:"잘못되다, 사고가 나다",tip:"What could go wrong? 은 반어로도 자주 씁니다."}]},
  {s:"A",en:"Or nothing got written down. Crews usually stop reporting because reporting once cost somebody a very uncomfortable conversation.",
   ko:"아니면 아무것도 기록되지 않은 거죠. 작업조가 신고를 그만두는 건 대개 한 번 신고했다가 누군가 아주 불편한 대화를 치렀기 때문입니다.",
   notes:[{t:"get written down",k:"grammar",m:"기록되다",tip:"get + 과거분사는 be동사보다 구어적이고 「어쩌다 그렇게 됐다」는 느낌을 줍니다."},
          {t:"cost somebody something",k:"collocation",m:"~에게 (대가를) 치르게 하다",tip:"It cost him his job. 돈이 아닌 대가에도 그대로 씁니다."}]},
  {s:"B",en:"That's a serious thing to imply about my shift. Give me one instance where I punished anyone for speaking up.",
   ko:"우리 교대조를 두고 하기엔 무거운 말입니다. 제가 문제를 말했다고 누굴 벌준 사례를 하나만 대 보세요.",
   notes:[{t:"imply",k:"business",m:"에둘러 시사하다",tip:"직접 말하지 않고 암시한다는 뜻. 반박할 때 What are you implying? 형태로 자주 나옵니다."},
          {t:"speak up",k:"phrasal",m:"(문제를) 소리 내어 말하다",tip:"speak up about safety. 목소리를 키우라는 뜻도 되니 문맥으로 가르세요."}]},
  {s:"A",en:"I'm not accusing you. Pressure doesn't need a villain — it builds when the schedule is tight and paperwork slows the line.",
   ko:"탓하는 게 아닙니다. 압박에는 악당이 필요 없어요. 일정이 빡빡하고 서류가 라인을 늦추면 저절로 쌓입니다.",
   notes:[{t:"Pressure does not need a villain",k:"colloquial",m:"압박은 나쁜 사람이 있어야 생기는 게 아니다",tip:"구조 문제를 지적하면서 상대를 방어적으로 만들지 않는 화법입니다. 그대로 외워 두세요."},
          {t:"tight (schedule)",k:"collocation",m:"빠듯한 (일정)",tip:"a tight schedule / a tight budget / tight margins 로 붙습니다."}]},
  {s:"B",en:"Fair enough. The schedule is tight, and a near-miss form takes twenty minutes that nobody has during a hot run.",
   ko:"인정합니다. 일정은 빡빡하고, 아차사고 양식은 20분이 걸리는데 조업이 한창일 땐 그 20분이 아무한테도 없어요.",
   notes:[{t:"a hot run",k:"business",m:"쉴 틈 없이 돌아가는 조업 구간",tip:"제조 현장의 구어입니다. 사무직 맥락이면 a crunch 로 바꿔 쓸 수 있습니다."},
          {t:"twenty minutes that nobody has",k:"grammar",m:"아무에게도 없는 20분",tip:"시간 명사에 관계절을 붙여 부족함을 드러내는 방식. 표현력이 확 올라갑니다."}]},
  {s:"A",en:"Then the form is the problem. Make it thirty seconds on a phone and you'll find out what's actually happening.",
   ko:"그럼 양식이 문제네요. 휴대폰으로 30초짜리로 만들면 실제로 무슨 일이 벌어지는지 알게 될 겁니다.",
   notes:[{t:"Then ~ is the problem",k:"colloquial",m:"그렇다면 문제는 ~이군요",tip:"상대의 변명을 받아 그대로 원인 규정으로 돌리는 화법입니다."},
          {t:"find out",k:"phrasal",m:"(몰랐던 것을) 알아내다",tip:"know와 다릅니다. find out 은 「없던 정보를 새로 얻는」 과정입니다."}]},
  {s:"B",en:"Suppose I do that. What do you actually do with a hundred small reports that mostly describe people being slightly clumsy?",
   ko:"그렇게 한다고 칩시다. 대부분 사람이 좀 서툴렀다는 얘기인 자잘한 신고 100건을 실제로 어떻게 하실 건데요?",
   notes:[{t:"Suppose I do that.",k:"grammar",m:"그렇게 한다고 칩시다",tip:"If I do that 보다 도전적인 어조입니다. 토론에서 상대에게 공을 넘길 때 씁니다."},
          {t:"clumsy",k:"colloquial",m:"손이 서툰, 덤벙대는",tip:"사람에게 쓰면 가벼운 흠. 사고 원인을 개인 탓으로 돌리는 말이라 안전 회의에서는 조심해서 씁니다."}]},
  {s:"A",en:"I look for the ones that repeat. A near miss that keeps happening in the same spot is a warning, not clumsiness.",
   ko:"반복되는 것을 찾습니다. 같은 자리에서 계속 일어나는 아차사고는 서투름이 아니라 경고예요.",
   notes:[{t:"the ones that repeat",k:"grammar",m:"반복되는 것들",tip:"the ones + 관계절. 앞서 나온 명사를 되받는 가장 자연스러운 방식입니다."},
          {t:"A is a warning, not B",k:"colloquial",m:"그건 B가 아니라 경고다",tip:"쉼표 뒤 not 으로 대비시키는 반박 구조. 짧고 강합니다."}]},
  {s:"B",en:"So you're after patterns, not incidents. That I can work with, as long as it never turns into a scoreboard.",
   ko:"그러니까 개별 사고가 아니라 패턴을 보시겠다는 거군요. 그거라면 같이 갈 수 있습니다, 점수판만 되지 않는다면요.",
   notes:[{t:"be after ~",k:"phrasal",m:"~을 노리다, ~을 찾고 있다",tip:"What are you after? = 원하시는 게 뭡니까. 구어에서 매우 자주 씁니다."},
          {t:"That I can work with",k:"grammar",m:"그거라면 해 볼 만합니다",tip:"목적어 도치로 조건부 수용을 나타냅니다. 협상에서 유용합니다."},
          {t:"a scoreboard",k:"business",m:"부서끼리 줄 세우는 점수판",tip:"안전·품질 맥락에서는 거의 항상 부정적 함의로 씁니다."}]},
  {s:"A",en:"It can't be a scoreboard. The moment reporting counts against a crew, the reports dry up and we're blind again.",
   ko:"점수판이 되면 안 됩니다. 신고가 작업조에게 불리하게 매겨지는 순간 신고는 말라붙고 우리는 다시 눈이 멉니다.",
   notes:[{t:"count against ~",k:"phrasal",m:"~에게 불리하게 작용하다",tip:"반대는 count towards / count in your favour."},
          {t:"dry up",k:"phrasal",m:"(신고·자금이) 말라붙다",tip:"서서히가 아니라 끊기는 느낌입니다. Applications dried up."}]},
  {s:"B",en:"Good, because the last program rewarded low numbers and everyone quickly learned what the company wanted to hear.",
   ko:"다행이네요. 지난번 제도는 낮은 숫자에 상을 줬고, 다들 회사가 뭘 듣고 싶어 하는지 금방 배웠거든요.",
   notes:[{t:"reward low numbers",k:"collocation",m:"낮은 수치에 보상하다",tip:"reward + 행동/결과. 인센티브 설계를 비판할 때의 정석 표현입니다."},
          {t:"what the company wanted to hear",k:"grammar",m:"회사가 듣고 싶어 하던 말",tip:"tell someone what they want to hear = 듣기 좋은 말만 하다. 통째로 외우세요."}]},
  {s:"A",en:"That's the trap. Injury counts are lagging indicators — they tell you what already went wrong, long after it mattered.",
   ko:"그게 함정입니다. 재해 건수는 후행지표예요. 이미 잘못된 것을, 손쓸 시점이 한참 지난 뒤에 알려 줍니다.",
   notes:[{t:"a lagging indicator",k:"business",m:"후행지표 — 이미 벌어진 뒤를 세는 수치",tip:"안전뿐 아니라 경영 전반에서 씁니다. Turnover is a lagging indicator."},
          {t:"long after it mattered",k:"colloquial",m:"이미 늦어 버린 뒤에",tip:"after the fact 와 비슷하지만 아쉬움이 더 짙습니다."}]},
  {s:"B",en:"And the leading ones? Checks, drills, the things nobody notices until an auditor asks somebody for a signature?",
   ko:"그럼 선행지표는요? 점검, 훈련, 감사가 서명을 요구하기 전까지는 아무도 신경 안 쓰는 그런 것들 말입니까?",
   notes:[{t:"a leading indicator",k:"business",m:"선행지표 — 앞을 내다보는 수치",tip:"lagging 과 반드시 짝으로 외우세요. 회의에서 한 쌍으로 등장합니다."},
          {t:"a drill",k:"business",m:"(비상) 훈련",tip:"a fire drill / an evacuation drill. 「지루한 소동」이라는 비유로도 씁니다."}]},
  {s:"A",en:"Those, yes, but only if they're done rather than signed. A tick in a box protects nobody standing near the press.",
   ko:"네, 그것들입니다. 다만 서명만 하는 게 아니라 실제로 할 때만이에요. 칸에 친 체크 표시는 프레스 옆에 선 사람을 지켜 주지 않습니다.",
   notes:[{t:"a tick in a box",k:"idiom",m:"형식만 채운 확인",tip:"미국식은 a check in a box. tick-box exercise = 형식적 요식행위."},
          {t:"done rather than signed",k:"grammar",m:"서명만 한 게 아니라 실제로 이행된",tip:"rather than 으로 두 과거분사를 대비시켰습니다. 짧게 대조할 때 유용합니다."}]},
  {s:"B",en:"Here's what I actually see. Standards don't collapse, they slip. One shortcut works, and then it becomes the method.",
   ko:"제가 실제로 보는 건 이겁니다. 기준은 무너지는 게 아니라 밀립니다. 지름길이 한 번 통하면, 그다음엔 그게 방법이 돼요.",
   notes:[{t:"Here is what I actually see",k:"colloquial",m:"제가 실제로 보는 건 이렇습니다",tip:"자기 관찰을 앞세워 발언권을 가져오는 화법. 회의에서 아주 자주 씁니다."},
          {t:"slip",k:"idiom",m:"조금씩 밀리다, 느슨해지다",tip:"standards slip / the date slipped. 「미끄러지다」의 비유입니다."}]},
  {s:"A",en:"That's the whole mechanism, and it has a name — normalization of deviance. The exception quietly turns into the rule.",
   ko:"그게 메커니즘 전부이고, 이름도 있습니다 — 일탈의 일상화. 예외가 조용히 규칙이 되는 겁니다.",
   notes:[{t:"normalization of deviance",k:"business",m:"예외가 반복되어 정상이 되는 현상",tip:"안전공학에서 나와 경영 전반으로 퍼진 말입니다. 회의에서 쓰면 무게가 실립니다."},
          {t:"turn into ~",k:"phrasal",m:"~으로 변하다",tip:"turn to 와 다릅니다. into 는 성질 자체가 바뀌는 것입니다."}]},
  {s:"B",en:"Then don't hand me another poster. Give me the authority to stop the line without explaining myself to three managers.",
   ko:"그럼 포스터 한 장 더 주지 마세요. 관리자 셋한테 해명하지 않고도 라인을 세울 수 있는 권한을 주십시오.",
   notes:[{t:"stop the line",k:"business",m:"(안전을 위해) 생산을 세우다",tip:"제조업 안전 문화의 핵심 개념입니다. the authority to stop the line 으로 통째로 씁니다."},
          {t:"explain oneself",k:"collocation",m:"자기 행동을 해명하다",tip:"explain 과 다릅니다. 추궁당하는 뉘앙스가 붙습니다."}]},
  {s:"A",en:"You'll get it in writing, and I'll take the argument upstairs when somebody asks why output dropped for an hour.",
   ko:"문서로 드리겠습니다. 그리고 왜 한 시간 산출이 줄었냐고 누가 물으면 제가 윗선에 가서 싸우겠습니다.",
   notes:[{t:"in writing",k:"idiom",m:"구두가 아니라 문서로",tip:"Get it in writing. 은 실무 조언의 정석 문장입니다."},
          {t:"take something upstairs",k:"idiom",m:"윗선으로 가져가다",tip:"escalate 의 구어형입니다. 회의에서 훨씬 자연스럽게 들립니다."}]},
  {s:"B",en:"Then we're aligned. Just remember that the day I use it, that hour will look expensive and the accident won't.",
   ko:"그럼 뜻이 맞았네요. 다만 제가 그 권한을 쓰는 날, 그 한 시간은 비싸 보이고 일어나지 않은 사고는 안 보인다는 걸 기억해 주세요.",
   notes:[{t:"be aligned",k:"business",m:"뜻이 맞다, 방향이 일치하다",tip:"We are aligned on the approach. 합의를 확인하는 회의 마무리 표현입니다."},
          {t:"the day I use it",k:"grammar",m:"내가 그것을 쓰는 그날",tip:"the day 가 접속사처럼 쓰였습니다. when 보다 그 시점을 또렷하게 만듭니다."}]}
 ],
 keys:[
  {en:"a near miss",ko:"아차사고 — 다치지 않고 지나간 사고",ex:"Every near miss is a lesson you did not have to pay for."},
  {en:"normalization of deviance",ko:"예외가 반복되어 정상이 되는 현상",ex:"Skipping the check saved time once; normalization of deviance did the rest."},
  {en:"a lagging indicator",ko:"후행지표 — 이미 벌어진 뒤를 세는 수치",ex:"Turnover is a lagging indicator; by the time it moves, the damage is done."},
  {en:"a leading indicator",ko:"선행지표 — 앞을 내다보는 수치",ex:"Completed training is a leading indicator of how the audit will go."},
  {en:"speak up",ko:"(문제를) 소리 내어 말하다",ex:"People speak up when being wrong in front of the boss is survivable."},
  {en:"stop the line",ko:"안전을 위해 생산을 세우다",ex:"Anyone on the floor can stop the line and nobody has to justify it first."},
  {en:"a tick in a box",ko:"형식만 채운 확인",ex:"The inspection had become a tick in a box long before the failure."},
  {en:"standards slip",ko:"기준이 조금씩 밀리다",ex:"Standards slip quietly; they rarely collapse in a way anyone can point to."}
 ],
 out:[
  {q:"Explain why zero reported near misses can be a warning sign rather than good news.",hint:"a near miss / reports dry up / speak up"},
  {q:"Your director wants to reward the crew with the lowest injury count. Push back.",hint:"a lagging indicator / a scoreboard / what the company wanted to hear"},
  {q:"Describe how a safety standard erodes without anyone deciding to break it.",hint:"standards slip / one shortcut works / normalization of deviance"}
 ]
},
{
 id:"w2d6", day:13, cat:"조직·성과관리", level:"B2+",
 title:"What Gets Measured Gets Gamed",
 titleKo:"재면 조작된다 — 지표가 목표가 될 때",
 names:{A:"Ruth (성과관리)", B:"Ali (현업 팀장)"},
 brief:[
  "조직은 재지 않으면 관리하지 못한다. 그런데 재기 시작하는 순간 지표는 단순한 관찰이 아니라 <b>목표</b>가 되고, 사람들은 일이 아니라 지표를 향해 움직이기 시작한다.",
  "대부분의 지표는 <b>대리 지표(proxy)</b>다. 정말 보고 싶은 것 — 고객이 만족했는지, 품질이 좋아졌는지 — 은 직접 재기 어려워서, 대신 세기 쉬운 것을 센다. 처리 건수, 응답 시간 같은 것들이다. 대리와 본체가 어긋나기 시작하면 지표는 그때부터 거짓말을 한다.",
  "지표가 목표가 되면 좋은 지표이기를 그친다 — <b>굿하트의 법칙(Goodhart's law)</b>. 여기서 중요한 것은 조작이 대개 부정행위가 아니라는 점이다. 걸린 보상에 대한 합리적인 반응일 뿐이고, 그래서 사람을 바꿔도 되풀이된다.",
  "실무의 해법은 완벽한 지표를 찾는 것이 아니라 <b>여러 지표를 묶어(a basket of measures)</b> 서로를 견제하게 두는 것이다. 처리 건수 옆에 재문의율을, 속도 옆에 재작업률을 놓는다. 하나는 속일 수 있어도 셋을 동시에 속이려면 대개 일을 제대로 하는 편이 빠르다."
 ],
 lines:[
  {s:"A",en:"Your team's ticket closure rate doubled in two months, which means either a miracle happened or something moved in the numbers.",
   ko:"그쪽 팀 티켓 처리율이 두 달 만에 두 배가 됐는데, 기적이 일어났거나 숫자 안에서 뭔가 움직였다는 뜻이겠죠.",
   notes:[{t:"either A or B",k:"grammar",m:"A이거나 B이거나 둘 중 하나다",tip:"either 뒤 어순에 주의하세요. means either a miracle happened or ~ 처럼 절이 통째로 옵니다."},
          {t:"move in the numbers",k:"business",m:"수치 안에서 무언가 바뀌다",tip:"실적이 아니라 「집계 방식」이 바뀌었다는 완곡한 의심입니다. 직접 비난하지 않는 표현."}]},
  {s:"B",en:"You asked for closure rate and you got closure rate. I'd have preferred you asked for something worth measuring.",
   ko:"처리율을 달라셔서 처리율을 드린 겁니다. 저는 잴 값어치가 있는 걸 물어보셨으면 했고요.",
   notes:[{t:"You asked for X and you got X",k:"colloquial",m:"X 달라고 하셔서 X 드린 겁니다",tip:"같은 말을 반복해 「요구가 잘못이었다」를 찌르는 반박입니다. 아주 자주 쓰입니다."},
          {t:"worth ~ing",k:"grammar",m:"~할 값어치가 있는",tip:"worth measuring / worth doing. 뒤에 반드시 동명사가 옵니다."}]},
  {s:"A",en:"That's not an answer. Tell me what changed on the ground, because the board reads that chart as productivity.",
   ko:"그건 답이 아니죠. 현장에서 뭐가 바뀌었는지 말해 주세요. 이사회는 저 그래프를 생산성으로 읽습니다.",
   notes:[{t:"on the ground",k:"idiom",m:"현장에서 실제로",tip:"보고서·계획과 대비되는 말입니다. It looks fine on paper, but on the ground ~"},
          {t:"read A as B",k:"collocation",m:"A를 B로 해석하다",tip:"They will read silence as agreement. 오해의 소지를 경고할 때 유용합니다."}]},
  {s:"B",en:"Tickets get closed and then reopened. The same problem walks back in the door under a new number the following week.",
   ko:"티켓이 닫혔다가 다시 열립니다. 같은 문제가 다음 주에 새 번호를 달고 문으로 걸어 들어와요.",
   notes:[{t:"walk back in the door",k:"idiom",m:"(해결된 줄 알았던 것이) 되돌아오다",tip:"사물을 사람처럼 걷게 하는 비유. 원어민이 즐겨 쓰는 생생한 표현입니다."},
          {t:"under a new number",k:"collocation",m:"새 번호를 달고",tip:"under a new name / under a different heading 처럼 under 로 「이름을 바꿔」를 나타냅니다."}]},
  {s:"A",en:"So we're counting the same work twice and calling it improvement. That's exactly what I was afraid we had built.",
   ko:"그럼 같은 일을 두 번 세고 그걸 개선이라 부르는 거네요. 우리가 만들어 놓은 게 딱 그거일까 봐 걱정했습니다.",
   notes:[{t:"call A B",k:"grammar",m:"A를 B라고 부르다",tip:"calling it improvement 처럼 목적격 보어가 관사 없이 오는 경우가 많습니다."},
          {t:"what I was afraid we had built",k:"grammar",m:"우리가 만들어 놨을까 봐 걱정하던 것",tip:"관계절 안에 시제가 한 단계 더 뒤로 갑니다. 문장이 길어져도 흔들리지 않게 연습하세요."}]},
  {s:"B",en:"Nobody cheated. People did what the target rewarded, which is what people always do once you hang a number on them.",
   ko:"아무도 속이지 않았습니다. 목표가 보상하는 대로 했을 뿐이고, 숫자를 걸어 두면 사람은 늘 그렇게 합니다.",
   notes:[{t:"hang a number on someone",k:"idiom",m:"~에게 수치 목표를 걸다",tip:"목에 걸어 놓는 이미지입니다. 목표 관리의 압박을 말할 때 인상적으로 들립니다."},
          {t:", which is what ~",k:"grammar",m:"그리고 그것은 ~하는 바이다",tip:"앞 문장 전체를 받는 계속적 용법입니다. 토론에서 논리를 이어 붙일 때 필수."}]},
  {s:"A",en:"I know. The measure stopped describing the work the moment it became the thing the work was judged on.",
   ko:"압니다. 그 지표는 일이 평가받는 잣대가 된 순간부터 일을 설명하기를 그만뒀어요.",
   notes:[{t:"the moment (that) ~",k:"grammar",m:"~하는 바로 그 순간",tip:"as soon as 보다 극적입니다. 접속사처럼 씁니다."},
          {t:"be judged on ~",k:"collocation",m:"~을 기준으로 평가받다",tip:"We are judged on delivery, not effort. 전치사 on 을 통째로 외우세요."}]},
  {s:"B",en:"There's a name for that, isn't there? The one about a measure ceasing to be good once it becomes a target.",
   ko:"그거 이름이 있지 않나요? 지표가 목표가 되는 순간 좋은 지표이기를 그친다는 그 법칙이요.",
   notes:[{t:"cease to ~",k:"business",m:"~하기를 그치다",tip:"stop 보다 격식 있습니다. cease to be valid / cease to apply 로 계약서에도 나옵니다."},
          {t:"The one about ~",k:"colloquial",m:"~에 관한 그거",tip:"이름이 바로 안 떠오를 때 쓰는 자연스러운 말버릇입니다. 회화에서 아주 유용합니다."}]},
  {s:"A",en:"Goodhart's law. It's not a warning about dishonest people, it's a warning about honest people responding to incentives.",
   ko:"굿하트의 법칙입니다. 부정직한 사람에 대한 경고가 아니라, 인센티브에 반응하는 정직한 사람들에 대한 경고예요.",
   notes:[{t:"Goodhart's law",k:"business",m:"지표가 목표가 되면 좋은 지표이기를 그친다는 법칙",tip:"영어 회의에서 이 이름을 정확히 대면 논의의 격이 올라갑니다."},
          {t:"It's not A, it's B",k:"colloquial",m:"그건 A가 아니라 B다",tip:"쉼표로 이어 붙이는 대비 구문. 강연과 토론에서 즐겨 쓰는 리듬입니다."}]},
  {s:"B",en:"Then stop measuring closure and measure whether the customer came back. That's the thing you actually care about.",
   ko:"그럼 처리 건수 재는 걸 그만두고 고객이 다시 왔는지를 재세요. 실제로 신경 쓰는 건 그거잖아요.",
   notes:[{t:"whether ~",k:"grammar",m:"~인지 아닌지",tip:"measure/ask/decide 뒤에 if 대신 whether 를 쓰면 격식이 올라갑니다."},
          {t:"care about",k:"phrasal",m:"진짜로 중요하게 여기다",tip:"care for(돌보다)와 다릅니다. 실무 대화에서 헷갈리면 뜻이 어긋납니다."}]},
  {s:"A",en:"I'd love to, but repeat contact is slow, noisy, and half of it has nothing to do with your team at all.",
   ko:"그러고 싶죠. 그런데 재문의는 느리고 잡음이 많고, 그중 절반은 그쪽 팀과 아무 상관이 없습니다.",
   notes:[{t:"I would love to, but ~",k:"colloquial",m:"그러고 싶은데 다만 ~",tip:"거절을 부드럽게 하는 정형입니다. 뒤에 실제 제약을 붙입니다."},
          {t:"have nothing to do with ~",k:"idiom",m:"~과 아무 상관이 없다",tip:"부분 부정과 헷갈리지 마세요. 전면 부정입니다."}]},
  {s:"B",en:"Everything useful is slow and noisy. The clean numbers are clean precisely because the hard parts have been stripped out.",
   ko:"쓸모 있는 건 다 느리고 지저분합니다. 깔끔한 숫자가 깔끔한 건 어려운 부분이 걷어내졌기 때문이고요.",
   notes:[{t:"precisely because ~",k:"grammar",m:"바로 ~하기 때문에",tip:"because 앞에 precisely/exactly 를 붙이면 인과를 강하게 못 박습니다."},
          {t:"strip out",k:"phrasal",m:"(요소를) 걷어내다, 제거하다",tip:"strip out the noise / strip out one-off costs. 데이터·회계 대화에서 자주 나옵니다."}]},
  {s:"A",en:"Fair enough, but I can't take 'it's complicated' upstairs. I need something on a page that survives a ten-minute review.",
   ko:"일리 있습니다. 그래도 「복잡합니다」를 윗선에 가져갈 순 없어요. 10분짜리 검토에서 살아남는 한 장짜리가 필요합니다.",
   notes:[{t:"take something upstairs",k:"idiom",m:"윗선에 가져가다",tip:"escalate 의 구어형입니다. 회의에서 훨씬 자연스럽습니다."},
          {t:"survive a review",k:"collocation",m:"검토를 버텨 내다",tip:"자료를 사람처럼 살아남게 하는 비유. 실무 영어에서 흔합니다."}]},
  {s:"B",en:"Then put three numbers on the page instead of one and let them argue with each other in front of the board.",
   ko:"그럼 한 장에 숫자를 하나가 아니라 셋을 올리고, 이사회 앞에서 그 셋이 서로 다투게 두세요.",
   notes:[{t:"let them argue with each other",k:"colloquial",m:"그것들이 서로 다투게 두다",tip:"지표를 사람처럼 말하게 하는 비유. 견제 구조를 설명하는 데 아주 효과적입니다."},
          {t:"instead of ~",k:"grammar",m:"~ 대신에",tip:"instead of one 처럼 뒤에 숫자·대명사만 와도 됩니다. 문장을 짧게 유지하세요."}]},
  {s:"A",en:"A basket of measures. Closure rate next to reopen rate, and volume next to how long the queue actually is.",
   ko:"지표 묶음이군요. 처리율 옆에 재개율, 처리량 옆에 대기열이 실제로 얼마나 긴지를 놓는 거죠.",
   notes:[{t:"a basket of measures",k:"business",m:"서로를 견제하는 지표 묶음",tip:"a basket of currencies 에서 온 비유입니다. 성과관리 회의의 표준 표현."},
          {t:"next to ~",k:"collocation",m:"~ 바로 옆에 (나란히 놓아 비교하는)",tip:"put A next to B 는 물리적 위치이자 「대조해 보이다」라는 뜻입니다."}]},
  {s:"B",en:"That's better. Any single number can be gamed, but gaming three at once usually means doing the job properly.",
   ko:"그게 낫죠. 숫자 하나는 얼마든지 조작되지만, 셋을 동시에 조작하려면 대개 일을 제대로 하는 편이 빠릅니다.",
   notes:[{t:"game (a metric)",k:"business",m:"규칙 안에서 지표를 유리하게 조작하다",tip:"cheat 과 다릅니다. 규칙을 어기지 않고 허점을 이용하는 것입니다."},
          {t:"at once",k:"idiom",m:"한꺼번에, 동시에",tip:"immediately 라는 다른 뜻도 있으니 문맥으로 가르세요."}]},
  {s:"A",en:"Usually. Someone will still find the seam, and when they do I'd rather hear it from you than from an audit.",
   ko:"대개는요. 그래도 누군가는 허점을 찾아낼 텐데, 그때는 감사보다 그쪽한테서 먼저 듣고 싶습니다.",
   notes:[{t:"find the seam",k:"idiom",m:"허점·이음매를 찾아내다",tip:"옷의 솔기에서 온 비유입니다. loophole 보다 구어적이고 생생합니다."},
          {t:"I would rather A than B",k:"grammar",m:"B보다 A 하는 편이 낫다",tip:"뒤에 동사원형이 옵니다. would rather hear ~ than hear ~."}]},
  {s:"B",en:"You will, if telling you costs me nothing. The last team that flagged a bad metric got the blame for it.",
   ko:"그러시게 될 겁니다, 말하는 게 저한테 아무 대가도 없다면요. 지난번에 잘못된 지표를 짚은 팀은 그 책임을 뒤집어썼거든요.",
   notes:[{t:"flag (an issue)",k:"business",m:"문제를 공식적으로 짚어 알리다",tip:"Let me flag one risk. 회의에서 이견을 꺼낼 때의 부드러운 도입입니다."},
          {t:"get the blame for ~",k:"collocation",m:"~에 대한 책임을 뒤집어쓰다",tip:"take the blame(스스로 지다)과 다릅니다. get 은 억울함이 섞입니다."}]},
  {s:"A",en:"That's on us, and I'll change how it's handled. A metric nobody dares question is worse than no metric at all.",
   ko:"그건 우리 잘못이고, 처리 방식을 바꾸겠습니다. 아무도 감히 묻지 못하는 지표는 지표가 아예 없는 것보다 나쁩니다.",
   notes:[{t:"That is on us",k:"colloquial",m:"그건 우리 책임입니다",tip:"That's on me. 형태로 책임을 짧게 인정할 때 씁니다. 사과보다 담백하게 들립니다."},
          {t:"dare (to) question",k:"grammar",m:"감히 의문을 제기하다",tip:"부정문·의문문에서는 to 를 흔히 생략합니다. nobody dares question it."}]},
  {s:"B",en:"Then we're getting somewhere. Just don't fall in love with the new numbers the way you fell for the old ones.",
   ko:"그럼 진전이 있네요. 다만 예전 숫자에 빠졌던 것처럼 새 숫자에 빠지지는 마세요.",
   notes:[{t:"we are getting somewhere",k:"idiom",m:"이제 좀 진전이 있다",tip:"논의가 풀리기 시작할 때 쓰는 정형 문장입니다. 그대로 외워 두세요."},
          {t:"fall for ~",k:"phrasal",m:"~에 홀딱 넘어가다",tip:"fall in love with 보다 「속았다」는 뉘앙스가 섞입니다. 여기서는 그 대비를 노렸습니다."}]}
 ],
 keys:[
  {en:"game a metric",ko:"규칙 안에서 지표를 유리하게 조작하다",ex:"Any target can be gamed once people work out what actually counts."},
  {en:"a proxy for ~",ko:"진짜 대신 재는 대리 지표",ex:"Response time is a proxy for service, and a poor one on hard cases."},
  {en:"Goodhart's law",ko:"지표가 목표가 되면 좋은 지표이기를 그친다는 법칙",ex:"Goodhart's law explains most of what goes wrong with bonus schemes."},
  {en:"a basket of measures",ko:"서로를 견제하는 지표 묶음",ex:"We moved from one headline number to a basket of measures."},
  {en:"hang a number on someone",ko:"~에게 수치 목표를 걸다",ex:"Hang a number on a team and they will optimize for the number."},
  {en:"take something upstairs",ko:"윗선에 가져가다",ex:"If we cannot settle it here, I will take it upstairs and let them decide."},
  {en:"find the seam",ko:"허점을 찾아내다",ex:"Give people a rulebook and somebody will find the seam within a month."},
  {en:"on the ground",ko:"현장에서 실제로",ex:"The plan reads well; on the ground it needs two more people."}
 ],
 out:[
  {q:"Explain Goodhart's law using an example from your own work.",hint:"a proxy for / becomes a target / game the metric"},
  {q:"Your director wants a single headline KPI. Argue for three instead.",hint:"a basket of measures / gamed / argue with each other"},
  {q:"Someone reports that a metric is misleading. How should the company respond?",hint:"flag / get the blame / a metric nobody dares question"}
 ]
},
{
 id:"w2d7", day:14, cat:"물류·운송", level:"B2+",
 title:"The Box That Waits",
 titleKo:"기다리는 컨테이너 — 체선료와 리드타임이라는 숨은 원가",
 names:{A:"Nadia (물류)", B:"Peter (생산계획)"},
 brief:[
  "운송 원가는 운임만이 아니다. 컨테이너가 항만에 서 있는 동안에도 값이 붙는다 — 터미널 안에 머무는 시간에 붙는 <b>체선료(demurrage)</b>와, 컨테이너를 끌고 나간 뒤 반납이 늦어질 때 붙는 <b>지체료(detention)</b>다.",
  "이 값은 벌금이 아니라 <b>회전율을 강제하는 가격</b>이다. 터미널과 선사는 한정된 자리와 장비가 묶이는 것을 싫어한다. 그래서 <b>무료 기간(free time)</b>을 짧게 두고 그 뒤부터는 시간을 판다. 창고를 빌려주는 것이 아니라, 오래 세워 둘 사람을 값으로 밀어내는 것이다.",
  "공장이 실제로 아파하는 것은 평균 리드타임이 아니라 <b>흔들림(variability)</b>이다. 늘 30일이면 계획이 서지만 20일과 45일을 오가면 그 차이만큼을 재고로 메워야 한다. 그렇게 쌓아 두는 것이 <b>안전재고(safety stock)</b>이고, 그것은 창고에 잠긴 현금이다.",
  "그래서 물류와 생산계획은 같은 돈을 서로 다른 계정에서 본다. 물류는 운임과 체선료를 보고, 생산은 멈춘 라인과 쌓인 재고를 본다. 각자의 예산에서 상대의 숫자가 보이지 않는다는 것 — 이것이 이 다툼의 진짜 뿌리다."
 ],
 lines:[
  {s:"A",en:"The demurrage bill for last month landed on my desk, and it's bigger than the freight rate we spent weeks arguing about.",
   ko:"지난달 체선료 청구서가 제 책상에 올라왔는데, 우리가 몇 주씩 다투던 운임보다 큽니다.",
   notes:[{t:"demurrage",k:"business",m:"체선료 — 컨테이너가 터미널에 머무는 시간에 붙는 값",tip:"detention(반출 뒤 반납 지연)과 짝으로 외우세요. 실무에서 둘을 섞어 쓰면 청구서를 잘못 읽습니다."},
          {t:"land on someone's desk",k:"idiom",m:"~에게 (일·청구서가) 떨어지다",tip:"원치 않게 떠맡게 됐다는 뉘앙스가 붙습니다. It landed on my desk this morning."}]},
  {s:"B",en:"That's not my line item. I asked for those boxes to sit until we had the space to unload them properly.",
   ko:"그건 제 예산 항목이 아닙니다. 저는 제대로 하역할 자리가 날 때까지 그 컨테이너를 세워 두라고 했을 뿐이에요.",
   notes:[{t:"a line item",k:"business",m:"(예산·청구서의) 개별 항목",tip:"That's not my line item. 은 「그건 내 예산 소관이 아니다」라는 뜻의 실무 관용구입니다."},
          {t:"sit",k:"colloquial",m:"(물건이) 놀고 있다, 세워져 있다",tip:"The stock has been sitting in the yard for weeks. 방치의 뉘앙스가 있습니다."}]},
  {s:"A",en:"The boxes sitting is exactly what you're being charged for. Free time ran out and the clock started billing by the day.",
   ko:"세워 둔 것 자체가 청구 사유입니다. 무료 기간이 끝나면서 하루 단위로 시계가 돌기 시작한 거예요.",
   notes:[{t:"free time",k:"business",m:"체선료가 붙지 않는 무료 유치 기간",tip:"「자유 시간」이 아닙니다. 물류 계약서에서는 이 뜻으로만 씁니다."},
          {t:"the clock started billing",k:"colloquial",m:"시간이 곧 돈으로 매겨지기 시작했다",tip:"the clock is ticking(시간이 촉박하다)과 함께 외우세요. 시계를 주어로 세우는 비유입니다."}]},
  {s:"B",en:"Then the free time is too short, because nobody clears a full vessel inside the window they hand us.",
   ko:"그럼 무료 기간이 너무 짧은 겁니다. 그쪽이 주는 시간 안에 배 한 척을 다 비워 내는 사람은 없어요.",
   notes:[{t:"clear (a vessel)",k:"business",m:"(화물을) 다 빼내다, 처리해 비우다",tip:"clear customs(통관하다)와 다릅니다. 물류에서 clear 는 문맥마다 뜻이 갈립니다."},
          {t:"the window",k:"business",m:"허용된 시간 구간",tip:"a delivery window / a booking window. 창문이 아니라 「기간」입니다."}]},
  {s:"A",en:"It's short on purpose. The terminal isn't renting you storage, it's pricing you out of parking there.",
   ko:"일부러 짧은 겁니다. 터미널은 창고를 빌려주는 게 아니라, 값으로 오래 세워 둘 사람을 밀어내는 거예요.",
   notes:[{t:"on purpose",k:"idiom",m:"일부러, 의도적으로",tip:"by accident 의 반대. deliberately 보다 구어적입니다."},
          {t:"price someone out of ~",k:"business",m:"값을 올려 ~에서 밀어내다",tip:"priced out of the market = 값 때문에 시장에서 밀려난. 통째로 외워 두면 유용합니다."}]},
  {s:"B",en:"Fair enough, but my yard was full and the line was running. What was I supposed to do, stop production?",
   ko:"일리 있습니다. 그래도 야적장은 꽉 찼고 라인은 돌고 있었어요. 그럼 어쩌란 겁니까, 생산을 세울까요?",
   notes:[{t:"What was I supposed to do?",k:"colloquial",m:"그럼 저더러 어쩌라는 겁니까",tip:"be supposed to = ~하기로 되어 있다. 과거형으로 쓰면 항변이 됩니다."},
          {t:"the yard",k:"business",m:"야적장, 물류 마당",tip:"the shop floor(생산 현장)와 짝으로 알아 두면 공장 대화가 편해집니다."}]},
  {s:"A",en:"You could have told me a week earlier. I can pre-book slots when I know, and I can't when I don't.",
   ko:"일주일 전에만 말해 주셨어도 됐습니다. 알면 자리를 미리 잡을 수 있고, 모르면 못 잡아요.",
   notes:[{t:"could have + 과거분사",k:"grammar",m:"~할 수도 있었는데 (하지 않았다)",tip:"아쉬움과 가벼운 질책을 동시에 담습니다. 비난 없이 지적할 때 유용합니다."},
          {t:"pre-book a slot",k:"collocation",m:"자리를 미리 잡아 두다",tip:"a slot 은 시간·설비의 「자리」입니다. book a slot / free up a slot."}]},
  {s:"B",en:"I didn't know a week earlier. The schedule moved twice because two orders got pulled forward at short notice.",
   ko:"일주일 전엔 저도 몰랐습니다. 주문 두 건이 갑자기 앞당겨지면서 일정이 두 번 움직였어요.",
   notes:[{t:"pull forward",k:"phrasal",m:"(일정을) 앞당기다",tip:"반대는 push back. 회의에서 일정 조정을 말할 때의 기본 짝입니다."},
          {t:"at short notice",k:"idiom",m:"촉박하게, 갑작스럽게",tip:"미국식은 on short notice. 둘 다 통합니다."}]},
  {s:"A",en:"Then that's the real problem, and it isn't demurrage. It's that your plan moves faster than my bookings can follow.",
   ko:"그럼 진짜 문제는 그거고, 체선료가 아닙니다. 계획이 제 예약이 따라갈 수 있는 속도보다 빠르다는 거죠.",
   notes:[{t:"the real problem is ~",k:"colloquial",m:"진짜 문제는 ~이다",tip:"증상과 원인을 갈라 놓는 토론의 정석 문형입니다."},
          {t:"faster than ~ can follow",k:"grammar",m:"~이 따라갈 수 있는 것보다 빠르게",tip:"비교급 + than + 절. 속도 차이를 정확히 규정할 때 씁니다."}]},
  {s:"B",en:"Plans always move. I'd rather move a plan than sit on stock we might never turn into anything sellable.",
   ko:"계획은 늘 움직입니다. 팔릴지도 모르는 재고를 끌어안고 있느니 계획을 움직이는 편이 낫죠.",
   notes:[{t:"sit on stock",k:"idiom",m:"재고를 끌어안고 있다",tip:"sit on cash / sit on a decision 처럼 「쥐고 안 움직인다」는 뜻으로 두루 씁니다."},
          {t:"I'd rather A than B",k:"grammar",m:"B 하느니 A 하겠다",tip:"뒤에 동사원형이 옵니다. 선택을 선언할 때 가장 자연스러운 형태입니다."}]},
  {s:"A",en:"I understand that, but every change costs me somewhere. It just shows up in my budget instead of yours.",
   ko:"이해합니다. 다만 변경 하나하나가 어디선가 제 비용이 됩니다. 그쪽 예산이 아니라 제 예산에 나타날 뿐이에요.",
   notes:[{t:"show up in ~",k:"phrasal",m:"~에 (수치로) 나타나다",tip:"It shows up in the numbers next quarter. 결과가 드러나는 자리를 말할 때 씁니다."},
          {t:"cost someone somewhere",k:"colloquial",m:"어디선가는 대가를 치르게 하다",tip:"막연한 장소를 뜻하는 somewhere 가 「어딘가에서는 반드시」라는 뉘앙스를 만듭니다."}]},
  {s:"B",en:"That's the whole argument in one sentence. We're both saving money and the company is paying for it twice.",
   ko:"그 한 문장이 이 논쟁 전부네요. 우리 둘 다 돈을 아끼고 있는데 회사는 그 값을 두 번 치르고 있고요.",
   notes:[{t:"in one sentence",k:"collocation",m:"한 문장으로 요약하면",tip:"That's the whole thing in one sentence. 논의를 압축해 되받을 때 씁니다."},
          {t:"pay for it twice",k:"idiom",m:"같은 값을 두 번 치르다",tip:"부분 최적화의 폐해를 지적하는 정형 표현입니다."}]},
  {s:"A",en:"So let's stop optimizing separately. Give me a rolling forecast, even a rough one, and I'll hold slots against it.",
   ko:"그러니 따로따로 최적화하는 걸 그만둡시다. 대충이라도 굴러가는 예측을 주시면 거기에 맞춰 자리를 잡아 두겠습니다.",
   notes:[{t:"a rolling forecast",k:"business",m:"기간을 밀며 계속 갱신하는 예측",tip:"고정된 연간 예산과 대비되는 개념입니다. a rolling three-month forecast."},
          {t:"hold slots against ~",k:"business",m:"~을 근거로 자리를 잡아 두다",tip:"against 가 「~에 대응해서」라는 뜻으로 쓰였습니다. hold stock against an order."}]},
  {s:"B",en:"How rough can it be before it stops being useful? I can't promise numbers I haven't got orders behind.",
   ko:"얼마나 대충이어야 쓸모가 없어지는 겁니까? 주문이 뒤에 없는 숫자는 약속할 수 없어요.",
   notes:[{t:"before it stops being useful",k:"grammar",m:"쓸모없어지기 전까지는 (어디까지)",tip:"before 로 한계선을 묻는 방식입니다. How late can I leave before I miss it?"},
          {t:"have orders behind (a number)",k:"colloquial",m:"그 숫자를 뒷받침하는 실제 주문이 있다",tip:"behind 하나로 「근거가 받치고 있다」를 나타냅니다."}]},
  {s:"A",en:"Rough is fine. What kills me is silence, because silence gets treated as no change until the day it isn't.",
   ko:"대충이어도 됩니다. 저를 죽이는 건 침묵이에요. 침묵은 변경 없음으로 처리되다가, 아닌 날이 옵니다.",
   notes:[{t:"What kills me is ~",k:"colloquial",m:"내가 정말 힘든 건 ~이다",tip:"과장된 구어입니다. 회의에서 감정을 실어 강조할 때 자연스럽게 쓰입니다."},
          {t:"get treated as ~",k:"grammar",m:"~으로 취급되다",tip:"get + 과거분사 수동. be treated 보다 「어쩌다 그렇게 되어 버린다」는 느낌을 줍니다."}]},
  {s:"B",en:"All right. Then help me with the other half — lead times swing by three weeks and I plan around the worst case.",
   ko:"좋습니다. 그럼 나머지 절반도 도와주세요. 리드타임이 3주씩 흔들려서 저는 최악을 기준으로 계획합니다.",
   notes:[{t:"swing by ~",k:"collocation",m:"~만큼 오르내리다",tip:"명사 a swing 과 함께 씁니다. swing by three weeks = 3주 폭으로 흔들리다."},
          {t:"plan around ~",k:"phrasal",m:"~을 감안해 우회하며 계획하다",tip:"work around 와 비슷합니다. 문제를 없애지 못하고 피해 간다는 뉘앙스."}]},
  {s:"A",en:"That's what safety stock is for, and it isn't free either. Every week of variability sits in your warehouse as cash.",
   ko:"그게 안전재고가 하는 일이고, 그것도 공짜가 아닙니다. 흔들림 1주일치가 그쪽 창고에 현금으로 잠겨 있어요.",
   notes:[{t:"safety stock",k:"business",m:"안전재고",tip:"buffer stock 도 같은 개념입니다. 흔들림을 흡수하려고 두는 재고입니다."},
          {t:"variability",k:"business",m:"흔들림, 편차",tip:"average 와 대비해 씁니다. It's not the average, it's the variability."}]},
  {s:"B",en:"So I'm buying certainty with inventory while you're buying it with bookings. Neither of us calls it the same thing.",
   ko:"그러니까 저는 재고로 확실성을 사고, 그쪽은 예약으로 사는 거군요. 서로 그걸 같은 이름으로 부르지 않고요.",
   notes:[{t:"buy certainty with ~",k:"collocation",m:"~을 들여 확실성을 사다",tip:"추상적인 것을 사는 비유. buy time / buy goodwill 도 같은 방식입니다."},
          {t:"Neither of us ~",k:"grammar",m:"우리 둘 다 ~하지 않는다",tip:"뒤에 단수 동사가 옵니다. Neither of us was told."}]},
  {s:"A",en:"Right. Let's put both numbers on one page and let whoever owns the total decide which one to spend.",
   ko:"맞습니다. 두 숫자를 한 장에 올리고, 총액을 책임지는 사람이 어느 쪽을 쓸지 정하게 합시다.",
   notes:[{t:"whoever owns ~",k:"grammar",m:"~을 책임지는 사람이 누구든",tip:"복합관계대명사. 이름을 몰라도 책임 소재를 가리킬 수 있어 실무에서 유용합니다."},
          {t:"own (a number)",k:"business",m:"(숫자·결과를) 책임지다",tip:"Who owns this? = 이건 누구 책임입니까. 회의에서 대단히 자주 나옵니다."}]},
  {s:"B",en:"Now that I'd sign up for, provided nobody uses the page to decide whose department was wrong all along.",
   ko:"그거라면 저도 하겠습니다. 다만 그 한 장을 어느 부서가 내내 틀렸는지 가리는 데 쓰지만 않는다면요.",
   notes:[{t:"sign up for ~",k:"phrasal",m:"~에 동의하고 참여하다",tip:"agree to 보다 「내가 책임을 지고 들어간다」는 무게가 있습니다."},
          {t:"all along",k:"idiom",m:"처음부터 내내",tip:"You knew all along. 뒤늦게 드러난 사실을 말할 때 자주 붙습니다."}]}
 ],
 keys:[
  {en:"demurrage",ko:"체선료 — 컨테이너가 터미널에 머무는 시간에 붙는 값",ex:"The vessel arrived late, so demurrage started before we ever touched the cargo."},
  {en:"free time",ko:"체선료가 붙지 않는 무료 유치 기간",ex:"You get five days of free time; after that the clock bills you daily."},
  {en:"a line item",ko:"(예산·청구서의) 개별 항목",ex:"Training is the line item nobody defends when the budget gets cut."},
  {en:"pull forward",ko:"(일정을) 앞당기다",ex:"Two orders were pulled forward and the whole month's plan moved."},
  {en:"a rolling forecast",ko:"기간을 밀며 계속 갱신하는 예측",ex:"We replaced the annual budget with a rolling forecast updated every month."},
  {en:"safety stock",ko:"안전재고 — 흔들림을 흡수하려고 쌓아 두는 재고",ex:"Safety stock is what you buy when you cannot trust the lead time."},
  {en:"variability",ko:"흔들림, 편차",ex:"It is not the average that hurts you, it is the variability around it."},
  {en:"show up in someone's budget",ko:"~의 예산에 비용으로 나타나다",ex:"The saving shows up in my budget and the cost shows up in yours."}
 ],
 out:[
  {q:"Explain why demurrage is a price rather than a penalty.",hint:"free time / price someone out of / by the day"},
  {q:"Your planner keeps changing the schedule at short notice. Explain the cost without blaming them.",hint:"pull forward / pre-book slots / show up in my budget"},
  {q:"Argue that lead-time variability costs more than a longer average lead time.",hint:"variability / safety stock / plan around the worst case"}
 ]
},
{
 id:"w2d8", day:15, cat:"의사결정", level:"B2+",
 title:"The Project Nobody Will Kill",
 titleKo:"아무도 끝내지 못하는 프로젝트 — 매몰비용과 멈추는 기술",
 names:{A:"Helen (재무)", B:"Raj (프로젝트 책임)"},
 brief:[
  "이미 쓴 돈은 <b>매몰비용(sunk cost)</b>이다. 무엇을 하든 회수되지 않으므로 앞으로의 판단에 넣어서는 안 된다. 지금 물어야 할 것은 「지금까지 얼마를 썼나」가 아니라 「앞으로 쓸 돈이 값어치를 하는가」뿐이다.",
  "그런데 사람은 쓴 돈이 클수록 그만두기 어려워한다. 계속하는 편이 유리해서가 아니라, 멈추는 순간 그동안의 판단이 틀렸다고 인정하는 일이 되기 때문이다. 이것을 <b>집착의 확대(escalation of commitment)</b>라 부른다.",
  "조직은 이 함정을 개인의 의지로 막지 못한다. 그래서 <b>단계별 관문(stage gate)</b>을 미리 세워 둔다. 다음 단계로 갈 자격을 매번 새로 증명하게 하는 장치이고, 핵심은 기준을 <b>숫자가 나오기 전에</b> 합의해 두는 것이다.",
  "관문이 실제로 작동하려면 <b>멈추는 것이 실패가 아니어야</b> 한다. 중단을 말한 사람이 불이익을 받는 조직에서는 아무도 관문에서 손을 들지 않고, 보고서는 전부 노란불이 되며, 관문은 서명 절차로 전락한다."
 ],
 lines:[
  {s:"A",en:"We're eighteen months into this now, and I'd like to talk about whether it should carry on at all.",
   ko:"이 건에 들어온 지 열여덟 달째인데, 이걸 계속하는 게 맞는지부터 이야기하고 싶습니다.",
   notes:[{t:"be ~ into something",k:"grammar",m:"(기간이) ~째 진행 중이다",tip:"We're three weeks into the trial. 진행 경과를 말하는 가장 간결한 형태입니다."},
          {t:"carry on",k:"phrasal",m:"계속 진행하다",tip:"continue의 구어형입니다. carry on with the plan 처럼 with 를 붙이기도 합니다."}]},
  {s:"B",en:"We're two thirds of the way through. Stopping now throws away everything we've spent getting here.",
   ko:"3분의 2까지 왔습니다. 지금 멈추면 여기까지 쓴 걸 전부 버리는 겁니다.",
   notes:[{t:"two thirds of the way through",k:"collocation",m:"3분의 2 지점까지 온",tip:"halfway through / most of the way through 로 응용됩니다. 진행률을 말하는 자연스러운 방식."},
          {t:"throw away",k:"phrasal",m:"내버리다, 헛되게 하다",tip:"throw away an opportunity 처럼 추상적인 것에도 씁니다."}]},
  {s:"A",en:"That money is gone either way. The only question left is whether the next twelve months are worth spending.",
   ko:"그 돈은 어느 쪽을 택하든 이미 나갔습니다. 남은 질문은 앞으로의 열두 달이 쓸 값어치가 있느냐뿐이에요.",
   notes:[{t:"either way",k:"idiom",m:"어느 쪽이든 마찬가지로",tip:"결론이 같음을 못 박습니다. Either way, we pay. 매몰비용을 설명하는 핵심 표현입니다."},
          {t:"worth ~ing",k:"grammar",m:"~할 값어치가 있는",tip:"worth spending / worth doing. 뒤에는 반드시 동명사가 옵니다."}]},
  {s:"B",en:"That's easy to say from finance. My team has lived on this for a year and you're asking them to call it wasted.",
   ko:"재무에서야 하기 쉬운 말이죠. 우리 팀은 1년을 여기에 매달렸는데, 그걸 헛수고였다고 부르라는 겁니다.",
   notes:[{t:"That's easy to say from ~",k:"colloquial",m:"~쪽에서야 하기 쉬운 말이죠",tip:"상대의 위치를 짚어 반박하는 화법입니다. 날 서지 않게 쓰려면 뒤에 근거를 바로 붙이세요."},
          {t:"live on something",k:"idiom",m:"~에 매달려 살다",tip:"먹고산다는 뜻도 되지만 여기서는 「그것만 붙들고 지냈다」는 뜻입니다."}]},
  {s:"A",en:"I'm not calling it wasted. I'm saying the reason we started has changed and nobody has looked at it since.",
   ko:"헛수고라고 하는 게 아닙니다. 시작한 이유가 바뀌었는데 그 뒤로 아무도 들여다보지 않았다는 말이에요.",
   notes:[{t:"I'm not ~ing, I'm ~ing",k:"colloquial",m:"~하는 게 아니라 ~하는 겁니다",tip:"오해를 바로잡고 논점을 되돌리는 정형입니다. 회의에서 자주 필요합니다."},
          {t:"since",k:"grammar",m:"그 이후로",tip:"문장 끝에 홀로 놓인 since 는 「그때 이후 지금까지」를 뜻합니다."}]},
  {s:"B",en:"Fair enough. The case was built on volumes that never showed up, and I've been working around that for a while.",
   ko:"일리 있습니다. 사업 근거가 끝내 나타나지 않은 물량 위에 세워졌고, 저는 한동안 그걸 피해 가며 일해 왔어요.",
   notes:[{t:"the case",k:"business",m:"(투자·사업의) 근거, 명분",tip:"the business case for it = 그것을 해야 할 사업적 근거. 회의 필수어입니다."},
          {t:"work around ~",k:"phrasal",m:"~을 없애지 못한 채 피해 가며 처리하다",tip:"근본 해결이 아니라는 뉘앙스가 늘 따라붙습니다."}]},
  {s:"A",en:"That's the part I needed to hear out loud, because your reports have been amber for four quarters running.",
   ko:"제가 소리 내어 듣고 싶던 게 그겁니다. 그쪽 보고서는 네 분기 연속 노란불이었거든요.",
   notes:[{t:"out loud",k:"idiom",m:"소리 내어, 말로",tip:"say it out loud = 속으로만 알던 것을 말로 꺼내다. 회의에서 무게 있는 표현입니다."},
          {t:"four quarters running",k:"collocation",m:"네 분기 연속으로",tip:"three days running / two years running. 명사 뒤에 running 을 붙여 「연속」을 만듭니다."}]},
  {s:"B",en:"Amber is what you write when red gets you a meeting like this one and green gets you left alone.",
   ko:"빨간불을 쓰면 이런 회의에 불려 오고 초록불을 쓰면 아무도 안 건드리니까, 그래서 노란불을 씁니다.",
   notes:[{t:"amber",k:"business",m:"(신호등식 보고에서) 주의 단계",tip:"red / amber / green 을 RAG status 라 부릅니다. 미국식은 amber 대신 yellow 를 쓰기도 합니다."},
          {t:"get someone left alone",k:"colloquial",m:"아무도 안 건드리게 만들다",tip:"leave someone alone 을 사역으로 비튼 형태입니다. 구어에서 자연스럽게 통합니다."}]},
  {s:"A",en:"Then the reporting is broken, and I'd rather fix that than argue about your project on bad information.",
   ko:"그럼 보고 체계가 망가진 거고, 저는 나쁜 정보 위에서 그쪽 프로젝트를 두고 다투느니 그걸 고치겠습니다.",
   notes:[{t:"broken",k:"colloquial",m:"(제도·절차가) 제 구실을 못 하는",tip:"The process is broken. 고장 난 물건이 아니라 「작동하지 않는 구조」에 씁니다."},
          {t:"on bad information",k:"collocation",m:"잘못된 정보에 근거해서",tip:"act on information / decide on the numbers 처럼 on 이 근거를 나타냅니다."}]},
  {s:"B",en:"Fix it by making it survivable to say red. Right now the person who stops something is the person who failed.",
   ko:"빨간불을 말해도 살아남을 수 있게 만들어서 고치세요. 지금은 무언가를 멈춘 사람이 곧 실패한 사람입니다.",
   notes:[{t:"survivable",k:"colloquial",m:"(말해도) 살아남을 수 있는",tip:"Make disagreement survivable. 심리적 안전을 말할 때 쓰기 좋은 형용사입니다."},
          {t:"the person who ~ is the person who ~",k:"grammar",m:"~하는 사람이 곧 ~한 사람이다",tip:"같은 구조를 반복해 인과를 못 박는 수사입니다. 짧고 강하게 들립니다."}]},
  {s:"A",en:"Agreed, and that's on the company rather than on you. Killing a project early should read as judgment, not defeat.",
   ko:"동의합니다. 그건 그쪽이 아니라 회사 책임이에요. 프로젝트를 일찍 접는 건 패배가 아니라 판단으로 읽혀야 합니다.",
   notes:[{t:"that's on ~",k:"colloquial",m:"그건 ~의 책임입니다",tip:"That's on me. 로 짧게 책임을 인정할 때도 씁니다. 사과보다 담백합니다."},
          {t:"read as ~",k:"collocation",m:"~으로 읽히다, ~으로 받아들여지다",tip:"It reads as criticism. 의도가 아니라 「전달되는 인상」을 말합니다."}]},
  {s:"B",en:"Then say that out loud in the room, because everyone here has watched what happened to the last one.",
   ko:"그럼 그 말을 회의실에서 소리 내어 해 주세요. 여기 사람들은 지난번 그 사람이 어떻게 됐는지 다 봤으니까요.",
   notes:[{t:"in the room",k:"idiom",m:"(그 자리에 모인) 사람들 앞에서",tip:"the mood in the room / everyone in the room. 회의 자리 전체를 가리킵니다."},
          {t:"what happened to the last one",k:"grammar",m:"지난번 그것에게 벌어진 일",tip:"the last one 이 사람일 수도 사안일 수도 있어, 굳이 지목하지 않고 말할 때 편리합니다."}]},
  {s:"A",en:"I will. But I still need an answer on this one, and I'd rather get it from you than impose it from here.",
   ko:"그렇게 하겠습니다. 다만 이 건에 대한 답은 여전히 필요하고, 제가 밀어붙이기보다 그쪽에게서 듣고 싶습니다.",
   notes:[{t:"impose",k:"business",m:"(결정을) 일방적으로 부과하다",tip:"impose a decision / impose a deadline. 상대의 동의 없이 내린다는 뜻입니다."},
          {t:"an answer on ~",k:"collocation",m:"~에 대한 답",tip:"answer to a question / answer on an issue. 사안에는 on 을 씁니다."}]},
  {s:"B",en:"Give me a gate with real criteria and I'll take it. What I can't work with is a decision made in a corridor.",
   ko:"진짜 기준이 있는 관문을 주시면 받겠습니다. 제가 못 받는 건 복도에서 내려진 결정이에요.",
   notes:[{t:"a gate",k:"business",m:"단계별 관문 — 다음 단계로 갈지 새로 정하는 자리",tip:"stage gate / gate review 로 씁니다. 문이 아니라 「심사 지점」입니다."},
          {t:"a decision made in a corridor",k:"idiom",m:"복도에서 내려진 결정 — 공식 절차 밖의 결정",tip:"a corridor conversation 도 같은 계열입니다. 밀실 결정을 점잖게 지적합니다."}]},
  {s:"A",en:"That's reasonable. Three conditions, measured at the end of the quarter, and we both sign up to them beforehand.",
   ko:"합리적입니다. 조건 셋, 분기 말에 측정, 그리고 그 전에 우리 둘 다 그것에 합의합니다.",
   notes:[{t:"sign up to ~",k:"phrasal",m:"~에 합의하고 따르기로 하다",tip:"영국식은 sign up to, 미국식은 sign up for 를 즐겨 씁니다. 둘 다 통합니다."},
          {t:"beforehand",k:"collocation",m:"미리, 사전에",tip:"agreed beforehand 는 계약과 회의록 양쪽에서 힘을 갖는 말입니다."}]},
  {s:"B",en:"Beforehand matters. Criteria written after the numbers arrive are just a way of dressing up a decision already made.",
   ko:"「미리」가 중요합니다. 숫자가 나온 뒤에 쓴 기준은 이미 내린 결정을 그럴듯하게 꾸미는 방법일 뿐이에요.",
   notes:[{t:"dress up",k:"phrasal",m:"그럴듯하게 꾸미다, 포장하다",tip:"dress up the figures = 숫자를 좋게 보이도록 손보다. 비판적인 말입니다."},
          {t:"a way of ~ing",k:"grammar",m:"~하는 방법일 뿐인 것",tip:"just a way of avoiding the question 처럼 의도를 폭로할 때 자주 씁니다."}]},
  {s:"A",en:"You'll get them in writing this week. And if it passes, you get the funding without another round of this.",
   ko:"이번 주에 문서로 드리겠습니다. 통과하면 이런 자리를 한 번 더 거치지 않고 예산을 받습니다.",
   notes:[{t:"in writing",k:"idiom",m:"구두가 아니라 문서로",tip:"Get it in writing. 은 실무 조언의 정석 문장입니다."},
          {t:"another round of ~",k:"collocation",m:"~을 한 차례 더",tip:"another round of cuts / of reviews. 반복되는 절차를 지겹다는 투로 가리킵니다."}]},
  {s:"B",en:"And if it fails, I want to redeploy the team quickly, not leave them wondering for two months what happens next.",
   ko:"실패하면 팀을 빨리 다른 데로 돌리고 싶습니다. 두 달씩 다음이 뭔지 모른 채 두고 싶지 않아요.",
   notes:[{t:"redeploy",k:"business",m:"(인력을) 다른 업무로 돌리다",tip:"reassign 보다 조직적인 규모에 씁니다. 해고가 아니라 배치 전환입니다."},
          {t:"leave someone wondering",k:"collocation",m:"~을 궁금한 채로 방치하다",tip:"leave + 목적어 + 분사. leave them waiting / leave it running 도 같은 구조입니다."}]},
  {s:"A",en:"That I can promise. The worst part of stopping isn't stopping, it's the silence afterwards while nobody decides anything.",
   ko:"그건 약속할 수 있습니다. 멈추는 일에서 최악은 멈춤 자체가 아니라, 아무도 아무것도 정하지 않는 그 뒤의 침묵이에요.",
   notes:[{t:"The worst part of A isn't A, it's B",k:"colloquial",m:"A에서 최악은 A가 아니라 B다",tip:"통념을 뒤집는 수사입니다. 발표와 토론에서 기억에 남는 문장을 만듭니다."},
          {t:"afterwards",k:"collocation",m:"그 뒤에",tip:"미국식은 afterward. 문장 끝에 놓아 시간의 흐름을 매듭짓습니다."}]},
  {s:"B",en:"Then let's write it down. I'd rather be judged on a gate I agreed to than on the mood in a meeting.",
   ko:"그럼 문서로 남깁시다. 저는 회의 분위기로 평가받느니 제가 합의한 관문으로 평가받겠습니다.",
   notes:[{t:"be judged on ~",k:"collocation",m:"~을 기준으로 평가받다",tip:"We are judged on delivery, not effort. 전치사 on 을 통째로 외우세요."},
          {t:"the mood in a meeting",k:"idiom",m:"회의의 분위기 — 근거 없는 판단의 비유",tip:"기준 없는 결정을 점잖게 비판하는 말입니다."}]}
 ],
 keys:[
  {en:"sunk cost",ko:"매몰비용 — 이미 써서 회수할 수 없는 돈",ex:"The tooling is a sunk cost and it should not decide what we do next."},
  {en:"either way",ko:"어느 쪽이든 마찬가지로",ex:"Either way we pay for the line, so the question is what we get for it."},
  {en:"carry on",ko:"계속 진행하다",ex:"Nobody asked whether the pilot should carry on, only how to fund it."},
  {en:"amber",ko:"(신호등식 보고에서) 주의 단계",ex:"Everything is amber because red invites the questions nobody wants."},
  {en:"a stage gate",ko:"단계별 관문 — 다음 단계로 갈지 새로 정하는 자리",ex:"The stage gate forces a fresh decision instead of an automatic renewal."},
  {en:"dress up a decision",ko:"이미 내린 결정을 그럴듯하게 꾸미다",ex:"Criteria chosen afterwards just dress up a decision already made."},
  {en:"redeploy",ko:"(인력을) 다른 업무로 돌리다",ex:"If we stop, we redeploy the team within the month rather than eventually."},
  {en:"survivable",ko:"(말해도) 살아남을 수 있는",ex:"Make disagreement survivable and you will hear about problems earlier."}
 ],
 out:[
  {q:"Explain why money already spent should not affect the decision to continue.",hint:"sunk cost / gone either way / worth spending"},
  {q:"Your status report has been amber for a year. Say honestly what that means.",hint:"amber / gets you left alone / survivable to say red"},
  {q:"Propose stage gates to a project owner without sounding like a threat.",hint:"a gate with real criteria / beforehand / redeploy the team"}
 ]
}
