{
 id:"w4d1", day:26, cat:"도시·주거", level:"B2+",
 title:"Why Housing Never Gets Cheaper",
 titleKo:"집값은 왜 안 내려가는가 — 공급을 막는 것들",
 names:{A:"Nina (도시계획 연구자)", B:"Ethan (개발업체)"},
 brief:[
  "집값 이야기는 대개 <b>수요</b>에서 멈춥니다. 사람이 몰리고 돈이 풀렸다는 설명입니다. 그런데 같은 수요를 받고도 집값이 덜 오르는 도시가 있습니다. 차이는 <b>공급이 얼마나 빨리 따라붙느냐</b>에 있습니다.",
  "공급을 늦추는 것은 대개 기술이 아니라 <b>절차</b>입니다. 인허가에 몇 년이 걸리면 그 기간의 이자와 불확실성이 고스란히 원가가 됩니다. 그리고 절차 비용이 싼 집이나 비싼 집이나 똑같이 든다면, 짓는 쪽은 <b>비싼 집</b>을 짓습니다.",
  "여기서 <b>filtering</b>이라는 개념이 나옵니다. 새 집은 언제나 비싸고, 세월이 지나 다음 세대의 새 집이 생겨야 값이 내려간다는 것입니다. 그래서 「지금 비싼 집을 지어야 30년 뒤 싼 집이 생긴다」는 불편한 결론이 따라옵니다.",
  "마지막 층은 <b>정치</b>입니다. 새 공급으로 이득을 볼 사람은 아직 그 도시에 오지 않았고, 투표하는 사람은 이미 그 자산을 갖고 있습니다. 이 대화는 그 구조를 차분히 짚으면서, <b>절차를 예측 가능하게 만들자</b>는 현실적인 접점까지 갑니다."
 ],
 lines:[
  {s:"A",en:"Every city says it has a housing shortage, and every city has rules that make building harder.",
   ko:"도시마다 주택이 부족하다고 말하면서, 도시마다 짓기를 더 어렵게 만드는 규정을 갖고 있습니다.",
   notes:[{t:"a housing shortage",k:"business",m:"주택 부족",tip:"a shortage of ~ 로도 씁니다. a shortage of skilled workers."}]},
  {s:"B",en:"That's the part homeowners never hear, because the debate always gets framed as greedy developers.",
   ko:"집주인들이 절대 듣지 못하는 부분이 그겁니다. 논쟁이 늘 탐욕스러운 개발업자 구도로 짜이니까요.",
   notes:[{t:"get framed as ~",k:"business",m:"~ 라는 구도로 짜이다",tip:"frame(틀을 짜다)의 수동형입니다. 논쟁의 프레임을 말할 때 씁니다."},
          {t:"greedy",k:"collocation",m:"탐욕스러운",tip:"greedy developers / greedy landlords. 비난의 상투어입니다."}]},
  {s:"A",en:"I'd push back slightly, since plenty of developers do sit on land waiting for prices to climb.",
   ko:"조금 반박하자면, 값이 오르기를 기다리며 땅을 깔고 앉은 개발업자도 많습니다.",
   notes:[{t:"sit on land",k:"idiom",m:"땅을 놀리며 쥐고 있다",tip:"sit on cash / sit on inventory 도 같은 형태입니다."},
          {t:"I'd push back slightly",k:"colloquial",m:"조금 이견을 붙이자면",tip:"전면 반박이 아니라 부분 반박을 예고하는 말입니다."}]},
  {s:"B",en:"We hold land because approval takes four years, and nobody finances a project that might never start.",
   ko:"인허가에 4년이 걸리니까 땅을 쥐고 있는 겁니다. 시작도 못 할 수 있는 사업에 아무도 돈을 대지 않으니까요.",
   notes:[{t:"approval",k:"business",m:"인허가, 승인",tip:"get approval / grant approval. 행정 절차의 핵심 명사입니다."},
          {t:"finance a project",k:"collocation",m:"사업에 자금을 대다",tip:"동사로 쓰인 finance 입니다. fund 보다 격식 있습니다."}]},
  {s:"A",en:"So the delay itself becomes the cost, which then gets passed straight into the asking price.",
   ko:"그럼 지연 자체가 비용이 되고, 그게 그대로 호가에 얹히는 거네요.",
   notes:[{t:"pass into the price",k:"business",m:"가격에 전가되다",tip:"pass through 와 같은 뜻입니다. 원가 전가를 말합니다."},
          {t:"the asking price",k:"business",m:"부르는 값, 호가",tip:"파는 쪽이 제시한 가격입니다. the selling price 와 구별됩니다."}]},
  {s:"B",en:"Exactly, and every month of review is interest we're paying on land that earns nothing.",
   ko:"정확합니다. 심사 한 달 한 달이, 아무것도 벌지 않는 땅에 물고 있는 이자입니다.",
   notes:[{t:"land that earns nothing",k:"collocation",m:"아무 수익도 내지 않는 땅",tip:"유휴 자산을 표현하는 자연스러운 방식입니다."}]},
  {s:"A",en:"Then why does nearly every proposal still pencil out at the luxury end of the market?",
   ko:"그런데 왜 거의 모든 사업안이 여전히 고급 주택 쪽에서만 수지가 맞는 겁니까?",
   notes:[{t:"pencil out",k:"idiom",m:"계산이 맞다, 수지가 맞다",tip:"부동산과 사업 검토에서 아주 자주 쓰는 구어입니다."},
          {t:"the luxury end",k:"collocation",m:"고급 시장 쪽",tip:"the low end / the high end 와 함께 외워 두세요."}]},
  {s:"B",en:"Because if the process costs the same for cheap flats and expensive ones, you build the expensive ones.",
   ko:"싼 집이든 비싼 집이든 절차 비용이 똑같이 든다면, 비싼 쪽을 짓게 되니까요.",
   notes:[{t:"the process costs the same",k:"grammar",m:"절차 비용이 똑같이 들다",tip:"cost 가 「~만큼의 비용이 들다」로 쓰인 형태입니다."}]},
  {s:"A",en:"That's a fair point, and it explains why filtering takes a generation instead of a decade.",
   ko:"타당한 지적이고, 필터링이 10년이 아니라 한 세대가 걸리는 이유도 설명되네요.",
   notes:[{t:"That's a fair point.",k:"colloquial",m:"타당한 지적입니다",tip:"상대 논거를 인정하고 넘어가는 표준 표현입니다."}]},
  {s:"B",en:"What's filtering? I know the idea, but I've never heard anyone in the trade name it.",
   ko:"필터링이 뭡니까? 개념은 아는데, 업계에서 그렇게 부르는 건 들어 본 적이 없어서요.",
   notes:[{t:"in the trade",k:"idiom",m:"그 업계에서",tip:"in the industry 의 구어체입니다. 현장 종사자를 가리킵니다."},
          {t:"name something",k:"business",m:"이름을 붙여 부르다",tip:"개념에 명칭을 부여한다는 뜻입니다."}]},
  {s:"A",en:"New housing is always expensive, and it only becomes affordable as it ages and newer stock arrives.",
   ko:"새 집은 언제나 비쌉니다. 세월이 지나고 더 새 물량이 들어와야 비로소 감당할 만해지죠.",
   notes:[{t:"affordable",k:"business",m:"감당할 만한 가격의",tip:"cheap 과 달리 「소득 대비」의 뉘앙스입니다."},
          {t:"stock",k:"business",m:"(주택) 물량, 재고",tip:"housing stock 은 그 도시의 전체 주택 수를 뜻합니다."}]},
  {s:"B",en:"So the only way to get cheap housing in thirty years is to build expensive housing right now.",
   ko:"그럼 30년 뒤에 싼 집을 가지려면 지금 비싼 집을 지어야 한다는 얘기네요.",
   notes:[{t:"The only way to A is to B",k:"grammar",m:"A 하는 유일한 방법은 B 하는 것이다",tip:"불편한 결론을 압축할 때 유용합니다."}]},
  {s:"A",en:"Broadly, yes, though that argument is impossible to sell to somebody who needs a flat this year.",
   ko:"대체로 그렇습니다. 다만 올해 당장 집이 필요한 사람에게는 도저히 팔 수 없는 논리죠.",
   notes:[{t:"Broadly, yes",k:"colloquial",m:"대체로 그렇습니다",tip:"조건을 달고 동의하는 시작입니다."},
          {t:"impossible to sell",k:"collocation",m:"도저히 설득할 수 없는",tip:"a hard sell 의 강화형입니다."}]},
  {s:"B",en:"Which is why the politics never move, since the people who benefit haven't arrived in the city yet.",
   ko:"그래서 정치가 꿈쩍하지 않는 거죠. 이득을 볼 사람들이 아직 그 도시에 오지도 않았으니까요.",
   notes:[{t:"the politics never move",k:"idiom",m:"정치가 꿈쩍도 하지 않는다",tip:"the politics 는 「정치적 역학」이라는 뜻의 단수 취급입니다."}]},
  {s:"A",en:"And the people who do vote already own the asset that any new supply would make cheaper.",
   ko:"그리고 실제로 투표하는 사람들은, 새 공급이 값을 떨어뜨릴 바로 그 자산을 이미 갖고 있고요.",
   notes:[{t:"do vote",k:"grammar",m:"실제로 투표하다",tip:"동사 앞의 do 는 강조입니다. I do think so."}]},
  {s:"B",en:"You've just described the whole problem in one sentence, and it isn't one that planning can fix.",
   ko:"문제 전체를 한 문장으로 말씀하셨네요. 그리고 그건 도시계획으로 고칠 수 있는 종류가 아니고요.",
   notes:[{t:"describe something in one sentence",k:"collocation",m:"한 문장으로 요약해 말하다",tip:"put it in one line 도 같은 뜻입니다."}]},
  {s:"A",en:"Planning can fix the part that's procedural, like approving by right instead of case by case.",
   ko:"절차에 해당하는 부분은 고칠 수 있습니다. 건건이 심사하는 대신 요건만 맞으면 승인하는 식으로요.",
   notes:[{t:"by right",k:"business",m:"요건만 갖추면 자동으로 (승인되는)",tip:"재량 심사가 아니라 규정 충족만 보는 방식입니다."},
          {t:"case by case",k:"idiom",m:"건건이, 사안마다",tip:"일관된 규칙이 없다는 비판의 뉘앙스로도 씁니다."}]},
  {s:"B",en:"That would change everything for us, because uncertainty is what we actually price into a bid.",
   ko:"그건 우리에게 모든 걸 바꿔 놓습니다. 우리가 입찰가에 실제로 얹는 게 불확실성이거든요.",
   notes:[{t:"price something into ~",k:"business",m:"~ 에 값으로 반영해 넣다",tip:"price in risk / price in a delay."}]},
  {s:"A",en:"Then let's argue for predictable rules rather than looser ones, which is a far easier case to make.",
   ko:"그럼 느슨한 규칙이 아니라 예측 가능한 규칙을 주장합시다. 그쪽이 훨씬 설득하기 쉬우니까요.",
   notes:[{t:"predictable rather than looser",k:"collocation",m:"느슨한 것이 아니라 예측 가능한",tip:"규제 완화 논쟁의 프레임을 바꾸는 표현입니다."},
          {t:"an easier case to make",k:"idiom",m:"더 설득하기 쉬운 주장",tip:"make a case for ~ 에서 온 표현입니다."}]},
  {s:"B",en:"Agreed. Nobody defends a slow process out loud, so that's the door worth pushing on.",
   ko:"동의합니다. 느린 절차를 대놓고 옹호하는 사람은 없으니, 밀어 볼 만한 문은 그쪽이죠.",
   notes:[{t:"defend something out loud",k:"collocation",m:"대놓고 옹호하다",tip:"속으로는 반대하지 않아도 공개적으로는 못 한다는 뉘앙스입니다."},
          {t:"the door worth pushing on",k:"idiom",m:"밀어 볼 만한 문",tip:"push on an open door(열린 문을 밀다)에서 온 비유입니다."}]}
 ],
 keys:[
  {en:"sit on land",ko:"땅을 놀리며 쥐고 있다",ex:"They sit on land for years waiting for the zoning to change."},
  {en:"pencil out",ko:"수지가 맞다",ex:"The project only pencils out if we go twelve storeys."},
  {en:"pass into the price",ko:"가격에 전가되다",ex:"Every month of delay passes straight into the price."},
  {en:"affordable",ko:"감당할 만한 가격의",ex:"Housing becomes affordable as it ages, not as it is built."},
  {en:"by right",ko:"요건만 갖추면 자동으로 승인되는",ex:"Approve it by right and half the uncertainty disappears."},
  {en:"case by case",ko:"건건이, 사안마다",ex:"Reviewing it case by case is what makes the timeline unpredictable."},
  {en:"price something into ~",ko:"~ 에 값으로 반영해 넣다",ex:"We price the delay into every bid we submit."},
  {en:"an easier case to make",ko:"더 설득하기 쉬운 주장",ex:"Predictable rules are an easier case to make than looser ones."}
 ],
 out:[
  {q:"Explain why slow approvals end up raising the price of housing.",hint:"approval / pass into the price / land that earns nothing"},
  {q:"Explain the idea of filtering, then say what's uncomfortable about it.",hint:"affordable / stock / The only way to A is to B"},
  {q:"Propose a reform that both a planner and a developer could support.",hint:"by right / case by case / an easier case to make"}
 ]
},
{
 id:"w4d2", day:27, cat:"미디어·주의력", level:"B2+",
 title:"The Attention You Sell",
 titleKo:"팔려 나가는 주의력 — 알고리즘과 분노의 경제학",
 names:{A:"Priya (뉴스 편집자)", B:"Sam (추천 알고리즘 담당)"},
 brief:[
  "무료로 보는 서비스에서 <b>값을 치르는 것은 돈이 아니라 시간</b>입니다. 그리고 시간을 파는 사업에서 좋은 지표는 하나뿐입니다. 사람들이 <b>얼마나 오래 머무느냐</b>입니다.",
  "여기서 기묘한 일이 벌어집니다. 오래 머물게 하는 감정과 좋은 정보를 주는 감정이 <b>같지 않기</b> 때문입니다. 분노와 불안은 사람을 붙잡아 두고, 차분한 설명은 그렇지 못합니다. 알고리즘은 그 차이를 알아서 학습합니다.",
  "누가 악의를 품은 것도 아닙니다. <b>체류 시간을 최적화하라</b>는 지시 하나가 있었을 뿐입니다. 13회차에서 본 굿하트의 법칙이 여기서 다시 나타납니다. 지표가 목표가 되는 순간 그 지표는 일을 설명하기를 그만둡니다.",
  "이 대화의 핵심은 <b>누구를 탓할 것인가</b>가 아니라 <b>무엇을 측정할 것인가</b>입니다. 「나중에 후회했는가」, 「다시 찾아왔는가」처럼 느리고 지저분한 지표를 쓰자는 제안까지 갑니다."
 ],
 lines:[
  {s:"A",en:"Our best-read story last month was also the one I'm least proud of publishing.",
   ko:"지난달 가장 많이 읽힌 기사가, 하필 제가 내보낸 것 중 가장 자랑스럽지 않은 기사였습니다.",
   notes:[{t:"best-read",k:"collocation",m:"가장 많이 읽힌",tip:"best-selling, best-loved 처럼 best- 로 만드는 복합어입니다."},
          {t:"the one I'm least proud of",k:"grammar",m:"가장 자랑스럽지 않은 것",tip:"최상급 least 로 완곡하게 말하는 방식입니다."}]},
  {s:"B",en:"That's not an accident, and honestly it's what the system is built to find for you.",
   ko:"그건 우연이 아닙니다. 솔직히 시스템이 당신 대신 찾아내도록 만들어진 게 바로 그거예요.",
   notes:[{t:"That's not an accident.",k:"colloquial",m:"그건 우연이 아닙니다",tip:"구조적 원인을 짚는 짧고 강한 문장입니다."}]},
  {s:"A",en:"Built by whom, though? Nobody in my newsroom asked for outrage to travel faster.",
   ko:"누가 그렇게 만들었죠? 우리 편집국에서 분노가 더 빨리 퍼지게 해 달라고 한 사람은 없습니다.",
   notes:[{t:"travel",k:"collocation",m:"(소문·기사가) 퍼지다",tip:"News travels fast. 확산을 말하는 자동사 용법입니다."}]},
  {s:"B",en:"Nobody asked. We optimized for time on page, and the system worked out the rest by itself.",
   ko:"아무도 요청하지 않았습니다. 우리는 체류 시간을 최적화했고, 나머지는 시스템이 알아서 알아냈죠.",
   notes:[{t:"optimize for ~",k:"business",m:"~ 를 기준으로 최적화하다",tip:"무엇을 최대화할지 정하는 행위입니다. optimize for cost / for speed."},
          {t:"work something out",k:"phrasal",m:"알아내다, 풀어내다",tip:"여기서는 사람이 아니라 시스템이 주어입니다."}]},
  {s:"A",en:"So the machine learned that anger holds people, which is something no editor would write down.",
   ko:"그럼 기계가 분노는 사람을 붙잡아 둔다는 걸 배운 거군요. 어떤 편집자도 문서로 적지 않을 사실을요.",
   notes:[{t:"hold people",k:"collocation",m:"사람을 붙잡아 두다",tip:"독자나 시청자를 이탈시키지 않는다는 뜻입니다."}]},
  {s:"B",en:"It learned what correlates with staying, and anger simply happens to correlate very well.",
   ko:"머무는 것과 무엇이 같이 움직이는지를 배운 겁니다. 분노가 유난히 잘 맞아떨어졌을 뿐이고요.",
   notes:[{t:"correlate with ~",k:"business",m:"~ 와 함께 움직이다, 상관관계가 있다",tip:"인과가 아니라는 점이 중요합니다. cause 와 구별하세요."},
          {t:"happen to ~",k:"grammar",m:"우연히 ~ 하다",tip:"의도하지 않았음을 드러내는 표현입니다."}]},
  {s:"A",en:"That's Goodhart's law wearing a new coat, and it's the same failure we saw with newsroom quotas.",
   ko:"굿하트의 법칙이 새 옷을 입은 거네요. 편집국 할당량에서 봤던 것과 같은 실패라고 봅니다.",
   notes:[{t:"wearing a new coat",k:"idiom",m:"새 옷을 입은, 겉모습만 바뀐",tip:"오래된 문제가 다시 나타났을 때 쓰는 비유입니다."},
          {t:"a quota",k:"business",m:"할당량",tip:"기사 건수처럼 숫자로 찍어 내리는 목표입니다."}]},
  {s:"B",en:"Fair, though a quota is a person's decision and a model is a million small ones nobody reads.",
   ko:"타당합니다. 다만 할당량은 사람의 결정이고, 모델은 아무도 읽지 않는 작은 결정 백만 개죠.",
   notes:[{t:"a million small ones",k:"collocation",m:"작은 결정 수백만 개",tip:"ones 로 앞의 decisions 를 받는 대용 표현입니다."}]},
  {s:"A",en:"Which makes it harder to argue with, because there's no memo anyone can point at.",
   ko:"그래서 따지기가 더 어렵습니다. 누가 가리킬 수 있는 문서가 없으니까요.",
   notes:[{t:"point at ~",k:"phrasal",m:"~ 를 가리키다, 지목하다",tip:"책임 소재를 다툴 때 자주 쓰는 구동사입니다."}]},
  {s:"B",en:"There's a dashboard, and I'd argue that's worse, since everyone treats it as the truth.",
   ko:"대시보드가 있죠. 오히려 그게 더 나쁘다고 봅니다. 다들 그걸 진실로 취급하니까요.",
   notes:[{t:"treat A as B",k:"collocation",m:"A를 B로 취급하다",tip:"treat it as data, not instructions. 실무에서 아주 자주 씁니다."}]},
  {s:"A",en:"Then change what the dashboard counts, because that's the only lever either of us actually holds.",
   ko:"그럼 대시보드가 무엇을 세는지를 바꾸죠. 우리 둘 다 실제로 쥐고 있는 지렛대는 그것뿐이니까요.",
   notes:[{t:"a lever",k:"business",m:"지렛대, 움직일 수 있는 수단",tip:"the only lever we hold. 영향력의 범위를 말합니다."}]},
  {s:"B",en:"Count what, though? Everything honest is slow, and slow numbers lose every budget meeting.",
   ko:"그런데 뭘 세죠? 정직한 건 전부 느리고, 느린 숫자는 예산 회의에서 늘 집니다.",
   notes:[{t:"lose a meeting",k:"colloquial",m:"회의에서 지다, 설득에 실패하다",tip:"win the room 과 짝을 이룹니다."}]},
  {s:"A",en:"Count whether they came back a week later, which is slow but much harder to fake.",
   ko:"일주일 뒤에 다시 왔는지를 세세요. 느리지만 조작하기는 훨씬 어렵습니다.",
   notes:[{t:"hard to fake",k:"collocation",m:"조작하기 어려운",tip:"지표를 고를 때의 핵심 기준입니다."}]},
  {s:"B",en:"We tried that, and it barely moves, which makes it useless for telling two designs apart.",
   ko:"해 봤는데 거의 움직이지 않습니다. 그래서 설계안 둘을 구별하는 데는 쓸모가 없어요.",
   notes:[{t:"tell A and B apart",k:"idiom",m:"A와 B를 구별하다",tip:"tell them apart / tell the difference 로도 씁니다."}]},
  {s:"A",en:"Then ask them outright whether the time they spent was time they wanted to spend.",
   ko:"그럼 대놓고 물어보세요. 쓴 시간이 본인이 쓰고 싶었던 시간이었는지를요.",
   notes:[{t:"ask someone outright",k:"collocation",m:"대놓고 묻다",tip:"돌려 말하지 않고 직접 묻는 것입니다."},
          {t:"time they wanted to spend",k:"grammar",m:"쓰고 싶었던 시간",tip:"관계절이 생략된 형태입니다. 구어에서 자연스럽습니다."}]},
  {s:"B",en:"Surveys are noisy, but I'll give you that regret is the thing we've never once measured.",
   ko:"설문은 잡음이 많죠. 다만 후회는 우리가 단 한 번도 재 본 적 없는 것이라는 건 인정하겠습니다.",
   notes:[{t:"I'll give you that",k:"idiom",m:"그건 인정하겠습니다",tip:"상대 주장 하나를 받아들일 때의 관용구입니다."},
          {t:"noisy",k:"business",m:"잡음이 많은, 편차가 큰",tip:"데이터의 신뢰도를 말할 때 씁니다."}]},
  {s:"A",en:"And regret is exactly what separates a story people needed from one that merely held them.",
   ko:"그리고 필요했던 기사와 그냥 붙잡아 둔 기사를 가르는 게 바로 그 후회입니다.",
   notes:[{t:"separate A from B",k:"collocation",m:"A와 B를 구분 짓다",tip:"what separates X from Y 는 정의를 내리는 틀입니다."}]},
  {s:"B",en:"Put it that way and it stops sounding like ethics and starts sounding like product work.",
   ko:"그렇게 말하니 윤리 얘기로 들리지 않고 제품 일처럼 들리기 시작하네요.",
   notes:[{t:"Put it that way and ~",k:"grammar",m:"그렇게 표현하면 ~ 하다",tip:"명령문 + and 로 조건을 만드는 구어 형태입니다."}]},
  {s:"A",en:"That's deliberate, because nothing changes in your world until it arrives as a metric.",
   ko:"일부러 그렇게 말한 겁니다. 당신네 세계에서는 지표로 도착하기 전까지 아무것도 바뀌지 않으니까요.",
   notes:[{t:"deliberate",k:"business",m:"의도적인, 일부러 한",tip:"That's deliberate. 은 「일부러 그런 겁니다」라는 짧은 답입니다."}]},
  {s:"B",en:"Then write the metric with me, and I'll take it into the review before the quarter closes.",
   ko:"그럼 그 지표를 저와 같이 쓰시죠. 분기가 끝나기 전에 제가 검토 회의에 올리겠습니다.",
   notes:[{t:"take something into a review",k:"collocation",m:"검토 회의에 올리다",tip:"안건을 공식 절차에 태운다는 뜻입니다."}]}
 ],
 keys:[
  {en:"optimize for ~",ko:"~ 를 기준으로 최적화하다",ex:"Whatever you optimize for is what you will eventually get."},
  {en:"correlate with ~",ko:"~ 와 상관관계가 있다",ex:"Anger correlates with staying, which is not the same as helping."},
  {en:"treat A as B",ko:"A를 B로 취급하다",ex:"Everyone treats the dashboard as the truth about the work."},
  {en:"a lever",ko:"지렛대, 움직일 수 있는 수단",ex:"Changing what we count is the only lever we actually hold."},
  {en:"hard to fake",ko:"조작하기 어려운",ex:"A slow measure is useful precisely because it's hard to fake."},
  {en:"tell A and B apart",ko:"A와 B를 구별하다",ex:"The number barely moves, so it can't tell two designs apart."},
  {en:"I'll give you that",ko:"그건 인정하겠습니다",ex:"I'll give you that we have never once measured regret."},
  {en:"separate A from B",ko:"A와 B를 구분 짓다",ex:"Regret is what separates a story people needed from one that held them."}
 ],
 out:[
  {q:"Explain how a platform ends up promoting anger without anyone deciding to.",hint:"optimize for ~ / correlate with ~ / That's not an accident"},
  {q:"Argue that the dashboard, not the people, is the thing to fix.",hint:"treat A as B / a lever / a quota"},
  {q:"Propose a measure that is slower but harder to game, and defend it.",hint:"hard to fake / tell A and B apart / separate A from B"}
 ]
},
{
 id:"w4d3", day:28, cat:"교육·평가", level:"B2+",
 title:"What a Degree Still Signals",
 titleKo:"학위는 아직 무엇을 말해 주는가 — 신호와 실력 사이",
 names:{A:"Omar (채용 담당)", B:"Lise (대학 교수)"},
 brief:[
  "학위가 값어치를 갖는 이유에 대해서는 오래된 두 가지 설명이 있습니다. 하나는 학교가 <b>실제로 능력을 키워 준다</b>는 것이고, 다른 하나는 학위가 <b>원래 가진 성질을 드러내는 신호</b>일 뿐이라는 것입니다.",
  "신호 쪽 설명은 이렇습니다. 4년을 버티고, 재미없는 과제를 마감에 맞추고, 낯선 사람들과 조를 짜서 결과를 내는 일은 <b>아무나 견디지 못합니다</b>. 그래서 학위는 배운 내용이 아니라 <b>견뎠다는 사실</b>을 증명합니다.",
  "채용하는 쪽에서 보면 이건 냉정한 이야기지만 편리한 도구이기도 합니다. 지원자 수백 명을 걸러야 할 때, 학위는 <b>싸고 빠른 필터</b>입니다. 문제는 그 필터가 <b>걸러 내는 사람</b>이 누구인지를 아무도 세지 않는다는 데 있습니다.",
  "이 대화는 어느 쪽이 옳은지를 가리는 대신, <b>그래서 무엇을 대신 볼 것인가</b>로 넘어갑니다. 과제형 평가, 수습 기간, 포트폴리오 같은 대안의 비용까지 솔직하게 다룹니다."
 ],
 lines:[
  {s:"A",en:"I screened four hundred applications last month, and the degree did most of the filtering.",
   ko:"지난달에 지원서 400건을 검토했는데, 거르는 일의 대부분을 학위가 했습니다.",
   notes:[{t:"screen applications",k:"business",m:"지원서를 선별하다",tip:"screen out(걸러 내다)과 함께 채용 실무의 기본 동사입니다."}]},
  {s:"B",en:"That's the hardest part of my job to defend, because I never agreed to be your filter.",
   ko:"제 일에서 가장 방어하기 어려운 부분이 그겁니다. 저는 당신네 필터가 되겠다고 한 적이 없거든요.",
   notes:[{t:"hard to defend",k:"collocation",m:"방어하기 어려운, 정당화하기 어려운",tip:"defend a decision / defend a position 과 같은 계열입니다."}]},
  {s:"A",en:"Nobody asked you to, but the market turned your certificate into one anyway.",
   ko:"아무도 그래 달라고 하지 않았죠. 그래도 시장이 그 졸업장을 필터로 만들어 버렸습니다.",
   notes:[{t:"turn A into B",k:"phrasal",m:"A를 B로 바꿔 놓다",tip:"의도하지 않은 변형을 말할 때 자연스럽습니다."}]},
  {s:"B",en:"Then tell me honestly whether you think we taught them anything they actually use.",
   ko:"그럼 솔직히 말씀해 주세요. 우리가 그들이 실제로 쓰는 걸 가르쳤다고 보십니까?",
   notes:[{t:"Tell me honestly whether ~",k:"grammar",m:"~ 인지 솔직히 말해 주세요",tip:"솔직한 답을 요구하는 정중한 틀입니다."}]},
  {s:"A",en:"Some of it, though what I'm really buying is evidence that they finished something difficult.",
   ko:"일부는요. 다만 제가 실제로 사는 건 어려운 일을 끝까지 해냈다는 증거입니다.",
   notes:[{t:"what I'm really buying is ~",k:"grammar",m:"제가 실제로 사는 것은 ~ 입니다",tip:"진짜 목적을 드러내는 강조 구문입니다."}]},
  {s:"B",en:"So the content is almost beside the point, and four years of persistence is the product.",
   ko:"그럼 내용은 거의 부차적이고, 4년의 끈기가 상품인 셈이네요.",
   notes:[{t:"beside the point",k:"idiom",m:"요점에서 벗어난, 중요하지 않은",tip:"That's beside the point. 논점 이탈을 지적할 때도 씁니다."},
          {t:"persistence",k:"business",m:"끈기, 버텨 내는 힘",tip:"grit 과 비슷하지만 더 중립적이고 격식 있습니다."}]},
  {s:"A",en:"That's the signalling argument, and I'd say it explains more of my industry than anyone admits.",
   ko:"그게 신호 이론이죠. 제 업계는 다들 인정하는 것보다 그걸로 더 많이 설명된다고 봅니다.",
   notes:[{t:"signalling",k:"business",m:"신호 기능, 시그널링",tip:"능력을 직접 보여 주는 대신 증명서로 대신하는 것입니다."},
          {t:"more than anyone admits",k:"collocation",m:"아무도 인정하지 않을 만큼 많이",tip:"불편한 진실을 말할 때의 완곡한 강조입니다."}]},
  {s:"B",en:"If that's all it is, then you're paying for a sorting machine you could build much more cheaply.",
   ko:"그게 전부라면, 훨씬 싸게 만들 수 있는 분류 기계에 돈을 내고 계신 겁니다.",
   notes:[{t:"a sorting machine",k:"idiom",m:"사람을 골라 내는 장치",tip:"제도를 기능으로 환원해 부르는 비판적 비유입니다."}]},
  {s:"A",en:"Cheaply for whom? Every alternative I've tried moved the cost onto my own team.",
   ko:"누구에게 싸다는 거죠? 제가 시도해 본 대안은 전부 비용을 우리 팀으로 옮겨 놓았습니다.",
   notes:[{t:"Cheaply for whom?",k:"colloquial",m:"누구에게 싸다는 겁니까",tip:"비용이 사라진 게 아니라 이동했음을 지적하는 반문입니다."}]},
  {s:"B",en:"Such as? I'd like to know what you actually ran, not what the textbooks recommend.",
   ko:"예를 들면요? 교과서가 권하는 게 아니라 실제로 돌려 보신 걸 알고 싶습니다.",
   notes:[{t:"what you actually ran",k:"collocation",m:"실제로 시행해 본 것",tip:"run a pilot / run a trial 에서 온 표현입니다."}]},
  {s:"A",en:"Work samples. They predict performance far better, and they take three hours each to mark.",
   ko:"과제형 평가요. 성과 예측력은 훨씬 좋은데, 채점에 건당 세 시간이 듭니다.",
   notes:[{t:"a work sample",k:"business",m:"실무 과제형 평가",tip:"실제 업무와 비슷한 과제를 주고 결과를 보는 방식입니다."},
          {t:"mark",k:"business",m:"채점하다",tip:"영국식입니다. 미국식은 grade 입니다."}]},
  {s:"B",en:"Three hours times four hundred is a number no hiring manager will ever sign off on.",
   ko:"세 시간 곱하기 400이면, 어떤 채용 담당 임원도 결재하지 않을 숫자죠.",
   notes:[{t:"sign off on ~",k:"business",m:"결재하다, 승인하다",tip:"책임을 지고 서명한다는 뉘앙스가 핵심입니다."}]},
  {s:"A",en:"Which is exactly why the degree survives, and it isn't because anyone thinks it's precise.",
   ko:"학위가 살아남는 이유가 정확히 그겁니다. 누가 그걸 정밀하다고 생각해서가 아니고요.",
   notes:[{t:"survive",k:"business",m:"살아남다, 계속 쓰이다",tip:"제도나 관행이 유지되는 것을 말할 때 자주 씁니다."}]},
  {s:"B",en:"Then at least count who the filter removes, because that number never appears in your report.",
   ko:"그럼 적어도 그 필터가 누구를 걸러 내는지는 세어 보세요. 보고서에 절대 안 나오는 숫자니까요.",
   notes:[{t:"count who it removes",k:"grammar",m:"걸러 내는 대상을 세어 보다",tip:"who절을 목적어로 쓰는 형태입니다."}]},
  {s:"A",en:"We don't have that data, which is a poor excuse and I know it.",
   ko:"그 데이터가 없습니다. 형편없는 변명이라는 건 저도 압니다.",
   notes:[{t:"a poor excuse",k:"collocation",m:"변변찮은 변명",tip:"자기 논리의 약점을 스스로 인정하는 표현입니다."}]},
  {s:"B",en:"Then run one round without the screen and compare who you would have thrown away.",
   ko:"그럼 한 번은 그 필터 없이 돌려 보고, 원래대로면 버렸을 사람이 누구인지 비교해 보세요.",
   notes:[{t:"throw someone away",k:"idiom",m:"사람을 버리다, 기회를 주지 않고 탈락시키다",tip:"강한 표현이라 비판할 때 효과적입니다."}]},
  {s:"A",en:"That's testable, and honestly it's cheaper than the argument we've been having for years.",
   ko:"그건 시험해 볼 수 있네요. 솔직히 우리가 몇 년째 하고 있는 논쟁보다 쌉니다.",
   notes:[{t:"testable",k:"business",m:"시험해 볼 수 있는",tip:"주장을 검증 가능한 형태로 바꿀 때 쓰는 단어입니다."}]},
  {s:"B",en:"And if the screen turns out to be right, you'll have something better than tradition to point to.",
   ko:"그리고 그 필터가 옳은 걸로 드러나면, 관행 말고 더 나은 근거를 갖게 되실 테고요.",
   notes:[{t:"turn out to be ~",k:"grammar",m:"~ 인 것으로 드러나다",tip:"결과가 밝혀진 뒤를 말하는 형태입니다."},
          {t:"point to ~",k:"phrasal",m:"근거로 제시하다",tip:"something to point to = 내세울 근거."}]},
  {s:"A",en:"That's the part I want, because right now I'm defending a habit rather than a finding.",
   ko:"제가 원하는 게 그겁니다. 지금은 발견이 아니라 습관을 방어하고 있으니까요.",
   notes:[{t:"a habit rather than a finding",k:"collocation",m:"발견이 아니라 습관",tip:"근거 없는 관행을 꼬집는 짝 표현입니다."}]},
  {s:"B",en:"Then run it this cycle, and I'll send you the students I think your filter would miss.",
   ko:"그럼 이번 채용에서 돌려 보세요. 그 필터가 놓칠 것 같은 학생들은 제가 보내 드리겠습니다.",
   notes:[{t:"this cycle",k:"business",m:"이번 (채용) 회차",tip:"hiring cycle / budget cycle 처럼 주기를 가리킵니다."}]}
 ],
 keys:[
  {en:"screen applications",ko:"지원서를 선별하다",ex:"We screened four hundred applications in a single week."},
  {en:"beside the point",ko:"요점에서 벗어난",ex:"What they studied is almost beside the point to me."},
  {en:"signalling",ko:"신호 기능",ex:"Signalling explains more of hiring than most people admit."},
  {en:"a work sample",ko:"실무 과제형 평가",ex:"Work samples predict performance far better than a transcript."},
  {en:"sign off on ~",ko:"결재하다, 승인하다",ex:"No manager will sign off on twelve hundred hours of marking."},
  {en:"throw someone away",ko:"기회를 주지 않고 탈락시키다",ex:"Count who the filter throws away before you defend it."},
  {en:"turn out to be ~",ko:"~ 인 것으로 드러나다",ex:"If the screen turns out to be right, you'll have evidence."},
  {en:"point to ~",ko:"근거로 제시하다",ex:"You'd have a finding to point to instead of a habit."}
 ],
 out:[
  {q:"Explain the signalling view of a degree in your own words.",hint:"signalling / beside the point / persistence"},
  {q:"Argue that an employer's cheap filter moves costs rather than removing them.",hint:"screen applications / Cheaply for whom? / sign off on ~"},
  {q:"Propose a test that would settle the argument, and say what it costs.",hint:"a work sample / throw someone away / turn out to be ~"}
 ]
},
{
 id:"w4d4", day:29, cat:"건강·의료", level:"B2+",
 title:"The Test That Finds Too Much",
 titleKo:"너무 많이 찾아내는 검사 — 과잉진단의 역설",
 names:{A:"Jinho (환자, 종합검진 애호가)", B:"Dr. Wen (내과의)"},
 brief:[
  "검사는 많이 할수록 좋다는 생각은 자연스럽습니다. 일찍 찾으면 일찍 고칠 수 있으니까요. 그런데 의학에서 오래 논쟁이 되어 온 사실이 하나 있습니다. <b>찾아낸 것이 전부 병은 아니라는 것</b>입니다.",
  "몸에는 평생 아무 해도 끼치지 않고 지나갈 이상 소견이 적지 않습니다. 검사를 촘촘히 하면 그것들이 걸려 나옵니다. 여기서 <b>과잉진단(overdiagnosis)</b>이 생깁니다. 병을 찾아낸 것이 아니라, <b>병이 되지 않았을 것</b>을 찾아낸 상태입니다.",
  "문제는 찾아낸 뒤입니다. 추가 검사, 조직 검사, 때로는 수술이 이어지고, 각 단계마다 작지만 실재하는 위험이 붙습니다. 그리고 <b>통계는 좋아 보입니다</b>. 해롭지 않았을 사례가 생존자 숫자에 더해지기 때문입니다.",
  "이 대화는 「검사를 하지 말라」는 이야기가 아닙니다. <b>이 검사가 내 결정을 바꾸는가</b>라는 질문을 배우는 자리입니다. 의사와 환자가 쓰는 표현이 함께 나오니, 실제 진료실에서 그대로 써 보실 수 있습니다."
 ],
 lines:[
  {s:"A",en:"I paid for the full scan package this year, and it picked up three things worth watching.",
   ko:"올해는 전신 검사 패키지를 받았는데, 지켜볼 만한 게 세 가지 잡혔습니다.",
   notes:[{t:"pick something up",k:"phrasal",m:"(검사가) 잡아내다, 발견하다",tip:"The scan picked it up. 검사 결과를 말하는 자연스러운 구동사입니다."},
          {t:"worth watching",k:"collocation",m:"지켜볼 만한",tip:"경과 관찰이 필요하다는 의학적 완곡어입니다."}]},
  {s:"B",en:"Worth watching by whose judgment, though? That phrase does a lot of work in a report.",
   ko:"그런데 누구의 판단으로 지켜볼 만한 거죠? 그 표현은 판독지에서 꽤 많은 일을 합니다.",
   notes:[{t:"do a lot of work",k:"idiom",m:"(한 표현이) 많은 것을 떠안다",tip:"모호한 말이 판단을 대신하고 있다는 지적입니다."}]},
  {s:"A",en:"The report's, I assume. Isn't finding things early the entire point of screening?",
   ko:"판독지의 판단이겠죠. 일찍 찾는 게 검진의 존재 이유 아닌가요?",
   notes:[{t:"screening",k:"business",m:"선별 검사, 검진",tip:"증상 없는 사람을 대상으로 한다는 점이 핵심입니다."}]},
  {s:"B",en:"Only if finding it early changes what we do, and for a lot of findings it simply doesn't.",
   ko:"일찍 찾아서 우리가 하는 일이 달라질 때만 그렇습니다. 그런데 많은 소견에서는 달라지지 않아요.",
   notes:[{t:"change what we do",k:"collocation",m:"조치를 바꾸다",tip:"검사의 가치를 재는 가장 실용적인 기준입니다."}]},
  {s:"A",en:"That sounds like an argument for knowing less, which is a hard thing to hear as a patient.",
   ko:"덜 알자는 주장처럼 들리는데, 환자 입장에서는 듣기 힘든 얘기입니다.",
   notes:[{t:"an argument for ~",k:"business",m:"~ 를 지지하는 논거",tip:"an argument against ~ 와 짝으로 씁니다."},
          {t:"hard to hear",k:"collocation",m:"듣기 힘든",tip:"불편한 진실에 대한 반응을 표현합니다."}]},
  {s:"B",en:"I understand, but consider that some of what we find would never have troubled you at all.",
   ko:"이해합니다. 다만 우리가 찾아내는 것 중 일부는 평생 당신을 괴롭히지 않았을 것들입니다.",
   notes:[{t:"would never have troubled you",k:"grammar",m:"결코 괴롭히지 않았을 것이다",tip:"가정법 과거완료로 실현되지 않은 과거를 말합니다."}]},
  {s:"A",en:"How could anyone possibly know that, given that we treated it before we found out?",
   ko:"찾자마자 치료해 버리는데, 그걸 대체 어떻게 알 수 있죠?",
   notes:[{t:"given that ~",k:"grammar",m:"~ 임을 감안하면",tip:"전제를 깔고 반문하는 형식적인 접속 표현입니다."}]},
  {s:"B",en:"That's the honest difficulty, and it's why the evidence comes from populations rather than patients.",
   ko:"그게 솔직히 어려운 지점입니다. 그래서 근거가 환자가 아니라 집단에서 나오는 거고요.",
   notes:[{t:"the honest difficulty",k:"collocation",m:"솔직히 말해 어려운 점",tip:"약점을 먼저 인정하며 설명을 이어 가는 방식입니다."}]},
  {s:"A",en:"Meaning you compare two groups and see whether the screened one actually lives longer?",
   ko:"그러니까 두 집단을 비교해서, 검진받은 쪽이 실제로 더 오래 사는지를 본다는 말씀이군요?",
   notes:[{t:"Meaning ~?",k:"colloquial",m:"그러니까 ~ 라는 말씀이죠?",tip:"상대 설명을 자기 말로 확인하는 짧은 되물음입니다."}]},
  {s:"B",en:"Exactly, and survival rates on their own are misleading because they flatter earlier detection.",
   ko:"정확합니다. 그리고 생존율만 놓고 보면 오해를 부릅니다. 일찍 발견한 쪽을 좋게 보이게 하니까요.",
   notes:[{t:"misleading",k:"business",m:"오해를 부르는",tip:"거짓은 아니지만 잘못된 인상을 주는 경우입니다."},
          {t:"flatter",k:"idiom",m:"실제보다 좋아 보이게 하다",tip:"The numbers flatter us. 통계를 다룰 때 유용합니다."}]},
  {s:"A",en:"Because you start the clock earlier, so the person appears to survive longer regardless.",
   ko:"시계를 더 일찍 켜니까, 어느 쪽이든 더 오래 산 것처럼 보인다는 거군요.",
   notes:[{t:"start the clock",k:"idiom",m:"시간을 재기 시작하다",tip:"기준 시점이 달라지는 문제를 비유로 설명합니다."},
          {t:"regardless",k:"collocation",m:"어느 쪽이든, 상관없이",tip:"문장 끝에 단독으로 붙이는 용법입니다."}]},
  {s:"B",en:"You've got it, and that single confusion has driven decades of very confident bad advice.",
   ko:"바로 그겁니다. 그 혼동 하나가 수십 년간 아주 자신만만한 나쁜 조언을 낳았습니다.",
   notes:[{t:"You've got it.",k:"colloquial",m:"바로 그겁니다",tip:"상대의 이해가 정확할 때 쓰는 짧은 확인입니다."},
          {t:"confident bad advice",k:"collocation",m:"자신만만하게 주는 나쁜 조언",tip:"형용사를 겹쳐 아이러니를 만드는 방식입니다."}]},
  {s:"A",en:"So what should I actually ask before I agree to the next test on the list?",
   ko:"그럼 목록의 다음 검사에 동의하기 전에 제가 뭘 물어야 합니까?",
   notes:[{t:"agree to ~",k:"collocation",m:"~ 에 동의하다, 받아들이다",tip:"agree with(의견에 동의)와 구별하세요."}]},
  {s:"B",en:"Ask what we would do differently depending on the result, and make me answer both ways.",
   ko:"결과에 따라 우리가 무엇을 달리하게 되는지 물으세요. 그리고 양쪽 답을 다 하게 만드세요.",
   notes:[{t:"do differently",k:"collocation",m:"달리 조치하다",tip:"What would we do differently? 는 강력한 의사결정 질문입니다."},
          {t:"make me answer both ways",k:"idiom",m:"양쪽 경우 모두 답하게 하다",tip:"양성일 때와 음성일 때를 모두 묻는 것입니다."}]},
  {s:"A",en:"And if the answer is the same either way, then the test is just expensive reassurance.",
   ko:"그리고 양쪽 답이 같다면, 그 검사는 그냥 값비싼 안심이겠네요.",
   notes:[{t:"either way",k:"idiom",m:"어느 쪽이든",tip:"결과가 갈려도 결론이 같을 때 쓰는 표현입니다."},
          {t:"expensive reassurance",k:"idiom",m:"값비싼 안심",tip:"실익 없는 지출을 꼬집는 재치 있는 표현입니다."}]},
  {s:"B",en:"Reassurance has real value, so I'd never dismiss it, but it should be priced honestly.",
   ko:"안심에도 실제 값어치가 있으니 무시하지는 않겠습니다. 다만 정직하게 값을 매겨야죠.",
   notes:[{t:"dismiss",k:"business",m:"일축하다, 무시하다",tip:"I'd never dismiss it. 상대 입장을 존중하며 단서를 답니다."}]},
  {s:"A",en:"Priced how? I can see the invoice, and it doesn't mention anything about risk.",
   ko:"어떻게 값을 매기죠? 청구서는 보이는데, 거기에 위험 얘기는 한 줄도 없습니다.",
   notes:[{t:"Priced how?",k:"colloquial",m:"어떻게 값을 매긴다는 겁니까",tip:"한 단어 + how 로 되묻는 압축된 구어입니다."}]},
  {s:"B",en:"In biopsies you never needed, and in a year of worrying about something that would never have grown.",
   ko:"필요 없던 조직 검사로, 그리고 자라지도 않았을 것을 1년 내내 걱정한 시간으로요.",
   notes:[{t:"something that would never have grown",k:"grammar",m:"애초에 자라지 않았을 것",tip:"가정법 과거완료로 「실제로는 일어나지 않았을 일」을 말합니다."}]},
  {s:"A",en:"Put like that, I'd rather have fewer tests and better questions at the next appointment.",
   ko:"그렇게 말씀하시니, 다음 진료에서는 검사를 줄이고 질문을 늘리는 편이 낫겠습니다.",
   notes:[{t:"Put like that",k:"grammar",m:"그렇게 말하고 보니",tip:"상대의 표현을 받아 태도를 바꾸는 자연스러운 전환입니다."}]},
  {s:"B",en:"That's the right trade, and it's the one thing a fifteen-minute visit can actually deliver.",
   ko:"그게 맞는 교환입니다. 15분짜리 진료가 실제로 해 줄 수 있는 유일한 일이기도 하고요.",
   notes:[{t:"the right trade",k:"business",m:"맞는 교환, 옳은 맞바꿈",tip:"무엇을 내주고 무엇을 얻을지가 분명할 때 씁니다."}]}
 ],
 keys:[
  {en:"pick something up",ko:"(검사가) 잡아내다",ex:"The scan picked up three things nobody can explain yet."},
  {en:"screening",ko:"선별 검사, 검진",ex:"Screening only helps if finding it early changes what we do."},
  {en:"misleading",ko:"오해를 부르는",ex:"Survival rates on their own are misleading."},
  {en:"flatter",ko:"실제보다 좋아 보이게 하다",ex:"Earlier detection flatters every number in the report."},
  {en:"start the clock",ko:"시간을 재기 시작하다",ex:"You start the clock earlier, so survival looks longer regardless."},
  {en:"do differently",ko:"달리 조치하다",ex:"Ask what we would do differently depending on the result."},
  {en:"either way",ko:"어느 쪽이든",ex:"If the answer is the same either way, skip the test."},
  {en:"expensive reassurance",ko:"값비싼 안심",ex:"Some of what we sell is expensive reassurance, and we should say so."}
 ],
 out:[
  {q:"Explain in plain words why more testing is not always better.",hint:"screening / change what we do / pick something up"},
  {q:"Explain why survival rates can look good without anyone living longer.",hint:"misleading / flatter / start the clock"},
  {q:"Say what you would ask a doctor before agreeing to an optional test.",hint:"do differently / either way / expensive reassurance"}
 ]
},
{
 id:"w4d5", day:30, cat:"식품·농업", level:"B2+",
 title:"The Cheapest Calorie",
 titleKo:"가장 싼 칼로리 — 값싼 식탁의 진짜 계산서",
 names:{A:"Marta (농업경제학자)", B:"Dev (식품회사 구매 총괄)"},
 brief:[
  "지난 백 년 동안 식량 정책의 목표는 하나였습니다. <b>칼로리를 싸게 만드는 것</b>입니다. 굶주림이 실재하던 시대에 이것은 훌륭한 목표였고, 실제로 성공했습니다. 곡물과 기름과 설탕은 인류 역사상 가장 싸졌습니다.",
  "그런데 값이 싸진 것은 <b>모든 칼로리가 아니라 특정한 칼로리</b>였습니다. 오래 보관되고, 멀리 운반되고, 기계로 수확되는 것들입니다. 신선한 채소와 생선은 그 혜택을 훨씬 덜 받았습니다. 가격 구조가 식탁의 모양을 바꿔 놓았습니다.",
  "여기서 <b>외부비용</b>이 등장합니다. 값싼 칼로리의 진짜 비용 중 일부는 식료품 가격표에 찍히지 않고, 훨씬 나중에 <b>의료비와 토양과 물</b>로 청구됩니다. 청구서가 다른 부서로 가는 셈입니다.",
  "이 대화는 「가공식품은 나쁘다」는 도덕론으로 가지 않습니다. <b>왜 그 가격이 그렇게 형성되었는가</b>를 따라가고, 세금·보조금·표시제 같은 수단의 한계까지 솔직하게 다룹니다."
 ],
 lines:[
  {s:"A",en:"Food policy spent a century making calories cheap, and by that measure it worked brilliantly.",
   ko:"식량 정책은 한 세기 동안 칼로리를 싸게 만드는 데 매달렸고, 그 기준으로는 훌륭하게 성공했습니다.",
   notes:[{t:"by that measure",k:"idiom",m:"그 기준으로 보면",tip:"성공의 잣대를 명시할 때 쓰는 표현입니다."},
          {t:"work brilliantly",k:"collocation",m:"훌륭하게 작동하다",tip:"It worked brilliantly. 성과를 인정하는 말입니다."}]},
  {s:"B",en:"And now the same success gets described as a public health failure, which I find unfair.",
   ko:"그런데 이제 그 성공이 공중보건 실패로 묘사되죠. 저는 그게 부당하다고 봅니다.",
   notes:[{t:"get described as ~",k:"business",m:"~ 로 묘사되다",tip:"수동태로 「누가 그렇게 부른다」를 드러냅니다."}]},
  {s:"A",en:"Not unfair, just incomplete, because cheap calories and cheap nutrition were never the same project.",
   ko:"부당한 건 아니고 불완전한 겁니다. 싼 칼로리와 싼 영양은 애초에 같은 사업이 아니었으니까요.",
   notes:[{t:"Not A, just B",k:"grammar",m:"A가 아니라 그저 B",tip:"상대 표현을 부드럽게 교정하는 틀입니다."}]},
  {s:"B",en:"Go on, because in my world a calorie is a calorie and the spreadsheet doesn't care which.",
   ko:"계속해 보세요. 제 세계에서 칼로리는 그냥 칼로리고, 엑셀은 어느 쪽인지 신경 쓰지 않거든요.",
   notes:[{t:"the spreadsheet doesn't care",k:"idiom",m:"숫자는 따지지 않는다",tip:"의사결정이 수치로만 이뤄지는 상황을 꼬집습니다."}]},
  {s:"A",en:"What fell in price was whatever stores well, ships far, and comes off a machine.",
   ko:"값이 떨어진 건 오래 보관되고, 멀리 실려 가고, 기계에서 나오는 것들이었습니다.",
   notes:[{t:"store well",k:"collocation",m:"보관성이 좋다",tip:"travel well(운송에 잘 견디다)과 함께 식품업의 기본 표현입니다."},
          {t:"come off a machine",k:"idiom",m:"기계에서 생산되어 나오다",tip:"기계화된 생산을 가리키는 구어입니다."}]},
  {s:"B",en:"Grain, oil, and sugar, which happen to be exactly the three things we buy by the tanker.",
   ko:"곡물, 기름, 설탕이죠. 하필 우리가 탱커 단위로 사들이는 바로 그 셋입니다.",
   notes:[{t:"by the tanker",k:"collocation",m:"탱커 단위로",tip:"by the ton / by the container 처럼 규모를 표현합니다."}]},
  {s:"A",en:"Exactly, and nothing comparable happened to fresh vegetables or to fish that has to stay cold.",
   ko:"정확합니다. 그리고 신선 채소나 계속 차게 유지해야 하는 생선에는 그런 일이 없었습니다.",
   notes:[{t:"nothing comparable happened",k:"collocation",m:"그에 견줄 만한 일은 없었다",tip:"비교 대상이 없음을 격식 있게 말합니다."}]},
  {s:"B",en:"Cold chain is brutal. Every hour of it costs money that the customer refuses to see.",
   ko:"냉장 유통은 가혹합니다. 그 한 시간 한 시간이 돈인데, 고객은 그걸 보려 하지 않죠.",
   notes:[{t:"cold chain",k:"business",m:"냉장 유통망",tip:"식품 물류의 핵심 용어입니다."},
          {t:"brutal",k:"colloquial",m:"혹독한, 가차 없는",tip:"비용이나 일정이 가혹할 때 쓰는 구어 형용사입니다."}]},
  {s:"A",en:"So the price on the shelf reflects handling, not health, and shoppers read it as both.",
   ko:"그럼 진열대 가격은 건강이 아니라 취급 비용을 반영하는 건데, 소비자는 둘 다로 읽죠.",
   notes:[{t:"the price on the shelf",k:"collocation",m:"진열대 가격, 소비자가",tip:"현장감 있게 소비자 가격을 가리키는 표현입니다."}]},
  {s:"B",en:"I'd push back there, since plenty of shoppers know perfectly well and buy the cheap thing anyway.",
   ko:"그 부분은 반박하겠습니다. 뻔히 알면서도 싼 걸 사는 소비자가 아주 많으니까요.",
   notes:[{t:"know perfectly well",k:"collocation",m:"뻔히 잘 알다",tip:"상대가 몰라서 그런 게 아님을 강조합니다."}]},
  {s:"A",en:"Fair, and I'd never argue people are simply uninformed, because budgets do most of the choosing.",
   ko:"타당합니다. 사람들이 그저 모른다고 주장할 생각은 없습니다. 선택의 대부분은 예산이 하니까요.",
   notes:[{t:"do most of the choosing",k:"idiom",m:"선택의 대부분을 대신하다",tip:"제약이 결정을 지배한다는 것을 표현합니다."}]},
  {s:"B",en:"Then where does the argument actually land, if it isn't about blaming anyone in particular?",
   ko:"그럼 논지가 어디에 착지합니까? 특정한 누구를 탓하는 게 아니라면요.",
   notes:[{t:"Where does the argument land?",k:"idiom",m:"논지가 결국 어디로 가는가",tip:"결론을 요구하는 세련된 질문입니다."}]},
  {s:"A",en:"On the costs that never show up in the price, which land later as illness, soil, and water.",
   ko:"가격에 절대 나타나지 않는 비용에 착지합니다. 나중에 질병과 토양과 물로 도착하는 것들이죠.",
   notes:[{t:"costs that never show up in the price",k:"business",m:"가격에 반영되지 않는 비용",tip:"외부비용을 평이한 영어로 설명한 것입니다."}]},
  {s:"B",en:"Externalities, then. I know the word, but I've never seen one arrive on my own budget line.",
   ko:"외부비용이군요. 단어는 아는데, 제 예산 항목에 그게 도착한 걸 본 적은 없습니다.",
   notes:[{t:"an externality",k:"business",m:"외부비용, 외부효과",tip:"거래 당사자가 아닌 제3자가 치르는 비용입니다."},
          {t:"arrive on a budget line",k:"idiom",m:"예산 항목으로 도착하다",tip:"비용이 누구에게 청구되는지를 구체화합니다."}]},
  {s:"A",en:"That's precisely the problem, since the bill goes to a department that never sat in your meeting.",
   ko:"문제가 바로 그겁니다. 청구서가, 당신 회의에 앉아 본 적 없는 부서로 가니까요.",
   notes:[{t:"the bill goes to ~",k:"idiom",m:"청구서가 ~ 에게 간다",tip:"비용 귀착을 짧게 표현하는 비유입니다."}]},
  {s:"B",en:"Then tax it and be honest about it, rather than lecturing shoppers about their shopping baskets.",
   ko:"그럼 세금을 매기고 솔직하게 말하세요. 소비자의 장바구니를 훈계하지 말고요.",
   notes:[{t:"lecture someone about ~",k:"collocation",m:"~ 를 두고 훈계하다",tip:"부정적인 뉘앙스가 강한 동사입니다."}]},
  {s:"A",en:"Taxes on single ingredients get gamed within a year, because reformulation is cheaper than reform.",
   ko:"단일 성분에 매긴 세금은 1년이면 뚫립니다. 배합을 바꾸는 게 제도를 바꾸는 것보다 싸거든요.",
   notes:[{t:"get gamed",k:"business",m:"(제도가) 악용되다, 편법으로 뚫리다",tip:"game a metric 의 수동형입니다."},
          {t:"reformulation",k:"business",m:"(제품의) 배합 변경",tip:"규제를 피해 성분을 바꾸는 것을 말합니다."}]},
  {s:"B",en:"So what would you actually do, given that every tool on that list has been tried somewhere?",
   ko:"그럼 실제로 뭘 하시겠습니까? 그 목록의 수단은 전부 어디선가 시도된 적이 있는데요.",
   notes:[{t:"given that ~",k:"grammar",m:"~ 임을 감안하면",tip:"반론의 전제를 먼저 인정하는 접속 표현입니다."}]},
  {s:"A",en:"Move the subsidy rather than add the tax, because what we pay farmers to grow shapes everything downstream.",
   ko:"세금을 더하지 말고 보조금을 옮기세요. 농가에 무엇을 기르라고 돈을 주느냐가 그 아래 전부를 결정하니까요.",
   notes:[{t:"downstream",k:"business",m:"공정의 아래쪽, 후방",tip:"upstream(상류)과 짝으로 씁니다. 여기서는 유통과 소비 단계입니다."}]},
  {s:"B",en:"That I could defend to my board, because it changes my input costs instead of my label.",
   ko:"그거라면 이사회에 설명할 수 있습니다. 표시 문구가 아니라 원재료 값을 바꾸는 얘기니까요.",
   notes:[{t:"input costs",k:"business",m:"투입 원가, 원재료 비용",tip:"제조업 손익 논의의 기본 용어입니다."}]}
 ],
 keys:[
  {en:"by that measure",ko:"그 기준으로 보면",ex:"By that measure the policy worked exactly as intended."},
  {en:"store well",ko:"보관성이 좋다",ex:"What fell in price was whatever stores well and ships far."},
  {en:"cold chain",ko:"냉장 유통망",ex:"Cold chain is brutal, and every hour of it costs money."},
  {en:"know perfectly well",ko:"뻔히 잘 알다",ex:"Plenty of shoppers know perfectly well and buy it anyway."},
  {en:"an externality",ko:"외부비용, 외부효과",ex:"An externality is a cost that never arrives on your budget line."},
  {en:"the bill goes to ~",ko:"청구서가 ~ 에게 간다",ex:"The bill goes to a department that never sat in the meeting."},
  {en:"get gamed",ko:"편법으로 뚫리다",ex:"A tax on one ingredient gets gamed within a year."},
  {en:"input costs",ko:"투입 원가",ex:"Moving the subsidy changes my input costs, not just my label."}
 ],
 out:[
  {q:"Explain why cheap calories and cheap nutrition are not the same achievement.",hint:"by that measure / store well / cold chain"},
  {q:"Explain externalities using food as the example.",hint:"an externality / costs that never show up in the price / the bill goes to ~"},
  {q:"Argue for one policy tool and say honestly where it would fail.",hint:"get gamed / lecture someone about ~ / input costs"}
 ]
}
