{
 id:"w2d1", day:8, cat:"품질·리스크", level:"B2+",
 title:"The Recall Nobody Wants to Own",
 titleKo:"아무도 떠안기 싫은 리콜 — 결함과 책임의 경계",
 names:{A:"Grace (품질보증)", B:"Diego (구매·공급망)"},
 brief:[
  "제조 현장에서 결함이 나오면 가장 먼저 정해지는 것은 책임이 아니라 순서다. <b>봉쇄(containment)</b>가 먼저고 <b>시정(corrective action)</b>이 그다음이며, 책임 배분은 마지막이다. 원인을 다 밝히기 전에도 확산은 멈춰야 하기 때문이다.",
  "책임을 가르는 실질적 기준은 <b>입증책임(the burden of proof)</b>이 어디에 놓이느냐다. 공급사는 도면과 규격을 들고 오고, 완성품 업체는 실제 사용 조건을 든다. 계약서의 <b>책임한도(liability cap)</b>가 이 다툼의 상한을 미리 정해 둔다.",
  "리콜의 비용 구조는 <b>확실한 비용 대 불확실한 비용</b>의 대결이다. 지금 회수하면 금액이 확정되고, 미루면 확률은 낮지만 손실이 큰 <b>꼬리위험(tail risk)</b>이 남는다. 둘을 같은 저울에 올리는 순간 판단이 쉬워진다.",
  "그래서 실무에서 진짜로 다투는 것은 「리콜을 하느냐」가 아니라 <b>범위(scope)</b>다. 어느 로트까지, 어느 일련번호까지 포함할 것인가. 이 선을 예산이 아니라 <b>증거</b>로 그어야 나중에 방어할 수 있다."
 ],
 lines:[
  {s:"A",en:"We've traced the cracking to a single supplier's batch, though the design tolerance we specified was tight to begin with.",
   ko:"균열을 한 공급사의 특정 로트까지 추적했어요. 다만 우리가 지정한 설계 공차 자체가 애초에 빡빡했죠.",
   notes:[{t:"trace A to B",k:"phrasal",m:"A의 원인을 B까지 거슬러 찾아내다",tip:"We traced the leak to a faulty valve. 원인 규명 보고의 표준 동사입니다."},
          {t:"the tolerance we specified",k:"grammar",m:"우리가 지정한 그 공차",tip:"접촉절입니다. 책임의 절반이 우리에게 있다는 사실을 명사 안에 조용히 넣었습니다."},
          {t:"to begin with",k:"idiom",m:"애초에, 처음부터",tip:"문장 끝에 붙여 '원래부터 그랬다'는 뜻을 답니다. in the first place와 바꿔 쓸 수 있습니다."}]},
  {s:"B",en:"Hold on. You're already framing this as ours in a report that goes out tomorrow, and the analysis isn't finished.",
   ko:"잠깐요. 내일 나갈 보고서에서 벌써 우리 책임으로 몰고 계신데, 분석이 끝나지도 않았어요.",
   notes:[{t:"Hold on.",k:"colloquial",m:"잠깐만요 (말을 끊고 제동)",tip:"Wait보다 부드럽고 회의에서 훨씬 자주 씁니다. Hold on, let me finish."},
          {t:"frame A as B",k:"business",m:"A를 B인 것처럼 규정하다",tip:"프레임을 씌운다는 뜻. Don't frame this as a failure. 논쟁에서 상대의 전제를 걷어낼 때 씁니다."},
          {t:"a report that goes out tomorrow",k:"grammar",m:"내일 나갈 보고서",tip:"관계절 안의 현재시제가 확정된 미래를 나타냅니다. 일정이 잡힌 일에는 will을 쓰지 않습니다."}]},
  {s:"A",en:"I'm not assigning blame. I'm saying the burden of proof is going to land on whoever specified the tolerance, which was us.",
   ko:"책임을 떠넘기는 게 아니에요. 입증책임이 공차를 지정한 쪽에 떨어질 거라는 말이고, 그게 우리라는 겁니다.",
   notes:[{t:"the burden of proof",k:"business",m:"입증책임",tip:"The burden of proof is on the supplier. 계약·품질 회의의 핵심 단어입니다."},
          {t:"whoever specified ~, which was us",k:"grammar",m:"~을 지정한 사람이 누구든, 그게 우리였다",tip:"복합관계대명사로 열어 두고 which로 정답을 밝히는 2단 구성입니다. 자기 책임을 인정하는 세련된 방식입니다."},
          {t:"land on ~",k:"phrasal",m:"(부담이) ~에게 떨어지다",tip:"The cost landed on our division. 의도치 않게 떠안게 됐다는 뉘앙스."}]},
  {s:"B",en:"It always does. The supplier will point at the drawing we sent them, and we'll be on the hook for a batch we never made.",
   ko:"늘 그렇죠. 공급사는 우리가 보낸 도면을 가리킬 테고, 우리가 만들지도 않은 로트를 우리가 뒤집어쓰게 될 겁니다.",
   notes:[{t:"be on the hook (for)",k:"idiom",m:"(비용·책임을) 떠안다",tip:"We're on the hook for the repair cost. 한국인이 잘 안 쓰는데 원어민은 매우 자주 씁니다."},
          {t:"a batch we never made",k:"grammar",m:"우리가 만들지도 않은 로트",tip:"접촉절 하나로 억울함을 압축했습니다. 감정을 형용사로 말하지 않고 사실로 말하는 화법입니다."},
          {t:"point at ~",k:"phrasal",m:"~을 (책임 근거로) 들이대다",tip:"point to the contract / point at the drawing. 문서를 근거로 삼는다는 뜻으로 확장됩니다."}]},
  {s:"A",en:"Which is why we contain first and argue later: stop shipments, quarantine the lot, and have the argument once we know what we're arguing about.",
   ko:"그래서 봉쇄가 먼저고 논쟁이 나중인 겁니다. 출하 중단, 로트 격리, 그리고 무엇을 두고 다투는지 알게 된 뒤에 다투는 거죠.",
   notes:[{t:"Which is why ~",k:"grammar",m:"바로 그래서 ~인 겁니다",tip:"앞 문장 전체를 받아 결론으로 잇는 연결어. That's why보다 논증적으로 들립니다."},
          {t:"contain",k:"business",m:"(확산을) 봉쇄하다",tip:"품질 용어로 containment action = 봉쇄 조치. 원인 규명 전에 하는 응급 처치입니다."},
          {t:"once we know what we're arguing about",k:"grammar",m:"무엇을 두고 다투는지 알게 되면",tip:"once절 + 간접의문문의 조합입니다. once 뒤에는 미래 대신 현재를 씁니다."}]},
  {s:"B",en:"Containment I can live with. A public recall is a different animal entirely, and it's the one that ends up in the trade press.",
   ko:"봉쇄까지는 받아들일 수 있어요. 공개 리콜은 완전히 다른 이야기고, 업계지에 실리는 건 그쪽이죠.",
   notes:[{t:"I can live with ~",k:"idiom",m:"~ 정도는 감수할 수 있다",tip:"완전히 만족하진 않지만 수용한다는 뜻. 협상에서 부분 합의를 표시할 때 최고의 표현입니다."},
          {t:"a different animal",k:"idiom",m:"성격이 전혀 다른 것",tip:"That's a different animal altogether. 규모나 종류가 다르다는 뜻으로 씁니다."},
          {t:"the one that ends up in ~",k:"grammar",m:"결국 ~에 실리게 되는 쪽",tip:"end up in ~ = 결국 ~에 이르다. the one that ~ 으로 둘 중 하나를 지목합니다."}]},
  {s:"A",en:"Agreed, but if we sit on this and it surfaces through a customer rather than through us, it comes back to bite us twice.",
   ko:"동의해요. 그런데 이걸 깔고 앉아 있다가 우리가 아니라 고객을 통해 드러나면, 두 배로 되돌아옵니다.",
   notes:[{t:"sit on ~",k:"phrasal",m:"~을 묵혀 두다, 깔고 앉다",tip:"They sat on the report for months. 알고도 조치를 미뤘다는 부정적 뉘앙스."},
          {t:"come back to bite us",k:"idiom",m:"나중에 부메랑으로 돌아오다",tip:"That shortcut will come back to bite us. 미룬 결정의 대가를 말할 때."},
          {t:"through A rather than through B",k:"grammar",m:"B가 아니라 A를 통해",tip:"전치사를 두 번 반복해 대비를 또렷하게 만들었습니다. 생략하면 문장이 흐려집니다."}]},
  {s:"B",en:"You're assuming it surfaces at all. Most of the parts in that batch will never see a load anywhere near what we tested for.",
   ko:"애초에 드러난다는 걸 전제하시는 거잖아요. 그 로트 부품 대부분은 우리가 시험한 하중 근처에도 못 가 볼 겁니다.",
   notes:[{t:"You're assuming ~",k:"business",m:"~을 전제하고 계시잖아요",tip:"상대 논리의 숨은 가정을 끄집어내는 토론 필수 표현. 공격적이지 않게 반박됩니다."},
          {t:"anywhere near what we tested for",k:"grammar",m:"우리가 시험한 수준 근처에도",tip:"anywhere near는 부정문에서 '근처에도 못 미친다'는 강조입니다. what절이 목적어로 붙었습니다."}]},
  {s:"A",en:"That's a gamble on tail risk. The odds are low, but the downside is large enough to swallow every saving we'd make by waiting.",
   ko:"그건 꼬리위험에 거는 도박이에요. 확률은 낮지만, 손실이 기다려서 아낀 돈을 전부 삼킬 만큼 큽니다.",
   notes:[{t:"tail risk",k:"business",m:"확률은 낮지만 손실이 큰 위험",tip:"금융에서 온 말이 품질·안전 회의로 넘어왔습니다. low-probability, high-impact와 같은 뜻."},
          {t:"the downside",k:"business",m:"최악의 경우 손실",tip:"upside(잘 됐을 때 이익)와 짝입니다. What's the downside? 는 회의에서 매일 나옵니다."},
          {t:"every saving we'd make by waiting",k:"grammar",m:"기다려서 아끼게 될 모든 절감액",tip:"접촉절 + 가정법 would + by -ing. 세 요소가 한 명사구에 들어간 고밀도 표현입니다."}]},
  {s:"B",en:"Fair. Still, somebody in this room has to weigh a certain cost against an uncertain one, and that person signs either way.",
   ko:"일리 있어요. 그래도 이 방의 누군가는 확실한 비용과 불확실한 비용을 저울에 올려야 하고, 어느 쪽이든 그 사람이 서명합니다.",
   notes:[{t:"weigh A against B",k:"collocation",m:"A와 B를 견주어 판단하다",tip:"compare보다 '득실을 따진다'는 뜻이 강합니다. weigh the risks against the benefits."},
          {t:"either way",k:"idiom",m:"어느 쪽이든 간에",tip:"결과가 갈려도 부담은 같다는 뜻을 두 단어로 담습니다. 문장 끝에 붙이세요."}]},
  {s:"A",en:"Then let's price both of them honestly, instead of dressing the cheaper option up as prudence and hoping nobody checks the reasoning.",
   ko:"그럼 둘 다 정직하게 값을 매기죠. 싼 쪽을 신중함으로 포장해 놓고 아무도 논리를 안 따지길 바라지 말고요.",
   notes:[{t:"dress ~ up as …",k:"idiom",m:"~을 …인 것처럼 포장하다",tip:"They dressed a budget cut up as a strategy. 비판할 때 아주 잘 드는 표현입니다."},
          {t:"price ~",k:"business",m:"~에 값을 매기다, 비용으로 환산하다",tip:"동사로 씁니다. price the risk / price it in(가격에 이미 반영하다)."},
          {t:"instead of -ing and -ing",k:"grammar",m:"~하고 ~하는 대신에",tip:"전치사 뒤 동명사 두 개를 and로 이었습니다. 두 번째에 of를 다시 붙이지 않습니다."}]},
  {s:"B",en:"Careful. That cuts the other way, because erring on the side of caution isn't free either once you count the lines we'd stop.",
   ko:"조심하세요. 그 논리는 반대로도 작동합니다. 멈추게 될 라인을 세어 보면, 안전하게 가는 것도 공짜가 아니거든요.",
   notes:[{t:"That cuts the other way.",k:"idiom",m:"그 논리는 반대편에도 똑같이 적용됩니다",tip:"상대의 무기를 그대로 돌려줄 때. cut both ways = 양날의 검이다."},
          {t:"err on the side of caution",k:"idiom",m:"안전한 쪽으로 판단을 기울이다",tip:"통째로 외우세요. err는 /ɜːr/로 읽습니다. 회의에서 매우 자주 나옵니다."},
          {t:"once you count ~",k:"grammar",m:"~을 세어 보면",tip:"once가 '일단 ~하고 나면'이라는 조건을 만듭니다. 숨은 비용을 드러낼 때 잘 쓰입니다."}]},
  {s:"A",en:"No, and I'd never pretend it is. But a quiet field fix buys us credibility that we can't purchase any other way.",
   ko:"맞아요, 공짜인 척할 생각도 없습니다. 다만 조용한 현장 수리는 다른 방법으로는 살 수 없는 신뢰를 벌어 줘요.",
   notes:[{t:"buy (someone) ~",k:"idiom",m:"~을 벌어 주다, 확보해 주다",tip:"buy us time / buy us credibility. 돈이 아니라 시간·신뢰를 목적어로 씁니다."},
          {t:"field fix",k:"business",m:"현장 조치, 출고 후 수리",tip:"in the field = 고객 현장에서. field failure / field data 세트로 쓰입니다."},
          {t:"credibility that we can't purchase any other way",k:"grammar",m:"다른 방법으로는 살 수 없는 신뢰",tip:"buy와 purchase를 한 문장에 나란히 써서 비유를 끝까지 밀고 갔습니다. 영어다운 문장 운용입니다."}]},
  {s:"B",en:"A silent recall, you mean. Regulators have a name for that, and it's the sort of thing that turns a defect into a case.",
   ko:"그러니까 은밀한 리콜이란 말이죠. 규제 당국도 그걸 부르는 이름이 있고, 결함을 사건으로 바꿔 놓는 게 딱 그런 겁니다.",
   notes:[{t:"~, you mean.",k:"colloquial",m:"그러니까 ~라는 말씀이죠",tip:"상대 표현을 더 노골적인 말로 바꿔 되받는 기법. 토론에서 아주 강력합니다."},
          {t:"the sort of thing that turns A into B",k:"grammar",m:"A를 B로 바꿔 놓는 그런 종류의 일",tip:"the sort/kind of thing that ~ 은 범주로 경고할 때 쓰는 완곡하면서 강한 표현입니다."}]},
  {s:"A",en:"Then we notify properly. My point was never whether we own it; my point is how wide the scope has to be.",
   ko:"그럼 제대로 신고하죠. 제 요지는 우리가 책임지느냐가 아니었어요. 범위를 얼마나 넓게 잡아야 하느냐입니다.",
   notes:[{t:"My point is ~",k:"business",m:"제 요지는 ~입니다",tip:"논점이 흐려졌을 때 되돌리는 문장. That's not my point. 도 함께 외우세요."},
          {t:"own it",k:"idiom",m:"책임을 인정하고 떠맡다",tip:"We should just own it. 잘못을 인정한다는 뜻으로 현대 비즈니스 영어에서 매우 흔합니다."},
          {t:"how wide the scope has to be",k:"grammar",m:"범위를 얼마나 넓게 잡아야 하는지",tip:"간접의문문이라 how wide 뒤가 주어+동사입니다. how wide has the scope로 쓰면 틀립니다."}]},
  {s:"B",en:"Scope is where this gets expensive. Every extra lot we include widens a bill that somebody upstairs will read line by line.",
   ko:"비싸지는 지점이 바로 범위예요. 로트를 하나 더 넣을 때마다, 윗선에서 한 줄 한 줄 읽을 청구서가 넓어집니다.",
   notes:[{t:"where this gets ~",k:"grammar",m:"바로 이 지점에서 ~해진다",tip:"That's where it gets tricky. 문제의 핵심을 짚는 구어 골격입니다."},
          {t:"a bill somebody will read line by line",k:"grammar",m:"누군가 한 줄씩 읽어 볼 청구서",tip:"접촉절로 '감시받는다'는 압박을 명사에 실었습니다. line by line은 꼼꼼한 검토를 뜻합니다."}]},
  {s:"A",en:"So we draw the line on evidence rather than on budget, because the moment the number drives the engineering, we can't defend either one.",
   ko:"그러니 선은 예산이 아니라 증거로 긋죠. 숫자가 기술 판단을 끌고 가는 순간, 둘 다 방어할 수 없게 되니까요.",
   notes:[{t:"draw the line",k:"idiom",m:"한계선을 긋다",tip:"draw the line at ~ = ~까지는 허용하고 그 이상은 안 된다."},
          {t:"the moment ~",k:"grammar",m:"~하는 순간",tip:"as soon as와 같은 뜻인데 훨씬 극적입니다. 접속사처럼 절을 이끕니다."},
          {t:"A drives B",k:"collocation",m:"A가 B를 좌우하다",tip:"Cost is driving the design. 주객이 전도됐다는 비판에 자주 씁니다."}]},
  {s:"B",en:"That's fair. Let's ring-fence the serial range the test data actually covers, and defend that boundary rather than a convenient one.",
   ko:"타당하네요. 시험 데이터가 실제로 덮는 일련번호 구간만 따로 떼어 놓고, 편한 경계가 아니라 그 경계를 방어합시다.",
   notes:[{t:"ring-fence",k:"business",m:"(대상을) 울타리 쳐 따로 떼어 두다",tip:"ring-fence the budget / the affected units. 영국식이지만 이제 널리 쓰입니다."},
          {t:"the range the test data actually covers",k:"grammar",m:"시험 데이터가 실제로 덮는 그 구간",tip:"접촉절 안의 actually가 '편의가 아니라 사실'이라는 기준을 실어 줍니다."}]},
  {s:"A",en:"And we front-load the supplier conversation, in good faith, before the lawyers on either side start deciding what we're allowed to say.",
   ko:"그리고 공급사와의 대화를 앞당깁시다. 선의로요. 양쪽 변호사들이 우리가 무슨 말을 해도 되는지 정하기 시작하기 전에요.",
   notes:[{t:"front-load",k:"business",m:"앞쪽에 몰아서 하다, 앞당기다",tip:"front-load the work / the cost. 반대는 back-load. 일정 회의에서 자주 나옵니다."},
          {t:"in good faith",k:"business",m:"선의로, 성실하게",tip:"계약 용어이면서 일상 표현입니다. We acted in good faith. 라고 하면 방어가 됩니다."},
          {t:"what we're allowed to say",k:"grammar",m:"우리가 말해도 되는 것",tip:"what절 + 수동태 조합입니다. 통제받는 상황을 명사 하나로 표현합니다."}]},
  {s:"B",en:"Good. I'd rather split the difference on cost with a supplier we trust than kick this can down a road that only gets narrower.",
   ko:"좋습니다. 갈수록 좁아지기만 하는 길로 이 문제를 미루느니, 믿는 공급사와 비용을 반씩 나누는 편이 낫죠.",
   notes:[{t:"split the difference",k:"idiom",m:"차액을 반씩 나눠 절충하다",tip:"협상 마무리의 정석 표현입니다. Let's split the difference and move on."},
          {t:"kick the can down the road",k:"idiom",m:"결정을 뒤로 미루다",tip:"통째로 외우세요. 미룬다는 뜻의 표현 중 가장 자주 쓰입니다."},
          {t:"a road that only gets narrower",k:"grammar",m:"갈수록 좁아지기만 하는 길",tip:"관용구의 마지막 단어(road)에 관계절을 붙여 비유를 되살렸습니다. 영어 글쓰기의 고급 기술입니다."}]}
 ],
 keys:[
  {en:"be on the hook for ~",ko:"~의 책임·비용을 떠안다",ex:"If the test fails, we're on the hook for the rework."},
  {en:"the burden of proof",ko:"입증책임",ex:"The burden of proof sits with whoever claims the defect."},
  {en:"come back to bite us",ko:"나중에 부메랑으로 돌아오다",ex:"Skipping the audit will come back to bite us."},
  {en:"err on the side of caution",ko:"안전한 쪽으로 판단하다",ex:"With safety parts, we err on the side of caution."},
  {en:"That cuts the other way.",ko:"그 논리는 반대편에도 적용됩니다",ex:"That cuts the other way — speed has a cost too."},
  {en:"ring-fence ~",ko:"~만 따로 떼어 보호하다",ex:"Let's ring-fence next year's maintenance budget."},
  {en:"split the difference",ko:"차액을 반씩 나눠 절충하다",ex:"Neither side moved, so we split the difference."},
  {en:"kick the can down the road",ko:"결정을 뒤로 미루다",ex:"Another review just kicks the can down the road."}
 ],
 out:[
  {q:"Describe a defect or complaint your team handled. What did you contain first, and what did you fix later?",hint:"contain / trace it to / on the hook for"},
  {q:"Argue that acting late is more expensive than acting early, then argue the opposite.",hint:"tail risk / err on the side of caution / that cuts the other way"},
  {q:"Your supplier blames your drawing. Respond without accepting blame and without escalating.",hint:"the burden of proof / in good faith / front-load"}
 ]
},
{
 id:"w2d2", day:9, cat:"환경·통상", level:"B2+",
 title:"Paying for Carbon at the Border",
 titleKo:"국경에서 탄소값을 치르다 — 배출 규제와 수출 경쟁력",
 names:{A:"Lena (환경·규제 대응)", B:"Hugo (수출영업)"},
 brief:[
  "배출에 값이 매겨지면 원가 구조가 바뀐다. 지금까지 원가는 원료와 에너지였지만, <b>탄소 가격(carbon pricing)</b>이 붙는 순간 배출량 자체가 비용 항목이 된다. 같은 제품, 같은 공정이라도 어디서 어떻게 만들었는지가 값을 가른다.",
  "국경에서 조정이 일어나는 이유는 <b>탄소 누출(carbon leakage)</b> 때문이다. 규제가 강한 나라의 공장이 규제가 약한 나라로 옮겨 가면 배출은 그대로인 채 산업만 빠져나간다. 그래서 수입품에도 같은 값을 물려 <b>공정한 경쟁 조건(a level playing field)</b>을 맞추려 한다.",
  "실무의 난점은 규제가 아니라 <b>측정</b>이다. 한 톤에 들어 있는 배출량(embedded emissions)을 어떻게 셈하느냐에 따라 누가 얼마를 내는지가 달라진다. 그래서 다툼은 늘 방법론에서 벌어지고, <b>검증(verification)</b>을 거친 숫자만 값을 인정받는다.",
  "영업 쪽에서 갈리는 것은 <b>전가(pass-through)</b>다. 늘어난 비용을 가격에 얹을 수 있는 고객이 있고, 얹는 순간 떠나는 고객이 있다. 검증된 데이터가 있으면 <b>친환경 프리미엄(green premium)</b>이 붙지만, 없으면 그냥 값만 오른 제품이 된다."
 ],
 lines:[
  {s:"A",en:"Once emissions carry a price at the border, our cost base stops being just steel and energy and starts including how we made it.",
   ko:"국경에서 배출에 값이 붙는 순간, 우리 원가는 철과 에너지만이 아니라 어떻게 만들었느냐까지 포함하게 됩니다.",
   notes:[{t:"carry a price",k:"collocation",m:"값이 매겨지다, 대가가 따르다",tip:"Everything carries a price now. carry a risk / carry a penalty 로도 확장됩니다."},
          {t:"cost base",k:"business",m:"원가 구조, 비용 기반",tip:"lower our cost base = 원가 구조를 낮추다. 경영진 보고의 단골 표현입니다."},
          {t:"stops being A and starts including B",k:"grammar",m:"A이기를 멈추고 B를 포함하기 시작하다",tip:"stop과 start 뒤에 나란히 동명사를 붙여 변화를 한 문장에 담았습니다."}]},
  {s:"B",en:"In theory. In practice, nobody can agree on how to measure what's embedded in a ton, which is where every negotiation stalls.",
   ko:"이론상은요. 현실에선 한 톤에 뭐가 들어 있는지 재는 방법부터 합의가 안 되고, 협상은 늘 거기서 멈춥니다.",
   notes:[{t:"In theory. In practice, ~",k:"idiom",m:"이론상은 그렇고, 현실은 ~",tip:"두 문장으로 끊어 던지는 반박 리듬입니다. 토론에서 아주 강하게 들립니다."},
          {t:"embedded",k:"business",m:"(제품 안에) 내재된",tip:"embedded emissions / embedded cost. 겉으로 안 보이지만 안에 들어 있다는 뜻."},
          {t:"which is where ~ stalls",k:"grammar",m:"바로 거기서 ~이 멈춘다",tip:"앞 절을 which로 받고 관계부사 where로 '지점'을 짚습니다. 병목을 지목하는 세련된 형태입니다."}]},
  {s:"A",en:"That's the whole fight. Measurement decides who pays, so everyone argues about method while pretending to argue about principle.",
   ko:"싸움의 전부가 거기예요. 측정이 누가 낼지를 정하니, 다들 원칙을 두고 다투는 척하면서 방법론을 두고 다투는 거죠.",
   notes:[{t:"That's the whole fight.",k:"colloquial",m:"바로 그 지점이 쟁점의 전부입니다",tip:"That's the whole point. 의 변형. 핵심을 한마디로 못 박을 때 씁니다."},
          {t:"while pretending to ~",k:"grammar",m:"~하는 척하면서",tip:"분사구문입니다. 주어가 같으므로 while 뒤에 주어를 다시 쓰지 않습니다."}]},
  {s:"B",en:"And meanwhile my customers want a number today, not a methodology paper next year that three consultants will disagree with anyway.",
   ko:"그러는 동안 제 고객들은 오늘 숫자를 원해요. 어차피 컨설턴트 셋이 서로 반대할 내년 방법론 보고서가 아니라요.",
   notes:[{t:"And meanwhile ~",k:"colloquial",m:"그러는 사이에 (현실은)",tip:"이상론을 현실로 끌어내릴 때 씁니다. 영업이 기획을 반박하는 전형적인 시작입니다."},
          {t:"a paper that consultants will disagree with",k:"grammar",m:"컨설턴트들이 반대할 보고서",tip:"관계절 끝에 전치사 with가 남습니다. disagree with ~ 의 with가 사라지지 않도록 주의하세요."}]},
  {s:"A",en:"Give them a range and the assumptions behind it. A precise number that turns out to be wrong costs more than an honest range.",
   ko:"구간으로 주고 그 뒤의 전제도 밝히세요. 정밀했다가 틀린 숫자가 정직한 구간보다 비싸게 먹힙니다.",
   notes:[{t:"the assumptions behind it",k:"business",m:"그 숫자가 딛고 선 전제",tip:"What are the assumptions behind this? 는 숫자를 검증할 때 가장 좋은 질문입니다."},
          {t:"a number that turns out to be wrong",k:"grammar",m:"나중에 틀린 것으로 드러나는 숫자",tip:"turn out to be ~ = 결국 ~로 밝혀지다. 관계절 안에 넣으면 위험을 명사에 붙일 수 있습니다."}]},
  {s:"B",en:"Try selling a range to a buyer whose own boss wants one figure. They read uncertainty as risk and price it against us.",
   ko:"자기 상사가 숫자 하나를 원하는 구매자한테 구간을 한번 팔아 보세요. 불확실성을 위험으로 읽고 우리한테 불리하게 값을 매깁니다.",
   notes:[{t:"Try ~ing.",k:"colloquial",m:"(비꼬듯) 그거 한번 해 보시죠",tip:"Try explaining that to a customer. 실현 불가능함을 지적하는 반어법입니다."},
          {t:"a buyer whose own boss wants ~",k:"grammar",m:"자기 상사가 ~을 원하는 구매자",tip:"소유격 관계대명사 whose입니다. 사람의 사정을 한 문장에 접어 넣을 때 매우 유용합니다."},
          {t:"price it against us",k:"business",m:"우리에게 불리하게 가격에 반영하다",tip:"price A in(가격에 반영하다) / price A against B(불리하게 매기다) 를 짝으로 외우세요."}]},
  {s:"A",en:"Then we verify early and get certified, because verification is what turns a claim anyone can make into a discount only we can offer.",
   ko:"그럼 일찍 검증받고 인증까지 받죠. 누구나 할 수 있는 주장을 우리만 줄 수 있는 할인으로 바꾸는 게 검증이니까요.",
   notes:[{t:"turn A into B",k:"phrasal",m:"A를 B로 바꾸다",tip:"What turns a claim into evidence? 처럼 씁니다. 문장을 힘 있게 만드는 골격입니다."},
          {t:"a claim anyone can make / a discount only we can offer",k:"grammar",m:"누구나 할 수 있는 주장 / 우리만 줄 수 있는 할인",tip:"같은 접촉절 구조를 두 번 써서 대구를 만들었습니다. 차별성을 설명하는 데 최적입니다."}]},
  {s:"B",en:"Certification costs money we'd have to pass through, and the thin-margin customers who make up half our volume will simply walk.",
   ko:"인증에는 우리가 전가해야 할 돈이 들고, 물량의 절반을 차지하는 마진 얇은 고객들은 그냥 떠날 겁니다.",
   notes:[{t:"pass ~ through",k:"business",m:"(비용을) 가격에 전가하다",tip:"pass the cost through to customers. 명사형 pass-through도 그대로 씁니다."},
          {t:"customers who make up half our volume",k:"grammar",m:"우리 물량의 절반을 차지하는 고객들",tip:"make up = 구성하다, 차지하다. 관계절로 비중을 밝혀 반박의 무게를 실었습니다."},
          {t:"walk",k:"colloquial",m:"(거래를 접고) 떠나다",tip:"If we raise it, they'll walk. walk away from the deal의 줄임으로 쓰입니다."}]},
  {s:"A",en:"Some will. Others will pay a premium the moment their own reporting depends on numbers that somebody has actually audited.",
   ko:"일부는 떠나겠죠. 하지만 자기네 보고가 누군가 실제로 감사한 숫자에 걸리는 순간, 웃돈을 낼 고객도 있습니다.",
   notes:[{t:"pay a premium",k:"collocation",m:"웃돈을 지불하다",tip:"pay a premium for quality. 반대는 at a discount. 한 세트로 외우세요."},
          {t:"numbers that somebody has actually audited",k:"grammar",m:"누군가 실제로 감사한 숫자",tip:"현재완료 관계절입니다. 검증 여부가 가치를 가른다는 논지를 명사 안에 넣었습니다."}]},
  {s:"B",en:"You're betting their regulators bite before ours do, which is a big assumption to build a capital plan on.",
   ko:"그쪽 규제가 우리 쪽보다 먼저 조여든다는 데 거시는 거죠. 자본 계획을 얹기엔 큰 가정입니다.",
   notes:[{t:"bite",k:"idiom",m:"(규제·정책이) 실제로 아프게 작용하다",tip:"When do the rules start to bite? 발효는 됐지만 아직 체감되지 않을 때 씁니다."},
          {t:"a big assumption to build a plan on",k:"grammar",m:"계획을 얹기에는 큰 가정",tip:"명사 + to부정사 + 문미 전치사 on 구조입니다. build A on B의 on이 그대로 남습니다."}]},
  {s:"A",en:"It's not a bet on timing. It's a bet that a direction which every major buyer is already moving in doesn't reverse.",
   ko:"시점에 거는 게 아니에요. 주요 구매자들이 이미 그쪽으로 움직이고 있는 방향이 되돌아가지 않는다는 데 거는 겁니다.",
   notes:[{t:"It's not A. It's B.",k:"grammar",m:"A가 아니라 B입니다",tip:"상대의 규정을 고쳐 잡는 대조 골격. 짧게 끊어 말할수록 힘이 실립니다."},
          {t:"a direction which everyone is moving in",k:"grammar",m:"모두가 그쪽으로 움직이고 있는 방향",tip:"관계절 끝에 전치사 in이 남습니다. move in a direction의 in을 빠뜨리지 마세요."}]},
  {s:"B",en:"Fair enough. Still, if we move first we carry the cost alone for years while everyone else watches to see what it does to us.",
   ko:"일리 있어요. 그래도 먼저 움직이면 몇 년을 혼자 비용을 짊어지고, 나머지는 우리가 어떻게 되나 구경할 겁니다.",
   notes:[{t:"Fair enough. Still, ~",k:"idiom",m:"일리는 있습니다. 그래도 ~",tip:"인정하고 반박으로 넘어가는 다리. 토론에서 가장 자주 쓰는 전환입니다."},
          {t:"move first",k:"business",m:"선제적으로 나서다",tip:"first mover advantage와 짝. move first / wait and see 가 대립 구도를 만듭니다."},
          {t:"watch to see what it does to us",k:"grammar",m:"그게 우리한테 어떤 결과를 내는지 지켜보다",tip:"watch to see + 의문사절 구조입니다. 관망하는 태도를 정확히 묘사합니다."}]},
  {s:"A",en:"And if we move last we buy the same equipment at panic prices alongside everyone who waited exactly as long as we did.",
   ko:"마지막에 움직이면, 우리만큼 기다린 사람들과 나란히 똑같은 설비를 값이 치솟은 상태로 사게 되죠.",
   notes:[{t:"at panic prices",k:"collocation",m:"수요가 몰려 값이 치솟은 상태로",tip:"buy at panic prices / sell in a panic. 시장 심리를 한 단어로 표현합니다."},
          {t:"everyone who waited exactly as long as we did",k:"grammar",m:"우리만큼 딱 그만큼 기다린 모든 사람",tip:"as long as + 주어 + did 구조입니다. 끝의 did가 waited의 반복을 대신합니다."}]},
  {s:"B",en:"That argument holds water. I just don't want us dressing up a cost as strategy in a deck that somebody quotes back at us later.",
   ko:"그 논리는 설득력이 있네요. 다만 나중에 누가 그대로 되읊을 장표에서 비용을 전략인 척 포장하는 건 원치 않습니다.",
   notes:[{t:"hold water",k:"idiom",m:"(논리가) 말이 되다, 설득력이 있다",tip:"That doesn't hold water. 부정문으로 훨씬 자주 씁니다."},
          {t:"dress up A as B",k:"idiom",m:"A를 B인 것처럼 포장하다",tip:"8일차에도 나온 표현입니다. 비판할 때 반복해서 쓰게 됩니다."},
          {t:"a deck somebody quotes back at us",k:"grammar",m:"누군가 나중에 그대로 들이밀 장표",tip:"quote it back at someone = 남의 말을 그대로 인용해 되받다. 회의에서 흔한 위험입니다."}]},
  {s:"A",en:"Then let's be blunt about it. Part of this spend is compliance we can't avoid, and part is positioning we're choosing to buy.",
   ko:"그럼 솔직하게 말하죠. 이 지출의 일부는 피할 수 없는 규제 대응이고, 일부는 우리가 사기로 선택한 포지셔닝입니다.",
   notes:[{t:"be blunt about it",k:"idiom",m:"에두르지 않고 솔직히 말하다",tip:"Let me be blunt. 로 문장을 열면 '돌직구 갑니다'라는 신호가 됩니다."},
          {t:"compliance we can't avoid / positioning we're choosing to buy",k:"grammar",m:"피할 수 없는 규제 대응 / 사기로 선택한 포지셔닝",tip:"같은 접촉절 구조로 두 항목을 나눴습니다. 예산을 정직하게 쪼개 보이는 화법입니다."}]},
  {s:"B",en:"I can sell that. What I can't sell is a green premium with nothing behind it except a logo and a promise.",
   ko:"그건 팔 수 있어요. 못 파는 건 로고와 약속 말고는 뒷받침이 없는 친환경 프리미엄입니다.",
   notes:[{t:"I can sell that.",k:"idiom",m:"그 정도면 (고객·윗선을) 설득할 수 있습니다",tip:"sell = 설득하다. sell it upstairs / sell it internally 로 확장됩니다."},
          {t:"What I can't sell is ~",k:"grammar",m:"내가 못 파는 것은 ~이다",tip:"what절을 주어로 세운 강조구문입니다. 앞 문장과 대구를 이루며 조건을 분명히 합니다."},
          {t:"with nothing behind it",k:"colloquial",m:"뒷받침할 근거가 없는",tip:"a promise with nothing behind it. 실체 없음을 지적하는 짧은 꼬리표입니다."}]},
  {s:"A",en:"Nobody's asking you to. The premium only sticks if the verified data behind it survives the first customer who audits us.",
   ko:"아무도 그러라고 안 합니다. 프리미엄은 우리를 감사하는 첫 고객 앞에서 그 데이터가 버텨야만 유지돼요.",
   notes:[{t:"stick",k:"idiom",m:"(가격·주장이) 자리를 잡고 유지되다",tip:"The price increase didn't stick. 올렸다가 도로 내렸다는 뜻이 됩니다."},
          {t:"survives the first customer who audits us",k:"grammar",m:"우리를 감사하는 첫 고객 앞에서 버티다",tip:"survive를 '견뎌 내다'로 쓰는 용법입니다. 뒤에 사람이 목적어로 올 수 있다는 점이 포인트입니다."}]},
  {s:"B",en:"Then get me the data early enough to write it into next year's contracts, because after signing it becomes somebody else's problem.",
   ko:"그럼 내년 계약서에 넣을 수 있을 만큼 일찍 데이터를 주세요. 서명하고 나면 그건 다른 사람 문제가 되니까요.",
   notes:[{t:"early enough to ~",k:"grammar",m:"~할 수 있을 만큼 충분히 일찍",tip:"형용사 + enough to 구조. 마감을 압박할 때 부드럽지만 분명합니다."},
          {t:"write it into ~",k:"phrasal",m:"~에 조항으로 넣다",tip:"write it into the contract / into the spec. 구두 합의를 문서로 못 박는다는 뜻."}]},
  {s:"A",en:"Deal. And we should hedge by locking in the low-emission route for the accounts whose own targets depend on ours.",
   ko:"좋습니다. 그리고 자기네 목표가 우리 것에 걸려 있는 거래처부터 저배출 공정을 확보해 두는 식으로 헤지하죠.",
   notes:[{t:"hedge",k:"business",m:"위험을 나눠 걸다",tip:"hedge our bets = 한쪽에 다 걸지 않다. 전략 회의의 필수 동사입니다."},
          {t:"lock in ~",k:"phrasal",m:"~을 미리 확정해 두다",tip:"lock in the price / the capacity. 나중에 바뀌지 않게 묶어 둔다는 뜻입니다."},
          {t:"accounts whose own targets depend on ours",k:"grammar",m:"자기네 목표가 우리 것에 달린 거래처",tip:"소유격 관계대명사 whose로 이해관계의 사슬을 한 문장에 담았습니다."}]},
  {s:"B",en:"That works. Bite the bullet where it counts, and let the rest follow the market once somebody else has paid for the learning.",
   ko:"괜찮네요. 중요한 데서는 감수하고, 나머지는 누가 학습 비용을 대신 치른 뒤에 시장을 따라가게 두죠.",
   notes:[{t:"bite the bullet",k:"idiom",m:"싫지만 감수하고 실행하다",tip:"We had to bite the bullet and raise prices. 통째로 외우는 표현입니다."},
          {t:"where it counts",k:"idiom",m:"정말 중요한 곳에서는",tip:"Spend where it counts. 선택과 집중을 한마디로 표현합니다."},
          {t:"pay for the learning",k:"collocation",m:"시행착오 비용을 치르다",tip:"먼저 움직인 쪽이 치르는 값을 뜻합니다. learning curve와 함께 알아 두세요."}]}
 ],
 keys:[
  {en:"pass the cost through",ko:"비용을 가격에 전가하다",ex:"We can't pass the whole increase through to buyers."},
  {en:"a level playing field",ko:"공정한 경쟁 조건",ex:"Importers want a level playing field, not a subsidy."},
  {en:"hold water",ko:"(논리가) 설득력이 있다",ex:"That explanation doesn't hold water."},
  {en:"In theory. In practice, ~",ko:"이론상은 그렇고, 현실은 ~",ex:"In theory it's automated. In practice, someone still checks it."},
  {en:"hedge our bets",ko:"한쪽에 다 걸지 않다",ex:"Let's hedge our bets and qualify a second supplier."},
  {en:"lock in ~",ko:"~을 미리 확정해 두다",ex:"We locked in the freight rate for two years."},
  {en:"bite the bullet",ko:"싫지만 감수하고 실행하다",ex:"At some point we bite the bullet and replace the line."},
  {en:"That's a big assumption.",ko:"그건 큰 가정입니다",ex:"That's a big assumption — demand could fall instead."}
 ],
 out:[
  {q:"Explain to a customer why your product costs more this year, without sounding defensive.",hint:"pass the cost through / verified / a level playing field"},
  {q:"Argue for moving first on an expensive change, then argue for waiting.",hint:"move first / hedge our bets / that's a big assumption"},
  {q:"Someone calls your environmental spending a marketing exercise. Answer them honestly.",hint:"be blunt about it / part is A, part is B / with nothing behind it"}
 ]
},
{
 id:"w2d3", day:10, cat:"인구·노동", level:"B2+",
 title:"The Shift Nobody Can Fill",
 titleKo:"채울 수 없는 교대조 — 고령화와 현장의 기술 전수",
 names:{A:"Ines (인사)", B:"Karl (제조 현장 반장)"},
 brief:[
  "숙련 인력의 은퇴는 인원 문제로 보이지만 실제로는 <b>지식 문제</b>다. 사람이 나가면 자리는 채울 수 있어도, 그 사람 머릿속에만 있던 판단은 함께 나간다. 이것을 <b>암묵지(tacit knowledge)</b>라고 부른다.",
  "암묵지가 어려운 이유는 <b>말로 옮겨지지 않기 때문</b>이다. 소리로 이상을 알아채고, 손끝으로 온도를 가늠하는 판단은 매뉴얼에 담기지 않는다. 그래서 전수는 문서가 아니라 <b>같이 서 있는 시간</b>으로만 일어난다.",
  "현장이 이 문제를 미루는 방식은 대개 <b>초과근무</b>다. 당장은 돌아가지만 격차를 감출 뿐 좁히지는 못한다. 이런 임시 대응을 <b>stopgap</b>이라 하고, 반복되면 은퇴가 몰리는 시점에 한꺼번에 터진다.",
  "자동화는 이 문제의 해답이면서 동시에 함정이다. 기계가 공정을 대신해도 <b>결과가 이상할 때 알아채는 판단</b>은 사람에게 남는다. 그래서 채용과 훈련의 기준이 「손」에서 「판단」으로 옮겨 간다."
 ],
 lines:[
  {s:"A",en:"Three of your senior operators retire within a year, and we have nobody shadowing them who could take a shift alone tomorrow.",
   ko:"반장님 쪽 숙련 오퍼레이터 세 분이 1년 안에 은퇴하는데, 내일 혼자 교대를 설 수 있을 만큼 붙어 배우는 사람이 없어요.",
   notes:[{t:"shadow (someone)",k:"business",m:"옆에 붙어 따라다니며 배우다",tip:"job shadowing = 현장 밀착 학습. 명사로도 동사로도 씁니다."},
          {t:"nobody shadowing them who could ~",k:"grammar",m:"~할 수 있을 만큼 붙어 배우는 사람이 아무도 없다",tip:"현재분사와 관계절이 같은 명사에 이어 붙었습니다. 조건을 겹쳐 놓아 부족함을 정확히 규정합니다."}]},
  {s:"B",en:"You can't shadow forty years of feel in twelve months, and anyone who tells you otherwise has never stood on the floor.",
   ko:"40년 몸에 밴 감각을 열두 달 붙어서 배울 순 없어요. 된다고 말하는 사람은 현장에 서 본 적이 없는 겁니다.",
   notes:[{t:"feel",k:"colloquial",m:"(설명 못 하는) 감각, 손맛",tip:"He has a feel for the machine. 명사로 쓰면 경험에서 온 직관을 뜻합니다."},
          {t:"anyone who tells you otherwise",k:"grammar",m:"그렇지 않다고 말하는 사람은 누구든",tip:"otherwise = 그와 다르게. 반박을 미리 봉쇄하는 정형 표현입니다."},
          {t:"the floor",k:"business",m:"(공장의) 현장",tip:"on the shop floor = 생산 현장에서. 사무실과 대비되는 말입니다."}]},
  {s:"A",en:"I know. But if we do nothing, that knowledge walks out the door with them and there's no version of it left behind.",
   ko:"압니다. 그런데 아무것도 안 하면 그 지식이 그분들과 함께 걸어 나가고, 남는 판본은 하나도 없어요.",
   notes:[{t:"walk out the door",k:"idiom",m:"(사람과 함께 지식·고객이) 빠져나가다",tip:"Our best accounts walked out the door with him. 퇴사 리스크를 말할 때의 정석입니다."},
          {t:"there's no version of it left behind",k:"grammar",m:"남겨진 판본이 하나도 없다",tip:"과거분사 left가 명사를 뒤에서 꾸밉니다. leave behind = 남겨 두다."}]},
  {s:"B",en:"It already is. We papered over the last two retirements with overtime and luck, neither of which is a plan I'd write down.",
   ko:"이미 그러고 있어요. 지난 두 번의 은퇴는 초과근무와 운으로 덮었는데, 둘 다 제가 문서로 쓸 만한 계획은 아니죠.",
   notes:[{t:"paper over ~",k:"phrasal",m:"~을 임시로 덮어 감추다",tip:"paper over the cracks = 균열을 벽지로 덮다. 근본 해결이 아님을 지적합니다."},
          {t:", neither of which ~",k:"grammar",m:"그런데 그 둘 다 ~이 아니다",tip:"수량사 + of which의 계속적 용법입니다. 앞의 두 항목을 한 번에 묶어 평가할 때 씁니다."}]},
  {s:"A",en:"Overtime is a stopgap. It hides the gap from anyone reading the report instead of closing it on the floor.",
   ko:"초과근무는 임시방편이에요. 현장에서 격차를 좁히는 게 아니라, 보고서 읽는 사람 눈에서 가리는 거죠.",
   notes:[{t:"a stopgap",k:"business",m:"임시방편, 땜질 처방",tip:"a stopgap measure / a stopgap solution. band-aid solution과 같은 뜻입니다."},
          {t:"close the gap",k:"collocation",m:"격차를 좁히다",tip:"close/narrow/widen the gap 세트로 외우세요. 실적 보고에 매일 나옵니다."},
          {t:"hide A from B instead of -ing",k:"grammar",m:"~하는 대신 A를 B에게서 감추다",tip:"전치사 from과 instead of가 한 문장에 들어갔습니다. 두 행위를 대비시키는 구조입니다."}]},
  {s:"B",en:"Then give me apprentices who stay. The last three picked it up quickly and left for shifts that didn't start at five in the morning.",
   ko:"그럼 남아 있을 견습생을 주세요. 지난 세 명은 빨리 익히고는 새벽 다섯 시에 시작하지 않는 교대조로 떠났어요.",
   notes:[{t:"pick it up",k:"phrasal",m:"(기술을) 어깨너머로 익히다",tip:"He picked it up on the job. 정식 교육 없이 배웠다는 뜻으로 아주 자주 씁니다."},
          {t:"shifts that didn't start at five",k:"grammar",m:"새벽 다섯 시에 시작하지 않는 교대조",tip:"관계절로 이직 사유를 구체적으로 밝혔습니다. 불평을 사실로 바꾸는 화법입니다."}]},
  {s:"A",en:"That's a retention problem, and I'll own it. But pay alone won't fix a pipeline that has been thin for five years.",
   ko:"그건 잔류 문제고, 제가 책임지겠습니다. 그런데 5년째 얇은 인력 파이프라인이 급여만으로 고쳐지진 않아요.",
   notes:[{t:"retention",k:"business",m:"(직원) 잔류·유지",tip:"retention rate / a retention problem. 반대는 turnover(이직률)입니다."},
          {t:"a pipeline that has been thin for five years",k:"grammar",m:"5년째 얇았던 파이프라인",tip:"현재완료 관계절이 '지금까지 계속'을 표시합니다. 문제의 만성을 문법으로 드러냅니다."}]},
  {s:"B",en:"Money helps more than you think when the work is hot, loud, and scheduled at hours that make a family life awkward.",
   ko:"덥고 시끄럽고 가정생활이 어려워지는 시간대에 배치되는 일이라면, 돈이 생각보다 훨씬 큽니다.",
   notes:[{t:"more than you think",k:"colloquial",m:"생각하시는 것보다 더",tip:"문장 뒤에 붙이는 짧은 강조. It matters more than you think."},
          {t:"hours that make a family life awkward",k:"grammar",m:"가정생활을 곤란하게 만드는 시간대",tip:"make + 목적어 + 형용사 구조가 관계절 안에 들어갔습니다. 교대 근무의 부담을 구체화합니다."}]},
  {s:"A",en:"It does, up to a point. Past that, people leave because nobody ever taught them properly and they got tired of guessing.",
   ko:"어느 선까지는 그렇죠. 그 선을 넘으면, 제대로 가르쳐 준 사람이 없어서 짐작하는 데 지쳐 떠납니다.",
   notes:[{t:"up to a point",k:"idiom",m:"어느 정도까지는",tip:"부분 동의의 대표 표현입니다. I agree, up to a point."},
          {t:"get tired of -ing",k:"grammar",m:"~하는 데 지치다",tip:"of 뒤라 동명사입니다. get tired of waiting / of explaining."}]},
  {s:"B",en:"Fair. Half of what I know I picked up watching a man who never once explained why he did anything.",
   ko:"인정합니다. 제가 아는 것의 절반은, 왜 그렇게 하는지 한 번도 설명해 준 적 없는 사람을 보면서 익힌 거예요.",
   notes:[{t:"Half of what I know",k:"grammar",m:"내가 아는 것의 절반",tip:"what절을 목적어로 쓰는 구조. 회화에서 문장을 길고 자연스럽게 늘려 줍니다."},
          {t:"a man who never once explained ~",k:"grammar",m:"한 번도 설명해 준 적 없는 사람",tip:"never once는 '단 한 번도'라는 강조입니다. 관계절 안에서 원망을 담담하게 실어 줍니다."}]},
  {s:"A",en:"That's exactly the problem — tacit knowledge that nobody ever wrote down because writing it down was never anyone's job.",
   ko:"바로 그게 문제예요. 아무도 적어 두지 않은 암묵지죠. 적어 두는 게 누구의 일도 아니었으니까요.",
   notes:[{t:"tacit knowledge",k:"business",m:"암묵지, 말로 옮기지 못한 지식",tip:"explicit knowledge(형식지)와 짝입니다. 지식경영의 기본 용어입니다."},
          {t:"That's exactly the problem.",k:"colloquial",m:"바로 그게 문제입니다",tip:"상대의 말을 받아 내 논점으로 끌어오는 전환 문장입니다."},
          {t:"because -ing was never anyone's job",k:"grammar",m:"~하는 것이 누구의 업무도 아니었기 때문에",tip:"동명사를 주어로 세웠습니다. 책임의 공백을 지적하는 조직 화법입니다."}]},
  {s:"B",en:"Some of it can't be written down. You feel a bad weld through the handle before anything shows up on a screen.",
   ko:"그중 일부는 적을 수가 없어요. 화면에 뭐가 뜨기 전에 손잡이로 불량 용접이 느껴지거든요.",
   notes:[{t:"before anything shows up on a screen",k:"grammar",m:"화면에 뭐가 뜨기도 전에",tip:"감각이 계측을 앞선다는 뜻을 시간 접속사로 표현했습니다. 현장 설명에 잘 어울립니다."}]},
  {s:"A",en:"Agreed, but the other half can. Let's capture what's teachable and stop pretending that everything a veteran knows is art.",
   ko:"동의해요. 그런데 나머지 절반은 가능합니다. 가르칠 수 있는 건 담아 두고, 숙련자가 아는 게 전부 예술인 척은 그만두죠.",
   notes:[{t:"capture",k:"business",m:"(지식을) 붙잡아 기록으로 남기다",tip:"capture the process / capture lessons learned. 문서화를 뜻하는 세련된 동사입니다."},
          {t:"what's teachable",k:"grammar",m:"가르칠 수 있는 것",tip:"what절이 목적어가 됐습니다. -able 형용사를 붙이면 범위를 정확히 자를 수 있습니다."},
          {t:"stop pretending that ~",k:"colloquial",m:"~인 척하는 걸 그만두다",tip:"직설적이지만 무례하지 않은 압박. Let's stop pretending this is temporary."}]},
  {s:"B",en:"Fine. Give me protected time on the schedule for it, not another folder that nobody opens after the first week.",
   ko:"좋아요. 그럼 일정에 보호된 시간을 주세요. 첫 주 지나면 아무도 안 여는 폴더 하나 더 말고요.",
   notes:[{t:"another folder that nobody opens",k:"grammar",m:"아무도 열지 않는 문서 하나 더",tip:"형식적 산출물을 비꼬는 관용적 표현. 관계절이 냉소를 담는 자리입니다."},
          {t:"protected time",k:"business",m:"(다른 일에 뺏기지 않는) 확보된 시간",tip:"protected hours라고도 합니다. 교육·개선활동 예산을 지킬 때 쓰는 말입니다."}]},
  {s:"A",en:"You'll get it. In exchange, I want each of the seniors paired with two juniors whose names go on the schedule with theirs.",
   ko:"드리겠습니다. 대신 숙련자마다 후배 둘씩 짝지어 주시고, 그 이름들이 일정표에 같이 올라가야 합니다.",
   notes:[{t:"In exchange, ~",k:"business",m:"그 대신에",tip:"조건부 합의를 만드는 연결어. 협상에서 주고받기를 명시할 때 씁니다."},
          {t:"juniors whose names go on the schedule",k:"grammar",m:"이름이 일정표에 오르는 후배들",tip:"소유격 관계대명사 whose입니다. 약속을 문서에 묶는다는 뜻을 문법으로 표현했습니다."}]},
  {s:"B",en:"Two is a lot. One learns while the other watches the first one make the mistakes that nobody wants repeated.",
   ko:"둘은 많아요. 하나는 배우고, 다른 하나는 첫째가 아무도 반복되길 원치 않는 실수를 하는 걸 구경하게 됩니다.",
   notes:[{t:"watch someone do ~",k:"grammar",m:"~가 …하는 것을 지켜보다",tip:"지각동사 뒤 원형부정사. watch him make / see her leave. 한국인이 자주 틀리는 곳입니다."},
          {t:"mistakes that nobody wants repeated",k:"grammar",m:"아무도 반복되길 원치 않는 실수",tip:"want + 목적어 + 과거분사 구조입니다. want them to be repeated를 줄인 형태로 보면 쉽습니다."}]},
  {s:"A",en:"That's still learning, and it gives us a backup for the day one of them moves on without much notice.",
   ko:"그것도 배움이고, 둘 중 하나가 별 예고 없이 떠나는 날을 대비한 여유가 생기죠.",
   notes:[{t:"move on",k:"phrasal",m:"(회사를) 떠나다, 다음 자리로 가다",tip:"leave보다 완곡합니다. She moved on last spring. 퇴사를 부드럽게 말할 때."},
          {t:"the day one of them moves on",k:"grammar",m:"그중 하나가 떠나는 그날",tip:"시간 명사 뒤 관계부사 when이 생략된 접촉절입니다. 현재시제가 미래의 그날을 가리킵니다."}]},
  {s:"B",en:"The writing's on the wall anyway. Automation will take some of these stations, probably the ones we've just agreed to train for.",
   ko:"어차피 흐름은 뻔합니다. 자동화가 이 공정 자리 몇 개는 가져갈 텐데, 하필 우리가 방금 훈련하기로 한 자리들이겠죠.",
   notes:[{t:"The writing's on the wall.",k:"idiom",m:"흐름은 이미 정해져 있다",tip:"피할 수 없는 변화를 뜻합니다. 다소 비관적인 어감이라 자리를 가려 씁니다."},
          {t:"the ones we've just agreed to train for",k:"grammar",m:"우리가 방금 훈련하기로 합의한 그 자리들",tip:"the ones that ~ 으로 앞 명사를 받고 문미에 for가 남습니다. 아이러니를 얹는 자리입니다."}]},
  {s:"A",en:"Some, not all. The machines still need somebody who knows when the output looks wrong before the alarm decides it is.",
   ko:"일부지 전부는 아니에요. 기계도 경보가 울리기 전에 결과가 이상하다는 걸 아는 사람이 여전히 필요합니다.",
   notes:[{t:"Some, not all.",k:"colloquial",m:"일부지 전부는 아닙니다",tip:"두 단어로 과장을 잘라내는 반박. 토론에서 아주 경제적인 문장입니다."},
          {t:"knows when the output looks wrong",k:"grammar",m:"결과가 이상해 보이는 때를 알다",tip:"know 뒤의 when절은 간접의문문이라 주어+동사 어순입니다. 판단력을 정의하는 문장입니다."}]},
  {s:"B",en:"Then let's train for that judgment and stop hiring for a pair of hands that the next machine will make unnecessary.",
   ko:"그럼 그 판단력을 겨냥해 훈련하고, 다음 기계가 필요 없게 만들 손 한 쌍을 뽑는 건 그만두죠.",
   notes:[{t:"train for ~",k:"collocation",m:"~을 겨냥해 훈련하다",tip:"train for judgment / hire for attitude. 목표를 명시하는 전치사 for를 씁니다."},
          {t:"hands that the next machine will make unnecessary",k:"grammar",m:"다음 기계가 필요 없게 만들 손",tip:"make + 목적어 + 형용사가 관계절 안에 들어갔습니다. 목적어가 앞으로 빠져 hands가 됐습니다."}]}
 ],
 keys:[
  {en:"walk out the door",ko:"(사람과 함께 지식이) 빠져나가다",ex:"When he retires, thirty years walk out the door."},
  {en:"paper over the cracks",ko:"근본 문제를 임시로 덮다",ex:"Hiring temps just papers over the cracks."},
  {en:"a stopgap",ko:"임시방편, 땜질 처방",ex:"Overtime is a stopgap, not a plan."},
  {en:"pick it up on the job",ko:"일하면서 어깨너머로 익히다",ex:"Nobody trained me; I picked it up on the job."},
  {en:"tacit knowledge",ko:"암묵지, 말로 옮기지 못한 지식",ex:"Most of our tacit knowledge sits with five people."},
  {en:"up to a point",ko:"어느 정도까지는",ex:"I agree, up to a point — but not on cost."},
  {en:"move on",ko:"(회사를) 떠나다",ex:"Two of the juniors moved on within a year."},
  {en:"The writing's on the wall.",ko:"흐름은 이미 정해져 있다",ex:"The writing's on the wall for manual inspection."}
 ],
 out:[
  {q:"Describe one thing you learned at work that nobody could have written in a manual.",hint:"tacit knowledge / pick it up on the job / feel"},
  {q:"Your team lost an experienced colleague. Explain what actually left with them.",hint:"walk out the door / paper over the cracks / a stopgap"},
  {q:"Argue that automation makes training more important, not less.",hint:"train for judgment / some, not all / up to a point"}
 ]
}
