{
 id:"w4d1", day:26, cat:"도시·주거", level:"B2+",
 title:"Why Housing Never Gets Cheaper",
 titleKo:"집값은 왜 안 내려가는가 — 공급을 막는 것들",
 names:{A:"Nina (도시계획 연구자)", B:"Ethan (개발업체)"},
 brief:[
  "집값 이야기는 대개 <b>수요</b>에서 멈춥니다. 사람이 몰리고 돈이 풀렸다는 설명입니다. 그런데 같은 수요를 받고도 집값이 덜 오르는 도시가 있습니다. 차이는 <b>공급이 얼마나 빨리 따라붙느냐</b>에 있습니다.",
  "공급을 늦추는 것은 대개 기술이 아니라 <b>절차</b>입니다. 인허가에 몇 년이 걸리면 그 기간의 이자와 불확실성이 고스란히 원가가 됩니다. 그리고 절차 비용이 싼 집이나 비싼 집이나 똑같이 든다면, 짓는 쪽은 <b>비싼 집</b>을 짓습니다.",
  "여기서 <b>filtering</b>이라는 개념이 나옵니다. 새 집은 언제나 비싸고, 세월이 지나 다음 세대의 새 집이 생겨야 값이 내려간다는 것입니다. 그래서 「지금 비싼 집을 지어야 30년 뒤 싼 집이 생긴다」는 불편한 결론이 따라옵니다.",
  "마지막 층은 <b>정치</b>입니다. 새 공급으로 이득을 볼 사람은 아직 그 도시에 오지 않았고, 투표하는 사람은 이미 그 자산을 갖고 있습니다. 이 대화는 그 구조를 차분히 짚으면서, <b>절차를 예측 가능하게 만들자</b>는 현실적인 접점까지 갑니다."
 ],
 lines:[
  {s:"A",en:"Every city reports a housing shortage, and every city has rules that make construction slower.",
   ko:"도시마다 주택 부족을 보고하고, 도시마다 건설을 더 느리게 만드는 규정을 갖고 있습니다.",
   notes:[{t:"a housing shortage",k:"business",m:"주택 부족",tip:"수요에 비해 공급이 모자란 상태입니다."}]},
  {s:"B",en:"Homeowners never hear that, because the public debate blames developers for the price.",
   ko:"집주인들은 그 얘기를 듣지 못합니다. 공론은 가격의 책임을 개발업자에게 돌리니까요.",
   notes:[{t:"blame A for B",k:"collocation",m:"B의 책임을 A에게 돌리다",tip:"전치사 for 가 고정입니다."}]},
  {s:"A",en:"I disagree in part, because many developers do hold land and wait for prices to rise.",
   ko:"부분적으로는 동의하지 않습니다. 많은 개발업자가 실제로 땅을 쥐고 값이 오르기를 기다립니다.",
   notes:[{t:"I disagree in part",k:"business",m:"부분적으로 동의하지 않습니다",tip:"반대의 범위를 미리 한정합니다."},
          {t:"hold land",k:"business",m:"토지를 보유하다",tip:"개발하지 않고 갖고 있는 상태입니다."}]},
  {s:"B",en:"We hold land because approval takes four years, and no bank finances a project that may never start.",
   ko:"인허가에 4년이 걸리니까 땅을 쥐고 있는 겁니다. 시작도 못 할 수 있는 사업에 자금을 대는 은행은 없습니다.",
   notes:[{t:"approval",k:"business",m:"인허가, 승인",tip:"건설 전에 받아야 하는 행정 허가입니다."},
          {t:"finance a project",k:"business",m:"사업에 자금을 대다",tip:"동사로 쓰인 finance 입니다."}]},
  {s:"A",en:"So the delay itself becomes a cost, and that cost is added to the selling price.",
   ko:"그럼 지연 자체가 비용이 되고, 그 비용은 판매 가격에 더해집니다.",
   notes:[{t:"be added to the price",k:"business",m:"가격에 더해지다",tip:"원가 전가를 평이하게 표현합니다."}]},
  {s:"B",en:"Correct. Every month of review is interest we pay on land that produces no income.",
   ko:"맞습니다. 심사 한 달 한 달이, 아무 수입도 내지 않는 토지에 내는 이자입니다.",
   notes:[{t:"produce no income",k:"collocation",m:"수입을 내지 않다",tip:"유휴 자산의 상태입니다."}]},
  {s:"A",en:"Then why does almost every proposal only become profitable at the expensive end of the market?",
   ko:"그런데 왜 거의 모든 사업안이 고가 시장에서만 수익이 납니까?",
   notes:[{t:"become profitable",k:"business",m:"수익이 나다",tip:"비용을 넘어 이익이 발생하는 것입니다."},
          {t:"the expensive end of the market",k:"collocation",m:"고가 시장",tip:"the cheap end 와 짝을 이룹니다."}]},
  {s:"B",en:"Because the approval process costs the same for cheap flats and expensive ones.",
   ko:"인허가 절차 비용이 싼 아파트나 비싼 아파트나 똑같이 들기 때문입니다.",
   notes:[{t:"cost the same for A and B",k:"grammar",m:"A와 B에 똑같이 든다",tip:"고정비가 선택을 왜곡하는 구조입니다."}]},
  {s:"A",en:"That explains why filtering takes a generation in most cities rather than a decade.",
   ko:"그래서 대부분의 도시에서 필터링이 10년이 아니라 한 세대가 걸리는 거군요.",
   notes:[{t:"filtering",k:"business",m:"필터링",tip:"새 주택이 노후화되며 저렴해지는 과정입니다."}]},
  {s:"B",en:"Explain filtering. I know the concept, but nobody in construction uses that word.",
   ko:"필터링을 설명해 주세요. 개념은 알지만, 건설업계에서 그 단어를 쓰는 사람은 없습니다.",
   notes:[{t:"use a word",k:"collocation",m:"그 용어를 쓰다",tip:"업계 용어 여부를 확인하는 표현입니다."}]},
  {s:"A",en:"New housing is always expensive. It becomes affordable only as it ages and newer housing appears.",
   ko:"새 주택은 언제나 비쌉니다. 노후화되고 더 새 주택이 나타나야 비로소 감당할 만해집니다.",
   notes:[{t:"affordable",k:"business",m:"감당할 만한 가격의",tip:"소득 대비 부담 가능한 수준입니다."},
          {t:"age",k:"business",m:"노후화되다",tip:"시간이 지나 낡는 것입니다."}]},
  {s:"B",en:"So the way to produce cheap housing in thirty years is to build expensive housing today.",
   ko:"그럼 30년 뒤 싼 주택을 만드는 방법은 오늘 비싼 주택을 짓는 것이군요.",
   notes:[{t:"the way to A is to B",k:"grammar",m:"A 하는 방법은 B 하는 것이다",tip:"결론을 압축하는 형태입니다."}]},
  {s:"A",en:"Broadly, yes, although that argument is very difficult to explain to someone who needs housing now.",
   ko:"대체로 그렇습니다. 다만 지금 당장 집이 필요한 사람에게 설명하기는 매우 어려운 논리입니다.",
   notes:[{t:"difficult to explain to ~",k:"collocation",m:"~ 에게 설명하기 어려운",tip:"설득의 난이도를 말합니다."}]},
  {s:"B",en:"Which is why the politics do not change: the people who benefit have not moved here yet.",
   ko:"그래서 정치가 바뀌지 않는 겁니다. 이득을 볼 사람들이 아직 이곳으로 이사 오지 않았으니까요.",
   notes:[{t:"benefit",k:"business",m:"이득을 보다",tip:"benefit from ~ 형태로도 자주 씁니다."}]},
  {s:"A",en:"And the residents who vote already own the asset that new supply would make cheaper.",
   ko:"그리고 투표하는 주민들은 새 공급이 값을 떨어뜨릴 바로 그 자산을 이미 소유하고 있습니다.",
   notes:[{t:"an asset",k:"business",m:"자산",tip:"가치를 지닌 재산입니다."}]},
  {s:"B",en:"You have described the problem in one sentence, and planning policy cannot solve that part.",
   ko:"문제를 한 문장으로 설명하셨습니다. 그리고 도시계획 정책은 그 부분을 해결할 수 없습니다.",
   notes:[{t:"solve a part of a problem",k:"collocation",m:"문제의 일부를 해결하다",tip:"해결 범위를 한정합니다."}]},
  {s:"A",en:"Planning can solve the procedural part: approve by right when the rules are met, instead of reviewing each case.",
   ko:"도시계획은 절차적인 부분을 해결할 수 있습니다. 건건이 심사하는 대신 규정을 충족하면 자동 승인하는 방식으로요.",
   notes:[{t:"approve by right",k:"business",m:"요건 충족 시 자동 승인하다",tip:"재량 심사 없이 규정만 보는 방식입니다."},
          {t:"review each case",k:"collocation",m:"건건이 심사하다",tip:"개별 재량 판단을 뜻합니다."}]},
  {s:"B",en:"That would change our business completely, because uncertainty is what we include in every bid.",
   ko:"그건 우리 사업을 완전히 바꿉니다. 우리가 모든 입찰가에 포함하는 게 불확실성이니까요.",
   notes:[{t:"include something in a bid",k:"business",m:"입찰가에 포함하다",tip:"비용으로 반영한다는 뜻입니다."}]},
  {s:"A",en:"Then we should argue for predictable rules rather than looser ones, which is much easier to defend.",
   ko:"그럼 느슨한 규칙이 아니라 예측 가능한 규칙을 주장해야 합니다. 그쪽이 훨씬 방어하기 쉽습니다.",
   notes:[{t:"predictable rather than looser",k:"collocation",m:"느슨한 것이 아니라 예측 가능한",tip:"규제 논쟁의 프레임을 바꾸는 표현입니다."}]},
  {s:"B",en:"Agreed. Nobody publicly defends a slow process, so that is where the argument can succeed.",
   ko:"동의합니다. 느린 절차를 공개적으로 옹호하는 사람은 없으니, 논쟁이 이길 수 있는 지점이 거기입니다.",
   notes:[{t:"publicly defend",k:"collocation",m:"공개적으로 옹호하다",tip:"사석과 공석의 차이를 드러냅니다."}]}
 ],
 keys:[
  {en:"I disagree in part",ko:"부분적으로 동의하지 않습니다",ex:"I disagree in part, because the other side also delays."},
  {en:"the way to A is to B",ko:"A 하는 방법은 B 하는 것이다",ex:"The way to get cheap housing later is to build now."},
  {en:"Explain A. I know the concept, but ~",ko:"A를 설명해 주세요. 개념은 아는데 ~",ex:"Explain filtering. I know the concept, but not the term."},
  {en:"predictable rather than looser",ko:"느슨한 것이 아니라 예측 가능한",ex:"Argue for predictable rules rather than looser ones."},
  {en:"approval",ko:"인허가, 승인",ex:"Approval takes four years, and that delay is a cost."},
  {en:"affordable",ko:"감당할 만한 가격의",ex:"Housing becomes affordable as it ages, not as it is built."},
  {en:"approve by right",ko:"요건 충족 시 자동 승인하다",ex:"Approve by right instead of reviewing each case."},
  {en:"an asset",ko:"자산",ex:"The residents who vote already own the asset."}
 ],
 out:[
  {q:"Explain how a slow approval process ends up in the price of a house.",hint:"approval / be added to the price / produce no income"},
  {q:"Explain a technical term to someone who knows the idea but not the word.",hint:"filtering / Explain A. I know the concept, but ~ / affordable"},
  {q:"Propose a reform that both sides of an argument could accept.",hint:"approve by right / predictable rather than looser / publicly defend"}
 ]
},
{
 id:"w4d2", day:27, cat:"미디어·주의력", level:"B2+",
 title:"The Attention You Sell",
 titleKo:"팔려 나가는 주의력 — 알고리즘과 분노의 경제학",
 names:{A:"Priya (뉴스 편집자)", B:"Sam (추천 알고리즘 담당)"},
 brief:[
  "무료로 보는 서비스에서 <b>값을 치르는 것은 돈이 아니라 시간</b>입니다. 그리고 시간을 파는 사업에서 좋은 지표는 하나뿐입니다. 사람들이 <b>얼마나 오래 머무느냐</b>입니다.",
  "여기서 기묘한 일이 벌어집니다. 오래 머물게 하는 감정과 좋은 정보를 주는 감정이 <b>같지 않기</b> 때문입니다. 분노와 불안은 사람을 붙잡아 두고, 차분한 설명은 그렇지 못합니다. 알고리즘은 그 차이를 알아서 학습합니다.",
  "누가 악의를 품은 것도 아닙니다. <b>체류 시간을 최적화하라</b>는 지시 하나가 있었을 뿐입니다. 13회차에서 본 굿하트의 법칙이 여기서 다시 나타납니다. 지표가 목표가 되는 순간 그 지표는 일을 설명하기를 그만둡니다.",
  "이 대화의 핵심은 <b>누구를 탓할 것인가</b>가 아니라 <b>무엇을 측정할 것인가</b>입니다. 「나중에 후회했는가」, 「다시 찾아왔는가」처럼 느리고 지저분한 지표를 쓰자는 제안까지 갑니다."
 ],
 lines:[
  {s:"A",en:"Our most-read article last month was also the article I am least proud of publishing.",
   ko:"지난달 가장 많이 읽힌 기사가, 제가 내보낸 것 중 가장 자랑스럽지 않은 기사였습니다.",
   notes:[{t:"most-read",k:"collocation",m:"가장 많이 읽힌",tip:"best-selling 처럼 만드는 복합 형용사입니다."}]},
  {s:"B",en:"That is not a coincidence. The system is designed to find exactly that article for you.",
   ko:"그건 우연이 아닙니다. 시스템은 정확히 그런 기사를 찾아내도록 설계되어 있습니다.",
   notes:[{t:"be designed to ~",k:"grammar",m:"~ 하도록 설계되다",tip:"의도된 기능임을 밝히는 수동 표현입니다."}]},
  {s:"A",en:"Designed by whom? Nobody in my newsroom asked for angry articles to spread faster.",
   ko:"누가 설계했습니까? 우리 편집국에서 화나게 하는 기사가 더 빨리 퍼지게 해 달라고 한 사람은 없습니다.",
   notes:[{t:"spread",k:"business",m:"퍼지다",tip:"정보나 소문이 확산되는 것입니다."}]},
  {s:"B",en:"Nobody asked. We optimized for time on page, and the system found the rest by itself.",
   ko:"아무도 요청하지 않았습니다. 우리는 체류 시간을 기준으로 최적화했고, 나머지는 시스템이 스스로 찾아냈습니다.",
   notes:[{t:"optimize for ~",k:"business",m:"~ 를 기준으로 최적화하다",tip:"무엇을 최대화할지 정하는 것입니다."},
          {t:"time on page",k:"business",m:"체류 시간",tip:"독자가 한 페이지에 머문 시간입니다."}]},
  {s:"A",en:"So the system learned that anger keeps readers on the page, which no editor would ever write down.",
   ko:"그럼 시스템이 분노가 독자를 페이지에 붙잡아 둔다는 걸 배운 거군요. 어떤 편집자도 문서로 적지 않을 사실을요.",
   notes:[{t:"keep readers on the page",k:"collocation",m:"독자를 페이지에 붙잡아 두다",tip:"이탈을 막는다는 뜻입니다."}]},
  {s:"B",en:"It learned what correlates with staying. Anger correlates strongly, and correlation is all it can see.",
   ko:"머무는 것과 무엇이 함께 움직이는지를 배웠습니다. 분노는 강하게 상관하고, 시스템이 볼 수 있는 건 상관관계뿐입니다.",
   notes:[{t:"correlate with ~",k:"business",m:"~ 와 상관관계가 있다",tip:"인과가 아니라는 점이 중요합니다."}]},
  {s:"A",en:"That is Goodhart's law in a new form, and it is the same failure we had with article quotas.",
   ko:"그건 굿하트의 법칙의 새로운 형태이고, 기사 건수 할당에서 겪은 것과 같은 실패입니다.",
   notes:[{t:"in a new form",k:"collocation",m:"새로운 형태로",tip:"같은 문제가 모습을 바꿔 나타난 것입니다."},
          {t:"a quota",k:"business",m:"할당량",tip:"숫자로 부과된 목표입니다."}]},
  {s:"B",en:"A quota is one person's decision. A model is a million small decisions that nobody reads.",
   ko:"할당은 한 사람의 결정입니다. 모델은 아무도 읽지 않는 작은 결정 백만 개입니다.",
   notes:[{t:"a model",k:"business",m:"모델, 알고리즘",tip:"데이터로 학습한 예측 장치입니다."}]},
  {s:"A",en:"That makes it harder to challenge, because there is no document anyone can point to.",
   ko:"그래서 이의를 제기하기가 더 어렵습니다. 누구도 가리킬 수 있는 문서가 없으니까요.",
   notes:[{t:"challenge",k:"business",m:"이의를 제기하다",tip:"결정이나 근거에 반론하는 것입니다."},
          {t:"point to ~",k:"phrasal",m:"~ 를 가리키다",tip:"근거로 제시하는 것입니다."}]},
  {s:"B",en:"There is a dashboard, which is worse, because everyone in the company treats it as fact.",
   ko:"대시보드가 있는데, 그게 더 나쁩니다. 회사 사람들 전부가 그걸 사실로 취급하니까요.",
   notes:[{t:"treat A as B",k:"collocation",m:"A를 B로 취급하다",tip:"해석을 고정하는 태도를 말합니다."}]},
  {s:"A",en:"Then change what the dashboard counts, because that is the only thing either of us controls.",
   ko:"그럼 대시보드가 무엇을 세는지 바꾸세요. 우리 둘이 통제할 수 있는 건 그것뿐입니다.",
   notes:[{t:"control",k:"business",m:"통제하다",tip:"영향을 미칠 수 있는 범위를 말합니다."}]},
  {s:"B",en:"Count what instead? Every honest measure is slow, and slow measures lose every budget meeting.",
   ko:"대신 무엇을 셉니까? 정직한 지표는 전부 느리고, 느린 지표는 예산 회의에서 늘 집니다.",
   notes:[{t:"an honest measure",k:"business",m:"정직한 지표",tip:"조작하기 어렵고 실제를 반영하는 지표입니다."}]},
  {s:"A",en:"Count whether the reader returned a week later, which is slow but difficult to manipulate.",
   ko:"독자가 일주일 뒤에 다시 왔는지를 세세요. 느리지만 조작하기 어렵습니다.",
   notes:[{t:"manipulate",k:"business",m:"조작하다",tip:"수치를 인위적으로 움직이는 것입니다."}]},
  {s:"B",en:"We measured that, and it barely moves, so it cannot distinguish one design from another.",
   ko:"그건 재 봤는데 거의 움직이지 않습니다. 그래서 설계안 하나와 다른 하나를 구별하지 못합니다.",
   notes:[{t:"distinguish A from B",k:"business",m:"A와 B를 구별하다",tip:"차이를 판별하는 것입니다."}]},
  {s:"A",en:"Then ask readers directly whether the time they spent was time they wanted to spend.",
   ko:"그럼 독자에게 직접 물어보세요. 쓴 시간이 본인이 쓰고 싶었던 시간이었는지를요.",
   notes:[{t:"ask someone directly",k:"collocation",m:"직접 묻다",tip:"추정하지 않고 확인하는 방식입니다."}]},
  {s:"B",en:"Surveys are unreliable, but I accept that we have never measured regret at all.",
   ko:"설문은 신뢰도가 낮습니다. 다만 우리가 후회를 한 번도 재지 않았다는 점은 인정합니다.",
   notes:[{t:"unreliable",k:"business",m:"신뢰하기 어려운",tip:"측정값이 일관되지 않는 상태입니다."},
          {t:"I accept that ~",k:"business",m:"~ 라는 점은 인정합니다",tip:"부분적 동의를 정확히 밝힙니다."}]},
  {s:"A",en:"Regret is what distinguishes an article readers needed from one that merely kept them reading.",
   ko:"후회가, 독자에게 필요했던 기사와 그저 계속 읽게 만든 기사를 가릅니다.",
   notes:[{t:"merely",k:"business",m:"그저, 단지",tip:"가치 없는 기능에 한정된다는 뉘앙스입니다."}]},
  {s:"B",en:"Stated that way, it stops being an ethical question and becomes a product question.",
   ko:"그렇게 말하면, 그건 윤리 문제이기를 멈추고 제품 문제가 됩니다.",
   notes:[{t:"Stated that way, ~",k:"business",m:"그렇게 말하면 ~",tip:"표현 방식이 바꾸는 것을 짚는 표현입니다."}]},
  {s:"A",en:"That was deliberate, because nothing changes in your organization until it becomes a metric.",
   ko:"의도한 것입니다. 그쪽 조직에서는 지표가 되기 전까지 아무것도 바뀌지 않으니까요.",
   notes:[{t:"That was deliberate.",k:"business",m:"의도한 것입니다",tip:"전략적 선택이었음을 밝히는 짧은 문장입니다."}]},
  {s:"B",en:"Then define the metric with me, and I will submit it to the review before the quarter ends.",
   ko:"그럼 그 지표를 저와 함께 정의하시죠. 분기가 끝나기 전에 제가 검토에 제출하겠습니다.",
   notes:[{t:"submit something to a review",k:"business",m:"검토에 제출하다",tip:"공식 절차에 올리는 것입니다."}]}
 ],
 keys:[
  {en:"I accept that ~",ko:"~ 라는 점은 인정합니다",ex:"I accept that we have never measured it at all."},
  {en:"Stated that way, ~",ko:"그렇게 말하면 ~",ex:"Stated that way, it becomes a product question."},
  {en:"That was deliberate.",ko:"의도한 것입니다",ex:"That was deliberate, because metrics are what move you."},
  {en:"Count whether ~",ko:"~ 인지를 세세요",ex:"Count whether the reader returned a week later."},
  {en:"optimize for ~",ko:"~ 를 기준으로 최적화하다",ex:"Whatever you optimize for is what you eventually get."},
  {en:"correlate with ~",ko:"~ 와 상관관계가 있다",ex:"Anger correlates with staying, which is not the same as helping."},
  {en:"treat A as B",ko:"A를 B로 취급하다",ex:"Everyone treats the dashboard as fact."},
  {en:"distinguish A from B",ko:"A와 B를 구별하다",ex:"The measure cannot distinguish one design from another."}
 ],
 out:[
  {q:"Explain how a system produces a result nobody chose.",hint:"optimize for ~ / correlate with ~ / be designed to ~"},
  {q:"Argue that the measurement, not the people, is what needs changing.",hint:"treat A as B / control / an honest measure"},
  {q:"Propose a slower measure and explain why it is better.",hint:"Count whether ~ / manipulate / distinguish A from B"}
 ]
},
{
 id:"w4d3", day:28, cat:"교육·평가", level:"B2+",
 title:"What a Degree Still Signals",
 titleKo:"학위는 아직 무엇을 말해 주는가 — 신호와 실력 사이",
 names:{A:"Omar (채용 담당)", B:"Lise (대학 교수)"},
 brief:[
  "학위가 값어치를 갖는 이유에 대해서는 오래된 두 가지 설명이 있습니다. 하나는 학교가 <b>실제로 능력을 키워 준다</b>는 것이고, 다른 하나는 학위가 <b>원래 가진 성질을 드러내는 신호</b>일 뿐이라는 것입니다.",
  "신호 쪽 설명은 이렇습니다. 4년을 버티고, 재미없는 과제를 마감에 맞추고, 낯선 사람들과 조를 짜서 결과를 내는 일은 <b>아무나 견디지 못합니다</b>. 그래서 학위는 배운 내용이 아니라 <b>견뎠다는 사실</b>을 증명합니다.",
  "채용하는 쪽에서 보면 이건 냉정한 이야기지만 편리한 도구이기도 합니다. 지원자 수백 명을 걸러야 할 때, 학위는 <b>싸고 빠른 필터</b>입니다. 문제는 그 필터가 <b>걸러 내는 사람</b>이 누구인지를 아무도 세지 않는다는 데 있습니다.",
  "이 대화는 어느 쪽이 옳은지를 가리는 대신, <b>그래서 무엇을 대신 볼 것인가</b>로 넘어갑니다. 과제형 평가, 수습 기간, 포트폴리오 같은 대안의 비용까지 솔직하게 다룹니다."
 ],
 lines:[
  {s:"A",en:"I screened four hundred applications last month, and the degree requirement removed most of them.",
   ko:"지난달 지원서 400건을 검토했는데, 학위 요건이 그중 대부분을 걸러 냈습니다.",
   notes:[{t:"screen applications",k:"business",m:"지원서를 선별하다",tip:"1차로 걸러 내는 절차입니다."},
          {t:"a requirement",k:"business",m:"요건",tip:"반드시 충족해야 하는 조건입니다."}]},
  {s:"B",en:"That is the part of my work I find hardest to justify, because I never agreed to filter for you.",
   ko:"그게 제 일에서 가장 정당화하기 어려운 부분입니다. 저는 그쪽을 위해 걸러 주기로 한 적이 없으니까요.",
   notes:[{t:"justify",k:"business",m:"정당화하다",tip:"근거를 대어 타당함을 보이는 것입니다."}]},
  {s:"A",en:"Nobody asked you to, but employers began using your certificate as a filter anyway.",
   ko:"아무도 요청하지 않았습니다. 다만 고용주들이 그 졸업장을 필터로 쓰기 시작했습니다.",
   notes:[{t:"use A as B",k:"collocation",m:"A를 B로 쓰다",tip:"본래 용도와 다른 쓰임을 지적합니다."}]},
  {s:"B",en:"Tell me honestly whether you think we taught them anything they use in their work.",
   ko:"솔직히 말씀해 주세요. 우리가 그들이 업무에서 쓰는 무언가를 가르쳤다고 보십니까?",
   notes:[{t:"Tell me honestly whether ~",k:"business",m:"~ 인지 솔직히 말해 주세요",tip:"솔직한 답을 요구하는 정중한 틀입니다."}]},
  {s:"A",en:"Some of it, but what I am actually buying is evidence that they completed something difficult.",
   ko:"일부는요. 다만 제가 실제로 사는 것은 그들이 어려운 일을 끝까지 마쳤다는 증거입니다.",
   notes:[{t:"what I am actually buying is ~",k:"grammar",m:"제가 실제로 사는 것은 ~ 입니다",tip:"진짜 목적을 드러내는 강조 구문입니다."},
          {t:"complete something difficult",k:"collocation",m:"어려운 일을 끝까지 마치다",tip:"완수 능력을 표현합니다."}]},
  {s:"B",en:"So the course content matters very little, and four years of persistence is the real product.",
   ko:"그럼 교육 내용은 거의 중요하지 않고, 4년의 끈기가 진짜 상품이군요.",
   notes:[{t:"persistence",k:"business",m:"끈기",tip:"어려움에도 계속하는 능력입니다."}]},
  {s:"A",en:"That is the signalling argument, and it explains more of hiring than employers usually admit.",
   ko:"그게 신호 이론입니다. 고용주들이 보통 인정하는 것보다 채용을 더 많이 설명합니다.",
   notes:[{t:"signalling",k:"business",m:"신호 기능",tip:"능력을 직접 보이지 않고 증명서로 대신하는 것입니다."}]},
  {s:"B",en:"If that is all a degree does, you are paying for a sorting process you could build more cheaply.",
   ko:"학위가 하는 일이 그것뿐이라면, 훨씬 싸게 만들 수 있는 선별 절차에 돈을 내고 계신 겁니다.",
   notes:[{t:"a sorting process",k:"business",m:"선별 절차",tip:"사람을 나누는 과정입니다."}]},
  {s:"A",en:"Cheaper for whom? Every alternative I have tried moved the cost onto my own team.",
   ko:"누구에게 더 쌉니까? 제가 시도한 모든 대안은 비용을 우리 팀으로 옮겨 놓았습니다.",
   notes:[{t:"Cheaper for whom?",k:"business",m:"누구에게 더 쌉니까",tip:"비용이 사라진 게 아니라 이동했음을 지적합니다."}]},
  {s:"B",en:"Which alternatives? I want to know what you actually tested, not what the research recommends.",
   ko:"어떤 대안들입니까? 연구가 권하는 것이 아니라 실제로 시험해 보신 것을 알고 싶습니다.",
   notes:[{t:"test an alternative",k:"business",m:"대안을 시험해 보다",tip:"실제로 운영해 보는 것입니다."}]},
  {s:"A",en:"Work samples. They predict performance much better, and each one takes three hours to assess.",
   ko:"실무 과제입니다. 성과 예측력은 훨씬 좋은데, 하나를 평가하는 데 세 시간이 걸립니다.",
   notes:[{t:"a work sample",k:"business",m:"실무 과제형 평가",tip:"실제 업무와 비슷한 과제를 주고 결과를 보는 방식입니다."},
          {t:"assess",k:"business",m:"평가하다",tip:"기준에 따라 판정하는 것입니다."}]},
  {s:"B",en:"Three hours multiplied by four hundred is a number no hiring manager will approve.",
   ko:"세 시간 곱하기 400은 어떤 채용 책임자도 승인하지 않을 숫자입니다.",
   notes:[{t:"multiplied by ~",k:"business",m:"~ 를 곱한",tip:"계산을 말로 표현하는 방식입니다."}]},
  {s:"A",en:"That is why the degree requirement continues, and not because anyone believes it is precise.",
   ko:"그래서 학위 요건이 계속되는 겁니다. 누가 그것을 정밀하다고 믿어서가 아니고요.",
   notes:[{t:"continue",k:"business",m:"계속되다, 유지되다",tip:"제도가 존속하는 것입니다."}]},
  {s:"B",en:"Then at least count the people your filter removes, because that number never appears in your report.",
   ko:"그럼 최소한 그 필터가 걸러 내는 사람 수는 세세요. 그 숫자는 보고서에 절대 나오지 않으니까요.",
   notes:[{t:"count the people ~",k:"grammar",m:"~ 하는 사람 수를 세다",tip:"보이지 않는 비용을 측정하라는 요구입니다."}]},
  {s:"A",en:"We do not collect that data, which is a weak answer and I am aware of it.",
   ko:"그 데이터를 수집하지 않습니다. 형편없는 답이라는 건 저도 압니다.",
   notes:[{t:"collect data",k:"business",m:"데이터를 수집하다",tip:"측정의 전제 조건입니다."},
          {t:"a weak answer",k:"business",m:"설득력 없는 답",tip:"자기 논리의 약점을 스스로 인정하는 표현입니다."}]},
  {s:"B",en:"Then run one round without the requirement and compare the candidates you would have rejected.",
   ko:"그럼 한 번은 그 요건 없이 진행하고, 원래대로면 탈락시켰을 지원자들을 비교해 보세요.",
   notes:[{t:"reject a candidate",k:"business",m:"지원자를 탈락시키다",tip:"채용 절차의 표준 용어입니다."}]},
  {s:"A",en:"That is testable, and it costs less than the argument we have been repeating for years.",
   ko:"그건 시험해 볼 수 있고, 우리가 몇 년째 되풀이한 논쟁보다 비용이 적습니다.",
   notes:[{t:"testable",k:"business",m:"시험해 볼 수 있는",tip:"주장을 검증 가능한 형태로 바꾸는 단어입니다."}]},
  {s:"B",en:"And if the requirement proves correct, you will have evidence instead of tradition.",
   ko:"그리고 그 요건이 옳은 것으로 입증되면, 관행이 아니라 증거를 갖게 되실 겁니다.",
   notes:[{t:"prove correct",k:"business",m:"옳은 것으로 입증되다",tip:"검증 결과를 말합니다."},
          {t:"evidence instead of tradition",k:"collocation",m:"관행이 아니라 증거",tip:"근거의 종류를 대비합니다."}]},
  {s:"A",en:"That is what I want, because at present I am defending a habit rather than a finding.",
   ko:"제가 원하는 게 그겁니다. 지금은 발견이 아니라 습관을 방어하고 있으니까요.",
   notes:[{t:"at present",k:"collocation",m:"현재로서는",tip:"현재 상태를 격식 있게 표현합니다."}]},
  {s:"B",en:"Then run it this hiring cycle, and I will send you the students your filter would reject.",
   ko:"그럼 이번 채용에서 시행해 보세요. 그 필터가 탈락시킬 학생들은 제가 보내 드리겠습니다.",
   notes:[{t:"a hiring cycle",k:"business",m:"채용 회차",tip:"정기적으로 반복되는 채용 기간입니다."}]}
 ],
 keys:[
  {en:"Cheaper for whom?",ko:"누구에게 더 쌉니까",ex:"Cheaper for whom? The cost moved, it did not disappear."},
  {en:"what I am actually buying is ~",ko:"제가 실제로 사는 것은 ~ 입니다",ex:"What I am actually buying is evidence of persistence."},
  {en:"Tell me honestly whether ~",ko:"~ 인지 솔직히 말해 주세요",ex:"Tell me honestly whether the course taught them anything."},
  {en:"evidence instead of tradition",ko:"관행이 아니라 증거",ex:"Then you would have evidence instead of tradition."},
  {en:"screen applications",ko:"지원서를 선별하다",ex:"We screened four hundred applications in one week."},
  {en:"signalling",ko:"신호 기능",ex:"Signalling explains more of hiring than employers admit."},
  {en:"a work sample",ko:"실무 과제형 평가",ex:"Work samples predict performance far better than a transcript."},
  {en:"testable",ko:"시험해 볼 수 있는",ex:"That is testable, and cheaper than arguing about it."}
 ],
 out:[
  {q:"Explain what an employer is really paying for when they require a degree.",hint:"what I am actually buying is ~ / signalling / persistence"},
  {q:"Point out that a cheap solution has moved its cost rather than removed it.",hint:"Cheaper for whom? / a work sample / assess"},
  {q:"Propose an experiment that would settle a long-running argument.",hint:"testable / reject a candidate / evidence instead of tradition"}
 ]
},
{
 id:"w4d4", day:29, cat:"건강·의료", level:"B2+",
 title:"The Test That Finds Too Much",
 titleKo:"너무 많이 찾아내는 검사 — 과잉진단의 역설",
 names:{A:"Jinho (환자, 종합검진 애호가)", B:"Dr. Wen (내과의)"},
 brief:[
  "검사는 많이 할수록 좋다는 생각은 자연스럽습니다. 일찍 찾으면 일찍 고칠 수 있으니까요. 그런데 의학에서 오래 논쟁이 되어 온 사실이 하나 있습니다. <b>찾아낸 것이 전부 병은 아니라는 것</b>입니다.",
  "몸에는 평생 아무 해도 끼치지 않고 지나갈 이상 소견이 적지 않습니다. 검사를 촘촘히 하면 그것들이 걸려 나옵니다. 여기서 <b>과잉진단(overdiagnosis)</b>이 생깁니다. 병을 찾아낸 것이 아니라, <b>병이 되지 않았을 것</b>을 찾아낸 상태입니다.",
  "문제는 찾아낸 뒤입니다. 추가 검사, 조직 검사, 때로는 수술이 이어지고, 각 단계마다 작지만 실재하는 위험이 붙습니다. 그리고 <b>통계는 좋아 보입니다</b>. 해롭지 않았을 사례가 생존자 숫자에 더해지기 때문입니다.",
  "이 대화는 「검사를 하지 말라」는 이야기가 아닙니다. <b>이 검사가 내 결정을 바꾸는가</b>라는 질문을 배우는 자리입니다. 의사와 환자가 쓰는 표현이 함께 나오니, 실제 진료실에서 그대로 써 보실 수 있습니다."
 ],
 lines:[
  {s:"A",en:"I paid for the full scan package this year, and it found three things that need monitoring.",
   ko:"올해 전신 검사 패키지를 받았는데, 경과를 지켜봐야 할 게 세 가지 나왔습니다.",
   notes:[{t:"need monitoring",k:"collocation",m:"경과 관찰이 필요하다",tip:"즉시 치료하지 않고 지켜본다는 뜻입니다."}]},
  {s:"B",en:"Who decided they need monitoring? That phrase carries a great deal of weight in a report.",
   ko:"누가 경과 관찰이 필요하다고 판단했습니까? 그 표현은 판독지에서 아주 많은 것을 떠안습니다.",
   notes:[{t:"carry weight",k:"business",m:"무게를 지니다, 영향력이 있다",tip:"한 표현이 판단을 대신하고 있다는 지적입니다."}]},
  {s:"A",en:"The radiologist, I assume. Is finding problems early not the purpose of screening?",
   ko:"영상의학과 의사겠죠. 문제를 일찍 찾는 게 검진의 목적 아닙니까?",
   notes:[{t:"screening",k:"business",m:"선별 검사, 검진",tip:"증상이 없는 사람을 대상으로 한다는 점이 핵심입니다."}]},
  {s:"B",en:"Only when finding it early changes the treatment, and for many findings it does not.",
   ko:"일찍 찾는 것이 치료를 바꿀 때만 그렇습니다. 많은 소견에서는 바뀌지 않습니다.",
   notes:[{t:"change the treatment",k:"business",m:"치료 방침을 바꾸다",tip:"검사의 가치를 재는 실용적 기준입니다."}]},
  {s:"A",en:"That is an argument for knowing less, which is difficult to accept as a patient.",
   ko:"그건 덜 알자는 주장인데, 환자로서는 받아들이기 어렵습니다.",
   notes:[{t:"an argument for ~",k:"business",m:"~ 를 지지하는 논거",tip:"an argument against ~ 와 짝입니다."}]},
  {s:"B",en:"I understand. But some of what we detect would never have caused you any symptoms.",
   ko:"이해합니다. 다만 우리가 발견하는 것 중 일부는 평생 어떤 증상도 일으키지 않았을 것들입니다.",
   notes:[{t:"detect",k:"business",m:"발견하다, 검출하다",tip:"검사로 찾아내는 것입니다."},
          {t:"cause symptoms",k:"collocation",m:"증상을 일으키다",tip:"질병이 실제로 문제를 만드는 것입니다."}]},
  {s:"A",en:"How can anyone know that, when we treat these findings before they develop?",
   ko:"그걸 어떻게 압니까? 이런 소견은 발전하기 전에 치료해 버리는데요.",
   notes:[{t:"develop",k:"business",m:"진행되다, 발전하다",tip:"병이 심해지는 과정입니다."}]},
  {s:"B",en:"That is the genuine difficulty, and it is why the evidence comes from populations, not individuals.",
   ko:"그게 진짜 어려운 점이고, 그래서 근거가 개인이 아니라 집단에서 나옵니다.",
   notes:[{t:"a population",k:"business",m:"모집단, 집단",tip:"통계적 근거의 단위입니다."}]},
  {s:"A",en:"So you compare two groups and check whether the screened group lives longer overall.",
   ko:"그럼 두 집단을 비교해서 검진받은 집단이 전체적으로 더 오래 사는지 확인하는 거군요.",
   notes:[{t:"overall",k:"business",m:"전체적으로",tip:"개별이 아니라 총합 기준을 말합니다."}]},
  {s:"B",en:"Correct, and survival rates alone are misleading, because earlier detection improves them automatically.",
   ko:"맞습니다. 그리고 생존율만으로는 오해를 부릅니다. 일찍 발견하는 것만으로 생존율이 자동으로 좋아지니까요.",
   notes:[{t:"a survival rate",k:"business",m:"생존율",tip:"진단 후 일정 기간 생존한 비율입니다."},
          {t:"misleading",k:"business",m:"오해를 부르는",tip:"거짓은 아니지만 잘못된 인상을 주는 것입니다."}]},
  {s:"A",en:"Because the measurement begins earlier, so the patient appears to survive longer without living longer.",
   ko:"측정이 더 일찍 시작되니까, 더 오래 살지 않았는데도 더 오래 생존한 것처럼 보이는군요.",
   notes:[{t:"the measurement begins",k:"collocation",m:"측정이 시작되다",tip:"기준 시점이 결과를 바꾸는 문제입니다."}]},
  {s:"B",en:"That is exactly right, and that single confusion has produced decades of confident advice.",
   ko:"정확합니다. 그 혼동 하나가 수십 년간의 자신만만한 조언을 만들어 냈습니다.",
   notes:[{t:"That is exactly right.",k:"business",m:"정확합니다",tip:"상대 이해가 맞다고 확인하는 표현입니다."}]},
  {s:"A",en:"What should I ask before I agree to the next test on the recommended list?",
   ko:"권장 목록의 다음 검사에 동의하기 전에 무엇을 물어야 합니까?",
   notes:[{t:"agree to ~",k:"collocation",m:"~ 에 동의하다",tip:"agree with(의견 동의)와 구별됩니다."}]},
  {s:"B",en:"Ask what we would do differently depending on the result, and require an answer for both outcomes.",
   ko:"결과에 따라 무엇을 달리하게 되는지 묻고, 두 결과 모두에 대한 답을 요구하세요.",
   notes:[{t:"do differently",k:"collocation",m:"달리 조치하다",tip:"의사결정의 핵심 질문입니다."},
          {t:"both outcomes",k:"collocation",m:"두 결과 모두",tip:"양성과 음성 각각을 뜻합니다."}]},
  {s:"A",en:"And if the answer is identical for both outcomes, the test only provides reassurance.",
   ko:"두 결과의 답이 같다면, 그 검사는 안심만 제공하는 거군요.",
   notes:[{t:"provide reassurance",k:"collocation",m:"안심을 제공하다",tip:"의학적 실익과 구별되는 심리적 효과입니다."}]},
  {s:"B",en:"Reassurance has genuine value, so I would not dismiss it, but it should be priced honestly.",
   ko:"안심에는 실제 가치가 있으니 무시하지는 않겠습니다. 다만 정직하게 값을 매겨야 합니다.",
   notes:[{t:"dismiss",k:"business",m:"일축하다",tip:"고려할 가치가 없다고 물리치는 것입니다."}]},
  {s:"A",en:"Priced in what terms? The invoice shows a figure, and it says nothing about risk.",
   ko:"무엇으로 값을 매깁니까? 청구서에는 금액이 있지만 위험에 대해서는 아무 말이 없습니다.",
   notes:[{t:"in what terms",k:"business",m:"무엇을 단위로",tip:"측정 기준을 묻는 표현입니다."}]},
  {s:"B",en:"In unnecessary biopsies, and in a year spent worrying about something that would never have grown.",
   ko:"불필요한 조직 검사로, 그리고 자라지도 않았을 것을 걱정하며 보낸 1년으로요.",
   notes:[{t:"unnecessary",k:"business",m:"불필요한",tip:"의학적 필요가 없었던 처치입니다."},
          {t:"a biopsy",k:"business",m:"조직 검사",tip:"조직을 떼어 검사하는 시술입니다."}]},
  {s:"A",en:"Stated that way, I would prefer fewer tests and better questions at my next appointment.",
   ko:"그렇게 말씀하시니, 다음 진료에서는 검사를 줄이고 질문을 늘리는 편이 낫겠습니다.",
   notes:[{t:"an appointment",k:"business",m:"예약된 진료",tip:"병원 방문 일정입니다."}]},
  {s:"B",en:"That is the right exchange, and it is what a fifteen-minute consultation can actually deliver.",
   ko:"그게 맞는 교환이고, 15분 진료가 실제로 제공할 수 있는 것입니다.",
   notes:[{t:"a consultation",k:"business",m:"상담, 진료",tip:"의사와 환자가 대화하는 시간입니다."},
          {t:"deliver",k:"business",m:"제공하다, 실현하다",tip:"약속한 것을 실제로 내놓는 것입니다."}]}
 ],
 keys:[
  {en:"Who decided ~ ?",ko:"누가 ~ 를 판단했습니까",ex:"Who decided they need monitoring, and on what basis?"},
  {en:"do differently",ko:"달리 조치하다",ex:"Ask what we would do differently depending on the result."},
  {en:"in what terms",ko:"무엇을 단위로",ex:"Priced in what terms? The invoice says nothing about risk."},
  {en:"That is exactly right.",ko:"정확합니다",ex:"That is exactly right, and it explains the whole confusion."},
  {en:"screening",ko:"선별 검사, 검진",ex:"Screening only helps when it changes the treatment."},
  {en:"misleading",ko:"오해를 부르는",ex:"Survival rates alone are misleading."},
  {en:"a survival rate",ko:"생존율",ex:"A survival rate improves automatically with earlier detection."},
  {en:"provide reassurance",ko:"안심을 제공하다",ex:"If nothing changes, the test only provides reassurance."}
 ],
 out:[
  {q:"Explain why more testing does not always produce better health.",hint:"screening / change the treatment / detect"},
  {q:"Explain why a statistic can improve without anyone being better off.",hint:"a survival rate / misleading / the measurement begins"},
  {q:"Say what you would ask a professional before agreeing to something optional.",hint:"Who decided ~ ? / do differently / in what terms"}
 ]
},
{
 id:"w4d5", day:30, cat:"식품·농업", level:"B2+",
 title:"The Cheapest Calorie",
 titleKo:"가장 싼 칼로리 — 값싼 식탁의 진짜 계산서",
 names:{A:"Marta (농업경제학자)", B:"Dev (식품회사 구매 총괄)"},
 brief:[
  "지난 백 년 동안 식량 정책의 목표는 하나였습니다. <b>칼로리를 싸게 만드는 것</b>입니다. 굶주림이 실재하던 시대에 이것은 훌륭한 목표였고, 실제로 성공했습니다. 곡물과 기름과 설탕은 인류 역사상 가장 싸졌습니다.",
  "그런데 값이 싸진 것은 <b>모든 칼로리가 아니라 특정한 칼로리</b>였습니다. 오래 보관되고, 멀리 운반되고, 기계로 수확되는 것들입니다. 신선한 채소와 생선은 그 혜택을 훨씬 덜 받았습니다. 가격 구조가 식탁의 모양을 바꿔 놓았습니다.",
  "여기서 <b>외부비용</b>이 등장합니다. 값싼 칼로리의 진짜 비용 중 일부는 식료품 가격표에 찍히지 않고, 훨씬 나중에 <b>의료비와 토양과 물</b>로 청구됩니다. 청구서가 다른 부서로 가는 셈입니다.",
  "이 대화는 「가공식품은 나쁘다」는 도덕론으로 가지 않습니다. <b>왜 그 가격이 그렇게 형성되었는가</b>를 따라가고, 세금·보조금·표시제 같은 수단의 한계까지 솔직하게 다룹니다."
 ],
 lines:[
  {s:"A",en:"Food policy spent a century reducing the price of calories, and by that measure it succeeded completely.",
   ko:"식량 정책은 한 세기 동안 칼로리 가격을 낮추는 데 매달렸고, 그 기준으로는 완전히 성공했습니다.",
   notes:[{t:"by that measure",k:"business",m:"그 기준으로 보면",tip:"성공의 잣대를 명시하는 표현입니다."}]},
  {s:"B",en:"And now the same result is described as a public health failure, which seems unfair to me.",
   ko:"그리고 이제 그 결과가 공중보건의 실패로 묘사되는데, 제게는 부당해 보입니다.",
   notes:[{t:"be described as ~",k:"business",m:"~ 로 묘사되다",tip:"평가가 달라진 것을 표현합니다."}]},
  {s:"A",en:"Not unfair, only incomplete, because cheap calories and cheap nutrition were never the same objective.",
   ko:"부당한 게 아니라 불완전한 겁니다. 싼 칼로리와 싼 영양은 애초에 같은 목표가 아니었으니까요.",
   notes:[{t:"Not A, only B",k:"grammar",m:"A가 아니라 B일 뿐",tip:"상대 표현을 부드럽게 교정하는 틀입니다."},
          {t:"an objective",k:"business",m:"목표",tip:"달성하려는 결과입니다."}]},
  {s:"B",en:"Explain that, because in my work a calorie is a calorie and the cost sheet does not distinguish them.",
   ko:"설명해 주세요. 제 일에서 칼로리는 칼로리이고, 원가표는 그것들을 구별하지 않습니다.",
   notes:[{t:"a cost sheet",k:"business",m:"원가표",tip:"품목별 비용을 정리한 표입니다."}]},
  {s:"A",en:"What became cheap was whatever stores well, transports far, and can be harvested by machine.",
   ko:"싸진 것은 보관성이 좋고, 멀리 운반되고, 기계로 수확할 수 있는 것들이었습니다.",
   notes:[{t:"store well",k:"collocation",m:"보관성이 좋다",tip:"오래 두어도 상하지 않는 성질입니다."},
          {t:"harvest",k:"business",m:"수확하다",tip:"농작물을 거두어들이는 것입니다."}]},
  {s:"B",en:"Grain, oil and sugar, which are the three commodities we purchase in bulk.",
   ko:"곡물, 기름, 설탕이군요. 우리가 대량으로 구매하는 세 가지 원자재입니다.",
   notes:[{t:"a commodity",k:"business",m:"원자재, 범용 상품",tip:"품질 차이가 작아 가격으로 경쟁하는 품목입니다."},
          {t:"in bulk",k:"collocation",m:"대량으로",tip:"낱개가 아니라 큰 단위로 사는 것입니다."}]},
  {s:"A",en:"Correct, and nothing equivalent happened to fresh vegetables or to fish that requires refrigeration.",
   ko:"맞습니다. 그리고 신선 채소나 냉장이 필요한 생선에는 그에 상응하는 일이 없었습니다.",
   notes:[{t:"require refrigeration",k:"collocation",m:"냉장이 필요하다",tip:"보관 조건을 명시합니다."}]},
  {s:"B",en:"The cold chain is expensive. Every hour of it adds cost that the customer will not pay for.",
   ko:"냉장 유통망은 비쌉니다. 그 한 시간 한 시간이 비용을 더하는데, 고객은 그 값을 치르려 하지 않습니다.",
   notes:[{t:"the cold chain",k:"business",m:"냉장 유통망",tip:"저온을 유지하며 운송·보관하는 체계입니다."}]},
  {s:"A",en:"So the shelf price reflects handling cost rather than nutritional value, and shoppers read it as both.",
   ko:"그럼 진열대 가격은 영양 가치가 아니라 취급 비용을 반영하는데, 소비자는 그것을 둘 다로 읽습니다.",
   notes:[{t:"the shelf price",k:"business",m:"소비자가, 진열대 가격",tip:"매장에서 소비자가 보는 가격입니다."},
          {t:"nutritional value",k:"business",m:"영양 가치",tip:"식품이 제공하는 영양의 양과 질입니다."}]},
  {s:"B",en:"I disagree there, because many shoppers understand this clearly and still buy the cheaper product.",
   ko:"그 부분은 동의하지 않습니다. 많은 소비자가 이걸 분명히 이해하면서도 더 싼 제품을 삽니다.",
   notes:[{t:"understand clearly",k:"collocation",m:"분명히 이해하다",tip:"정보 부족이 원인이 아님을 지적합니다."}]},
  {s:"A",en:"That is fair, and I would not claim people are uninformed, because the budget decides most purchases.",
   ko:"타당합니다. 사람들이 정보가 없다고 주장하지는 않겠습니다. 대부분의 구매는 예산이 결정하니까요.",
   notes:[{t:"uninformed",k:"business",m:"정보가 부족한",tip:"무지하다는 뜻의 완곡한 표현입니다."}]},
  {s:"B",en:"Then what is your actual conclusion, if it is not about blaming a particular group?",
   ko:"그럼 실제 결론은 무엇입니까? 특정 집단을 탓하는 게 아니라면요.",
   notes:[{t:"What is your actual conclusion?",k:"business",m:"실제 결론이 무엇입니까",tip:"논지의 착지점을 요구하는 질문입니다."}]},
  {s:"A",en:"The costs that never appear in the price appear later as medical spending, soil damage and water use.",
   ko:"가격에 나타나지 않는 비용은 나중에 의료비와 토양 훼손과 물 사용으로 나타납니다.",
   notes:[{t:"medical spending",k:"business",m:"의료 지출",tip:"건강 문제에 드는 사회적 비용입니다."}]},
  {s:"B",en:"Externalities, then. I know the term, but I have never seen one appear on my own budget.",
   ko:"외부비용이군요. 용어는 압니다만, 제 예산에 그게 나타난 걸 본 적은 없습니다.",
   notes:[{t:"an externality",k:"business",m:"외부비용, 외부효과",tip:"거래 당사자가 아닌 제3자가 부담하는 비용입니다."}]},
  {s:"A",en:"That is the problem exactly, because the cost is charged to a department that was never in the discussion.",
   ko:"문제가 바로 그것입니다. 그 비용은 논의에 없던 부서에 청구되니까요.",
   notes:[{t:"be charged to ~",k:"business",m:"~ 에게 청구되다",tip:"비용의 귀착처를 말합니다."}]},
  {s:"B",en:"Then tax it and state that openly, rather than criticizing consumers for what they buy.",
   ko:"그럼 세금을 매기고 공개적으로 그렇게 말하세요. 소비자가 무엇을 사는지 비판하는 대신에요.",
   notes:[{t:"state something openly",k:"collocation",m:"공개적으로 밝히다",tip:"숨기지 않고 말하는 것입니다."},
          {t:"criticize someone for ~",k:"collocation",m:"~ 에 대해 비판하다",tip:"전치사 for 가 고정입니다."}]},
  {s:"A",en:"A tax on one ingredient is avoided within a year, because changing the recipe is cheaper than changing the policy.",
   ko:"단일 성분에 매긴 세금은 1년이면 회피됩니다. 배합을 바꾸는 게 정책을 바꾸는 것보다 싸니까요.",
   notes:[{t:"be avoided",k:"business",m:"회피되다",tip:"규제를 우회하는 것입니다."},
          {t:"change the recipe",k:"business",m:"배합을 바꾸다",tip:"규제를 피해 제품 성분을 조정하는 것입니다."}]},
  {s:"B",en:"Then what would you do instead, given that every tool on that list has been tried somewhere?",
   ko:"그럼 대신 무엇을 하시겠습니까? 그 목록의 모든 수단은 어디선가 시도된 적이 있는데요.",
   notes:[{t:"given that ~",k:"grammar",m:"~ 임을 감안하면",tip:"반론의 전제를 먼저 인정하는 접속 표현입니다."}]},
  {s:"A",en:"Move the subsidy rather than add a tax, because what we pay farmers to grow determines everything after that.",
   ko:"세금을 더하지 말고 보조금을 옮기세요. 농가에 무엇을 기르라고 지급하느냐가 그 뒤의 모든 것을 결정합니다.",
   notes:[{t:"a subsidy",k:"business",m:"보조금",tip:"정부가 특정 활동을 장려하기 위해 주는 돈입니다."},
          {t:"determine",k:"business",m:"결정하다",tip:"인과 관계를 강조하는 동사입니다."}]},
  {s:"B",en:"That I could defend to my board, because it changes my input costs rather than my product label.",
   ko:"그건 이사회에 설명할 수 있습니다. 제품 표시가 아니라 투입 원가를 바꾸는 얘기니까요.",
   notes:[{t:"input costs",k:"business",m:"투입 원가",tip:"원재료와 자재에 드는 비용입니다."},
          {t:"a product label",k:"business",m:"제품 표시",tip:"포장에 적히는 성분과 영양 정보입니다."}]}
 ],
 keys:[
  {en:"by that measure",ko:"그 기준으로 보면",ex:"By that measure the policy succeeded completely."},
  {en:"Not A, only B",ko:"A가 아니라 B일 뿐",ex:"Not unfair, only incomplete."},
  {en:"What is your actual conclusion?",ko:"실제 결론이 무엇입니까",ex:"What is your actual conclusion, if not blame?"},
  {en:"given that ~",ko:"~ 임을 감안하면",ex:"Given that every tool has been tried, what would you do?"},
  {en:"the cold chain",ko:"냉장 유통망",ex:"The cold chain adds cost the customer will not pay for."},
  {en:"an externality",ko:"외부비용",ex:"An externality is a cost charged to someone outside the deal."},
  {en:"a subsidy",ko:"보조금",ex:"Move the subsidy rather than add a tax."},
  {en:"input costs",ko:"투입 원가",ex:"It changes my input costs rather than my label."}
 ],
 out:[
  {q:"Explain why making food cheap and making food healthy are different projects.",hint:"by that measure / an objective / Not A, only B"},
  {q:"Explain externalities using a concrete example from your own industry.",hint:"an externality / be charged to ~ / medical spending"},
  {q:"Recommend one policy and say honestly where it would fail.",hint:"be avoided / given that ~ / a subsidy"}
 ]
}
