{
 id:"w3d1", day:16, cat:"투자·시장", level:"B2+",
 title:"Why Cheap Stays Cheap",
 titleKo:"싼 주식은 왜 계속 싼가 — 저평가와 밸류 트랩",
 names:{A:"Mina (리서치)", B:"Dohyun (개인 투자자)"},
 brief:[
  "주식이 싸다는 말은 대개 <b>이익 대비 값</b>이 낮다는 뜻입니다. 그것을 재는 가장 흔한 잣대가 주가수익비율(PER)이고, 영어로는 <b>trade at X times earnings</b>라고 말합니다. 「PER이 4배다」가 아니라 「이익의 네 배에 거래된다」고 표현하는 것이 자연스럽습니다.",
  "문제는 싼 데는 대개 이유가 있다는 점입니다. 시장이 그 회사의 이익을 <b>지속되지 않을 이익</b>으로 보거나, 지배구조·배당·업황 주기를 할인 요인으로 잡고 있을 수 있습니다. 싸 보이지만 계속 싼 채로 머무는 주식을 <b>value trap(밸류 트랩)</b>이라 부릅니다.",
  "그래서 던져야 할 질문은 「싼가」가 아니라 <b>What's driving the price?(무엇이 주가를 움직이는가)</b>입니다. 할인의 이유가 사라질 수 있는 것인지, 구조적으로 남는 것인지에 따라 답이 갈립니다.",
  "손실을 말하는 영어도 정해져 있습니다. <b>I'm down forty percent</b>가 가장 자연스럽고, 평가손실을 안고 있다는 뜻으로 <b>sitting on a loss</b>를 씁니다. 팔지 않고 계속 들고 가겠다는 말은 <b>hold on to</b>입니다."
 ],
 lines:[
  {s:"A",en:"You've been sitting on this loss for a while now, so how far down are you at this point?",
   ko:"이 손실을 한참 안고 계셨는데, 지금은 얼마나 내려와 있습니까?",
   notes:[{t:"sit on a loss",k:"idiom",m:"(팔지 않고) 포지션을 안고 있다",tip:"sit on cash / sit on a loss처럼 「쥐고 안 움직인다」는 뜻입니다."},
          {t:"How far down are you?",k:"colloquial",m:"얼마나 손실이신가요",tip:"투자 대화에서 손실 폭을 묻는 가장 자연스러운 형태입니다."}]},
  {s:"B",en:"I'm down about forty percent, and honestly, I stopped opening the app for a couple of months.",
   ko:"40퍼센트쯤 내려와 있고, 솔직히 두어 달은 앱을 아예 안 열었습니다.",
   notes:[{t:"I'm down forty percent.",k:"idiom",m:"40퍼센트 손실입니다",tip:"반대는 I'm up twenty percent. 투자 영어의 기본 문장입니다."},
          {t:"Honestly, ~",k:"colloquial",m:"솔직히 말해서",tip:"문장 앞에 붙여 개인적인 고백을 부드럽게 만듭니다."}]},
  {s:"A",en:"That's painful. What's the case for holding on to it from where it stands today?",
   ko:"괴로우셨겠네요. 오늘 이 자리에서 계속 들고 갈 근거는 뭡니까?",
   notes:[{t:"hold on to ~",k:"phrasal",m:"~을 팔지 않고 계속 보유하다",tip:"hold보다 「놓지 않는다」는 의지가 담깁니다."},
          {t:"one's case for ~",k:"business",m:"~을 주장하는 근거",tip:"What's your case for it? = 그렇게 보는 근거가 뭡니까."}]},
  {s:"B",en:"It trades at four times earnings, while the American peer that does the same thing trades at thirteen.",
   ko:"이건 이익의 네 배에 거래되는데, 같은 일을 하는 미국 동종 기업은 열세 배에 거래됩니다.",
   notes:[{t:"trade at X times earnings",k:"business",m:"이익의 X배에 거래되다",tip:"PER을 말하는 표준 영어입니다. 「PER 4배」를 그대로 옮기지 마세요."},
          {t:"a peer",k:"business",m:"동종 업계의 비교 대상 기업",tip:"peer group / peer comparison으로 자주 씁니다."}]},
  {s:"A",en:"So on that one number it looks cheap, but cheap on its own has never been a thesis.",
   ko:"그 숫자 하나만 보면 싸 보이죠. 그런데 싸다는 것만으로 투자 논리가 된 적은 없습니다.",
   notes:[{t:"a thesis",k:"business",m:"투자 논거, 왜 사는지에 대한 설명",tip:"investment thesis의 줄임입니다. 근거 없는 매수를 지적할 때 씁니다."}]},
  {s:"B",en:"Why not? If the earnings are real, surely the gap between the two has to close eventually.",
   ko:"왜 안 되죠? 이익이 진짜라면 두 회사 사이의 격차는 결국 좁혀져야 하는 거 아닙니까?",
   notes:[{t:"close the gap",k:"collocation",m:"격차를 좁히다",tip:"The gap closed / The gap widened. 밸류에이션 대화의 단골입니다."}]},
  {s:"A",en:"Only if the market agrees those earnings will last, and right now it may be pricing in the cycle.",
   ko:"그 이익이 지속된다고 시장이 동의할 때만요. 지금은 시장이 경기 사이클을 가격에 반영하고 있을 수도 있습니다.",
   notes:[{t:"price in ~",k:"phrasal",m:"~을 미리 값에 반영하다",tip:"The market has priced in a rate cut. 투자 영어의 필수 구동사입니다."}]},
  {s:"B",en:"You mean the earnings I'm looking at are sitting near the top of the cycle right now.",
   ko:"제가 보고 있는 이익이 지금 사이클의 꼭대기 근처에 있다는 말씀이군요.",
   notes:[{t:"~, you mean",k:"grammar",m:"그러니까 ~라는 말씀이군요",tip:"상대 표현을 더 정확한 말로 바꿔 되받는 형태입니다."}]},
  {s:"A",en:"That's one reading. Cyclical earnings look cheapest at exactly the moment they're about to fall.",
   ko:"그렇게 읽을 수 있죠. 경기민감주의 이익은 하필 떨어지기 직전에 가장 싸 보입니다.",
   notes:[{t:"cyclical",k:"business",m:"경기·업황 주기를 타는",tip:"cyclical stocks / a cyclical business. defensive의 반대편입니다."},
          {t:"That's one reading.",k:"colloquial",m:"그건 하나의 해석입니다",tip:"단정하지 않고 다른 해석의 여지를 남기는 말입니다."}]},
  {s:"B",en:"Fair enough, but the discount has been sitting there for years, through several complete cycles.",
   ko:"일리 있어요. 그래도 그 할인은 몇 번의 완전한 사이클을 거치는 동안 몇 년째 그대로 있었습니다.",
   notes:[{t:"a discount",k:"business",m:"(다른 자산 대비) 값이 낮게 매겨진 상태",tip:"trade at a discount to peers. 반대는 at a premium입니다."}]},
  {s:"A",en:"Then it isn't about the cycle at all, and something structural is keeping the price down.",
   ko:"그럼 사이클 문제는 아예 아니고, 구조적인 무언가가 주가를 눌러 두고 있는 겁니다.",
   notes:[{t:"structural",k:"business",m:"구조적인 — 쉽게 사라지지 않는",tip:"a structural discount / a structural problem. 일시적(temporary)의 반대입니다."}]},
  {s:"B",en:"Such as? Governance, dividends, or just the fact that nobody bothers to cover these names?",
   ko:"예를 들면요? 지배구조, 배당, 아니면 그냥 아무도 이런 종목을 분석해 주지 않는다는 사실?",
   notes:[{t:"Such as?",k:"colloquial",m:"예를 들면요?",tip:"상대에게 구체적인 예를 요구하는 한 단어짜리 되물음입니다."},
          {t:"cover a name",k:"business",m:"(애널리스트가) 그 종목을 분석해 다루다",tip:"a name은 업계에서 「종목」을 뜻하는 말입니다."}]},
  {s:"A",en:"Any of those, and that's exactly what makes it a value trap rather than a bargain.",
   ko:"그중 무엇이든요. 그리고 그게 이걸 저가 매수 기회가 아니라 가치 함정으로 만드는 지점입니다.",
   notes:[{t:"a value trap",k:"business",m:"싸 보이지만 계속 싼 채로 머무는 주식",tip:"a bargain(진짜 싼 물건)과 대비해 씁니다."},
          {t:"A rather than B",k:"grammar",m:"B라기보다 A인",tip:"두 해석을 가르는 비교입니다. 짧고 또렷하게 들립니다."}]},
  {s:"B",en:"So how would I tell the two apart before I put any more money into it?",
   ko:"그럼 돈을 더 넣기 전에 그 둘을 어떻게 구별하죠?",
   notes:[{t:"tell A and B apart",k:"idiom",m:"A와 B를 구별하다",tip:"tell them apart / tell the difference. 구별이 어렵다는 뉘앙스가 깔립니다."}]},
  {s:"A",en:"Ask what would have to change for the discount to disappear, and ask who would even notice.",
   ko:"그 할인이 사라지려면 무엇이 바뀌어야 하는지 묻고, 그걸 알아챌 사람이 있기는 한지 물으세요.",
   notes:[{t:"what has to change for ~",k:"grammar",m:"~하려면 무엇이 바뀌어야 하는가",tip:"막연한 기대를 조건으로 바꾸는 질문 형태입니다."}]},
  {s:"B",en:"That's a much better question than the one I've been asking myself for a year.",
   ko:"제가 1년 동안 스스로에게 던져 온 질문보다 훨씬 나은 질문이네요.",
   notes:[{t:"a better question than ~",k:"collocation",m:"~보다 나은 질문",tip:"논의의 수준을 끌어올릴 때 쓰는 칭찬 겸 전환입니다."}]},
  {s:"A",en:"Most people ask whether it's cheap, when they should be asking what's driving the price.",
   ko:"대부분은 싼지를 묻지만, 정작 물어야 할 건 무엇이 그 가격을 움직이고 있는가입니다.",
   notes:[{t:"What's driving the price?",k:"business",m:"무엇이 주가를 움직이고 있는가",tip:"a driver = 움직이는 요인. The main driver is AI demand."}]},
  {s:"B",en:"I'm still bullish on the sector as a whole. I just can't defend the timing to myself.",
   ko:"저는 업종 전체에는 여전히 강세로 보고 있어요. 다만 시점만큼은 스스로에게 방어가 안 됩니다.",
   notes:[{t:"bullish on ~",k:"business",m:"~의 상승을 낙관하다",tip:"반대는 bearish on ~입니다. 반드시 짝으로 외우세요."}]},
  {s:"A",en:"Then size the position so that the timing doesn't matter, because conviction isn't the same thing as certainty.",
   ko:"그럼 시점이 중요하지 않을 만큼만 담으세요. 확신은 확실성과 같은 것이 아니니까요.",
   notes:[{t:"size a position",k:"business",m:"비중을 정하다",tip:"How do you size it? 얼마나 넣을지를 묻는 실무 표현입니다."},
          {t:"A isn't the same as B",k:"grammar",m:"A와 B는 같은 것이 아니다",tip:"비슷해 보이는 두 개념을 가르는 형태입니다."}]},
  {s:"B",en:"That I can live with. I'll hold on to it, but I'll stop adding to it blindly.",
   ko:"그건 받아들일 수 있습니다. 계속 들고 가되, 무작정 더 사는 건 그만두겠습니다.",
   notes:[{t:"I can live with that.",k:"idiom",m:"그 정도는 받아들일 수 있습니다",tip:"완전한 찬성은 아니라는 뉘앙스입니다. 협상에서 자주 씁니다."},
          {t:"blindly",k:"collocation",m:"앞뒤 안 가리고",tip:"buy blindly / follow blindly. 근거 없는 행동을 지적합니다."}]}
 ],
 keys:[
  {en:"I'm down forty percent.",ko:"40퍼센트 손실입니다",ex:"I'm down forty percent, but I'm up on the other position."},
  {en:"sit on a loss",ko:"평가손실을 안고 있다",ex:"He's been sitting on a loss since he bought at the top."},
  {en:"trade at X times earnings",ko:"이익의 X배에 거래되다",ex:"It trades at four times earnings, which looks cheap on paper."},
  {en:"price in ~",ko:"~을 미리 값에 반영하다",ex:"The market has already priced in the slowdown."},
  {en:"a value trap",ko:"싸 보이지만 계속 싼 채로 머무는 주식",ex:"A cheap stock with no catalyst is usually a value trap."},
  {en:"What's driving the price?",ko:"무엇이 주가를 움직이는가",ex:"Before you buy, ask what's driving the price."},
  {en:"hold on to ~",ko:"~을 팔지 않고 계속 보유하다",ex:"I'll hold on to it, but I won't add to it."},
  {en:"bullish on ~",ko:"~의 상승을 낙관하다",ex:"I'm bullish on the sector and bearish on that one name."}
 ],
 out:[
  {q:"Describe a position you are losing money on, and why you are still holding it.",hint:"I'm down ~ / sitting on a loss / hold on to"},
  {q:"Your colleague says a stock is cheap because it trades at four times earnings. Push back.",hint:"trade at X times earnings / a value trap / What's driving the price?"},
  {q:"Explain the difference between a cheap stock and a bargain.",hint:"price in / structural / a discount"}
 ]
},
{
 id:"w3d2", day:17, cat:"투자·자산배분", level:"B2+",
 title:"The Ten Percent Rule",
 titleKo:"10퍼센트의 규칙 — 헤지와 비중, 그리고 정치",
 names:{A:"Sena (자산배분 담당)", B:"Won (동료)"},
 brief:[
  "헤지는 수익을 노리는 것이 아니라 <b>다른 자산이 무너질 때 버텨 줄 것</b>을 사 두는 일입니다. 그래서 금 이야기를 할 때 「오를까요」가 아니라 「무엇에 대비하는가」를 먼저 묻습니다. 영어로는 <b>hedge against inflation</b>처럼 against 뒤에 대비 대상을 씁니다.",
  "핵심은 <b>비중(position sizing)</b>입니다. 좋은 자산이라도 비중이 과하면 포트폴리오 전체가 그 자산이 되어 버립니다. 「전체의 10퍼센트를 넘기지 않는다」는 <b>account for no more than ten percent</b>로 말합니다.",
  "정치와 시장의 관계도 자주 오르내립니다. 정부가 시장을 인위적으로 떠받친다는 뜻으로 <b>prop up the market</b>을 쓰고, 선거가 끝나면 그럴 <b>유인(incentive)</b>이 줄어든다는 식으로 이어집니다. 다만 이런 이야기는 근거가 약할 때가 많아, 토론에서는 반박을 받습니다.",
  "마지막은 <b>규칙으로 만들기</b>입니다. 예측이 아니라 절차로 정해 두는 것 — 매달 같은 금액을 넣고, 비중이 어긋나면 되돌리는 <b>rebalance</b>가 그것입니다. 감정이 개입할 자리를 미리 줄이는 방법입니다."
 ],
 lines:[
  {s:"A",en:"You said you want to start buying gold again, so what exactly are you hedging against?",
   ko:"금을 다시 사기 시작하고 싶다고 하셨는데, 정확히 무엇에 대비해 헤지하시려는 겁니까?",
   notes:[{t:"hedge against ~",k:"business",m:"~에 대비해 위험을 덜다",tip:"against 뒤에 대비 대상이 옵니다. hedge against inflation / against a weak won."}]},
  {s:"B",en:"Inflation, mostly. I want something in there that holds its value when cash doesn't.",
   ko:"주로 인플레이션이요. 현금이 값어치를 못 지킬 때 대신 지켜 주는 걸 하나 넣고 싶습니다.",
   notes:[{t:"hold value",k:"collocation",m:"값어치를 유지하다",tip:"Gold tends to hold its value. hold up도 비슷하게 씁니다."}]},
  {s:"A",en:"That's a reason, not a target. How much of the portfolio are we actually talking about?",
   ko:"그건 이유지 목표가 아닙니다. 포트폴리오의 몇 퍼센트를 말씀하시는 건가요?",
   notes:[{t:"A, not B",k:"grammar",m:"B가 아니라 A",tip:"짧게 구별을 짚는 형태입니다. 논점을 다시 세울 때 유용합니다."},
          {t:"What are we talking about?",k:"colloquial",m:"어느 정도를 말씀하시는 겁니까",tip:"막연한 말을 숫자로 끌어내는 질문입니다."}]},
  {s:"B",en:"Something small. I don't want it to account for more than ten percent of the whole thing.",
   ko:"적게요. 전체에서 10퍼센트를 넘게 차지하는 건 원치 않습니다.",
   notes:[{t:"account for X percent",k:"business",m:"전체의 X퍼센트를 차지하다",tip:"비중을 말하는 표준 표현입니다. take up도 구어로 씁니다."}]},
  {s:"A",en:"Good, because above that it stops being a hedge and quietly becomes a bet.",
   ko:"좋습니다. 그 선을 넘으면 헤지이기를 그만두고 조용히 베팅이 되니까요.",
   notes:[{t:"stop being A and become B",k:"grammar",m:"A이기를 그치고 B가 되다",tip:"경계를 넘는 순간을 묘사하는 형태입니다. 기억에 남는 문장을 만듭니다."}]},
  {s:"B",en:"I sold my last commodities at a loss, so I'd rather go slowly this time round.",
   ko:"지난번 원자재는 손해를 보고 팔았던 터라, 이번에는 천천히 가고 싶습니다.",
   notes:[{t:"at a loss",k:"business",m:"손해를 보고",tip:"sell at a loss / sell at a profit. 「어찌할 바를 모르다」라는 다른 뜻과 구별하세요."}]},
  {s:"A",en:"Then buy the same amount every month and ignore the price on the day entirely.",
   ko:"그럼 매달 같은 금액을 사고, 그날의 가격은 아예 무시하세요.",
   notes:[{t:"ignore ~ entirely",k:"collocation",m:"~을 아예 무시하다",tip:"부사를 뒤에 붙여 정도를 못 박습니다. 규칙을 강조할 때 씁니다."}]},
  {s:"B",en:"Doesn't that mean I also buy at bad prices, on the months when it's already expensive?",
   ko:"그럼 이미 비싼 달에는 나쁜 가격에도 사게 된다는 뜻 아닌가요?",
   notes:[{t:"Doesn't that mean ~?",k:"grammar",m:"그럼 ~라는 뜻 아닌가요",tip:"상대 제안의 결과를 짚어 되묻는 부드러운 반박입니다."}]},
  {s:"A",en:"Yes, and at good ones too. The point is that you stop guessing the timing altogether.",
   ko:"네, 좋은 가격에도 사고요. 요점은 시점 맞히기를 아예 그만둔다는 데 있습니다.",
   notes:[{t:"guess the timing",k:"collocation",m:"시점을 맞히려 하다",tip:"time the market과 같은 뜻입니다. 실패한다는 전제가 깔립니다."}]},
  {s:"B",en:"Fair. Honestly, my own timing has been wrong more often than not over the years.",
   ko:"일리 있네요. 솔직히 지난 세월 제 시점 판단은 맞기보다 틀린 적이 더 많았습니다.",
   notes:[{t:"more often than not",k:"idiom",m:"대체로, 십중팔구",tip:"여기서는 그 구조를 풀어 썼습니다. More often than not, he's right."}]},
  {s:"A",en:"Then set a rule and rebalance twice a year, and let the rule do the deciding for you.",
   ko:"그럼 규칙을 정하고 1년에 두 번 리밸런싱하세요. 결정은 그 규칙이 대신하게 두고요.",
   notes:[{t:"rebalance",k:"business",m:"비중을 원래대로 되돌리다",tip:"오른 자산을 팔고 내린 자산을 사는 정기 조정입니다."},
          {t:"let ~ do the deciding",k:"colloquial",m:"결정은 ~이 하게 두다",tip:"사람이 아닌 것을 주어로 세워 감정을 배제한다는 뜻을 냅니다."}]},
  {s:"B",en:"What about equities? Quite a few people expect a drop sometime after the election.",
   ko:"주식은요? 선거가 끝난 뒤 어느 시점에 하락이 온다고 보는 사람이 꽤 있던데요.",
   notes:[{t:"equities",k:"business",m:"주식 (자산군으로서)",tip:"stocks의 격식체입니다. equities / bonds / commodities로 묶어 씁니다."}]},
  {s:"A",en:"The argument is that the government props up the market right up until the vote.",
   ko:"투표 직전까지는 정부가 시장을 떠받친다는 논리죠.",
   notes:[{t:"prop up the market",k:"idiom",m:"시장을 인위적으로 떠받치다",tip:"막대기로 받쳐 세우는 이미지입니다. support보다 인위적인 뉘앙스가 셉니다."}]},
  {s:"B",en:"And afterwards they'd have far less incentive to keep doing it, which is when it slips.",
   ko:"그리고 그 뒤에는 계속 그럴 유인이 훨씬 줄어들 테고, 그때 미끄러진다는 거고요.",
   notes:[{t:"incentive",k:"business",m:"그렇게 할 유인, 동기",tip:"have an incentive to ~ 형태로 씁니다. 행동의 이유를 구조로 설명합니다."}]},
  {s:"A",en:"It's a tidy story, and I'd be careful with any thesis that needs a calendar to work.",
   ko:"깔끔한 이야기죠. 저는 달력이 있어야 성립하는 논리라면 뭐든 조심하겠습니다.",
   notes:[{t:"a tidy story",k:"colloquial",m:"너무 깔끔해서 의심스러운 설명",tip:"현실이 그렇게 단순하지 않다는 완곡한 반박입니다."}]},
  {s:"B",en:"That's a fair warning. I've lost money on tidy stories more than once before.",
   ko:"타당한 경고네요. 저도 깔끔한 이야기에 돈을 잃은 적이 한 번이 아닙니다.",
   notes:[{t:"a fair warning",k:"collocation",m:"새겨들을 만한 경고",tip:"Fair point / fair warning으로 짧게 인정할 때 씁니다."}]},
  {s:"A",en:"If you want to act on it at all, reduce risk gradually instead of trying to call the top.",
   ko:"그래도 행동에 옮기고 싶으시면, 꼭지를 맞히려 들지 말고 위험을 조금씩 줄이세요.",
   notes:[{t:"call the top",k:"business",m:"고점을 맞히다",tip:"call the bottom과 짝입니다. 거의 불가능하다는 뜻이 깔립니다."}]},
  {s:"B",en:"So trim the position, hold the core, and keep the gold small enough to stay a hedge.",
   ko:"그럼 비중을 조금 덜어 내고, 핵심은 들고 가고, 금은 헤지로 남을 만큼만 작게 유지한다.",
   notes:[{t:"trim a position",k:"business",m:"비중을 조금 줄이다",tip:"cut(크게 줄이다)보다 가볍습니다. trim / add로 짝지어 씁니다."}]},
  {s:"A",en:"That's the whole plan, and written down it takes about three lines on a page.",
   ko:"그게 계획의 전부이고, 적어 놓으면 한 장에 세 줄쯤 됩니다.",
   notes:[{t:"Written down, ~",k:"grammar",m:"적어 놓으면 ~",tip:"분사구문으로 조건을 간결하게 붙이는 형태입니다."}]},
  {s:"B",en:"Then let's write it down, because I make worse decisions when nothing is written anywhere.",
   ko:"그럼 적어 둡시다. 아무것도 적혀 있지 않을 때 제가 더 나쁜 결정을 하거든요.",
   notes:[{t:"make a decision",k:"collocation",m:"결정을 내리다",tip:"take a decision은 영국식입니다. 미국식은 make를 씁니다."}]}
 ],
 keys:[
  {en:"hedge against ~",ko:"~에 대비해 위험을 덜다",ex:"We hold a little gold to hedge against inflation."},
  {en:"account for X percent",ko:"전체의 X퍼센트를 차지하다",ex:"Gold shouldn't account for more than ten percent of the portfolio."},
  {en:"prop up the market",ko:"시장을 인위적으로 떠받치다",ex:"Some believe the government is trying to prop up the market."},
  {en:"an incentive to ~",ko:"~할 유인",ex:"After the vote they have less incentive to support prices."},
  {en:"rebalance",ko:"비중을 원래대로 되돌리다",ex:"We rebalance twice a year and ignore the noise in between."},
  {en:"sell at a loss",ko:"손해를 보고 팔다",ex:"I sold the commodities at a loss and learned something."},
  {en:"call the top",ko:"고점을 맞히다",ex:"Nobody calls the top twice in a row."},
  {en:"trim a position",ko:"비중을 조금 줄이다",ex:"Let's trim it rather than sell the whole thing."}
 ],
 out:[
  {q:"Explain why you hold a small amount of gold, without predicting its price.",hint:"hedge against / account for / hold value"},
  {q:"A colleague says stocks will fall right after the election. Respond carefully.",hint:"prop up the market / an incentive to / a tidy story"},
  {q:"Describe an investment rule you follow so that emotion doesn't decide for you.",hint:"rebalance / guess the timing / let the rule do the deciding"}
 ]
},
{
 id:"w3d3", day:18, cat:"신기술·훈련", level:"B2+",
 title:"Who Learns to Judge?",
 titleKo:"판단은 누가 배우는가 — 초안을 기계가 쓸 때",
 names:{A:"Hyun (팀장)", B:"Rosa (인재개발)"},
 brief:[
  "초안을 만드는 일이 쉬워지면서 일의 무게중심이 <b>생산에서 검증으로</b> 옮겨 갔습니다. 예전에는 초안을 쓰는 것이 가장 오래 걸리고 가장 중요한 일이었지만, 지금은 나온 것을 따져 보는 능력이 더 값어치 있게 됐습니다.",
  "문제는 <b>그 검증 능력이 어디서 오느냐</b>입니다. 좋은 검토자는 대개 직접 만들어 본 사람입니다. 숫자를 손으로 맞춰 보고, 틀려 보고, 어디가 잘 틀리는지 몸으로 아는 사람이 어디를 봐야 할지 압니다.",
  "그래서 생기는 것이 이 회차의 쟁점입니다. 신입이 초안을 한 번도 만들어 보지 않고 검토자부터 시작하면, <b>무엇을 근거로 판단하는가</b>. 조직은 효율을 얻고 그 대가로 다음 세대의 판단력을 잃을 수 있습니다.",
  "실무의 해법은 대개 둘 중 하나입니다. 일부러 <b>손으로 해 보는 구간(reps)</b>을 남겨 두거나, 검토를 가르치는 훈련을 따로 만드는 것입니다. 어느 쪽이든 <b>그냥 두면 저절로 생기지 않는다</b>는 것이 출발점입니다."
 ],
 lines:[
  {s:"A",en:"Drafting used to be the slow part, and now it takes a junior about ten minutes.",
   ko:"예전엔 초안 쓰기가 느린 부분이었는데, 지금은 신입이 10분이면 끝냅니다.",
   notes:[{t:"used to be ~",k:"grammar",m:"예전엔 ~였다 (지금은 아니다)",tip:"뒤에 Now ~ 를 붙이면 대비가 또렷해집니다."}]},
  {s:"B",en:"So the time has moved somewhere else, which raises the obvious question: where does the time go now?",
   ko:"그럼 시간이 다른 데로 옮겨 간 거고, 이제 그게 어디로 가는지가 문제가 되겠네요.",
   notes:[{t:"Where does the time go?",k:"collocation",m:"시간이 어디로 가는가",tip:"업무 분석에서 자주 쓰는 질문 형태입니다."}]},
  {s:"A",en:"Into checking, and checking is the part nobody ever put on a training plan.",
   ko:"확인하는 데로 갑니다. 그런데 확인은 아무도 교육 계획에 올려놓은 적이 없는 부분이죠.",
   notes:[{t:"put ~ on a plan",k:"collocation",m:"~을 계획에 넣다",tip:"It was never on the plan. 의도적으로 다뤄진 적이 없다는 뜻입니다."}]},
  {s:"B",en:"Because it was never the hard part. Producing was the skill we actually hired for.",
   ko:"어려운 부분이 아니었으니까요. 우리가 실제로 뽑을 때 본 능력은 생산이었습니다.",
   notes:[{t:"hire for ~",k:"collocation",m:"~을 보고 채용하다",tip:"hire for attitude, train for skill. 전치사 for를 통째로 외우세요."}]},
  {s:"A",en:"Right, and now I have people approving work that they couldn't have produced themselves.",
   ko:"맞아요. 그래서 지금은 자기가 직접 만들어 낼 수 없는 결과물을 승인하는 사람들이 생겼습니다.",
   notes:[{t:"approve work",k:"collocation",m:"결과물을 승인하다",tip:"sign off on과 비슷하지만 더 일반적인 말입니다."}]},
  {s:"B",en:"Is that actually a problem, though? Plenty of good editors couldn't write a novel either.",
   ko:"그런데 그게 정말 문제인가요? 좋은 편집자 중에도 소설을 못 쓰는 사람이 많잖아요.",
   notes:[{t:"Is that a problem, though?",k:"colloquial",m:"그런데 그게 문제인가요",tip:"though를 끝에 붙여 부드럽게 반박합니다. 구어에서 매우 흔합니다."}]},
  {s:"A",en:"Editors read thousands of drafts first, and that's where the judgment comes from.",
   ko:"편집자는 먼저 수천 편의 원고를 읽습니다. 판단력은 바로 거기서 나오는 거고요.",
   notes:[{t:"That's where ~ comes from.",k:"grammar",m:"~은 거기서 나온다",tip:"원인의 자리를 짚어 주는 형태입니다. 설명을 매듭지을 때 좋습니다."}]},
  {s:"B",en:"So your worry isn't the tool itself. It's that nobody builds up the reps anymore.",
   ko:"그러니까 걱정은 도구 자체가 아니군요. 아무도 더는 반복 경험을 쌓지 않는다는 거네요.",
   notes:[{t:"reps",k:"colloquial",m:"반복 훈련 횟수, 몸으로 쌓은 경험",tip:"운동의 repetition에서 왔습니다. You need more reps."}]},
  {s:"A",en:"Exactly. You learn where things break by breaking them yourself, over and over.",
   ko:"정확합니다. 어디서 깨지는지는 스스로 몇 번이고 깨뜨려 보면서 배우는 거니까요.",
   notes:[{t:"where things break",k:"collocation",m:"무엇이 어디서 잘못되는지",tip:"실패 지점을 가리키는 표현입니다. 품질·안전 대화에도 씁니다."}]},
  {s:"B",en:"I'll push back a little, because we could simply teach the checking directly instead.",
   ko:"조금 반박하자면, 그냥 확인하는 법을 직접 가르치면 되지 않나요?",
   notes:[{t:"I'll push back a little.",k:"idiom",m:"조금 이견을 내겠습니다",tip:"반대 의견을 예고해 각이 서지 않게 하는 말입니다."}]},
  {s:"A",en:"Teach it with what? A checklist tells you where to look, not what's actually wrong.",
   ko:"뭘로 가르치죠? 체크리스트는 어디를 보라고만 알려 주지, 뭐가 잘못됐는지는 말해 주지 않습니다.",
   notes:[{t:"Teach it with what?",k:"colloquial",m:"무엇으로 가르칩니까",tip:"짧은 되물음으로 상대 제안의 빈 곳을 찌릅니다."}]},
  {s:"B",en:"Fair. Most of my own catches come from having made that exact mistake myself before.",
   ko:"일리 있네요. 제가 잡아내는 것 대부분도 제가 전에 똑같은 실수를 해 봤기 때문이고요.",
   notes:[{t:"a catch",k:"business",m:"잡아낸 오류",tip:"Good catch. = 잘 짚으셨습니다. 명사로도 널리 씁니다."}]},
  {s:"A",en:"That's the whole argument. Verification is really just memory of your own past errors.",
   ko:"그게 논지의 전부입니다. 검증이란 결국 자기가 저질렀던 오류에 대한 기억이니까요.",
   notes:[{t:"That's the whole argument.",k:"colloquial",m:"그게 논지의 전부입니다",tip:"길게 설명한 뒤 한 문장으로 압축할 때 씁니다."}]},
  {s:"B",en:"Then protect some of the manual work on purpose, even if it makes the team slower.",
   ko:"그럼 팀이 느려지더라도, 손으로 하는 일 일부는 일부러 지켜 두세요.",
   notes:[{t:"on purpose",k:"idiom",m:"일부러, 의도적으로",tip:"by accident의 반대입니다. 비효율을 의도했다는 것을 밝힙니다."}]},
  {s:"A",en:"That's a hard sell upstairs, because it reads as choosing to be inefficient on purpose.",
   ko:"그건 윗선에 설득하기 어렵습니다. 일부러 비효율을 택하는 걸로 읽히니까요.",
   notes:[{t:"a hard sell",k:"idiom",m:"설득하기 어려운 것",tip:"반대는 an easy sell입니다."},
          {t:"read as ~",k:"collocation",m:"~으로 받아들여지다",tip:"의도가 아니라 전달되는 인상을 말합니다."}]},
  {s:"B",en:"Then don't frame it as training at all. Frame it as quality control with a cost.",
   ko:"그럼 아예 교육이라고 프레임을 잡지 마세요. 비용이 드는 품질 관리라고 하세요.",
   notes:[{t:"frame it as ~",k:"business",m:"~으로 규정해 보이게 하다",tip:"같은 지출도 이름에 따라 승인 여부가 갈립니다."}]},
  {s:"A",en:"That might actually work, because nobody argues with fewer errors in a customer report.",
   ko:"그건 통할 수도 있겠네요. 고객 보고서의 오류가 줄어드는 데 반대하는 사람은 없으니까요.",
   notes:[{t:"Nobody argues with ~",k:"colloquial",m:"~에는 아무도 반대하지 않는다",tip:"합의가 쉬운 근거를 제시할 때 씁니다."}]},
  {s:"B",en:"And it's true. We still miss wrong numbers whenever the checking gets rushed at the end.",
   ko:"게다가 사실이고요. 마지막에 확인이 급해지면 우리는 여전히 틀린 숫자를 놓칩니다.",
   notes:[{t:"miss a number",k:"collocation",m:"숫자를 놓치다, 오류를 못 잡다",tip:"a number slipped through로도 씁니다."}]},
  {s:"A",en:"So we keep the speed we've gained and buy back some of the judgment we lost.",
   ko:"그럼 얻은 속도는 지키면서, 잃은 판단력을 얼마쯤 되사 오는 거네요.",
   notes:[{t:"buy back ~",k:"phrasal",m:"~을 되사다, 되찾다",tip:"buy back time / buy back trust처럼 추상적인 것에도 씁니다."}]},
  {s:"B",en:"That's the trade I'd make, because speed is easy to get back and judgment isn't.",
   ko:"저라면 그 거래를 하겠습니다. 속도는 되찾기 쉽지만 판단력은 그렇지 않으니까요.",
   notes:[{t:"the trade I'd make",k:"idiom",m:"제가 택할 교환",tip:"선택지를 맞바꾸는 결정을 말할 때 씁니다. It's a trade, not a win."}]}
 ],
 keys:[
  {en:"hire for ~ / train for ~",ko:"~을 보고 뽑다 / ~을 겨냥해 훈련하다",ex:"Hire for attitude and train for the rest."},
  {en:"reps",ko:"반복 훈련, 몸으로 쌓은 경험",ex:"She's good because she's had far more reps than anyone else."},
  {en:"a catch",ko:"잡아낸 오류",ex:"That was a good catch before the report went out."},
  {en:"That's where ~ comes from.",ko:"~은 거기서 나온다",ex:"He's made every mistake once; that's where the judgment comes from."},
  {en:"a hard sell",ko:"설득하기 어려운 것",ex:"Slower on purpose is a hard sell in any budget meeting."},
  {en:"frame it as ~",ko:"~으로 규정해 보이게 하다",ex:"Frame it as quality control and the money appears."},
  {en:"on purpose",ko:"일부러, 의도적으로",ex:"We keep part of it manual on purpose."},
  {en:"buy back ~",ko:"~을 되사다, 되찾다",ex:"You can buy back speed later; you can't buy back judgment."}
 ],
 out:[
  {q:"Explain why a good reviewer usually needs to have produced the work themselves.",hint:"reps / where things break / That's where it comes from"},
  {q:"Propose keeping some work manual, to a manager who only cares about speed.",hint:"frame it as / a hard sell / Nobody argues with"},
  {q:"Describe a mistake you caught because you had made it yourself before.",hint:"a catch / miss a number / on purpose"}
 ]
},
{
 id:"w3d4", day:19, cat:"신기술·에이전트", level:"B2+",
 title:"The New Hire Who Never Sleeps",
 titleKo:"잠들지 않는 신입 — AI 에이전트를 데리고 일하기",
 names:{A:"Jae (영업관리)", B:"Claire (업무혁신)"},
 brief:[
  "글을 만들어 주던 도구가 이제 <b>컴퓨터를 직접 쓰는 단계</b>로 넘어왔습니다. 파일을 열고 자료를 읽고 결과물을 만들어 냅니다. 영어로는 이런 것을 <b>an agent</b>라 부르고, 사람을 대신해 실제로 일을 <b>실행한다(carry out)</b>는 점에서 이전과 다릅니다.",
  "그래서 비유가 바뀝니다. 도구가 아니라 <b>아주 유능하지만 맥락을 모르는 신입</b>에 가깝습니다. 신입에게 필요한 것과 똑같은 것이 필요합니다 — 목표, 배경, 판단 기준, 그리고 어디까지 스스로 정해도 되는지의 선.",
  "여기서 <b>지시를 잘 쓰는 일(prompting)</b>과 <b>일이 되게 판을 짜는 일</b>이 갈립니다. 후자는 도구·규칙·검토 절차·피드백까지 포함하는 설계입니다. 사람에게 맡길 때 우리가 늘 하던 일과 다르지 않습니다.",
  "마지막 쟁점은 <b>어디까지 맡길 것인가</b>입니다. 되돌릴 수 있는 일과 되돌릴 수 없는 일을 가르는 것이 실무의 기준선이고, 이것은 신입에게 권한을 주는 방식과 정확히 같습니다."
 ],
 lines:[
  {s:"A",en:"It didn't just write the report, but opened the files and built the slides by itself.",
   ko:"보고서만 쓴 게 아닙니다. 파일을 직접 열고 장표까지 스스로 만들었어요.",
   notes:[{t:"not just A, but B",k:"grammar",m:"A만이 아니라 B까지",tip:"놀라움을 단계로 쌓아 올리는 형태입니다. 발표에서 효과적입니다."},
          {t:"build slides",k:"collocation",m:"장표를 만들다",tip:"make a deck / put a deck together도 함께 씁니다."}]},
  {s:"B",en:"So it's actually carrying out the task, rather than just describing how the task should be done.",
   ko:"그럼 일을 어떻게 해야 하는지 설명만 하는 게 아니라, 실제로 그 일을 수행하고 있는 거네요.",
   notes:[{t:"carry out ~",k:"phrasal",m:"(일을) 실제로 수행하다",tip:"carry out a plan / carry out a test. 실행 단계를 가리킵니다."}]},
  {s:"A",en:"Exactly. Work that would have taken me the better part of a week took about fifteen minutes.",
   ko:"정확합니다. 저였으면 한 주의 상당 부분을 썼을 일이 15분쯤에 끝났어요.",
   notes:[{t:"Work that would have taken ~",k:"grammar",m:"~걸렸을 일",tip:"would have + 과거분사로 실제와 다른 경우를 가정합니다."}]},
  {s:"B",en:"That's the part that changes budgets, but how much of what came back did you have to fix?",
   ko:"예산을 바꾸는 게 바로 그 부분이죠. 그런데 돌아온 결과물 중 얼마나 손을 봐야 했습니까?",
   notes:[{t:"That's the part that ~",k:"grammar",m:"바로 그 부분이 ~하는 것이다",tip:"여러 요소 중 하나를 짚어 강조합니다."}]},
  {s:"A",en:"Some of it. It guessed at things I never told it, which is honestly my own fault.",
   ko:"일부는요. 제가 말해 주지 않은 것들을 추측해서 채웠는데, 솔직히 그건 제 잘못입니다.",
   notes:[{t:"guess at ~",k:"phrasal",m:"~을 짐작으로 채우다",tip:"근거 없이 메운다는 뉘앙스입니다. Don't guess at the numbers."}]},
  {s:"B",en:"That sounds familiar, because new people do exactly the same thing in their first week.",
   ko:"익숙한 얘기네요. 새로 온 사람들도 첫 주에 정확히 똑같이 하거든요.",
   notes:[{t:"That sounds familiar.",k:"colloquial",m:"익숙한 얘기네요",tip:"상대 경험이 자기 경험과 겹칠 때 쓰는 짧은 공감입니다."}]},
  {s:"A",en:"That's honestly how it feels, like hiring someone brilliant who arrives with no context at all.",
   ko:"솔직히 딱 그런 느낌입니다. 아무 맥락도 없이 들어온 아주 똑똑한 사람을 뽑은 것 같은.",
   notes:[{t:"with no context",k:"collocation",m:"배경을 전혀 모른 채",tip:"context = 그 일이 놓인 배경. 실무 영어의 핵심어입니다."}]},
  {s:"B",en:"Then treat it that way. What would you actually give a new analyst on their first day?",
   ko:"그럼 그렇게 대하세요. 신입 분석가에게 첫날 실제로 뭘 주시겠습니까?",
   notes:[{t:"treat it that way",k:"colloquial",m:"그런 식으로 대하다",tip:"비유를 실제 행동으로 옮기라고 권하는 말입니다."}]},
  {s:"A",en:"The goal, the audience, last quarter's version, and a list of what we got wrong before.",
   ko:"목적, 읽을 사람, 지난 분기 버전, 그리고 전에 우리가 틀렸던 것들의 목록이요.",
   notes:[{t:"what we got wrong",k:"grammar",m:"우리가 무엇을 틀렸는지",tip:"what절로 실패 경험을 정리해 넘깁니다. 인수인계의 정석입니다."}]},
  {s:"B",en:"Then give it exactly the same, because most bad output is really a briefing problem.",
   ko:"그럼 그것과 똑같이 주세요. 나쁜 결과물 대부분은 사실 브리핑 문제니까요.",
   notes:[{t:"output",k:"business",m:"산출물, 결과물",tip:"input과 짝입니다. 사람과 기계 양쪽에 씁니다."}]},
  {s:"A",en:"People call that harness engineering now, rather than simply writing better prompts.",
   ko:"요즘은 그걸 더 나은 프롬프트를 쓰는 일이 아니라 하네스 엔지니어링이라고 부르더군요.",
   notes:[{t:"rather than ~",k:"grammar",m:"~이라기보다",tip:"두 개념을 가를 때의 기본 형태입니다."}]},
  {s:"B",en:"Is that a real distinction, or is it just a new name for the same old thing?",
   ko:"그게 진짜 구분인가요, 아니면 같은 것에 붙인 새 이름일 뿐인가요?",
   notes:[{t:"Is that a real distinction?",k:"business",m:"그게 실질적인 구분입니까",tip:"유행어를 만났을 때 던지기 좋은 질문입니다."}]},
  {s:"A",en:"I think it's real. One of them is what you say, and the other is the whole setup around it.",
   ko:"저는 진짜라고 봅니다. 하나는 무엇을 말하느냐이고, 다른 하나는 그 주위를 둘러싼 전체 판이니까요.",
   notes:[{t:"the setup around it",k:"collocation",m:"그것을 둘러싼 체계",tip:"도구·규칙·절차를 통칭합니다. set it up = 판을 짜다."}]},
  {s:"B",en:"Tools, rules, and somebody who checks the result before any of it goes out the door.",
   ko:"도구, 규칙, 그리고 그게 밖으로 나가기 전에 결과를 확인하는 사람이군요.",
   notes:[{t:"go out",k:"phrasal",m:"(문서·결과물이) 나가다",tip:"before it goes out = 대외로 나가기 전에."}]},
  {s:"A",en:"Right, and the instruction itself is maybe a tenth of whether the thing works.",
   ko:"맞습니다. 지시문 자체는 그게 제대로 돌아가느냐의 10분의 1쯤밖에 안 됩니다.",
   notes:[{t:"a tenth of ~",k:"collocation",m:"~의 10분의 1",tip:"a third / a quarter / a tenth로 분수를 말합니다."}]},
  {s:"B",en:"Then where do you draw the line on what it's allowed to decide by itself?",
   ko:"그럼 그게 스스로 결정해도 되는 범위의 선을 어디에 긋습니까?",
   notes:[{t:"draw the line on ~",k:"idiom",m:"~에 대해 기준선을 긋다",tip:"Where do you draw the line? 기준을 묻는 정석 질문입니다."}]},
  {s:"A",en:"Anything reversible, it can do on its own. Anything irreversible that reaches a customer, I sign myself.",
   ko:"되돌릴 수 있는 일은 알아서 해도 됩니다. 고객에게 닿는 일은 제가 직접 결재하고요.",
   notes:[{t:"reversible",k:"business",m:"되돌릴 수 있는",tip:"irreversible과 짝으로 씁니다. 권한 위임의 기준으로 매우 유용합니다."}]},
  {s:"B",en:"That's the same rule I'd give a junior, which is probably the whole point of it.",
   ko:"그건 제가 후배에게 줄 규칙과 똑같은데, 아마 그게 핵심이겠죠.",
   notes:[{t:"which is probably the point",k:"colloquial",m:"아마 그게 요점이겠죠",tip:"앞말을 받아 결론을 가볍게 던지는 구어입니다."}]},
  {s:"A",en:"It is. The hard part was never the tool, it's knowing what good actually looks like.",
   ko:"그렇습니다. 어려운 건 애초에 도구가 아니라, 좋은 게 실제로 어떤 모습인지 아는 것이었죠.",
   notes:[{t:"know what good looks like",k:"idiom",m:"좋은 결과가 어떤 것인지 안다",tip:"기준을 가진 사람만 검토할 수 있다는 뜻입니다. 실무에서 자주 인용됩니다."}]},
  {s:"B",en:"And that still lives in people, at least for as long as anyone can see ahead.",
   ko:"그리고 그건 아직 사람 안에 있습니다. 적어도 지금 내다볼 수 있는 동안에는요.",
   notes:[{t:"live in ~",k:"collocation",m:"(능력·지식이) ~에 자리하다",tip:"The knowledge lives in three people. 조직 대화에서 즐겨 씁니다."}]}
 ],
 keys:[
  {en:"carry out ~",ko:"(일을) 실제로 수행하다",ex:"It doesn't just plan the work; it carries it out."},
  {en:"with no context",ko:"배경을 전혀 모른 채",ex:"Brilliant with no context is still going to guess."},
  {en:"guess at ~",ko:"~을 짐작으로 채우다",ex:"If you don't tell it, it will guess at the assumptions."},
  {en:"the setup around it",ko:"그것을 둘러싼 체계",ex:"The prompt matters less than the setup around it."},
  {en:"reversible / irreversible",ko:"되돌릴 수 있는 / 없는",ex:"Anything reversible it can do; the rest comes to me."},
  {en:"draw the line on ~",ko:"~에 대해 기준선을 긋다",ex:"Where do you draw the line on what it decides alone?"},
  {en:"know what good looks like",ko:"좋은 결과가 어떤 것인지 안다",ex:"You can't review it unless you know what good looks like."},
  {en:"output",ko:"산출물, 결과물",ex:"Bad output is usually a briefing problem, not a tool problem."}
 ],
 out:[
  {q:"Explain how using an AI agent is different from using a tool that only writes text.",hint:"carry out / output / with no context"},
  {q:"Describe what you would give an agent at the start of a task, as if briefing a new hire.",hint:"the goal / what we got wrong / the setup around it"},
  {q:"Say where you would draw the line between what it decides and what you sign.",hint:"reversible / draw the line on / know what good looks like"}
 ]
},
{
 id:"w3d5", day:20, cat:"신기술·기술", level:"B2+",
 title:"Do We Still Need to Code?",
 titleKo:"코딩을 여전히 배워야 하는가 — 번역기 비유의 한계",
 names:{A:"Tae (기획, 비개발자)", B:"Noor (개발자)"},
 brief:[
  "프로그래밍 언어는 결국 <b>기계가 알아듣도록 만든 언어</b>입니다. 그래서 사람의 말을 코드로 옮기는 일을 <b>번역</b>에 비유하는 시각이 자연스럽게 나옵니다. 원하는 것을 말하면 도구가 옮겨 준다는 그림입니다.",
  "이 비유의 강점은 분명합니다. 예전에는 문법을 익히는 데 몇 년이 들었고, 그 문턱 때문에 아이디어가 <b>코드로 옮겨지지 못한 채</b> 사라졌습니다. 이제는 말로 설명하는 것만으로 움직이는 것이 나옵니다.",
  "약점도 분명합니다. 번역은 <b>무엇을 원하는지 아는 사람</b>이 있어야 성립합니다. 그리고 프로그램은 글과 달리 <b>틀리면 조용히 잘못 돌아갑니다</b>. 그때 필요한 것이 디버깅이고, 디버깅은 결국 「기계가 실제로 무엇을 하는가」를 읽는 일입니다.",
  "그래서 쟁점은 「언어를 외울 필요가 있는가」가 아니라 <b>어떤 개념을 알아야 하는가</b>로 옮겨 갑니다. 문법은 덜 중요해졌지만, 자료가 어떻게 흐르고 무엇이 어디서 깨지는지에 대한 감각은 그대로 필요합니다."
 ],
 lines:[
  {s:"A",en:"I've started to think of it as a translator sitting between what I want and the code.",
   ko:"저는 이걸 제가 원하는 것과 코드 사이에 앉아 있는 번역기로 보게 됐습니다.",
   notes:[{t:"think of A as B",k:"grammar",m:"A를 B로 여기다",tip:"I think of it as a colleague. 비유를 꺼낼 때의 기본 형태입니다."}]},
  {s:"B",en:"That's a fair description of what it does, but where does the metaphor stop working?",
   ko:"하는 일에 대한 설명으로는 타당합니다. 그런데 그 비유는 어디서부터 안 맞기 시작하죠?",
   notes:[{t:"Where does it stop working?",k:"business",m:"어디서부터 안 맞습니까",tip:"비유나 규칙의 한계를 묻는 좋은 질문입니다."}]},
  {s:"A",en:"I'm not sure it does, because a programming language was designed for machines in the first place.",
   ko:"안 맞는 데가 있는지 모르겠습니다. 프로그래밍 언어는 애초에 기계용으로 만든 거니까요.",
   notes:[{t:"I'm not sure it does.",k:"colloquial",m:"그런 데가 있는지 모르겠습니다",tip:"앞 문장의 동사를 does로 받는 대동사 용법입니다."}]},
  {s:"B",en:"True, but translation assumes there's somebody who already knows what they want said.",
   ko:"맞습니다. 그런데 번역은 무엇을 말할지 이미 아는 사람이 있다고 전제하죠.",
   notes:[{t:"assume",k:"business",m:"전제하다",tip:"That assumes ~ 는 상대의 숨은 전제를 드러내는 반박 형태입니다."}]},
  {s:"A",en:"Fair enough, though describing what I want is exactly the part I'm confident I can do.",
   ko:"일리 있어요. 그래도 원하는 걸 설명하는 건 제가 할 수 있다고 자신하는 부분입니다.",
   notes:[{t:"Fair enough. Though ~",k:"grammar",m:"일리는 있습니다. 다만 ~",tip:"인정하고 단서를 다는 부드러운 반박 리듬입니다."}]},
  {s:"B",en:"Then try describing what should happen when two of the rules you wrote disagree with each other.",
   ko:"그럼 직접 쓴 규칙 두 개가 서로 어긋날 때 어떻게 되어야 하는지 설명해 보세요.",
   notes:[{t:"disagree",k:"business",m:"(규칙·자료가) 서로 어긋나다",tip:"사람만이 아니라 숫자에도 씁니다. The two reports disagree."}]},
  {s:"A",en:"That's a good example, and I wouldn't have thought to specify that on my own.",
   ko:"좋은 예네요. 저 혼자였다면 그걸 명시할 생각을 못 했을 겁니다.",
   notes:[{t:"specify",k:"business",m:"명확히 지정하다",tip:"specify the format / specify the conditions. 요건 정의의 동사입니다."}]},
  {s:"B",en:"That's most of programming, honestly: deciding what happens in all the odd cases nobody imagines.",
   ko:"솔직히 프로그래밍의 대부분이 그겁니다. 아무도 상상하지 않는 이상한 경우들에 어떻게 할지 정하는 것.",
   notes:[{t:"the odd cases",k:"collocation",m:"드물고 이상한 경우",tip:"edge cases와 같은 뜻입니다. 대부분의 버그가 여기서 나옵니다."}]},
  {s:"A",en:"Still, I'd rather describe those in Korean than sit down and learn the syntax first.",
   ko:"그래도 앉아서 문법부터 배우느니 그걸 한국어로 설명하는 편이 낫겠습니다.",
   notes:[{t:"syntax",k:"business",m:"문법, 표기 규칙",tip:"언어의 형태 규칙입니다. semantics(의미)와 짝으로 알아 두세요."}]},
  {s:"B",en:"I agree with that part, because the syntax was never the valuable bit of the skill.",
   ko:"그 부분은 동의합니다. 문법이 그 능력에서 값어치 있는 부분이었던 적은 없으니까요.",
   notes:[{t:"the valuable bit",k:"colloquial",m:"정작 값어치 있는 부분",tip:"bit는 영국식 구어로 「부분」입니다. the tricky bit / the boring bit."}]},
  {s:"A",en:"So we agree, then. Nobody needs to memorize a language the way we used to.",
   ko:"그럼 동의하시는군요. 예전처럼 언어를 외울 필요는 이제 없다는 거죠.",
   notes:[{t:"memorize",k:"collocation",m:"외우다",tip:"learn(익히다)과 구별됩니다. 여기서는 암기의 불필요함을 말합니다."}]},
  {s:"B",en:"Not quite. You don't need the grammar, but you do need to read what it built for you.",
   ko:"꼭 그렇진 않습니다. 문법은 필요 없어도, 그게 대신 만들어 준 걸 읽을 줄은 알아야죠.",
   notes:[{t:"Not quite.",k:"colloquial",m:"꼭 그렇지는 않습니다",tip:"전면 부정이 아닌 부분 부정입니다. 부드럽게 반박할 때 씁니다."}]},
  {s:"A",en:"Why, if it works? I can test the result without ever reading a line of it.",
   ko:"돌아가면 됐지 왜요? 한 줄도 안 읽고 결과만 시험해 볼 수 있는데요.",
   notes:[{t:"Why, if it works?",k:"colloquial",m:"돌아가면 됐지 왜요",tip:"짧게 되받아 근거를 요구하는 구어입니다."}]},
  {s:"B",en:"Because code fails quietly, which means it keeps running and hands you a wrong number.",
   ko:"코드는 조용히 실패하니까요. 계속 돌면서 틀린 숫자를 건네준다는 뜻입니다.",
   notes:[{t:"fail quietly",k:"idiom",m:"티 나지 않게 잘못되다",tip:"오류 메시지 없이 잘못 도는 상태입니다. 실무에서 가장 위험한 실패입니다."}]},
  {s:"A",en:"That's the part that actually worries me, because I'd never know that it was wrong.",
   ko:"사실 저를 정말 걱정시키는 게 그겁니다. 틀렸다는 걸 알 길이 없으니까요.",
   notes:[{t:"That's the part that worries me.",k:"colloquial",m:"저를 걱정시키는 건 그 부분입니다",tip:"여러 쟁점 중 하나를 짚어 앞세우는 말입니다."}]},
  {s:"B",en:"So learn concepts, not languages: how data moves, and where it tends to break.",
   ko:"그럼 언어가 아니라 개념을 배우세요. 자료가 어떻게 흐르고, 주로 어디서 깨지는지.",
   notes:[{t:"concepts, not languages",k:"collocation",m:"언어가 아니라 개념",tip:"A, not B 형태로 학습의 초점을 옮깁니다."}]},
  {s:"A",en:"That sounds like a much shorter list than the one I was expecting to hear.",
   ko:"제가 듣게 될 거라 예상했던 것보다 훨씬 짧은 목록 같네요.",
   notes:[{t:"a shorter list than ~",k:"collocation",m:"~보다 짧은 목록",tip:"학습 부담이 줄었다는 것을 구체적으로 표현합니다."}]},
  {s:"B",en:"It is shorter. It just isn't empty, which is what people keep claiming that it is.",
   ko:"짧은 건 맞습니다. 다만 비어 있진 않아요. 사람들이 계속 비어 있다고 주장하지만요.",
   notes:[{t:"It just isn't empty.",k:"colloquial",m:"다만 아예 없는 건 아닙니다",tip:"과장된 주장을 깎아 내리는 짧은 반박입니다."}]},
  {s:"A",en:"Then I'll keep building things and read just enough to argue with the result it gives me.",
   ko:"그럼 계속 만들면서, 그게 내놓는 결과와 다툴 수 있을 만큼만 읽겠습니다.",
   notes:[{t:"argue with the result",k:"idiom",m:"결과를 그대로 받아들이지 않고 따져 보다",tip:"맹신하지 않겠다는 태도를 짧게 드러냅니다."}]},
  {s:"B",en:"That's exactly the right level, because you don't need to write it in order to question it.",
   ko:"딱 그 정도면 됩니다. 의심하기 위해 직접 쓸 필요는 없으니까요.",
   notes:[{t:"You don't need to A to B",k:"grammar",m:"B 하려고 A 할 필요는 없다",tip:"필요 조건을 부정하는 형태입니다. 조언에 자주 쓰입니다."}]}
 ],
 keys:[
  {en:"think of A as B",ko:"A를 B로 여기다",ex:"I think of the agent as a very fast junior."},
  {en:"the odd cases",ko:"드물고 이상한 경우",ex:"Most of the work is deciding what happens in the odd cases."},
  {en:"specify",ko:"명확히 지정하다",ex:"If you don't specify it, something else will decide for you."},
  {en:"fail quietly",ko:"티 나지 않게 잘못되다",ex:"The worst errors fail quietly and keep producing numbers."},
  {en:"Not quite.",ko:"꼭 그렇지는 않습니다",ex:"Not quite — the grammar is optional, the concepts aren't."},
  {en:"syntax",ko:"문법, 표기 규칙",ex:"The syntax was never the valuable part of the skill."},
  {en:"concepts, not languages",ko:"언어가 아니라 개념",ex:"Teach concepts, not languages, and the tools stop mattering."},
  {en:"argue with the result",ko:"결과를 그대로 받아들이지 않고 따져 보다",ex:"Read enough to argue with the result it hands you."}
 ],
 out:[
  {q:"Explain the 'translator' view of AI and coding, then say where it stops working.",hint:"think of A as B / assume / Where does it stop working?"},
  {q:"Argue that people still need some understanding of programming concepts.",hint:"fail quietly / the odd cases / Not quite"},
  {q:"Describe what you personally would learn, and what you would skip.",hint:"syntax / concepts, not languages / argue with the result"}
 ]
},
{
 id:"w3d6", day:21, cat:"공급망·현지화", level:"B2+",
 title:"Make Where You Sell",
 titleKo:"파는 곳에서 만들기 — 현지화는 비용인가 보험인가",
 names:{A:"Hyun (구매 총괄)", B:"Dana (현지 법인장)"},
 brief:[
  "지난 30년의 공급망은 하나의 질문만 물었습니다. <b>어디서 만들면 가장 쌉니까.</b> 그 답을 따라 공장이 옮겨 다녔고, 재고는 얇아졌으며, 배는 정확히 제때 도착한다는 전제 위에 모든 계획이 올라섰습니다.",
  "그 전제가 몇 번 깨졌습니다. 항구가 막히고, 국경이 닫히고, 관세가 하룻밤에 바뀌었습니다. 그래서 요즘 회사들이 던지는 질문이 바뀌었습니다. <b>가장 싼 곳</b>이 아니라 <b>끊겨도 견디는 구조</b>를 묻습니다.",
  "대안은 대체로 셋입니다. 같은 부품을 여러 나라에서 사는 <b>다중 소싱</b>, 파는 시장 안에서 만드는 <b>현지화</b>, 그리고 그냥 재고를 더 쌓는 것. 셋 다 돈이 듭니다. 그래서 논쟁은 「할 것인가」가 아니라 <b>얼마를 보험료로 낼 것인가</b>가 됩니다.",
  "이 대화에서 유용한 것은 결론이 아니라 <b>비용을 보험으로 바꿔 말하는 언어</b>입니다. 「비싸다」를 「무엇에 대한 대가인가」로 되묻는 문장들을 익혀 두면, 어떤 투자 논의에서도 그대로 쓸 수 있습니다."
 ],
 lines:[
  {s:"A",en:"For thirty years we only ever asked one question, which was where we could make this cheapest.",
   ko:"30년 동안 우리는 질문 하나만 던졌습니다. 어디서 만들면 이걸 가장 싸게 만들 수 있는가.",
   notes:[{t:"For thirty years we asked one question.",k:"grammar",m:"30년간 우리는 질문 하나만 던졌습니다",tip:"기간 + 과거형으로 「끝난 시대」를 선언하는 도입부입니다."},
          {t:"make it cheapest",k:"collocation",m:"가장 싸게 만들다",tip:"최상급을 부사처럼 씁니다. build it fastest 도 같은 형태입니다."}]},
  {s:"B",en:"And it worked beautifully, right up until the day the ships stopped arriving on time.",
   ko:"그리고 배가 제때 도착하지 않기 시작한 날 전까지는 훌륭하게 돌아갔죠.",
   notes:[{t:"It worked, until ~",k:"grammar",m:"통했습니다, ~ 하기 전까지는",tip:"전제가 언제 깨졌는지 짚는 반박 형태입니다."},
          {t:"arrive on time",k:"collocation",m:"제때 도착하다",tip:"on time(정시에)과 in time(늦지 않게)은 다릅니다."}]},
  {s:"A",en:"One bad quarter doesn't undo thirty good years of buying at the lowest price available.",
   ko:"나쁜 분기 하나가, 구할 수 있는 가장 싼 값에 사 온 좋은 30년을 없던 일로 만들지는 않습니다.",
   notes:[{t:"undo",k:"business",m:"없던 일로 만들다, 되돌리다",tip:"One mistake doesn't undo the record. 강한 반박 동사입니다."}]},
  {s:"B",en:"It wasn't one quarter. We missed the season twice in the space of three years.",
   ko:"한 분기가 아니었습니다. 3년 사이에 성수기를 두 번 놓쳤어요.",
   notes:[{t:"miss the season",k:"idiom",m:"성수기를 놓치다",tip:"팔릴 시점에 물건이 없었다는 뜻입니다. 유통에서 최악의 실패입니다."}]},
  {s:"A",en:"Point taken, but making it here costs us about eighteen percent more on every single unit.",
   ko:"인정합니다. 그래도 여기서 만들면 낱개마다 18퍼센트쯤 더 듭니다.",
   notes:[{t:"Point taken.",k:"colloquial",m:"일리 있습니다, 인정합니다",tip:"상대 지적을 짧게 받아들이고 반론을 이어 가는 말입니다."},
          {t:"cost us X percent more",k:"collocation",m:"우리에게 X퍼센트 더 들다",tip:"증가분을 말할 때의 기본 틀입니다."}]},
  {s:"B",en:"More than what, though? You're comparing it to a year in which nothing went wrong.",
   ko:"그런데 뭐보다 더요? 아무 일도 안 생긴 해와 비교하고 계시잖아요.",
   notes:[{t:"More than what, though?",k:"colloquial",m:"그런데 뭐에 비해서요?",tip:"비교 대상을 드러내라고 되묻는 짧은 반문입니다."}]},
  {s:"A",en:"Against our normal cost, because that's the only number I can actually budget against.",
   ko:"평상시 원가 대비죠. 제가 실제로 예산을 잡을 수 있는 숫자는 그것뿐이니까요.",
   notes:[{t:"budget against",k:"business",m:"~을 기준으로 예산을 잡다",tip:"against는 「기준으로 삼아」라는 뜻으로 자주 쓰입니다."}]},
  {s:"B",en:"Then your budget quietly assumes that nothing goes wrong, and that's an expensive assumption to build on.",
   ko:"그럼 예산이 아무 일도 안 생긴다고 조용히 전제하는 셈인데, 그건 위에 뭘 올리기엔 비싼 전제입니다.",
   notes:[{t:"an expensive assumption",k:"idiom",m:"대가가 큰 전제",tip:"틀렸을 때 손실이 크다는 뜻입니다. 회의에서 힘이 센 표현입니다."}]},
  {s:"A",en:"So call it insurance, fine. What exactly am I buying for that eighteen percent?",
   ko:"그럼 보험이라고 하죠, 좋습니다. 그 18퍼센트로 제가 정확히 뭘 사는 겁니까?",
   notes:[{t:"What am I buying for X?",k:"business",m:"X를 내고 제가 사는 것이 무엇입니까",tip:"비용을 편익으로 되묻는 아주 실용적인 질문입니다."}]},
  {s:"B",en:"Two weeks instead of eleven, and a border that can't be closed on you overnight.",
   ko:"11주 대신 2주, 그리고 하룻밤에 당신 앞에서 닫힐 수 없는 국경입니다.",
   notes:[{t:"A instead of B",k:"grammar",m:"B 대신 A",tip:"개선을 숫자 대 숫자로 보여 주는 가장 간단한 형태입니다."},
          {t:"a border that can't close on you",k:"idiom",m:"막힐 걱정이 없는 국경",tip:"close on someone은 「누군가에게 불리하게 닫히다」입니다."}]},
  {s:"A",en:"That matters more than I like to admit, because our lead time is what customers complain about.",
   ko:"인정하기 싫지만 그게 중요하긴 합니다. 고객이 불평하는 게 우리 리드타임이거든요.",
   notes:[{t:"more than I like to admit",k:"idiom",m:"인정하고 싶은 것보다 더",tip:"솔직하게 물러설 때 쓰는 부드러운 양보 표현입니다."},
          {t:"lead time",k:"business",m:"주문에서 납품까지 걸리는 시간",tip:"제조와 유통 회의의 핵심 단어입니다."}]},
  {s:"B",en:"Then price the complaint. What does a single late shipment cost you in orders you never see?",
   ko:"그럼 그 불만에 값을 매기세요. 늦은 선적 한 번이, 구경도 못 해 본 주문으로 치면 얼마입니까?",
   notes:[{t:"price something",k:"business",m:"~에 값을 매기다, 비용을 계산하다",tip:"추상적인 위험을 숫자로 바꾸라는 요구입니다."}]},
  {s:"A",en:"We've never measured that, to be honest, because we only measure what we spend and never what we lose.",
   ko:"솔직히 재 본 적이 없습니다. 우리는 쓰는 돈만 재지, 잃는 돈은 재지 않으니까요.",
   notes:[{t:"We only measure what we spend.",k:"grammar",m:"우리는 쓰는 돈만 측정합니다",tip:"what절을 목적어로 쓰는 형태입니다. 사고의 사각지대를 지적합니다."}]},
  {s:"B",en:"That's why cheap always wins, since the other side of the ledger stays completely invisible.",
   ko:"그래서 늘 싼 쪽이 이깁니다. 장부의 반대편은 아예 보이지 않으니까요.",
   notes:[{t:"the other side of the ledger",k:"idiom",m:"장부의 반대편, 드러나지 않는 쪽",tip:"비용은 보이고 편익은 안 보이는 상황을 가리킵니다."}]},
  {s:"A",en:"I'd rather not move everything at once, though, because that's a huge bet to make all at once.",
   ko:"그래도 전부를 한꺼번에 옮기고 싶진 않습니다. 그건 너무 큰 도박이니까요.",
   notes:[{t:"I'd rather not ~",k:"grammar",m:"~ 하지 않는 편이 좋겠습니다",tip:"거절을 부드럽게 만드는 기본 표현입니다."},
          {t:"a huge bet",k:"idiom",m:"큰 도박, 위험한 베팅",tip:"되돌릴 수 없는 결정을 가리킬 때 씁니다."}]},
  {s:"B",en:"Nobody's asking you to move everything. Move only the parts that stop the line when they're late.",
   ko:"아무도 전부 옮기라고 하지 않습니다. 늦어지면 라인을 멈추게 하는 부품만 옮기세요.",
   notes:[{t:"Nobody's asking you to move everything.",k:"colloquial",m:"아무도 전부 옮기라고 하지 않습니다",tip:"상대가 과장한 요구를 되돌려 놓는 말입니다."},
          {t:"stop the line",k:"idiom",m:"생산 라인을 멈추게 하다",tip:"없으면 전체가 멈추는 병목 부품을 가리킵니다."}]},
  {s:"A",en:"That's maybe six items out of four hundred, which is something I could actually defend.",
   ko:"400개 중 여섯 개쯤이겠네요. 그 정도면 제가 실제로 방어할 수 있습니다.",
   notes:[{t:"I could defend that.",k:"business",m:"그 정도면 (윗선에) 설명해 낼 수 있습니다",tip:"승인받을 자신이 있다는 실무 표현입니다."}]},
  {s:"B",en:"Then start there, and after two quarters let the numbers argue for the rest of them.",
   ko:"그럼 거기서 시작하고, 두 분기가 지나면 나머지는 숫자가 대신 말하게 두세요.",
   notes:[{t:"let the numbers argue",k:"idiom",m:"숫자가 대신 설득하게 하다",tip:"작게 시작해 실적으로 확대하자는 제안입니다."}]},
  {s:"A",en:"One thing first. If it turns out that cheaper was right all along, we go back.",
   ko:"먼저 하나만요. 결국 싼 쪽이 내내 옳았던 걸로 드러나면, 우리는 되돌립니다.",
   notes:[{t:"If it turns out ~",k:"grammar",m:"~ 로 밝혀지면",tip:"결과가 드러난 뒤를 가정하는 형태입니다. turn out = 알고 보니 ~ 이다."}]},
  {s:"B",en:"Agreed, and put a date on that review, because otherwise it simply never happens.",
   ko:"동의합니다. 그리고 그 검토에 날짜를 못 박으세요. 안 그러면 그냥 영영 안 하게 되니까요.",
   notes:[{t:"put a date on it",k:"idiom",m:"날짜를 못 박다",tip:"막연한 합의를 실행 가능한 약속으로 바꾸는 말입니다."},
          {t:"Otherwise it never happens.",k:"colloquial",m:"안 그러면 결국 안 하게 됩니다",tip:"현실적인 경고를 짧게 던지는 마무리입니다."}]}
 ],
 keys:[
  {en:"Point taken.",ko:"일리 있습니다, 인정합니다",ex:"Point taken, but the cost still has to be paid by someone."},
  {en:"an expensive assumption",ko:"대가가 큰 전제",ex:"Assuming the border stays open is an expensive assumption."},
  {en:"lead time",ko:"주문에서 납품까지 걸리는 시간",ex:"We cut lead time from eleven weeks to two."},
  {en:"price something",ko:"~에 값을 매기다",ex:"Nobody has priced what a missed season actually costs us."},
  {en:"the other side of the ledger",ko:"장부의 드러나지 않는 쪽",ex:"Cheap always wins because the other side of the ledger is invisible."},
  {en:"stop the line",ko:"생산 라인을 멈추게 하다",ex:"Localize only the parts that stop the line."},
  {en:"let the numbers argue",ko:"숫자가 대신 설득하게 하다",ex:"Start small and let the numbers argue for the rest."},
  {en:"put a date on it",ko:"날짜를 못 박다",ex:"Agree to review it, and put a date on it."}
 ],
 out:[
  {q:"Explain why your company sourced offshore, and what changed.",hint:"make it cheapest / It worked, until ~ / miss the season"},
  {q:"Argue that paying more to produce locally is insurance, not waste.",hint:"an expensive assumption / price something / the other side of the ledger"},
  {q:"Propose a small first step instead of moving everything.",hint:"stop the line / let the numbers argue / put a date on it"}
 ]
},
{
 id:"w3d7", day:22, cat:"심리·정체성", level:"B2+",
 title:"The Person You Invent",
 titleKo:"우리가 만들어 내는 또 하나의 나 — 가면과 정체성",
 names:{A:"Ren (작가)", B:"Iris (임상심리 전공)"},
 brief:[
  "「파이트 클럽」이 오래 회자되는 이유는 반전 때문만이 아닙니다. 사람들이 <b>자기가 되고 싶었던 인물을 만들어 내고, 결국 그쪽에 끌려다니는</b> 경험을 어렴풋이 알고 있기 때문입니다.",
  "심리학은 이것을 훨씬 조심스럽게 다룹니다. 임상적 해리 장애는 드물고, 대개 심각한 외상과 연결됩니다. 반면 <b>상황마다 다른 얼굴을 쓰는 것</b>은 병이 아니라 거의 모든 사람이 하는 일입니다.",
  "그래서 흥미로운 질문은 「가면을 쓰는가」가 아닙니다. <b>가면을 벗을 수 있는가</b>, 그리고 <b>여러 얼굴이 서로를 알고 있는가</b>입니다. 회사에서의 나와 집에서의 나가 서로를 부끄러워하기 시작하면 문제가 됩니다.",
  "이 대화는 <b>영화 이야기에서 시작해 자기 이야기로 내려가는</b> 전형적인 영어 대화의 흐름을 담고 있습니다. 소재를 바꿔도 그대로 쓸 수 있는 문장들이 많으니, 흐름 자체를 통째로 익혀 두세요."
 ],
 lines:[
  {s:"A",en:"I rewatched Fight Club last night, and it landed completely differently from how I remembered it.",
   ko:"어젯밤에 파이트 클럽을 다시 봤는데, 기억하던 것과는 완전히 다르게 다가왔어요.",
   notes:[{t:"it landed differently",k:"idiom",m:"다르게 다가왔다, 느낌이 달랐다",tip:"작품이나 말이 받아들여진 방식을 말합니다. That joke didn't land."},
          {t:"rewatch",k:"collocation",m:"다시 보다",tip:"re- 접두사는 read, run, write 등에 자유롭게 붙습니다."}]},
  {s:"B",en:"At twenty it's a fantasy about freedom, and later on it reads as a warning.",
   ko:"스무 살에는 자유에 대한 판타지죠. 나이가 들면 경고문으로 읽히고요.",
   notes:[{t:"it reads as ~",k:"grammar",m:"~ 로 읽힌다",tip:"작품이나 문서의 인상을 말하는 수동적 표현입니다."},
          {t:"a warning",k:"collocation",m:"경고, 경고 사례",tip:"a cautionary tale 도 같은 맥락에서 자주 쓰입니다."}]},
  {s:"A",en:"What struck me is that he doesn't invent a stranger at all, he invents himself.",
   ko:"인상 깊었던 건, 그가 낯선 사람을 만드는 게 전혀 아니라 자기 자신을 만든다는 점이에요.",
   notes:[{t:"What struck me is that ~",k:"grammar",m:"제게 인상 깊었던 건 ~ 라는 점입니다",tip:"감상을 앞세우는 아주 유용한 도입 형태입니다."}]},
  {s:"B",en:"He invents the version he wishes he were, which is what makes it uncomfortable to watch.",
   ko:"자기가 그랬으면 하는 버전을 만들어 내죠. 그래서 보기가 불편한 겁니다.",
   notes:[{t:"the version he wishes he were",k:"grammar",m:"그가 그랬으면 하는 버전",tip:"wish + 과거형은 현재의 반대되는 소망입니다."},
          {t:"uncomfortable to watch",k:"collocation",m:"보기 불편한",tip:"hard to watch 보다 조금 더 심리적인 뉘앙스입니다."}]},
  {s:"A",en:"So is that what a split personality actually looks like for people who really have one?",
   ko:"그럼 실제로 다중 인격이 있는 사람에게는 그게 정말 그런 모습으로 나타나나요?",
   notes:[{t:"Is that what X looks like?",k:"grammar",m:"X가 실제로 그런 모습입니까",tip:"비유를 현실과 대조하며 묻는 형태입니다."}]},
  {s:"B",en:"Not really, no. The clinical version is rare and it's usually rooted in serious trauma.",
   ko:"사실은 아닙니다. 임상적인 쪽은 드물고, 대개 심각한 외상에 뿌리를 두고 있어요.",
   notes:[{t:"Not really, no.",k:"colloquial",m:"사실은 아닙니다",tip:"부드럽게 부정하고 설명을 이어 가는 구어입니다."},
          {t:"rooted in ~",k:"idiom",m:"~ 에 뿌리를 둔",tip:"원인을 깊은 곳에 두는 표현입니다. rooted in fear / in history."}]},
  {s:"A",en:"Then why does everybody seem to recognize something in it? That can't be a coincidence.",
   ko:"그런데 왜 다들 거기서 뭔가를 알아보는 것 같을까요? 우연일 리는 없잖아요.",
   notes:[{t:"That can't be a coincidence.",k:"colloquial",m:"우연일 리 없습니다",tip:"패턴을 발견했다고 주장할 때의 짧은 문장입니다."}]},
  {s:"B",en:"Because switching faces is completely ordinary, and you're not the same person at work as at home.",
   ko:"얼굴을 바꿔 쓰는 게 지극히 평범한 일이니까요. 회사에서의 당신과 집에서의 당신은 같은 사람이 아니죠.",
   notes:[{t:"switch faces",k:"idiom",m:"상황에 따라 다른 얼굴을 쓰다",tip:"가면을 바꾸는 이미지입니다. wear a different hat 도 비슷합니다."},
          {t:"ordinary",k:"business",m:"평범한, 흔한",tip:"normal보다 「특별할 것 없다」는 뉘앙스가 강합니다."}]},
  {s:"A",en:"I'd argue that's just manners, though, since everyone adjusts to the room they happen to be in.",
   ko:"그건 그냥 예의 아닌가요. 누구나 자기가 들어간 자리의 분위기에 맞추잖아요.",
   notes:[{t:"I'd argue that ~",k:"business",m:"저라면 ~ 라고 보겠습니다",tip:"단정 대신 자기 견해임을 밝히는 정중한 반박입니다."},
          {t:"adjust to the room",k:"idiom",m:"자리 분위기에 맞추다",tip:"read the room(분위기를 읽다)과 짝으로 익혀 두세요."}]},
  {s:"B",en:"It is, right up to the point where you find that you can't take the mask off.",
   ko:"맞습니다. 가면이 벗겨지지 않는다는 걸 알게 되는 지점 전까지는요.",
   notes:[{t:"right up to the point where ~",k:"grammar",m:"~ 하는 지점 바로 전까지는",tip:"동의한 뒤 한계선을 긋는 강력한 형태입니다."},
          {t:"take the mask off",k:"idiom",m:"가면을 벗다",tip:"put on a mask 와 짝으로 씁니다."}]},
  {s:"A",en:"But how would I even notice that happening, when it wouldn't feel like a mask to me?",
   ko:"그런데 그게 벌어지는 걸 제가 어떻게 알아차리죠? 제겐 가면처럼 느껴지지도 않을 텐데요.",
   notes:[{t:"How would I even notice?",k:"colloquial",m:"그걸 제가 어떻게 알아차리겠어요",tip:"자각의 어려움을 강조하는 반문입니다."}]},
  {s:"B",en:"One sign is embarrassment, specifically when one version of you embarrasses the other one.",
   ko:"한 가지 신호는 부끄러움입니다. 정확히는, 당신의 한쪽이 다른 쪽을 부끄러워할 때죠.",
   notes:[{t:"One sign is ~",k:"grammar",m:"한 가지 신호는 ~ 입니다",tip:"증상이나 징후를 열거할 때의 기본 틀입니다."},
          {t:"embarrass",k:"collocation",m:"부끄럽게 만들다",tip:"주어가 원인, 목적어가 사람입니다. It embarrasses me."}]},
  {s:"A",en:"That's uncomfortably specific. I've felt exactly that at company dinners more than once.",
   ko:"불편할 만큼 정확하네요. 회식 자리에서 정확히 그걸 느낀 적이 한 번이 아닙니다.",
   notes:[{t:"uncomfortably specific",k:"idiom",m:"불편할 만큼 정확히 들어맞는",tip:"상대의 지적이 뼈아플 때 쓰는 재치 있는 반응입니다."}]},
  {s:"B",en:"Most people have. The question is whether the two sides ever talk to each other.",
   ko:"대부분 그렇습니다. 문제는 그 두 쪽이 서로 대화를 하기는 하느냐죠.",
   notes:[{t:"The question is whether ~",k:"grammar",m:"문제는 ~ 인지 여부입니다",tip:"쟁점을 정확히 재정의하는 문장입니다."}]},
  {s:"A",en:"Mine don't, I think. They just take turns and then pretend that nothing happened.",
   ko:"제 경우엔 안 하는 것 같아요. 그냥 번갈아 나오고는 아무 일 없던 척합니다.",
   notes:[{t:"take turns",k:"collocation",m:"번갈아 하다",tip:"take turns speaking / take turns driving."},
          {t:"pretend nothing happened",k:"idiom",m:"아무 일 없던 척하다",tip:"외면의 태도를 짧게 표현합니다."}]},
  {s:"B",en:"Then start naming them. It sounds silly, but a name is what makes them negotiable.",
   ko:"그럼 이름을 붙여 보세요. 우스워 보여도, 그것들을 협상 가능하게 만드는 게 바로 이름이거든요.",
   notes:[{t:"It sounds silly, but ~",k:"colloquial",m:"우스워 보이겠지만 ~",tip:"저항이 예상되는 조언을 꺼낼 때의 완충 표현입니다."},
          {t:"negotiable",k:"business",m:"협상 가능한, 조정할 수 있는",tip:"non-negotiable(양보 불가)과 짝으로 알아 두세요."}]},
  {s:"A",en:"Negotiable how? I can't exactly sit down at a table with a version of myself.",
   ko:"어떻게 협상하죠? 제 다른 버전과 마주 앉을 수는 없는 노릇이잖아요.",
   notes:[{t:"I can't exactly ~",k:"colloquial",m:"~ 할 수는 없는 노릇이죠",tip:"현실적으로 불가능하다고 가볍게 되받는 표현입니다."}]},
  {s:"B",en:"You can decide which one of them gets the evening, and that's already a negotiation.",
   ko:"그중 누가 저녁 시간을 차지할지는 정할 수 있죠. 그것부터가 이미 협상입니다.",
   notes:[{t:"which one gets the evening",k:"idiom",m:"저녁 시간을 누가 차지할지",tip:"추상적인 선택을 시간 배분으로 구체화한 표현입니다."}]},
  {s:"A",en:"So the goal isn't one true self after all. It's a self that stays in charge.",
   ko:"그럼 목표는 결국 하나의 진짜 자아가 아니군요. 주도권을 계속 쥐고 있는 자아네요.",
   notes:[{t:"stay in charge",k:"idiom",m:"주도권을 계속 쥐고 있다",tip:"be in charge(책임지다)의 지속 형태입니다."}]},
  {s:"B",en:"That's the healthier version of it, yes, because Tyler's problem was never really the mask.",
   ko:"그게 더 건강한 쪽이죠. 타일러의 문제는 애초에 가면 자체가 아니었으니까요.",
   notes:[{t:"The problem was never X.",k:"grammar",m:"문제는 애초에 X가 아니었습니다",tip:"오해를 바로잡으며 대화를 닫는 강한 마무리입니다."}]}
 ],
 keys:[
  {en:"it landed differently",ko:"다르게 다가왔다",ex:"I saw it again at forty and it landed completely differently."},
  {en:"What struck me is that ~",ko:"제게 인상 깊었던 건 ~ 라는 점입니다",ex:"What struck me is that he invents the person he wanted to be."},
  {en:"rooted in ~",ko:"~ 에 뿌리를 둔",ex:"The clinical condition is rare and usually rooted in trauma."},
  {en:"switch faces",ko:"상황에 따라 다른 얼굴을 쓰다",ex:"Everyone switches faces; the trouble starts when you can't switch back."},
  {en:"right up to the point where ~",ko:"~ 하는 지점 바로 전까지는",ex:"It's healthy, right up to the point where you can't take the mask off."},
  {en:"The question is whether ~",ko:"문제는 ~ 인지 여부입니다",ex:"The question is whether the two sides talk to each other."},
  {en:"pretend nothing happened",ko:"아무 일 없던 척하다",ex:"They take turns and pretend nothing happened."},
  {en:"stay in charge",ko:"주도권을 계속 쥐고 있다",ex:"The goal isn't one true self, it's a self that stays in charge."}
 ],
 out:[
  {q:"Describe a film you saw again years later and explain what changed.",hint:"rewatch / it landed differently / What struck me is that ~"},
  {q:"Explain the difference between a clinical split and everyday role-switching.",hint:"rooted in ~ / switch faces / right up to the point where ~"},
  {q:"Talk about the different versions of yourself at work and at home.",hint:"adjust to the room / pretend nothing happened / stay in charge"}
 ]
},
{
 id:"w3d8", day:23, cat:"인생·중년", level:"B2+",
 title:"Fewer Doors, Better Rooms",
 titleKo:"문은 줄고 방은 나아진다 — 중년의 위기라는 오해",
 names:{A:"Sang (46, 제조업)", B:"Priya (49, 컨설턴트)"},
 brief:[
  "중년의 위기를 흔히 <b>후회</b>의 문제로 설명합니다. 그러나 겪는 사람들의 말을 들어 보면, 후회보다 자주 나오는 단어는 <b>좁아짐</b>입니다. 예전에는 열려 있던 문들이 하나씩 조용히 닫힙니다.",
  "이십 대에는 <b>아직 아무것도 정해지지 않았다</b>는 감각이 있습니다. 사십 대에는 정해진 것이 많고, 그중 상당수는 되돌리기 어렵습니다. 그 차이가 만들어 내는 불안은 실패가 아니라 <b>산수</b>에서 옵니다.",
  "반대편의 주장도 있습니다. 선택지가 줄어드는 대신 <b>선택의 질</b>이 올라간다는 것입니다. 무엇을 잘하고 무엇을 못하는지 알고, 어떤 사람과 시간을 보내야 하는지 압니다. 스무 살에는 없던 정보입니다.",
  "이 대화는 <b>인생 이야기를 감정적으로 흐르지 않게 말하는 법</b>을 연습하기 좋습니다. 비유(문·방·산수)를 하나 잡고 끝까지 밀고 가는 방식은 영어 대화에서 매우 효과적이니 그대로 가져가 보세요."
 ],
 lines:[
  {s:"A",en:"I keep noticing that far fewer things feel possible now than they did at thirty.",
   ko:"서른 때에 비해 가능해 보이는 일이 훨씬 줄었다는 걸 자꾸 느낍니다.",
   notes:[{t:"I keep noticing that ~",k:"grammar",m:"자꾸 ~ 라는 걸 느낍니다",tip:"keep -ing는 반복되는 자각을 부드럽게 전합니다."},
          {t:"feel possible",k:"collocation",m:"가능하게 느껴지다",tip:"be possible(객관적 가능)과 달리 주관적 감각을 말합니다."}]},
  {s:"B",en:"That's the part nobody warns you about, and it isn't regret, it's arithmetic.",
   ko:"그건 아무도 미리 알려 주지 않는 부분이죠. 그리고 그건 후회가 아니라 산수입니다.",
   notes:[{t:"nobody warns you about it",k:"idiom",m:"아무도 미리 알려 주지 않는다",tip:"경험해야만 아는 일을 가리킵니다."},
          {t:"It isn't A, it's B.",k:"grammar",m:"A가 아니라 B입니다",tip:"오해를 바로잡는 가장 간결한 문장 틀입니다."}]},
  {s:"A",en:"Arithmetic how? By almost any measure I'm doing better now than I was at thirty.",
   ko:"산수라니 무슨 뜻이죠? 거의 어떤 기준으로 봐도 서른 때보다 지금이 나은데요.",
   notes:[{t:"do better than ~",k:"collocation",m:"~ 보다 형편이 낫다",tip:"성과와 상황 양쪽에 씁니다."}]},
  {s:"B",en:"Doing better, yes, but you have half as many years left in which to change direction.",
   ko:"형편은 낫죠. 그런데 방향을 바꿀 수 있는 햇수가 절반밖에 안 남았습니다.",
   notes:[{t:"half as many years",k:"grammar",m:"절반의 햇수",tip:"as many as 비교의 배수 표현입니다. twice as many 도 같은 형태."},
          {t:"change direction",k:"collocation",m:"방향을 바꾸다",tip:"진로나 전략 전환을 말할 때의 표준 표현입니다."}]},
  {s:"A",en:"Put like that, it sounds grim, and I'd rather not count it that way at all.",
   ko:"그렇게 말하니 암울하게 들리네요. 저는 그런 식으로 세고 싶지 않습니다.",
   notes:[{t:"Put like that, ~",k:"grammar",m:"그렇게 말하고 보니 ~",tip:"상대의 표현을 받아 반응하는 자연스러운 도입입니다."},
          {t:"grim",k:"business",m:"암울한, 우울한",tip:"전망을 말할 때 자주 씁니다. a grim outlook."}]},
  {s:"B",en:"You don't have to, but the doors do close, whether we bother counting them or not.",
   ko:"안 세셔도 됩니다. 다만 우리가 굳이 세든 안 세든 문은 닫혀요.",
   notes:[{t:"whether we count them or not",k:"grammar",m:"우리가 세든 안 세든",tip:"whether A or not은 어느 쪽이든 결과가 같음을 말합니다."}]},
  {s:"A",en:"Some of them I closed myself, though, because I chose this job and this city.",
   ko:"그중 일부는 제가 닫은 겁니다. 이 일도 이 도시도 제가 골랐으니까요.",
   notes:[{t:"close a door",k:"idiom",m:"가능성을 닫다",tip:"open doors(기회를 열다)와 짝을 이룹니다."}]},
  {s:"B",en:"That's the healthier way to look at it, because a closed door you chose is a decision.",
   ko:"그게 더 건강한 관점입니다. 내가 골라서 닫은 문은 결정이니까요.",
   notes:[{t:"the healthier way to look at it",k:"collocation",m:"그것을 보는 더 건강한 방식",tip:"관점을 제안하는 정중한 표현입니다."}]},
  {s:"A",en:"And what about the ones I didn't choose? Those are the ones that keep me up at night.",
   ko:"그럼 제가 고르지 않은 문들은요? 밤에 저를 잠 못 들게 하는 건 그쪽입니다.",
   notes:[{t:"keep someone up",k:"idiom",m:"잠 못 이루게 하다",tip:"It's what keeps me up at night. 걱정거리를 말하는 관용구입니다."}]},
  {s:"B",en:"Name one, because it's far easier to argue with a specific door than with a vague feeling.",
   ko:"하나만 대 보세요. 막연한 기분보다 구체적인 문 하나가 훨씬 다투기 쉬우니까요.",
   notes:[{t:"Name one.",k:"colloquial",m:"하나만 말해 보세요",tip:"막연한 주장에 구체성을 요구하는 짧은 요구입니다."},
          {t:"argue with a feeling",k:"idiom",m:"막연한 감정과 씨름하다",tip:"감정을 논증 대상으로 삼는 재치 있는 비유입니다."}]},
  {s:"A",en:"Starting something of my own, which I told myself I'd have done by forty.",
   ko:"제 사업을 시작하는 거요. 마흔 전에는 해 놓겠다고 스스로 말했었죠.",
   notes:[{t:"something of my own",k:"idiom",m:"내 것, 내 사업",tip:"a business of my own 을 줄여 말하는 자연스러운 표현입니다."},
          {t:"I told myself I'd ~",k:"grammar",m:"~ 하겠다고 스스로 다짐했었다",tip:"지키지 못한 다짐을 말할 때의 형태입니다."}]},
  {s:"B",en:"Forty was a number that you picked, not a rule that anybody handed you.",
   ko:"마흔은 본인이 고른 숫자지, 누가 건네준 규칙이 아닙니다.",
   notes:[{t:"a number you picked",k:"idiom",m:"본인이 임의로 정한 숫자",tip:"자의적인 기준을 지적하는 표현입니다."}]},
  {s:"A",en:"True, though starting now means starting with a mortgage and two children to feed.",
   ko:"맞습니다. 다만 지금 시작한다는 건 대출과 먹여야 할 아이 둘을 안고 시작한다는 뜻이죠.",
   notes:[{t:"Though ~",k:"grammar",m:"다만 ~ 입니다",tip:"앞 문장을 인정한 뒤 단서를 붙이는 접속사입니다."},
          {t:"a mortgage",k:"business",m:"주택 담보 대출",tip:"중년의 재정 제약을 말할 때 거의 반드시 나옵니다."}]},
  {s:"B",en:"It also means starting with customers, credit, and twenty years of judgment you didn't have then.",
   ko:"그건 고객과 신용, 그리고 그때는 없던 20년의 판단력을 안고 시작한다는 뜻이기도 합니다.",
   notes:[{t:"It also means ~",k:"grammar",m:"그것은 또한 ~ 라는 뜻이기도 합니다",tip:"같은 사실의 반대 면을 제시하는 형태입니다."},
          {t:"judgment",k:"business",m:"판단력",tip:"경험에서 오는 무형 자산을 가리키는 단어입니다."}]},
  {s:"A",en:"I hadn't weighed that side of it properly, and it does change the math a little.",
   ko:"그쪽은 제대로 저울에 올리지 않았네요. 그러고 보니 계산이 조금 달라지긴 합니다.",
   notes:[{t:"weigh something",k:"business",m:"저울질하다, 따져 보다",tip:"weigh the risks / weigh both sides."},
          {t:"change the math",k:"idiom",m:"셈이 달라지다",tip:"결론을 뒤집는 새 변수를 말합니다."}]},
  {s:"B",en:"Fewer doors, better rooms. That's the trade that nobody bothers to explain at twenty.",
   ko:"문은 줄고 방은 나아진다. 스무 살에는 아무도 굳이 설명해 주지 않는 거래죠.",
   notes:[{t:"the trade",k:"business",m:"맞바꿈, 트레이드오프",tip:"얻는 것과 잃는 것을 한 단어로 압축합니다."}]},
  {s:"A",en:"That's a nicer framing, but is it actually true or is it just comforting?",
   ko:"표현은 근사한데, 그게 실제로 사실인가요 아니면 그냥 위로인가요?",
   notes:[{t:"framing",k:"business",m:"틀 짓기, 표현 방식",tip:"같은 사실을 다르게 제시하는 방식입니다."},
          {t:"true or just comforting",k:"collocation",m:"사실인가 그저 위안인가",tip:"위안에 속지 않겠다는 태도를 짧게 드러냅니다."}]},
  {s:"B",en:"Test it, then. Would you trade the judgment you have now for your options at twenty-five?",
   ko:"그럼 시험해 보세요. 지금 가진 판단력을 스물다섯의 선택지와 바꾸시겠습니까?",
   notes:[{t:"Would you trade A for B?",k:"grammar",m:"A를 B와 바꾸시겠습니까",tip:"가치를 비교하게 만드는 아주 강한 질문입니다."}]},
  {s:"A",en:"Honestly, no. I'd keep the judgment and go on complaining about the doors.",
   ko:"솔직히 아니요. 판단력은 그대로 갖고, 문에 대해선 계속 투덜대겠습니다.",
   notes:[{t:"Honestly, no.",k:"colloquial",m:"솔직히 아닙니다",tip:"자기 인식을 드러내며 솔직해지는 짧은 답입니다."}]},
  {s:"B",en:"Then you're not in a crisis at all. You're just adjusting to a smaller map.",
   ko:"그럼 위기 같은 건 아닙니다. 더 작아진 지도에 적응하는 중일 뿐이죠.",
   notes:[{t:"adjust to ~",k:"collocation",m:"~ 에 적응하다",tip:"상황 변화에 맞춰 자신을 조정하는 것입니다."},
          {t:"a smaller map",k:"idiom",m:"좁아진 지도, 줄어든 선택지",tip:"비유를 마지막에 새로 던져 대화를 닫습니다."}]}
 ],
 keys:[
  {en:"It isn't A, it's B.",ko:"A가 아니라 B입니다",ex:"It isn't regret, it's arithmetic."},
  {en:"change direction",ko:"방향을 바꾸다",ex:"You have half as many years left to change direction."},
  {en:"close a door",ko:"가능성을 닫다",ex:"A closed door you chose yourself is a decision, not a loss."},
  {en:"keep someone up",ko:"잠 못 이루게 하다",ex:"The choices I never made are the ones that keep me up."},
  {en:"Name one.",ko:"하나만 말해 보세요",ex:"Name one, because a specific door is easier to argue with."},
  {en:"weigh something",ko:"저울질하다, 따져 보다",ex:"I hadn't weighed that side of it properly."},
  {en:"change the math",ko:"셈이 달라지다",ex:"Twenty years of judgment does change the math."},
  {en:"Would you trade A for B?",ko:"A를 B와 바꾸시겠습니까",ex:"Would you trade your judgment now for your options at twenty-five?"}
 ],
 out:[
  {q:"Describe how your sense of possibility has changed since your twenties.",hint:"I keep noticing that ~ / feel possible / close a door"},
  {q:"Argue that a midlife crisis is arithmetic rather than regret.",hint:"It isn't A, it's B / change direction / keep someone up"},
  {q:"Make the case that fewer options can mean better decisions.",hint:"judgment / change the math / Would you trade A for B?"}
 ]
},
{
 id:"w3d9", day:24, cat:"문화·스타일", level:"B2+",
 title:"Why Italians Dress Well",
 titleKo:"이탈리아 남자들은 왜 옷을 잘 입는가 — 스프레차투라의 경제학",
 names:{A:"Marco (밀라노 출신)", B:"Joon (서울, 패션 무관심)"},
 brief:[
  "「이탈리아 남자는 옷을 잘 입는다」는 말은 흔하지만, 설명은 대개 취향 이야기에서 멈춥니다. 실제 이유의 상당 부분은 <b>산업</b>에 있습니다. 이탈리아 북부는 수백 년 동안 유럽의 직물 생산지였습니다.",
  "좋은 원단이 가까이 있으면 <b>옷값의 구조</b>가 달라집니다. 재단사가 많고, 수선이 싸고, 좋은 옷을 오래 입는 것이 합리적인 선택이 됩니다. 취향은 그 위에서 자랍니다.",
  "여기에 <b>스프레차투라</b>라는 개념이 붙습니다. 애써 노력한 티가 나지 않게 잘 해내는 태도입니다. 옷에서는 「신경 쓴 티 안 나게 신경 쓴」 상태를 뜻합니다. 이 개념 자체가 아주 좋은 영어 대화 소재입니다.",
  "이 대화는 <b>문화적 일반화를 조심스럽게 다루는 법</b>도 함께 연습합니다. 「~ 하는 경향이 있다」, 「그건 과장이다」 같은 표현을 익혀 두면, 국가나 세대를 두고 이야기할 때 훨씬 안전하고 설득력 있게 말할 수 있습니다."
 ],
 lines:[
  {s:"A",en:"You keep saying that Italian men dress well, which is a bit of a cliche.",
   ko:"이탈리아 남자들이 옷을 잘 입는다고 자꾸 말씀하시는데, 그건 좀 상투적인 얘기죠.",
   notes:[{t:"a cliche",k:"business",m:"상투적인 말, 뻔한 이야기",tip:"일반화를 부드럽게 견제할 때 씁니다."},
          {t:"a bit of a ~",k:"colloquial",m:"좀 ~ 한 편이다",tip:"비판을 약하게 만드는 완충 표현입니다."}]},
  {s:"B",en:"Maybe, but cliches usually start somewhere, so where does that particular one come from?",
   ko:"그럴 수도요. 그런데 상투적인 말도 대개 어딘가에서 시작하잖아요. 그건 어디서 온 겁니까?",
   notes:[{t:"Cliches start somewhere.",k:"idiom",m:"뻔한 말에도 근거는 있다",tip:"일반화를 완전히 버리지 않고 근거를 찾는 태도입니다."},
          {t:"Where does it come from?",k:"grammar",m:"그것은 어디서 비롯되었습니까",tip:"기원을 묻는 가장 간단한 질문입니다."}]},
  {s:"A",en:"Honestly, from textiles, because northern Italy has been making cloth for six hundred years.",
   ko:"솔직히 직물에서 왔습니다. 북부 이탈리아는 600년째 천을 만들어 오고 있으니까요.",
   notes:[{t:"textiles",k:"business",m:"직물, 섬유 산업",tip:"산업을 가리킬 때는 보통 복수형으로 씁니다."}]},
  {s:"B",en:"I'd never have connected the two. So it's industry before it's ever a matter of taste?",
   ko:"둘을 연결해 볼 생각을 못 했네요. 그럼 취향 문제이기 이전에 산업이라는 건가요?",
   notes:[{t:"I'd never have connected the two.",k:"colloquial",m:"둘을 연결해 볼 생각을 못 했습니다",tip:"새 관점에 감탄할 때의 자연스러운 반응입니다."},
          {t:"A before B",k:"grammar",m:"B 이전에 A",tip:"우선순위나 인과 순서를 압축해 말합니다."}]},
  {s:"A",en:"Largely, yes. When good cloth is made locally, a good jacket stops being anything exotic.",
   ko:"대체로 그렇습니다. 좋은 천을 동네에서 만들면, 좋은 재킷이 특별한 물건이기를 그만두죠.",
   notes:[{t:"Largely, yes.",k:"colloquial",m:"대체로 그렇습니다",tip:"전면 동의를 피하면서 긍정하는 답입니다."},
          {t:"stop being exotic",k:"idiom",m:"특별한 것이 아니게 되다",tip:"희소성이 사라지는 상황을 표현합니다."}]},
  {s:"B",en:"That makes sense economically, since cheap access quietly changes what counts as normal.",
   ko:"경제적으로 말이 되네요. 접근이 싸지면 무엇이 평범한지가 조용히 바뀌니까요.",
   notes:[{t:"what counts as normal",k:"grammar",m:"무엇이 평범한 것으로 통하는가",tip:"count as는 「~ 로 여겨지다」입니다."},
          {t:"access",k:"business",m:"접근성, 이용 가능성",tip:"access to capital / access to good cloth."}]},
  {s:"A",en:"And tailors stayed cheap, which is why people repair clothes instead of replacing them.",
   ko:"그리고 재단사가 계속 쌌고, 그래서 사람들이 옷을 바꾸는 대신 고쳐 입는 겁니다.",
   notes:[{t:"repair instead of replace",k:"collocation",m:"교체하는 대신 수선하다",tip:"소비 태도를 대조하는 유용한 짝입니다."}]},
  {s:"B",en:"In Seoul, altering a jacket sometimes costs more than the jacket itself did.",
   ko:"서울에서는 재킷 수선비가 재킷값보다 비쌀 때도 있어요.",
   notes:[{t:"alter",k:"business",m:"(옷을) 고치다, 수선하다",tip:"alteration(수선)이 명사형입니다."},
          {t:"more than X sometimes does",k:"grammar",m:"때로는 X보다 더",tip:"비교문에 sometimes를 끼워 과장을 피합니다."}]},
  {s:"A",en:"Then of course nobody learns to care, because the habit only survives on cheap repair.",
   ko:"그럼 당연히 아무도 신경 쓰는 법을 안 배우죠. 그 습관은 싼 수선 위에서만 살아남으니까요.",
   notes:[{t:"Then of course ~",k:"colloquial",m:"그럼 당연히 ~ 하죠",tip:"상대 말에서 결론을 끌어내는 리듬입니다."}]},
  {s:"B",en:"So what's the part that isn't economics? There must be something cultural underneath it.",
   ko:"그럼 경제가 아닌 부분은 뭔가요? 그 밑에 문화적인 무언가가 있을 텐데요.",
   notes:[{t:"the part that isn't X",k:"grammar",m:"X가 아닌 부분",tip:"설명을 한 요인에 가두지 않도록 되묻는 형태입니다."},
          {t:"There must be ~",k:"grammar",m:"~ 이 있을 것입니다",tip:"추론을 나타내는 must입니다."}]},
  {s:"A",en:"There's a word for it here. Sprezzatura, roughly, means the kind of effort that doesn't show.",
   ko:"그걸 가리키는 말이 있습니다. 스프레차투라, 대충 말하면 티가 나지 않는 종류의 노력이죠.",
   notes:[{t:"There's a word for it.",k:"colloquial",m:"그걸 가리키는 말이 있습니다",tip:"개념을 소개할 때의 자연스러운 도입입니다."},
          {t:"roughly",k:"business",m:"대략, 대충 말하면",tip:"정의가 완벽하지 않음을 미리 밝힙니다."}]},
  {s:"B",en:"That sounds exhausting, actually, because hiding the effort is just extra effort on top.",
   ko:"사실 피곤하게 들리는데요. 노력을 숨기는 건 그 위에 노력을 더 얹는 거잖아요.",
   notes:[{t:"That sounds exhausting.",k:"colloquial",m:"그거 피곤하게 들리는데요",tip:"솔직한 반응으로 대화에 온도를 넣습니다."},
          {t:"extra effort",k:"collocation",m:"추가적인 수고",tip:"말장난처럼 반박을 만드는 좋은 짝입니다."}]},
  {s:"A",en:"It is, and Italians would never admit it. The trick is looking completely unbothered.",
   ko:"맞습니다. 그리고 이탈리아 사람들은 절대 인정 안 하죠. 요령은 전혀 신경 안 쓴 듯 보이는 겁니다.",
   notes:[{t:"The trick is ~ing",k:"grammar",m:"요령은 ~ 하는 것입니다",tip:"비결을 설명하는 실용적인 형태입니다."},
          {t:"unbothered",k:"colloquial",m:"신경 쓰지 않는 듯한",tip:"의도적으로 무심해 보이는 태도입니다."}]},
  {s:"B",en:"We have a version of that too, which is looking like you simply woke up that way.",
   ko:"우리도 비슷한 게 있어요. 그냥 자고 일어나니 그렇더라는 얼굴 말이죠.",
   notes:[{t:"a version of that",k:"collocation",m:"그와 비슷한 것",tip:"문화 비교에서 아주 자주 쓰는 표현입니다."}]},
  {s:"A",en:"Then you already understand it perfectly. You just haven't spent any money on it yet.",
   ko:"그럼 이미 완벽히 이해하고 계신 겁니다. 아직 거기에 돈을 안 쓰셨을 뿐이죠.",
   notes:[{t:"You just haven't ~",k:"grammar",m:"다만 아직 ~ 하지 않았을 뿐입니다",tip:"능력이 아니라 선택의 문제로 돌리는 표현입니다."}]},
  {s:"B",en:"Where would I even start? I own four shirts and every one of them is identical.",
   ko:"어디서부터 시작하죠? 셔츠 네 벌이 있는데 하나같이 똑같이 생겼어요.",
   notes:[{t:"Where would I even start?",k:"colloquial",m:"대체 어디서부터 시작하죠",tip:"막막함을 유머로 표현하는 질문입니다."}]},
  {s:"A",en:"Start with fit, not brands, because a cheap jacket that fits beats an expensive one that doesn't.",
   ko:"브랜드가 아니라 핏부터 하세요. 잘 맞는 싼 재킷이, 안 맞는 비싼 재킷보다 나으니까요.",
   notes:[{t:"fit, not brands",k:"collocation",m:"브랜드가 아니라 핏",tip:"A, not B로 우선순위를 뒤집습니다."},
          {t:"X beats Y",k:"idiom",m:"X가 Y보다 낫다",tip:"구어에서 우열을 짧게 말하는 동사입니다."}]},
  {s:"B",en:"That's much cheaper advice than I was expecting from somebody who grew up in Milan.",
   ko:"밀라노에서 자란 분에게서 기대한 것보다 훨씬 싼 조언이네요.",
   notes:[{t:"cheaper advice than I expected",k:"collocation",m:"기대보다 저렴한 조언",tip:"비교급으로 가볍게 농담을 만듭니다."}]},
  {s:"A",en:"Because the expensive part was never really the clothes at all. It was the tailor.",
   ko:"비싼 건 애초에 옷이 전혀 아니었으니까요. 재단사였죠.",
   notes:[{t:"The expensive part was never X.",k:"grammar",m:"비싼 것은 애초에 X가 아니었습니다",tip:"오해를 뒤집으며 핵심을 짚는 문장입니다."}]},
  {s:"B",en:"Fine, I'll find one, though I refuse to look unbothered about the whole business.",
   ko:"좋습니다, 한 명 찾아보죠. 다만 이 일 전체에 무심한 척하는 건 거부하겠습니다.",
   notes:[{t:"I refuse to ~",k:"grammar",m:"~ 하기를 거부합니다",tip:"가볍게 농담조로 선을 긋는 표현입니다."}]}
 ],
 keys:[
  {en:"a cliche",ko:"상투적인 말, 뻔한 이야기",ex:"It's a cliche, but cliches usually start somewhere."},
  {en:"what counts as normal",ko:"무엇이 평범한 것으로 통하는가",ex:"Cheap access changes what counts as normal."},
  {en:"repair instead of replace",ko:"교체하는 대신 수선하다",ex:"When tailors are cheap, people repair instead of replace."},
  {en:"the part that isn't X",ko:"X가 아닌 부분",ex:"So what's the part that isn't economics?"},
  {en:"There's a word for it.",ko:"그걸 가리키는 말이 있습니다",ex:"There's a word for it — effort that doesn't show."},
  {en:"The trick is ~ing",ko:"요령은 ~ 하는 것입니다",ex:"The trick is looking unbothered while caring a great deal."},
  {en:"X beats Y",ko:"X가 Y보다 낫다",ex:"A cheap jacket that fits beats an expensive one that doesn't."},
  {en:"a version of that",ko:"그와 비슷한 것",ex:"We have a version of that here, we just call it something else."}
 ],
 out:[
  {q:"Explain a national reputation you think has a practical, industrial cause.",hint:"a cliche / textiles / A before B"},
  {q:"Describe how the cost of repair changes how people treat their things.",hint:"repair instead of replace / what counts as normal / alter"},
  {q:"Explain 'sprezzatura' to someone, then say whether you buy it.",hint:"There's a word for it / The trick is ~ing / That sounds exhausting"}
 ]
},
{
 id:"w3d10", day:25, cat:"사상·미래", level:"C1",
 title:"When Abundance Stops Being the Plan",
 titleKo:"풍요가 더 이상 계획이 아닐 때 — 희소성의 정치학",
 names:{A:"Elena (정치철학 연구자)", B:"Tomas (테크 업계)"},
 brief:[
  "전후 70년의 기본 가정은 <b>파이가 계속 커진다</b>는 것이었습니다. 성장하면 나눌 것이 늘고, 그러면 분배 논쟁도 견딜 만해집니다. 민주주의의 여유는 상당 부분 이 가정 위에 있었습니다.",
  "최근 몇 년, 그 가정을 <b>내려놓은 사람들</b>이 눈에 띕니다. 에너지, 인구, 반도체, 물처럼 늘리기 어려운 것들을 앞세우며, 성장이 아니라 <b>확보</b>를 말합니다. 파이가 고정이라면 논리적 귀결은 「내 몫을 지키는 것」입니다.",
  "여기서 한 걸음 더 나간 흐름이 <b>다크 인라이튼먼트</b>로 불리는 사상입니다. 민주적 절차가 느리고 비효율적이니 유능한 소수가 결정해야 한다는 주장입니다. 소수의 견해지만, 영향력 있는 곳에서 인용된다는 점이 논쟁거리입니다.",
  "이 대화의 목적은 편을 정하는 것이 아니라, <b>불편한 사상을 정확하게 요약하고 반박하는 영어</b>를 익히는 것입니다. 「그 논리를 끝까지 밀면 어떻게 되는가」를 묻는 문장들에 특히 주목하세요."
 ],
 lines:[
  {s:"A",en:"For seventy years we could argue about distribution precisely because we all assumed growth.",
   ko:"70년 동안 우리가 분배를 두고 다툴 수 있었던 건, 바로 다들 성장을 전제했기 때문입니다.",
   notes:[{t:"assume growth",k:"business",m:"성장을 전제하다",tip:"경제 논의의 숨은 전제를 드러내는 표현입니다."}]},
  {s:"B",en:"And a number of people in my industry have quietly stopped assuming it at all.",
   ko:"그런데 제 업계 사람 상당수는 그 전제를 아예 조용히 버렸습니다.",
   notes:[{t:"quietly stop ~ing",k:"idiom",m:"조용히 ~ 하기를 그만두다",tip:"공표 없이 입장이 바뀐 상황을 나타냅니다."}]},
  {s:"A",en:"Stopped on what evidence? Growth has certainly slowed, but it hasn't actually stopped anywhere.",
   ko:"무슨 근거로 버렸죠? 성장이 둔화된 건 분명하지만, 어디서도 실제로 멈추지는 않았습니다.",
   notes:[{t:"On what evidence?",k:"business",m:"무슨 근거로요",tip:"주장에 증거를 요구하는 짧고 강한 질문입니다."}]},
  {s:"B",en:"Energy, water, chips, and people, which are four things you can't simply decide to have more of.",
   ko:"에너지, 물, 반도체, 사람이요. 더 갖기로 마음먹는다고 되는 게 아닌 넷입니다.",
   notes:[{t:"things you can't decide to have more of",k:"grammar",m:"마음먹는다고 늘릴 수 없는 것들",tip:"전치사가 뒤로 밀린 관계절입니다. 구어에서 자연스럽습니다."}]},
  {s:"A",en:"Those are real constraints, but that doesn't make the pie permanently fixed in size.",
   ko:"실제 제약인 건 맞습니다. 그렇다고 파이 크기가 영구히 고정되는 건 아니죠.",
   notes:[{t:"That doesn't make X ~",k:"grammar",m:"그렇다고 X가 ~ 이 되는 건 아닙니다",tip:"성급한 결론을 끊는 매우 유용한 반박입니다."}]},
  {s:"B",en:"No, but if you believe that it might be, your whole strategy changes overnight.",
   ko:"아니죠. 그런데 그럴 수도 있다고 믿으면, 전략 전체가 하룻밤에 바뀝니다.",
   notes:[{t:"if you believe it might be",k:"grammar",m:"그럴 수도 있다고 믿는다면",tip:"사실이 아니라 믿음이 행동을 바꾼다는 논지입니다."}]},
  {s:"A",en:"Changes to what, concretely? I want to hear the actual policy, not the mood behind it.",
   ko:"구체적으로 뭘로 바뀌는데요? 그 뒤에 깔린 분위기 말고 실제 정책을 듣고 싶습니다.",
   notes:[{t:"concretely",k:"business",m:"구체적으로",tip:"막연한 답을 차단하는 부사입니다."},
          {t:"the actual policy, not the mood",k:"idiom",m:"분위기가 아니라 실제 정책",tip:"추상을 걷어 내라는 요구를 압축했습니다."}]},
  {s:"B",en:"Securing supply rather than expanding it, which means owning the input instead of the market.",
   ko:"공급을 늘리기보다 확보하는 겁니다. 시장이 아니라 원재료를 갖는다는 뜻이죠.",
   notes:[{t:"secure rather than expand",k:"collocation",m:"늘리기보다 확보하다",tip:"희소성 전략의 핵심을 두 동사로 대비합니다."}]},
  {s:"A",en:"Push that logic a little further and you arrive somewhere that's politically very uncomfortable.",
   ko:"그 논리를 조금만 더 밀면, 정치적으로 아주 불편한 자리에 도착합니다.",
   notes:[{t:"Push that logic further",k:"idiom",m:"그 논리를 끝까지 밀어 보다",tip:"상대 주장의 귀결을 따져 묻는 강력한 표현입니다."},
          {t:"arrive somewhere ~",k:"grammar",m:"~ 한 지점에 도달하다",tip:"논증의 종착지를 비유적으로 말합니다."}]},
  {s:"B",en:"I know where you're going with this. You mean the anti-democratic strand of it.",
   ko:"어디로 가시려는지 압니다. 그중 반민주적인 갈래를 말씀하시는 거죠.",
   notes:[{t:"I know where you're going.",k:"colloquial",m:"어디로 가시려는지 압니다",tip:"상대의 논지를 미리 읽었을 때 씁니다."},
          {t:"strand",k:"business",m:"(사상·논의의) 갈래",tip:"한 흐름 안의 부분적 계열을 가리킵니다."}]},
  {s:"A",en:"I do. The argument that competent people should simply decide things without bothering with a vote.",
   ko:"맞습니다. 유능한 사람들이 투표 같은 건 신경 쓰지 말고 그냥 결정해야 한다는 주장이요.",
   notes:[{t:"without a vote",k:"collocation",m:"투표 없이",tip:"민주적 절차의 생략을 짧게 표현합니다."}]},
  {s:"B",en:"Almost nobody says it that plainly, but the reasoning does show up anyway.",
   ko:"그렇게 대놓고 말하는 사람은 거의 없습니다. 그래도 그 논리는 어떻게든 등장하죠.",
   notes:[{t:"say it that plainly",k:"collocation",m:"그렇게 노골적으로 말하다",tip:"완곡한 주장의 실체를 지적할 때 씁니다."},
          {t:"show up",k:"idiom",m:"나타나다, 등장하다",tip:"형태를 바꿔 반복되는 논리를 말할 때 유용합니다."}]},
  {s:"A",en:"Then let's test it on its own terms, starting with competent by whose measurement.",
   ko:"그럼 그쪽 논리 그대로 시험해 보죠. 누구의 기준으로 유능한가부터요.",
   notes:[{t:"on its own terms",k:"idiom",m:"그 자체의 논리로",tip:"상대 전제를 받아들인 채 반박하는 방식입니다."},
          {t:"by whose measurement",k:"grammar",m:"누구의 기준으로",tip:"기준의 자의성을 찌르는 질문입니다."}]},
  {s:"B",en:"That's the weakest part of it, honestly, since competence usually means whoever is already winning.",
   ko:"솔직히 거기가 가장 약한 부분입니다. 유능함이란 대개 이미 이기고 있는 쪽을 뜻하니까요.",
   notes:[{t:"the weakest part",k:"collocation",m:"가장 약한 부분",tip:"논증의 취약점을 짚는 표준 표현입니다."},
          {t:"whoever is already winning",k:"grammar",m:"이미 이기고 있는 쪽이 누구든",tip:"whoever절로 대상을 열어 둡니다."}]},
  {s:"A",en:"And there's no way to remove them, which is the whole point of having a vote.",
   ko:"게다가 그들을 물러나게 할 방법이 없죠. 투표가 존재하는 이유 전부가 바로 그건데요.",
   notes:[{t:"remove someone",k:"business",m:"(자리에서) 물러나게 하다",tip:"선거의 기능을 설명하는 중립적 동사입니다."},
          {t:"which is the whole point of ~",k:"grammar",m:"그것이 ~ 의 존재 이유입니다",tip:"핵심 목적을 상기시키는 반박 형태입니다."}]},
  {s:"B",en:"Fair, though I'd say the appeal isn't the theory at all, it's the frustration underneath it.",
   ko:"타당합니다. 다만 사람들이 끌리는 건 이론이 전혀 아니라, 그 밑에 깔린 좌절감이라고 봅니다.",
   notes:[{t:"the appeal isn't A, it's B",k:"grammar",m:"끌리는 이유는 A가 아니라 B입니다",tip:"현상의 진짜 동인을 짚는 문장 틀입니다."},
          {t:"frustration",k:"business",m:"좌절감, 답답함",tip:"제도가 느릴 때의 감정을 가리킵니다."}]},
  {s:"A",en:"Frustration is legitimate. It just isn't an argument for removing accountability from the people deciding.",
   ko:"좌절감은 정당합니다. 다만 그게 결정하는 사람들에게서 책임을 걷어낼 근거는 아니죠.",
   notes:[{t:"accountability",k:"business",m:"책임을 지는 구조",tip:"responsibility보다 「누가 답해야 하는가」에 가깝습니다."}]},
  {s:"B",en:"So what would you actually offer somebody who genuinely thinks the process is too slow?",
   ko:"그럼 절차가 정말로 너무 느리다고 보는 사람에게 실제로 무엇을 제안하시겠습니까?",
   notes:[{t:"What would you offer someone who ~",k:"grammar",m:"~ 하는 사람에게 무엇을 제안하겠습니까",tip:"비판에 대안을 요구하는 공정한 질문입니다."}]},
  {s:"A",en:"Faster institutions, not fewer of them, because speed and consent are not actually opposites.",
   ko:"제도를 줄이는 게 아니라 더 빠르게 만드는 겁니다. 속도와 동의는 사실 반대말이 아니니까요.",
   notes:[{t:"A, not fewer B",k:"grammar",m:"B를 줄이는 게 아니라 A",tip:"가짜 양자택일을 거부하는 형태입니다."},
          {t:"not actually opposites",k:"idiom",m:"사실 서로 반대되는 것이 아니다",tip:"잘못된 대립 구도를 해체합니다."}]},
  {s:"B",en:"That's a hard sell, but it's the one I'd much rather be defending in public.",
   ko:"그건 설득하기 어려운 주장이죠. 그래도 공개 석상에서 제가 훨씬 변호하고 싶은 쪽은 그겁니다.",
   notes:[{t:"a hard sell",k:"idiom",m:"설득하기 어려운 주장",tip:"상품이든 논지든 받아들이게 하기 힘든 것입니다."},
          {t:"the one I'd rather be defending",k:"grammar",m:"제가 차라리 변호하고 싶은 쪽",tip:"입장을 고르는 세련된 마무리입니다."}]}
 ],
 keys:[
  {en:"On what evidence?",ko:"무슨 근거로요",ex:"They've stopped assuming growth — on what evidence?"},
  {en:"That doesn't make X ~",ko:"그렇다고 X가 ~ 이 되는 건 아닙니다",ex:"Real constraints exist, but that doesn't make the pie permanently fixed."},
  {en:"Push that logic further",ko:"그 논리를 끝까지 밀어 보다",ex:"Push that logic further and you arrive somewhere uncomfortable."},
  {en:"on its own terms",ko:"그 자체의 논리로",ex:"Let's test the argument on its own terms before rejecting it."},
  {en:"the weakest part",ko:"가장 약한 부분",ex:"The weakest part is deciding who counts as competent."},
  {en:"accountability",ko:"책임을 지는 구조",ex:"Frustration isn't an argument for removing accountability."},
  {en:"a hard sell",ko:"설득하기 어려운 주장",ex:"Faster institutions is a hard sell, but it's the honest answer."},
  {en:"not actually opposites",ko:"사실 서로 반대되는 것이 아니다",ex:"Speed and consent are not actually opposites."}
 ],
 out:[
  {q:"Explain what changes when people stop assuming the economy will grow.",hint:"assume growth / constraint / secure rather than expand"},
  {q:"Summarize an argument you disagree with as fairly as you can, then answer it.",hint:"on its own terms / the weakest part / by whose measurement"},
  {q:"Respond to someone who says democratic decision-making is simply too slow.",hint:"frustration / accountability / not actually opposites"}
 ]
}
