{
 id:"w2d1", day:8, cat:"품질·리스크", level:"B2+",
 title:"The Recall Nobody Wants to Own",
 titleKo:"아무도 떠안기 싫은 리콜 — 결함과 책임의 경계",
 names:{A:"Grace (품질보증)", B:"Diego (구매·공급망)"},
 brief:[
  "제조 현장에서 결함이 나오면 가장 먼저 정해지는 것은 책임이 아니라 순서다. <b>봉쇄(containment)</b>가 먼저고 <b>시정(corrective action)</b>이 그다음이며, 책임 배분은 마지막이다. 원인을 다 밝히기 전에도 확산은 멈춰야 하기 때문이다.",
  "책임을 가르는 실질적 기준은 <b>입증책임(the burden of proof)</b>이 어디에 놓이느냐다. 공급사는 도면과 규격을 들고 오고, 완성품 업체는 실제 사용 조건을 든다. 계약서의 <b>책임한도(liability cap)</b>가 이 다툼의 상한을 미리 정해 둔다.",
  "리콜의 비용 구조는 <b>확실한 비용 대 불확실한 비용</b>의 대결이다. 지금 회수하면 금액이 확정되고, 미루면 확률은 낮지만 손실이 큰 <b>꼬리위험(tail risk)</b>이 남는다. 둘을 같은 저울에 올리는 순간 판단이 쉬워진다.",
  "그래서 실무에서 진짜로 다투는 것은 「리콜을 하느냐」가 아니라 <b>범위(scope)</b>다. 어느 로트까지, 어느 일련번호까지 포함할 것인가. 이 선을 예산이 아니라 <b>증거</b>로 그어야 나중에 방어할 수 있다."
 ],
 lines:[
  {s:"A",en:"We have traced the cracking to one supplier's batch, but I should add that our design tolerance was tight.",
   ko:"균열을 한 공급사의 로트까지 추적했습니다. 다만 우리 설계 공차가 빡빡했다는 점은 덧붙여야겠습니다.",
   notes:[{t:"trace A to B",k:"business",m:"A의 원인을 B까지 거슬러 찾다",tip:"불량의 출처를 확정하는 동사입니다."},
          {t:"tolerance",k:"business",m:"공차, 허용 오차",tip:"설계가 허용하는 치수 오차의 범위입니다."}]},
  {s:"B",en:"Stop there. You are already treating this as our fault, and the analysis is not finished.",
   ko:"거기서 멈추시죠. 벌써 우리 잘못으로 다루고 계신데, 분석이 끝나지 않았습니다.",
   notes:[{t:"Stop there.",k:"business",m:"거기서 멈추시죠",tip:"진행을 끊고 전제를 다시 보자고 요구하는 짧은 개입입니다."},
          {t:"treat A as B",k:"collocation",m:"A를 B로 다루다",tip:"전제를 지적할 때 자주 쓰는 동사입니다."}]},
  {s:"A",en:"I am not assigning blame. The burden of proof falls on whoever specified the tolerance.",
   ko:"책임을 지우려는 게 아닙니다. 입증책임은 공차를 지정한 쪽에 있습니다.",
   notes:[{t:"assign blame",k:"business",m:"책임을 지우다",tip:"누구 잘못인지 지목하는 행위입니다."},
          {t:"the burden of proof",k:"business",m:"입증책임",tip:"증명해야 할 의무가 누구에게 있는가를 말합니다."}]},
  {s:"B",en:"It always does. The supplier will point to our drawing, and we will be the party that pays.",
   ko:"늘 그렇습니다. 공급사는 우리 도면을 가리킬 테고, 돈을 내는 쪽은 우리가 됩니다.",
   notes:[{t:"point to ~",k:"phrasal",m:"~ 를 근거로 가리키다",tip:"책임을 돌릴 때의 표준 표현입니다."},
          {t:"the party that pays",k:"business",m:"비용을 부담하는 쪽",tip:"계약 문맥에서 party 는 당사자입니다."}]},
  {s:"A",en:"So we contain the problem first and settle responsibility later: stop shipments and quarantine the lot today.",
   ko:"그럼 문제를 먼저 봉쇄하고 책임은 나중에 정리합시다. 오늘 출하를 멈추고 로트를 격리합니다.",
   notes:[{t:"contain a problem",k:"business",m:"문제를 봉쇄하다",tip:"더 번지지 않게 막는 1차 조치입니다."},
          {t:"quarantine",k:"business",m:"격리하다",tip:"출하를 막고 따로 보관하는 것입니다."}]},
  {s:"B",en:"I accept containment. A public recall is a completely different decision with different consequences.",
   ko:"봉쇄는 받아들입니다. 공개 리콜은 결과가 전혀 다른 완전히 별개의 결정입니다.",
   notes:[{t:"I accept A.",k:"business",m:"A는 받아들입니다",tip:"부분적으로 동의하고 나머지를 분리하는 표현입니다."}]},
  {s:"A",en:"Agreed, but if a customer finds the defect before we report it, the damage is much larger.",
   ko:"동의합니다. 다만 우리가 신고하기 전에 고객이 결함을 발견하면 피해가 훨씬 큽니다.",
   notes:[{t:"report a defect",k:"business",m:"결함을 신고하다",tip:"규제 기관이나 고객에게 알리는 것입니다."}]},
  {s:"B",en:"You are assuming the defect appears at all, when most of that batch will never carry a real load.",
   ko:"결함이 드러난다고 전제하고 계십니다. 그 로트 대부분은 실제 하중을 받을 일이 없습니다.",
   notes:[{t:"carry a load",k:"business",m:"하중을 받다",tip:"구조물이 실제 힘을 견디는 상태입니다."}]},
  {s:"A",en:"That is a bet on tail risk: the probability is low, but the loss exceeds every saving we would make.",
   ko:"그건 꼬리위험에 거는 베팅입니다. 확률은 낮지만, 손실이 우리가 아낄 모든 금액을 넘어섭니다.",
   notes:[{t:"tail risk",k:"business",m:"꼬리위험",tip:"확률은 낮지만 손실이 막대한 위험입니다."},
          {t:"exceed",k:"business",m:"넘어서다, 초과하다",tip:"수치 비교에서 쓰는 격식 있는 동사입니다."}]},
  {s:"B",en:"Somebody still has to compare a cost that is certain with a loss that is only possible.",
   ko:"그래도 누군가는 확실한 비용과 가능성에 불과한 손실을 견주어야 합니다.",
   notes:[{t:"compare A with B",k:"collocation",m:"A를 B와 견주다",tip:"전치사 with 가 고정입니다."}]},
  {s:"A",en:"Then let us price both honestly, instead of presenting the cheaper option as the careful one.",
   ko:"그럼 둘 다 정직하게 값을 매깁시다. 싼 쪽을 신중한 쪽으로 제시하는 대신에요.",
   notes:[{t:"price something",k:"business",m:"~ 에 값을 매기다",tip:"비용을 숫자로 산출한다는 뜻입니다."},
          {t:"present A as B",k:"business",m:"A를 B로 제시하다",tip:"같은 사실에 다른 이름을 붙이는 행위입니다."}]},
  {s:"B",en:"The same argument works against you: choosing the safer option is not free either.",
   ko:"같은 논리가 그쪽에도 적용됩니다. 더 안전한 쪽을 고르는 것도 공짜가 아닙니다.",
   notes:[{t:"The same argument works against you.",k:"business",m:"같은 논리가 그쪽에도 적용됩니다",tip:"상대의 논거를 그대로 되돌리는 문장입니다."}]},
  {s:"A",en:"I would never claim it is free, but a quiet field repair preserves credibility we will need later.",
   ko:"공짜라고 주장할 생각은 없습니다. 다만 조용한 현장 수리는 나중에 필요할 신뢰를 지켜 줍니다.",
   notes:[{t:"a field repair",k:"business",m:"현장 수리",tip:"고객이 있는 곳에서 직접 고치는 조치입니다."},
          {t:"preserve credibility",k:"collocation",m:"신뢰를 지키다",tip:"damage credibility 와 반대입니다."}]},
  {s:"B",en:"You mean an unreported recall. Regulators have a specific term for that, and a specific penalty.",
   ko:"신고하지 않은 리콜을 말씀하시는군요. 규제 기관에는 그것을 가리키는 용어와 그에 맞는 제재가 있습니다.",
   notes:[{t:"unreported",k:"business",m:"신고되지 않은",tip:"보고 의무를 이행하지 않은 상태입니다."},
          {t:"a penalty",k:"business",m:"제재, 벌칙",tip:"규정 위반에 따르는 불이익입니다."}]},
  {s:"A",en:"Then we notify properly. My question was never whether we accept responsibility, but how wide the scope should be.",
   ko:"그럼 제대로 신고합니다. 제 질문은 책임을 지느냐가 아니라 범위를 얼마나 넓게 잡느냐였습니다.",
   notes:[{t:"My question was never A, but B.",k:"business",m:"제 질문은 A가 아니라 B였습니다",tip:"오해를 정확히 되돌리는 문장입니다."}]},
  {s:"B",en:"Scope decides the cost, because every additional lot adds directly to the final bill.",
   ko:"범위가 비용을 결정합니다. 로트를 하나 더할 때마다 최종 청구액이 바로 늘어나니까요.",
   notes:[{t:"scope",k:"business",m:"범위",tip:"조치가 적용되는 대상의 크기입니다."}]},
  {s:"A",en:"So we set the scope on evidence, not on budget, because a budget-based scope cannot be defended.",
   ko:"그러니 범위는 예산이 아니라 증거로 정합니다. 예산에 맞춘 범위는 방어할 수 없으니까요.",
   notes:[{t:"set the scope on ~",k:"business",m:"~ 를 기준으로 범위를 정하다",tip:"판단 기준을 명시하는 표현입니다."}]},
  {s:"B",en:"Agreed. Limit it to the serial range that the test data actually covers, and nothing beyond that.",
   ko:"동의합니다. 시험 데이터가 실제로 덮는 일련번호 구간으로 한정하고, 그 바깥은 포함하지 않습니다.",
   notes:[{t:"limit it to ~",k:"business",m:"~ 로 한정하다",tip:"적용 대상을 좁히는 동사입니다."},
          {t:"a serial range",k:"business",m:"일련번호 구간",tip:"제품을 특정하는 번호의 범위입니다."}]},
  {s:"A",en:"And we open the supplier conversation early, in good faith, before either side brings in lawyers.",
   ko:"그리고 양쪽이 변호사를 부르기 전에, 선의로 공급사와의 대화를 일찍 시작합니다.",
   notes:[{t:"in good faith",k:"business",m:"선의로",tip:"상대를 속일 의도 없이 임한다는 법률·상거래 용어입니다."}]},
  {s:"B",en:"Good. I would rather share the cost with a supplier we trust than delay the decision another quarter.",
   ko:"좋습니다. 결정을 한 분기 더 미루느니 믿는 공급사와 비용을 나누는 편이 낫습니다.",
   notes:[{t:"share the cost",k:"collocation",m:"비용을 나누다",tip:"양쪽이 분담한다는 뜻입니다."},
          {t:"delay a decision",k:"collocation",m:"결정을 미루다",tip:"postpone 보다 구어적이고 자주 쓰입니다."}]}
 ],
 keys:[
  {en:"Stop there.",ko:"거기서 멈추시죠",ex:"Stop there. The analysis is not finished yet."},
  {en:"The same argument works against you.",ko:"같은 논리가 그쪽에도 적용됩니다",ex:"The same argument works against you: caution has a cost too."},
  {en:"My question was never A, but B.",ko:"제 질문은 A가 아니라 B였습니다",ex:"My question was never whether, but how wide."},
  {en:"I accept A.",ko:"A는 받아들입니다",ex:"I accept containment, but not a public recall."},
  {en:"the burden of proof",ko:"입증책임",ex:"The burden of proof falls on whoever specified the tolerance."},
  {en:"tail risk",ko:"꼬리위험",ex:"That is a bet on tail risk: low probability, enormous loss."},
  {en:"scope",ko:"범위",ex:"Scope decides the cost, so we set it on evidence."},
  {en:"in good faith",ko:"선의로",ex:"Open the conversation early and in good faith."}
 ],
 out:[
  {q:"Interrupt a colleague who is assuming a conclusion, and say why.",hint:"Stop there. / treat A as B / the burden of proof"},
  {q:"Argue that the cheap option is a bet, not a careful choice.",hint:"tail risk / price something / present A as B"},
  {q:"Agree to part of a proposal and set a precise limit on it.",hint:"I accept A. / limit it to ~ / set the scope on ~"}
 ]
},
{
 id:"w2d2", day:9, cat:"환경·통상", level:"B2+",
 title:"Paying for Carbon at the Border",
 titleKo:"국경에서 탄소값을 치르다 — 배출 규제와 수출 경쟁력",
 names:{A:"Lena (환경·규제 대응)", B:"Hugo (수출영업)"},
 brief:[
  "배출에 값이 매겨지면 원가 구조가 바뀐다. 지금까지 원가는 원료와 에너지였지만, <b>탄소 가격(carbon pricing)</b>이 붙는 순간 배출량 자체가 비용 항목이 된다. 같은 제품, 같은 공정이라도 어디서 어떻게 만들었는지가 값을 가른다.",
  "국경에서 조정이 일어나는 이유는 <b>탄소 누출(carbon leakage)</b> 때문이다. 규제가 강한 나라의 공장이 규제가 약한 나라로 옮겨 가면 배출은 그대로인 채 산업만 빠져나간다. 그래서 수입품에도 같은 값을 물려 <b>공정한 경쟁 조건(a level playing field)</b>을 맞추려 한다.",
  "실무의 난점은 규제가 아니라 <b>측정</b>이다. 한 톤에 들어 있는 배출량(embedded emissions)을 어떻게 셈하느냐에 따라 누가 얼마를 내는지가 달라진다. 그래서 다툼은 늘 방법론에서 벌어지고, <b>검증(verification)</b>을 거친 숫자만 값을 인정받는다.",
  "영업 쪽에서 갈리는 것은 <b>전가(pass-through)</b>다. 늘어난 비용을 가격에 얹을 수 있는 고객이 있고, 얹는 순간 떠나는 고객이 있다. 검증된 데이터가 있으면 <b>친환경 프리미엄(green premium)</b>이 붙지만, 없으면 그냥 값만 오른 제품이 된다."
 ],
 lines:[
  {s:"A",en:"Once emissions carry a price at the border, our cost base includes how the product was made.",
   ko:"국경에서 배출에 값이 붙으면, 우리 원가에는 그 제품을 어떻게 만들었는지가 포함됩니다.",
   notes:[{t:"carry a price",k:"business",m:"값이 매겨지다",tip:"비용이 부과된다는 뜻입니다."},
          {t:"cost base",k:"business",m:"원가 구조",tip:"제품 하나에 들어가는 비용의 총체입니다."}]},
  {s:"B",en:"In theory, yes. In practice, nobody agrees on how to measure the emissions embedded in one ton.",
   ko:"이론상으로는 그렇습니다. 실제로는 1톤에 내재된 배출량을 어떻게 재는지에 아무도 합의하지 못했습니다.",
   notes:[{t:"In theory, yes. In practice, ~",k:"business",m:"이론상으로는 그렇습니다. 실제로는 ~",tip:"원칙과 현실을 갈라 반박하는 표준 구조입니다."},
          {t:"embedded emissions",k:"business",m:"내재 배출량",tip:"제품을 만드는 과정에서 나온 배출량입니다."}]},
  {s:"A",en:"The policy is presented as fair competition, but the measurement rules decide who actually pays.",
   ko:"그 제도는 공정 경쟁으로 제시되지만, 실제로 누가 내는지는 측정 규칙이 결정합니다.",
   notes:[{t:"be presented as ~",k:"business",m:"~ 로 제시되다",tip:"공식적인 명분과 실제 효과를 구분할 때 씁니다."}]},
  {s:"B",en:"My customers want a number this week, not a methodology paper sometime next year.",
   ko:"제 고객들은 이번 주에 숫자를 원합니다. 내년 어느 때쯤 나올 방법론 보고서가 아니라요.",
   notes:[{t:"a methodology paper",k:"business",m:"방법론 문서",tip:"계산 방식을 설명한 기술 문서입니다."}]},
  {s:"A",en:"Give them a range and state the assumptions behind it, because a precise number that is wrong costs more.",
   ko:"구간을 주고 그 뒤의 전제를 밝히세요. 정밀하지만 틀린 숫자가 더 비싸게 먹히니까요.",
   notes:[{t:"state the assumptions",k:"business",m:"전제를 밝히다",tip:"숫자가 어떤 조건에서 나왔는지 드러내는 것입니다."}]},
  {s:"B",en:"A buyer whose manager wants one figure will treat a range as uncertainty and raise the discount.",
   ko:"상사가 숫자 하나를 원하는 구매자는 구간을 불확실성으로 받아들이고 할인을 더 요구합니다.",
   notes:[{t:"treat A as B",k:"collocation",m:"A를 B로 받아들이다",tip:"상대의 해석 방식을 설명합니다."},
          {t:"raise the discount",k:"collocation",m:"할인 폭을 키우다",tip:"가격 협상에서의 결과를 말합니다."}]},
  {s:"A",en:"Then we verify our figures early and get certified, because verification turns a claim into a discount.",
   ko:"그럼 수치를 일찍 검증받고 인증을 얻습니다. 검증이 주장을 할인으로 바꿔 주니까요.",
   notes:[{t:"verification",k:"business",m:"검증",tip:"제3자가 수치의 정확성을 확인하는 절차입니다."},
          {t:"get certified",k:"business",m:"인증을 받다",tip:"공인 기관의 자격을 취득하는 것입니다."}]},
  {s:"B",en:"Certification costs money that we would pass through, and thin-margin customers will go elsewhere.",
   ko:"인증에는 우리가 전가할 비용이 들고, 마진이 얇은 고객은 다른 데로 갈 겁니다.",
   notes:[{t:"pass the cost through",k:"business",m:"비용을 전가하다",tip:"원가 상승분을 판매가에 반영하는 것입니다."},
          {t:"thin-margin",k:"business",m:"마진이 얇은",tip:"이익률이 낮아 가격에 민감한 상태입니다."}]},
  {s:"A",en:"Some will. Others pay a premium once their own reporting depends on numbers that passed an audit.",
   ko:"일부는 그럴 겁니다. 자기네 보고가 감사를 통과한 숫자에 걸리는 순간 웃돈을 낼 고객도 있습니다.",
   notes:[{t:"pay a premium",k:"collocation",m:"웃돈을 내다",tip:"기준보다 비싼 값을 치르는 것입니다."},
          {t:"pass an audit",k:"collocation",m:"감사를 통과하다",tip:"외부 검증을 문제없이 마치는 것입니다."}]},
  {s:"B",en:"You are assuming their regulators act before ours do, and that assumption carries real risk.",
   ko:"그쪽 규제 기관이 우리보다 먼저 움직인다고 전제하고 계십니다. 그 전제에는 실제 위험이 있습니다.",
   notes:[{t:"carry risk",k:"collocation",m:"위험을 안고 있다",tip:"전제나 결정에 위험이 따른다는 뜻입니다."}]},
  {s:"A",en:"I am not predicting the timing. I am predicting that the direction will not reverse, which is different.",
   ko:"저는 시점을 예측하는 게 아닙니다. 방향이 되돌아가지 않을 거라고 예측하는 것이고, 그건 다릅니다.",
   notes:[{t:"I am not A. I am B, which is different.",k:"business",m:"저는 A가 아니라 B입니다, 그건 다릅니다",tip:"자기 주장의 범위를 정확히 좁히는 문장입니다."}]},
  {s:"B",en:"If we move first, we carry the cost alone for several years before competitors follow.",
   ko:"먼저 움직이면, 경쟁사가 따라오기까지 몇 년을 혼자 비용을 짊어집니다.",
   notes:[{t:"move first",k:"business",m:"먼저 움직이다",tip:"first mover 의 동사형입니다. 이점과 부담이 함께 있습니다."}]},
  {s:"A",en:"If we move last, we buy the same equipment when demand is high and prices have risen.",
   ko:"마지막에 움직이면, 수요가 몰리고 값이 오른 시점에 같은 설비를 사게 됩니다.",
   notes:[{t:"demand is high",k:"collocation",m:"수요가 몰리다",tip:"가격 상승의 원인을 평이하게 설명합니다."}]},
  {s:"B",en:"That argument is sound. I only object to describing an unavoidable cost as a strategy.",
   ko:"그 논리는 타당합니다. 저는 피할 수 없는 비용을 전략이라고 부르는 것에만 반대합니다.",
   notes:[{t:"That argument is sound.",k:"business",m:"그 논리는 타당합니다",tip:"상대 논거를 인정하는 정확한 평가 표현입니다."},
          {t:"I only object to ~",k:"business",m:"저는 ~ 에만 반대합니다",tip:"반대의 범위를 정확히 한정합니다."}]},
  {s:"A",en:"Then let us separate the two: part of this is compliance we cannot avoid, and part is positioning we chose.",
   ko:"그럼 둘을 나눕시다. 일부는 피할 수 없는 규제 대응이고, 일부는 우리가 선택한 포지셔닝입니다.",
   notes:[{t:"Let us separate the two:",k:"business",m:"그럼 둘을 나눕시다",tip:"섞여 있는 사안을 분리하자는 제안입니다."},
          {t:"compliance",k:"business",m:"규제 준수",tip:"법과 규정을 지키기 위한 활동과 비용입니다."}]},
  {s:"B",en:"I can sell that division. What I cannot sell is a green premium with no evidence behind it.",
   ko:"그 구분은 팔 수 있습니다. 제가 팔 수 없는 건 근거 없는 친환경 프리미엄입니다.",
   notes:[{t:"What I cannot sell is ~",k:"business",m:"제가 팔 수 없는 것은 ~ 입니다",tip:"영업이 감당할 수 없는 한계를 명확히 밝힙니다."}]},
  {s:"A",en:"Nobody is asking you to, because the premium only holds if the data survives an external audit.",
   ko:"아무도 그러라고 하지 않습니다. 그 프리미엄은 데이터가 외부 감사를 견뎌야만 유지되니까요.",
   notes:[{t:"hold",k:"business",m:"유지되다, 성립하다",tip:"조건이 계속 유효하다는 뜻입니다. The price holds."}]},
  {s:"B",en:"Then give me the data early enough to write it into the contracts we sign next year.",
   ko:"그럼 내년에 체결할 계약서에 넣을 수 있을 만큼 일찍 데이터를 주세요.",
   notes:[{t:"write it into a contract",k:"business",m:"계약서에 명시하다",tip:"구두 합의를 문서 조항으로 만드는 것입니다."}]},
  {s:"A",en:"Agreed. And we reduce our exposure by securing the low-emission route for the key accounts first.",
   ko:"동의합니다. 그리고 주요 거래처부터 저배출 공정을 확보해 노출을 줄이겠습니다.",
   notes:[{t:"reduce exposure",k:"business",m:"위험 노출을 줄이다",tip:"hedge 의 평이한 표현입니다."},
          {t:"a key account",k:"business",m:"주요 거래처",tip:"매출 비중이 큰 핵심 고객입니다."}]},
  {s:"B",en:"That works. Accept the cost where it matters most, and let the rest follow the market price.",
   ko:"괜찮습니다. 가장 중요한 곳에서는 비용을 감수하고, 나머지는 시장 가격을 따라가게 둡니다.",
   notes:[{t:"where it matters most",k:"collocation",m:"가장 중요한 곳에서",tip:"자원 배분의 우선순위를 말합니다."}]}
 ],
 keys:[
  {en:"In theory, yes. In practice, ~",ko:"이론상으로는 그렇습니다. 실제로는 ~",ex:"In theory, yes. In practice, nobody agrees on the method."},
  {en:"That argument is sound.",ko:"그 논리는 타당합니다",ex:"That argument is sound, and I have no answer to it."},
  {en:"I only object to ~",ko:"저는 ~ 에만 반대합니다",ex:"I only object to calling a cost a strategy."},
  {en:"What I cannot sell is ~",ko:"제가 팔 수 없는 것은 ~ 입니다",ex:"What I cannot sell is a claim with no evidence behind it."},
  {en:"cost base",ko:"원가 구조",ex:"Our cost base now includes how the product was made."},
  {en:"pass the cost through",ko:"비용을 전가하다",ex:"Certification costs money that we would pass through."},
  {en:"compliance",ko:"규제 준수",ex:"Part of this is compliance and part is positioning."},
  {en:"reduce exposure",ko:"위험 노출을 줄이다",ex:"We reduce exposure by securing the route for key accounts."}
 ],
 out:[
  {q:"Separate what a policy claims to do from what it actually does.",hint:"be presented as ~ / In theory, yes. In practice, ~ / embedded emissions"},
  {q:"Accept a colleague's reasoning and state exactly what you still object to.",hint:"That argument is sound. / I only object to ~ / Let us separate the two:"},
  {q:"Set a condition before you agree to sell something.",hint:"What I cannot sell is ~ / pass an audit / write it into a contract"}
 ]
},
{
 id:"w2d3", day:10, cat:"인구·노동", level:"B2+",
 title:"The Shift Nobody Can Fill",
 titleKo:"채울 수 없는 교대조 — 고령화와 현장의 기술 전수",
 names:{A:"Ines (인사)", B:"Karl (제조 현장 반장)"},
 brief:[
  "숙련 인력의 은퇴는 인원 문제로 보이지만 실제로는 <b>지식 문제</b>다. 사람이 나가면 자리는 채울 수 있어도, 그 사람 머릿속에만 있던 판단은 함께 나간다. 이것을 <b>암묵지(tacit knowledge)</b>라고 부른다.",
  "암묵지가 어려운 이유는 <b>말로 옮겨지지 않기 때문</b>이다. 소리로 이상을 알아채고, 손끝으로 온도를 가늠하는 판단은 매뉴얼에 담기지 않는다. 그래서 전수는 문서가 아니라 <b>같이 서 있는 시간</b>으로만 일어난다.",
  "현장이 이 문제를 미루는 방식은 대개 <b>초과근무</b>다. 당장은 돌아가지만 격차를 감출 뿐 좁히지는 못한다. 이런 임시 대응을 <b>stopgap</b>이라 하고, 반복되면 은퇴가 몰리는 시점에 한꺼번에 터진다.",
  "자동화는 이 문제의 해답이면서 동시에 함정이다. 기계가 공정을 대신해도 <b>결과가 이상할 때 알아채는 판단</b>은 사람에게 남는다. 그래서 채용과 훈련의 기준이 「손」에서 「판단」으로 옮겨 간다."
 ],
 lines:[
  {s:"A",en:"Three of your senior operators retire within a year, and nobody is currently training beside them.",
   ko:"숙련 오퍼레이터 세 분이 1년 안에 은퇴하는데, 지금 그 옆에서 배우는 사람이 없습니다.",
   notes:[{t:"train beside someone",k:"collocation",m:"옆에 붙어 배우다",tip:"현장에서 직접 보며 익히는 방식입니다."}]},
  {s:"B",en:"You cannot transfer forty years of experience in twelve months, and anyone who claims otherwise has not tried.",
   ko:"40년의 경험을 열두 달에 옮길 수는 없습니다. 그렇게 주장하는 사람은 해 본 적이 없는 겁니다.",
   notes:[{t:"transfer experience",k:"business",m:"경험을 전수하다",tip:"knowledge transfer 의 동사형입니다."},
          {t:"claim otherwise",k:"collocation",m:"그렇지 않다고 주장하다",tip:"반대 주장을 한 단어로 받는 표현입니다."}]},
  {s:"A",en:"I understand that, but if we do nothing, all of that knowledge leaves the company with them.",
   ko:"이해합니다. 그래도 아무것도 하지 않으면, 그 지식 전부가 그분들과 함께 회사를 떠납니다.",
   notes:[{t:"leave the company",k:"collocation",m:"회사를 떠나다",tip:"지식이나 인력의 이탈을 말합니다."}]},
  {s:"B",en:"It is already leaving. We covered the last two retirements with overtime and good luck.",
   ko:"이미 떠나고 있습니다. 지난 두 번의 은퇴는 초과근무와 운으로 메웠습니다.",
   notes:[{t:"cover",k:"business",m:"메우다, 대신 맡다",tip:"cover a shift / cover for someone 처럼 씁니다."}]},
  {s:"A",en:"Overtime is a temporary fix that hides the gap in the report instead of closing it.",
   ko:"초과근무는 공백을 메우는 게 아니라 보고서에서 가려 주는 임시 조치입니다.",
   notes:[{t:"a temporary fix",k:"business",m:"임시 조치",tip:"근본 해결이 아닌 대증요법입니다. a permanent fix 와 반대입니다."}]},
  {s:"B",en:"Then give me apprentices who stay, because the last three left for shifts with better hours.",
   ko:"그럼 남아 있을 견습생을 주세요. 지난 세 명은 근무 시간이 나은 교대조로 떠났습니다.",
   notes:[{t:"an apprentice",k:"business",m:"견습생",tip:"일하면서 배우는 훈련생입니다."}]},
  {s:"A",en:"That is a retention problem and I accept responsibility for it, but pay alone will not fill the pipeline.",
   ko:"그건 잔류 문제이고 제가 책임지겠습니다. 다만 급여만으로는 인력 공급이 채워지지 않습니다.",
   notes:[{t:"retention",k:"business",m:"인력 유지",tip:"직원이 회사에 남아 있게 하는 것입니다."},
          {t:"a pipeline",k:"business",m:"인력 공급 경로",tip:"뒤이어 들어올 사람들의 흐름을 말합니다."}]},
  {s:"B",en:"Pay matters more than you think when the work is hot, loud and scheduled at difficult hours.",
   ko:"일이 덥고 시끄럽고 근무 시간까지 불편하다면, 급여가 생각하시는 것보다 크게 작용합니다.",
   notes:[{t:"matter more than you think",k:"collocation",m:"생각보다 크게 작용하다",tip:"상대의 과소평가를 지적하는 표현입니다."}]},
  {s:"A",en:"It does, up to a certain level. Above that, people leave because nobody trained them properly.",
   ko:"어느 수준까지는 그렇습니다. 그 위로는 제대로 가르쳐 준 사람이 없어서 떠납니다.",
   notes:[{t:"up to a certain level",k:"collocation",m:"어느 수준까지는",tip:"조건부 동의를 표현하는 정확한 방식입니다."}]},
  {s:"B",en:"Half of what I know I learned on the job, by watching a man who never explained anything.",
   ko:"제가 아는 것의 절반은 현장에서 배웠습니다. 아무것도 설명해 주지 않는 사람을 보면서요.",
   notes:[{t:"learn on the job",k:"collocation",m:"현장에서 일하며 배우다",tip:"공식 교육이 아닌 실무 경험을 말합니다."}]},
  {s:"A",en:"That is the problem exactly: tacit knowledge that nobody recorded, because recording it was never anyone's job.",
   ko:"문제가 바로 그것입니다. 아무도 기록하지 않은 암묵지죠. 기록하는 게 누구의 업무도 아니었으니까요.",
   notes:[{t:"tacit knowledge",k:"business",m:"암묵지",tip:"말이나 글로 옮기기 어려운, 몸에 밴 지식입니다."},
          {t:"record knowledge",k:"business",m:"지식을 기록하다",tip:"문서로 남겨 조직에 보관하는 것입니다."}]},
  {s:"B",en:"Some of it cannot be recorded, because you feel a bad weld before any instrument shows it.",
   ko:"일부는 기록할 수 없습니다. 어떤 계기에 나타나기 전에 손으로 불량 용접이 느껴지니까요.",
   notes:[{t:"an instrument",k:"business",m:"계측기",tip:"측정 장비를 가리키는 격식 있는 단어입니다."}]},
  {s:"A",en:"The other half can be, so let us capture what is teachable and accept the limit.",
   ko:"나머지 절반은 가능합니다. 그러니 가르칠 수 있는 것만 담고 그 한계는 받아들입시다.",
   notes:[{t:"what is teachable",k:"grammar",m:"가르칠 수 있는 것",tip:"what절로 범위를 지정합니다."},
          {t:"accept the limit",k:"collocation",m:"한계를 받아들이다",tip:"완전한 해결이 불가능함을 인정하는 것입니다."}]},
  {s:"B",en:"Then give me protected time on the shift schedule, not another document that nobody opens.",
   ko:"그럼 교대 일정에 보호된 시간을 주세요. 아무도 열어 보지 않는 문서 하나 더 말고요.",
   notes:[{t:"protected time",k:"business",m:"다른 업무로 침범되지 않는 확보 시간",tip:"교육이나 정비를 위해 떼어 둔 시간입니다."}]},
  {s:"A",en:"You will get it. In exchange, pair each senior operator with two juniors on every shift.",
   ko:"드리겠습니다. 대신 교대마다 숙련 오퍼레이터 한 명에 후배 둘을 짝지어 주세요.",
   notes:[{t:"in exchange",k:"collocation",m:"그 대가로",tip:"교환 조건을 제시하는 연결어입니다."},
          {t:"pair A with B",k:"collocation",m:"A와 B를 짝짓다",tip:"인원 배치에 쓰는 동사입니다."}]},
  {s:"B",en:"Two is too many, because one learns while the other only watches the first one make mistakes.",
   ko:"둘은 너무 많습니다. 하나가 배우는 동안 다른 하나는 첫째가 실수하는 걸 보기만 하니까요.",
   notes:[{t:"too many",k:"grammar",m:"너무 많은",tip:"셀 수 있는 명사에는 too many, 셀 수 없는 명사에는 too much 입니다."}]},
  {s:"A",en:"Watching is still learning, and it gives us a replacement for the day one of them resigns.",
   ko:"보는 것도 배움입니다. 그리고 둘 중 하나가 퇴사하는 날의 대체 인력이 생깁니다.",
   notes:[{t:"a replacement",k:"business",m:"대체 인력",tip:"빈자리를 채울 사람입니다."},
          {t:"resign",k:"business",m:"퇴사하다",tip:"자발적으로 그만두는 것입니다. quit 보다 격식 있습니다."}]},
  {s:"B",en:"Automation will take some of these stations within a few years, so the problem changes shape anyway.",
   ko:"몇 년 안에 자동화가 이 공정 자리 일부를 가져갈 테니, 문제의 모양은 어차피 바뀝니다.",
   notes:[{t:"a station",k:"business",m:"공정 자리, 작업 위치",tip:"생산 라인의 한 지점입니다."}]},
  {s:"A",en:"Some of them, not all. The machines still need somebody who can tell when the output is wrong.",
   ko:"일부입니다, 전부가 아니라. 기계에도 결과가 잘못됐다는 걸 알아볼 사람은 여전히 필요합니다.",
   notes:[{t:"A, not all",k:"grammar",m:"전부가 아니라 일부",tip:"과장된 주장을 정확히 깎는 표현입니다."},
          {t:"tell when ~",k:"grammar",m:"~ 인지 알아보다",tip:"tell 은 여기서 「구별하다, 알아차리다」입니다."}]},
  {s:"B",en:"Then we should train for judgment and stop hiring for tasks a machine will take over.",
   ko:"그럼 판단력을 목표로 훈련하고, 기계가 넘겨받을 작업을 기준으로 뽑는 것은 그만둬야 합니다.",
   notes:[{t:"train for ~ / hire for ~",k:"business",m:"~ 를 목표로 훈련하다 / ~ 를 기준으로 채용하다",tip:"무엇을 보고 사람을 뽑고 기르는지를 말합니다."},
          {t:"take over",k:"phrasal",m:"넘겨받다",tip:"일이나 역할을 대신 맡는 것입니다."}]}
 ],
 keys:[
  {en:"up to a certain level",ko:"어느 수준까지는",ex:"Pay helps, but only up to a certain level."},
  {en:"A, not all",ko:"전부가 아니라 일부",ex:"Automation will take some of them, not all."},
  {en:"in exchange",ko:"그 대가로",ex:"You get protected time. In exchange, pair each senior with two juniors."},
  {en:"accept the limit",ko:"한계를 받아들이다",ex:"Capture what is teachable and accept the limit."},
  {en:"tacit knowledge",ko:"암묵지",ex:"Tacit knowledge disappears because recording it is nobody's job."},
  {en:"retention",ko:"인력 유지",ex:"That is a retention problem, and pay alone will not fix it."},
  {en:"protected time",ko:"확보된 교육 시간",ex:"Give me protected time on the schedule, not another document."},
  {en:"train for ~ / hire for ~",ko:"~ 를 목표로 훈련하다 / ~ 를 기준으로 채용하다",ex:"Train for judgment and stop hiring for a pair of hands."}
 ],
 out:[
  {q:"Explain what a company loses when an experienced worker retires.",hint:"tacit knowledge / leave the company / learn on the job"},
  {q:"Accept part of a criticism and set the limit of your agreement.",hint:"up to a certain level / retention / a temporary fix"},
  {q:"Propose a trade: what you will give and what you want in return.",hint:"in exchange / protected time / pair A with B"}
 ]
},
{
 id:"w2d4", day:11, cat:"협상·계약", level:"B2+",
 title:"The Price Is Not the Price",
 titleKo:"가격은 가격이 아니다 — 장기계약의 조정 조항과 원가 전가",
 names:{A:"Marta (계약·법무)", B:"Joon (수출영업)"},
 brief:[
  "장기 공급계약에서 표지에 적힌 가격은 실제로 받는 값이 아니다. 몇 년을 묶는 계약에서 원가만 움직이고 값이 고정되어 있으면 한쪽이 반드시 무너진다. 그래서 원가가 움직이면 값도 따라 움직이도록 <b>가격 조정 조항(escalation clause)</b>을 넣어 둔다.",
  "조정의 기준은 대개 공개된 지수다 — <b>지수 연동(index-linked)</b>. 양쪽이 임의로 다투지 않아도 되니 깔끔해 보이지만, 지수는 현실을 몇 주 늦게 반영한다. 그 <b>시차(lag)</b> 동안 벌어진 손실은 계약서에 적힌 대로 누군가가 <b>떠안는다(eat the cost)</b>.",
  "그래서 위험을 나누는 장치가 붙는다. 값이 오를 때의 상한이 <b>cap</b>, 상한과 하한을 함께 두는 것이 <b>collar</b>다. 상한만 주고 하한을 못 받으면 오를 때의 부담은 우리가 지고 내릴 때의 이익은 상대가 가져간다 — 흔히 놓치는 자리다.",
  "물량 쪽의 장치는 <b>take-or-pay</b>다. 안 가져가도 약정한 값은 낸다. 설비 투자를 회수하려면 필요하지만 수요가 꺾이면 분쟁의 씨앗이 된다. 그래서 실무에서는 물량을 조금 풀어 주고 분기마다 차액을 맞추는 <b>정산(true-up)</b>으로 절충한다."
 ],
 lines:[
  {s:"A",en:"Before you sign a three-year contract, tell me exactly what happens when energy costs rise.",
   ko:"3년짜리 계약에 서명하기 전에, 에너지 비용이 오르면 정확히 어떻게 되는지 말해 주세요.",
   notes:[{t:"Before you ~, tell me ~",k:"grammar",m:"~ 하기 전에 ~ 을 말해 주세요",tip:"순서를 못 박아 확인을 요구하는 형태입니다."}]},
  {s:"B",en:"The price is index-linked, so the quarterly average feeds into the invoice and both sides share the change.",
   ko:"가격은 지수 연동입니다. 분기 평균이 청구서에 반영되어 변동을 양쪽이 나눠 집니다.",
   notes:[{t:"index-linked",k:"business",m:"지수 연동의",tip:"외부 지표에 따라 가격이 자동으로 조정되는 방식입니다."},
          {t:"feed into ~",k:"phrasal",m:"~ 에 반영되어 들어가다",tip:"데이터가 계산식에 입력된다는 뜻입니다."}]},
  {s:"A",en:"That looks clean in the contract, but the index lags by several weeks, and somebody absorbs that cost.",
   ko:"계약서상으로는 깔끔해 보입니다. 다만 지수가 몇 주 늦어서, 그 비용은 누군가 떠안습니다.",
   notes:[{t:"lag",k:"business",m:"뒤처지다, 시차가 있다",tip:"지표가 실제 변화를 늦게 반영하는 것입니다."},
          {t:"absorb a cost",k:"business",m:"비용을 떠안다",tip:"전가하지 못하고 자기가 감당하는 것입니다."}]},
  {s:"B",en:"A lagging index is still better than a fixed price that becomes loss-making in the fourth month.",
   ko:"늦는 지수라도, 넉 달째에 적자가 되는 고정가보다는 낫습니다.",
   notes:[{t:"loss-making",k:"business",m:"적자를 내는",tip:"profitable(수익을 내는)과 반대입니다."}]},
  {s:"A",en:"My real concern is the cap, because you gave them a maximum price with no minimum underneath it.",
   ko:"제 진짜 우려는 상한입니다. 하한도 없이 최고가만 정해 주셨으니까요.",
   notes:[{t:"a cap",k:"business",m:"가격 상한",tip:"그 이상은 청구할 수 없는 최고 한도입니다."},
          {t:"My real concern is ~",k:"business",m:"제 진짜 우려는 ~ 입니다",tip:"여러 문제 중 핵심 하나를 앞세우는 틀입니다."}]},
  {s:"B",en:"The cap is what closed the deal, because their procurement team would not agree without it.",
   ko:"그 상한이 계약을 성사시켰습니다. 상대 구매팀이 그것 없이는 동의하지 않았으니까요.",
   notes:[{t:"close a deal",k:"business",m:"계약을 성사시키다",tip:"협상을 마무리해 체결하는 것입니다."}]},
  {s:"A",en:"Then ask for a floor as well, because a minimum price costs them nothing today and protects us later.",
   ko:"그럼 하한도 요구하세요. 최저가는 오늘 그들에게 비용이 들지 않으면서 나중에 우리를 보호합니다.",
   notes:[{t:"a floor",k:"business",m:"가격 하한",tip:"그 아래로는 내려가지 않는 최저 한도입니다. cap 과 짝입니다."}]},
  {s:"B",en:"I can raise it, though reopening the price now may undo everything we have already agreed.",
   ko:"제기할 수는 있습니다. 다만 지금 가격을 다시 열면 이미 합의한 것이 전부 풀릴 수 있습니다.",
   notes:[{t:"undo an agreement",k:"business",m:"합의를 원점으로 되돌리다",tip:"진전을 되돌린다는 뜻입니다."}]},
  {s:"A",en:"It is better to reopen it now than to argue about the same sentence in court in year two.",
   ko:"2년 차에 법정에서 같은 문장을 두고 다투느니, 지금 다시 여는 편이 낫습니다.",
   notes:[{t:"It is better to A than to B",k:"grammar",m:"B 하느니 A 하는 편이 낫다",tip:"두 선택지를 직접 비교하는 골격입니다."}]},
  {s:"B",en:"Understood. What about volume? They pushed hard for take-or-pay and I resisted as long as possible.",
   ko:"알겠습니다. 물량은요? 상대가 take-or-pay 를 강하게 밀었고 저는 가능한 한 버텼습니다.",
   notes:[{t:"take-or-pay",k:"business",m:"인수하거나 대금을 내는 조항",tip:"약정 물량을 안 가져가도 값은 치러야 하는 조건입니다."},
          {t:"resist",k:"business",m:"버티다, 저항하다",tip:"요구를 받아들이지 않고 견디는 것입니다."}]},
  {s:"A",en:"How much did it soften? Take-or-pay is how we recover the investment we made in that line.",
   ko:"얼마나 완화됐습니까? take-or-pay 가 그 라인에 투입한 투자를 회수하는 방법인데요.",
   notes:[{t:"soften",k:"business",m:"조건이 완화되다",tip:"강한 조항이 약해지는 것입니다."},
          {t:"recover an investment",k:"business",m:"투자를 회수하다",tip:"들인 돈을 되찾는 것입니다."}]},
  {s:"B",en:"Eighty percent of nominated tonnage with a quarterly true-up, and anything stricter would have ended the deal.",
   ko:"지정 물량의 80퍼센트에 분기 정산입니다. 그보다 엄격했으면 계약이 깨졌을 겁니다.",
   notes:[{t:"a true-up",k:"business",m:"정산, 사후 조정",tip:"실제와 약정의 차이를 뒤에 맞추는 절차입니다."},
          {t:"nominated tonnage",k:"business",m:"지정 물량",tip:"미리 통보해 확정한 인수 수량입니다."}]},
  {s:"A",en:"That is workable, provided the true-up offsets shortfalls in the same quarter they occur.",
   ko:"그건 운용 가능합니다. 단, 정산이 부족분이 발생한 바로 그 분기에 상계된다면요.",
   notes:[{t:"provided that ~",k:"grammar",m:"~ 하는 조건이라면",tip:"if 보다 조건임을 분명히 강조합니다."},
          {t:"offset",k:"business",m:"상계하다, 상쇄하다",tip:"플러스와 마이너스를 맞물려 지우는 것입니다."}]},
  {s:"B",en:"Now you are the one reopening the terms, so let us write it plainly and finish.",
   ko:"이제는 조건을 다시 여는 쪽이 그쪽이군요. 그러니 평이하게 쓰고 끝냅시다.",
   notes:[{t:"terms",k:"business",m:"계약 조건",tip:"가격, 물량, 기간 등 합의된 내용입니다."}]},
  {s:"A",en:"That is my job. Most disputes are not bad faith. They are two honest readings of one sentence.",
   ko:"그게 제 일입니다. 분쟁 대부분은 악의가 아니라, 한 문장에 대한 두 개의 정직한 해석입니다.",
   notes:[{t:"bad faith",k:"business",m:"악의, 기만적 의도",tip:"in good faith 와 반대입니다."},
          {t:"a reading",k:"business",m:"해석",tip:"같은 문장을 달리 이해하는 방식입니다."}]},
  {s:"B",en:"Then remove the boilerplate force majeure clause, because it came from a template nobody reviewed.",
   ko:"그럼 표준 불가항력 조항은 빼세요. 아무도 검토하지 않은 템플릿에서 온 거니까요.",
   notes:[{t:"boilerplate",k:"business",m:"정형화된 표준 문구",tip:"계약서에 관행적으로 들어가는 상투 조항입니다."},
          {t:"force majeure",k:"business",m:"불가항력",tip:"천재지변 등으로 이행이 면제되는 사유입니다."}]},
  {s:"A",en:"It has to stay, but I will narrow it, because a clause that excuses everything protects only them.",
   ko:"조항은 남아야 합니다. 다만 범위를 좁히겠습니다. 모든 것을 면책하는 조항은 상대만 보호하니까요.",
   notes:[{t:"narrow a clause",k:"business",m:"조항의 범위를 좁히다",tip:"적용 대상을 제한하는 수정입니다."},
          {t:"excuse",k:"business",m:"면책하다",tip:"의무 불이행에 책임을 묻지 않는 것입니다."}]},
  {s:"B",en:"Fine. And specify that verified cost increases pass through within a single billing cycle.",
   ko:"좋습니다. 그리고 확인된 원가 상승분이 한 번의 청구 주기 안에 전가된다고 명시해 주세요.",
   notes:[{t:"pass-through",k:"business",m:"원가 전가",tip:"비용 상승분을 가격에 옮기는 것입니다."},
          {t:"a billing cycle",k:"business",m:"청구 주기",tip:"청구서가 발행되는 기간 단위입니다."}]},
  {s:"A",en:"I can draft that. Do not promise a formula you have not tested against three years of past costs.",
   ko:"그건 제가 초안을 잡겠습니다. 3년 치 과거 원가로 검증하지 않은 산식은 약속하지 마세요.",
   notes:[{t:"draft",k:"business",m:"초안을 작성하다",tip:"계약서나 문서의 첫 판을 쓰는 것입니다."},
          {t:"test a formula against ~",k:"business",m:"산식을 ~ 에 대조해 검증하다",tip:"과거 데이터로 돌려 보는 것입니다."}]},
  {s:"B",en:"I have tested it, and it works unless energy and freight both rise sharply in the same quarter.",
   ko:"검증했습니다. 에너지와 운임이 같은 분기에 동시에 급등하지 않는 한 작동합니다.",
   notes:[{t:"unless ~",k:"grammar",m:"~ 하지 않는 한",tip:"예외 조건 하나를 지정합니다."},
          {t:"rise sharply",k:"collocation",m:"급등하다",tip:"fall sharply 와 짝을 이룹니다."}]}
 ],
 keys:[
  {en:"My real concern is ~",ko:"제 진짜 우려는 ~ 입니다",ex:"My real concern is the cap, not the index."},
  {en:"It is better to A than to B",ko:"B 하느니 A 하는 편이 낫다",ex:"It is better to reopen it now than to litigate it later."},
  {en:"provided that ~",ko:"~ 하는 조건이라면",ex:"That is workable, provided the true-up offsets shortfalls."},
  {en:"I can draft that.",ko:"그건 제가 초안을 잡겠습니다",ex:"I can draft that, but test the formula first."},
  {en:"index-linked",ko:"지수 연동의",ex:"The price is index-linked to the quarterly average."},
  {en:"a cap and a floor",ko:"가격 상한과 하한",ex:"You gave them a cap with no floor underneath it."},
  {en:"take-or-pay",ko:"인수하거나 대금을 내는 조항",ex:"Take-or-pay is how we recover the investment."},
  {en:"pass-through",ko:"원가 전가",ex:"Specify that verified increases pass through in one billing cycle."}
 ],
 out:[
  {q:"Ask what happens to a contract when a cost you do not control rises.",hint:"Before you ~, tell me ~ / index-linked / absorb a cost"},
  {q:"Identify the one clause you are most worried about and say why.",hint:"My real concern is ~ / a cap and a floor / close a deal"},
  {q:"Agree to a term with one precise condition attached.",hint:"provided that ~ / offset / a true-up"}
 ]
},
{
 id:"w2d5", day:12, cat:"안전·현장", level:"B2+",
 title:"The Accident That Was Waiting",
 titleKo:"예고되어 있던 사고 — 아차사고와 기준이 무너지는 방식",
 names:{A:"Dana (안전보건)", B:"Victor (생산 관리)"},
 brief:[
  "큰 사고는 어느 날 갑자기 오지 않는다. 그 앞에는 다치지 않고 지나간 <b>아차사고(near miss)</b>가 수없이 있다. 결과만 달랐을 뿐 원인은 같으므로, 아차사고는 값을 치르지 않고 얻는 교훈이다.",
  "기준은 한 번에 무너지지 않고 조금씩 밀린다. 급할 때 한 번 건너뛴 절차가 통하면 다음에도 건너뛰고, 예외가 반복되어 정상이 된다. 이것을 <b>일탈의 일상화(normalization of deviance)</b>라 부른다. 누구도 규칙을 어기기로 결심하지 않았는데 규칙이 사라져 있다.",
  "그래서 안전은 한 겹으로 설계하지 않는다. 방호장치, 절차, 점검, 교육을 <b>여러 겹으로 쌓아(layers of defence)</b> 한 겹에 난 구멍이 다른 겹에 막히게 한다. 사고는 구멍들이 한 줄로 늘어서는 드문 순간에 일어난다.",
  "지표는 둘로 나뉜다. 사고 건수처럼 이미 벌어진 뒤를 세는 <b>후행지표(lagging indicator)</b>와, 점검 이행률이나 아차사고 신고 건수처럼 앞을 내다보는 <b>선행지표(leading indicator)</b>다. 신고가 줄었다고 안전해진 것이 아니다 — 사람들이 말하기를 그만둔 것일 수도 있다."
 ],
 lines:[
  {s:"A",en:"Your line reported zero near misses last quarter, and that is exactly the number that concerns me.",
   ko:"그쪽 라인은 지난 분기 아차사고 신고가 0건이었습니다. 저를 우려하게 만드는 게 바로 그 숫자입니다.",
   notes:[{t:"a near miss",k:"business",m:"아차사고",tip:"사고로 이어질 뻔했으나 피해가 없었던 사건입니다."},
          {t:"concern someone",k:"business",m:"~ 를 우려하게 만들다",tip:"worry 보다 격식 있고 업무적입니다."}]},
  {s:"B",en:"Zero is good news. My crews are careful and nothing has gone wrong for several months.",
   ko:"0건은 좋은 소식입니다. 우리 작업조는 조심하고, 몇 달째 아무 일도 없었습니다.",
   notes:[{t:"a crew",k:"business",m:"작업조",tip:"현장에서 함께 일하는 인원 단위입니다."}]},
  {s:"A",en:"Or nothing was recorded, because crews stop reporting once a report has cost somebody something.",
   ko:"아니면 아무것도 기록되지 않은 겁니다. 신고가 누군가에게 대가를 치르게 한 뒤로는 작업조가 신고를 멈추니까요.",
   notes:[{t:"stop reporting",k:"collocation",m:"신고를 그만두다",tip:"보고 문화가 무너지는 상태를 말합니다."}]},
  {s:"B",en:"That is a serious accusation, so give me one instance where I punished someone for speaking up.",
   ko:"심각한 지적입니다. 그러니 제가 문제를 제기한 사람을 벌준 사례를 하나만 대 보세요.",
   notes:[{t:"speak up",k:"phrasal",m:"문제를 제기하다",tip:"침묵하지 않고 말하는 것입니다."},
          {t:"give me one instance",k:"business",m:"사례를 하나만 대 보세요",tip:"근거를 요구하는 직접적인 표현입니다."}]},
  {s:"A",en:"I am not accusing you. Pressure does not require a bad manager, because schedules create it on their own.",
   ko:"탓하는 게 아닙니다. 압박에 나쁜 관리자가 필요하지는 않습니다. 일정만으로도 생기니까요.",
   notes:[{t:"I am not accusing you.",k:"business",m:"탓하려는 게 아닙니다",tip:"비난이 아님을 먼저 분명히 하는 문장입니다."}]},
  {s:"B",en:"A near-miss form takes twenty minutes, and nobody has twenty minutes in the middle of production.",
   ko:"아차사고 양식은 20분이 걸리는데, 조업 중에는 아무도 20분이 없습니다.",
   notes:[{t:"in the middle of production",k:"collocation",m:"조업이 한창일 때",tip:"작업이 진행 중인 상황을 가리킵니다."}]},
  {s:"A",en:"Then the form is the problem. Make it thirty seconds on a phone, filled in at the machine.",
   ko:"그럼 양식이 문제입니다. 기계 옆에서 휴대폰으로 30초에 채우게 만드세요.",
   notes:[{t:"fill in a form",k:"collocation",m:"양식을 채우다",tip:"영국식은 fill in, 미국식은 fill out 입니다."}]},
  {s:"B",en:"Suppose I do that. What do you actually do with a hundred reports about people being careless?",
   ko:"그렇게 한다고 칩시다. 사람이 부주의했다는 신고 100건을 실제로 어떻게 하실 겁니까?",
   notes:[{t:"Suppose I do that.",k:"grammar",m:"그렇게 한다고 칩시다",tip:"가정을 받아들이고 다음 문제를 제기하는 형태입니다."}]},
  {s:"A",en:"I look for the reports that repeat, because the same event in the same place is a warning.",
   ko:"반복되는 신고를 찾습니다. 같은 자리에서 같은 일이 생기면 그건 경고니까요.",
   notes:[{t:"repeat",k:"business",m:"반복되다",tip:"패턴을 판별하는 기준입니다."}]},
  {s:"B",en:"So you want patterns rather than individual incidents, and I can work with that.",
   ko:"그럼 개별 사건이 아니라 패턴을 원하시는 거군요. 그거라면 같이 할 수 있습니다.",
   notes:[{t:"I can work with that.",k:"business",m:"그거라면 같이 할 수 있습니다",tip:"조건부 수용을 밝히는 실무 표현입니다."}]},
  {s:"A",en:"It must not become a scoreboard, because once reports count against a crew, the reports stop.",
   ko:"그게 점수판이 되어서는 안 됩니다. 신고가 작업조에 불리하게 계산되는 순간 신고가 멈추니까요.",
   notes:[{t:"count against ~",k:"phrasal",m:"~ 에게 불리하게 작용하다",tip:"평가에서 감점 요인이 되는 것입니다."}]},
  {s:"B",en:"Good, because the last program rewarded low numbers and everyone learned which events to report.",
   ko:"다행입니다. 지난 제도는 낮은 숫자에 상을 줬고, 다들 어떤 사건을 신고해야 하는지 배웠거든요.",
   notes:[{t:"reward low numbers",k:"collocation",m:"낮은 숫자에 보상하다",tip:"지표를 왜곡시키는 전형적인 설계 오류입니다."}]},
  {s:"A",en:"Injury counts are lagging indicators, which means they only tell you what has already happened.",
   ko:"재해 건수는 후행지표입니다. 이미 벌어진 일만 알려 준다는 뜻이죠.",
   notes:[{t:"a lagging indicator",k:"business",m:"후행지표",tip:"결과가 나온 뒤에야 움직이는 지표입니다."}]},
  {s:"B",en:"And the leading indicators are the inspections and drills that nobody notices until an audit?",
   ko:"그럼 선행지표는 감사가 오기 전까지 아무도 신경 쓰지 않는 점검과 훈련입니까?",
   notes:[{t:"a leading indicator",k:"business",m:"선행지표",tip:"결과보다 먼저 움직여 예측에 쓰이는 지표입니다."},
          {t:"a drill",k:"business",m:"훈련, 모의 연습",tip:"실제 상황을 가정해 반복하는 연습입니다."}]},
  {s:"A",en:"Those, but only if they are actually performed rather than signed, because a signature protects nobody.",
   ko:"그것들입니다. 다만 서명만 하는 게 아니라 실제로 수행될 때만입니다. 서명은 아무도 지켜 주지 않으니까요.",
   notes:[{t:"performed rather than signed",k:"collocation",m:"서명만 하는 게 아니라 실제로 수행되는",tip:"형식과 실질을 가르는 대비입니다."}]},
  {s:"B",en:"Standards do not collapse suddenly. They decline slowly, until one shortcut becomes the normal method.",
   ko:"기준은 갑자기 무너지지 않습니다. 천천히 낮아지다가, 지름길 하나가 정상적인 방법이 됩니다.",
   notes:[{t:"decline slowly",k:"collocation",m:"서서히 낮아지다",tip:"점진적 악화를 표현합니다."},
          {t:"a shortcut",k:"business",m:"지름길, 편법",tip:"규정된 절차를 건너뛰는 방식입니다."}]},
  {s:"A",en:"That process has a name: normalization of deviance, where an exception gradually becomes the standard.",
   ko:"그 과정에는 이름이 있습니다. 일탈의 일상화죠. 예외가 점차 기준이 되는 현상입니다.",
   notes:[{t:"normalization of deviance",k:"business",m:"일탈의 일상화",tip:"반복된 예외가 정상으로 받아들여지는 현상입니다."}]},
  {s:"B",en:"Then do not give me another poster. Give me the authority to stop the line without calling anyone.",
   ko:"그럼 포스터를 하나 더 주지 마세요. 누구에게도 전화하지 않고 라인을 세울 권한을 주십시오.",
   notes:[{t:"stop the line",k:"business",m:"생산 라인을 세우다",tip:"안전 문제에서 현장에 주어지는 권한입니다."},
          {t:"authority",k:"business",m:"권한",tip:"결정을 내릴 수 있는 공식적 자격입니다."}]},
  {s:"A",en:"You will have it in writing, and I will defend the decision to senior management myself.",
   ko:"문서로 드리겠습니다. 그리고 그 결정은 제가 직접 경영진에 설명하겠습니다.",
   notes:[{t:"in writing",k:"business",m:"문서로",tip:"구두가 아니라 기록으로 남긴다는 뜻입니다."},
          {t:"defend a decision to ~",k:"business",m:"~ 에게 결정을 설명해 내다",tip:"윗선의 반론을 받아 내겠다는 뜻입니다."}]},
  {s:"B",en:"Then we agree. Remember that the stopped hour has a visible cost and the prevented accident does not.",
   ko:"그럼 합의됐습니다. 멈춘 한 시간은 비용이 보이지만 막아 낸 사고는 보이지 않는다는 걸 기억해 주세요.",
   notes:[{t:"a visible cost",k:"business",m:"눈에 보이는 비용",tip:"측정되고 보고되는 비용입니다."},
          {t:"prevented",k:"business",m:"막아 낸, 예방된",tip:"일어나지 않았기에 증명하기 어려운 성과입니다."}]}
 ],
 keys:[
  {en:"Suppose I do that.",ko:"그렇게 한다고 칩시다",ex:"Suppose I do that. What happens to the hundred reports?"},
  {en:"I can work with that.",ko:"그거라면 같이 할 수 있습니다",ex:"You want patterns, not incidents. I can work with that."},
  {en:"I am not accusing you.",ko:"탓하려는 게 아닙니다",ex:"I am not accusing you. I am describing how pressure works."},
  {en:"give me one instance",ko:"사례를 하나만 대 보세요",ex:"Give me one instance where that actually happened."},
  {en:"a lagging indicator",ko:"후행지표",ex:"Injury counts are lagging indicators and tell you nothing early."},
  {en:"a leading indicator",ko:"선행지표",ex:"Leading indicators only help if the checks are actually performed."},
  {en:"normalization of deviance",ko:"일탈의 일상화",ex:"Normalization of deviance turns one shortcut into the method."},
  {en:"stop the line",ko:"생산 라인을 세우다",ex:"Give the crew authority to stop the line without a phone call."}
 ],
 out:[
  {q:"Explain why a report of zero problems can be worse than a report of several.",hint:"a near miss / stop reporting / count against ~"},
  {q:"Accept a hypothetical and then raise the practical problem with it.",hint:"Suppose I do that. / fill in a form / I can work with that."},
  {q:"Ask for authority instead of a policy, and say why.",hint:"authority / stop the line / in writing"}
 ]
},
{
 id:"w2d6", day:13, cat:"조직·성과관리", level:"B2+",
 title:"What Gets Measured Gets Gamed",
 titleKo:"재면 조작된다 — 지표가 목표가 될 때",
 names:{A:"Ruth (성과관리)", B:"Ali (현업 팀장)"},
 brief:[
  "조직은 재지 않으면 관리하지 못한다. 그런데 재기 시작하는 순간 지표는 단순한 관찰이 아니라 <b>목표</b>가 되고, 사람들은 일이 아니라 지표를 향해 움직이기 시작한다.",
  "대부분의 지표는 <b>대리 지표(proxy)</b>다. 정말 보고 싶은 것 — 고객이 만족했는지, 품질이 좋아졌는지 — 은 직접 재기 어려워서, 대신 세기 쉬운 것을 센다. 처리 건수, 응답 시간 같은 것들이다. 대리와 본체가 어긋나기 시작하면 지표는 그때부터 거짓말을 한다.",
  "지표가 목표가 되면 좋은 지표이기를 그친다 — <b>굿하트의 법칙(Goodhart's law)</b>. 여기서 중요한 것은 조작이 대개 부정행위가 아니라는 점이다. 걸린 보상에 대한 합리적인 반응일 뿐이고, 그래서 사람을 바꿔도 되풀이된다.",
  "실무의 해법은 완벽한 지표를 찾는 것이 아니라 <b>여러 지표를 묶어(a basket of measures)</b> 서로를 견제하게 두는 것이다. 처리 건수 옆에 재문의율을, 속도 옆에 재작업률을 놓는다. 하나는 속일 수 있어도 셋을 동시에 속이려면 대개 일을 제대로 하는 편이 빠르다."
 ],
 lines:[
  {s:"A",en:"Your team's closure rate doubled in two months, so either something extraordinary happened or the definition changed.",
   ko:"그쪽 팀 처리율이 두 달 만에 두 배가 됐습니다. 대단한 일이 일어났거나, 정의가 바뀐 겁니다.",
   notes:[{t:"either A or B",k:"grammar",m:"A이거나 B이거나",tip:"두 가지 가능성만 남기는 형태입니다."},
          {t:"closure rate",k:"business",m:"처리율, 종결률",tip:"접수된 건 중 종결 처리된 비율입니다."}]},
  {s:"B",en:"You asked for closure rate and you received closure rate. I would have preferred a better question.",
   ko:"처리율을 요구하셨고 처리율을 받으셨습니다. 저는 더 나은 질문을 받고 싶었습니다.",
   notes:[{t:"I would have preferred ~",k:"grammar",m:"저는 ~ 를 더 원했을 겁니다",tip:"실제와 다른 과거의 선호를 말합니다."}]},
  {s:"A",en:"That is not an answer. Tell me what changed in the actual work your team does.",
   ko:"그건 답이 아닙니다. 팀이 실제로 하는 일에서 무엇이 바뀌었는지 말해 주세요.",
   notes:[{t:"the actual work",k:"collocation",m:"실제 업무",tip:"보고된 숫자와 대비되는 현실의 작업입니다."}]},
  {s:"B",en:"Tickets are closed and then reopened, so the same problem returns under a new number each week.",
   ko:"티켓을 닫았다가 다시 엽니다. 그래서 같은 문제가 매주 새 번호로 돌아옵니다.",
   notes:[{t:"reopen",k:"business",m:"다시 열다",tip:"종결된 건을 재개하는 것입니다."}]},
  {s:"A",en:"So we count the same work twice and then report the result as an improvement.",
   ko:"그럼 같은 일을 두 번 세고, 그 결과를 개선으로 보고하는 겁니다.",
   notes:[{t:"report A as B",k:"business",m:"A를 B로 보고하다",tip:"해석을 붙여 상부에 올리는 행위입니다."}]},
  {s:"B",en:"Nobody cheated. You attached a target to people, and they did what the target rewarded.",
   ko:"아무도 속이지 않았습니다. 사람들에게 목표를 붙여 두셨고, 그 목표가 보상하는 대로 한 것입니다.",
   notes:[{t:"attach a target to ~",k:"business",m:"~ 에게 목표를 부과하다",tip:"평가 지표를 사람에게 연결하는 것입니다."}]},
  {s:"A",en:"I know. The measure stopped describing the work as soon as it became the target.",
   ko:"압니다. 그 지표는 목표가 되는 순간 일을 설명하기를 멈췄습니다.",
   notes:[{t:"as soon as ~",k:"grammar",m:"~ 하는 순간",tip:"전환 시점을 정확히 지정합니다."}]},
  {s:"B",en:"There is a name for this. A measure stops being a good measure once it becomes a target.",
   ko:"이 현상에는 이름이 있습니다. 지표는 목표가 되는 순간 좋은 지표이기를 멈춥니다.",
   notes:[{t:"There is a name for this.",k:"business",m:"이 현상에는 이름이 있습니다",tip:"개념을 소개하는 도입 문장입니다."}]},
  {s:"A",en:"Goodhart's law. It is not about dishonest people. It is about honest people responding to incentives.",
   ko:"굿하트의 법칙입니다. 부정직한 사람에 관한 것이 아니라, 인센티브에 반응하는 정직한 사람에 관한 것입니다.",
   notes:[{t:"Goodhart's law",k:"business",m:"굿하트의 법칙",tip:"지표가 목표가 되면 지표로서의 기능을 잃는다는 법칙입니다."},
          {t:"respond to incentives",k:"business",m:"유인에 반응하다",tip:"보상 구조에 따라 행동이 바뀌는 것입니다."}]},
  {s:"B",en:"Then measure whether the customer returned, because that is what the company actually cares about.",
   ko:"그럼 고객이 돌아왔는지를 재세요. 회사가 실제로 신경 쓰는 건 그것이니까요.",
   notes:[{t:"care about ~",k:"phrasal",m:"~ 를 중요하게 여기다",tip:"우선순위를 말합니다."}]},
  {s:"A",en:"Repeat contact is a slow and noisy proxy for satisfaction, and half of it is outside your control.",
   ko:"재문의는 만족도를 대신하는 느리고 잡음 많은 지표이고, 그중 절반은 그쪽 통제 밖입니다.",
   notes:[{t:"a proxy for ~",k:"business",m:"~ 를 대신하는 지표",tip:"직접 잴 수 없는 것을 대신 재는 수치입니다."},
          {t:"noisy",k:"business",m:"잡음이 많은, 편차가 큰",tip:"다른 요인이 많이 섞여 있다는 뜻입니다."}]},
  {s:"B",en:"Everything useful is slow and noisy. A clean number is clean because somebody removed something.",
   ko:"쓸모 있는 것은 전부 느리고 잡음이 많습니다. 깔끔한 숫자는 누군가 뭔가를 걷어냈기 때문에 깔끔한 겁니다.",
   notes:[{t:"remove something",k:"business",m:"제외하다, 걷어내다",tip:"데이터에서 항목을 빼는 것입니다."}]},
  {s:"A",en:"I cannot present 'it is complicated' to senior management, so I need this on one page.",
   ko:"저는 경영진에 「복잡합니다」를 제시할 수 없습니다. 그러니 이걸 한 장에 담아야 합니다.",
   notes:[{t:"present something to ~",k:"business",m:"~ 에게 제시하다",tip:"공식 보고의 표준 동사입니다."}]},
  {s:"B",en:"Then put three numbers on that page and let the board see where they disagree with each other.",
   ko:"그럼 그 한 장에 숫자 셋을 올리고, 이사회가 그것들이 어디서 어긋나는지 보게 하세요.",
   notes:[{t:"disagree with each other",k:"collocation",m:"서로 어긋나다",tip:"숫자나 자료가 일치하지 않는 상태입니다."}]},
  {s:"A",en:"A basket of measures, then: closure rate beside reopen rate, and volume beside queue length.",
   ko:"그럼 지표 묶음이군요. 처리율 옆에 재개율, 처리량 옆에 대기열 길이.",
   notes:[{t:"a basket of measures",k:"business",m:"지표 묶음",tip:"하나가 아니라 여러 지표를 함께 보는 방식입니다."},
          {t:"queue length",k:"business",m:"대기열 길이",tip:"처리를 기다리는 건수입니다."}]},
  {s:"B",en:"That is better. Any single number can be manipulated, but manipulating three at once usually requires real work.",
   ko:"그게 낫습니다. 숫자 하나는 조작할 수 있지만, 셋을 한꺼번에 조작하려면 대개 진짜 일을 해야 합니다.",
   notes:[{t:"manipulate a number",k:"business",m:"숫자를 조작하다",tip:"game a metric 의 평이한 표현입니다."}]},
  {s:"A",en:"Someone will still find a weakness in it, and I would rather hear about it from you first.",
   ko:"그래도 누군가는 그 안에서 허점을 찾아낼 겁니다. 저는 그걸 그쪽에게서 먼저 듣고 싶습니다.",
   notes:[{t:"find a weakness in ~",k:"collocation",m:"~ 에서 허점을 찾다",tip:"제도의 빈틈을 발견하는 것입니다."}]},
  {s:"B",en:"You will, if reporting it costs me nothing. The last team that raised a problem was blamed for it.",
   ko:"보고하는 게 제게 아무 대가도 없다면 그러실 겁니다. 지난번에 문제를 제기한 팀은 그 책임을 뒤집어썼습니다.",
   notes:[{t:"raise a problem",k:"business",m:"문제를 제기하다",tip:"공식적으로 알리는 것입니다."},
          {t:"be blamed for ~",k:"collocation",m:"~ 에 대해 비난받다",tip:"책임을 뒤집어쓰는 것입니다."}]},
  {s:"A",en:"That is our failure and I will change it, because a measure nobody may question is worse than none.",
   ko:"그건 우리 잘못이고 제가 바꾸겠습니다. 아무도 의문을 제기할 수 없는 지표는 없느니만 못하니까요.",
   notes:[{t:"That is our failure.",k:"business",m:"그건 우리 잘못입니다",tip:"책임을 조직 쪽으로 명확히 돌리는 문장입니다."}]},
  {s:"B",en:"Then we are making progress. Just do not trust the new numbers the way we trusted the old ones.",
   ko:"그럼 진전이 있습니다. 다만 예전 숫자를 믿었던 것처럼 새 숫자를 믿지는 마세요.",
   notes:[{t:"make progress",k:"collocation",m:"진전을 이루다",tip:"논의나 작업이 앞으로 나아가는 것입니다."}]}
 ],
 keys:[
  {en:"There is a name for this.",ko:"이 현상에는 이름이 있습니다",ex:"There is a name for this, and it explains the whole pattern."},
  {en:"I would have preferred ~",ko:"저는 ~ 를 더 원했을 겁니다",ex:"I would have preferred a better question in the first place."},
  {en:"That is our failure.",ko:"그건 우리 잘못입니다",ex:"That is our failure, not yours, and I will change it."},
  {en:"I cannot present A to B.",ko:"A를 B에게 제시할 수는 없습니다",ex:"I cannot present 'it is complicated' to the board."},
  {en:"Goodhart's law",ko:"굿하트의 법칙",ex:"Goodhart's law is about honest people responding to incentives."},
  {en:"a proxy for ~",ko:"~ 를 대신하는 지표",ex:"Repeat contact is a noisy proxy for satisfaction."},
  {en:"a basket of measures",ko:"지표 묶음",ex:"Use a basket of measures so no single number can be manipulated."},
  {en:"respond to incentives",ko:"유인에 반응하다",ex:"People respond to incentives, and the target was the incentive."}
 ],
 out:[
  {q:"Explain why a metric improved without the underlying work improving.",hint:"closure rate / reopen / attach a target to ~"},
  {q:"Introduce a named concept and explain it in plain words.",hint:"There is a name for this. / Goodhart's law / respond to incentives"},
  {q:"Propose replacing one number with several, and defend the extra complexity.",hint:"a basket of measures / a proxy for ~ / I cannot present A to B."}
 ]
},
{
 id:"w2d7", day:14, cat:"물류·운송", level:"B2+",
 title:"The Box That Waits",
 titleKo:"기다리는 컨테이너 — 체선료와 리드타임이라는 숨은 원가",
 names:{A:"Nadia (물류)", B:"Peter (생산계획)"},
 brief:[
  "운송 원가는 운임만이 아니다. 컨테이너가 항만에 서 있는 동안에도 값이 붙는다 — 터미널 안에 머무는 시간에 붙는 <b>체선료(demurrage)</b>와, 컨테이너를 끌고 나간 뒤 반납이 늦어질 때 붙는 <b>지체료(detention)</b>다.",
  "이 값은 벌금이 아니라 <b>회전율을 강제하는 가격</b>이다. 터미널과 선사는 한정된 자리와 장비가 묶이는 것을 싫어한다. 그래서 <b>무료 기간(free time)</b>을 짧게 두고 그 뒤부터는 시간을 판다. 창고를 빌려주는 것이 아니라, 오래 세워 둘 사람을 값으로 밀어내는 것이다.",
  "공장이 실제로 아파하는 것은 평균 리드타임이 아니라 <b>흔들림(variability)</b>이다. 늘 30일이면 계획이 서지만 20일과 45일을 오가면 그 차이만큼을 재고로 메워야 한다. 그렇게 쌓아 두는 것이 <b>안전재고(safety stock)</b>이고, 그것은 창고에 잠긴 현금이다.",
  "그래서 물류와 생산계획은 같은 돈을 서로 다른 계정에서 본다. 물류는 운임과 체선료를 보고, 생산은 멈춘 라인과 쌓인 재고를 본다. 각자의 예산에서 상대의 숫자가 보이지 않는다는 것 — 이것이 이 다툼의 진짜 뿌리다."
 ],
 lines:[
  {s:"A",en:"The demurrage invoice arrived this morning, and it is larger than the freight cost we argued about.",
   ko:"오늘 아침 체선료 청구서가 왔습니다. 우리가 다투던 운임보다 큽니다.",
   notes:[{t:"demurrage",k:"business",m:"체선료",tip:"무료 기간을 넘겨 컨테이너를 붙잡아 둘 때 내는 비용입니다."}]},
  {s:"B",en:"That is not my budget line. I only asked for those containers to wait until we had space.",
   ko:"그건 제 예산 항목이 아닙니다. 저는 자리가 날 때까지 그 컨테이너를 기다리게 해 달라고 했을 뿐입니다.",
   notes:[{t:"a budget line",k:"business",m:"예산 항목",tip:"비용이 계상되는 항목입니다. a line item 과 같습니다."}]},
  {s:"A",en:"Waiting is exactly what you are charged for, once the free time ends and billing begins.",
   ko:"기다리는 것 자체가 청구 대상입니다. 무료 기간이 끝나면 과금이 시작되니까요.",
   notes:[{t:"free time",k:"business",m:"무료 보관 기간",tip:"추가 요금 없이 컨테이너를 둘 수 있는 기간입니다."},
          {t:"be charged for ~",k:"grammar",m:"~ 에 대해 요금이 부과되다",tip:"수동으로 청구 사유를 말합니다."}]},
  {s:"B",en:"Then the free time is too short, because nobody unloads a full vessel within that period.",
   ko:"그럼 무료 기간이 너무 짧습니다. 그 기간 안에 배 한 척을 다 내리는 사람은 없으니까요.",
   notes:[{t:"unload a vessel",k:"business",m:"선박에서 화물을 내리다",tip:"load(싣다)와 짝입니다."}]},
  {s:"A",en:"It is short deliberately. The terminal is not renting storage. It is discouraging you from using the yard.",
   ko:"일부러 짧게 둔 겁니다. 터미널은 창고를 빌려주는 게 아니라, 야적장을 쓰지 못하게 막는 겁니다.",
   notes:[{t:"deliberately",k:"business",m:"의도적으로",tip:"on purpose 의 격식 있는 형태입니다."},
          {t:"discourage someone from ~ing",k:"grammar",m:"~ 하지 못하게 유도하다",tip:"금지가 아니라 비용으로 막는 방식입니다."}]},
  {s:"B",en:"My yard was full and the line was still running, so tell me what I should have done instead.",
   ko:"야적장은 꽉 찼고 라인은 계속 돌고 있었습니다. 그럼 대신 무엇을 했어야 하는지 말해 주세요.",
   notes:[{t:"What should I have done instead?",k:"grammar",m:"대신 무엇을 했어야 합니까",tip:"과거의 대안을 묻는 형태입니다."}]},
  {s:"A",en:"You could have told me a week earlier, because I can reserve slots when I know in advance.",
   ko:"일주일 전에 말해 주실 수 있었습니다. 미리 알면 자리를 예약할 수 있으니까요.",
   notes:[{t:"could have + 과거분사",k:"grammar",m:"~ 할 수 있었을 것이다",tip:"실현되지 않은 과거의 가능성을 말합니다."},
          {t:"reserve a slot",k:"business",m:"자리를 예약하다",tip:"항만이나 창고의 처리 시간대를 잡는 것입니다."}]},
  {s:"B",en:"I did not know either. The schedule moved twice because two orders were pulled forward without warning.",
   ko:"저도 몰랐습니다. 주문 두 건이 예고 없이 앞당겨지면서 일정이 두 번 움직였습니다.",
   notes:[{t:"pull forward",k:"phrasal",m:"일정을 앞당기다",tip:"push back(미루다)과 반대입니다."}]},
  {s:"A",en:"Then the real problem is the schedule, not demurrage, because your plan moves faster than my bookings.",
   ko:"그럼 진짜 문제는 체선료가 아니라 일정입니다. 계획이 제 예약보다 빨리 움직이니까요.",
   notes:[{t:"the real problem is A, not B",k:"business",m:"진짜 문제는 B가 아니라 A입니다",tip:"원인을 재지정하는 문장입니다."}]},
  {s:"B",en:"Plans always move. I would rather change a plan than hold stock that we cannot sell.",
   ko:"계획은 늘 움직입니다. 팔 수 없는 재고를 안고 있느니 계획을 바꾸겠습니다.",
   notes:[{t:"hold stock",k:"business",m:"재고를 안고 있다",tip:"보관 비용이 계속 발생하는 상태입니다."}]},
  {s:"A",en:"I understand, but every change costs money, and that cost appears in my budget rather than yours.",
   ko:"이해합니다. 다만 변경마다 비용이 들고, 그 비용은 그쪽이 아니라 제 예산에 나타납니다.",
   notes:[{t:"appear in a budget",k:"business",m:"예산에 나타나다",tip:"비용이 어느 부서로 귀속되는지를 말합니다."}]},
  {s:"B",en:"That is the whole problem in one sentence: we both reduce our own costs and the company pays twice.",
   ko:"그게 문제 전부를 한 문장으로 말한 겁니다. 둘 다 각자의 비용을 줄이고, 회사는 두 번 냅니다.",
   notes:[{t:"in one sentence",k:"collocation",m:"한 문장으로",tip:"요약을 예고하는 표현입니다."}]},
  {s:"A",en:"So let us stop optimizing separately. Give me a rolling forecast, even an approximate one.",
   ko:"그러니 따로따로 최적화하는 것을 그만둡시다. 대략적이라도 굴러가는 예측을 주세요.",
   notes:[{t:"a rolling forecast",k:"business",m:"롤링 예측",tip:"기간이 지날 때마다 갱신되는 이동식 예측입니다."},
          {t:"optimize separately",k:"business",m:"각자 따로 최적화하다",tip:"부분 최적이 전체를 악화시키는 상황입니다."}]},
  {s:"B",en:"How approximate before it becomes useless? I cannot promise numbers that have no orders behind them.",
   ko:"얼마나 대략적이면 쓸모없어집니까? 뒤에 주문이 없는 숫자는 약속할 수 없습니다.",
   notes:[{t:"have orders behind ~",k:"collocation",m:"뒤에 실제 주문이 있다",tip:"근거가 있는 숫자인지를 말합니다."}]},
  {s:"A",en:"Approximate is acceptable. What damages me is silence, because silence means no change has occurred.",
   ko:"대략적이어도 괜찮습니다. 저를 곤란하게 하는 건 침묵입니다. 침묵은 변경이 없었다는 뜻이니까요.",
   notes:[{t:"What damages me is ~",k:"business",m:"저를 곤란하게 하는 것은 ~ 입니다",tip:"문제의 핵심을 앞세우는 강조 구문입니다."}]},
  {s:"B",en:"Then help me with lead times, which vary by as much as three weeks from order to delivery.",
   ko:"그럼 리드타임을 도와주세요. 주문에서 납품까지가 최대 3주씩 달라집니다.",
   notes:[{t:"lead time",k:"business",m:"리드타임",tip:"주문에서 납품까지 걸리는 시간입니다."},
          {t:"vary by ~",k:"collocation",m:"~ 만큼 차이가 나다",tip:"변동 폭을 수치로 말합니다."}]},
  {s:"A",en:"That is what safety stock is for, and it is not free, because the variability is held as cash.",
   ko:"그게 안전재고의 역할입니다. 그리고 공짜가 아닙니다. 그 변동성이 현금으로 묶여 있으니까요.",
   notes:[{t:"safety stock",k:"business",m:"안전재고",tip:"수요와 납기 변동에 대비해 두는 여유 재고입니다."},
          {t:"variability",k:"business",m:"변동성",tip:"수치가 흔들리는 정도입니다."}]},
  {s:"B",en:"So I buy certainty with inventory, and you buy the same certainty with advance bookings.",
   ko:"그럼 저는 재고로 확실성을 사고, 그쪽은 같은 확실성을 사전 예약으로 사는 거군요.",
   notes:[{t:"buy certainty with ~",k:"collocation",m:"~ 로 확실성을 사다",tip:"불확실성을 줄이는 대가를 표현합니다."}]},
  {s:"A",en:"Correct. Let us put both costs on one page and let whoever owns the total budget decide.",
   ko:"맞습니다. 두 비용을 한 장에 올리고, 총예산을 책임지는 사람이 결정하게 합시다.",
   notes:[{t:"own a budget",k:"business",m:"예산을 책임지다",tip:"집행 권한과 책임을 함께 가진 상태입니다."}]},
  {s:"B",en:"I agree to that, provided nobody uses the page to decide which of us made the mistake.",
   ko:"동의합니다. 다만 둘 중 누가 잘못했는지 가리는 데 그 장표를 쓰지 않는다는 조건입니다.",
   notes:[{t:"provided nobody ~",k:"grammar",m:"아무도 ~ 하지 않는다는 조건으로",tip:"합의에 단서를 붙이는 형태입니다."}]}
 ],
 keys:[
  {en:"What should I have done instead?",ko:"대신 무엇을 했어야 합니까",ex:"My yard was full. What should I have done instead?"},
  {en:"the real problem is A, not B",ko:"진짜 문제는 B가 아니라 A입니다",ex:"The real problem is the schedule, not the invoice."},
  {en:"What damages me is ~",ko:"저를 곤란하게 하는 것은 ~ 입니다",ex:"What damages me is silence, not a change of plan."},
  {en:"provided nobody ~",ko:"아무도 ~ 하지 않는다는 조건으로",ex:"I agree, provided nobody uses it to assign blame."},
  {en:"demurrage",ko:"체선료",ex:"The demurrage invoice was larger than the freight cost."},
  {en:"lead time",ko:"리드타임",ex:"Lead times vary by as much as three weeks."},
  {en:"a rolling forecast",ko:"롤링 예측",ex:"Give me a rolling forecast, even an approximate one."},
  {en:"safety stock",ko:"안전재고",ex:"Safety stock is how we absorb variability, and it costs cash."}
 ],
 out:[
  {q:"Explain a charge your colleague did not know they were creating.",hint:"demurrage / free time / be charged for ~"},
  {q:"Reassign a problem from the symptom to its actual cause.",hint:"the real problem is A, not B / pull forward / reserve a slot"},
  {q:"Agree to share information, and attach one condition.",hint:"a rolling forecast / What damages me is ~ / provided nobody ~"}
 ]
},
{
 id:"w2d8", day:15, cat:"의사결정", level:"B2+",
 title:"The Project Nobody Will Kill",
 titleKo:"아무도 끝내지 못하는 프로젝트 — 매몰비용과 멈추는 기술",
 names:{A:"Helen (재무)", B:"Raj (프로젝트 책임)"},
 brief:[
  "이미 쓴 돈은 <b>매몰비용(sunk cost)</b>이다. 무엇을 하든 회수되지 않으므로 앞으로의 판단에 넣어서는 안 된다. 지금 물어야 할 것은 「지금까지 얼마를 썼나」가 아니라 「앞으로 쓸 돈이 값어치를 하는가」뿐이다.",
  "그런데 사람은 쓴 돈이 클수록 그만두기 어려워한다. 계속하는 편이 유리해서가 아니라, 멈추는 순간 그동안의 판단이 틀렸다고 인정하는 일이 되기 때문이다. 이것을 <b>집착의 확대(escalation of commitment)</b>라 부른다.",
  "조직은 이 함정을 개인의 의지로 막지 못한다. 그래서 <b>단계별 관문(stage gate)</b>을 미리 세워 둔다. 다음 단계로 갈 자격을 매번 새로 증명하게 하는 장치이고, 핵심은 기준을 <b>숫자가 나오기 전에</b> 합의해 두는 것이다.",
  "관문이 실제로 작동하려면 <b>멈추는 것이 실패가 아니어야</b> 한다. 중단을 말한 사람이 불이익을 받는 조직에서는 아무도 관문에서 손을 들지 않고, 보고서는 전부 노란불이 되며, 관문은 서명 절차로 전락한다."
 ],
 lines:[
  {s:"A",en:"We are eighteen months into this project, and I want to ask whether it should continue.",
   ko:"이 프로젝트에 들어온 지 열여덟 달입니다. 계속해야 하는지 묻고 싶습니다.",
   notes:[{t:"be ~ into a project",k:"grammar",m:"프로젝트에 ~ 만큼 들어와 있다",tip:"경과 기간을 말하는 형태입니다."}]},
  {s:"B",en:"We have completed two thirds of it, so stopping now discards everything we have already spent.",
   ko:"3분의 2를 마쳤습니다. 지금 멈추면 지금까지 쓴 것을 전부 버리게 됩니다.",
   notes:[{t:"discard",k:"business",m:"버리다, 폐기하다",tip:"throw away 보다 격식 있습니다."}]},
  {s:"A",en:"That money is a sunk cost and it is gone in both cases. The question is whether the next year is worth it.",
   ko:"그 돈은 매몰비용이고 어느 쪽이든 이미 나갔습니다. 질문은 앞으로의 1년이 값어치가 있느냐입니다.",
   notes:[{t:"a sunk cost",k:"business",m:"매몰비용",tip:"이미 지출되어 회수할 수 없는 비용입니다. 의사결정에서 제외해야 합니다."},
          {t:"in both cases",k:"collocation",m:"어느 쪽이든",tip:"두 선택지 모두에서 결과가 같다는 뜻입니다."}]},
  {s:"B",en:"That is simple to say from finance, when my team has worked on nothing else for a year.",
   ko:"우리 팀은 1년 동안 다른 일을 하지 않았는데, 재무에서는 말하기 쉬운 얘기입니다.",
   notes:[{t:"work on nothing else",k:"collocation",m:"다른 일은 하지 않다",tip:"전념했다는 것을 강조하는 표현입니다."}]},
  {s:"A",en:"I am not calling the work wasted. I am saying the reason we started has changed and nobody checked.",
   ko:"그 일이 헛되다는 게 아닙니다. 시작한 이유가 바뀌었는데 아무도 확인하지 않았다는 얘기입니다.",
   notes:[{t:"I am not A. I am B.",k:"grammar",m:"저는 A가 아니라 B라고 말하는 겁니다",tip:"오해를 즉시 바로잡는 두 문장 골격입니다."}]},
  {s:"B",en:"That is correct. The business case was built on volumes that never materialized.",
   ko:"맞습니다. 사업 근거는 끝내 실현되지 않은 물량 위에 세워졌습니다.",
   notes:[{t:"a business case",k:"business",m:"사업 타당성 근거",tip:"왜 이 투자를 해야 하는지를 정리한 문서입니다."},
          {t:"materialize",k:"business",m:"실현되다",tip:"예상한 일이 실제로 일어나는 것입니다."}]},
  {s:"A",en:"That is what I needed to hear, because your status reports have been amber for four consecutive quarters.",
   ko:"그 말을 들어야 했습니다. 보고서가 네 분기 연속 노란색이었거든요.",
   notes:[{t:"amber",k:"business",m:"황색 경고 상태",tip:"녹색은 정상, 적색은 위험, 황색은 주의입니다."},
          {t:"consecutive",k:"business",m:"연속된",tip:"four consecutive quarters = 네 분기 연속."}]},
  {s:"B",en:"People write amber because red produces a meeting like this one and green produces no attention.",
   ko:"사람들이 노란색을 쓰는 이유는, 빨간색은 이런 회의를 부르고 초록색은 관심을 못 받기 때문입니다.",
   notes:[{t:"produce attention",k:"collocation",m:"관심을 불러오다",tip:"결과를 만들어 낸다는 뜻의 중립적 동사입니다."}]},
  {s:"A",en:"Then the reporting system is broken, and I would rather fix that than argue from bad information.",
   ko:"그럼 보고 체계가 망가진 겁니다. 나쁜 정보 위에서 다투느니 그걸 고치겠습니다.",
   notes:[{t:"argue from bad information",k:"collocation",m:"잘못된 정보를 근거로 다투다",tip:"전제가 틀린 논쟁을 가리킵니다."}]},
  {s:"B",en:"Fix it by making red a safe thing to report, because at the moment stopping is treated as failure.",
   ko:"빨간색을 보고해도 안전하게 만들어서 고치세요. 지금은 멈추는 것이 실패로 취급됩니다.",
   notes:[{t:"a safe thing to report",k:"collocation",m:"보고해도 안전한 것",tip:"심리적 안전의 조건을 평이하게 표현합니다."}]},
  {s:"A",en:"Agreed, and that is the company's failure, because ending a project early should count as good judgment.",
   ko:"동의합니다. 그건 회사의 잘못입니다. 프로젝트를 일찍 끝내는 건 좋은 판단으로 인정돼야 하니까요.",
   notes:[{t:"count as ~",k:"phrasal",m:"~ 로 인정되다, ~ 로 간주되다",tip:"평가 기준을 말합니다."}]},
  {s:"B",en:"Then say that in the meeting, because everyone saw what happened to the last person who stopped one.",
   ko:"그럼 회의에서 그렇게 말해 주세요. 지난번에 프로젝트를 멈춘 사람이 어떻게 됐는지 다들 봤으니까요.",
   notes:[{t:"say that in the meeting",k:"collocation",m:"회의에서 그렇게 말하다",tip:"공개적으로 밝히는 것이 핵심입니다."}]},
  {s:"A",en:"I will, but I still need a decision, and I would rather get it from you than from a spreadsheet.",
   ko:"그러겠습니다. 다만 결정은 여전히 필요하고, 스프레드시트보다 그쪽에게서 듣고 싶습니다.",
   notes:[{t:"get a decision from ~",k:"collocation",m:"~ 에게서 결정을 받다",tip:"책임 있는 판단을 요구하는 것입니다."}]},
  {s:"B",en:"Give me a stage gate with real criteria and I will accept the outcome, whatever it is.",
   ko:"진짜 기준이 있는 단계 관문을 주시면, 결과가 무엇이든 받아들이겠습니다.",
   notes:[{t:"a stage gate",k:"business",m:"단계 관문",tip:"다음 단계로 넘어갈지 판정하는 공식 심사 지점입니다."},
          {t:"criteria",k:"business",m:"판정 기준",tip:"criterion 의 복수형입니다."}]},
  {s:"A",en:"That is reasonable. Three conditions, measured at quarter end, and all agreed in advance of the quarter.",
   ko:"합리적입니다. 조건 셋, 분기 말에 측정, 그리고 전부 분기에 앞서 사전 합의.",
   notes:[{t:"agreed in advance",k:"collocation",m:"사전에 합의된",tip:"나중에 바꿀 수 없다는 점이 핵심입니다."}]},
  {s:"B",en:"Agreeing in advance is the part that matters, because criteria written afterwards only justify a decision already made.",
   ko:"사전 합의가 핵심입니다. 나중에 쓴 기준은 이미 내려진 결정을 정당화할 뿐이니까요.",
   notes:[{t:"justify a decision",k:"business",m:"결정을 정당화하다",tip:"사후에 근거를 붙이는 것을 가리킵니다."}]},
  {s:"A",en:"You will have them in writing this week, and if the project passes, the funding continues automatically.",
   ko:"이번 주에 문서로 드리겠습니다. 통과하면 예산은 자동으로 이어집니다.",
   notes:[{t:"funding",k:"business",m:"예산 지원",tip:"프로젝트에 배정된 자금입니다."}]},
  {s:"B",en:"And if it does not pass, I want to reassign the team quickly rather than leave them waiting.",
   ko:"통과하지 못하면, 팀을 기다리게 두지 말고 빨리 재배치하고 싶습니다.",
   notes:[{t:"reassign",k:"business",m:"재배치하다",tip:"다른 업무로 인력을 옮기는 것입니다."}]},
  {s:"A",en:"I can promise that, because the worst part of stopping a project is the silence that follows.",
   ko:"그건 약속할 수 있습니다. 프로젝트를 멈출 때 최악은 그 뒤에 이어지는 침묵이니까요.",
   notes:[{t:"the worst part of ~",k:"grammar",m:"~ 에서 가장 나쁜 점",tip:"문제의 핵심을 지목하는 형태입니다."}]},
  {s:"B",en:"Then let us put it in writing, because I would rather be judged on criteria than on impressions.",
   ko:"그럼 문서로 남깁시다. 저는 인상보다 기준으로 평가받는 편이 낫습니다.",
   notes:[{t:"be judged on ~",k:"grammar",m:"~ 를 기준으로 평가받다",tip:"평가의 근거를 지정합니다."},
          {t:"an impression",k:"business",m:"인상, 주관적 느낌",tip:"criteria 와 대비되는 판단 근거입니다."}]}
 ],
 keys:[
  {en:"I am not A. I am B.",ko:"저는 A가 아니라 B라고 말하는 겁니다",ex:"I am not calling it wasted. I am saying the reason changed."},
  {en:"count as ~",ko:"~ 로 인정되다",ex:"Ending a project early should count as good judgment."},
  {en:"agreed in advance",ko:"사전에 합의된",ex:"Three conditions, all agreed in advance, measured at quarter end."},
  {en:"be judged on ~",ko:"~ 를 기준으로 평가받다",ex:"I would rather be judged on criteria than on impressions."},
  {en:"a sunk cost",ko:"매몰비용",ex:"That money is a sunk cost and it is gone in both cases."},
  {en:"a business case",ko:"사업 타당성 근거",ex:"The business case was built on volumes that never materialized."},
  {en:"a stage gate",ko:"단계 관문",ex:"Give me a stage gate with real criteria and I will accept it."},
  {en:"reassign",ko:"재배치하다",ex:"If it fails, reassign the team quickly instead of leaving them waiting."}
 ],
 out:[
  {q:"Explain why money already spent should not decide what happens next.",hint:"a sunk cost / in both cases / materialize"},
  {q:"Correct a misunderstanding about what you are actually arguing.",hint:"I am not A. I am B. / argue from bad information / count as ~"},
  {q:"Ask for a decision process instead of a decision, and say what it must contain.",hint:"a stage gate / criteria / agreed in advance"}
 ]
}
