{
 id:"w3d1", day:16, cat:"투자·시장", level:"B2+",
 title:"Why Cheap Stays Cheap",
 titleKo:"싼 주식은 왜 계속 싼가 — 저평가와 밸류 트랩",
 names:{A:"Mina (리서치)", B:"Dohyun (개인 투자자)"},
 brief:[
  "주식이 싸다는 말은 대개 <b>이익 대비 값</b>이 낮다는 뜻입니다. 그것을 재는 가장 흔한 잣대가 주가수익비율(PER)이고, 영어로는 <b>trade at X times earnings</b>라고 말합니다. 「PER이 4배다」가 아니라 「이익의 네 배에 거래된다」고 표현하는 것이 자연스럽습니다.",
  "문제는 싼 데는 대개 이유가 있다는 점입니다. 시장이 그 회사의 이익을 <b>지속되지 않을 이익</b>으로 보거나, 지배구조·배당·업황 주기를 할인 요인으로 잡고 있을 수 있습니다. 싸 보이지만 계속 싼 채로 머무는 주식을 <b>value trap(밸류 트랩)</b>이라 부릅니다.",
  "그래서 던져야 할 질문은 「싼가」가 아니라 <b>What's driving the price?(무엇이 주가를 움직이는가)</b>입니다. 할인의 이유가 사라질 수 있는 것인지, 구조적으로 남는 것인지에 따라 답이 갈립니다.",
  "손실을 말하는 영어도 정해져 있습니다. <b>I'm down forty percent</b>가 가장 자연스럽고, 평가손실을 안고 있다는 뜻으로 <b>sitting on a loss</b>를 씁니다. 팔지 않고 계속 들고 가겠다는 말은 <b>hold on to</b>입니다."
 ],
 lines:[
  {s:"A",en:"You have held this position at a loss for a while, so how far below your entry price are you?",
   ko:"이 종목을 손실 상태로 한참 들고 계셨는데, 매수가보다 얼마나 아래에 있습니까?",
   notes:[{t:"hold a position",k:"business",m:"포지션을 보유하다",tip:"주식이나 자산을 들고 있는 상태입니다."},
          {t:"an entry price",k:"business",m:"매수가, 진입 가격",tip:"처음 산 가격입니다. exit price 와 짝입니다."}]},
  {s:"B",en:"About forty percent down, and I stopped opening the application for a couple of months.",
   ko:"40퍼센트쯤 내려와 있고, 두어 달은 앱을 열지 않았습니다.",
   notes:[{t:"be forty percent down",k:"business",m:"40퍼센트 하락한 상태다",tip:"손실 폭을 말하는 표준 표현입니다."}]},
  {s:"A",en:"What is your reason for holding it from today's price, rather than from the price you paid?",
   ko:"본인이 지불한 가격이 아니라 오늘 가격을 기준으로, 계속 들고 있을 이유는 무엇입니까?",
   notes:[{t:"from today's price",k:"collocation",m:"오늘 가격을 기준으로",tip:"매몰비용을 배제하고 판단하라는 요구입니다."}]},
  {s:"B",en:"It trades at four times earnings, while the American company doing the same work trades at thirteen.",
   ko:"이익의 네 배에 거래됩니다. 같은 일을 하는 미국 기업은 열세 배에 거래되고요.",
   notes:[{t:"trade at X times earnings",k:"business",m:"이익의 X배에 거래되다",tip:"PER 을 말하는 실무 표현입니다."}]},
  {s:"A",en:"On that single number it looks cheap, but a low price alone is not an investment reason.",
   ko:"그 숫자 하나로는 싸 보입니다. 다만 가격이 낮다는 것만으로는 투자 근거가 되지 않습니다.",
   notes:[{t:"an investment reason",k:"business",m:"투자 근거",tip:"왜 사야 하는지에 대한 논리입니다."}]},
  {s:"B",en:"Why not? If the earnings are genuine, the gap between the two should close eventually.",
   ko:"왜 안 됩니까? 이익이 진짜라면 두 회사의 격차는 결국 좁혀져야 합니다.",
   notes:[{t:"close a gap",k:"collocation",m:"격차가 좁혀지다",tip:"narrow the gap 도 같은 뜻입니다."}]},
  {s:"A",en:"Only if the market believes those earnings will continue, and it may be pricing in a downturn.",
   ko:"그 이익이 계속된다고 시장이 믿을 때만입니다. 시장은 경기 하강을 가격에 반영하고 있을 수도 있습니다.",
   notes:[{t:"price in ~",k:"business",m:"~ 를 가격에 미리 반영하다",tip:"시장이 예상을 주가에 넣어 두는 것입니다."},
          {t:"a downturn",k:"business",m:"경기 하강",tip:"upturn(경기 상승)과 반대입니다."}]},
  {s:"B",en:"You are saying the earnings I am looking at are near the peak of the business cycle.",
   ko:"제가 보고 있는 이익이 경기 순환의 정점 근처라는 말씀이군요.",
   notes:[{t:"the business cycle",k:"business",m:"경기 순환",tip:"확장과 수축을 반복하는 경제의 주기입니다."}]},
  {s:"A",en:"That is one interpretation. Cyclical earnings appear cheapest immediately before they decline.",
   ko:"그건 하나의 해석입니다. 경기민감 이익은 하락 직전에 가장 싸 보입니다.",
   notes:[{t:"an interpretation",k:"business",m:"해석",tip:"하나의 읽는 방식임을 밝히는 단어입니다."},
          {t:"cyclical",k:"business",m:"경기에 민감한",tip:"경기 순환에 따라 실적이 크게 오르내리는 성격입니다."}]},
  {s:"B",en:"The discount has been there for several years, through more than one complete cycle.",
   ko:"그 할인은 몇 년째 있었습니다. 완전한 순환을 한 번 이상 지나는 동안에도요.",
   notes:[{t:"a discount",k:"business",m:"할인, 저평가 폭",tip:"동종 기업 대비 낮게 평가된 정도입니다."}]},
  {s:"A",en:"Then the cause is not the cycle. Something structural is keeping the price down permanently.",
   ko:"그럼 원인은 순환이 아닙니다. 구조적인 무언가가 주가를 계속 눌러 두고 있습니다.",
   notes:[{t:"structural",k:"business",m:"구조적인",tip:"일시적이 아니라 근본적인 원인을 가리킵니다."}]},
  {s:"B",en:"Such as what? Governance, the dividend policy, or the fact that no analyst covers the company?",
   ko:"예를 들면 무엇입니까? 지배구조, 배당 정책, 아니면 어떤 애널리스트도 분석하지 않는다는 사실?",
   notes:[{t:"governance",k:"business",m:"지배구조",tip:"경영진과 주주의 관계, 의사결정 구조입니다."},
          {t:"cover a company",k:"business",m:"기업을 분석하다",tip:"증권사가 정기적으로 보고서를 내는 것입니다."}]},
  {s:"A",en:"Any of those. A discount with a permanent cause is a value trap, not a buying opportunity.",
   ko:"그중 무엇이든요. 원인이 영구적인 할인은 매수 기회가 아니라 가치 함정입니다.",
   notes:[{t:"a value trap",k:"business",m:"가치 함정",tip:"싸 보이지만 영원히 싼 채로 남는 주식입니다."}]},
  {s:"B",en:"How do I distinguish the two before I put more money into the position?",
   ko:"포지션에 돈을 더 넣기 전에, 그 둘을 어떻게 구별합니까?",
   notes:[{t:"distinguish A from B",k:"business",m:"A와 B를 구별하다",tip:"tell apart 의 격식 있는 형태입니다."}]},
  {s:"A",en:"Ask what would have to change for the discount to disappear, and ask who would notice the change.",
   ko:"그 할인이 사라지려면 무엇이 바뀌어야 하는지 묻고, 그 변화를 누가 알아챌지 물으세요.",
   notes:[{t:"What would have to change for ~ ?",k:"business",m:"~ 하려면 무엇이 바뀌어야 합니까",tip:"막연한 기대를 조건으로 바꾸는 질문입니다."}]},
  {s:"B",en:"That is a better question than the one I have been asking myself for a year.",
   ko:"제가 1년 동안 스스로에게 던져 온 질문보다 나은 질문입니다.",
   notes:[{t:"ask oneself",k:"collocation",m:"스스로에게 묻다",tip:"자기 점검을 표현합니다."}]},
  {s:"A",en:"Most people ask whether a stock is cheap. The useful question is what is setting the price.",
   ko:"대부분은 주식이 싼지를 묻습니다. 쓸모 있는 질문은 무엇이 그 가격을 정하고 있는가입니다.",
   notes:[{t:"set the price",k:"collocation",m:"가격을 결정하다",tip:"가격 형성의 주체나 요인을 말합니다."}]},
  {s:"B",en:"I remain positive on the sector overall. I simply cannot justify the timing to myself.",
   ko:"업종 전체에 대해서는 여전히 긍정적입니다. 다만 시점을 스스로에게 정당화하지 못하겠습니다.",
   notes:[{t:"remain positive on ~",k:"business",m:"~ 에 대해 긍정적인 입장을 유지하다",tip:"bullish 의 평이한 표현입니다."},
          {t:"justify",k:"business",m:"정당화하다",tip:"근거를 대어 타당함을 보이는 것입니다."}]},
  {s:"A",en:"Then size the position so the timing does not matter, because confidence is not the same as certainty.",
   ko:"그럼 시점이 중요하지 않을 만큼만 비중을 잡으세요. 확신은 확실성과 같지 않으니까요.",
   notes:[{t:"size a position",k:"business",m:"비중을 정하다",tip:"얼마나 담을지 결정하는 것입니다."},
          {t:"A is not the same as B",k:"grammar",m:"A는 B와 같지 않다",tip:"혼동되는 두 개념을 가르는 문장입니다."}]},
  {s:"B",en:"I accept that. I will keep the position, but I will stop adding to it without a reason.",
   ko:"받아들이겠습니다. 포지션은 유지하되, 근거 없이 더 사는 것은 그만두겠습니다.",
   notes:[{t:"add to a position",k:"business",m:"비중을 늘리다",tip:"추가 매수를 뜻합니다."}]}
 ],
 keys:[
  {en:"What would have to change for ~ ?",ko:"~ 하려면 무엇이 바뀌어야 합니까",ex:"What would have to change for this discount to disappear?"},
  {en:"A is not the same as B",ko:"A는 B와 같지 않다",ex:"Confidence is not the same as certainty."},
  {en:"from today's price",ko:"오늘 가격을 기준으로",ex:"Judge it from today's price, not from what you paid."},
  {en:"That is one interpretation.",ko:"그건 하나의 해석입니다",ex:"That is one interpretation, and here is another."},
  {en:"price in ~",ko:"~ 를 가격에 미리 반영하다",ex:"The market may already be pricing in a downturn."},
  {en:"a value trap",ko:"가치 함정",ex:"A discount with a permanent cause is a value trap."},
  {en:"size a position",ko:"비중을 정하다",ex:"Size the position so the timing does not matter."},
  {en:"trade at X times earnings",ko:"이익의 X배에 거래되다",ex:"It trades at four times earnings and the peer at thirteen."}
 ],
 out:[
  {q:"Explain why a low price alone is not a reason to buy.",hint:"trade at X times earnings / an investment reason / price in ~"},
  {q:"Distinguish a temporary discount from a permanent one.",hint:"cyclical / structural / a value trap"},
  {q:"Give advice that removes the need to predict timing.",hint:"size a position / A is not the same as B / add to a position"}
 ]
},
{
 id:"w3d2", day:17, cat:"투자·자산배분", level:"B2+",
 title:"The Ten Percent Rule",
 titleKo:"10퍼센트의 규칙 — 헤지와 비중, 그리고 정치",
 names:{A:"Sena (자산배분 담당)", B:"Won (동료)"},
 brief:[
  "헤지는 수익을 노리는 것이 아니라 <b>다른 자산이 무너질 때 버텨 줄 것</b>을 사 두는 일입니다. 그래서 금 이야기를 할 때 「오를까요」가 아니라 「무엇에 대비하는가」를 먼저 묻습니다. 영어로는 <b>hedge against inflation</b>처럼 against 뒤에 대비 대상을 씁니다.",
  "핵심은 <b>비중(position sizing)</b>입니다. 좋은 자산이라도 비중이 과하면 포트폴리오 전체가 그 자산이 되어 버립니다. 「전체의 10퍼센트를 넘기지 않는다」는 <b>account for no more than ten percent</b>로 말합니다.",
  "정치와 시장의 관계도 자주 오르내립니다. 정부가 시장을 인위적으로 떠받친다는 뜻으로 <b>prop up the market</b>을 쓰고, 선거가 끝나면 그럴 <b>유인(incentive)</b>이 줄어든다는 식으로 이어집니다. 다만 이런 이야기는 근거가 약할 때가 많아, 토론에서는 반박을 받습니다.",
  "마지막은 <b>규칙으로 만들기</b>입니다. 예측이 아니라 절차로 정해 두는 것 — 매달 같은 금액을 넣고, 비중이 어긋나면 되돌리는 <b>rebalance</b>가 그것입니다. 감정이 개입할 자리를 미리 줄이는 방법입니다."
 ],
 lines:[
  {s:"A",en:"You said you want to buy gold again, so tell me exactly what risk you are protecting against.",
   ko:"금을 다시 사고 싶다고 하셨는데, 정확히 어떤 위험에 대비하려는 건지 말해 주세요.",
   notes:[{t:"protect against a risk",k:"business",m:"위험에 대비하다",tip:"hedge against 의 평이한 표현입니다."}]},
  {s:"B",en:"Inflation, mainly. I want an asset that holds its value when cash loses purchasing power.",
   ko:"주로 인플레이션입니다. 현금이 구매력을 잃을 때 값어치를 유지하는 자산을 원합니다.",
   notes:[{t:"purchasing power",k:"business",m:"구매력",tip:"같은 돈으로 살 수 있는 양입니다."},
          {t:"hold its value",k:"collocation",m:"값어치를 유지하다",tip:"가격이 크게 떨어지지 않는다는 뜻입니다."}]},
  {s:"A",en:"That is a reason, not a target. What percentage of the portfolio are you actually proposing?",
   ko:"그건 이유지 목표가 아닙니다. 포트폴리오의 몇 퍼센트를 제안하시는 겁니까?",
   notes:[{t:"That is a reason, not a target.",k:"business",m:"그건 이유지 목표가 아닙니다",tip:"동기와 수치를 구분하라고 요구하는 문장입니다."}]},
  {s:"B",en:"Something small. I do not want it to account for more than ten percent of the total.",
   ko:"적게요. 전체의 10퍼센트를 넘게 차지하는 건 원치 않습니다.",
   notes:[{t:"account for X percent",k:"business",m:"X퍼센트를 차지하다",tip:"구성 비중을 말하는 표준 표현입니다."}]},
  {s:"A",en:"Good, because above ten percent it stops being protection and becomes a position with its own risk.",
   ko:"좋습니다. 10퍼센트를 넘으면 그건 보호 수단이 아니라 그 자체로 위험을 가진 포지션이 됩니다.",
   notes:[{t:"stop being A and become B",k:"grammar",m:"A이기를 멈추고 B가 되다",tip:"성격이 바뀌는 지점을 표시합니다."}]},
  {s:"B",en:"I sold my last commodity position at a loss, so I would prefer to build it gradually.",
   ko:"지난번 원자재 포지션은 손실로 정리했습니다. 그래서 이번에는 천천히 쌓고 싶습니다.",
   notes:[{t:"sell at a loss",k:"business",m:"손실을 보고 매도하다",tip:"sell at a profit 과 반대입니다."},
          {t:"build a position gradually",k:"business",m:"비중을 점차 늘려 가다",tip:"한 번에 사지 않고 나누어 사는 방식입니다."}]},
  {s:"A",en:"Then buy the same amount every month and ignore the price on the day you buy.",
   ko:"그럼 매달 같은 금액을 사고, 사는 날의 가격은 무시하세요.",
   notes:[{t:"ignore the price",k:"collocation",m:"가격을 무시하다",tip:"시점 판단을 배제한다는 뜻입니다."}]},
  {s:"B",en:"That means I also buy in months when the price is already high, which seems inefficient.",
   ko:"그럼 가격이 이미 높은 달에도 사게 된다는 뜻인데, 비효율적으로 보입니다.",
   notes:[{t:"inefficient",k:"business",m:"비효율적인",tip:"자원을 낭비하는 상태입니다."}]},
  {s:"A",en:"You also buy in the months when it is low. The purpose is to remove timing from the decision.",
   ko:"낮은 달에도 삽니다. 목적은 결정에서 시점 판단을 제거하는 것입니다.",
   notes:[{t:"remove A from B",k:"collocation",m:"B에서 A를 제거하다",tip:"변수를 없애 단순화하는 것입니다."}]},
  {s:"B",en:"My timing has been wrong more often than right, so I accept that reasoning.",
   ko:"제 시점 판단은 맞은 것보다 틀린 적이 많았으니, 그 논리는 받아들입니다.",
   notes:[{t:"more often than right",k:"collocation",m:"맞은 것보다 자주",tip:"빈도를 비교하는 자연스러운 표현입니다."}]},
  {s:"A",en:"Then set a written rule and rebalance twice a year, and let the rule make the decision.",
   ko:"그럼 규칙을 문서로 정하고 1년에 두 번 리밸런싱하세요. 결정은 그 규칙이 하게 두고요.",
   notes:[{t:"rebalance",k:"business",m:"비중을 원래대로 되돌리다",tip:"오른 자산을 팔고 내린 자산을 사서 비율을 맞추는 것입니다."},
          {t:"a written rule",k:"business",m:"문서로 정한 규칙",tip:"즉흥적 판단을 막기 위한 장치입니다."}]},
  {s:"B",en:"What about equities? Several people expect prices to fall in the months after the election.",
   ko:"주식은요? 선거 뒤 몇 달 안에 가격이 떨어질 거라고 보는 사람이 여럿입니다.",
   notes:[{t:"equities",k:"business",m:"주식",tip:"주식 자산 전체를 가리키는 금융 용어입니다."}]},
  {s:"A",en:"The argument is that the government supports the market until the vote and then stops.",
   ko:"논리는 정부가 투표 때까지 시장을 떠받치다가 그 뒤에 멈춘다는 것입니다.",
   notes:[{t:"support the market",k:"business",m:"시장을 떠받치다",tip:"정책으로 가격 하락을 막는 것입니다."}]},
  {s:"B",en:"And after the vote they have much less incentive to continue, which is when prices fall.",
   ko:"그리고 투표 뒤에는 계속할 유인이 훨씬 줄어들고, 그때 가격이 떨어진다는 거죠.",
   notes:[{t:"an incentive to ~",k:"business",m:"~ 할 유인",tip:"행동을 유발하는 동기입니다."}]},
  {s:"A",en:"It is a neat explanation, and I am cautious about any thesis that depends on a specific date.",
   ko:"깔끔한 설명입니다. 저는 특정 날짜에 의존하는 논리라면 무엇이든 조심합니다.",
   notes:[{t:"depend on a specific date",k:"collocation",m:"특정 날짜에 의존하다",tip:"시점이 틀리면 전체가 무너지는 논리입니다."},
          {t:"a thesis",k:"business",m:"투자 논리",tip:"왜 이 자산을 사는지에 대한 근거입니다."}]},
  {s:"B",en:"That is a fair warning. I have lost money on neat explanations more than once.",
   ko:"타당한 경고입니다. 깔끔한 설명 때문에 돈을 잃은 적이 한 번이 아닙니다.",
   notes:[{t:"That is a fair warning.",k:"business",m:"타당한 경고입니다",tip:"조언을 받아들이는 짧은 표현입니다."}]},
  {s:"A",en:"If you want to act on it, reduce risk gradually rather than trying to sell at the peak.",
   ko:"행동에 옮기고 싶다면, 정점에서 팔려고 하지 말고 위험을 점차 줄이세요.",
   notes:[{t:"reduce risk gradually",k:"business",m:"위험을 점진적으로 줄이다",tip:"한 번에 정리하지 않는 방식입니다."},
          {t:"sell at the peak",k:"business",m:"꼭지에서 팔다",tip:"시점을 정확히 맞히려는 시도입니다."}]},
  {s:"B",en:"So I trim the position, keep the core holding, and limit the gold to ten percent.",
   ko:"그럼 비중을 조금 덜어 내고, 핵심 보유분은 유지하고, 금은 10퍼센트로 제한하는 거군요.",
   notes:[{t:"trim a position",k:"business",m:"비중을 조금 줄이다",tip:"전량이 아니라 일부를 파는 것입니다."},
          {t:"a core holding",k:"business",m:"핵심 보유 자산",tip:"장기로 계속 들고 가는 부분입니다."}]},
  {s:"A",en:"That is the entire plan, and written down it occupies about three lines on one page.",
   ko:"그게 계획 전부입니다. 적어 놓으면 한 장에 세 줄쯤 차지합니다.",
   notes:[{t:"occupy",k:"business",m:"차지하다",tip:"공간이나 지면을 점유한다는 뜻입니다."}]},
  {s:"B",en:"Then let us write it down, because I make worse decisions when nothing is recorded.",
   ko:"그럼 적어 둡시다. 아무것도 기록되어 있지 않을 때 제가 더 나쁜 결정을 하니까요.",
   notes:[{t:"be recorded",k:"grammar",m:"기록되다",tip:"문서로 남아 있는 상태입니다."}]}
 ],
 keys:[
  {en:"That is a reason, not a target.",ko:"그건 이유지 목표가 아닙니다",ex:"That is a reason, not a target. Give me a percentage."},
  {en:"That is a fair warning.",ko:"타당한 경고입니다",ex:"That is a fair warning, and I will take it."},
  {en:"The purpose is to remove A from B.",ko:"목적은 B에서 A를 없애는 것입니다",ex:"The purpose is to remove timing from the decision."},
  {en:"stop being A and become B",ko:"A이기를 멈추고 B가 되다",ex:"Above ten percent it stops being protection and becomes a bet."},
  {en:"account for X percent",ko:"X퍼센트를 차지하다",ex:"I do not want it to account for more than ten percent."},
  {en:"rebalance",ko:"비중을 원래대로 되돌리다",ex:"Set a rule and rebalance twice a year."},
  {en:"trim a position",ko:"비중을 조금 줄이다",ex:"Trim the position and keep the core holding."},
  {en:"an incentive to ~",ko:"~ 할 유인",ex:"After the vote they have less incentive to support prices."}
 ],
 out:[
  {q:"Turn a vague motivation into a specific allocation.",hint:"protect against a risk / That is a reason, not a target. / account for X percent"},
  {q:"Explain a rule that removes the need to predict prices.",hint:"The purpose is to remove A from B. / rebalance / a written rule"},
  {q:"Warn someone about an argument that depends on a date.",hint:"a thesis / depend on a specific date / reduce risk gradually"}
 ]
},
{
 id:"w3d3", day:18, cat:"신기술·훈련", level:"B2+",
 title:"Who Learns to Judge?",
 titleKo:"판단은 누가 배우는가 — 초안을 기계가 쓸 때",
 names:{A:"Hyun (팀장)", B:"Rosa (인재개발)"},
 brief:[
  "초안을 만드는 일이 쉬워지면서 일의 무게중심이 <b>생산에서 검증으로</b> 옮겨 갔습니다. 예전에는 초안을 쓰는 것이 가장 오래 걸리고 가장 중요한 일이었지만, 지금은 나온 것을 따져 보는 능력이 더 값어치 있게 됐습니다.",
  "문제는 <b>그 검증 능력이 어디서 오느냐</b>입니다. 좋은 검토자는 대개 직접 만들어 본 사람입니다. 숫자를 손으로 맞춰 보고, 틀려 보고, 어디가 잘 틀리는지 몸으로 아는 사람이 어디를 봐야 할지 압니다.",
  "그래서 생기는 것이 이 회차의 쟁점입니다. 신입이 초안을 한 번도 만들어 보지 않고 검토자부터 시작하면, <b>무엇을 근거로 판단하는가</b>. 조직은 효율을 얻고 그 대가로 다음 세대의 판단력을 잃을 수 있습니다.",
  "실무의 해법은 대개 둘 중 하나입니다. 일부러 <b>손으로 해 보는 구간(reps)</b>을 남겨 두거나, 검토를 가르치는 훈련을 따로 만드는 것입니다. 어느 쪽이든 <b>그냥 두면 저절로 생기지 않는다</b>는 것이 출발점입니다."
 ],
 lines:[
  {s:"A",en:"Writing the first draft used to be the slow part, and now a junior finishes one in ten minutes.",
   ko:"예전에는 초안 쓰기가 느린 부분이었는데, 지금은 신입이 10분이면 하나를 끝냅니다.",
   notes:[{t:"the first draft",k:"business",m:"초안",tip:"수정 전의 첫 번째 원고입니다."}]},
  {s:"B",en:"So the time moved somewhere else. Where exactly does that time go now?",
   ko:"그럼 시간이 다른 데로 옮겨 간 겁니다. 그 시간은 이제 정확히 어디로 갑니까?",
   notes:[{t:"Where exactly does ~ go?",k:"business",m:"~ 는 정확히 어디로 갑니까",tip:"자원의 행방을 구체적으로 묻는 질문입니다."}]},
  {s:"A",en:"It goes into checking, and checking was never included in any training plan we wrote.",
   ko:"확인하는 데로 갑니다. 그런데 확인은 우리가 만든 어떤 교육 계획에도 들어 있지 않았습니다.",
   notes:[{t:"a training plan",k:"business",m:"교육 계획",tip:"직원에게 무엇을 가르칠지 정리한 계획입니다."}]},
  {s:"B",en:"Because checking was never the difficult part. Producing the document was the skill we recruited for.",
   ko:"확인이 어려운 부분이었던 적이 없으니까요. 우리가 뽑을 때 본 능력은 문서를 만드는 것이었습니다.",
   notes:[{t:"recruit for ~",k:"business",m:"~ 를 기준으로 채용하다",tip:"어떤 능력을 보고 뽑는지를 말합니다."}]},
  {s:"A",en:"And now I have people approving documents they could not have written themselves.",
   ko:"그리고 이제는 자기가 직접 쓸 수 없었을 문서를 승인하는 사람들이 생겼습니다.",
   notes:[{t:"approve a document",k:"business",m:"문서를 승인하다",tip:"검토를 마치고 통과시키는 것입니다."}]},
  {s:"B",en:"Is that a problem? Many good editors could not write a novel, and they still edit well.",
   ko:"그게 문제입니까? 훌륭한 편집자 중에도 소설을 못 쓰는 사람이 많지만, 편집은 잘합니다.",
   notes:[{t:"Is that a problem?",k:"business",m:"그게 문제입니까",tip:"전제를 검증하라고 되묻는 짧은 질문입니다."}]},
  {s:"A",en:"Editors read thousands of drafts before they edit, and their judgment comes from that reading.",
   ko:"편집자는 편집하기 전에 수천 편의 원고를 읽습니다. 그들의 판단력은 그 독서에서 나옵니다.",
   notes:[{t:"judgment comes from ~",k:"business",m:"판단력은 ~ 에서 나온다",tip:"능력의 출처를 지정하는 문장입니다."}]},
  {s:"B",en:"So your concern is not the tool. Your concern is that nobody accumulates that experience now.",
   ko:"그럼 걱정은 도구가 아니군요. 이제 아무도 그 경험을 쌓지 않는다는 것이 걱정이시고요.",
   notes:[{t:"accumulate experience",k:"business",m:"경험을 쌓다",tip:"시간을 들여 축적하는 것입니다."}]},
  {s:"A",en:"Correct. You learn where things fail by making the mistakes yourself, repeatedly.",
   ko:"맞습니다. 어디서 실패하는지는 스스로 반복해서 실수하며 배웁니다.",
   notes:[{t:"repeatedly",k:"business",m:"반복해서",tip:"한 번이 아니라 여러 번임을 강조합니다."}]},
  {s:"B",en:"I disagree slightly, because we could teach the checking skill directly instead of waiting for experience.",
   ko:"조금 다르게 봅니다. 경험을 기다리는 대신 확인하는 능력을 직접 가르칠 수도 있으니까요.",
   notes:[{t:"I disagree slightly",k:"business",m:"조금 다르게 봅니다",tip:"부분적 반대를 정중하게 예고합니다."}]},
  {s:"A",en:"Teach it using what material? A checklist tells you where to look, not what is wrong.",
   ko:"무슨 자료로 가르칩니까? 체크리스트는 어디를 보라고만 알려 주지, 무엇이 잘못됐는지는 알려 주지 않습니다.",
   notes:[{t:"a checklist",k:"business",m:"점검 목록",tip:"확인할 항목을 나열한 목록입니다."}]},
  {s:"B",en:"That is fair. Most errors I catch are errors I made myself at some earlier point.",
   ko:"타당합니다. 제가 잡아내는 오류 대부분은 제가 예전에 직접 저질렀던 오류입니다.",
   notes:[{t:"catch an error",k:"collocation",m:"오류를 잡아내다",tip:"검토 과정에서 발견하는 것입니다."}]},
  {s:"A",en:"That is the argument in one sentence: verification depends on memory of your own mistakes.",
   ko:"그게 논지를 한 문장으로 말한 겁니다. 검증은 자기 실수에 대한 기억에 의존합니다.",
   notes:[{t:"depend on ~",k:"collocation",m:"~ 에 의존하다",tip:"전제 조건을 명시합니다."}]},
  {s:"B",en:"Then keep some of the manual work deliberately, even though it makes the team slower.",
   ko:"그럼 팀이 느려지더라도 수작업 일부를 의도적으로 남겨 두세요.",
   notes:[{t:"deliberately",k:"business",m:"의도적으로",tip:"실수가 아니라 선택임을 강조합니다."}]},
  {s:"A",en:"Senior management will not accept that, because it reads as choosing to be inefficient.",
   ko:"경영진은 그걸 받아들이지 않을 겁니다. 일부러 비효율을 택하는 걸로 읽히니까요.",
   notes:[{t:"will not accept ~",k:"business",m:"~ 를 받아들이지 않을 것이다",tip:"승인 가능성을 평가하는 표현입니다."}]},
  {s:"B",en:"Then do not present it as training. Present it as quality control, with a measurable cost.",
   ko:"그럼 교육으로 제시하지 마세요. 측정 가능한 비용이 드는 품질 관리로 제시하십시오.",
   notes:[{t:"quality control",k:"business",m:"품질 관리",tip:"결과물의 오류를 걸러 내는 공정입니다."},
          {t:"measurable",k:"business",m:"측정 가능한",tip:"숫자로 확인할 수 있다는 뜻입니다."}]},
  {s:"A",en:"That could work, because nobody argues against fewer errors in a document sent to a customer.",
   ko:"그건 통할 수 있습니다. 고객에게 나가는 문서의 오류가 줄어드는 데 반대하는 사람은 없으니까요.",
   notes:[{t:"argue against ~",k:"collocation",m:"~ 에 반대 논거를 대다",tip:"argue for 와 짝입니다."}]},
  {s:"B",en:"And it is true. We still miss incorrect numbers whenever the checking is compressed at the end.",
   ko:"게다가 사실입니다. 마지막에 확인 시간이 압축되면 우리는 여전히 틀린 숫자를 놓칩니다.",
   notes:[{t:"be compressed",k:"business",m:"시간이 압축되다",tip:"일정에 쫓겨 짧아지는 것입니다."}]},
  {s:"A",en:"So we keep the speed and recover part of the judgment we lost along the way.",
   ko:"그럼 속도는 지키면서, 그 과정에서 잃은 판단력의 일부를 되찾는 겁니다.",
   notes:[{t:"recover",k:"business",m:"되찾다, 회복하다",tip:"잃었던 것을 다시 얻는 것입니다."}]},
  {s:"B",en:"That is the trade I would accept, because speed is easy to regain and judgment is not.",
   ko:"저라면 그 맞바꿈을 받아들이겠습니다. 속도는 되찾기 쉽고 판단력은 그렇지 않으니까요.",
   notes:[{t:"regain",k:"business",m:"다시 얻다",tip:"recover 와 거의 같으나 능력에 더 자주 씁니다."}]}
 ],
 keys:[
  {en:"Where exactly does ~ go?",ko:"~ 는 정확히 어디로 갑니까",ex:"Where exactly does the time go after we automate this?"},
  {en:"Is that a problem?",ko:"그게 문제입니까",ex:"Is that a problem, or are we assuming it is?"},
  {en:"I disagree slightly",ko:"조금 다르게 봅니다",ex:"I disagree slightly, because there is a second option."},
  {en:"Then do not present it as A. Present it as B.",ko:"A로 제시하지 말고 B로 제시하세요",ex:"Then do not present it as training. Present it as quality control."},
  {en:"recruit for ~",ko:"~ 를 기준으로 채용하다",ex:"Producing was the skill we recruited for, not checking."},
  {en:"accumulate experience",ko:"경험을 쌓다",ex:"Nobody accumulates that experience once the tool writes the draft."},
  {en:"quality control",ko:"품질 관리",ex:"Frame the extra hours as quality control with a measurable cost."},
  {en:"catch an error",ko:"오류를 잡아내다",ex:"Most errors I catch are errors I made myself before."}
 ],
 out:[
  {q:"Explain where work goes after the slow part is automated.",hint:"Where exactly does ~ go? / a training plan / recruit for ~"},
  {q:"Disagree partially and give the alternative you see.",hint:"I disagree slightly / a checklist / accumulate experience"},
  {q:"Reframe an unpopular proposal so that it will be approved.",hint:"Then do not present it as A. Present it as B. / quality control / measurable"}
 ]
},
{
 id:"w3d4", day:19, cat:"신기술·에이전트", level:"B2+",
 title:"The New Hire Who Never Sleeps",
 titleKo:"잠들지 않는 신입 — AI 에이전트를 데리고 일하기",
 names:{A:"Jae (영업관리)", B:"Claire (업무혁신)"},
 brief:[
  "글을 만들어 주던 도구가 이제 <b>컴퓨터를 직접 쓰는 단계</b>로 넘어왔습니다. 파일을 열고 자료를 읽고 결과물을 만들어 냅니다. 영어로는 이런 것을 <b>an agent</b>라 부르고, 사람을 대신해 실제로 일을 <b>실행한다(carry out)</b>는 점에서 이전과 다릅니다.",
  "그래서 비유가 바뀝니다. 도구가 아니라 <b>아주 유능하지만 맥락을 모르는 신입</b>에 가깝습니다. 신입에게 필요한 것과 똑같은 것이 필요합니다 — 목표, 배경, 판단 기준, 그리고 어디까지 스스로 정해도 되는지의 선.",
  "여기서 <b>지시를 잘 쓰는 일(prompting)</b>과 <b>일이 되게 판을 짜는 일</b>이 갈립니다. 후자는 도구·규칙·검토 절차·피드백까지 포함하는 설계입니다. 사람에게 맡길 때 우리가 늘 하던 일과 다르지 않습니다.",
  "마지막 쟁점은 <b>어디까지 맡길 것인가</b>입니다. 되돌릴 수 있는 일과 되돌릴 수 없는 일을 가르는 것이 실무의 기준선이고, 이것은 신입에게 권한을 주는 방식과 정확히 같습니다."
 ],
 lines:[
  {s:"A",en:"It did not only write the report. It opened the files and built the slides without instruction.",
   ko:"보고서만 쓴 게 아닙니다. 지시 없이 파일을 열고 장표까지 만들었습니다.",
   notes:[{t:"without instruction",k:"collocation",m:"지시 없이",tip:"스스로 판단해 행동했다는 뜻입니다."}]},
  {s:"B",en:"So it is carrying out the task rather than describing how the task should be done.",
   ko:"그럼 작업을 어떻게 해야 하는지 설명하는 게 아니라, 실제로 그 작업을 수행하는 거군요.",
   notes:[{t:"carry out a task",k:"business",m:"작업을 수행하다",tip:"계획을 실행에 옮기는 것입니다."}]},
  {s:"A",en:"Correct. Work that would have taken me most of a week took about fifteen minutes.",
   ko:"맞습니다. 저였으면 한 주의 대부분을 썼을 일이 15분쯤 걸렸습니다.",
   notes:[{t:"most of a week",k:"collocation",m:"한 주의 대부분",tip:"기간의 대략적인 비율을 말합니다."}]},
  {s:"B",en:"That is what changes a budget. How much of the result did you have to correct afterwards?",
   ko:"예산을 바꾸는 건 그겁니다. 그 결과물 중 얼마나 나중에 고쳐야 했습니까?",
   notes:[{t:"correct a result",k:"business",m:"결과물을 고치다",tip:"오류를 바로잡는 것입니다."}]},
  {s:"A",en:"Some of it. It made assumptions about things I never specified, which was my own mistake.",
   ko:"일부요. 제가 명시하지 않은 것들에 대해 가정을 했는데, 그건 제 잘못이었습니다.",
   notes:[{t:"make an assumption",k:"business",m:"가정하다",tip:"명시되지 않은 것을 스스로 채워 넣는 것입니다."},
          {t:"specify",k:"business",m:"명시하다, 구체적으로 지정하다",tip:"요건 정의의 핵심 동사입니다."}]},
  {s:"B",en:"That is familiar, because new employees do exactly the same thing in their first week.",
   ko:"익숙한 얘기입니다. 신입 직원도 첫 주에 정확히 같은 일을 하니까요.",
   notes:[{t:"in one's first week",k:"collocation",m:"입사 첫 주에",tip:"적응 기간을 가리킵니다."}]},
  {s:"A",en:"That is how it feels: like hiring a capable person who arrives with no background information.",
   ko:"딱 그런 느낌입니다. 배경 정보 없이 들어온 유능한 사람을 뽑은 것 같은.",
   notes:[{t:"background information",k:"business",m:"배경 정보",tip:"판단에 필요한 사전 맥락입니다."}]},
  {s:"B",en:"Then manage it that way. What would you give a new analyst on their first morning?",
   ko:"그럼 그렇게 관리하세요. 신입 분석가에게 첫날 아침 무엇을 주시겠습니까?",
   notes:[{t:"manage something that way",k:"collocation",m:"그런 방식으로 관리하다",tip:"접근법을 지정하는 표현입니다."}]},
  {s:"A",en:"The objective, the audience, last quarter's version, and a list of the errors we made before.",
   ko:"목적, 읽을 사람, 지난 분기 버전, 그리고 전에 우리가 저지른 오류의 목록입니다.",
   notes:[{t:"the objective",k:"business",m:"목적",tip:"무엇을 달성해야 하는지입니다."},
          {t:"the audience",k:"business",m:"읽거나 들을 대상",tip:"누구를 위한 문서인지입니다."}]},
  {s:"B",en:"Then provide exactly the same material, because most poor output comes from a poor briefing.",
   ko:"그럼 정확히 같은 자료를 주세요. 나쁜 결과물 대부분은 나쁜 브리핑에서 나옵니다.",
   notes:[{t:"a briefing",k:"business",m:"사전 설명, 지시 전달",tip:"일을 맡기기 전에 배경과 요건을 설명하는 것입니다."}]},
  {s:"A",en:"The current term for that is harness engineering, rather than writing better prompts.",
   ko:"요즘 그것을 부르는 용어는 더 나은 프롬프트 작성이 아니라 하네스 엔지니어링입니다.",
   notes:[{t:"the current term for ~",k:"business",m:"요즘 ~ 를 부르는 용어",tip:"용어의 최신 쓰임을 소개합니다."}]},
  {s:"B",en:"Is that a real distinction, or is it a new name for something we already did?",
   ko:"그게 실제 구분입니까, 아니면 우리가 이미 하던 것에 붙은 새 이름입니까?",
   notes:[{t:"a real distinction",k:"business",m:"실질적인 구분",tip:"이름만 다른지 내용이 다른지를 묻습니다."}]},
  {s:"A",en:"It is real. One is the instruction itself, and the other is everything arranged around it.",
   ko:"실제 구분입니다. 하나는 지시문 자체이고, 다른 하나는 그 주위에 배치된 모든 것입니다.",
   notes:[{t:"arranged around ~",k:"collocation",m:"~ 주위에 배치된",tip:"환경과 조건 전체를 가리킵니다."}]},
  {s:"B",en:"Tools, rules, and a person who reviews the result before it reaches anyone outside the team.",
   ko:"도구, 규칙, 그리고 결과가 팀 밖으로 나가기 전에 검토하는 사람이군요.",
   notes:[{t:"review a result",k:"business",m:"결과를 검토하다",tip:"내보내기 전 확인 단계입니다."}]},
  {s:"A",en:"Yes, and the instruction itself accounts for perhaps a tenth of whether the work succeeds.",
   ko:"그렇습니다. 지시문 자체는 그 일이 성공하느냐의 10분의 1쯤을 차지합니다.",
   notes:[{t:"account for ~",k:"phrasal",m:"~ 를 차지하다, 설명하다",tip:"비중이나 원인의 몫을 말합니다."}]},
  {s:"B",en:"Then how do you decide what it is allowed to complete without your approval?",
   ko:"그럼 당신 승인 없이 끝내도 되는 범위를 어떻게 정합니까?",
   notes:[{t:"without approval",k:"collocation",m:"승인 없이",tip:"권한 위임의 경계를 말합니다."}]},
  {s:"A",en:"Anything reversible it completes alone. Anything irreversible that reaches a customer, I approve personally.",
   ko:"되돌릴 수 있는 일은 혼자 끝냅니다. 되돌릴 수 없고 고객에게 닿는 일은 제가 직접 승인합니다.",
   notes:[{t:"reversible / irreversible",k:"business",m:"되돌릴 수 있는 / 없는",tip:"위임 범위를 가르는 가장 실용적인 기준입니다."}]},
  {s:"B",en:"That is the same rule I would give a junior employee, which is probably the point.",
   ko:"그건 제가 신입 직원에게 줄 규칙과 같습니다. 아마 그게 핵심이겠죠.",
   notes:[{t:"which is probably the point",k:"colloquial",m:"아마 그게 핵심일 겁니다",tip:"결론을 가볍게 짚는 마무리 표현입니다."}]},
  {s:"A",en:"It is. The difficult part was never the tool. It is knowing what a good result looks like.",
   ko:"그렇습니다. 어려운 부분은 도구였던 적이 없습니다. 좋은 결과가 어떤 모습인지 아는 것입니다.",
   notes:[{t:"know what a good result looks like",k:"business",m:"좋은 결과가 어떤 모습인지 안다",tip:"판단 기준을 갖고 있다는 뜻입니다."}]},
  {s:"B",en:"And that knowledge still sits with people, at least for as long as anyone can predict.",
   ko:"그리고 그 지식은 아직 사람에게 있습니다. 적어도 예측할 수 있는 기간 동안은요.",
   notes:[{t:"sit with ~",k:"phrasal",m:"~ 에게 있다, ~ 의 몫이다",tip:"책임이나 능력의 소재를 말합니다."}]}
 ],
 keys:[
  {en:"Is that a real distinction?",ko:"그게 실질적인 구분입니까",ex:"Is that a real distinction, or just a new name?"},
  {en:"Then manage it that way.",ko:"그럼 그런 방식으로 관리하세요",ex:"It behaves like a new hire. Then manage it that way."},
  {en:"which is probably the point",ko:"아마 그게 핵심일 겁니다",ex:"It is the same rule I give a junior, which is probably the point."},
  {en:"know what a good result looks like",ko:"좋은 결과가 어떤 모습인지 안다",ex:"The hard part is knowing what a good result looks like."},
  {en:"carry out a task",ko:"작업을 수행하다",ex:"It is carrying out the task, not describing it."},
  {en:"make an assumption",ko:"가정하다",ex:"It made assumptions about things I never specified."},
  {en:"a briefing",ko:"사전 설명, 지시 전달",ex:"Most poor output comes from a poor briefing."},
  {en:"reversible / irreversible",ko:"되돌릴 수 있는 / 없는",ex:"Anything reversible it completes alone."}
 ],
 out:[
  {q:"Describe a tool that did more than you expected, and what you had to fix.",hint:"carry out a task / make an assumption / specify"},
  {q:"Explain why the instruction is the small part of the problem.",hint:"a briefing / arranged around ~ / account for ~"},
  {q:"State a rule for what a new person may decide without you.",hint:"reversible / irreversible / without approval / know what a good result looks like"}
 ]
},
{
 id:"w3d5", day:20, cat:"신기술·기술", level:"B2+",
 title:"Do We Still Need to Code?",
 titleKo:"코딩을 여전히 배워야 하는가 — 번역기 비유의 한계",
 names:{A:"Tae (기획, 비개발자)", B:"Noor (개발자)"},
 brief:[
  "프로그래밍 언어는 결국 <b>기계가 알아듣도록 만든 언어</b>입니다. 그래서 사람의 말을 코드로 옮기는 일을 <b>번역</b>에 비유하는 시각이 자연스럽게 나옵니다. 원하는 것을 말하면 도구가 옮겨 준다는 그림입니다.",
  "이 비유의 강점은 분명합니다. 예전에는 문법을 익히는 데 몇 년이 들었고, 그 문턱 때문에 아이디어가 <b>코드로 옮겨지지 못한 채</b> 사라졌습니다. 이제는 말로 설명하는 것만으로 움직이는 것이 나옵니다.",
  "약점도 분명합니다. 번역은 <b>무엇을 원하는지 아는 사람</b>이 있어야 성립합니다. 그리고 프로그램은 글과 달리 <b>틀리면 조용히 잘못 돌아갑니다</b>. 그때 필요한 것이 디버깅이고, 디버깅은 결국 「기계가 실제로 무엇을 하는가」를 읽는 일입니다.",
  "그래서 쟁점은 「언어를 외울 필요가 있는가」가 아니라 <b>어떤 개념을 알아야 하는가</b>로 옮겨 갑니다. 문법은 덜 중요해졌지만, 자료가 어떻게 흐르고 무엇이 어디서 깨지는지에 대한 감각은 그대로 필요합니다."
 ],
 lines:[
  {s:"A",en:"I have started to describe it as a translator between what I want and the code.",
   ko:"저는 이걸 제가 원하는 것과 코드 사이의 번역기라고 설명하기 시작했습니다.",
   notes:[{t:"describe A as B",k:"business",m:"A를 B라고 설명하다",tip:"비유나 정의를 제시하는 동사입니다."}]},
  {s:"B",en:"That describes what it does. At what point does the comparison stop being accurate?",
   ko:"하는 일에 대한 설명으로는 맞습니다. 그 비교는 어느 지점부터 정확하지 않게 됩니까?",
   notes:[{t:"At what point does ~ ?",k:"business",m:"어느 지점부터 ~ 합니까",tip:"한계가 시작되는 경계를 묻는 질문입니다."}]},
  {s:"A",en:"I am not sure it does, because a programming language was designed for machines to read.",
   ko:"정확하지 않게 되는 지점이 있는지 모르겠습니다. 프로그래밍 언어는 기계가 읽으라고 만든 거니까요.",
   notes:[{t:"be designed for ~",k:"grammar",m:"~ 를 위해 설계되다",tip:"목적을 명시하는 수동 표현입니다."}]},
  {s:"B",en:"True, but translation requires somebody who already knows what they want to say.",
   ko:"맞습니다. 다만 번역에는 무엇을 말하고 싶은지 이미 아는 사람이 필요합니다.",
   notes:[{t:"require",k:"business",m:"필요로 하다",tip:"need 보다 격식 있고 조건을 강조합니다."}]},
  {s:"A",en:"Describing what I want is the part I am confident about, so that requirement is met.",
   ko:"원하는 것을 설명하는 건 제가 자신 있는 부분이니, 그 조건은 충족됩니다.",
   notes:[{t:"a requirement is met",k:"business",m:"요건이 충족되다",tip:"조건을 만족시켰다는 뜻입니다."}]},
  {s:"B",en:"Then describe what should happen when two rules you wrote produce conflicting results.",
   ko:"그럼 직접 쓴 규칙 두 개가 서로 모순된 결과를 낼 때 어떻게 되어야 하는지 설명해 보세요.",
   notes:[{t:"conflicting results",k:"collocation",m:"서로 모순되는 결과",tip:"둘이 동시에 성립할 수 없는 상태입니다."}]},
  {s:"A",en:"That is a good example, and I would not have thought to specify that case myself.",
   ko:"좋은 예입니다. 그 경우를 제가 직접 명시할 생각은 못 했을 겁니다.",
   notes:[{t:"specify",k:"business",m:"명시하다, 구체적으로 지정하다",tip:"요건 정의의 핵심 동사입니다. specify the format / the conditions."}]},
  {s:"B",en:"That is most of programming: deciding what happens in the cases nobody thinks about.",
   ko:"그게 프로그래밍의 대부분입니다. 아무도 생각하지 않는 경우에 어떻게 할지 정하는 것.",
   notes:[{t:"the cases nobody thinks about",k:"collocation",m:"아무도 생각하지 않는 경우들",tip:"edge case 를 평이하게 표현한 것입니다."}]},
  {s:"A",en:"I would still rather describe those cases in Korean than learn the syntax first.",
   ko:"그래도 저는 문법을 먼저 배우느니 그 경우들을 한국어로 설명하겠습니다.",
   notes:[{t:"syntax",k:"business",m:"문법, 표기 규칙",tip:"언어의 형태 규칙입니다. semantics(의미)와 짝입니다."}]},
  {s:"B",en:"I agree, because syntax was never the valuable part of programming as a skill.",
   ko:"동의합니다. 문법이 프로그래밍이라는 능력에서 값어치 있는 부분이었던 적은 없으니까요.",
   notes:[{t:"the valuable part of ~",k:"collocation",m:"~ 에서 값어치 있는 부분",tip:"핵심 역량이 무엇인지 지목합니다."}]},
  {s:"A",en:"So we agree that memorizing a language is no longer necessary for someone in my role.",
   ko:"그럼 제 위치에 있는 사람에게 언어 암기가 더는 필요하지 않다는 데 동의하시는군요.",
   notes:[{t:"no longer necessary",k:"collocation",m:"더는 필요하지 않은",tip:"과거와 달라진 조건을 말합니다."}]},
  {s:"B",en:"Only partly. You do not need the grammar, but you do need to read what it produced.",
   ko:"일부만 그렇습니다. 문법은 필요 없지만, 그것이 만들어 낸 것을 읽을 줄은 알아야 합니다.",
   notes:[{t:"Only partly.",k:"business",m:"일부만 그렇습니다",tip:"전면 동의를 피하는 정확한 부분 부정입니다."}]},
  {s:"A",en:"Why, if it works? I can test the output without reading a single line of the code.",
   ko:"돌아가면 됐지 왜요? 코드를 한 줄도 읽지 않고 결과를 시험할 수 있는데요.",
   notes:[{t:"test the output",k:"business",m:"결과물을 시험하다",tip:"의도대로 동작하는지 확인하는 것입니다."}]},
  {s:"B",en:"Because code can fail without any error message, and it will keep producing wrong numbers.",
   ko:"코드는 오류 메시지 없이 실패할 수 있고, 계속 틀린 숫자를 만들어 내기 때문입니다.",
   notes:[{t:"fail without an error message",k:"collocation",m:"오류 메시지 없이 실패하다",tip:"가장 발견하기 어려운 실패 유형입니다."}]},
  {s:"A",en:"That is the part that concerns me, because I would have no way of knowing it was wrong.",
   ko:"저를 우려하게 하는 게 그 부분입니다. 틀렸다는 걸 알 방법이 없으니까요.",
   notes:[{t:"have no way of ~ing",k:"grammar",m:"~ 할 방법이 없다",tip:"불가능을 분명히 말하는 형태입니다."}]},
  {s:"B",en:"So learn concepts rather than languages: how data moves, and where it usually breaks.",
   ko:"그럼 언어가 아니라 개념을 배우세요. 자료가 어떻게 흐르고 주로 어디서 깨지는지.",
   notes:[{t:"concepts rather than languages",k:"collocation",m:"언어가 아니라 개념",tip:"학습의 초점을 옮기는 대비 표현입니다."}]},
  {s:"A",en:"That is a shorter list of things to learn than the one I was expecting.",
   ko:"제가 예상했던 것보다 배울 것의 목록이 짧습니다.",
   notes:[{t:"a list of things to learn",k:"collocation",m:"배울 것의 목록",tip:"학습 범위를 가리킵니다."}]},
  {s:"B",en:"It is shorter, but it is not empty, and many people claim that it is.",
   ko:"짧습니다. 다만 비어 있지는 않은데, 많은 사람이 비어 있다고 주장합니다.",
   notes:[{t:"claim that ~",k:"business",m:"~ 라고 주장하다",tip:"근거 없이 말한다는 함의가 약간 있습니다."}]},
  {s:"A",en:"Then I will keep building things and read enough code to question the result it gives me.",
   ko:"그럼 계속 만들면서, 그것이 주는 결과에 의문을 제기할 만큼만 코드를 읽겠습니다.",
   notes:[{t:"question a result",k:"business",m:"결과에 의문을 제기하다",tip:"그대로 받아들이지 않는 태도입니다."}]},
  {s:"B",en:"That is the right level, because you do not need to write code in order to check it.",
   ko:"그게 적절한 수준입니다. 코드를 확인하기 위해 직접 쓸 필요는 없으니까요.",
   notes:[{t:"You do not need to A to B",k:"grammar",m:"B 하려고 A 할 필요는 없다",tip:"필요 조건을 부정하는 형태입니다."}]}
 ],
 keys:[
  {en:"At what point does ~ ?",ko:"어느 지점부터 ~ 합니까",ex:"At what point does that comparison stop being accurate?"},
  {en:"Only partly.",ko:"일부만 그렇습니다",ex:"Only partly. You need the concepts, not the grammar."},
  {en:"have no way of ~ing",ko:"~ 할 방법이 없다",ex:"I would have no way of knowing the number was wrong."},
  {en:"You do not need to A to B",ko:"B 하려고 A 할 필요는 없다",ex:"You do not need to write code to check it."},
  {en:"describe A as B",ko:"A를 B라고 설명하다",ex:"I describe it as a translator between intent and code."},
  {en:"specify",ko:"명시하다",ex:"I would not have thought to specify that case."},
  {en:"syntax",ko:"문법, 표기 규칙",ex:"Syntax was never the valuable part of the skill."},
  {en:"question a result",ko:"결과에 의문을 제기하다",ex:"Read enough to question the result it gives you."}
 ],
 out:[
  {q:"Offer a comparison for a new tool, then say where it breaks down.",hint:"describe A as B / At what point does ~ ? / require"},
  {q:"Disagree only in part, and say exactly which part.",hint:"Only partly. / test the output / fail without an error message"},
  {q:"Decide what is worth learning and what is not.",hint:"concepts rather than languages / no longer necessary / You do not need to A to B"}
 ]
},
{
 id:"w3d6", day:21, cat:"공급망·현지화", level:"B2+",
 title:"Make Where You Sell",
 titleKo:"파는 곳에서 만들기 — 현지화는 비용인가 보험인가",
 names:{A:"Hyun (구매 총괄)", B:"Dana (현지 법인장)"},
 brief:[
  "지난 30년의 공급망은 하나의 질문만 물었습니다. <b>어디서 만들면 가장 쌉니까.</b> 그 답을 따라 공장이 옮겨 다녔고, 재고는 얇아졌으며, 배는 정확히 제때 도착한다는 전제 위에 모든 계획이 올라섰습니다.",
  "그 전제가 몇 번 깨졌습니다. 항구가 막히고, 국경이 닫히고, 관세가 하룻밤에 바뀌었습니다. 그래서 요즘 회사들이 던지는 질문이 바뀌었습니다. <b>가장 싼 곳</b>이 아니라 <b>끊겨도 견디는 구조</b>를 묻습니다.",
  "대안은 대체로 셋입니다. 같은 부품을 여러 나라에서 사는 <b>다중 소싱</b>, 파는 시장 안에서 만드는 <b>현지화</b>, 그리고 그냥 재고를 더 쌓는 것. 셋 다 돈이 듭니다. 그래서 논쟁은 「할 것인가」가 아니라 <b>얼마를 보험료로 낼 것인가</b>가 됩니다.",
  "이 대화에서 유용한 것은 결론이 아니라 <b>비용을 보험으로 바꿔 말하는 언어</b>입니다. 「비싸다」를 「무엇에 대한 대가인가」로 되묻는 문장들을 익혀 두면, 어떤 투자 논의에서도 그대로 쓸 수 있습니다."
 ],
 lines:[
  {s:"A",en:"For thirty years we asked only one question: where can we manufacture this at the lowest cost?",
   ko:"30년 동안 우리는 질문 하나만 했습니다. 어디서 만들면 원가가 가장 낮은가?",
   notes:[{t:"at the lowest cost",k:"collocation",m:"가장 낮은 원가로",tip:"비용 기준의 의사결정을 표현합니다."}]},
  {s:"B",en:"That worked until the shipments stopped arriving on the dates we had planned for.",
   ko:"그건 선적이 우리가 계획한 날짜에 도착하지 않게 되기 전까지는 통했습니다.",
   notes:[{t:"arrive on the planned date",k:"collocation",m:"계획한 날짜에 도착하다",tip:"납기 준수를 평이하게 표현합니다."}]},
  {s:"A",en:"One difficult quarter does not cancel thirty years of buying at the lowest available price.",
   ko:"어려운 분기 하나가 가장 싼 값에 사 온 30년을 없던 일로 만들지는 않습니다.",
   notes:[{t:"cancel",k:"business",m:"무효로 만들다, 상쇄하다",tip:"앞선 성과를 지운다는 뜻입니다."}]},
  {s:"B",en:"It was not one quarter. We missed the selling season twice within three years.",
   ko:"한 분기가 아니었습니다. 3년 안에 판매 성수기를 두 번 놓쳤습니다.",
   notes:[{t:"the selling season",k:"business",m:"판매 성수기",tip:"수요가 집중되는 기간입니다."}]},
  {s:"A",en:"I accept that, but manufacturing here costs about eighteen percent more on every unit.",
   ko:"그건 인정합니다. 다만 여기서 만들면 개당 18퍼센트쯤 더 듭니다.",
   notes:[{t:"per unit",k:"business",m:"단위당, 개당",tip:"원가를 비교하는 표준 기준입니다."}]},
  {s:"B",en:"Eighteen percent more than what? You are comparing it to a year in which nothing went wrong.",
   ko:"무엇보다 18퍼센트 더입니까? 아무 일도 일어나지 않은 해와 비교하고 계십니다.",
   notes:[{t:"X more than what?",k:"business",m:"무엇보다 X 더입니까",tip:"비교 대상을 드러내라고 요구하는 반문입니다."}]},
  {s:"A",en:"More than our normal cost, because that is the only figure I can build a budget on.",
   ko:"평상시 원가보다입니다. 제가 예산을 세울 수 있는 유일한 수치가 그것이니까요.",
   notes:[{t:"build a budget on ~",k:"business",m:"~ 를 기준으로 예산을 세우다",tip:"계획의 근거 수치를 말합니다."}]},
  {s:"B",en:"Then your budget assumes that nothing goes wrong, and that assumption has a cost of its own.",
   ko:"그럼 예산이 아무 일도 일어나지 않는다고 전제하는 겁니다. 그 전제에는 그 자체의 비용이 있습니다.",
   notes:[{t:"an assumption has a cost",k:"business",m:"전제에 비용이 따른다",tip:"틀렸을 때의 손실을 가리킵니다."}]},
  {s:"A",en:"Then treat it as insurance. What exactly do I receive in return for eighteen percent?",
   ko:"그럼 보험으로 취급합시다. 18퍼센트의 대가로 제가 정확히 무엇을 받습니까?",
   notes:[{t:"in return for ~",k:"collocation",m:"~ 의 대가로",tip:"교환 관계를 명시합니다."}]},
  {s:"B",en:"Two weeks of lead time instead of eleven, and a supply route that a border cannot close.",
   ko:"리드타임이 11주가 아니라 2주가 되고, 국경이 막을 수 없는 공급 경로가 생깁니다.",
   notes:[{t:"a supply route",k:"business",m:"공급 경로",tip:"원재료나 제품이 이동하는 길입니다."}]},
  {s:"A",en:"That matters more than I want to admit, because lead time is what customers complain about.",
   ko:"인정하고 싶은 것보다 중요합니다. 고객이 불평하는 게 리드타임이니까요.",
   notes:[{t:"lead time",k:"business",m:"리드타임",tip:"주문에서 납품까지 걸리는 시간입니다."}]},
  {s:"B",en:"Then calculate the cost of that complaint. What does one late shipment cost in lost orders?",
   ko:"그럼 그 불평의 비용을 계산하세요. 늦은 선적 한 번이 잃은 주문으로 얼마입니까?",
   notes:[{t:"calculate the cost of ~",k:"business",m:"~ 의 비용을 계산하다",tip:"막연한 손실을 숫자로 바꾸는 요구입니다."},
          {t:"lost orders",k:"business",m:"놓친 주문",tip:"받지 못한 매출을 가리킵니다."}]},
  {s:"A",en:"We have never measured that, because we measure what we spend and not what we fail to earn.",
   ko:"그건 재 본 적이 없습니다. 우리는 쓰는 돈을 재지, 벌지 못한 것을 재지는 않으니까요.",
   notes:[{t:"fail to earn",k:"collocation",m:"벌지 못하다",tip:"기회 손실을 표현하는 방식입니다."}]},
  {s:"B",en:"That is why the cheapest option always wins: only one side of the comparison is measured.",
   ko:"그래서 가장 싼 선택지가 늘 이깁니다. 비교의 한쪽만 측정되니까요.",
   notes:[{t:"one side of the comparison",k:"collocation",m:"비교의 한쪽",tip:"양쪽을 다 보지 않는 상태를 지적합니다."}]},
  {s:"A",en:"I would prefer not to move everything at once, because that is a large and irreversible decision.",
   ko:"전부를 한꺼번에 옮기고 싶지는 않습니다. 그건 크고 되돌릴 수 없는 결정이니까요.",
   notes:[{t:"irreversible",k:"business",m:"되돌릴 수 없는",tip:"한 번 하면 원상 복구가 어려운 결정입니다."}]},
  {s:"B",en:"Nobody is proposing that. Move only the parts that stop production when they arrive late.",
   ko:"아무도 그걸 제안하지 않습니다. 늦게 도착하면 생산을 멈추게 하는 부품만 옮기세요.",
   notes:[{t:"stop production",k:"business",m:"생산을 멈추다",tip:"라인이 정지하는 상황입니다."}]},
  {s:"A",en:"That is perhaps six items out of four hundred, which is a proposal I could defend.",
   ko:"그건 400개 중 여섯 개쯤이고, 그 정도라면 제가 방어할 수 있는 제안입니다.",
   notes:[{t:"a proposal I could defend",k:"business",m:"제가 방어할 수 있는 제안",tip:"승인 심사를 통과시킬 자신이 있다는 뜻입니다."}]},
  {s:"B",en:"Start with those six, and after two quarters the results will make the case for the rest.",
   ko:"그 여섯 개로 시작하세요. 두 분기 뒤에는 결과가 나머지에 대한 근거를 만들어 줄 겁니다.",
   notes:[{t:"make the case for ~",k:"business",m:"~ 에 대한 근거를 만들다",tip:"설득 논리를 제공한다는 뜻입니다."}]},
  {s:"A",en:"One condition. If the cheaper option turns out to have been correct, we reverse the decision.",
   ko:"조건 하나. 싼 쪽이 옳았던 것으로 드러나면 결정을 되돌립니다.",
   notes:[{t:"reverse a decision",k:"business",m:"결정을 되돌리다",tip:"이전 상태로 복귀하는 것입니다."}]},
  {s:"B",en:"Agreed, and set a date for that review, because a review without a date never happens.",
   ko:"동의합니다. 그리고 그 검토에 날짜를 정하세요. 날짜 없는 검토는 절대 일어나지 않습니다.",
   notes:[{t:"set a date",k:"collocation",m:"날짜를 정하다",tip:"막연한 합의를 실행 가능하게 만드는 조치입니다."}]}
 ],
 keys:[
  {en:"X more than what?",ko:"무엇보다 X 더입니까",ex:"Eighteen percent more than what, exactly?"},
  {en:"in return for ~",ko:"~ 의 대가로",ex:"What do I receive in return for eighteen percent?"},
  {en:"a proposal I could defend",ko:"제가 방어할 수 있는 제안",ex:"Six items out of four hundred is a proposal I could defend."},
  {en:"make the case for ~",ko:"~ 에 대한 근거를 만들다",ex:"Two quarters of results will make the case for the rest."},
  {en:"lead time",ko:"리드타임",ex:"Lead time is what customers actually complain about."},
  {en:"calculate the cost of ~",ko:"~ 의 비용을 계산하다",ex:"Calculate the cost of one late shipment in lost orders."},
  {en:"irreversible",ko:"되돌릴 수 없는",ex:"Moving everything at once is an irreversible decision."},
  {en:"set a date",ko:"날짜를 정하다",ex:"Set a date for the review, or it will never happen."}
 ],
 out:[
  {q:"Challenge a cost comparison by asking what it is being compared with.",hint:"X more than what? / build a budget on ~ / an assumption has a cost"},
  {q:"Turn a vague complaint into a number.",hint:"calculate the cost of ~ / lost orders / fail to earn"},
  {q:"Propose a small first step and attach a review condition to it.",hint:"a proposal I could defend / reverse a decision / set a date"}
 ]
},
{
 id:"w3d7", day:22, cat:"심리·정체성", level:"B2+",
 title:"The Person You Invent",
 titleKo:"우리가 만들어 내는 또 하나의 나 — 가면과 정체성",
 names:{A:"Ren (작가)", B:"Iris (임상심리 전공)"},
 brief:[
  "「파이트 클럽」이 오래 회자되는 이유는 반전 때문만이 아닙니다. 사람들이 <b>자기가 되고 싶었던 인물을 만들어 내고, 결국 그쪽에 끌려다니는</b> 경험을 어렴풋이 알고 있기 때문입니다.",
  "심리학은 이것을 훨씬 조심스럽게 다룹니다. 임상적 해리 장애는 드물고, 대개 심각한 외상과 연결됩니다. 반면 <b>상황마다 다른 얼굴을 쓰는 것</b>은 병이 아니라 거의 모든 사람이 하는 일입니다.",
  "그래서 흥미로운 질문은 「가면을 쓰는가」가 아닙니다. <b>가면을 벗을 수 있는가</b>, 그리고 <b>여러 얼굴이 서로를 알고 있는가</b>입니다. 회사에서의 나와 집에서의 나가 서로를 부끄러워하기 시작하면 문제가 됩니다.",
  "이 대화는 <b>영화 이야기에서 시작해 자기 이야기로 내려가는</b> 전형적인 영어 대화의 흐름을 담고 있습니다. 소재를 바꿔도 그대로 쓸 수 있는 문장들이 많으니, 흐름 자체를 통째로 익혀 두세요."
 ],
 lines:[
  {s:"A",en:"I watched Fight Club again last night, and it affected me very differently from the first time.",
   ko:"어젯밤 파이트 클럽을 다시 봤는데, 처음 봤을 때와는 아주 다르게 다가왔습니다.",
   notes:[{t:"affect someone",k:"business",m:"~ 에게 영향을 주다",tip:"감정적 반응을 중립적으로 표현합니다."}]},
  {s:"B",en:"At twenty it looks like a story about freedom. Later it looks like a warning.",
   ko:"스무 살에는 자유에 관한 이야기로 보입니다. 나중에는 경고로 보이고요.",
   notes:[{t:"look like ~",k:"grammar",m:"~ 처럼 보이다",tip:"해석이 달라지는 것을 표현합니다."}]},
  {s:"A",en:"What struck me is that he does not invent a stranger. He invents a version of himself.",
   ko:"인상 깊었던 것은, 그가 낯선 사람을 만드는 게 아니라 자기 자신의 한 버전을 만든다는 점입니다.",
   notes:[{t:"What struck me is that ~",k:"business",m:"제게 인상 깊었던 것은 ~ 라는 점입니다",tip:"관찰을 앞세우는 도입 구문입니다."}]},
  {s:"B",en:"He invents the version he wishes he were, and that is what makes the film uncomfortable.",
   ko:"자기가 그랬으면 하는 버전을 만들어 냅니다. 그게 이 영화를 불편하게 만드는 점이고요.",
   notes:[{t:"the version he wishes he were",k:"grammar",m:"그가 그랬으면 하는 버전",tip:"wish + 과거형은 현재 사실의 반대를 뜻합니다."}]},
  {s:"A",en:"Is that an accurate picture of dissociative identity disorder as clinicians actually see it?",
   ko:"그게 임상의들이 실제로 보는 해리성 정체감 장애의 정확한 모습입니까?",
   notes:[{t:"an accurate picture of ~",k:"collocation",m:"~ 의 정확한 모습",tip:"묘사가 현실과 맞는지 묻습니다."}]},
  {s:"B",en:"No. The clinical condition is rare, and it is usually connected to severe early trauma.",
   ko:"아닙니다. 임상적 장애는 드물고, 대개 어린 시절의 심각한 외상과 연결되어 있습니다.",
   notes:[{t:"be connected to ~",k:"collocation",m:"~ 와 연결되어 있다",tip:"인과보다 약한 연관을 표현합니다."},
          {t:"trauma",k:"business",m:"외상, 정신적 충격",tip:"심리학과 의학 양쪽에서 쓰는 용어입니다."}]},
  {s:"A",en:"Then why do so many people recognize something familiar in it? That cannot be accidental.",
   ko:"그럼 왜 그렇게 많은 사람이 거기서 익숙한 무언가를 알아봅니까? 그게 우연일 수는 없습니다.",
   notes:[{t:"accidental",k:"business",m:"우연한",tip:"의도나 원인이 없는 상태입니다."}]},
  {s:"B",en:"Because behaving differently in different situations is ordinary, and everyone does it every day.",
   ko:"상황마다 다르게 행동하는 것은 평범한 일이고, 누구나 매일 그렇게 하기 때문입니다.",
   notes:[{t:"behave differently in different situations",k:"collocation",m:"상황마다 다르게 행동하다",tip:"은유 없이 같은 현상을 서술한 표현입니다."}]},
  {s:"A",en:"I would call that ordinary manners, because everyone adapts to the situation they are in.",
   ko:"저는 그걸 평범한 예의라고 부르겠습니다. 누구나 자기가 처한 상황에 맞추니까요.",
   notes:[{t:"adapt to ~",k:"business",m:"~ 에 맞추다, 적응하다",tip:"상황에 자신을 조정하는 것입니다."}]},
  {s:"B",en:"It is, until you reach the point where you can no longer return to your ordinary self.",
   ko:"그렇습니다. 평소의 자신으로 더는 돌아갈 수 없게 되는 지점에 이르기 전까지는요.",
   notes:[{t:"reach the point where ~",k:"grammar",m:"~ 하는 지점에 이르다",tip:"변화가 한계를 넘는 순간을 표현합니다."}]},
  {s:"A",en:"How would I notice that happening, when the behaviour would feel completely natural to me?",
   ko:"그 행동이 제게는 완전히 자연스럽게 느껴질 텐데, 그런 일이 벌어지는 걸 어떻게 알아차립니까?",
   notes:[{t:"feel natural",k:"collocation",m:"자연스럽게 느껴지다",tip:"자각하기 어려운 상태를 설명합니다."}]},
  {s:"B",en:"One clear sign is embarrassment: one version of you is ashamed of the other version.",
   ko:"분명한 신호 하나는 부끄러움입니다. 당신의 한 버전이 다른 버전을 부끄러워하는 것이죠.",
   notes:[{t:"One clear sign is ~",k:"business",m:"분명한 신호 하나는 ~ 입니다",tip:"증상을 항목으로 제시하는 틀입니다."},
          {t:"be ashamed of ~",k:"collocation",m:"~ 를 부끄러워하다",tip:"전치사 of 가 고정입니다."}]},
  {s:"A",en:"That description is uncomfortably precise. I have felt exactly that at company dinners.",
   ko:"그 설명은 불편할 만큼 정확합니다. 회식 자리에서 정확히 그것을 느낀 적이 있습니다.",
   notes:[{t:"uncomfortably precise",k:"collocation",m:"불편할 만큼 정확한",tip:"지적이 정곡을 찔렀을 때의 반응입니다."}]},
  {s:"B",en:"Most people have. The important question is whether the two versions communicate at all.",
   ko:"대부분이 그렇습니다. 중요한 질문은 두 버전이 서로 소통하기는 하느냐입니다.",
   notes:[{t:"The important question is whether ~",k:"business",m:"중요한 질문은 ~ 인지 여부입니다",tip:"쟁점을 정확히 재정의하는 문장입니다."}]},
  {s:"A",en:"Mine do not. They operate in turn and neither one refers to the other afterwards.",
   ko:"제 경우는 아닙니다. 번갈아 작동하고, 둘 다 나중에 서로를 언급하지 않습니다.",
   notes:[{t:"operate in turn",k:"collocation",m:"번갈아 작동하다",tip:"교대로 나타나는 상태입니다."},
          {t:"refer to ~",k:"phrasal",m:"~ 를 언급하다",tip:"말로 다루는 것입니다."}]},
  {s:"B",en:"Then give each of them a name. It sounds trivial, but a name makes them easier to discuss.",
   ko:"그럼 각각에 이름을 붙이세요. 사소해 보이지만, 이름이 있으면 논의하기 쉬워집니다.",
   notes:[{t:"It sounds trivial, but ~",k:"business",m:"사소해 보이지만 ~",tip:"저항이 예상되는 조언을 꺼내는 완충 표현입니다."}]},
  {s:"A",en:"Easier to discuss with whom? I cannot hold a conversation with a version of myself.",
   ko:"누구와 논의하기 쉬워진다는 겁니까? 제 다른 버전과 대화를 나눌 수는 없습니다.",
   notes:[{t:"hold a conversation",k:"collocation",m:"대화를 나누다",tip:"have a conversation 과 같습니다."}]},
  {s:"B",en:"With yourself. You can decide which version gets your evening, and that is a real decision.",
   ko:"당신 자신과요. 어느 버전이 저녁 시간을 갖는지는 정할 수 있고, 그건 실제 결정입니다.",
   notes:[{t:"a real decision",k:"collocation",m:"실제 결정",tip:"추상이 아니라 행동으로 이어지는 선택입니다."}]},
  {s:"A",en:"So the goal is not a single true self. The goal is deciding which version leads.",
   ko:"그럼 목표는 하나의 진짜 자아가 아니군요. 어느 버전이 주도할지 결정하는 것이고요.",
   notes:[{t:"The goal is not A. The goal is B.",k:"grammar",m:"목표는 A가 아니라 B입니다",tip:"결론을 정확히 재정의하는 두 문장 골격입니다."}]},
  {s:"B",en:"That is the healthier version of the question, because Tyler's problem was never the second identity.",
   ko:"그게 더 건강한 형태의 질문입니다. 타일러의 문제는 두 번째 정체성이 아니었으니까요.",
   notes:[{t:"the healthier version of ~",k:"collocation",m:"~ 의 더 건강한 형태",tip:"같은 문제를 더 나은 방식으로 바꾼 것입니다."}]}
 ],
 keys:[
  {en:"What struck me is that ~",ko:"제게 인상 깊었던 것은 ~ 라는 점입니다",ex:"What struck me is that he invents himself, not a stranger."},
  {en:"The important question is whether ~",ko:"중요한 질문은 ~ 인지 여부입니다",ex:"The important question is whether the two ever communicate."},
  {en:"The goal is not A. The goal is B.",ko:"목표는 A가 아니라 B입니다",ex:"The goal is not one true self. The goal is deciding who leads."},
  {en:"One clear sign is ~",ko:"분명한 신호 하나는 ~ 입니다",ex:"One clear sign is embarrassment about your own behaviour."},
  {en:"adapt to ~",ko:"~ 에 맞추다, 적응하다",ex:"Everyone adapts to the situation they are in."},
  {en:"reach the point where ~",ko:"~ 하는 지점에 이르다",ex:"It is fine until you reach the point where you cannot return."},
  {en:"be ashamed of ~",ko:"~ 를 부끄러워하다",ex:"One version of you is ashamed of the other."},
  {en:"trauma",ko:"외상, 정신적 충격",ex:"The clinical condition is usually connected to severe trauma."}
 ],
 out:[
  {q:"Describe a film or book that meant something different when you returned to it.",hint:"affect someone / look like ~ / What struck me is that ~"},
  {q:"Explain the difference between a clinical condition and ordinary behaviour.",hint:"trauma / behave differently in different situations / adapt to ~"},
  {q:"Restate someone's problem as a clearer question.",hint:"The important question is whether ~ / The goal is not A. The goal is B. / a real decision"}
 ]
},
{
 id:"w3d8", day:23, cat:"인생·중년", level:"B2+",
 title:"Fewer Options, Better Judgment",
 titleKo:"선택지는 줄고 판단력은 는다 — 중년을 세는 법",
 names:{A:"Sang (46, 제조업)", B:"Priya (49, 컨설턴트)"},
 brief:[
  "중년의 위기를 흔히 <b>후회</b>의 문제로 설명합니다. 그러나 겪는 사람들의 말을 들어 보면, 후회보다 자주 나오는 단어는 <b>좁아짐</b>입니다. 예전에는 열려 있던 문들이 하나씩 조용히 닫힙니다.",
  "이십 대에는 <b>아직 아무것도 정해지지 않았다</b>는 감각이 있습니다. 사십 대에는 정해진 것이 많고, 그중 상당수는 되돌리기 어렵습니다. 그 차이가 만들어 내는 불안은 실패가 아니라 <b>산수</b>에서 옵니다.",
  "반대편의 주장도 있습니다. 선택지가 줄어드는 대신 <b>선택의 질</b>이 올라간다는 것입니다. 무엇을 잘하고 무엇을 못하는지 알고, 어떤 사람과 시간을 보내야 하는지 압니다. 스무 살에는 없던 정보입니다.",
  "이 대화는 <b>인생 이야기를 감정적으로 흐르지 않게 말하는 법</b>을 연습하기 좋습니다. 비유(문·방·산수)를 하나 잡고 끝까지 밀고 가는 방식은 영어 대화에서 매우 효과적이니 그대로 가져가 보세요."
 ],
 lines:[
  {s:"A",en:"I notice that fewer things feel possible to me now at forty-six than felt possible at thirty.",
   ko:"마흔여섯인 지금, 서른 때 가능해 보이던 것들보다 가능해 보이는 게 줄었다는 걸 느낍니다.",
   notes:[{t:"I notice that ~",k:"business",m:"저는 ~ 라는 걸 느낍니다",tip:"관찰을 담담하게 꺼내는 시작입니다. I feel 보다 객관적으로 들립니다."},
          {t:"feel possible",k:"collocation",m:"가능하게 느껴지다",tip:"be possible(객관적 가능)과 달리 본인의 감각을 말합니다."}]},
  {s:"B",en:"Most people call that regret, but the real cause is having less time left, not having chosen wrongly.",
   ko:"대부분은 그걸 후회라고 부르지만, 진짜 원인은 잘못 고른 것이 아니라 남은 시간이 줄었다는 것입니다.",
   notes:[{t:"the real cause is A, not B",k:"business",m:"진짜 원인은 A이지 B가 아닙니다",tip:"원인을 바로잡을 때 쓰는 가장 분명한 문장 틀입니다."}]},
  {s:"A",en:"I don't follow. By income, position and health, I am doing better now than I was at thirty.",
   ko:"이해가 안 됩니다. 소득으로 보나 직위로 보나 건강으로 보나 저는 서른 때보다 지금이 낫습니다.",
   notes:[{t:"I don't follow.",k:"business",m:"이해가 안 됩니다",tip:"상대 논리를 못 따라갔다고 정중하게 밝히는 표준 표현입니다."},
          {t:"By A, B and C, ~",k:"grammar",m:"A와 B와 C로 보면 ~",tip:"판단의 기준을 먼저 나열해 주장을 검증 가능하게 만듭니다."}]},
  {s:"B",en:"You are doing better, but you have roughly half as many working years left to change direction.",
   ko:"형편은 나아졌습니다. 다만 방향을 바꿀 수 있는 근로 연수가 대략 절반밖에 남지 않았습니다.",
   notes:[{t:"half as many ~ as",k:"grammar",m:"~ 의 절반",tip:"배수 비교입니다. twice as many / three times as many 도 같은 형태입니다."},
          {t:"change direction",k:"business",m:"진로나 방향을 바꾸다",tip:"경력과 전략 양쪽에 씁니다."}]},
  {s:"A",en:"Stated that way it sounds depressing, and I would rather not measure my life in remaining years.",
   ko:"그렇게 말하니 우울하게 들립니다. 저는 남은 햇수로 제 인생을 재고 싶지 않습니다.",
   notes:[{t:"Stated that way, ~",k:"business",m:"그렇게 말하면 ~ 합니다",tip:"상대의 표현 방식 자체에 반응할 때의 정확한 표현입니다."},
          {t:"measure A in B",k:"collocation",m:"A를 B 단위로 재다",tip:"measure progress in months / measure value in hours."}]},
  {s:"B",en:"You don't have to measure it, but the number of options really does fall whether you count them or not.",
   ko:"재지 않으셔도 됩니다. 다만 세든 안 세든 선택지의 수는 실제로 줄어듭니다.",
   notes:[{t:"whether you A or not",k:"grammar",m:"A 하든 안 하든",tip:"어느 쪽이든 결과가 같음을 말하는 형태입니다."},
          {t:"does fall",k:"grammar",m:"실제로 줄어든다",tip:"동사 앞의 do/does 는 강조입니다. It does matter."}]},
  {s:"A",en:"I eliminated some of those options myself when I chose this company and this city.",
   ko:"그 선택지 중 일부는 제가 이 회사와 이 도시를 고르면서 직접 없앤 것입니다.",
   notes:[{t:"eliminate an option",k:"business",m:"선택지를 없애다",tip:"rule out 보다 격식 있고 최종적인 어감입니다."}]},
  {s:"B",en:"An option you gave up on purpose is a decision, and a decision is much easier to live with.",
   ko:"일부러 포기한 선택지는 결정입니다. 그리고 결정은 훨씬 견디기 쉽습니다.",
   notes:[{t:"give something up on purpose",k:"collocation",m:"일부러 포기하다",tip:"on purpose(의도적으로)와 by accident(우연히)는 짝입니다."},
          {t:"live with something",k:"business",m:"받아들이고 살아가다",tip:"완전히 만족하지는 않아도 감당할 수 있다는 뜻입니다."}]},
  {s:"A",en:"My concern is the options I never chose to give up, and those are what I think about at night.",
   ko:"제 걱정은 제가 포기하기로 결정한 적 없는 선택지들입니다. 밤에 생각나는 것도 그쪽입니다.",
   notes:[{t:"My concern is ~",k:"business",m:"제 걱정은 ~ 입니다",tip:"불안을 감정이 아니라 항목으로 제시하는 틀입니다."}]},
  {s:"B",en:"Name one specifically, because a specific plan is much easier to examine than a general feeling of loss.",
   ko:"구체적으로 하나만 말해 보세요. 막연한 상실감보다 구체적인 계획 하나가 훨씬 따져 보기 쉽습니다.",
   notes:[{t:"Name one specifically.",k:"business",m:"구체적으로 하나만 말해 보세요",tip:"막연한 주장에 구체성을 요구하는 짧고 강한 요청입니다."},
          {t:"examine",k:"business",m:"따져 보다, 검토하다",tip:"감정을 검토 대상으로 바꾸는 동사입니다."}]},
  {s:"A",en:"Starting my own business. I told myself I would do it before forty, and I did not.",
   ko:"제 사업을 시작하는 것입니다. 마흔 전에 하겠다고 스스로 말했는데, 하지 않았습니다.",
   notes:[{t:"I told myself I would ~",k:"grammar",m:"~ 하겠다고 스스로 말했다",tip:"지키지 못한 다짐을 말할 때의 형태입니다."}]},
  {s:"B",en:"Forty was a deadline you set for yourself, not a rule that anyone else imposed on you.",
   ko:"마흔은 본인이 스스로 정한 기한이지, 다른 누가 부과한 규칙이 아닙니다.",
   notes:[{t:"a deadline you set for yourself",k:"collocation",m:"스스로 정한 기한",tip:"자의적인 기준임을 지적하는 표현입니다."},
          {t:"impose a rule on someone",k:"business",m:"규칙을 부과하다",tip:"위에서 아래로 강제한다는 방향성이 담깁니다."}]},
  {s:"A",en:"That is true, but starting now means starting with a mortgage to pay and two children to support.",
   ko:"맞는 말입니다. 그래도 지금 시작한다는 건 갚을 대출과 부양할 아이 둘을 안고 시작한다는 뜻입니다.",
   notes:[{t:"a mortgage to pay",k:"grammar",m:"갚아야 할 대출",tip:"명사 + to부정사로 「~ 해야 할 것」을 만듭니다. work to do / bills to pay."},
          {t:"support",k:"business",m:"부양하다",tip:"경제적으로 책임진다는 뜻입니다. support a family / support two children."}]},
  {s:"B",en:"It also means starting with customers, a credit record and twenty years of judgment you did not have at thirty.",
   ko:"그건 고객과 신용 기록, 그리고 서른 때는 없었던 20년의 판단력을 안고 시작한다는 뜻이기도 합니다.",
   notes:[{t:"It also means ~",k:"business",m:"그것은 또한 ~ 라는 뜻이기도 합니다",tip:"같은 사실의 반대 면을 제시하는 형태입니다."},
          {t:"judgment",k:"business",m:"판단력",tip:"경험에서 오는 무형의 자산을 가리킵니다."}]},
  {s:"A",en:"I had not counted those on the other side, and they do change the calculation.",
   ko:"그쪽 항목은 세어 보지 않았습니다. 그리고 그것들이 계산을 바꾸긴 합니다.",
   notes:[{t:"count something on the other side",k:"collocation",m:"반대편 항목으로 세다",tip:"손익의 양쪽을 모두 계산에 넣는다는 뜻입니다."}]},
  {s:"B",en:"You lose options and you gain judgment, and nobody explains that exchange to you at twenty.",
   ko:"선택지는 잃고 판단력은 얻습니다. 스무 살에는 아무도 그 교환을 설명해 주지 않습니다.",
   notes:[{t:"an exchange",k:"business",m:"맞바꿈, 교환",tip:"무엇을 내주고 무엇을 얻는지가 분명할 때 씁니다."}]},
  {s:"A",en:"Describing it as an exchange is more comfortable, but I want to know whether it is actually true.",
   ko:"교환이라고 설명하면 더 편안합니다. 다만 저는 그게 실제로 사실인지를 알고 싶습니다.",
   notes:[{t:"I want to know whether ~",k:"business",m:"~ 인지를 알고 싶습니다",tip:"위안과 사실을 구분해 달라고 요구하는 문장입니다."}]},
  {s:"B",en:"Then test it. Would you trade the judgment you have today for the options you had at twenty-five?",
   ko:"그럼 시험해 보세요. 오늘 가진 판단력을 스물다섯의 선택지와 바꾸시겠습니까?",
   notes:[{t:"Would you trade A for B?",k:"business",m:"A를 B와 바꾸시겠습니까",tip:"두 가치를 직접 비교하게 만드는 아주 강한 질문입니다."}]},
  {s:"A",en:"No, I would not. I would keep the judgment and continue to complain about the lost options.",
   ko:"아니요, 바꾸지 않겠습니다. 판단력은 그대로 갖고, 잃은 선택지에 대해서는 계속 불평하겠습니다.",
   notes:[{t:"No, I would not.",k:"business",m:"아니요, 그러지 않겠습니다",tip:"가정 질문에 조동사를 되받아 짧게 답하는 형태입니다."}]},
  {s:"B",en:"Then this is not a crisis. You are adjusting to fewer options and a better ability to choose among them.",
   ko:"그럼 이건 위기가 아닙니다. 선택지는 줄고 그중에서 고르는 능력은 나아진 상태에 적응하는 중입니다.",
   notes:[{t:"adjust to ~",k:"business",m:"~ 에 적응하다",tip:"상황 변화에 맞춰 자신을 조정하는 것입니다."},
          {t:"the ability to ~",k:"grammar",m:"~ 할 수 있는 능력",tip:"뒤에 to부정사가 고정입니다. the ability to choose."}]}
 ],
 keys:[
  {en:"I don't follow.",ko:"이해가 안 됩니다",ex:"I don't follow. Can you say that again with an example?"},
  {en:"Stated that way, ~",ko:"그렇게 말하면 ~ 합니다",ex:"Stated that way, it sounds much worse than it is."},
  {en:"Name one specifically.",ko:"구체적으로 하나만 말해 보세요",ex:"Name one specifically, and we can look at whether it is still open."},
  {en:"Would you trade A for B?",ko:"A를 B와 바꾸시겠습니까",ex:"Would you trade your current salary for the free time you had then?"},
  {en:"change direction",ko:"진로나 방향을 바꾸다",ex:"I have about fifteen working years left to change direction."},
  {en:"give something up on purpose",ko:"일부러 포기하다",ex:"An option you gave up on purpose is a decision, not a loss."},
  {en:"judgment",ko:"경험에서 오는 판단력",ex:"You start with twenty years of judgment you did not have at thirty."},
  {en:"the calculation",ko:"셈, 계산",ex:"Counting both sides does change the calculation."}
 ],
 out:[
  {q:"Describe how your sense of what is possible has changed since your twenties.",hint:"I notice that ~ / feel possible / change direction"},
  {q:"Say you don't understand someone's reasoning, and ask them to be specific.",hint:"I don't follow. / Name one specifically. / examine"},
  {q:"Compare what you have lost with what you have gained, and reach a conclusion.",hint:"It also means ~ / the calculation / Would you trade A for B?"}
 ]
},
{
 id:"w3d9", day:24, cat:"문화·스타일", level:"B2+",
 title:"Why Italians Dress Well",
 titleKo:"이탈리아 남자들은 왜 옷을 잘 입는가 — 스프레차투라의 경제학",
 names:{A:"Marco (밀라노 출신)", B:"Joon (서울, 패션 무관심)"},
 brief:[
  "「이탈리아 남자는 옷을 잘 입는다」는 말은 흔하지만, 설명은 대개 취향 이야기에서 멈춥니다. 실제 이유의 상당 부분은 <b>산업</b>에 있습니다. 이탈리아 북부는 수백 년 동안 유럽의 직물 생산지였습니다.",
  "좋은 원단이 가까이 있으면 <b>옷값의 구조</b>가 달라집니다. 재단사가 많고, 수선이 싸고, 좋은 옷을 오래 입는 것이 합리적인 선택이 됩니다. 취향은 그 위에서 자랍니다.",
  "여기에 <b>스프레차투라</b>라는 개념이 붙습니다. 애써 노력한 티가 나지 않게 잘 해내는 태도입니다. 옷에서는 「신경 쓴 티 안 나게 신경 쓴」 상태를 뜻합니다. 이 개념 자체가 아주 좋은 영어 대화 소재입니다.",
  "이 대화는 <b>문화적 일반화를 조심스럽게 다루는 법</b>도 함께 연습합니다. 「~ 하는 경향이 있다」, 「그건 과장이다」 같은 표현을 익혀 두면, 국가나 세대를 두고 이야기할 때 훨씬 안전하고 설득력 있게 말할 수 있습니다."
 ],
 lines:[
  {s:"A",en:"You keep saying that Italian men dress well, and I think that is a generalization.",
   ko:"이탈리아 남자들이 옷을 잘 입는다고 계속 말씀하시는데, 저는 그게 일반화라고 봅니다.",
   notes:[{t:"a generalization",k:"business",m:"일반화",tip:"개별 사례를 전체로 확대한 진술입니다."}]},
  {s:"B",en:"Generalizations usually have a cause. What produced this particular one?",
   ko:"일반화에는 대개 원인이 있습니다. 이건 무엇이 만들어 낸 겁니까?",
   notes:[{t:"What produced ~ ?",k:"business",m:"무엇이 ~ 를 만들어 냈습니까",tip:"현상의 원인을 직접 묻는 질문입니다."}]},
  {s:"A",en:"The cause is the textile industry, because northern Italy has produced cloth for six hundred years.",
   ko:"원인은 직물 산업입니다. 북부 이탈리아가 600년 동안 천을 생산해 왔으니까요.",
   notes:[{t:"the textile industry",k:"business",m:"직물 산업",tip:"섬유를 만드는 산업 전체입니다."}]},
  {s:"B",en:"I had not connected those two facts. So the industry came before the taste did?",
   ko:"그 두 사실을 연결해 본 적이 없습니다. 그럼 취향보다 산업이 먼저였다는 겁니까?",
   notes:[{t:"connect two facts",k:"collocation",m:"두 사실을 연결하다",tip:"인과나 관련성을 인식하는 것입니다."}]},
  {s:"A",en:"Largely, yes. When good cloth is produced locally, a well-made jacket is no longer unusual.",
   ko:"대체로 그렇습니다. 좋은 천이 현지에서 생산되면, 잘 만든 재킷이 더는 드문 물건이 아닙니다.",
   notes:[{t:"no longer unusual",k:"collocation",m:"더는 드물지 않은",tip:"희소성이 사라진 상태입니다."}]},
  {s:"B",en:"That makes economic sense, because low prices change what people consider normal.",
   ko:"경제적으로 말이 됩니다. 낮은 가격이 사람들이 정상이라고 여기는 기준을 바꾸니까요.",
   notes:[{t:"make economic sense",k:"collocation",m:"경제적으로 타당하다",tip:"비용과 편익이 맞는다는 뜻입니다."},
          {t:"consider ~ normal",k:"collocation",m:"~ 를 정상으로 여기다",tip:"기준이 형성되는 과정을 표현합니다."}]},
  {s:"A",en:"Tailoring also stayed inexpensive, so people repair clothes rather than replacing them.",
   ko:"재단 비용도 계속 쌌습니다. 그래서 사람들이 옷을 바꾸는 대신 고쳐 입습니다.",
   notes:[{t:"tailoring",k:"business",m:"재단, 수선업",tip:"옷을 맞추거나 고치는 일입니다."},
          {t:"repair rather than replace",k:"collocation",m:"교체하는 대신 수선하다",tip:"소비 행태를 대조하는 짝입니다."}]},
  {s:"B",en:"In Seoul, altering a jacket sometimes costs more than the jacket originally cost.",
   ko:"서울에서는 재킷을 고치는 비용이 그 재킷의 원래 가격보다 비쌀 때가 있습니다.",
   notes:[{t:"alter",k:"business",m:"(옷을) 수선하다",tip:"치수를 고치는 것입니다. alteration 이 명사형입니다."}]},
  {s:"A",en:"Then the habit cannot develop, because the habit depends on repair being affordable.",
   ko:"그럼 그 습관은 생길 수 없습니다. 그 습관은 수선이 감당할 만해야 성립하니까요.",
   notes:[{t:"depend on ~",k:"collocation",m:"~ 에 달려 있다",tip:"성립 조건을 명시합니다."},
          {t:"affordable",k:"business",m:"감당할 만한 가격의",tip:"소득 대비 부담 가능한 수준입니다."}]},
  {s:"B",en:"What is the part that economics does not explain? There must be a cultural element as well.",
   ko:"경제로 설명되지 않는 부분은 무엇입니까? 문화적 요소도 있을 텐데요.",
   notes:[{t:"a cultural element",k:"business",m:"문화적 요소",tip:"경제적 요인과 구별되는 설명입니다."}]},
  {s:"A",en:"There is a term for it: sprezzatura, which means effort that is deliberately not visible.",
   ko:"그것을 가리키는 용어가 있습니다. 스프레차투라인데, 의도적으로 드러나지 않게 한 노력을 뜻합니다.",
   notes:[{t:"There is a term for it:",k:"business",m:"그것을 가리키는 용어가 있습니다",tip:"개념을 소개하는 도입 문장입니다."},
          {t:"deliberately",k:"business",m:"의도적으로",tip:"우연이 아니라 의식적인 선택임을 강조합니다."}]},
  {s:"B",en:"That sounds tiring, because concealing the effort requires additional effort of its own.",
   ko:"피곤하게 들립니다. 노력을 감추는 데 또 다른 노력이 필요하니까요.",
   notes:[{t:"conceal",k:"business",m:"감추다",tip:"hide 보다 격식 있고 의도성이 강합니다."}]},
  {s:"A",en:"It does, and Italians would not admit it. The objective is to appear entirely unconcerned.",
   ko:"그렇습니다. 그리고 이탈리아 사람들은 인정하지 않을 겁니다. 목표는 전혀 신경 쓰지 않는 것처럼 보이는 겁니다.",
   notes:[{t:"The objective is to ~",k:"business",m:"목표는 ~ 하는 것입니다",tip:"의도를 분명히 선언하는 문장입니다."},
          {t:"appear unconcerned",k:"collocation",m:"신경 쓰지 않는 것처럼 보이다",tip:"태도를 연출하는 것입니다."}]},
  {s:"B",en:"We have an equivalent here, which is looking as though you did not prepare at all.",
   ko:"여기에도 비슷한 게 있습니다. 전혀 준비하지 않은 것처럼 보이는 것이죠.",
   notes:[{t:"an equivalent",k:"business",m:"대응되는 것, 등가물",tip:"다른 문화의 비슷한 개념을 가리킵니다."}]},
  {s:"A",en:"Then you already understand the idea. You have simply never spent money on the result.",
   ko:"그럼 그 개념은 이미 이해하고 계십니다. 다만 그 결과에 돈을 써 본 적이 없을 뿐이죠.",
   notes:[{t:"spend money on ~",k:"collocation",m:"~ 에 돈을 쓰다",tip:"전치사 on 이 고정입니다."}]},
  {s:"B",en:"Where should I begin? I own four shirts and all four of them are identical.",
   ko:"어디서부터 시작해야 합니까? 셔츠가 네 벌인데 넷 다 똑같습니다.",
   notes:[{t:"identical",k:"business",m:"완전히 똑같은",tip:"similar 보다 강한 동일성을 뜻합니다."}]},
  {s:"A",en:"Begin with fit rather than brand, because an inexpensive jacket that fits looks better than an expensive one that does not.",
   ko:"브랜드가 아니라 핏부터 시작하세요. 잘 맞는 싼 재킷이 안 맞는 비싼 재킷보다 나아 보입니다.",
   notes:[{t:"fit rather than brand",k:"collocation",m:"브랜드가 아니라 핏",tip:"우선순위를 대비로 제시합니다."}]},
  {s:"B",en:"That is much less expensive advice than I expected from somebody who grew up in Milan.",
   ko:"밀라노에서 자란 분에게서 기대한 것보다 훨씬 덜 비싼 조언입니다.",
   notes:[{t:"less expensive than I expected",k:"collocation",m:"기대보다 덜 비싼",tip:"비교급으로 가벼운 놀람을 표현합니다."}]},
  {s:"A",en:"The expensive part was never the clothing itself. The expensive part was the tailor.",
   ko:"비싼 부분은 옷 자체였던 적이 없습니다. 비싼 부분은 재단사였습니다.",
   notes:[{t:"The expensive part was never A. It was B.",k:"grammar",m:"비싼 부분은 A가 아니라 B였습니다",tip:"오해를 뒤집는 두 문장 골격입니다."}]},
  {s:"B",en:"Then I will find a tailor, although I do not intend to pretend I am unconcerned about it.",
   ko:"그럼 재단사를 찾겠습니다. 다만 신경 안 쓰는 척할 생각은 없습니다.",
   notes:[{t:"I do not intend to ~",k:"business",m:"~ 할 생각은 없습니다",tip:"의도를 분명히 부정하는 표현입니다."}]}
 ],
 keys:[
  {en:"What produced ~ ?",ko:"무엇이 ~ 를 만들어 냈습니까",ex:"What produced that reputation in the first place?"},
  {en:"There is a term for it:",ko:"그것을 가리키는 용어가 있습니다",ex:"There is a term for it: effort that is not visible."},
  {en:"The objective is to ~",ko:"목표는 ~ 하는 것입니다",ex:"The objective is to appear entirely unconcerned."},
  {en:"The expensive part was never A. It was B.",ko:"비싼 부분은 A가 아니라 B였습니다",ex:"The expensive part was never the clothes. It was the tailor."},
  {en:"a generalization",ko:"일반화",ex:"That is a generalization, and generalizations have causes."},
  {en:"repair rather than replace",ko:"교체하는 대신 수선하다",ex:"People repair rather than replace when tailoring is cheap."},
  {en:"affordable",ko:"감당할 만한 가격의",ex:"The habit depends on repair being affordable."},
  {en:"an equivalent",ko:"대응되는 것",ex:"We have an equivalent here with a different name."}
 ],
 out:[
  {q:"Question a generalization and ask what caused it.",hint:"a generalization / What produced ~ ? / connect two facts"},
  {q:"Explain how a local industry changes what people consider normal.",hint:"the textile industry / no longer unusual / consider ~ normal"},
  {q:"Introduce a foreign concept and give the local equivalent.",hint:"There is a term for it: / The objective is to ~ / an equivalent"}
 ]
},
{
 id:"w3d10", day:25, cat:"사상·미래", level:"C1",
 title:"When Abundance Stops Being the Plan",
 titleKo:"풍요가 더 이상 계획이 아닐 때 — 희소성의 정치학",
 names:{A:"Elena (정치철학 연구자)", B:"Tomas (테크 업계)"},
 brief:[
  "전후 70년의 기본 가정은 <b>파이가 계속 커진다</b>는 것이었습니다. 성장하면 나눌 것이 늘고, 그러면 분배 논쟁도 견딜 만해집니다. 민주주의의 여유는 상당 부분 이 가정 위에 있었습니다.",
  "최근 몇 년, 그 가정을 <b>내려놓은 사람들</b>이 눈에 띕니다. 에너지, 인구, 반도체, 물처럼 늘리기 어려운 것들을 앞세우며, 성장이 아니라 <b>확보</b>를 말합니다. 파이가 고정이라면 논리적 귀결은 「내 몫을 지키는 것」입니다.",
  "여기서 한 걸음 더 나간 흐름이 <b>다크 인라이튼먼트</b>로 불리는 사상입니다. 민주적 절차가 느리고 비효율적이니 유능한 소수가 결정해야 한다는 주장입니다. 소수의 견해지만, 영향력 있는 곳에서 인용된다는 점이 논쟁거리입니다.",
  "이 대화의 목적은 편을 정하는 것이 아니라, <b>불편한 사상을 정확하게 요약하고 반박하는 영어</b>를 익히는 것입니다. 「그 논리를 끝까지 밀면 어떻게 되는가」를 묻는 문장들에 특히 주목하세요."
 ],
 lines:[
  {s:"A",en:"For seventy years we could argue about distribution because everyone assumed the economy would grow.",
   ko:"70년 동안 우리는 분배를 두고 다툴 수 있었습니다. 경제가 성장할 거라고 모두가 전제했으니까요.",
   notes:[{t:"distribution",k:"business",m:"분배",tip:"생산된 것을 나누는 방식입니다."},
          {t:"assume",k:"business",m:"전제하다",tip:"증명 없이 사실로 놓는 것입니다."}]},
  {s:"B",en:"A number of people in my industry have stopped making that assumption.",
   ko:"제 업계의 상당수는 그 전제를 놓는 것을 그만뒀습니다.",
   notes:[{t:"make an assumption",k:"business",m:"전제를 놓다",tip:"가정을 세우는 행위입니다."}]},
  {s:"A",en:"On what evidence? Growth has slowed, but it has not stopped in any major economy.",
   ko:"무슨 근거로요? 성장이 둔화되긴 했지만, 주요 경제 어디서도 멈추지는 않았습니다.",
   notes:[{t:"On what evidence?",k:"business",m:"무슨 근거로요",tip:"주장에 증거를 요구하는 짧고 강한 질문입니다."}]},
  {s:"B",en:"Energy, water, semiconductors and people: four inputs you cannot increase by deciding to.",
   ko:"에너지, 물, 반도체, 사람. 마음먹는다고 늘릴 수 없는 네 가지 투입물입니다.",
   notes:[{t:"an input",k:"business",m:"투입물",tip:"생산에 들어가는 자원입니다. output 과 짝입니다."}]},
  {s:"A",en:"Those are real constraints, but a constraint does not make the total permanently fixed.",
   ko:"실제 제약인 건 맞습니다. 다만 제약이 있다고 총량이 영구히 고정되지는 않습니다.",
   notes:[{t:"a constraint",k:"business",m:"제약",tip:"늘릴 수 없는 한계 조건입니다."},
          {t:"permanently fixed",k:"collocation",m:"영구히 고정된",tip:"변하지 않는 상태입니다."}]},
  {s:"B",en:"No, but if you believe it might be fixed, your strategy changes immediately.",
   ko:"아닙니다. 다만 고정일 수도 있다고 믿으면 전략이 즉시 바뀝니다.",
   notes:[{t:"change immediately",k:"collocation",m:"즉시 바뀌다",tip:"믿음이 행동을 바꾸는 속도를 말합니다."}]},
  {s:"A",en:"Changes into what, specifically? I want the actual policy, not the general attitude.",
   ko:"구체적으로 무엇으로 바뀝니까? 일반적인 태도가 아니라 실제 정책을 원합니다.",
   notes:[{t:"Changes into what, specifically?",k:"business",m:"구체적으로 무엇으로 바뀝니까",tip:"추상적인 답을 차단하는 질문입니다."}]},
  {s:"B",en:"Securing supply rather than expanding it, which means buying the input instead of competing for the market.",
   ko:"공급을 늘리기보다 확보하는 것입니다. 시장에서 경쟁하는 대신 투입물을 사들인다는 뜻이죠.",
   notes:[{t:"secure supply",k:"business",m:"공급을 확보하다",tip:"물량을 미리 잡아 두는 것입니다."}]},
  {s:"A",en:"Follow that reasoning to its conclusion and it arrives at a politically difficult position.",
   ko:"그 논리를 끝까지 따라가면 정치적으로 곤란한 입장에 도달합니다.",
   notes:[{t:"follow a reasoning to its conclusion",k:"business",m:"논리를 끝까지 따라가다",tip:"귀결을 검토하라는 요구입니다."}]},
  {s:"B",en:"I know which position you mean. You are referring to the anti-democratic version of the argument.",
   ko:"어떤 입장을 말씀하시는지 압니다. 그 논리의 반민주적인 형태를 가리키시는 거죠.",
   notes:[{t:"refer to ~",k:"phrasal",m:"~ 를 가리키다",tip:"언급 대상을 명시합니다."}]},
  {s:"A",en:"Yes. The claim that capable people should make decisions without going through an election.",
   ko:"그렇습니다. 유능한 사람들이 선거를 거치지 않고 결정을 내려야 한다는 주장입니다.",
   notes:[{t:"a claim",k:"business",m:"주장",tip:"증명되지 않은 진술입니다."},
          {t:"go through an election",k:"collocation",m:"선거를 거치다",tip:"절차를 통과한다는 뜻입니다."}]},
  {s:"B",en:"Very few people state it that plainly, but the same reasoning appears in other forms.",
   ko:"그렇게 평이하게 말하는 사람은 아주 적습니다. 다만 같은 논리가 다른 형태로 나타납니다.",
   notes:[{t:"state it plainly",k:"collocation",m:"평이하게 말하다",tip:"에두르지 않고 직접 말하는 것입니다."}]},
  {s:"A",en:"Then let us examine it on its own terms, beginning with competent by whose measurement.",
   ko:"그럼 그 논리 자체의 기준으로 검토해 봅시다. 누구의 기준으로 유능한가부터요.",
   notes:[{t:"on its own terms",k:"business",m:"그 자체의 기준으로",tip:"상대의 전제를 받아들인 채 검토하는 방식입니다."},
          {t:"by whose measurement",k:"grammar",m:"누구의 기준으로",tip:"평가 기준의 주체를 묻습니다."}]},
  {s:"B",en:"That is the weakest part of the argument, because competent usually describes whoever currently holds power.",
   ko:"그게 그 주장의 가장 약한 부분입니다. 유능하다는 말은 대개 지금 권력을 가진 쪽을 가리키니까요.",
   notes:[{t:"hold power",k:"collocation",m:"권력을 쥐다",tip:"지위를 가진 상태입니다."}]},
  {s:"A",en:"And there is no mechanism to replace them, which is the entire purpose of an election.",
   ko:"게다가 그들을 교체할 장치가 없습니다. 그게 선거의 존재 목적 전부인데요.",
   notes:[{t:"a mechanism",k:"business",m:"장치, 제도적 수단",tip:"목적을 실현하는 구조입니다."},
          {t:"replace someone",k:"business",m:"교체하다",tip:"자리에서 물러나게 하고 다른 사람을 앉히는 것입니다."}]},
  {s:"B",en:"I agree, though what attracts people is not the theory. It is the frustration with slow decisions.",
   ko:"동의합니다. 다만 사람들을 끄는 것은 이론이 아닙니다. 느린 결정에 대한 좌절감입니다.",
   notes:[{t:"what attracts people is ~",k:"grammar",m:"사람들을 끄는 것은 ~ 이다",tip:"진짜 동인을 지목하는 강조 구문입니다."}]},
  {s:"A",en:"The frustration is legitimate. It is not an argument for removing accountability from decision makers.",
   ko:"그 좌절감은 정당합니다. 다만 의사결정자에게서 책임을 없앨 근거는 아닙니다.",
   notes:[{t:"accountability",k:"business",m:"책임 소재",tip:"결정에 대해 답해야 하는 의무입니다."},
          {t:"a decision maker",k:"business",m:"의사결정자",tip:"최종 판단을 내리는 사람입니다."}]},
  {s:"B",en:"Then what would you offer somebody who genuinely believes the process takes too long?",
   ko:"그럼 절차가 정말로 너무 오래 걸린다고 믿는 사람에게 무엇을 제안하시겠습니까?",
   notes:[{t:"take too long",k:"collocation",m:"너무 오래 걸리다",tip:"시간 문제를 평이하게 표현합니다."}]},
  {s:"A",en:"Faster institutions rather than fewer of them, because speed and consent are not in conflict.",
   ko:"제도를 줄이는 게 아니라 더 빠르게 만드는 것입니다. 속도와 동의는 서로 충돌하지 않으니까요.",
   notes:[{t:"A rather than B",k:"grammar",m:"B가 아니라 A",tip:"대안을 정확히 대비하는 형태입니다."},
          {t:"be in conflict",k:"collocation",m:"서로 충돌하다",tip:"양립할 수 없는 관계를 말합니다."}]},
  {s:"B",en:"That is harder to explain in public, but it is the position I would rather defend.",
   ko:"그건 공개적으로 설명하기가 더 어렵습니다. 그래도 제가 변호하고 싶은 입장은 그쪽입니다.",
   notes:[{t:"harder to explain in public",k:"collocation",m:"공개적으로 설명하기 더 어려운",tip:"설득 난이도를 평이하게 표현합니다."}]}
 ],
 keys:[
  {en:"On what evidence?",ko:"무슨 근거로요",ex:"On what evidence did they stop assuming growth?"},
  {en:"Changes into what, specifically?",ko:"구체적으로 무엇으로 바뀝니까",ex:"Changes into what, specifically? Give me the policy."},
  {en:"on its own terms",ko:"그 자체의 기준으로",ex:"Let us examine the argument on its own terms first."},
  {en:"A rather than B",ko:"B가 아니라 A",ex:"Faster institutions rather than fewer of them."},
  {en:"a constraint",ko:"제약",ex:"Those are real constraints, not a permanent ceiling."},
  {en:"secure supply",ko:"공급을 확보하다",ex:"The strategy becomes securing supply rather than expanding it."},
  {en:"accountability",ko:"책임 소재",ex:"Frustration is not an argument for removing accountability."},
  {en:"by whose measurement",ko:"누구의 기준으로",ex:"Competent by whose measurement, exactly?"}
 ],
 out:[
  {q:"Ask someone to justify a change in their basic assumption.",hint:"On what evidence? / assume / an input"},
  {q:"Summarize an argument you disagree with fairly, then examine it.",hint:"on its own terms / a claim / by whose measurement"},
  {q:"Answer someone who says democratic decisions take too long.",hint:"take too long / A rather than B / accountability"}
 ]
}
