{
 id:"c2d1", day:8, cat:"이웃·갈등", level:"HSK 5~6",
 title:"楼上的动静", titlePy:"lóushàng de dòngjing", titleKo:"위층의 소음 — 얼굴 붉히지 않고 항의하기",
 names:{A:"小林 (아래층)", B:"张姐 (위층 이웃)"},
 brief:[
  "층간 소음은 옳고 그름을 가리는 문제가 아니라 <b>관계를 남기면서 요구를 관철하는</b> 문제입니다. 중국에서도 여기서 말을 잘못 꺼내면 그날로 원수가 됩니다. 그래서 첫 문장이 거의 전부입니다.",
  "핵심 장치는 <b>부정 + 재규정</b>입니다. 「不是嫌，就是…(싫다는 게 아니라 다만 ~)」처럼 상대가 들을 비난을 먼저 지워 놓고 요구를 꺼냅니다. 그다음 <b>将心比心(입장을 바꿔 생각하다)</b>으로 같은 편에 서 버립니다.",
  "중국인이 이런 자리에서 자주 쓰는 말이 <b>抬头不见低头见</b>입니다. 「고개를 들어도 숙여도 마주치는 사이」라는 뜻으로, 오래 볼 사이니 좋게 끝내자는 신호입니다. <b>得饶人处且饶人</b>도 같은 자리에서 나옵니다.",
  "이 회차에는 가능보어가 특히 많이 들어 있습니다. <b>睡不着 · 坐不住 · 拦不住 · 受得了</b>. 「할 수 있다/없다」를 조동사가 아니라 동사 뒤에 붙여 말하는 이 감각이 붙으면 회화가 단번에 어른스러워집니다."
 ],
 vocab:[
  {w:"动静",p:"dòngjing",m:"기척, 소리, 낌새",lv:"HSK6"},
  {w:"打扰",p:"dǎrǎo",m:"폐를 끼치다, 방해하다",lv:"HSK5"},
  {w:"将心比心",p:"jiāng xīn bǐ xīn",m:"입장을 바꿔 생각하다 (성어)",lv:"성어"},
  {w:"抬头不见低头见",p:"táitóu bú jiàn dītóu jiàn",m:"늘 마주칠 수밖에 없는 사이다",lv:"성어"},
  {w:"闹别扭",p:"nào bièniu",m:"틀어지다, 서먹해지다",lv:"구어"},
  {w:"物业",p:"wùyè",m:"(아파트) 관리사무소",lv:"HSK6"},
  {w:"投诉",p:"tóusù",m:"민원을 넣다, 신고하다",lv:"HSK5"},
  {w:"忍无可忍",p:"rěn wú kě rěn",m:"더는 참을 수 없다 (성어)",lv:"성어"},
  {w:"得饶人处且饶人",p:"dé ráo rén chù qiě ráo rén",m:"봐줄 수 있을 때는 봐줘라",lv:"성어"},
  {w:"通情达理",p:"tōng qíng dá lǐ",m:"사리에 밝고 이해심이 있다 (성어)",lv:"성어"},
  {w:"远亲不如近邻",p:"yuǎnqīn bùrú jìnlín",m:"먼 친척보다 가까운 이웃이 낫다",lv:"성어"},
  {w:"憋着",p:"biē zhe",m:"(말·감정을) 참고 담아 두다",lv:"구어"}
 ],
 lines:[
  {s:"A",zh:"张姐，实在不好意思，这么晚了还来打扰您。",py:"Zhāng jiě, shízài bù hǎoyìsi, zhème wǎn le hái lái dǎrǎo nín.",
   ko:"장 언니, 정말 죄송해요, 이렇게 늦은 시간에 찾아와서요.",
   ck:[["张姐，实在不好意思","Zhāng jiě, shízài bù hǎoyìsi"],["这么晚了还来打扰您","zhème wǎn le hái lái dǎrǎo nín"]],
   notes:[{t:"实在",p:"shízài",k:"word",m:"정말로, 참으로",tip:"真的보다 무겁고 정중합니다. 사과와 하소연에 특히 잘 붙습니다. 实在对不起 / 实在没办法."},
          {t:"这么晚了还…",p:"zhème wǎn le hái…",k:"expr",m:"이렇게 늦었는데도 ~하다",tip:"了 뒤에 还를 붙이면 미안함이 실립니다. 这么晚了还麻烦您."}]},
  {s:"B",zh:"哎，小林啊，快进来坐，是不是又嫌我们家吵了？",py:"Āi, Xiǎo Lín a, kuài jìnlái zuò, shì bu shì yòu xián wǒmen jiā chǎo le?",
   ko:"어머, 샤오린이구나, 어서 들어와 앉아. 또 우리 집 시끄럽다고 온 거지?",
   ck:[["哎，小林啊","Āi, Xiǎo Lín a"],["快进来坐","kuài jìnlái zuò"],["是不是又嫌我们家吵了","shì bu shì yòu xián wǒmen jiā chǎo le"]],
   notes:[{t:"嫌",p:"xián",k:"word",m:"~이 싫다고 여기다, 못마땅해하다",tip:"嫌贵 / 嫌麻烦 / 嫌吵. 讨厌보다 가볍고 일상적입니다."},
          {t:"是不是…了？",p:"shì bu shì…le?",k:"grammar",m:"~한 거 아니야? (짐작을 던져 확인)",tip:"상대가 말을 꺼내기 전에 먼저 짚어 주는 화법. 부드럽게 선수를 칩니다."}]},
  {s:"A",zh:"不是嫌，就是这两天晚上过了十一点还有动静，实在睡不着。",py:"Bú shì xián, jiùshì zhè liǎng tiān wǎnshang guò le shíyī diǎn hái yǒu dòngjing, shízài shuì bu zháo.",
   ko:"싫다는 게 아니라, 요 며칠 밤 열한 시 넘어서도 소리가 나서 정말 잠을 못 자겠어요.",
   ck:[["不是嫌","Bú shì xián"],["就是这两天晚上过了十一点还有动静","jiùshì zhè liǎng tiān wǎnshang guò le shíyī diǎn hái yǒu dòngjing"],["实在睡不着","shízài shuì bu zháo"]],
   notes:[{t:"不是A，就是B",p:"bú shì A, jiùshì B",k:"expr",m:"A가 아니라 다만 B다",tip:"이 회차의 핵심 골격입니다. 비난으로 들릴 말을 먼저 지우고 요구를 꺼냅니다."},
          {t:"睡不着",p:"shuì bu zháo",k:"grammar",m:"(자려 해도) 잠들 수 없다",tip:"가능보어. 睡不着(잠이 안 옴) / 睡不好(설침) / 睡不了(잘 수 없음)는 다 다릅니다."}]},
  {s:"B",zh:"说是这么说，可孩子刚上小学，一写作业就坐不住，我也拦不住啊。",py:"Shuō shì zhème shuō, kě háizi gāng shàng xiǎoxué, yì xiě zuòyè jiù zuò bu zhù, wǒ yě lán bu zhù a.",
   ko:"말이야 그렇지, 애가 초등학교 막 들어가서 숙제만 하면 가만히 못 앉아 있으니 나도 못 말려.",
   ck:[["说是这么说","Shuō shì zhème shuō"],["可孩子刚上小学","kě háizi gāng shàng xiǎoxué"],["一写作业就坐不住","yì xiě zuòyè jiù zuò bu zhù"],["我也拦不住啊","wǒ yě lán bu zhù a"]],
   notes:[{t:"说是这么说",p:"shuō shì zhème shuō",k:"expr",m:"말이야 그렇지만",tip:"상대 말을 반박하기 직전에 놓는 완충재입니다. 뒤에는 반드시 可나 但是가 옵니다."},
          {t:"一…就…",p:"yī…jiù…",k:"grammar",m:"~하기만 하면 곧 ~하다",tip:"조건과 결과를 붙이는 가장 흔한 골격. 一到夏天就下雨."},
          {t:"拦不住",p:"lán bu zhù",k:"grammar",m:"말릴 수 없다",tip:"V不住는 '붙잡아 두지 못한다'는 계열입니다. 坐不住 / 记不住 / 忍不住."}]},
  {s:"A",zh:"我理解，将心比心，我也带过孩子，可总不能天天到半夜吧。",py:"Wǒ lǐjiě, jiāng xīn bǐ xīn, wǒ yě dài guo háizi, kě zǒng bù néng tiāntiān dào bànyè ba.",
   ko:"이해해요, 저도 애 키워 봤으니 입장 바꿔 생각하죠. 그래도 매일 한밤중까지는 좀 그렇잖아요.",
   ck:[["我理解，将心比心","Wǒ lǐjiě, jiāng xīn bǐ xīn"],["我也带过孩子","wǒ yě dài guo háizi"],["可总不能天天到半夜吧","kě zǒng bù néng tiāntiān dào bànyè ba"]],
   notes:[{t:"将心比心",p:"jiāng xīn bǐ xīn",k:"idiom",m:"입장을 바꿔 생각하다",tip:"이 말 한마디로 '나는 당신 편'이라는 신호가 됩니다. 항의를 부드럽게 만드는 성어입니다."},
          {t:"总不能…吧",p:"zǒng bù néng…ba",k:"expr",m:"설마 ~할 수는 없잖아요",tip:"직접 요구하지 않고 상대가 스스로 결론 내게 만드는 골격입니다. 아주 자주 씁니다."}]},
  {s:"B",zh:"那你说怎么办？我总不能把孩子绑起来吧，他也不是故意的。",py:"Nà nǐ shuō zěnme bàn? Wǒ zǒng bù néng bǎ háizi bǎng qǐlái ba, tā yě bú shì gùyì de.",
   ko:"그럼 어쩌라고? 애를 묶어 둘 수도 없잖아, 일부러 그러는 것도 아니고.",
   ck:[["那你说怎么办","Nà nǐ shuō zěnme bàn"],["我总不能把孩子绑起来吧","wǒ zǒng bù néng bǎ háizi bǎng qǐlái ba"],["他也不是故意的","tā yě bú shì gùyì de"]],
   notes:[{t:"把…绑起来",p:"bǎ…bǎng qǐlái",k:"grammar",m:"~을 묶어 놓다",tip:"把자문 + 방향보어 起来. 把书收起来 / 把窗户关起来처럼 처리 결과를 말합니다."},
          {t:"不是故意的",p:"bú shì gùyì de",k:"expr",m:"일부러 그런 게 아니다",tip:"변명의 정형구입니다. 我不是故意的는 사과할 때도 그대로 씁니다."}]},
  {s:"A",zh:"我不是来吵架的，就是想商量个办法，咱们楼上楼下抬头不见低头见。",py:"Wǒ bú shì lái chǎojià de, jiùshì xiǎng shāngliang ge bànfǎ, zánmen lóushàng lóuxià táitóu bú jiàn dītóu jiàn.",
   ko:"싸우러 온 게 아니라 방법을 좀 의논하고 싶어서요. 위아래층이라 늘 마주칠 사이잖아요.",
   ck:[["我不是来吵架的","Wǒ bú shì lái chǎojià de"],["就是想商量个办法","jiùshì xiǎng shāngliang ge bànfǎ"],["咱们楼上楼下抬头不见低头见","zánmen lóushàng lóuxià táitóu bú jiàn dītóu jiàn"]],
   notes:[{t:"抬头不见低头见",p:"táitóu bú jiàn dītóu jiàn",k:"idiom",m:"고개를 들어도 숙여도 마주치는 사이다",tip:"이웃·같은 부서 사람에게 쓰는 화해의 신호입니다. '오래 볼 사이니 좋게 가자'는 뜻."},
          {t:"商量个办法",p:"shāngliang ge bànfǎ",k:"expr",m:"방법을 좀 의논하다",tip:"동사 뒤 个는 어투를 가볍게 만듭니다. 说个话 / 见个面처럼."}]},
  {s:"B",zh:"这话在理。要我说，铺个地垫应该能管点用，就是有点费钱。",py:"Zhè huà zài lǐ. Yào wǒ shuō, pū ge dìdiàn yīnggāi néng guǎn diǎn yòng, jiùshì yǒudiǎn fèi qián.",
   ko:"그 말은 맞네. 내 생각엔 매트를 깔면 좀 효과가 있을 것 같은데, 돈이 좀 든다는 게 문제지.",
   ck:[["这话在理","Zhè huà zài lǐ"],["要我说，铺个地垫应该能管点用","Yào wǒ shuō, pū ge dìdiàn yīnggāi néng guǎn diǎn yòng"],["就是有点费钱","jiùshì yǒudiǎn fèi qián"]],
   notes:[{t:"要我说",p:"yào wǒ shuō",k:"expr",m:"내 생각을 말하자면",tip:"我觉得보다 구어적이고 사람 냄새가 납니다. 문장 맨 앞에 던지세요."},
          {t:"管用",p:"guǎnyòng",k:"word",m:"효과가 있다, 먹히다",tip:"有效보다 훨씬 입말입니다. 这药挺管用 / 说了也不管用."},
          {t:"就是…",p:"jiùshì…",k:"expr",m:"다만 ~이라는 게 문제다",tip:"칭찬 뒤에 붙는 단서. 挺好的，就是贵了点."}]},
  {s:"A",zh:"费钱归费钱，可比起天天为这事儿闹别扭，还是值的。",py:"Fèi qián guī fèi qián, kě bǐqǐ tiāntiān wèi zhè shìr nào bièniu, háishi zhí de.",
   ko:"돈이 드는 건 드는 거지만, 매일 이 일로 서먹해지는 것보다야 그게 낫죠.",
   ck:[["费钱归费钱","Fèi qián guī fèi qián"],["可比起天天为这事儿闹别扭","kě bǐqǐ tiāntiān wèi zhè shìr nào bièniu"],["还是值的","háishi zhí de"]],
   notes:[{t:"A归A",p:"A guī A",k:"grammar",m:"A는 A대로 인정하되, 그것과 별개로",tip:"이 회차의 필수 골격입니다. 说归说，做归做 = 말은 말이고 행동은 행동이다."},
          {t:"闹别扭",p:"nào bièniu",k:"word",m:"틀어지다, 삐치다",tip:"싸움까지는 아니고 서먹해진 상태입니다. 两个人闹别扭好几天了."}]},
  {s:"B",zh:"说得也是。那这样，我明天就去买，晚上再让他早点写完作业。",py:"Shuō de yě shì. Nà zhèyàng, wǒ míngtiān jiù qù mǎi, wǎnshang zài ràng tā zǎodiǎn xiě wán zuòyè.",
   ko:"그 말도 맞네. 그럼 이렇게 하자, 내일 사러 갈게. 저녁엔 애한테 숙제 좀 일찍 끝내라고 하고.",
   ck:[["说得也是","Shuō de yě shì"],["那这样，我明天就去买","Nà zhèyàng, wǒ míngtiān jiù qù mǎi"],["晚上再让他早点写完作业","wǎnshang zài ràng tā zǎodiǎn xiě wán zuòyè"]],
   notes:[{t:"那这样",p:"nà zhèyàng",k:"expr",m:"그럼 이렇게 하죠",tip:"합의안을 꺼내기 직전의 신호탄입니다. 협상 대화에서 매우 자주 나옵니다."},
          {t:"写完",p:"xiě wán",k:"grammar",m:"다 쓰다 (결과보어)",tip:"完은 '끝까지'를 뜻합니다. 吃完 / 看完 / 说完. 写好와는 뉘앙스가 다릅니다."}]},
  {s:"A",zh:"那太好了。其实也不用完全没声音，过了十点小声点就行。",py:"Nà tài hǎo le. Qíshí yě búyòng wánquán méi shēngyīn, guò le shí diǎn xiǎoshēng diǎn jiù xíng.",
   ko:"정말 감사해요. 사실 완전히 조용할 필요는 없고, 열 시 넘어서만 좀 작게 해 주시면 돼요.",
   ck:[["那太好了","Nà tài hǎo le"],["其实也不用完全没声音","Qíshí yě búyòng wánquán méi shēngyīn"],["过了十点小声点就行","guò le shí diǎn xiǎoshēng diǎn jiù xíng"]],
   notes:[{t:"…就行",p:"…jiù xíng",k:"expr",m:"~해 주시기만 하면 됩니다",tip:"요구의 문턱을 낮춰 상대가 받아들이기 쉽게 만듭니다. 打个电话就行."},
          {t:"不用",p:"búyòng",k:"word",m:"~할 필요 없다",tip:"不要(하지 마라)와 다릅니다. 不用客气 / 不用等我."}]},
  {s:"B",zh:"你这么一说我心里舒服多了，我还以为你要去物业投诉呢。",py:"Nǐ zhème yì shuō wǒ xīnli shūfu duō le, wǒ hái yǐwéi nǐ yào qù wùyè tóusù ne.",
   ko:"그렇게 말해 주니 마음이 한결 편하네. 난 또 관리실에 민원 넣으러 가는 줄 알았지.",
   ck:[["你这么一说我心里舒服多了","Nǐ zhème yì shuō wǒ xīnli shūfu duō le"],["我还以为你要去物业投诉呢","wǒ hái yǐwéi nǐ yào qù wùyè tóusù ne"]],
   notes:[{t:"还以为",p:"hái yǐwéi",k:"expr",m:"~인 줄로만 알았다 (사실은 아니었다)",tip:"以为는 언제나 '틀린 짐작'입니다. 还를 붙이면 안도의 어감이 얹힙니다."},
          {t:"这么一说",p:"zhème yì shuō",k:"grammar",m:"그렇게 말하고 나니",tip:"이 골격은 대화의 분위기가 바뀌는 지점에 놓입니다. 你这么一说我就明白了."}]},
  {s:"A",zh:"投诉多难看啊，能私下说开则私下说开，何必闹到那一步。",py:"Tóusù duō nánkàn a, néng sīxià shuō kāi zé sīxià shuō kāi, hébì nào dào nà yí bù.",
   ko:"민원은 모양새가 안 좋잖아요. 조용히 풀 수 있으면 조용히 푸는 게 낫지, 굳이 거기까지 갈 필요 있나요.",
   ck:[["投诉多难看啊","Tóusù duō nánkàn a"],["能私下说开则私下说开","néng sīxià shuō kāi zé sīxià shuō kāi"],["何必闹到那一步","hébì nào dào nà yí bù"]],
   notes:[{t:"能…则…",p:"néng…zé…",k:"grammar",m:"~할 수 있으면 ~하는 게 낫다",tip:"문어에서 온 골격이라 말에 무게가 실립니다. 能省则省 = 아낄 수 있으면 아낀다."},
          {t:"何必",p:"hébì",k:"word",m:"굳이 ~할 필요가 있나",tip:"반문으로 상대를 설득합니다. 何必这么客气 / 何必跟他计较."},
          {t:"说开",p:"shuō kāi",k:"word",m:"터놓고 말해 오해를 풀다",tip:"说清楚가 사실 정리라면 说开는 감정까지 푸는 것입니다."}]},
  {s:"B",zh:"就是。有的邻居一上来就砸门，那谁受得了，火气全上来了。",py:"Jiùshì. Yǒude línjū yí shànglái jiù zá mén, nà shéi shòu de liǎo, huǒqì quán shànglái le.",
   ko:"그러게. 어떤 이웃은 다짜고짜 문을 두드리는데, 그걸 누가 견뎌. 화가 확 치밀지.",
   ck:[["就是","Jiùshì"],["有的邻居一上来就砸门","Yǒude línjū yí shànglái jiù zá mén"],["那谁受得了，火气全上来了","nà shéi shòu de liǎo, huǒqì quán shànglái le"]],
   notes:[{t:"受得了",p:"shòu de liǎo",k:"grammar",m:"견뎌 낼 수 있다",tip:"가능보어의 긍정형입니다. 부정형 受不了가 훨씬 자주 쓰이니 짝으로 외우세요."},
          {t:"火气上来了",p:"huǒqì shànglái le",k:"expr",m:"화가 치밀어 올랐다",tip:"生气보다 몸의 반응에 가깝습니다. 压住火气 = 화를 눌러 참다."}]},
  {s:"A",zh:"可不是嘛。人越吵越僵，最后连招呼都不打了，多别扭。",py:"Kě bú shì ma. Rén yuè chǎo yuè jiāng, zuìhòu lián zhāohu dōu bù dǎ le, duō bièniu.",
   ko:"그러니까요. 싸울수록 더 굳어지고, 나중엔 인사도 안 하게 되니 얼마나 불편해요.",
   ck:[["可不是嘛","Kě bú shì ma"],["人越吵越僵","Rén yuè chǎo yuè jiāng"],["最后连招呼都不打了，多别扭","zuìhòu lián zhāohu dōu bù dǎ le, duō bièniu"]],
   notes:[{t:"可不是嘛",p:"kě bú shì ma",k:"expr",m:"그러니까요, 내 말이요",tip:"강한 맞장구입니다. 是啊보다 훨씬 생생하니 통째로 익혀 두세요."},
          {t:"越…越…",p:"yuè…yuè…",k:"grammar",m:"~할수록 더 ~하다",tip:"越说越气 / 越想越不对劲. 감정이 커지는 장면에 특히 잘 붙습니다."},
          {t:"连…都…",p:"lián…dōu…",k:"grammar",m:"~조차도 ~하다",tip:"극단적인 예를 들어 강조합니다. 连饭都没吃 = 밥조차 못 먹었다."}]},
  {s:"B",zh:"对，得饶人处且饶人。以后我们注意，你也别老憋着，直接说。",py:"Duì, dé ráo rén chù qiě ráo rén. Yǐhòu wǒmen zhùyì, nǐ yě bié lǎo biē zhe, zhíjiē shuō.",
   ko:"맞아, 봐줄 수 있을 땐 봐주는 거지. 앞으로 우리도 조심할 테니, 너도 혼자 참지 말고 바로 말해.",
   ck:[["对，得饶人处且饶人","Duì, dé ráo rén chù qiě ráo rén"],["以后我们注意","Yǐhòu wǒmen zhùyì"],["你也别老憋着，直接说","nǐ yě bié lǎo biē zhe, zhíjiē shuō"]],
   notes:[{t:"得饶人处且饶人",p:"dé ráo rén chù qiě ráo rén",k:"idiom",m:"봐줄 수 있는 자리에서는 봐줘라",tip:"갈등을 끝낼 때 어른들이 쓰는 말입니다. 이 한마디로 상황이 정리됩니다."},
          {t:"别老…",p:"bié lǎo…",k:"expr",m:"자꾸 ~하지 마라",tip:"老는 '늘, 자꾸'입니다. 别老加班 / 别老看手机."},
          {t:"憋着",p:"biē zhe",k:"word",m:"참고 담아 두다",tip:"憋는 숨을 참는다는 뜻에서 왔습니다. 有话别憋着 = 할 말 있으면 담아 두지 마라."}]},
  {s:"A",zh:"那说定了。要是哪天实在忍无可忍，我就上来敲门找您喝茶。",py:"Nà shuōdìng le. Yàoshi nǎ tiān shízài rěn wú kě rěn, wǒ jiù shànglái qiāo mén zhǎo nín hē chá.",
   ko:"그럼 그렇게 하기로 해요. 언젠가 정말 못 참겠으면 올라와서 문 두드리고 차 한잔 하자고 할게요.",
   ck:[["那说定了","Nà shuōdìng le"],["要是哪天实在忍无可忍","Yàoshi nǎ tiān shízài rěn wú kě rěn"],["我就上来敲门找您喝茶","wǒ jiù shànglái qiāo mén zhǎo nín hē chá"]],
   notes:[{t:"说定了",p:"shuōdìng le",k:"expr",m:"그렇게 하기로 정했다",tip:"一言为定보다 가볍고 일상적입니다. 那就说定了！"},
          {t:"忍无可忍",p:"rěn wú kě rěn",k:"idiom",m:"참을 만큼 참아 더는 못 참다",tip:"무겁게 들리는 성어라, 여기서는 농담으로 눌러 쓰는 것이 재치입니다."}]},
  {s:"B",zh:"行，喝茶随时欢迎，敲门也随时欢迎，就别带着火气来就行。",py:"Xíng, hē chá suíshí huānyíng, qiāo mén yě suíshí huānyíng, jiù bié dài zhe huǒqì lái jiù xíng.",
   ko:"좋아, 차 마시러도 언제든 환영이고 문 두드리는 것도 언제든 환영이야. 화만 안 안고 오면 돼.",
   ck:[["行，喝茶随时欢迎","Xíng, hē chá suíshí huānyíng"],["敲门也随时欢迎","qiāo mén yě suíshí huānyíng"],["就别带着火气来就行","jiù bié dài zhe huǒqì lái jiù xíng"]],
   notes:[{t:"带着…来",p:"dài zhe…lái",k:"grammar",m:"~을 지닌 채로 오다",tip:"着는 상태의 지속입니다. 带着问题来 / 笑着说."}]},
  {s:"A",zh:"一言为定。其实今天要不是您这么通情达理，我还真不敢上来。",py:"Yì yán wéi dìng. Qíshí jīntiān yàobúshì nín zhème tōng qíng dá lǐ, wǒ hái zhēn bù gǎn shànglái.",
   ko:"약속한 겁니다. 사실 오늘 언니가 이렇게 이해심이 없었으면 저도 못 올라왔을 거예요.",
   ck:[["一言为定","Yì yán wéi dìng"],["其实今天要不是您这么通情达理","Qíshí jīntiān yàobúshì nín zhème tōng qíng dá lǐ"],["我还真不敢上来","wǒ hái zhēn bù gǎn shànglái"]],
   notes:[{t:"要不是…",p:"yàobúshì…",k:"grammar",m:"~이 아니었더라면",tip:"가정법입니다. 뒤에는 보통 就나 还真이 옵니다. 要不是你提醒，我就忘了."},
          {t:"通情达理",p:"tōng qíng dá lǐ",k:"idiom",m:"사리에 밝고 이해심이 있다",tip:"상대를 높이는 칭찬 성어입니다. 대화를 좋게 닫을 때 씁니다."}]},
  {s:"B",zh:"客气什么，远亲不如近邻，往后有事儿你尽管言语一声。",py:"Kèqi shénme, yuǎnqīn bùrú jìnlín, wǎnghòu yǒu shìr nǐ jǐnguǎn yányu yì shēng.",
   ko:"뭘 그런 걸로. 먼 친척보다 가까운 이웃이라잖아. 앞으로 무슨 일 있으면 얼마든지 말해.",
   ck:[["客气什么","Kèqi shénme"],["远亲不如近邻","yuǎnqīn bùrú jìnlín"],["往后有事儿你尽管言语一声","wǎnghòu yǒu shìr nǐ jǐnguǎn yányu yì shēng"]],
   notes:[{t:"远亲不如近邻",p:"yuǎnqīn bùrú jìnlín",k:"idiom",m:"먼 친척보다 가까운 이웃이 낫다",tip:"이웃 사이를 정리하는 대표 속담입니다. 마무리 인사로 자주 쓰입니다."},
          {t:"尽管",p:"jǐnguǎn",k:"word",m:"얼마든지, 마음 놓고",tip:"여기서는 '비록'이 아니라 '개의치 말고'입니다. 有问题尽管问."},
          {t:"言语一声",p:"yányu yì shēng",k:"expr",m:"한마디 말해 주다, 알려 주다",tip:"북방 구어입니다. 说一声과 같은 뜻인데 훨씬 정겹게 들립니다."}]}
 ],
 keys:[
  {zh:"不是A，就是B",py:"bú shì A, jiùshì B",ko:"A가 아니라 다만 B다",
   ex:"不是不想帮，就是这两天实在抽不开身。",exPy:"Bú shì bù xiǎng bāng, jiùshì zhè liǎng tiān shízài chōu bu kāi shēn.",exKo:"돕기 싫은 게 아니라 요 며칠 정말 시간이 안 나서요."},
  {zh:"总不能…吧",py:"zǒng bù néng…ba",ko:"설마 ~할 수는 없잖아요",
   ex:"总不能让客户一直等着吧。",exPy:"Zǒng bù néng ràng kèhù yìzhí děng zhe ba.",exKo:"설마 고객을 계속 기다리게 할 수는 없잖아요."},
  {zh:"A归A",py:"A guī A",ko:"A는 A대로 인정하되, 그것과 별개로",
   ex:"生气归生气，活儿还得干。",exPy:"Shēngqì guī shēngqì, huór hái děi gàn.",exKo:"화나는 건 화나는 거고, 일은 해야죠."},
  {zh:"能…则…",py:"néng…zé…",ko:"~할 수 있으면 ~하는 게 낫다",
   ex:"能不麻烦别人则不麻烦别人。",exPy:"Néng bù máfan biéren zé bù máfan biéren.",exKo:"남을 안 귀찮게 할 수 있으면 안 귀찮게 하는 게 낫죠."},
  {zh:"可不是嘛",py:"kě bú shì ma",ko:"그러니까요, 내 말이요",
   ex:"可不是嘛，我早就想说了。",exPy:"Kě bú shì ma, wǒ zǎojiù xiǎng shuō le.",exKo:"그러니까요, 저도 진작부터 말하고 싶었어요."},
  {zh:"越…越…",py:"yuè…yuè…",ko:"~할수록 더 ~하다",
   ex:"这事越拖越难办。",exPy:"Zhè shì yuè tuō yuè nán bàn.",exKo:"이 일은 미룰수록 더 처리하기 어려워져요."},
  {zh:"还以为",py:"hái yǐwéi",ko:"~인 줄로만 알았다",
   ex:"我还以为你today不来了呢。",exPy:"Wǒ hái yǐwéi nǐ jīntiān bù lái le ne.",exKo:"난 또 오늘 안 오시는 줄 알았어요."},
  {zh:"要不是…，我就…",py:"yàobúshì…, wǒ jiù…",ko:"~이 아니었다면 나는 ~했을 것이다",
   ex:"要不是你提醒，我就把这事忘了。",exPy:"Yàobúshì nǐ tíxǐng, wǒ jiù bǎ zhè shì wàng le.",exKo:"당신이 일러 주지 않았으면 이 일을 잊을 뻔했어요."}
 ],
 out:[
  {q:"위층 소음 때문에 올라갔습니다. 비난으로 들리지 않게 첫 두 문장을 말해 보세요.",hint:"实在不好意思 / 不是嫌，就是… / 实在睡不着"},
  {q:"상대가 「애가 어려서 어쩔 수 없다」고 합니다. 인정하면서도 요구는 남겨 보세요.",hint:"我理解，将心比心 / 总不能…吧 / 商量个办法"},
  {q:"합의가 된 뒤, 관계를 좋게 닫는 마지막 두 마디를 해 보세요.",hint:"说定了 / 通情达理 / 远亲不如近邻"}
 ]
},
{
 id:"c2d2", day:9, cat:"경조사·인정", level:"HSK 5~6",
 title:"随礼", titlePy:"suílǐ", titleKo:"축의금 — 액수와 체면 사이",
 names:{A:"晓雯 (후배 동료)", B:"老陈 (선배 동료)"},
 brief:[
  "중국에서 <b>随礼(suílǐ)</b>, 즉 부조는 액수 문제로 보이지만 실제로는 <b>관계의 등급을 숫자로 표시하는 일</b>입니다. 그래서 얼마를 낼지 정하는 것이 곧 '우리가 어느 정도 사이인가'를 정하는 것이 됩니다.",
  "판단의 기본 원칙은 <b>礼尚往来(오간 만큼 돌려준다)</b>입니다. 상대가 내게 얼마를 했는지가 첫 번째 기준이고, 그런 이력이 없으면 <b>随大流(대세를 따르다)</b>로 주변 동료들의 액수에 맞춥니다.",
  "여기서 중국인들이 경계하는 것이 <b>打肿脸充胖子</b>입니다. 얼굴을 부어오르게 때려 뚱뚱한 척한다는 뜻으로, 형편에 안 맞는 허세를 가리킵니다. 형편이 어려우면 액수 대신 <b>몸으로 때우는(人到礼到)</b> 방법이 있습니다.",
  "이 회차의 구어 골격은 <b>说A也不A · 越…越… · 话是这么说 · 非得…才… · 不在A，在B</b>입니다. 특히 「话是这么说，可…」는 상대 말을 받아 반박으로 넘어가는 다리라서, 회의에서도 그대로 쓸 수 있습니다."
 ],
 vocab:[
  {w:"份子钱",p:"fènziqián",m:"축의금, 부조금",lv:"구어"},
  {w:"随礼",p:"suílǐ",m:"부조하다, 축의금을 내다",lv:"구어"},
  {w:"礼尚往来",p:"lǐ shàng wǎng lái",m:"오고 가는 것이 예다 (성어)",lv:"성어"},
  {w:"随大流",p:"suí dàliú",m:"대세를 따르다",lv:"구어"},
  {w:"打听",p:"dǎting",m:"수소문하다, 알아보다",lv:"HSK5"},
  {w:"没底",p:"méi dǐ",m:"확신이 서지 않다",lv:"구어"},
  {w:"手头紧",p:"shǒutóu jǐn",m:"주머니 사정이 빠듯하다",lv:"구어"},
  {w:"打肿脸充胖子",p:"dǎ zhǒng liǎn chōng pàngzi",m:"형편에 안 맞는 허세를 부리다",lv:"성어"},
  {w:"攀比",p:"pānbǐ",m:"서로 견주며 경쟁하다",lv:"HSK6"},
  {w:"掏心窝子",p:"tāo xīnwōzi",m:"속마음을 다 털어놓다",lv:"구어"},
  {w:"反倒",p:"fǎndào",m:"오히려, 도리어",lv:"HSK6"},
  {w:"本末倒置",p:"běn mò dào zhì",m:"본말이 뒤바뀌다 (성어)",lv:"성어"}
 ],
 lines:[
  {s:"A",zh:"陈哥，小王下个月结婚，这份子钱我实在拿不准该给多少。",py:"Chén gē, Xiǎo Wáng xià ge yuè jiéhūn, zhè fènziqián wǒ shízài ná bu zhǔn gāi gěi duōshao.",
   ko:"천 형, 샤오왕이 다음 달에 결혼하는데 축의금을 얼마나 해야 할지 도무지 감이 안 잡혀요.",
   ck:[["陈哥，小王下个月结婚","Chén gē, Xiǎo Wáng xià ge yuè jiéhūn"],["这份子钱我实在拿不准该给多少","zhè fènziqián wǒ shízài ná bu zhǔn gāi gěi duōshao"]],
   notes:[{t:"拿不准",p:"ná bu zhǔn",k:"grammar",m:"확실히 판단하지 못하다",tip:"가능보어. 拿得准 / 拿不准. 我拿不准他的意思처럼 씁니다."},
          {t:"份子钱",p:"fènziqián",m:"축의금",p2:"",k:"word",tip:"红包가 봉투 자체라면 份子钱은 그 안에 넣는 돈, 즉 부조 액수를 말합니다."}]},
  {s:"B",zh:"这事儿说难也不难，你就看他当初给你随了多少，礼尚往来嘛。",py:"Zhè shìr shuō nán yě bù nán, nǐ jiù kàn tā dāngchū gěi nǐ suí le duōshao, lǐ shàng wǎng lái ma.",
   ko:"이건 어렵다면 어렵고 아니라면 아니야. 그 친구가 예전에 너한테 얼마 했는지 보면 되지, 오간 만큼 하는 거니까.",
   ck:[["这事儿说难也不难","Zhè shìr shuō nán yě bù nán"],["你就看他当初给你随了多少","nǐ jiù kàn tā dāngchū gěi nǐ suí le duōshao"],["礼尚往来嘛","lǐ shàng wǎng lái ma"]],
   notes:[{t:"说A也不A",p:"shuō A yě bù A",k:"grammar",m:"A라고 하면 A이고 아니라면 아니다",tip:"판단을 유보하며 여지를 두는 골격입니다. 说贵也不贵 / 说远也不远."},
          {t:"礼尚往来",p:"lǐ shàng wǎng lái",k:"idiom",m:"받았으면 돌려주는 것이 예다",tip:"부조·선물·접대의 기본 원리입니다. 이 한마디면 액수 논쟁이 정리됩니다."}]},
  {s:"A",zh:"问题就在这儿，我结婚那会儿他还没入职，压根儿没随过。",py:"Wèntí jiù zài zhèr, wǒ jiéhūn nà huìr tā hái méi rùzhí, yāgēnr méi suí guo.",
   ko:"문제가 바로 거기예요. 제가 결혼할 땐 그 친구가 입사 전이라 아예 부조를 한 적이 없거든요.",
   ck:[["问题就在这儿","Wèntí jiù zài zhèr"],["我结婚那会儿他还没入职","wǒ jiéhūn nà huìr tā hái méi rùzhí"],["压根儿没随过","yāgēnr méi suí guo"]],
   notes:[{t:"那会儿",p:"nà huìr",k:"word",m:"그때, 그 무렵",tip:"那时候의 구어형입니다. 这会儿(지금) / 那会儿(그때)로 짝지어 외우세요."},
          {t:"压根儿",p:"yāgēnr",k:"word",m:"아예, 애당초",tip:"부정문에서만 씁니다. 我压根儿不知道 = 난 아예 몰랐다."}]},
  {s:"B",zh:"那就随大流，跟同事们打听打听，别人给多少你就给多少。",py:"Nà jiù suí dàliú, gēn tóngshìmen dǎting dǎting, biéren gěi duōshao nǐ jiù gěi duōshao.",
   ko:"그럼 대세를 따라야지. 동료들한테 좀 물어보고, 남들 하는 만큼 하면 돼.",
   ck:[["那就随大流","Nà jiù suí dàliú"],["跟同事们打听打听","gēn tóngshìmen dǎting dǎting"],["别人给多少你就给多少","biéren gěi duōshao nǐ jiù gěi duōshao"]],
   notes:[{t:"随大流",p:"suí dàliú",k:"expr",m:"대세를 따르다",tip:"부정적일 때도 중립일 때도 씁니다. 别老随大流 = 남 따라만 하지 마라."},
          {t:"打听打听",p:"dǎting dǎting",k:"grammar",m:"좀 알아보다 (동사 중첩)",tip:"2음절 동사는 ABAB로 겹칩니다. 商量商量 / 研究研究. 어투가 가벼워집니다."},
          {t:"A多少就B多少",p:"A duōshao jiù B duōshao",k:"grammar",m:"A만큼 그대로 B하다",tip:"의문사를 두 번 써서 '그대로'를 만듭니다. 你说什么我做什么."}]},
  {s:"A",zh:"打听过了，有人说五百，有人说八百，越问我越没底。",py:"Dǎting guo le, yǒu rén shuō wǔbǎi, yǒu rén shuō bābǎi, yuè wèn wǒ yuè méi dǐ.",
   ko:"물어봤어요. 어떤 사람은 오백, 어떤 사람은 팔백이라니, 물어볼수록 더 감이 안 잡혀요.",
   ck:[["打听过了","Dǎting guo le"],["有人说五百，有人说八百","yǒu rén shuō wǔbǎi, yǒu rén shuō bābǎi"],["越问我越没底","yuè wèn wǒ yuè méi dǐ"]],
   notes:[{t:"没底",p:"méi dǐ",k:"expr",m:"확신이 안 서다, 자신이 없다",tip:"心里没底가 완전한 형태입니다. 반대는 心里有底."}]},
  {s:"B",zh:"那你就往中间靠，给个六百六，图个吉利，谁也说不出什么。",py:"Nà nǐ jiù wǎng zhōngjiān kào, gěi ge liùbǎiliù, tú ge jílì, shéi yě shuō bu chū shénme.",
   ko:"그럼 중간으로 가. 육백육십 정도 하면 숫자도 좋고, 누구도 뭐라 못 해.",
   ck:[["那你就往中间靠","Nà nǐ jiù wǎng zhōngjiān kào"],["给个六百六，图个吉利","gěi ge liùbǎiliù, tú ge jílì"],["谁也说不出什么","shéi yě shuō bu chū shénme"]],
   notes:[{t:"图个…",p:"tú ge…",k:"expr",m:"~을 노리다, ~을 바라서 하다",tip:"图个吉利 / 图个方便 / 图个安心. 목적을 가볍게 말하는 골격입니다."},
          {t:"说不出",p:"shuō bu chū",k:"grammar",m:"(말이) 나오지 않다, 뭐라 할 수 없다",tip:"가능보어. 谁也说不出什么 = 아무도 트집 잡을 수 없다."},
          {t:"六百六",p:"liùbǎiliù",k:"culture",m:"660위안",tip:"6은 顺(순조로움)을 뜻해 길한 숫자로 칩니다. 8은 发(발전), 4는 死와 소리가 닮아 피합니다."}]},
  {s:"A",zh:"六百六对我来说不算少，这个月房租刚交完，手头有点紧。",py:"Liùbǎiliù duì wǒ lái shuō bú suàn shǎo, zhège yuè fángzū gāng jiāo wán, shǒutóu yǒudiǎn jǐn.",
   ko:"육백육십은 저한테 적은 돈이 아니에요. 이번 달 월세를 막 냈더니 사정이 좀 빠듯하거든요.",
   ck:[["六百六对我来说不算少","Liùbǎiliù duì wǒ lái shuō bú suàn shǎo"],["这个月房租刚交完","zhège yuè fángzū gāng jiāo wán"],["手头有点紧","shǒutóu yǒudiǎn jǐn"]],
   notes:[{t:"对我来说",p:"duì wǒ lái shuō",k:"expr",m:"나에게는, 내 입장에서는",tip:"의견을 상대화해 부드럽게 만듭니다. 对我来说这不是钱的问题."},
          {t:"手头紧",p:"shǒutóu jǐn",k:"expr",m:"주머니 사정이 빠듯하다",tip:"没钱이라고 직접 말하지 않는 완곡어입니다. 최근에 手头松点了처럼도 씁니다."}]},
  {s:"B",zh:"手头紧就别硬撑，打肿脸充胖子最没意思，人家又不是不知道。",py:"Shǒutóu jǐn jiù bié yìng chēng, dǎ zhǒng liǎn chōng pàngzi zuì méi yìsi, rénjia yòu bú shì bù zhīdào.",
   ko:"빠듯하면 무리하지 마. 형편에 안 맞게 허세 부리는 게 제일 부질없어. 상대도 모르는 것도 아니고.",
   ck:[["手头紧就别硬撑","Shǒutóu jǐn jiù bié yìng chēng"],["打肿脸充胖子最没意思","dǎ zhǒng liǎn chōng pàngzi zuì méi yìsi"],["人家又不是不知道","rénjia yòu bú shì bù zhīdào"]],
   notes:[{t:"打肿脸充胖子",p:"dǎ zhǒng liǎn chōng pàngzi",k:"idiom",m:"형편에 안 맞는 허세를 부리다",tip:"직역은 '얼굴을 부어오르게 때려 뚱보인 척하다'. 아주 자주 쓰는 성어입니다."},
          {t:"硬撑",p:"yìng chēng",k:"word",m:"무리해서 버티다",tip:"몸에도 돈에도 씁니다. 别硬撑，累了就休息."},
          {t:"又不是…",p:"yòu bú shì…",k:"grammar",m:"~인 것도 아닌데",tip:"반박에 쓰는 골격입니다. 我又不是没做过 = 내가 안 해 본 것도 아닌데."}]},
  {s:"A",zh:"话是这么说，可给少了怕人家心里有想法，以后不好相处。",py:"Huà shì zhème shuō, kě gěi shǎo le pà rénjia xīnli yǒu xiǎngfa, yǐhòu bù hǎo xiāngchǔ.",
   ko:"말은 그렇지만, 적게 하면 상대가 서운해할까 봐요. 그럼 앞으로 지내기가 껄끄럽잖아요.",
   ck:[["话是这么说","Huà shì zhème shuō"],["可给少了怕人家心里有想法","kě gěi shǎo le pà rénjia xīnli yǒu xiǎngfa"],["以后不好相处","yǐhòu bù hǎo xiāngchǔ"]],
   notes:[{t:"话是这么说",p:"huà shì zhème shuō",k:"expr",m:"말은 그렇지만",tip:"说是这么说와 같은 계열입니다. 인정하고 반박으로 넘어가는 다리."},
          {t:"心里有想法",p:"xīnli yǒu xiǎngfa",k:"expr",m:"속으로 서운해하다, 앙금이 남다",tip:"직접 不高兴이라 하지 않는 완곡어입니다. 중국어 화법의 핵심 감각입니다."}]},
  {s:"B",zh:"你要真在乎这个，那就人到礼到，红包薄一点，多去帮帮忙。",py:"Nǐ yào zhēn zàihu zhège, nà jiù rén dào lǐ dào, hóngbāo báo yìdiǎn, duō qù bāngbang máng.",
   ko:"정말 그게 신경 쓰이면, 사람이 가면 성의도 간 거야. 봉투는 좀 얇게 하고 가서 많이 도와 줘.",
   ck:[["你要真在乎这个","Nǐ yào zhēn zàihu zhège"],["那就人到礼到","nà jiù rén dào lǐ dào"],["红包薄一点","hóngbāo báo yìdiǎn"],["多去帮帮忙","duō qù bāngbang máng"]],
   notes:[{t:"人到礼到",p:"rén dào lǐ dào",k:"expr",m:"사람이 가면 성의도 간 것이다",tip:"몸으로 때우는 것도 부조라는 뜻입니다. 형편이 어려울 때의 정답입니다."},
          {t:"要…",p:"yào…",k:"grammar",m:"만약 ~한다면",tip:"如果의 구어 축약입니다. 你要不去，我也不去."}]},
  {s:"A",zh:"这个主意好，我提前一天过去帮他们布置，也算尽了心。",py:"Zhège zhǔyi hǎo, wǒ tíqián yì tiān guòqù bāng tāmen bùzhì, yě suàn jìn le xīn.",
   ko:"그거 좋은 생각이네요. 하루 전에 가서 준비를 도와주면 그것도 성의를 다한 거죠.",
   ck:[["这个主意好","Zhège zhǔyi hǎo"],["我提前一天过去帮他们布置","wǒ tíqián yì tiān guòqù bāng tāmen bùzhì"],["也算尽了心","yě suàn jìn le xīn"]],
   notes:[{t:"也算…",p:"yě suàn…",k:"expr",m:"그것도 ~인 셈이다",tip:"완벽하진 않아도 인정할 만하다는 뉘앙스입니다. 也算帮了忙."},
          {t:"尽心",p:"jìn xīn",k:"word",m:"마음을 다하다",tip:"尽了心 / 尽心尽力. 결과보다 정성을 말할 때 씁니다."}]},
  {s:"B",zh:"就是这个理儿。人情这东西，不在钱多钱少，在心意到没到。",py:"Jiùshì zhège lǐr. Rénqíng zhè dōngxi, bú zài qián duō qián shǎo, zài xīnyì dào méi dào.",
   ko:"바로 그 이치야. 인정이란 건 돈이 많고 적음에 있는 게 아니라 마음이 닿았느냐에 있는 거지.",
   ck:[["就是这个理儿","Jiùshì zhège lǐr"],["人情这东西，不在钱多钱少","Rénqíng zhè dōngxi, bú zài qián duō qián shǎo"],["在心意到没到","zài xīnyì dào méi dào"]],
   notes:[{t:"不在A，在B",p:"bú zài A, zài B",k:"grammar",m:"A에 있는 게 아니라 B에 있다",tip:"핵심을 옮겨 놓는 골격입니다. 不在多，在精 = 많음이 아니라 정밀함에 있다."},
          {t:"这个理儿",p:"zhège lǐr",k:"word",m:"그 이치, 그 도리",tip:"就是这个理儿는 강한 동의입니다. 你说的在理와 짝으로 쓰세요."}]},
  {s:"A",zh:"说是这么说，可现在随礼越来越高，不跟上就显得小气。",py:"Shuō shì zhème shuō, kě xiànzài suílǐ yuèláiyuè gāo, bù gēn shàng jiù xiǎnde xiǎoqì.",
   ko:"말은 그렇지만 요즘은 부조 액수가 점점 높아져서, 따라가지 않으면 인색해 보이잖아요.",
   ck:[["说是这么说","Shuō shì zhème shuō"],["可现在随礼越来越高","kě xiànzài suílǐ yuèláiyuè gāo"],["不跟上就显得小气","bù gēn shàng jiù xiǎnde xiǎoqì"]],
   notes:[{t:"越来越…",p:"yuèláiyuè…",k:"grammar",m:"점점 더 ~해지다",tip:"越…越…와 구분하세요. 越来越는 시간에 따른 변화입니다."},
          {t:"显得",p:"xiǎnde",k:"word",m:"~하게 보이다",tip:"看起来보다 문어적입니다. 显得小气 / 显得年轻."}]},
  {s:"B",zh:"那是攀比闹的。你要是每次都往上加，最后谁也扛不住。",py:"Nà shì pānbǐ nào de. Nǐ yàoshi měi cì dōu wǎng shàng jiā, zuìhòu shéi yě káng bu zhù.",
   ko:"그건 서로 견주다 생긴 일이야. 매번 올려 가면 결국 아무도 못 버텨.",
   ck:[["那是攀比闹的","Nà shì pānbǐ nào de"],["你要是每次都往上加","Nǐ yàoshi měi cì dōu wǎng shàng jiā"],["最后谁也扛不住","zuìhòu shéi yě káng bu zhù"]],
   notes:[{t:"…闹的",p:"…nào de",k:"expr",m:"~ 때문에 생긴 일이다",tip:"원인을 탓하는 구어입니다. 都是你闹的 = 전부 네가 벌인 일이다."},
          {t:"扛不住",p:"káng bu zhù",k:"grammar",m:"감당하지 못하다, 버티지 못하다",tip:"가능보어. 몸도 돈도 압박도 목적어가 됩니다. 我快扛不住了."}]},
  {s:"A",zh:"也是。非得把自己逼到那份上，才叫懂事，那也太累了。",py:"Yě shì. Fēiděi bǎ zìjǐ bī dào nà fèn shàng, cái jiào dǒngshì, nà yě tài lèi le.",
   ko:"그러네요. 자기를 그 지경까지 몰아붙여야 철든 거라면, 그건 너무 피곤하죠.",
   ck:[["也是","Yě shì"],["非得把自己逼到那份上，才叫懂事","Fēiděi bǎ zìjǐ bī dào nà fèn shàng, cái jiào dǒngshì"],["那也太累了","nà yě tài lèi le"]],
   notes:[{t:"非得…才…",p:"fēiděi…cái…",k:"grammar",m:"반드시 ~해야만 비로소 ~이다",tip:"이 회차의 필수 골격입니다. 非得我说才行吗？"},
          {t:"把自己逼到那份上",p:"bǎ zìjǐ bī dào nà fèn shàng",k:"expr",m:"자신을 그 지경까지 몰아붙이다",tip:"到那份上은 '그 정도 상황까지'입니다. 把자문과 함께 통째로 익히세요."}]},
  {s:"B",zh:"对了，你们关系到底算近还是一般？这个才是关键。",py:"Duì le, nǐmen guānxi dàodǐ suàn jìn háishi yìbān? Zhège cái shì guānjiàn.",
   ko:"참, 너희 사이가 도대체 가까운 편이야, 그냥 그런 편이야? 그게 핵심이지.",
   ck:[["对了","Duì le"],["你们关系到底算近还是一般","nǐmen guānxi dàodǐ suàn jìn háishi yìbān"],["这个才是关键","Zhège cái shì guānjiàn"]],
   notes:[{t:"到底",p:"dàodǐ",k:"word",m:"도대체, 결국",tip:"의문문에서 답답함을 실어 줍니다. 你到底想说什么？"},
          {t:"才是",p:"cái shì",k:"grammar",m:"바로 ~이야말로",tip:"앞의 논의를 뒤집고 핵심을 세울 때 씁니다. 这才是重点."}]},
  {s:"A",zh:"一个部门的，平时一起吃饭，但也没到掏心窝子的程度。",py:"Yí ge bùmén de, píngshí yìqǐ chīfàn, dàn yě méi dào tāo xīnwōzi de chéngdù.",
   ko:"같은 부서라 평소에 같이 밥은 먹는데, 속을 다 터놓을 정도는 아니에요.",
   ck:[["一个部门的，平时一起吃饭","Yí ge bùmén de, píngshí yìqǐ chīfàn"],["但也没到掏心窝子的程度","dàn yě méi dào tāo xīnwōzi de chéngdù"]],
   notes:[{t:"掏心窝子",p:"tāo xīnwōzi",k:"expr",m:"속마음을 다 털어놓다",tip:"掏心窝子的话 = 진심에서 나온 말. 아주 친한 사이에만 씁니다."},
          {t:"没到…的程度",p:"méi dào…de chéngdù",k:"grammar",m:"~할 정도까지는 아니다",tip:"관계나 상태의 정도를 재는 표현입니다. 没到吵架的程度."}]},
  {s:"B",zh:"那就按同事的标准来，六百顶天了，多了反倒让人不自在。",py:"Nà jiù àn tóngshì de biāozhǔn lái, liùbǎi dǐngtiān le, duō le fǎndào ràng rén bú zìzai.",
   ko:"그럼 동료 기준으로 하면 돼. 육백이면 최대치야. 더 하면 오히려 상대가 부담스러워해.",
   ck:[["那就按同事的标准来","Nà jiù àn tóngshì de biāozhǔn lái"],["六百顶天了","liùbǎi dǐngtiān le"],["多了反倒让人不自在","duō le fǎndào ràng rén bú zìzai"]],
   notes:[{t:"顶天了",p:"dǐngtiān le",k:"expr",m:"많아 봐야, 최대로 잡아도",tip:"最多也就과 같은 뜻인데 훨씬 구어적입니다. 一小时顶天了."},
          {t:"反倒",p:"fǎndào",k:"word",m:"오히려, 도리어",tip:"예상과 반대의 결과를 말합니다. 帮忙反倒添乱."}]},
  {s:"A",zh:"那我就六百，再加一份小礼物，心意也到了，也不至于肉疼。",py:"Nà wǒ jiù liùbǎi, zài jiā yí fèn xiǎo lǐwù, xīnyì yě dào le, yě bú zhìyú ròuténg.",
   ko:"그럼 육백에 작은 선물 하나 더할게요. 마음도 전해지고, 그렇게 속 쓰리지도 않고요.",
   ck:[["那我就六百","Nà wǒ jiù liùbǎi"],["再加一份小礼物","zài jiā yí fèn xiǎo lǐwù"],["心意也到了，也不至于肉疼","xīnyì yě dào le, yě bú zhìyú ròuténg"]],
   notes:[{t:"不至于",p:"bú zhìyú",k:"word",m:"~할 정도까지는 아니다",tip:"단독으로도 씁니다. 不至于吧！= 설마 그 정도겠어?"},
          {t:"肉疼",p:"ròuténg",k:"word",m:"(돈이 나가서) 속이 쓰리다",tip:"心疼과 비슷하나 돈에 더 자주 씁니다. 花这么多钱真肉疼."}]},
  {s:"B",zh:"这就对了。记住，随礼是维持关系，不是买关系，别本末倒置。",py:"Zhè jiù duì le. Jìzhù, suílǐ shì wéichí guānxi, bú shì mǎi guānxi, bié běn mò dào zhì.",
   ko:"그래야지. 기억해, 부조는 관계를 유지하는 거지 사는 게 아니야. 본말이 뒤바뀌면 안 돼.",
   ck:[["这就对了","Zhè jiù duì le"],["记住，随礼是维持关系，不是买关系","Jìzhù, suílǐ shì wéichí guānxi, bú shì mǎi guānxi"],["别本末倒置","bié běn mò dào zhì"]],
   notes:[{t:"这就对了",p:"zhè jiù duì le",k:"expr",m:"그래야지, 그게 맞다",tip:"상대가 옳은 결론에 이르렀을 때의 칭찬입니다. 손윗사람이 자주 씁니다."},
          {t:"本末倒置",p:"běn mò dào zhì",k:"idiom",m:"본말이 뒤바뀌다",tip:"수단이 목적을 잡아먹었을 때 씁니다. 회의에서도 그대로 쓸 수 있습니다."}]}
 ],
 keys:[
  {zh:"礼尚往来",py:"lǐ shàng wǎng lái",ko:"받았으면 돌려주는 것이 예다",
   ex:"礼尚往来，上次他帮了我，这次我得还。",exPy:"Lǐ shàng wǎng lái, shàng cì tā bāng le wǒ, zhè cì wǒ děi huán.",exKo:"오간 만큼 하는 거죠. 지난번에 도와줬으니 이번엔 제가 갚아야죠."},
  {zh:"说A也不A",py:"shuō A yě bù A",ko:"A라면 A이고 아니라면 아니다",
   ex:"这活儿说累也不累，就是费时间。",exPy:"Zhè huór shuō lèi yě bú lèi, jiùshì fèi shíjiān.",exKo:"이 일은 힘들다면 힘들고 아니라면 아닌데, 시간이 많이 들어요."},
  {zh:"话是这么说，可…",py:"huà shì zhème shuō, kě…",ko:"말은 그렇지만, 다만",
   ex:"话是这么说，可客户不一定这么想。",exPy:"Huà shì zhème shuō, kě kèhù bù yídìng zhème xiǎng.",exKo:"말은 그렇지만 고객이 꼭 그렇게 생각하진 않을 거예요."},
  {zh:"打肿脸充胖子",py:"dǎ zhǒng liǎn chōng pàngzi",ko:"형편에 안 맞는 허세를 부리다",
   ex:"没钱就说没钱，别打肿脸充胖子。",exPy:"Méi qián jiù shuō méi qián, bié dǎ zhǒng liǎn chōng pàngzi.",exKo:"돈 없으면 없다고 해요, 괜히 허세 부리지 말고."},
  {zh:"不在A，在B",py:"bú zài A, zài B",ko:"A에 있는 게 아니라 B에 있다",
   ex:"问题不在价格，在交货期。",exPy:"Wèntí bú zài jiàgé, zài jiāohuòqī.",exKo:"문제는 가격이 아니라 납기에 있습니다."},
  {zh:"非得…才…",py:"fēiděi…cái…",ko:"반드시 ~해야만 비로소 ~이다",
   ex:"非得出了事才想起来检查。",exPy:"Fēiděi chū le shì cái xiǎng qǐlái jiǎnchá.",exKo:"꼭 사고가 나야만 점검할 생각을 하네요."},
  {zh:"顶天了",py:"dǐngtiān le",ko:"많아 봐야, 최대로 잡아도",
   ex:"这活儿两天顶天了。",exPy:"Zhè huór liǎng tiān dǐngtiān le.",exKo:"이 일은 많아 봐야 이틀이면 됩니다."},
  {zh:"本末倒置",py:"běn mò dào zhì",ko:"본말이 뒤바뀌다",
   ex:"为了做报告耽误了正事，这就本末倒置了。",exPy:"Wèile zuò bàogào dānwu le zhèngshì, zhè jiù běn mò dào zhì le.",exKo:"보고서 만드느라 정작 할 일을 미뤘으니, 본말이 뒤바뀐 겁니다."}
 ],
 out:[
  {q:"동료 결혼식 축의금을 얼마 할지 선배에게 상의해 보세요. 형편이 빠듯하다는 말도 넣어서.",hint:"拿不准 / 手头有点紧 / 越问我越没底"},
  {q:"상대가 「남들 하는 만큼 해」라고 합니다. 인정하면서도 걱정을 꺼내 보세요.",hint:"话是这么说 / 心里有想法 / 显得小气"},
  {q:"후배가 무리해서 큰 액수를 내려 합니다. 말려 보세요.",hint:"别硬撑 / 打肿脸充胖子 / 人到礼到"}
 ]
},
{
 id:"c2d3", day:10, cat:"주거·계약", level:"HSK 5~6",
 title:"押金", titlePy:"yājīn", titleKo:"보증금 돌려받기 — 문서로 따지고 관계로 닫기",
 names:{A:"小周 (세입자)", B:"王姐 (집주인)"},
 brief:[
  "보증금 반환은 중국에서도 세입자가 가장 자주 손해를 보는 자리입니다. 집주인은 대개 <b>먼저 흠을 잡고</b> 시작하기 때문에, 대응의 순서는 감정이 아니라 <b>증거 → 기준 → 절충</b>이어야 합니다.",
  "첫 번째 무기가 <b>白纸黑字(백지에 검은 글씨)</b>, 즉 계약서입니다. 여기에 입주 전 사진이 붙으면 「원래 있던 하자」와 「내가 낸 하자」가 갈립니다. 이것만 갖춰도 대화의 절반은 끝납니다.",
  "두 번째가 <b>正常磨损(정상 마모)</b>이라는 개념입니다. 사람이 살면 닳는 것이 당연하므로 그 부분까지 물어 주지는 않는다는 것이 상식적인 기준입니다. 여기서 <b>A归A</b> 골격이 위력을 발휘합니다.",
  "다만 끝을 이기는 것으로 닫으면 안 됩니다. 중국에서는 <b>各让一步(서로 한 발씩 양보)</b>로 마무리하고 <b>有言在先(미리 말해 두다)</b>으로 뒷말을 막습니다. 돈은 받되 사람은 남기는 것이 이 회차의 기술입니다."
 ],
 vocab:[
  {w:"押金",p:"yājīn",m:"보증금",lv:"HSK5"},
  {w:"白纸黑字",p:"bái zhǐ hēi zì",m:"문서에 분명히 적혀 있다 (성어)",lv:"성어"},
  {w:"磨损",p:"mósǔn",m:"마모, 닳아 해짐",lv:"HSK6"},
  {w:"划痕",p:"huáhén",m:"긁힌 자국",lv:"구어"},
  {w:"扣",p:"kòu",m:"(금액을) 공제하다, 떼다",lv:"HSK5"},
  {w:"结清",p:"jiéqīng",m:"정산해서 깨끗이 마치다",lv:"구어"},
  {w:"各让一步",p:"gè ràng yí bù",m:"서로 한 발씩 양보하다",lv:"구어"},
  {w:"话说回来",p:"huà shuō huí lái",m:"그건 그렇고, 다시 말하자면",lv:"구어"},
  {w:"省心",p:"shěngxīn",m:"신경 쓸 일이 없어 편하다",lv:"HSK6"},
  {w:"出头",p:"chūtóu",m:"(수량이) 남짓, 조금 넘음",lv:"구어"},
  {w:"扯皮",p:"chěpí",m:"옥신각신하며 책임을 미루다",lv:"구어"},
  {w:"有言在先",p:"yǒu yán zài xiān",m:"미리 말해 두다 (성어)",lv:"성어"}
 ],
 lines:[
  {s:"A",zh:"王姐，房子我今天就搬空了，押金什么时候能退给我？",py:"Wáng jiě, fángzi wǒ jīntiān jiù bān kōng le, yājīn shénme shíhou néng tuì gěi wǒ?",
   ko:"왕 언니, 집은 오늘 다 비웠어요. 보증금은 언제 돌려받을 수 있을까요?",
   ck:[["王姐，房子我今天就搬空了","Wáng jiě, fángzi wǒ jīntiān jiù bān kōng le"],["押金什么时候能退给我","yājīn shénme shíhou néng tuì gěi wǒ"]],
   notes:[{t:"搬空",p:"bān kōng",k:"grammar",m:"(짐을 옮겨) 텅 비우다",tip:"결과보어 空. 吃空 / 搬空 / 掏空처럼 '비게 만들다'를 나타냅니다."},
          {t:"退",p:"tuì",k:"word",m:"돌려주다, 반환하다",tip:"退押金 / 退货 / 退款. 돈이 되돌아오는 모든 장면에 씁니다."}]},
  {s:"B",zh:"别急，我得先看看房子，墙上那几个洞总得补吧。",py:"Bié jí, wǒ děi xiān kànkan fángzi, qiáng shàng nà jǐ ge dòng zǒng děi bǔ ba.",
   ko:"서두르지 마요, 집부터 좀 봐야지. 벽에 난 그 구멍들은 메워야 하지 않겠어요?",
   ck:[["别急，我得先看看房子","Bié jí, wǒ děi xiān kànkan fángzi"],["墙上那几个洞总得补吧","qiáng shàng nà jǐ ge dòng zǒng děi bǔ ba"]],
   notes:[{t:"总得…吧",p:"zǒng děi…ba",k:"expr",m:"아무래도 ~해야 하지 않겠어요",tip:"总不能…吧의 짝입니다. 이쪽은 요구를 부드럽게 밀어 넣습니다."}]},
  {s:"A",zh:"那几个洞是我进来之前就有的，当时拍了照，还发您微信了。",py:"Nà jǐ ge dòng shì wǒ jìnlái zhīqián jiù yǒu de, dāngshí pāi le zhào, hái fā nín Wēixìn le.",
   ko:"그 구멍들은 제가 들어오기 전부터 있던 거예요. 그때 사진 찍어서 위챗으로 보내 드렸잖아요.",
   ck:[["那几个洞是我进来之前就有的","Nà jǐ ge dòng shì wǒ jìnlái zhīqián jiù yǒu de"],["当时拍了照","dāngshí pāi le zhào"],["还发您微信了","hái fā nín Wēixìn le"]],
   notes:[{t:"是…的",p:"shì…de",k:"grammar",m:"(시점·주체를) 강조하는 구문",tip:"是我进来之前就有的 = 내가 들어오기 '전부터' 있었던 것이다. 책임 소재를 가릴 때 필수입니다."},
          {t:"当时",p:"dāngshí",k:"word",m:"그때, 그 당시",tip:"那会儿보다 격식 있게 들립니다. 증거를 말할 때 잘 어울립니다."}]},
  {s:"B",zh:"有这事儿？我一时想不起来了，你把照片再发我一遍。",py:"Yǒu zhè shìr? Wǒ yìshí xiǎng bu qǐlái le, nǐ bǎ zhàopiàn zài fā wǒ yí biàn.",
   ko:"그런 일이 있었나? 지금 당장은 기억이 안 나네. 사진 다시 한 번 보내 봐요.",
   ck:[["有这事儿","Yǒu zhè shìr"],["我一时想不起来了","Wǒ yìshí xiǎng bu qǐlái le"],["你把照片再发我一遍","nǐ bǎ zhàopiàn zài fā wǒ yí biàn"]],
   notes:[{t:"想不起来",p:"xiǎng bu qǐlái",k:"grammar",m:"떠올리지 못하다",tip:"가능보어. 记不住(외우지 못함)와 다릅니다. 이쪽은 '알던 것이 안 떠오름'입니다."},
          {t:"把…发我一遍",p:"bǎ…fā wǒ yí biàn",k:"grammar",m:"~을 나에게 한 번 더 보내다",tip:"把자문 + 동량보어 一遍. 再…一遍은 '다시 한 번'입니다."}]},
  {s:"A",zh:"已经发过去了。合同上白纸黑字写着，原有损坏不算我的。",py:"Yǐjīng fā guòqù le. Hétong shàng bái zhǐ hēi zì xiě zhe, yuányǒu sǔnhuài bú suàn wǒ de.",
   ko:"이미 보냈어요. 계약서에 분명히 적혀 있잖아요, 원래 있던 파손은 제 책임이 아니라고요.",
   ck:[["已经发过去了","Yǐjīng fā guòqù le"],["合同上白纸黑字写着","Hétong shàng bái zhǐ hēi zì xiě zhe"],["原有损坏不算我的","yuányǒu sǔnhuài bú suàn wǒ de"]],
   notes:[{t:"白纸黑字",p:"bái zhǐ hēi zì",k:"idiom",m:"흰 종이에 검은 글씨, 문서로 분명히",tip:"구두 약속과 대비해 문서를 들이밀 때 씁니다. 白纸黑字写着呢！"},
          {t:"不算我的",p:"bú suàn wǒ de",k:"expr",m:"내 책임으로 치지 않는다",tip:"算은 '~으로 친다'입니다. 这不算加班 / 算你的."}]},
  {s:"B",zh:"行行行，这个不算你的。可地板那道划痕，你总不能也赖我吧。",py:"Xíng xíng xíng, zhège bú suàn nǐ de. Kě dìbǎn nà dào huáhén, nǐ zǒng bù néng yě lài wǒ ba.",
   ko:"알았어 알았어, 그건 당신 책임 아니야. 그런데 바닥의 그 긁힌 자국은 설마 나한테 미루진 않겠지?",
   ck:[["行行行，这个不算你的","Xíng xíng xíng, zhège bú suàn nǐ de"],["可地板那道划痕","Kě dìbǎn nà dào huáhén"],["你总不能也赖我吧","nǐ zǒng bù néng yě lài wǒ ba"]],
   notes:[{t:"赖",p:"lài",k:"word",m:"(책임을) 뒤집어씌우다",tip:"赖我 / 赖账(빚을 떼먹다). 구어에서 자주 나오는 강한 단어입니다."},
          {t:"道",p:"dào",k:"measure",m:"줄·금을 세는 양사",tip:"一道划痕 / 一道疤 / 一道菜. 길게 난 자국에는 道를 씁니다."}]},
  {s:"A",zh:"划痕我认。不过那是正常使用的磨损，按理不该全扣我的。",py:"Huáhén wǒ rèn. Búguò nà shì zhèngcháng shǐyòng de mósǔn, ànlǐ bù gāi quán kòu wǒ de.",
   ko:"긁힌 건 제가 인정해요. 다만 정상적으로 쓰다 생긴 마모니까, 원칙대로면 다 떼면 안 되죠.",
   ck:[["划痕我认","Huáhén wǒ rèn"],["不过那是正常使用的磨损","Búguò nà shì zhèngcháng shǐyòng de mósǔn"],["按理不该全扣我的","ànlǐ bù gāi quán kòu wǒ de"]],
   notes:[{t:"认",p:"rèn",k:"word",m:"(잘못을) 인정하다",tip:"这个我认 = 그건 내가 인정한다. 인정할 것만 딱 잘라 인정하면 나머지 주장이 강해집니다."},
          {t:"按理",p:"ànlǐ",k:"word",m:"이치대로라면, 원칙대로면",tip:"按理说로도 씁니다. 按理说他早该到了."}]},
  {s:"B",zh:"正常磨损归正常磨损，可修一下也得花钱，这钱谁出？",py:"Zhèngcháng mósǔn guī zhèngcháng mósǔn, kě xiū yíxià yě děi huā qián, zhè qián shéi chū?",
   ko:"정상 마모는 정상 마모고, 그래도 고치려면 돈이 드는데 그 돈은 누가 내요?",
   ck:[["正常磨损归正常磨损","Zhèngcháng mósǔn guī zhèngcháng mósǔn"],["可修一下也得花钱","kě xiū yíxià yě děi huā qián"],["这钱谁出","zhè qián shéi chū"]],
   notes:[{t:"A归A",p:"A guī A",k:"grammar",m:"A는 A대로 인정하되, 그것과 별개로",tip:"8일차에도 나온 골격입니다. 상대의 논리를 인정하면서 무력화합니다."},
          {t:"出钱",p:"chū qián",k:"expr",m:"돈을 대다, 비용을 부담하다",tip:"谁出钱？ / 我出一半. 出는 '내놓다'입니다."}]},
  {s:"A",zh:"咱们各让一步。修划痕的钱我出一半，剩下的您担着，行吗？",py:"Zánmen gè ràng yí bù. Xiū huáhén de qián wǒ chū yíbàn, shèngxià de nín dān zhe, xíng ma?",
   ko:"서로 한 발씩 양보하죠. 긁힌 데 고치는 돈은 제가 절반 내고, 나머지는 언니가 부담하시는 걸로, 어때요?",
   ck:[["咱们各让一步","Zánmen gè ràng yí bù"],["修划痕的钱我出一半","Xiū huáhén de qián wǒ chū yíbàn"],["剩下的您担着，行吗","shèngxià de nín dān zhe, xíng ma"]],
   notes:[{t:"各让一步",p:"gè ràng yí bù",k:"expr",m:"서로 한 발씩 양보하다",tip:"협상을 닫는 정석 표현입니다. 各让一步，这事就过去了."},
          {t:"担着",p:"dān zhe",k:"word",m:"떠맡다, 부담하다",tip:"担责任 / 担风险. 着가 붙으면 '계속 지고 있다'는 상태가 됩니다."}]},
  {s:"B",zh:"你倒是会算账。不过话说回来，你这租客确实比上一个省心。",py:"Nǐ dàoshi huì suànzhàng. Búguò huà shuō huí lái, nǐ zhè zūkè quèshí bǐ shàng yí ge shěngxīn.",
   ko:"셈은 참 잘하네. 그건 그렇고, 당신은 지난번 세입자보다 확실히 손이 덜 가긴 했어.",
   ck:[["你倒是会算账","Nǐ dàoshi huì suànzhàng"],["不过话说回来","Búguò huà shuō huí lái"],["你这租客确实比上一个省心","nǐ zhè zūkè quèshí bǐ shàng yí ge shěngxīn"]],
   notes:[{t:"倒是",p:"dàoshi",k:"word",m:"의외로, 오히려 (가벼운 반전)",tip:"你倒是挺会说 = 말은 참 잘하네. 칭찬과 핀잔 사이를 오갑니다."},
          {t:"话说回来",p:"huà shuō huí lái",k:"expr",m:"그건 그렇고, 다시 말하자면",tip:"자기 말을 스스로 뒤집어 균형을 잡는 전환어입니다. 대화를 부드럽게 만듭니다."},
          {t:"省心",p:"shěngxīn",k:"word",m:"신경 쓸 일이 없어 편하다",tip:"这孩子省心 / 让人不省心. 사람에 대한 평가로 자주 씁니다."}]},
  {s:"A",zh:"那您就痛快点，别让我跑三趟才拿到自己的钱。",py:"Nà nín jiù tòngkuai diǎn, bié ràng wǒ pǎo sān tàng cái ná dào zìjǐ de qián.",
   ko:"그럼 시원하게 해 주세요. 제 돈 받자고 세 번씩 오가게 만들지 마시고요.",
   ck:[["那您就痛快点","Nà nín jiù tòngkuai diǎn"],["别让我跑三趟才拿到自己的钱","bié ràng wǒ pǎo sān tàng cái ná dào zìjǐ de qián"]],
   notes:[{t:"痛快点",p:"tòngkuai diǎn",k:"expr",m:"시원시원하게 좀 해라",tip:"你痛快点儿！= 질질 끌지 마. 협상 마무리를 재촉할 때 씁니다."},
          {t:"趟",p:"tàng",k:"measure",m:"오가는 횟수를 세는 양사",tip:"跑一趟 / 白跑一趟(헛걸음하다). 왕복에는 次가 아니라 趟입니다."}]},
  {s:"B",zh:"我什么时候拖过你？水电燃气结清了没有，这个总得算吧。",py:"Wǒ shénme shíhou tuō guo nǐ? Shuǐ diàn ránqì jiéqīng le méiyǒu, zhège zǒng děi suàn ba.",
   ko:"내가 언제 당신 걸 질질 끈 적 있어? 수도·전기·가스는 정산했나? 그건 따져 봐야지.",
   ck:[["我什么时候拖过你","Wǒ shénme shíhou tuō guo nǐ"],["水电燃气结清了没有","Shuǐ diàn ránqì jiéqīng le méiyǒu"],["这个总得算吧","zhège zǒng děi suàn ba"]],
   notes:[{t:"我什么时候…过？",p:"wǒ shénme shíhou…guo?",k:"grammar",m:"내가 언제 ~한 적 있냐?",tip:"의문사로 강하게 부정하는 반문입니다. 我什么时候骗过你？"},
          {t:"结清",p:"jiéqīng",k:"word",m:"정산해 깨끗이 마무리하다",tip:"结清账 / 结清费用. 清이 '남김없이'를 뜻합니다."}]},
  {s:"A",zh:"昨天全交完了，单子我都留着呢，一张都没少。",py:"Zuótiān quán jiāo wán le, dānzi wǒ dōu liú zhe ne, yì zhāng dōu méi shǎo.",
   ko:"어제 전부 냈어요. 영수증도 다 갖고 있고요, 한 장도 빠짐없이요.",
   ck:[["昨天全交完了","Zuótiān quán jiāo wán le"],["单子我都留着呢","dānzi wǒ dōu liú zhe ne"],["一张都没少","yì zhāng dōu méi shǎo"]],
   notes:[{t:"一…都没…",p:"yì…dōu méi…",k:"grammar",m:"하나도 ~하지 않았다",tip:"连…都…의 강조형입니다. 一分都没花 / 一句都没说."},
          {t:"…呢",p:"…ne",k:"expr",m:"(상태를 강조하는) 어기조사",tip:"我留着呢 = 잘 갖고 있다니까요. 상대의 의심을 눌러 줍니다."}]},
  {s:"B",zh:"那还行。这样吧，扣两百修地板，剩下的今天就转给你。",py:"Nà hái xíng. Zhèyàng ba, kòu liǎngbǎi xiū dìbǎn, shèngxià de jīntiān jiù zhuǎn gěi nǐ.",
   ko:"그럼 됐네. 이렇게 하자, 바닥 수리비로 이백 떼고 나머지는 오늘 바로 보내 줄게.",
   ck:[["那还行","Nà hái xíng"],["这样吧，扣两百修地板","Zhèyàng ba, kòu liǎngbǎi xiū dìbǎn"],["剩下的今天就转给你","shèngxià de jīntiān jiù zhuǎn gěi nǐ"]],
   notes:[{t:"这样吧",p:"zhèyàng ba",k:"expr",m:"이렇게 합시다",tip:"절충안을 꺼내는 신호입니다. 那这样吧와 함께 협상의 필수 표현입니다."},
          {t:"转",p:"zhuǎn",k:"word",m:"송금하다, 이체하다",tip:"微信转账 / 转给你. 요즘 중국에서 가장 자주 쓰는 결제 동사입니다."}]},
  {s:"A",zh:"两百有点多吧。我问过师傅，那种划痕补一下也就一百出头。",py:"Liǎngbǎi yǒudiǎn duō ba. Wǒ wèn guo shīfu, nà zhǒng huáhén bǔ yíxià yě jiù yìbǎi chūtóu.",
   ko:"이백은 좀 많은데요. 기사님한테 물어보니 그 정도 긁힘은 손보는 데 백 남짓이면 된대요.",
   ck:[["两百有点多吧","Liǎngbǎi yǒudiǎn duō ba"],["我问过师傅","Wǒ wèn guo shīfu"],["那种划痕补一下也就一百出头","nà zhǒng huáhén bǔ yíxià yě jiù yìbǎi chūtóu"]],
   notes:[{t:"出头",p:"chūtóu",k:"word",m:"~ 남짓, 조금 넘음",tip:"三十出头 = 서른 남짓. 나이와 금액에 두루 씁니다."},
          {t:"也就",p:"yě jiù",k:"expr",m:"기껏해야, 겨우",tip:"也就一百 = 많아야 백. 액수를 깎을 때 아주 유용합니다."}]},
  {s:"B",zh:"你还真去打听了。行，一百五，这回我可一分没多要。",py:"Nǐ hái zhēn qù dǎting le. Xíng, yìbǎi wǔ, zhè huí wǒ kě yì fēn méi duō yào.",
   ko:"진짜로 알아봤네. 좋아, 백오십. 이번엔 한 푼도 더 안 받았어.",
   ck:[["你还真去打听了","Nǐ hái zhēn qù dǎting le"],["行，一百五","Xíng, yìbǎi wǔ"],["这回我可一分没多要","zhè huí wǒ kě yì fēn méi duō yào"]],
   notes:[{t:"还真",p:"hái zhēn",k:"expr",m:"정말로 (뜻밖이라는 어감)",tip:"你还真去了 = 진짜로 갔네. 감탄과 놀람이 섞입니다."},
          {t:"一分没多要",p:"yì fēn méi duō yào",k:"expr",m:"한 푼도 더 받지 않았다",tip:"分은 가장 작은 화폐 단위입니다. 一分钱都没花처럼 강조에 씁니다."}]},
  {s:"A",zh:"那就这么定了。您现在转，我这边确认收到就把钥匙给您。",py:"Nà jiù zhème dìng le. Nín xiànzài zhuǎn, wǒ zhèbiān quèrèn shōu dào jiù bǎ yàoshi gěi nín.",
   ko:"그럼 그렇게 하기로 해요. 지금 보내 주시면 제가 확인하는 대로 열쇠 드릴게요.",
   ck:[["那就这么定了","Nà jiù zhème dìng le"],["您现在转","Nín xiànzài zhuǎn"],["我这边确认收到就把钥匙给您","wǒ zhèbiān quèrèn shōu dào jiù bǎ yàoshi gěi nín"]],
   notes:[{t:"这边",p:"zhèbiān",k:"word",m:"저희 쪽, 이쪽",tip:"我这边 / 你那边. 사람 대신 '쪽'으로 말하면 사무적이고 부드럽습니다."},
          {t:"把钥匙给您",p:"bǎ yàoshi gěi nín",k:"grammar",m:"열쇠를 당신께 드리다",tip:"把자문의 기본형입니다. 목적어를 앞으로 빼 처리 결과를 강조합니다."}]},
  {s:"B",zh:"你这孩子，防我跟防贼似的。转就转，我还能赖你这点钱？",py:"Nǐ zhè háizi, fáng wǒ gēn fáng zéi shìde. Zhuǎn jiù zhuǎn, wǒ hái néng lài nǐ zhè diǎn qián?",
   ko:"이 사람 참, 나를 도둑 막듯이 경계하네. 보내면 보내는 거지, 내가 이 돈을 떼먹기야 하겠어?",
   ck:[["你这孩子","Nǐ zhè háizi"],["防我跟防贼似的","fáng wǒ gēn fáng zéi shìde"],["转就转","Zhuǎn jiù zhuǎn"],["我还能赖你这点钱","wǒ hái néng lài nǐ zhè diǎn qián"]],
   notes:[{t:"跟…似的",p:"gēn…shìde",k:"grammar",m:"마치 ~인 것처럼",tip:"跟没事人似的 = 아무 일 없는 사람처럼. 像…一样의 구어형입니다."},
          {t:"V就V",p:"V jiù V",k:"grammar",m:"~하면 ~하는 거지 뭐",tip:"체념이나 수락을 나타냅니다. 去就去 / 买就买."}]},
  {s:"A",zh:"您别多心，有言在先大家都省事，回头也不用扯皮。",py:"Nín bié duōxīn, yǒu yán zài xiān dàjiā dōu shěngshì, huítóu yě búyòng chěpí.",
   ko:"오해하지 마세요. 미리 말해 두면 서로 편하고, 나중에 옥신각신할 일도 없잖아요.",
   ck:[["您别多心","Nín bié duōxīn"],["有言在先大家都省事","yǒu yán zài xiān dàjiā dōu shěngshì"],["回头也不用扯皮","huítóu yě búyòng chěpí"]],
   notes:[{t:"多心",p:"duōxīn",k:"word",m:"괜히 의심하다, 넘겨짚다",tip:"你别多心 = 오해하지 마세요. 관계를 지키는 한마디입니다."},
          {t:"有言在先",p:"yǒu yán zài xiān",k:"idiom",m:"미리 말해 두다",tip:"뒷말을 막는 성어입니다. 咱们有言在先，超时就加钱."},
          {t:"扯皮",p:"chěpí",k:"word",m:"옥신각신하며 책임을 미루다",tip:"两个部门互相扯皮. 회사에서도 그대로 씁니다."}]},
  {s:"B",zh:"说得也对。钱转过去了，你查收，往后租房子还找我。",py:"Shuō de yě duì. Qián zhuǎn guòqù le, nǐ cháshōu, wǎnghòu zū fángzi hái zhǎo wǒ.",
   ko:"그 말도 맞네. 돈 보냈으니 확인해요. 나중에 또 집 구하면 나한테 오고.",
   ck:[["说得也对","Shuō de yě duì"],["钱转过去了，你查收","Qián zhuǎn guòqù le, nǐ cháshōu"],["往后租房子还找我","wǎnghòu zū fángzi hái zhǎo wǒ"]],
   notes:[{t:"查收",p:"cháshōu",k:"word",m:"확인하고 받다",tip:"请查收는 메일·송금의 정형구입니다. 문서를 보낼 때도 그대로 씁니다."},
          {t:"往后",p:"wǎnghòu",k:"word",m:"앞으로, 이후로",tip:"以后와 같은 뜻인데 구어에서 더 정겹게 들립니다."}]}
 ],
 keys:[
  {zh:"白纸黑字",py:"bái zhǐ hēi zì",ko:"문서에 분명히 적혀 있다",
   ex:"合同上白纸黑字写着，你不能不认。",exPy:"Hétong shàng bái zhǐ hēi zì xiě zhe, nǐ bù néng bú rèn.",exKo:"계약서에 분명히 적혀 있으니 인정 안 할 수 없죠."},
  {zh:"总得…吧",py:"zǒng děi…ba",ko:"아무래도 ~해야 하지 않겠어요",
   ex:"你总得给我个理由吧。",exPy:"Nǐ zǒng děi gěi wǒ ge lǐyóu ba.",exKo:"그래도 이유는 하나 대 주셔야죠."},
  {zh:"按理",py:"ànlǐ",ko:"원칙대로라면, 이치대로면",
   ex:"按理这笔费用应该公司出。",exPy:"Ànlǐ zhè bǐ fèiyòng yīnggāi gōngsī chū.",exKo:"원칙대로면 이 비용은 회사가 내야 합니다."},
  {zh:"各让一步",py:"gè ràng yí bù",ko:"서로 한 발씩 양보하다",
   ex:"咱们各让一步，这事今天就了了。",exPy:"Zánmen gè ràng yí bù, zhè shì jīntiān jiù liǎo le.",exKo:"서로 한 발씩 양보하면 이 일은 오늘 끝납니다."},
  {zh:"话说回来",py:"huà shuō huí lái",ko:"그건 그렇고, 다시 말하자면",
   ex:"话说回来，这次也不全怪你。",exPy:"Huà shuō huí lái, zhè cì yě bù quán guài nǐ.",exKo:"그건 그렇고, 이번 일이 전부 당신 탓만은 아니에요."},
  {zh:"也就…",py:"yě jiù…",ko:"기껏해야, 겨우 ~ 정도",
   ex:"这活儿也就半天的事。",exPy:"Zhè huór yě jiù bàntiān de shì.",exKo:"이 일은 기껏해야 반나절이면 됩니다."},
  {zh:"跟…似的",py:"gēn…shìde",ko:"마치 ~인 것처럼",
   ex:"他忙得跟陀螺似的。",exPy:"Tā máng de gēn tuóluó shìde.",exKo:"그 사람은 팽이처럼 바쁘게 돌아다녀요."},
  {zh:"有言在先",py:"yǒu yán zài xiān",ko:"미리 말해 두다",
   ex:"咱们有言在先，超过期限就按合同办。",exPy:"Zánmen yǒu yán zài xiān, chāoguò qīxiàn jiù àn hétong bàn.",exKo:"미리 말해 두는데, 기한을 넘기면 계약대로 처리합니다."}
 ],
 out:[
  {q:"집주인이 원래 있던 하자를 당신 탓으로 돌립니다. 증거를 들어 반박해 보세요.",hint:"是…的 / 白纸黑字 / 不算我的"},
  {q:"인정할 것은 인정하되, 전액 공제는 막아 보세요.",hint:"划痕我认 / 正常磨损归正常磨损 / 按理"},
  {q:"금액 합의 후, 관계를 상하지 않게 마무리해 보세요.",hint:"各让一步 / 您别多心 / 有言在先"}
 ]
}
