{
 id:"c3d1", day:16, cat:"문병·예의", level:"HSK 5~6",
 title:"病房里的分寸", titlePy:"bìngfáng lǐ de fēncùn", titleKo:"병문안 — 위로하되 넘지 않는 선",
 names:{A:"小林 (후배 동료)", B:"老张 (입원한 선배)"},
 brief:[
  "병문안은 <b>말을 많이 해서 되는 자리가 아닙니다</b>. 환자는 이미 같은 질문을 스무 번 받았고, 몸보다 지친 것은 설명하는 일입니다. 그래서 중국어 병문안의 기본은 짧게 묻고, 길게 듣고, 일찍 일어서는 것입니다.",
  "선을 넘기 쉬운 대목이 셋 있습니다. <b>병세를 캐묻는 것</b>, <b>치료법을 권하는 것</b>, 그리고 <b>너무 오래 앉아 있는 것</b>입니다. 반대로 환자가 가장 듣고 싶어 하는 말은 「회사 일은 우리가 맡고 있다」는 한마디입니다.",
  "이 회차에는 위로의 말과 함께 <b>안심시키는 표현</b>이 여럿 나옵니다. 把心放肚子里(마음 푹 놓으세요), 您把身体养好(몸부터 추스르세요)처럼, 걱정의 대상을 상대에게서 내 쪽으로 옮겨 오는 말들입니다.",
  "마지막에 주목하세요. 환자가 <b>来什么来(오긴 뭘 와)</b>라며 다음 방문을 말리고, 대신 퇴원 후 식사를 기약합니다. 중국식 사양의 전형이며, 관계를 닫지 않고 자리를 마무리하는 방식입니다."
 ],
 vocab:[
  {w:"惦记",p:"diànjì",m:"마음에 걸려 계속 생각하다",lv:"HSK5"},
  {w:"难熬",p:"nán'áo",m:"견디기 힘들다",lv:"HSK6"},
  {w:"应酬",p:"yìngchou",m:"(업무상) 술자리·접대",lv:"HSK6"},
  {w:"摊子",p:"tānzi",m:"벌여 놓은 일, 판",lv:"구어"},
  {w:"岔子",p:"chàzi",m:"사고, 탈",lv:"구어"},
  {w:"拿不准",p:"ná bu zhǔn",m:"확신이 안 서다",lv:"구어"},
  {w:"撑",p:"chēng",m:"버티다, 떠받치다",lv:"HSK5"},
  {w:"难为情",p:"nánwéiqíng",m:"쑥스럽다, 민망하다",lv:"HSK6"},
  {w:"没辙",p:"méizhé",m:"어쩔 도리가 없다",lv:"구어"},
  {w:"在理",p:"zàilǐ",m:"이치에 맞다",lv:"구어"},
  {w:"福气",p:"fúqi",m:"복, 복됨",lv:"HSK5"},
  {w:"一环扣一环",p:"yì huán kòu yì huán",m:"하나가 하나에 물려 있다",lv:"성어"}
 ],
 lines:[
  {s:"A",zh:"老张，我来看看您。东西放这儿了，您可别嫌我来得晚。",py:"Lǎo Zhāng, wǒ lái kànkan nín. Dōngxi fàng zhèr le, nín kě bié xián wǒ lái de wǎn.",
   ko:"장 선배님, 뵈러 왔습니다. 물건은 여기 두었고요, 늦게 왔다고 타박은 마세요.",
   ck:[["老张，我来看看您","Lǎo Zhāng, wǒ lái kànkan nín"],["东西放这儿了","dōngxi fàng zhèr le"],["您可别嫌我来得晚","nín kě bié xián wǒ lái de wǎn"]],
   notes:[{t:"可别嫌…",p:"kě bié xián…",k:"expr",m:"~ 라고 흉보지 마세요",tip:"미리 사과를 깔아 두는 겸양입니다. 可别嫌少 / 可别嫌简单."},
          {t:"来看看您",p:"lái kànkan nín",k:"expr",m:"뵈러 왔습니다",tip:"동사 중첩으로 방문의 무게를 덜어 줍니다. 看望보다 훨씬 구어적입니다."}]},
  {s:"B",zh:"你这孩子，来就来了，还拎这么一大堆，让我怎么好意思。",py:"Nǐ zhè háizi, lái jiù lái le, hái līn zhème yí dà duī, ràng wǒ zěnme hǎoyìsi.",
   ko:"이 사람아, 오면 왔지 뭘 이렇게 한 보따리를 들고 와. 내가 민망하잖아.",
   ck:[["你这孩子，来就来了","Nǐ zhè háizi, lái jiù lái le"],["还拎这么一大堆","hái līn zhème yí dà duī"],["让我怎么好意思","ràng wǒ zěnme hǎoyìsi"]],
   notes:[{t:"来就来了",p:"lái jiù lái le",k:"grammar",m:"오면 왔지 (그걸로 됐지)",tip:"V就V了는 이미 벌어진 일을 가볍게 넘기는 골격입니다. 买就买了 / 说就说了."},
          {t:"让我怎么好意思",p:"ràng wǒ zěnme hǎoyìsi",k:"expr",m:"제가 민망해서 어쩝니까",tip:"선물을 받을 때의 정형화된 사양입니다."}]},
  {s:"A",zh:"应该的。手术那天我实在走不开，心里一直惦记着。",py:"Yīnggāi de. Shǒushù nà tiān wǒ shízài zǒu bu kāi, xīnlǐ yìzhí diànjì zhe.",
   ko:"당연한 걸요. 수술하시던 날 도저히 자리를 못 떠서, 내내 마음에 걸렸습니다.",
   ck:[["应该的","Yīnggāi de"],["手术那天我实在走不开","shǒushù nà tiān wǒ shízài zǒu bu kāi"],["心里一直惦记着","xīnlǐ yìzhí diànjì zhe"]],
   notes:[{t:"惦记着",p:"diànjì zhe",k:"word",m:"계속 마음에 걸려 있다",tip:"想念이 그리움이라면 惦记는 걱정입니다. 家里人一直惦记着你."},
          {t:"应该的",p:"Yīnggāi de",k:"expr",m:"당연한 일입니다",tip:"고맙다는 말에 대한 가장 짧은 응답입니다."}]},
  {s:"B",zh:"别提了，说是小手术，疼起来那两天我连觉都睡不着。",py:"Bié tí le, shuō shì xiǎo shǒushù, téng qǐlai nà liǎng tiān wǒ lián jiào dōu shuì bu zháo.",
   ko:"말도 마. 작은 수술이라더니, 아프기 시작한 그 이틀은 잠도 못 잤어.",
   ck:[["别提了，说是小手术","Bié tí le, shuō shì xiǎo shǒushù"],["疼起来那两天","téng qǐlai nà liǎng tiān"],["我连觉都睡不着","wǒ lián jiào dōu shuì bu zháo"]],
   notes:[{t:"疼起来",p:"téng qǐlai",k:"grammar",m:"아프기 시작하면",tip:"V起来는 「~하기 시작하다」와 「~해 보니」 두 갈래입니다. 여기서는 앞쪽입니다."},
          {t:"睡不着",p:"shuì bu zháo",k:"grammar",m:"잠들 수가 없다",tip:"가능보어입니다. 睡不着(잠이 안 옴)와 睡不了(잘 수가 없음)는 다릅니다."}]},
  {s:"A",zh:"那会儿最难熬。现在能下床走两步，就算过去了。",py:"Nà huìr zuì nán'áo. Xiànzài néng xià chuáng zǒu liǎng bù, jiù suàn guòqù le.",
   ko:"그때가 제일 견디기 힘들죠. 이제 침대에서 내려와 몇 걸음 걸으시면 고비는 넘긴 겁니다.",
   ck:[["那会儿最难熬","Nà huìr zuì nán'áo"],["现在能下床走两步","xiànzài néng xià chuáng zǒu liǎng bù"],["就算过去了","jiù suàn guòqù le"]],
   notes:[{t:"难熬",p:"nán'áo",k:"word",m:"견디기 힘들다",tip:"시간이 안 가는 괴로움입니다. 这三天最难熬."},
          {t:"就算过去了",p:"jiù suàn guòqù le",k:"expr",m:"그럼 고비는 넘긴 셈입니다",tip:"算은 「~인 셈으로 치다」입니다. 这就算完了."}]},
  {s:"B",zh:"可不是嘛。医生说恢复得挺好，就是不让我沾一口酒。",py:"Kě bú shì ma. Yīshēng shuō huīfù de tǐng hǎo, jiùshì bú ràng wǒ zhān yì kǒu jiǔ.",
   ko:"그러게 말이야. 의사는 회복이 좋다는데, 술은 한 모금도 못 대게 해.",
   ck:[["可不是嘛","Kě bú shì ma"],["医生说恢复得挺好","yīshēng shuō huīfù de tǐng hǎo"],["就是不让我沾一口酒","jiùshì bú ràng wǒ zhān yì kǒu jiǔ"]],
   notes:[{t:"沾一口",p:"zhān yì kǒu",k:"expr",m:"한 모금 대다",tip:"沾은 「살짝 닿다」입니다. 一口酒都不能沾 = 술은 한 방울도 안 된다."},
          {t:"就是",p:"jiùshì",k:"grammar",m:"다만, 단지",tip:"앞을 인정하고 아쉬운 한 가지를 덧붙입니다. 挺好的，就是有点贵."}]},
  {s:"A",zh:"那正好，您这些年应酬太多，身体早该歇一歇了。",py:"Nà zhènghǎo, nín zhèxiē nián yìngchou tài duō, shēntǐ zǎo gāi xiē yi xiē le.",
   ko:"잘됐네요. 그동안 술자리가 너무 많으셨어요. 몸도 진작 쉬었어야 했고요.",
   ck:[["那正好","Nà zhènghǎo"],["您这些年应酬太多","nín zhèxiē nián yìngchou tài duō"],["身体早该歇一歇了","shēntǐ zǎo gāi xiē yi xiē le"]],
   notes:[{t:"应酬",p:"yìngchou",k:"word",m:"업무상 술자리, 접대",tip:"피할 수 없는 자리라는 뉘앙스가 강합니다. 今晚有个应酬."},
          {t:"早该…了",p:"zǎo gāi…le",k:"grammar",m:"진작 ~ 했어야 했다",tip:"때를 놓쳤다는 가벼운 나무람입니다. 你早该说了."}]},
  {s:"B",zh:"话是这么说，可一闲下来，心里反倒更空得慌。",py:"Huà shì zhème shuō, kě yì xián xiàlai, xīnlǐ fǎndào gèng kōng de huāng.",
   ko:"말은 그렇지. 그런데 막상 한가해지니까 속이 오히려 더 허전해.",
   ck:[["话是这么说","Huà shì zhème shuō"],["可一闲下来","kě yì xián xiàlai"],["心里反倒更空得慌","xīnlǐ fǎndào gèng kōng de huāng"]],
   notes:[{t:"一…就/反倒…",p:"yì… fǎndào…",k:"grammar",m:"~ 하자마자 오히려",tip:"一 + 동사는 「~하자마자」입니다. 反倒는 예상과 반대라는 뜻입니다."},
          {t:"空得慌",p:"kōng de huāng",k:"expr",m:"허전해 못 견디겠다",tip:"得慌은 형용사 뒤에 붙어 「~해서 견딜 수 없다」입니다. 饿得慌 / 闷得慌."}]},
  {s:"A",zh:"您那摊子事我们顶着呢，您非得现在操心不可吗？",py:"Nín nà tānzi shì wǒmen dǐng zhe ne, nín fēiděi xiànzài cāoxīn bùkě ma?",
   ko:"선배님 벌여 놓으신 일은 저희가 받치고 있습니다. 꼭 지금 걱정하셔야겠어요?",
   ck:[["您那摊子事我们顶着呢","Nín nà tānzi shì wǒmen dǐng zhe ne"],["您非得现在操心不可吗","nín fēiděi xiànzài cāoxīn bùkě ma"]],
   notes:[{t:"摊子",p:"tānzi",k:"word",m:"벌여 놓은 일, 판",tip:"收拾摊子 = 벌여 놓은 일을 수습하다. 부담스러운 일더미를 뜻합니다."},
          {t:"非得…不可",p:"fēiděi… bùkě",k:"grammar",m:"꼭 ~ 해야만 한다",tip:"非…不可의 강조형입니다. 여기서는 반문으로 만류하고 있습니다."}]},
  {s:"B",zh:"不操心不行啊，那个项目一环扣一环，出了岔子谁都担不起。",py:"Bù cāoxīn bù xíng a, nàge xiàngmù yì huán kòu yì huán, chū le chàzi shéi dōu dān bu qǐ.",
   ko:"걱정을 안 할 수가 없지. 그 프로젝트는 하나가 하나에 물려 있어서, 탈 나면 아무도 감당 못 해.",
   ck:[["不操心不行啊","Bù cāoxīn bù xíng a"],["那个项目一环扣一环","nàge xiàngmù yì huán kòu yì huán"],["出了岔子谁都担不起","chū le chàzi shéi dōu dān bu qǐ"]],
   notes:[{t:"一环扣一环",p:"yì huán kòu yì huán",k:"idiom",m:"하나가 하나에 물려 있다",tip:"공정이나 논리가 촘촘히 맞물려 있다는 뜻입니다."},
          {t:"担不起",p:"dān bu qǐ",k:"grammar",m:"감당할 수 없다",tip:"가능보어입니다. 责任担不起 / 后果担不起."}]},
  {s:"A",zh:"您把心放肚子里。真有拿不准的，我随时给您打电话。",py:"Nín bǎ xīn fàng dùzi lǐ. Zhēn yǒu ná bu zhǔn de, wǒ suíshí gěi nín dǎ diànhuà.",
   ko:"마음 푹 놓으세요. 정말 확신이 안 서는 게 있으면 바로 전화드리겠습니다.",
   ck:[["您把心放肚子里","Nín bǎ xīn fàng dùzi lǐ"],["真有拿不准的","zhēn yǒu ná bu zhǔn de"],["我随时给您打电话","wǒ suíshí gěi nín dǎ diànhuà"]],
   notes:[{t:"把心放肚子里",p:"bǎ xīn fàng dùzi lǐ",k:"idiom",m:"마음을 푹 놓다",tip:"把자문으로 된 관용구입니다. 안심시키는 말 중 가장 자연스럽습니다."},
          {t:"拿不准",p:"ná bu zhǔn",k:"grammar",m:"확신이 서지 않다",tip:"가능보어입니다. 我拿不准他的意思."}]},
  {s:"B",zh:"那我就不客气了。说到底还是得靠你们几个撑着。",py:"Nà wǒ jiù bú kèqi le. Shuōdàodǐ háishi děi kào nǐmen jǐ ge chēng zhe.",
   ko:"그럼 사양 안 할게. 결국은 자네들 몇이서 받쳐 줘야 하는 거지.",
   ck:[["那我就不客气了","Nà wǒ jiù bú kèqi le"],["说到底","shuōdàodǐ"],["还是得靠你们几个撑着","háishi děi kào nǐmen jǐ ge chēng zhe"]],
   notes:[{t:"撑着",p:"chēng zhe",k:"word",m:"버텨 주고 있다",tip:"撑은 무게를 떠받치는 그림입니다. 撑住 / 撑不下去了."}]},
  {s:"A",zh:"您别这么说。您带我那几年，我欠您的可不止这一趟。",py:"Nín bié zhème shuō. Nín dài wǒ nà jǐ nián, wǒ qiàn nín de kě bùzhǐ zhè yí tàng.",
   ko:"그런 말씀 마세요. 저를 가르쳐 주신 그 몇 년, 제가 진 빚은 이 한 번으로 안 됩니다.",
   ck:[["您别这么说","Nín bié zhème shuō"],["您带我那几年","nín dài wǒ nà jǐ nián"],["我欠您的可不止这一趟","wǒ qiàn nín de kě bùzhǐ zhè yí tàng"]],
   notes:[{t:"带",p:"dài",k:"word",m:"(후배를) 가르치며 이끌다",tip:"师傅带徒弟. 직장에서 사수가 후배를 맡는 것을 带라고 합니다."},
          {t:"可不止",p:"kě bùzhǐ",k:"expr",m:"그 정도로 그치지 않는다",tip:"不止는 「~에 그치지 않다」입니다. 不止一次 = 한두 번이 아니다."}]},
  {s:"B",zh:"行了行了，再说下去我这眼泪都要出来了，多难为情。",py:"Xíng le xíng le, zài shuō xiàqù wǒ zhè yǎnlèi dōu yào chūlai le, duō nánwéiqíng.",
   ko:"됐어 됐어, 더 얘기하면 눈물 나오겠다. 이 무슨 창피야.",
   ck:[["行了行了","Xíng le xíng le"],["再说下去","zài shuō xiàqù"],["我这眼泪都要出来了","wǒ zhè yǎnlèi dōu yào chūlai le"],["多难为情","duō nánwéiqíng"]],
   notes:[{t:"再…下去",p:"zài… xiàqù",k:"grammar",m:"계속 더 ~ 하면",tip:"이대로 이어지면 어떻게 된다는 경고입니다. 再拖下去就来不及了."},
          {t:"难为情",p:"nánwéiqíng",k:"word",m:"쑥스럽다, 민망하다",tip:"不好意思보다 감정이 깊고 겸연쩍은 쪽입니다."}]},
  {s:"A",zh:"那我不说了。嫂子呢？这几天一直是她在这儿守着吗？",py:"Nà wǒ bù shuō le. Sǎozi ne? Zhè jǐ tiān yìzhí shì tā zài zhèr shǒu zhe ma?",
   ko:"그럼 그만할게요. 형수님은요? 요 며칠 계속 여기서 지키고 계셨어요?",
   ck:[["那我不说了","Nà wǒ bù shuō le"],["嫂子呢","sǎozi ne"],["这几天一直是她","zhè jǐ tiān yìzhí shì tā"],["在这儿守着吗","zài zhèr shǒu zhe ma"]],
   notes:[{t:"嫂子",p:"sǎozi",k:"culture",m:"형수님, 선배의 아내",tip:"친하지 않아도 선배의 배우자를 이렇게 부르면 거리가 가까워집니다."},
          {t:"守着",p:"shǒu zhe",k:"word",m:"곁을 지키다",tip:"병상이나 아이 곁을 떠나지 않는 상태를 말합니다."}]},
  {s:"B",zh:"她白天上班，晚上来。我说让她回去睡，她非不听。",py:"Tā báitiān shàngbān, wǎnshang lái. Wǒ shuō ràng tā huíqù shuì, tā fēi bù tīng.",
   ko:"낮에는 출근하고 저녁에 와. 집에 가서 자라고 해도 한사코 안 들어.",
   ck:[["她白天上班，晚上来","Tā báitiān shàngbān, wǎnshang lái"],["我说让她回去睡","wǒ shuō ràng tā huíqù shuì"],["她非不听","tā fēi bù tīng"]],
   notes:[{t:"非不听",p:"fēi bù tīng",k:"grammar",m:"한사코 듣지 않는다",tip:"非 + 부정은 「기어이 ~ 하지 않는다」는 고집을 나타냅니다. 他非不去."}]},
  {s:"A",zh:"两口子过日子就这样，越劝越不肯走，心疼也没辙。",py:"Liǎngkǒuzi guò rìzi jiù zhèyàng, yuè quàn yuè bù kěn zǒu, xīnténg yě méizhé.",
   ko:"부부 사는 게 다 그렇죠. 말릴수록 안 가려고 하니, 안쓰러워도 방법이 없죠.",
   ck:[["两口子过日子就这样","Liǎngkǒuzi guò rìzi jiù zhèyàng"],["越劝越不肯走","yuè quàn yuè bù kěn zǒu"],["心疼也没辙","xīnténg yě méizhé"]],
   notes:[{t:"两口子",p:"liǎngkǒuzi",k:"culture",m:"부부 두 사람",tip:"夫妻보다 훨씬 구어적이고 정겹습니다. 老两口 = 노부부."},
          {t:"没辙",p:"méizhé",k:"word",m:"어쩔 도리가 없다",tip:"没办法의 구어 강조형입니다. 我真拿他没辙."}]},
  {s:"B",zh:"是啊。人这一病才明白，能吃能睡就是最大的福气。",py:"Shì a. Rén zhè yí bìng cái míngbai, néng chī néng shuì jiùshì zuì dà de fúqi.",
   ko:"그러게. 사람이 한번 아파 봐야 알아. 잘 먹고 잘 자는 게 제일 큰 복이라는 걸.",
   ck:[["是啊","Shì a"],["人这一病才明白","rén zhè yí bìng cái míngbai"],["能吃能睡就是最大的福气","néng chī néng shuì jiùshì zuì dà de fúqi"]],
   notes:[{t:"一…才…",p:"yí… cái…",k:"grammar",m:"한번 ~ 해 보고서야 비로소",tip:"경험해야 알게 된다는 골격입니다. 一走才知道有多远."},
          {t:"福气",p:"fúqi",k:"word",m:"복, 복됨",tip:"건강과 가정에 대해 씁니다. 你真有福气."}]},
  {s:"A",zh:"您这话在理。那我不打扰了，您躺下歇着，我下周再来。",py:"Nín zhè huà zàilǐ. Nà wǒ bù dǎrǎo le, nín tǎng xià xiē zhe, wǒ xià zhōu zài lái.",
   ko:"맞는 말씀이십니다. 그럼 방해 안 하겠습니다. 누워서 쉬세요, 다음 주에 또 오겠습니다.",
   ck:[["您这话在理","Nín zhè huà zàilǐ"],["那我不打扰了","nà wǒ bù dǎrǎo le"],["您躺下歇着","nín tǎng xià xiē zhe"],["我下周再来","wǒ xià zhōu zài lái"]],
   notes:[{t:"在理",p:"zàilǐ",k:"expr",m:"이치에 맞다",tip:"这话在理 = 그 말이 옳다. 짧게 동의할 때 어른스럽습니다."},
          {t:"不打扰了",p:"bù dǎrǎo le",k:"expr",m:"이만 방해 안 하겠습니다",tip:"자리를 뜨는 표준 인사입니다. 병실에서는 특히 자주 씁니다."}]},
  {s:"B",zh:"来什么来，路那么远。等我出院，咱们找个地方好好吃一顿。",py:"Lái shénme lái, lù nàme yuǎn. Děng wǒ chūyuàn, zánmen zhǎo ge dìfang hǎohǎo chī yí dùn.",
   ko:"오긴 뭘 또 와, 길도 먼데. 내가 퇴원하면 어디 가서 제대로 한 끼 하자고.",
   ck:[["来什么来，路那么远","Lái shénme lái, lù nàme yuǎn"],["等我出院","děng wǒ chūyuàn"],["咱们找个地方好好吃一顿","zánmen zhǎo ge dìfang hǎohǎo chī yí dùn"]],
   notes:[{t:"来什么来",p:"lái shénme lái",k:"expr",m:"오긴 뭘 와",tip:"V什么V는 상대의 제안을 정겹게 물리치는 골격입니다. 谢什么谢 / 客气什么客气."},
          {t:"吃一顿",p:"chī yí dùn",k:"measure",m:"한 끼 하다",tip:"식사에는 次가 아니라 顿을 씁니다. 请你吃顿饭."}]}
 ],
 keys:[
  {zh:"可别嫌…",py:"kě bié xián…",ko:"~ 라고 흉보지 마세요",
   ex:"东西不多，您可别嫌少。",exPy:"Dōngxi bù duō, nín kě bié xián shǎo.",exKo:"별것 없습니다, 적다고 흉보지 마세요."},
  {zh:"来就来了",py:"lái jiù lái le",ko:"오면 왔지 (그걸로 됐지)",
   ex:"买就买了，别再退来退去的。",exPy:"Mǎi jiù mǎi le, bié zài tuì lái tuì qù de.",exKo:"샀으면 산 거지, 이리저리 무르지 마."},
  {zh:"惦记着",py:"diànjì zhe",ko:"계속 마음에 걸려 있다",
   ex:"这事我惦记着呢，忘不了。",exPy:"Zhè shì wǒ diànjì zhe ne, wàng bu liǎo.",exKo:"이 일은 제가 마음에 담고 있습니다, 잊을 리 없어요."},
  {zh:"把心放肚子里",py:"bǎ xīn fàng dùzi lǐ",ko:"마음을 푹 놓다",
   ex:"您把心放肚子里，出不了事。",exPy:"Nín bǎ xīn fàng dùzi lǐ, chū bu liǎo shì.",exKo:"마음 푹 놓으세요, 일 날 리 없습니다."},
  {zh:"一环扣一环",py:"yì huán kòu yì huán",ko:"하나가 하나에 물려 있다",
   ex:"流程一环扣一环，停一天全乱。",exPy:"Liúchéng yì huán kòu yì huán, tíng yì tiān quán luàn.",exKo:"공정이 하나하나 물려 있어서 하루만 서도 전부 엉킵니다."},
  {zh:"没辙",py:"méizhé",ko:"어쩔 도리가 없다",
   ex:"他不肯签，我也没辙。",exPy:"Tā bù kěn qiān, wǒ yě méizhé.",exKo:"그가 서명을 안 하니 저도 방법이 없습니다."},
  {zh:"这话在理",py:"zhè huà zàilǐ",ko:"그 말이 이치에 맞다",
   ex:"你这话在理，我没什么可反驳的。",exPy:"Nǐ zhè huà zàilǐ, wǒ méi shénme kě fǎnbó de.",exKo:"그 말이 맞습니다, 반박할 게 없네요."},
  {zh:"V什么V",py:"V shénme V",ko:"~ 하긴 뭘 ~ 해",
   ex:"谢什么谢，都是自己人。",exPy:"Xiè shénme xiè, dōu shì zìjǐ rén.",exKo:"고맙긴 뭐가 고마워, 다 우리 사람인데."}
 ],
 out:[
  {q:"선물을 들고 병문안을 왔습니다. 늦게 온 것을 사과하며 자연스럽게 말을 여세요.",hint:"我来看看您 / 可别嫌我来得晚 / 心里一直惦记着"},
  {q:"환자가 회사 일을 걱정합니다. 걱정을 내 쪽으로 가져오며 안심시켜 보세요.",hint:"我们顶着呢 / 把心放肚子里 / 真有拿不准的我随时打电话"},
  {q:"환자가 다음에 또 오지 말라고 사양합니다. 받아들이되 다음을 기약해 보세요.",hint:"来什么来 / 等我出院 / 好好吃一顿"}
 ]
},
{
 id:"c3d2", day:17, cat:"연애·거절", level:"HSK 5~6",
 title:"相亲之后", titlePy:"xiāngqīn zhīhòu", titleKo:"맞선 뒤 — 상처 주지 않고 끝내기",
 names:{A:"小雨 (맞선 본 쪽)", B:"王姐 (소개해 준 선배)"},
 brief:[
  "중국에서 소개로 만난 자리는 <b>두 사람만의 일이 아닙니다</b>. 중간에서 다리를 놓아 준 사람이 있고, 그 사람의 체면이 걸려 있습니다. 그래서 거절할 때도 <b>소개자에게 먼저</b> 말하는 순서를 지킵니다.",
  "이 회차의 핵심은 王姐가 알려 주는 한 문장입니다. <b>말은 부드럽게, 뜻은 단단하게(话要说得软，意思要给得硬)</b>. 한국어의 「완곡하게」와 달리, 중국어의 거절은 부드러움과 명확함을 동시에 요구합니다.",
  "가장 흔한 실수는 <b>「그래도 친구로 지내요」</b>입니다. 듣기에는 예의 바르지만, 상대에게 <b>여지를 남겨 기다리게 만드는</b> 말입니다. 王姐는 이것을 <b>留活口</b>, 즉 숨통을 남겨 두는 일이라고 부릅니다.",
  "대신 권하는 방식은 <b>상대를 평가하지 않고 내 사정만 말하는 것</b>입니다. 그래야 상대도 반박할 자리가 없고, 관계도 상하지 않습니다. 거절 전반에 그대로 옮겨 쓸 수 있는 원칙입니다."
 ],
 vocab:[
  {w:"相亲",p:"xiāngqīn",m:"맞선을 보다",lv:"HSK6"},
  {w:"没得挑",p:"méide tiāo",m:"나무랄 데가 없다",lv:"구어"},
  {w:"表态",p:"biǎotài",m:"입장을 밝히다",lv:"HSK6"},
  {w:"牵线",p:"qiān xiàn",m:"다리를 놓다, 중매하다",lv:"구어"},
  {w:"敷衍",p:"fūyǎn",m:"건성으로 대하다",lv:"HSK6"},
  {w:"拐弯抹角",p:"guǎiwān mòjiǎo",m:"빙빙 돌려 말하다",lv:"성어"},
  {w:"显得",p:"xiǎnde",m:"~ 처럼 보이다",lv:"HSK5"},
  {w:"起头",p:"qǐtóu",m:"말문을 열다",lv:"구어"},
  {w:"余地",p:"yúdì",m:"여지",lv:"HSK6"},
  {w:"体面",p:"tǐmiàn",m:"번듯하다, 체면이 서다",lv:"HSK6"},
  {w:"心思",p:"xīnsi",m:"그럴 마음, 생각",lv:"HSK5"},
  {w:"留意",p:"liúyì",m:"눈여겨 살펴 두다",lv:"HSK5"}
 ],
 lines:[
  {s:"A",zh:"王姐，上回您介绍的那位，我想跟您说说我的想法。",py:"Wáng jiě, shàng huí nín jièshào de nà wèi, wǒ xiǎng gēn nín shuōshuo wǒ de xiǎngfǎ.",
   ko:"왕 언니, 지난번에 소개해 주신 그분 말인데요, 제 생각을 말씀드리고 싶어요.",
   ck:[["王姐，上回您介绍的那位","Wáng jiě, shàng huí nín jièshào de nà wèi"],["我想跟您说说我的想法","wǒ xiǎng gēn nín shuōshuo wǒ de xiǎngfǎ"]],
   notes:[{t:"那位",p:"nà wèi",k:"measure",m:"그분",tip:"位는 사람을 높여 세는 양사입니다. 那个人보다 훨씬 정중합니다."},
          {t:"说说我的想法",p:"shuōshuo wǒ de xiǎngfǎ",k:"expr",m:"제 생각을 좀 말씀드리다",tip:"동사 중첩이 무게를 덜어 어려운 말을 꺼내기 쉽게 만듭니다."}]},
  {s:"B",zh:"你说你说。我一看你这开场白，心里就有数了。",py:"Nǐ shuō nǐ shuō. Wǒ yí kàn nǐ zhè kāichǎngbái, xīnlǐ jiù yǒushù le.",
   ko:"말해 봐, 말해 봐. 그 서두 보자마자 나는 벌써 짐작이 갔어.",
   ck:[["你说你说","Nǐ shuō nǐ shuō"],["我一看你这开场白","wǒ yí kàn nǐ zhè kāichǎngbái"],["心里就有数了","xīnlǐ jiù yǒushù le"]],
   notes:[{t:"一…就…",p:"yí… jiù…",k:"grammar",m:"~ 하자마자 바로 ~",tip:"一看就知道 처럼 즉각적인 반응을 나타냅니다."},
          {t:"开场白",p:"kāichǎngbái",k:"word",m:"서두, 첫마디",tip:"말을 꺼내는 방식 자체를 가리킵니다. 你这开场白不对劲."}]},
  {s:"A",zh:"他人挺好的，条件也没得挑，就是聊起来总差那么点儿意思。",py:"Tā rén tǐng hǎo de, tiáojiàn yě méide tiāo, jiùshì liáo qǐlai zǒng chà nàme diǎnr yìsi.",
   ko:"사람은 참 좋고 조건도 나무랄 데가 없어요. 그런데 얘기를 나눠 보면 늘 뭔가 2퍼센트가 부족해요.",
   ck:[["他人挺好的","Tā rén tǐng hǎo de"],["条件也没得挑","tiáojiàn yě méide tiāo"],["就是聊起来","jiùshì liáo qǐlai"],["总差那么点儿意思","zǒng chà nàme diǎnr yìsi"]],
   notes:[{t:"没得挑",p:"méide tiāo",k:"expr",m:"나무랄 데가 없다",tip:"挑(고르다, 흠잡다)에서 왔습니다. 조건을 칭찬할 때의 상투구입니다."},
          {t:"差那么点儿意思",p:"chà nàme diǎnr yìsi",k:"idiom",m:"뭔가 조금 부족하다",tip:"설명하기 어려운 아쉬움을 말할 때 가장 자주 쓰는 표현입니다."}]},
  {s:"B",zh:"我懂。这种事强求不来，有没有那个感觉一顿饭就知道。",py:"Wǒ dǒng. Zhè zhǒng shì qiǎngqiú bu lái, yǒu méiyǒu nàge gǎnjué yí dùn fàn jiù zhīdào.",
   ko:"알지. 이런 건 억지로는 안 돼. 그 느낌이 있는지 없는지는 밥 한 끼면 알거든.",
   ck:[["我懂","Wǒ dǒng"],["这种事强求不来","zhè zhǒng shì qiǎngqiú bu lái"],["有没有那个感觉","yǒu méiyǒu nàge gǎnjué"],["一顿饭就知道","yí dùn fàn jiù zhīdào"]],
   notes:[{t:"强求不来",p:"qiǎngqiú bu lái",k:"grammar",m:"억지로 되는 게 아니다",tip:"가능보어입니다. 感情强求不来 는 연애 얘기의 정석 문장입니다."}]},
  {s:"A",zh:"就怕您为难。毕竟是您牵的线，我总不能拖着不表态。",py:"Jiù pà nín wéinán. Bìjìng shì nín qiān de xiàn, wǒ zǒng bù néng tuō zhe bù biǎotài.",
   ko:"언니가 곤란해지실까 봐요. 어쨌든 언니가 다리를 놓으신 건데, 계속 미루며 입장을 안 밝힐 수는 없잖아요.",
   ck:[["就怕您为难","Jiù pà nín wéinán"],["毕竟是您牵的线","bìjìng shì nín qiān de xiàn"],["我总不能拖着不表态","wǒ zǒng bù néng tuō zhe bù biǎotài"]],
   notes:[{t:"牵线",p:"qiān xiàn",k:"word",m:"다리를 놓다",tip:"牵线搭桥 로 붙여 쓰기도 합니다. 중매와 소개 전반에 씁니다."},
          {t:"表态",p:"biǎotài",k:"word",m:"입장을 밝히다",tip:"찬성인지 반대인지 분명히 말하는 것입니다. 你得表个态."}]},
  {s:"B",zh:"为难什么呀。我给你们搭个桥，走不走是你们自己的事。",py:"Wéinán shénme ya. Wǒ gěi nǐmen dā ge qiáo, zǒu bu zǒu shì nǐmen zìjǐ de shì.",
   ko:"곤란하긴 뭐가 곤란해. 나는 다리만 놓아 준 거고, 건널지 말지는 너희 일이지.",
   ck:[["为难什么呀","Wéinán shénme ya"],["我给你们搭个桥","wǒ gěi nǐmen dā ge qiáo"],["走不走是你们自己的事","zǒu bu zǒu shì nǐmen zìjǐ de shì"]],
   notes:[{t:"搭桥",p:"dā qiáo",k:"idiom",m:"다리를 놓아 주다",tip:"牵线과 짝을 이루는 비유입니다. 여기서는 책임의 선을 긋고 있습니다."},
          {t:"走不走",p:"zǒu bu zǒu",k:"grammar",m:"갈지 말지",tip:"V不V 형태로 선택 자체를 명사처럼 씁니다."}]},
  {s:"A",zh:"那我心里就踏实了。您说我该怎么跟他说，才不至于太伤人？",py:"Nà wǒ xīnlǐ jiù tāshi le. Nín shuō wǒ gāi zěnme gēn tā shuō, cái bú zhìyú tài shāng rén?",
   ko:"그럼 마음이 좀 놓이네요. 그에게 어떻게 말해야 너무 상처 주지 않을까요?",
   ck:[["那我心里就踏实了","Nà wǒ xīnlǐ jiù tāshi le"],["您说我该怎么跟他说","nín shuō wǒ gāi zěnme gēn tā shuō"],["才不至于太伤人","cái bú zhìyú tài shāng rén"]],
   notes:[{t:"踏实",p:"tāshi",k:"word",m:"마음이 놓이다",tip:"성실하다는 뜻도 있습니다. 여기서는 불안이 가신 상태입니다."},
          {t:"不至于",p:"bú zhìyú",k:"grammar",m:"~ 할 정도까지는 아니다",tip:"과한 결과를 막을 때 씁니다. 不至于那么严重."}]},
  {s:"B",zh:"别绕弯子，也别找借口。越拐弯抹角，人家越觉得你在敷衍。",py:"Bié rào wānzi, yě bié zhǎo jièkǒu. Yuè guǎiwān mòjiǎo, rénjia yuè juéde nǐ zài fūyǎn.",
   ko:"빙빙 돌리지도 말고 핑계도 대지 마. 돌려 말할수록 상대는 네가 건성이라고 느껴.",
   ck:[["别绕弯子，也别找借口","Bié rào wānzi, yě bié zhǎo jièkǒu"],["越拐弯抹角","yuè guǎiwān mòjiǎo"],["人家越觉得你在敷衍","rénjia yuè juéde nǐ zài fūyǎn"]],
   notes:[{t:"拐弯抹角",p:"guǎiwān mòjiǎo",k:"idiom",m:"빙빙 돌려 말하다",tip:"성어입니다. 有话直说，别拐弯抹角."},
          {t:"敷衍",p:"fūyǎn",k:"word",m:"건성으로 대하다",tip:"敷衍了事 = 대충 해치우다. 성의 없음을 지적하는 강한 말입니다."}]},
  {s:"A",zh:"那我直接说不合适？会不会显得我太不给面子了。",py:"Nà wǒ zhíjiē shuō bù héshì? Huì bu huì xiǎnde wǒ tài bù gěi miànzi le.",
   ko:"그럼 그냥 안 맞는다고 해요? 너무 체면 안 세워 주는 것처럼 보이지 않을까요?",
   ck:[["那我直接说不合适","Nà wǒ zhíjiē shuō bù héshì"],["会不会显得我","huì bu huì xiǎnde wǒ"],["太不给面子了","tài bù gěi miànzi le"]],
   notes:[{t:"显得",p:"xiǎnde",k:"word",m:"~ 처럼 보이다",tip:"看起来가 관찰이라면 显得는 「그런 인상을 준다」에 가깝습니다."},
          {t:"不给面子",p:"bù gěi miànzi",k:"culture",m:"체면을 세워 주지 않다",tip:"중국어 인간관계에서 가장 무거운 비난 중 하나입니다."}]},
  {s:"B",zh:"话要说得软，意思要给得硬。这两句你记住就够用了。",py:"Huà yào shuō de ruǎn, yìsi yào gěi de yìng. Zhè liǎng jù nǐ jìzhù jiù gòu yòng le.",
   ko:"말은 부드럽게 하되, 뜻은 단단하게 줘야 해. 이 두 마디만 기억하면 충분해.",
   ck:[["话要说得软","Huà yào shuō de ruǎn"],["意思要给得硬","yìsi yào gěi de yìng"],["这两句你记住就够用了","zhè liǎng jù nǐ jìzhù jiù gòu yòng le"]],
   notes:[{t:"说得软，给得硬",p:"shuō de ruǎn, gěi de yìng",k:"idiom",m:"말은 부드럽게, 뜻은 단단하게",tip:"거절의 원칙을 여섯 글자로 압축한 말입니다. 그대로 외워 두세요."},
          {t:"够用",p:"gòu yòng",k:"expr",m:"쓰기에 충분하다",tip:"够 + 동사 형태입니다. 钱够花 / 时间够用."}]},
  {s:"A",zh:"说得软，给得硬。那具体一点，我第一句话该怎么起头？",py:"Shuō de ruǎn, gěi de yìng. Nà jùtǐ yìdiǎn, wǒ dì yī jù huà gāi zěnme qǐtóu?",
   ko:"부드럽게 말하고 단단하게 주기. 좀 더 구체적으로요, 첫마디는 어떻게 떼야 해요?",
   ck:[["说得软，给得硬","Shuō de ruǎn, gěi de yìng"],["那具体一点","nà jùtǐ yìdiǎn"],["我第一句话该怎么起头","wǒ dì yī jù huà gāi zěnme qǐtóu"]],
   notes:[{t:"起头",p:"qǐtóu",k:"word",m:"말문을 열다",tip:"开头가 시작 부분이라면 起头는 먼저 입을 떼는 행위입니다."}]},
  {s:"B",zh:"先谢人家的时间，再说自己的问题，最后别留活口。",py:"Xiān xiè rénjia de shíjiān, zài shuō zìjǐ de wèntí, zuìhòu bié liú huókǒu.",
   ko:"먼저 상대의 시간에 고마워하고, 다음으로 네 사정을 말하고, 마지막에 여지를 남기지 마.",
   ck:[["先谢人家的时间","Xiān xiè rénjia de shíjiān"],["再说自己的问题","zài shuō zìjǐ de wèntí"],["最后别留活口","zuìhòu bié liú huókǒu"]],
   notes:[{t:"先…再…最后…",p:"xiān… zài… zuìhòu…",k:"grammar",m:"먼저 ~ 하고, 다음에 ~ 하고, 마지막에 ~",tip:"절차를 세 걸음으로 지시하는 기본 골격입니다."},
          {t:"留活口",p:"liú huókǒu",k:"idiom",m:"여지를 남기다, 숨통을 터 두다",tip:"원래는 살려 두다라는 뜻입니다. 여기서는 기대를 남기는 것을 가리킵니다."}]},
  {s:"A",zh:"不留活口是什么意思？总得留点余地吧。",py:"Bù liú huókǒu shì shénme yìsi? Zǒng děi liú diǎn yúdì ba.",
   ko:"여지를 남기지 말라는 게 무슨 뜻이에요? 그래도 조금은 남겨야 하지 않나요?",
   ck:[["不留活口是什么意思","Bù liú huókǒu shì shénme yìsi"],["总得留点余地吧","zǒng děi liú diǎn yúdì ba"]],
   notes:[{t:"总得…吧",p:"zǒng děi… ba",k:"grammar",m:"그래도 ~ 해야 하지 않나요",tip:"상식에 호소하며 부드럽게 반문하는 골격입니다."}]},
  {s:"B",zh:"余地留给感情，不留给误会。你说以后做朋友，他就还等着。",py:"Yúdì liú gěi gǎnqíng, bù liú gěi wùhuì. Nǐ shuō yǐhòu zuò péngyou, tā jiù hái děng zhe.",
   ko:"여지는 감정에 남기는 거지 오해에 남기는 게 아니야. 나중에 친구로 지내자고 하면, 그 사람은 계속 기다려.",
   ck:[["余地留给感情，不留给误会","Yúdì liú gěi gǎnqíng, bù liú gěi wùhuì"],["你说以后做朋友","nǐ shuō yǐhòu zuò péngyou"],["他就还等着","tā jiù hái děng zhe"]],
   notes:[{t:"留给",p:"liú gěi",k:"grammar",m:"~ 에게 남겨 두다",tip:"동사 + 给 로 대상을 붙입니다. 留给你 / 说给他听."}]},
  {s:"A",zh:"这我还真没想到。我本来打算说大家还是朋友。",py:"Zhè wǒ hái zhēn méi xiǎngdào. Wǒ běnlái dǎsuàn shuō dàjiā háishi péngyou.",
   ko:"그건 정말 생각 못 했어요. 원래는 그래도 친구로 지내자고 하려고 했거든요.",
   ck:[["这我还真没想到","Zhè wǒ hái zhēn méi xiǎngdào"],["我本来打算说","wǒ běnlái dǎsuàn shuō"],["大家还是朋友","dàjiā háishi péngyou"]],
   notes:[{t:"还真",p:"hái zhēn",k:"expr",m:"정말이지, 의외로",tip:"예상 밖이라는 놀람을 담습니다. 这个还真不好办."}]},
  {s:"B",zh:"那句话最害人。听着体面，实际上把话头留在那儿了。",py:"Nà jù huà zuì hài rén. Tīng zhe tǐmiàn, shíjìshang bǎ huàtóu liú zài nàr le.",
   ko:"그 말이 제일 사람 잡아. 듣기엔 번듯한데, 실은 말꼬리를 거기 남겨 둔 거야.",
   ck:[["那句话最害人","Nà jù huà zuì hài rén"],["听着体面","tīng zhe tǐmiàn"],["实际上把话头留在那儿了","shíjìshang bǎ huàtóu liú zài nàr le"]],
   notes:[{t:"害人",p:"hài rén",k:"expr",m:"사람 잡다, 사람을 곤란하게 만들다",tip:"가볍게 쓰면 「고약하다」 정도의 뉘앙스입니다."},
          {t:"把话头留在那儿",p:"bǎ huàtóu liú zài nàr",k:"grammar",m:"말꼬리를 남겨 두다",tip:"把자문입니다. 무엇을 어디에 두었는지가 초점입니다."}]},
  {s:"A",zh:"明白了。那我就说自己最近没那个心思，让他别等。",py:"Míngbai le. Nà wǒ jiù shuō zìjǐ zuìjìn méi nàge xīnsi, ràng tā bié děng.",
   ko:"알겠어요. 그럼 요즘 제가 그럴 마음이 아니라고 말하고, 기다리지 말라고 할게요.",
   ck:[["明白了","Míngbai le"],["那我就说","nà wǒ jiù shuō"],["自己最近没那个心思","zìjǐ zuìjìn méi nàge xīnsi"],["让他别等","ràng tā bié děng"]],
   notes:[{t:"没那个心思",p:"méi nàge xīnsi",k:"expr",m:"그럴 마음이 아니다",tip:"상대를 평가하지 않고 내 상태만 말하는 가장 안전한 거절입니다."}]},
  {s:"B",zh:"这就对了。说自己的事，不评价人家，谁也挑不出理来。",py:"Zhè jiù duì le. Shuō zìjǐ de shì, bù píngjià rénjia, shéi yě tiāo bu chū lǐ lái.",
   ko:"그래야지. 내 얘기만 하고 상대를 평가하지 않으면, 누구도 트집 잡을 게 없어.",
   ck:[["这就对了","Zhè jiù duì le"],["说自己的事，不评价人家","shuō zìjǐ de shì, bù píngjià rénjia"],["谁也挑不出理来","shéi yě tiāo bu chū lǐ lái"]],
   notes:[{t:"挑不出理来",p:"tiāo bu chū lǐ lái",k:"grammar",m:"트집 잡을 데가 없다",tip:"가능보어 + 来 입니다. 挑理 = 흠을 잡다."},
          {t:"这就对了",p:"Zhè jiù duì le",k:"expr",m:"그래야지, 바로 그거야",tip:"상대가 제대로 이해했을 때의 짧은 칭찬입니다."}]},
  {s:"A",zh:"那我今晚就发消息。王姐，这回真是麻烦您了。",py:"Nà wǒ jīnwǎn jiù fā xiāoxi. Wáng jiě, zhè huí zhēnshi máfan nín le.",
   ko:"그럼 오늘 밤에 바로 메시지 보낼게요. 언니, 이번에 정말 번거롭게 해 드렸네요.",
   ck:[["那我今晚就发消息","Nà wǒ jīnwǎn jiù fā xiāoxi"],["王姐，这回真是麻烦您了","Wáng jiě, zhè huí zhēnshi máfan nín le"]],
   notes:[{t:"麻烦您了",p:"máfan nín le",k:"expr",m:"번거롭게 해 드렸습니다",tip:"부탁이 끝난 뒤의 표준 마무리 인사입니다."}]},
  {s:"B",zh:"麻烦什么。下回我再给你留意着，合适的总会碰上。",py:"Máfan shénme. Xià huí wǒ zài gěi nǐ liúyì zhe, héshì de zǒng huì pèng shàng.",
   ko:"번거롭긴 뭐가. 다음에 또 눈여겨봐 줄게. 맞는 사람은 언젠가 만나게 돼 있어.",
   ck:[["麻烦什么","Máfan shénme"],["下回我再给你留意着","xià huí wǒ zài gěi nǐ liúyì zhe"],["合适的总会碰上","héshì de zǒng huì pèng shàng"]],
   notes:[{t:"留意着",p:"liúyì zhe",k:"word",m:"눈여겨 살펴 두다",tip:"着가 붙어 계속 신경 쓰고 있겠다는 뜻이 됩니다."},
          {t:"碰上",p:"pèng shàng",k:"word",m:"우연히 마주치다",tip:"의도하지 않은 만남입니다. 碰上了老同学."}]}
 ],
 keys:[
  {zh:"没得挑",py:"méide tiāo",ko:"나무랄 데가 없다",
   ex:"这房子位置没得挑，就是贵。",exPy:"Zhè fángzi wèizhì méide tiāo, jiùshì guì.",exKo:"이 집은 위치가 나무랄 데 없어요, 비싼 게 흠이지."},
  {zh:"差那么点儿意思",py:"chà nàme diǎnr yìsi",ko:"뭔가 조금 부족하다",
   ex:"菜做得不错，就是差那么点儿意思。",exPy:"Cài zuò de búcuò, jiùshì chà nàme diǎnr yìsi.",exKo:"요리는 괜찮은데, 뭔가 2퍼센트가 부족해요."},
  {zh:"强求不来",py:"qiǎngqiú bu lái",ko:"억지로는 되지 않는다",
   ex:"缘分这东西强求不来。",exPy:"Yuánfèn zhè dōngxi qiǎngqiú bu lái.",exKo:"인연이라는 건 억지로 되는 게 아닙니다."},
  {zh:"牵线",py:"qiān xiàn",ko:"다리를 놓다",
   ex:"这单生意是他给牵的线。",exPy:"Zhè dān shēngyi shì tā gěi qiān de xiàn.",exKo:"이 거래는 그가 다리를 놓아 준 겁니다."},
  {zh:"拐弯抹角",py:"guǎiwān mòjiǎo",ko:"빙빙 돌려 말하다",
   ex:"有话直说，别拐弯抹角。",exPy:"Yǒu huà zhí shuō, bié guǎiwān mòjiǎo.",exKo:"할 말 있으면 바로 하세요, 돌려 말하지 말고."},
  {zh:"说得软，给得硬",py:"shuō de ruǎn, gěi de yìng",ko:"말은 부드럽게, 뜻은 단단하게",
   ex:"拒绝的时候要说得软，给得硬。",exPy:"Jùjué de shíhou yào shuō de ruǎn, gěi de yìng.",exKo:"거절할 때는 말은 부드럽게 하고 뜻은 단단하게 줘야 합니다."},
  {zh:"留活口",py:"liú huókǒu",ko:"여지를 남기다, 기대를 남기다",
   ex:"这话别留活口，不然他还等着。",exPy:"Zhè huà bié liú huókǒu, bùrán tā hái děng zhe.",exKo:"이 말에 여지를 남기지 마세요, 안 그러면 계속 기다립니다."},
  {zh:"挑不出理来",py:"tiāo bu chū lǐ lái",ko:"트집 잡을 데가 없다",
   ex:"你这么说，谁也挑不出理来。",exPy:"Nǐ zhème shuō, shéi yě tiāo bu chū lǐ lái.",exKo:"그렇게 말하면 누구도 트집 잡을 게 없습니다."}
 ],
 out:[
  {q:"소개해 준 사람에게 「안 될 것 같다」고 먼저 알려야 합니다. 상대를 깎지 않으면서 말해 보세요.",hint:"条件没得挑 / 差那么点儿意思 / 强求不来"},
  {q:"소개자가 곤란해할까 걱정됩니다. 그 마음을 먼저 꺼내 보세요.",hint:"就怕您为难 / 是您牵的线 / 总不能拖着不表态"},
  {q:"상대 본인에게 직접 거절해야 합니다. 세 걸음 순서대로 말해 보세요.",hint:"先谢人家的时间 / 没那个心思 / 别留活口"}
 ]
},
{
 id:"c3d3", day:18, cat:"육아·비교", level:"HSK 5~6",
 title:"别人家的孩子", titlePy:"biérén jiā de háizi", titleKo:"남의 집 아이 — 비교 앞에서 버티기",
 names:{A:"李姐 (성적 좋은 아이의 엄마)", B:"小周 (평범한 아이의 아빠)"},
 brief:[
  "<b>别人家的孩子</b>는 중국 가정에서 가장 자주 등장하는 유령입니다. 늘 우리 아이보다 잘하고, 늘 누군가의 입을 통해 옵니다. 학교 앞이든 학부모 단톡방이든, 이 비교가 시작되면 대화의 온도가 바뀝니다.",
  "이 회차의 A는 <b>비교의 가해자처럼 보이지만 실은 아닙니다</b>. 자기 아이도 성적이 떨어졌다고 먼저 털어놓고, 단톡방을 음소거해 두었다고 말합니다. 중국어에서 겸양이 어떻게 관계의 긴장을 푸는지 보여 줍니다.",
  "핵심은 B의 한마디입니다. <b>站着说话不腰疼</b> — 남의 일이니 쉽게 말한다는 속담입니다. 무례하지 않게 반박하는 말이며, 상대가 이걸 받아치는 방식도 함께 배웁니다.",
  "마지막에 나오는 제안이 이 대화의 값어치입니다. 아이가 원하는 것을 <b>허락</b>이 아니라 <b>기한을 정해 한번 들어 주는 것</b>으로 바꾸는 방법입니다. 거절과 허용 사이에 제3의 선택지를 만드는 화법입니다."
 ],
 vocab:[
  {w:"月考",p:"yuèkǎo",m:"월례 시험",lv:"구어"},
  {w:"中游",p:"zhōngyóu",m:"중간 수준",lv:"HSK6"},
  {w:"长处",p:"chángchu",m:"장점",lv:"HSK5"},
  {w:"较劲",p:"jiàojìn",m:"기를 쓰고 겨루다",lv:"구어"},
  {w:"争气",p:"zhēngqì",m:"기대에 부응해 잘하다",lv:"HSK6"},
  {w:"看得开",p:"kàn de kāi",m:"대범하게 넘기다",lv:"구어"},
  {w:"顶嘴",p:"dǐngzuǐ",m:"말대꾸하다",lv:"구어"},
  {w:"招",p:"zhāo",m:"수, 방법",lv:"구어"},
  {w:"来气",p:"láiqì",m:"화가 치밀다",lv:"구어"},
  {w:"期限",p:"qīxiàn",m:"기한",lv:"HSK5"},
  {w:"回绝",p:"huíjué",m:"거절하다",lv:"HSK6"},
  {w:"挨训",p:"ái xùn",m:"꾸지람을 듣다",lv:"구어"}
 ],
 lines:[
  {s:"A",zh:"小周，这回月考出来了吧？你们家孩子考得怎么样？",py:"Xiǎo Zhōu, zhè huí yuèkǎo chūlai le ba? Nǐmen jiā háizi kǎo de zěnmeyàng?",
   ko:"샤오저우, 이번 월례고사 나왔죠? 댁의 아이는 어떻게 봤어요?",
   ck:[["小周，这回月考出来了吧","Xiǎo Zhōu, zhè huí yuèkǎo chūlai le ba"],["你们家孩子考得怎么样","nǐmen jiā háizi kǎo de zěnmeyàng"]],
   notes:[{t:"你们家孩子",p:"nǐmen jiā háizi",k:"culture",m:"댁의 아이",tip:"我们家 / 你们家는 가족을 가리킬 때의 관용적 소유 표현입니다."},
          {t:"考得怎么样",p:"kǎo de zěnmeyàng",k:"grammar",m:"시험을 어떻게 봤는가",tip:"동사 + 得 + 정도보어로 결과를 묻는 기본 형태입니다."}]},
  {s:"B",zh:"就那样吧，中游偏上。李姐您家女儿肯定又是年级前几名。",py:"Jiù nàyàng ba, zhōngyóu piān shàng. Lǐ jiě nín jiā nǚ'ér kěndìng yòu shì niánjí qián jǐ míng.",
   ko:"그냥 그렇죠, 중간보다 조금 위요. 리 언니네 따님은 또 학년 상위권이겠죠.",
   ck:[["就那样吧，中游偏上","Jiù nàyàng ba, zhōngyóu piān shàng"],["李姐您家女儿","Lǐ jiě nín jiā nǚ'ér"],["肯定又是年级前几名","kěndìng yòu shì niánjí qián jǐ míng"]],
   notes:[{t:"就那样吧",p:"jiù nàyàng ba",k:"expr",m:"그냥 그렇죠",tip:"성적이나 상태를 얼버무릴 때의 방어적인 답입니다."},
          {t:"中游偏上",p:"zhōngyóu piān shàng",k:"expr",m:"중간보다 조금 위",tip:"偏上 / 偏下로 위치를 미세하게 조정합니다."}]},
  {s:"A",zh:"哪有啊，这次退了三名，回家我说了她两句。",py:"Nǎ yǒu a, zhè cì tuì le sān míng, huí jiā wǒ shuō le tā liǎng jù.",
   ko:"무슨요, 이번엔 세 등수 떨어져서 집에서 한 소리 했어요.",
   ck:[["哪有啊","Nǎ yǒu a"],["这次退了三名","zhè cì tuì le sān míng"],["回家我说了她两句","huí jiā wǒ shuō le tā liǎng jù"]],
   notes:[{t:"哪有啊",p:"Nǎ yǒu a",k:"expr",m:"무슨요, 그런 거 아니에요",tip:"칭찬을 받아넘기는 겸양의 첫마디입니다."},
          {t:"说两句",p:"shuō liǎng jù",k:"expr",m:"한 소리 하다, 나무라다",tip:"가볍게 꾸짖었다는 완곡한 표현입니다."}]},
  {s:"B",zh:"退三名还算退啊？我们家要是能进前三十，我能高兴半个月。",py:"Tuì sān míng hái suàn tuì a? Wǒmen jiā yàoshi néng jìn qián sānshí, wǒ néng gāoxìng bàn ge yuè.",
   ko:"세 등수 떨어진 게 떨어진 건가요? 우리 애가 30등 안에만 들면 저는 보름은 좋아할 겁니다.",
   ck:[["退三名还算退啊","Tuì sān míng hái suàn tuì a"],["我们家要是能进前三十","wǒmen jiā yàoshi néng jìn qián sānshí"],["我能高兴半个月","wǒ néng gāoxìng bàn ge yuè"]],
   notes:[{t:"还算…啊",p:"hái suàn… a",k:"grammar",m:"그게 ~ 축에 드나요",tip:"상대의 엄살을 가볍게 되받는 반문입니다."},
          {t:"要是…",p:"yàoshi…",k:"grammar",m:"만약 ~ 라면",tip:"如果보다 구어적입니다. 뒤에 就를 붙이는 일이 많습니다."}]},
  {s:"A",zh:"你别这么说。孩子各有各的长处，成绩不能说明一切。",py:"Nǐ bié zhème shuō. Háizi gè yǒu gè de chángchu, chéngjì bù néng shuōmíng yíqiè.",
   ko:"그런 말 마세요. 아이마다 제각기 장점이 있고, 성적이 전부를 말해 주진 않아요.",
   ck:[["你别这么说","Nǐ bié zhème shuō"],["孩子各有各的长处","háizi gè yǒu gè de chángchu"],["成绩不能说明一切","chéngjì bù néng shuōmíng yíqiè"]],
   notes:[{t:"各有各的…",p:"gè yǒu gè de…",k:"grammar",m:"제각기 자기 나름의 ~ 가 있다",tip:"各有各的难处 / 各有各的活法 처럼 통째로 씁니다."}]},
  {s:"B",zh:"道理谁都懂，可一到家长群里，我这心就沉下去了。",py:"Dàolǐ shéi dōu dǒng, kě yí dào jiāzhǎng qún lǐ, wǒ zhè xīn jiù chén xiàqù le.",
   ko:"이치야 누구나 알죠. 그런데 학부모 단톡방만 들어가면 마음이 가라앉아요.",
   ck:[["道理谁都懂","Dàolǐ shéi dōu dǒng"],["可一到家长群里","kě yí dào jiāzhǎng qún lǐ"],["我这心就沉下去了","wǒ zhè xīn jiù chén xiàqù le"]],
   notes:[{t:"道理谁都懂",p:"dàolǐ shéi dōu dǒng",k:"expr",m:"이치야 누구나 안다",tip:"머리로는 알지만 마음이 안 따른다는 말의 서두입니다."},
          {t:"心沉下去",p:"xīn chén xiàqù",k:"expr",m:"마음이 가라앉다",tip:"기분이 무거워지는 감각을 그대로 옮긴 표현입니다."}]},
  {s:"A",zh:"那个群我早就设静音了。看多了只会自己跟自己较劲。",py:"Nàge qún wǒ zǎo jiù shè jìngyīn le. Kàn duō le zhǐ huì zìjǐ gēn zìjǐ jiàojìn.",
   ko:"그 단톡방은 저도 진작 음소거했어요. 많이 볼수록 자기 자신과 씨름만 하게 되거든요.",
   ck:[["那个群我早就设静音了","Nàge qún wǒ zǎo jiù shè jìngyīn le"],["看多了只会","kàn duō le zhǐ huì"],["自己跟自己较劲","zìjǐ gēn zìjǐ jiàojìn"]],
   notes:[{t:"跟自己较劲",p:"gēn zìjǐ jiàojìn",k:"idiom",m:"스스로와 씨름하다",tip:"남이 아니라 자기 안에서 괴로워하는 상태입니다."},
          {t:"设静音",p:"shè jìngyīn",k:"word",m:"무음으로 설정하다",tip:"단톡방 이야기에서 거의 반드시 나오는 표현입니다."}]},
  {s:"B",zh:"您是站着说话不腰疼。您家孩子争气，您当然看得开。",py:"Nín shì zhàn zhe shuōhuà bù yāoténg. Nín jiā háizi zhēngqì, nín dāngrán kàn de kāi.",
   ko:"언니는 남의 일이라 쉽게 말씀하시는 거죠. 댁의 아이가 잘해 주니 당연히 대범해지시고요.",
   ck:[["您是站着说话不腰疼","Nín shì zhàn zhe shuōhuà bù yāoténg"],["您家孩子争气","nín jiā háizi zhēngqì"],["您当然看得开","nín dāngrán kàn de kāi"]],
   notes:[{t:"站着说话不腰疼",p:"zhàn zhe shuōhuà bù yāoténg",k:"idiom",m:"남의 일이라 쉽게 말한다",tip:"서서 말하는 사람은 허리가 안 아프다는 속담입니다. 친한 사이에서만 쓰세요."},
          {t:"看得开",p:"kàn de kāi",k:"grammar",m:"대범하게 넘길 수 있다",tip:"가능보어입니다. 반대는 看不开(집착을 못 놓다)입니다."}]},
  {s:"A",zh:"这话说得。我家那位在外人面前风光，在家也天天挨我训。",py:"Zhè huà shuō de. Wǒ jiā nà wèi zài wàirén miànqián fēngguāng, zài jiā yě tiāntiān ái wǒ xùn.",
   ko:"말씀 한번 하시네요. 우리 애도 밖에서나 번듯하지, 집에서는 날마다 저한테 혼나요.",
   ck:[["这话说得","Zhè huà shuō de"],["我家那位在外人面前风光","wǒ jiā nà wèi zài wàirén miànqián fēngguāng"],["在家也天天挨我训","zài jiā yě tiāntiān ái wǒ xùn"]],
   notes:[{t:"这话说得",p:"zhè huà shuō de",k:"expr",m:"말씀 한번 하시네요",tip:"뼈 있는 말을 받았을 때의 반쯤 인정하는 반응입니다."},
          {t:"挨训",p:"ái xùn",k:"word",m:"꾸지람을 듣다",tip:"挨는 원치 않는 일을 당하는 것입니다. 挨骂 / 挨打 / 挨批评."}]},
  {s:"B",zh:"那也是您会管。我一说他就顶嘴，说多了连门都不出。",py:"Nà yě shì nín huì guǎn. Wǒ yì shuō tā jiù dǐngzuǐ, shuō duō le lián mén dōu bù chū.",
   ko:"그것도 언니가 잘 다루시니까요. 저는 한마디 하면 바로 말대꾸하고, 많이 하면 방에서 나오지도 않아요.",
   ck:[["那也是您会管","Nà yě shì nín huì guǎn"],["我一说他就顶嘴","wǒ yì shuō tā jiù dǐngzuǐ"],["说多了连门都不出","shuō duō le lián mén dōu bù chū"]],
   notes:[{t:"会管",p:"huì guǎn",k:"expr",m:"잘 다룰 줄 안다",tip:"会 + 동사는 요령이 있다는 뜻입니다. 会说话 / 会办事."},
          {t:"顶嘴",p:"dǐngzuǐ",k:"word",m:"말대꾸하다",tip:"윗사람에게만 씁니다. 대등한 사이에는 顶回去라고 합니다."}]},
  {s:"A",zh:"这个年纪都这样。你越推他越往后缩，不如换个法子。",py:"Zhège niánjì dōu zhèyàng. Nǐ yuè tuī tā yuè wǎng hòu suō, bùrú huàn ge fǎzi.",
   ko:"그 나이엔 다 그래요. 밀수록 뒤로 움츠러드니까, 방법을 바꾸는 편이 나아요.",
   ck:[["这个年纪都这样","Zhège niánjì dōu zhèyàng"],["你越推他越往后缩","nǐ yuè tuī tā yuè wǎng hòu suō"],["不如换个法子","bùrú huàn ge fǎzi"]],
   notes:[{t:"不如…",p:"bùrú…",k:"grammar",m:"차라리 ~ 하는 편이 낫다",tip:"A不如B(A보다 B가 낫다)에서 온 제안 형식입니다."},
          {t:"法子",p:"fǎzi",k:"word",m:"방법",tip:"办法의 구어형입니다. 想个法子 = 방법을 궁리하다."}]},
  {s:"B",zh:"换什么法子？我能想的招都想遍了，钱也没少花。",py:"Huàn shénme fǎzi? Wǒ néng xiǎng de zhāo dōu xiǎng biàn le, qián yě méi shǎo huā.",
   ko:"무슨 방법을 바꿔요? 생각할 수 있는 수는 다 써 봤고, 돈도 적잖이 썼어요.",
   ck:[["换什么法子","Huàn shénme fǎzi"],["我能想的招都想遍了","wǒ néng xiǎng de zhāo dōu xiǎng biàn le"],["钱也没少花","qián yě méi shǎo huā"]],
   notes:[{t:"招",p:"zhāo",k:"word",m:"수, 방책",tip:"원래 무술의 초식입니다. 这一招真管用 = 이 수가 제대로 통한다."},
          {t:"没少…",p:"méi shǎo…",k:"grammar",m:"적잖이 ~ 했다",tip:"이중부정으로 많음을 강조합니다. 没少操心 / 没少挨骂."}]},
  {s:"A",zh:"钱花在补习上最没用。不如先问问他自己想要什么。",py:"Qián huā zài bǔxí shàng zuì méiyòng. Bùrú xiān wènwen tā zìjǐ xiǎng yào shénme.",
   ko:"돈을 학원에 쓰는 게 제일 소용없어요. 먼저 본인이 뭘 원하는지 물어보는 편이 나아요.",
   ck:[["钱花在补习上最没用","Qián huā zài bǔxí shàng zuì méiyòng"],["不如先问问","bùrú xiān wènwen"],["他自己想要什么","tā zìjǐ xiǎng yào shénme"]],
   notes:[{t:"花在…上",p:"huā zài… shàng",k:"grammar",m:"~ 에 (돈·시간을) 쓰다",tip:"花在孩子身上 / 时间花在这上面."}]},
  {s:"B",zh:"问过。他说想学画画，我一听就来气，那能当饭吃吗？",py:"Wèn guo. Tā shuō xiǎng xué huàhuà, wǒ yì tīng jiù láiqì, nà néng dāng fàn chī ma?",
   ko:"물어봤죠. 그림을 배우고 싶다길래 듣자마자 화가 났어요. 그게 밥이 됩니까?",
   ck:[["问过","Wèn guo"],["他说想学画画","tā shuō xiǎng xué huàhuà"],["我一听就来气","wǒ yì tīng jiù láiqì"],["那能当饭吃吗","nà néng dāng fàn chī ma"]],
   notes:[{t:"来气",p:"láiqì",k:"word",m:"화가 치밀다",tip:"生气보다 순간적이고 구어적입니다. 一想起来就来气."},
          {t:"当饭吃",p:"dāng fàn chī",k:"idiom",m:"밥벌이가 되다",tip:"这不能当饭吃 = 그걸로는 먹고살 수 없다. 현실론의 상투구입니다."}]},
  {s:"A",zh:"能不能当饭吃，得看他能走到哪一步，现在下结论太早。",py:"Néng bu néng dāng fàn chī, děi kàn tā néng zǒu dào nǎ yí bù, xiànzài xià jiélùn tài zǎo.",
   ko:"밥이 되느냐 마느냐는 그 아이가 어디까지 가느냐에 달렸죠. 지금 결론 내리긴 일러요.",
   ck:[["能不能当饭吃","Néng bu néng dāng fàn chī"],["得看他能走到哪一步","děi kàn tā néng zǒu dào nǎ yí bù"],["现在下结论太早","xiànzài xià jiélùn tài zǎo"]],
   notes:[{t:"得看…",p:"děi kàn…",k:"grammar",m:"~ 에 달려 있다",tip:"那得看情况 처럼 조건을 다는 기본 골격입니다."},
          {t:"下结论",p:"xià jiélùn",k:"expr",m:"결론을 내리다",tip:"下决心 / 下定义와 같은 계열의 동사 배합입니다."}]},
  {s:"B",zh:"说是这么说，万一走不通呢？我可耗不起那几年。",py:"Shuō shì zhème shuō, wànyī zǒu bu tōng ne? Wǒ kě hào bu qǐ nà jǐ nián.",
   ko:"말이야 그렇죠. 그런데 만에 하나 안 풀리면요? 저는 그 몇 년을 버릴 여유가 없어요.",
   ck:[["说是这么说","Shuō shì zhème shuō"],["万一走不通呢","wànyī zǒu bu tōng ne"],["我可耗不起那几年","wǒ kě hào bu qǐ nà jǐ nián"]],
   notes:[{t:"万一…呢",p:"wànyī… ne",k:"grammar",m:"만에 하나 ~ 하면요",tip:"최악의 경우를 꺼내 반박하는 형식입니다."},
          {t:"耗不起",p:"hào bu qǐ",k:"grammar",m:"(시간·돈을) 감당할 여유가 없다",tip:"가능보어입니다. 耗는 소모하며 버티는 것입니다."}]},
  {s:"A",zh:"那就给他定个期限。两年内出不来成绩，再回头也不迟。",py:"Nà jiù gěi tā dìng ge qīxiàn. Liǎng nián nèi chū bu lái chéngjì, zài huítóu yě bù chí.",
   ko:"그럼 기한을 정해 주세요. 2년 안에 성과가 안 나오면 그때 돌아서도 늦지 않아요.",
   ck:[["那就给他定个期限","Nà jiù gěi tā dìng ge qīxiàn"],["两年内出不来成绩","liǎng nián nèi chū bu lái chéngjì"],["再回头也不迟","zài huítóu yě bù chí"]],
   notes:[{t:"定个期限",p:"dìng ge qīxiàn",k:"expr",m:"기한을 정하다",tip:"허락과 거절 사이의 제3안을 만드는 실용적인 표현입니다."},
          {t:"再…也不迟",p:"zài… yě bù chí",k:"grammar",m:"그때 ~ 해도 늦지 않다",tip:"결정을 미루자고 설득하는 골격입니다."}]},
  {s:"B",zh:"这个法子我倒真没想过。至少他不会觉得我一口回绝。",py:"Zhège fǎzi wǒ dào zhēn méi xiǎng guo. Zhìshǎo tā bú huì juéde wǒ yìkǒu huíjué.",
   ko:"그 방법은 정말 생각 못 해 봤네요. 적어도 제가 단칼에 잘랐다고 느끼진 않겠어요.",
   ck:[["这个法子我倒真没想过","Zhège fǎzi wǒ dào zhēn méi xiǎng guo"],["至少他不会觉得","zhìshǎo tā bú huì juéde"],["我一口回绝","wǒ yìkǒu huíjué"]],
   notes:[{t:"倒真",p:"dào zhēn",k:"expr",m:"오히려 정말로",tip:"예상과 다른 깨달음을 드러내는 부사 조합입니다."},
          {t:"一口回绝",p:"yìkǒu huíjué",k:"idiom",m:"단칼에 거절하다",tip:"一口答应(두말없이 승낙하다)과 짝으로 외워 두세요."}]},
  {s:"A",zh:"就是这个道理。孩子要的不是允许，是你肯认真听一回。",py:"Jiù shì zhège dàolǐ. Háizi yào de bú shì yǔnxǔ, shì nǐ kěn rènzhēn tīng yì huí.",
   ko:"바로 그 이치예요. 아이가 원하는 건 허락이 아니라, 한 번 진지하게 들어 주는 거예요.",
   ck:[["就是这个道理","Jiù shì zhège dàolǐ"],["孩子要的不是允许","háizi yào de bú shì yǔnxǔ"],["是你肯认真听一回","shì nǐ kěn rènzhēn tīng yì huí"]],
   notes:[{t:"要的不是A，是B",p:"yào de bú shì A, shì B",k:"grammar",m:"원하는 건 A가 아니라 B다",tip:"상대의 진짜 욕구를 짚는 강한 문형입니다."},
          {t:"肯",p:"kěn",k:"word",m:"기꺼이 ~ 하려 하다",tip:"의지의 문제임을 드러냅니다. 他不肯说 = 말하려 들지 않는다."}]},
  {s:"B",zh:"行，今晚我就跟他好好聊一次，不拿别人家孩子比。",py:"Xíng, jīnwǎn wǒ jiù gēn tā hǎohǎo liáo yí cì, bù ná biérén jiā háizi bǐ.",
   ko:"좋아요, 오늘 밤에 한번 제대로 얘기해 볼게요. 남의 집 아이랑 비교하지 않고요.",
   ck:[["行，今晚我就跟他","Xíng, jīnwǎn wǒ jiù gēn tā"],["好好聊一次","hǎohǎo liáo yí cì"],["不拿别人家孩子比","bù ná biérén jiā háizi bǐ"]],
   notes:[{t:"拿A跟B比",p:"ná A gēn B bǐ",k:"grammar",m:"A를 B와 견주다",tip:"别拿我跟他比. 비교를 거부할 때 그대로 씁니다."}]}
 ],
 keys:[
  {zh:"中游偏上",py:"zhōngyóu piān shàng",ko:"중간보다 조금 위",
   ex:"我们部门业绩中游偏上，不算突出。",exPy:"Wǒmen bùmén yèjì zhōngyóu piān shàng, bú suàn tūchū.",exKo:"우리 부서 실적은 중간보다 조금 위지, 두드러지진 않습니다."},
  {zh:"站着说话不腰疼",py:"zhàn zhe shuōhuà bù yāoténg",ko:"남의 일이라 쉽게 말한다",
   ex:"你没干过这活，站着说话不腰疼。",exPy:"Nǐ méi gàn guo zhè huó, zhàn zhe shuōhuà bù yāoténg.",exKo:"이 일을 안 해 봤으니 남 얘기하듯 쉽게 말하는 거죠."},
  {zh:"争气",py:"zhēngqì",ko:"기대에 부응해 잘해 주다",
   ex:"这孩子争气，从来不用人操心。",exPy:"Zhè háizi zhēngqì, cónglái búyòng rén cāoxīn.",exKo:"이 아이는 잘해 줘서 애초에 걱정할 일이 없습니다."},
  {zh:"跟自己较劲",py:"gēn zìjǐ jiàojìn",ko:"스스로와 씨름하다",
   ex:"别老跟自己较劲，放过自己一回。",exPy:"Bié lǎo gēn zìjǐ jiàojìn, fàngguò zìjǐ yì huí.",exKo:"자꾸 자신과 씨름하지 말고 한 번쯤 놓아주세요."},
  {zh:"顶嘴",py:"dǐngzuǐ",ko:"말대꾸하다",
   ex:"我一说他就顶嘴，根本听不进去。",exPy:"Wǒ yì shuō tā jiù dǐngzuǐ, gēnběn tīng bu jìnqù.",exKo:"제가 한마디 하면 바로 말대꾸해서 아예 듣질 않습니다."},
  {zh:"当饭吃",py:"dāng fàn chī",ko:"밥벌이가 되다",
   ex:"兴趣归兴趣，可它当不了饭吃。",exPy:"Xìngqù guī xìngqù, kě tā dāng bu liǎo fàn chī.",exKo:"취미는 취미지, 그걸로 먹고살 수는 없습니다."},
  {zh:"耗不起",py:"hào bu qǐ",ko:"그만한 시간을 쓸 여유가 없다",
   ex:"这官司再拖下去，我可耗不起。",exPy:"Zhè guānsi zài tuō xiàqù, wǒ kě hào bu qǐ.",exKo:"이 소송이 더 길어지면 저는 감당할 여유가 없습니다."},
  {zh:"一口回绝",py:"yìkǒu huíjué",ko:"단칼에 거절하다",
   ex:"我还没说完，他就一口回绝了。",exPy:"Wǒ hái méi shuō wán, tā jiù yìkǒu huíjué le.",exKo:"제 말이 끝나기도 전에 그는 단칼에 거절했습니다."}
 ],
 out:[
  {q:"상대가 우리 아이 성적을 묻습니다. 얼버무리되 대화를 이어 보세요.",hint:"就那样吧 / 中游偏上 / 哪有啊"},
  {q:"상대의 위로가 남 얘기처럼 들립니다. 무례하지 않게 되받아 보세요.",hint:"站着说话不腰疼 / 您家孩子争气 / 您当然看得开"},
  {q:"아이가 원하는 진로를 반대하고 싶지만 단칼에 자르긴 싫습니다. 제3의 안을 내 보세요.",hint:"定个期限 / 再回头也不迟 / 别一口回绝"}
 ]
},
{
 id:"c3d4", day:19, cat:"중고거래·흥정", level:"HSK 5~6",
 title:"二手交易", titlePy:"èrshǒu jiāoyì", titleKo:"직거래 흥정 — 깎고, 버티고, 접점 찾기",
 names:{A:"买家 (사려는 사람)", B:"卖家 (파는 사람)"},
 brief:[
  "중고 직거래는 <b>가격을 다투는 자리이면서 동시에 신뢰를 확인하는 자리</b>입니다. 그래서 중국어 흥정에는 값을 깎는 말과, 상대가 사기꾼이 아님을 확인하는 말이 뒤섞여 나옵니다.",
  "이 대화의 뼈대는 셋입니다. 먼저 <b>근거를 들어 깎고</b>(다른 곳 시세, 사용 연수), 상대는 <b>근거로 되받고</b>(보관 상태, 구성품), 마지막에 <b>서로 한 걸음씩 물러서</b> 숫자를 맞춥니다.",
  "중국어 흥정에서 자주 나오는 무기가 <b>两码事</b>입니다. 「올려놓은 값과 실제 거래가는 별개」처럼, 상대가 든 근거의 성격 자체를 갈라 무력화하는 말입니다. 어떤 협상에서도 그대로 쓸 수 있습니다.",
  "마지막 <b>买卖不成情义在</b>는 중국 상거래의 오랜 인사말입니다. 거래가 성사되든 안 되든 사람 사이는 남긴다는 뜻으로, 값을 다툰 뒤의 공기를 정리해 줍니다."
 ],
 vocab:[
  {w:"诚心",p:"chéngxīn",m:"진심으로, 살 마음이 있어",lv:"HSK5"},
  {w:"成交价",p:"chéngjiāojià",m:"실제 거래 가격",lv:"HSK6"},
  {w:"两码事",p:"liǎng mǎ shì",m:"전혀 별개의 문제",lv:"구어"},
  {w:"成色",p:"chéngsè",m:"(물건의) 상태, 품질",lv:"HSK6"},
  {w:"折价",p:"zhéjià",m:"값을 깎다, 감가",lv:"HSK6"},
  {w:"划算",p:"huásuàn",m:"수지가 맞다",lv:"HSK5"},
  {w:"底线",p:"dǐxiàn",m:"마지노선",lv:"HSK6"},
  {w:"有的是",p:"yǒudeshì",m:"얼마든지 있다",lv:"구어"},
  {w:"出手",p:"chūshǒu",m:"(물건을) 처분하다",lv:"HSK6"},
  {w:"验机",p:"yànjī",m:"기기를 점검하다",lv:"구어"},
  {w:"痛快",p:"tòngkuài",m:"시원시원하다",lv:"HSK5"},
  {w:"照单全收",p:"zhàodān quánshōu",m:"제시한 대로 다 받다",lv:"성어"}
 ],
 lines:[
  {s:"A",zh:"您这台相机我看了半天了。能便宜点儿吗？诚心想要。",py:"Nín zhè tái xiàngjī wǒ kàn le bàntiān le. Néng piányi diǎnr ma? Chéngxīn xiǎng yào.",
   ko:"이 카메라 한참 봤습니다. 좀 깎아 주실 수 있나요? 진짜로 살 마음이 있어서요.",
   ck:[["您这台相机我看了半天了","Nín zhè tái xiàngjī wǒ kàn le bàntiān le"],["能便宜点儿吗","néng piányi diǎnr ma"],["诚心想要","chéngxīn xiǎng yào"]],
   notes:[{t:"看了半天",p:"kàn le bàntiān",k:"expr",m:"한참을 들여다봤다",tip:"半天은 반나절이 아니라 「꽤 오래」라는 과장 표현입니다."},
          {t:"诚心想要",p:"chéngxīn xiǎng yào",k:"expr",m:"진심으로 살 생각이 있다",tip:"흥정의 첫 카드입니다. 냉소적인 값 후려치기가 아님을 먼저 밝힙니다."}]},
  {s:"B",zh:"这个价我已经压到底了，再低我自己都亏。",py:"Zhège jià wǒ yǐjīng yā dào dǐ le, zài dī wǒ zìjǐ dōu kuī.",
   ko:"이 값은 이미 바닥까지 내린 겁니다. 더 낮추면 제가 손해예요.",
   ck:[["这个价我已经压到底了","Zhège jià wǒ yǐjīng yā dào dǐ le"],["再低我自己都亏","zài dī wǒ zìjǐ dōu kuī"]],
   notes:[{t:"压到底",p:"yā dào dǐ",k:"expr",m:"바닥까지 내리다",tip:"压价(값을 누르다) + 到底(끝까지)입니다. 더 못 내린다는 선언입니다."},
          {t:"再…都/就…",p:"zài… dōu…",k:"grammar",m:"더 ~ 하면 ~ 하다",tip:"가정을 짧게 만드는 골격입니다. 再晚就赶不上了."}]},
  {s:"A",zh:"我理解您的意思，可同款在别家挂的价比您低两百。",py:"Wǒ lǐjiě nín de yìsi, kě tóngkuǎn zài bié jiā guà de jià bǐ nín dī liǎng bǎi.",
   ko:"말씀은 이해합니다. 그런데 같은 모델이 다른 데는 200 낮게 올라와 있어요.",
   ck:[["我理解您的意思","Wǒ lǐjiě nín de yìsi"],["可同款在别家挂的价","kě tóngkuǎn zài bié jiā guà de jià"],["比您低两百","bǐ nín dī liǎng bǎi"]],
   notes:[{t:"挂的价",p:"guà de jià",k:"word",m:"올려놓은 값, 호가",tip:"挂는 온라인에 물건을 올린다는 뜻입니다. 挂出去卖."}]},
  {s:"B",zh:"挂的价和成交价是两码事。您真去问，人家未必卖。",py:"Guà de jià hé chéngjiāojià shì liǎng mǎ shì. Nín zhēn qù wèn, rénjia wèibì mài.",
   ko:"올려놓은 값과 실제 거래가는 별개예요. 정말 가서 물어보면 안 팔지도 모릅니다.",
   ck:[["挂的价和成交价是两码事","Guà de jià hé chéngjiāojià shì liǎng mǎ shì"],["您真去问","nín zhēn qù wèn"],["人家未必卖","rénjia wèibì mài"]],
   notes:[{t:"两码事",p:"liǎng mǎ shì",k:"idiom",m:"전혀 별개의 문제",tip:"상대 근거의 성격 자체를 갈라 무력화하는 강력한 반박입니다."},
          {t:"未必",p:"wèibì",k:"word",m:"반드시 ~ 인 것은 아니다",tip:"不一定의 문어적·단정적인 형태입니다."}]},
  {s:"A",zh:"那倒也是。不过您这台用了三年，快门数也不低吧？",py:"Nà dào yě shì. Búguò nín zhè tái yòng le sān nián, kuàiménshù yě bù dī ba?",
   ko:"그건 그렇네요. 그래도 이건 3년 쓰셨고, 셔터 수도 적지 않죠?",
   ck:[["那倒也是","Nà dào yě shì"],["不过您这台用了三年","búguò nín zhè tái yòng le sān nián"],["快门数也不低吧","kuàiménshù yě bù dī ba"]],
   notes:[{t:"那倒也是",p:"Nà dào yě shì",k:"expr",m:"그건 그렇네요",tip:"상대 말을 한 번 받아 준 뒤 다시 공격으로 넘어가는 완충입니다."}]},
  {s:"B",zh:"三年是三年，可我一直放防潮箱，成色您自己看。",py:"Sān nián shì sān nián, kě wǒ yìzhí fàng fángcháoxiāng, chéngsè nín zìjǐ kàn.",
   ko:"3년은 3년이죠. 그래도 늘 방습함에 넣어 뒀습니다. 상태는 직접 보세요.",
   ck:[["三年是三年","Sān nián shì sān nián"],["可我一直放防潮箱","kě wǒ yìzhí fàng fángcháoxiāng"],["成色您自己看","chéngsè nín zìjǐ kàn"]],
   notes:[{t:"A是A",p:"A shì A",k:"grammar",m:"A는 A지만",tip:"사실을 인정하되 결론은 내주지 않는 골격입니다. 贵是贵 / 忙是忙."},
          {t:"成色",p:"chéngsè",k:"word",m:"물건의 상태",tip:"원래는 금의 순도입니다. 중고 거래에서 가장 자주 쓰는 단어입니다."}]},
  {s:"A",zh:"成色确实不错，这我承认。可二手就是二手，总有折价。",py:"Chéngsè quèshí búcuò, zhè wǒ chéngrèn. Kě èrshǒu jiù shì èrshǒu, zǒng yǒu zhéjià.",
   ko:"상태는 확실히 좋네요, 그건 인정합니다. 그래도 중고는 중고라 감가는 있어야죠.",
   ck:[["成色确实不错，这我承认","Chéngsè quèshí búcuò, zhè wǒ chéngrèn"],["可二手就是二手","kě èrshǒu jiù shì èrshǒu"],["总有折价","zǒng yǒu zhéjià"]],
   notes:[{t:"A就是A",p:"A jiù shì A",k:"grammar",m:"A는 어디까지나 A다",tip:"앞의 A是A보다 단정적입니다. 상대의 예외 주장을 막습니다."}]},
  {s:"B",zh:"折价我认，但您得看我是连镜头一块儿给您的。",py:"Zhéjià wǒ rèn, dàn nín děi kàn wǒ shì lián jìngtóu yíkuàir gěi nín de.",
   ko:"감가는 인정합니다. 다만 제가 렌즈까지 함께 드리는 거라는 점은 봐 주셔야죠.",
   ck:[["折价我认","Zhéjià wǒ rèn"],["但您得看我是","dàn nín děi kàn wǒ shì"],["连镜头一块儿给您的","lián jìngtóu yíkuàir gěi nín de"]],
   notes:[{t:"我认",p:"wǒ rèn",k:"expr",m:"그건 인정합니다",tip:"짧게 한 칸 물러서며 신뢰를 사는 말입니다."},
          {t:"一块儿",p:"yíkuàir",k:"word",m:"함께, 한꺼번에",tip:"一起의 구어형입니다. 북방에서 특히 자주 들립니다."}]},
  {s:"A",zh:"镜头我本来也不缺，说实话我图的就是机身。",py:"Jìngtóu wǒ běnlái yě bù quē, shuō shíhuà wǒ tú de jiù shì jīshēn.",
   ko:"렌즈는 원래 부족하지 않아요. 솔직히 제가 노리는 건 바디입니다.",
   ck:[["镜头我本来也不缺","Jìngtóu wǒ běnlái yě bù quē"],["说实话","shuō shíhuà"],["我图的就是机身","wǒ tú de jiù shì jīshēn"]],
   notes:[{t:"图的就是…",p:"tú de jiù shì…",k:"expr",m:"노리는 것은 바로 ~ 다",tip:"图는 「바라다, 탐하다」입니다. 我图的是省事."}]},
  {s:"B",zh:"那就难办了。我这套是打包出，拆开卖我更不划算。",py:"Nà jiù nán bàn le. Wǒ zhè tào shì dǎbāo chū, chāikāi mài wǒ gèng bù huásuàn.",
   ko:"그럼 곤란해지네요. 저는 세트로 넘기는 거라, 쪼개 팔면 더 손해입니다.",
   ck:[["那就难办了","Nà jiù nán bàn le"],["我这套是打包出","wǒ zhè tào shì dǎbāo chū"],["拆开卖我更不划算","chāikāi mài wǒ gèng bù huásuàn"]],
   notes:[{t:"打包出",p:"dǎbāo chū",k:"expr",m:"묶어서 통째로 넘기다",tip:"打包는 음식 포장에도, 일괄 매각에도 씁니다."},
          {t:"划算",p:"huásuàn",k:"word",m:"수지가 맞다",tip:"不划算 = 남는 게 없다. 거래 대화의 핵심 단어입니다."}]},
  {s:"A",zh:"那咱们折中一下？您让两百，镜头我照单全收。",py:"Nà zánmen zhézhōng yíxià? Nín ràng liǎng bǎi, jìngtóu wǒ zhàodān quánshōu.",
   ko:"그럼 절충하죠. 200 깎아 주시면 렌즈는 주시는 대로 다 받겠습니다.",
   ck:[["那咱们折中一下","Nà zánmen zhézhōng yíxià"],["您让两百","nín ràng liǎng bǎi"],["镜头我照单全收","jìngtóu wǒ zhàodān quánshōu"]],
   notes:[{t:"折中",p:"zhézhōng",k:"word",m:"절충하다",tip:"서로 한 걸음씩 물러선다는 뜻입니다. 折中一下 = 중간에서 만나죠."},
          {t:"照单全收",p:"zhàodān quánshōu",k:"idiom",m:"제시한 대로 다 받다",tip:"원래는 계산서대로 다 받는다는 뜻입니다. 조건을 통째로 수용할 때 씁니다."}]},
  {s:"B",zh:"两百太狠了。一百，我再送您一张存储卡，这是底线。",py:"Liǎng bǎi tài hěn le. Yìbǎi, wǒ zài sòng nín yì zhāng cúnchǔkǎ, zhè shì dǐxiàn.",
   ko:"200은 너무 세요. 100에, 메모리 카드 한 장 더 드리는 게 제 마지노선입니다.",
   ck:[["两百太狠了","Liǎng bǎi tài hěn le"],["一百，我再送您一张存储卡","yìbǎi, wǒ zài sòng nín yì zhāng cúnchǔkǎ"],["这是底线","zhè shì dǐxiàn"]],
   notes:[{t:"太狠了",p:"tài hěn le",k:"expr",m:"너무 세다, 너무하다",tip:"값을 심하게 깎았을 때의 가벼운 항의입니다."},
          {t:"底线",p:"dǐxiàn",k:"word",m:"마지노선",tip:"협상에서 더 물러설 수 없는 선입니다. 这是我的底线."}]},
  {s:"A",zh:"存储卡我有的是。您要真想成交，不如再让五十。",py:"Cúnchǔkǎ wǒ yǒudeshì. Nín yào zhēn xiǎng chéngjiāo, bùrú zài ràng wǔshí.",
   ko:"메모리 카드는 얼마든지 있어요. 정말 거래하실 생각이면 50만 더 깎아 주시죠.",
   ck:[["存储卡我有的是","Cúnchǔkǎ wǒ yǒudeshì"],["您要真想成交","nín yào zhēn xiǎng chéngjiāo"],["不如再让五十","bùrú zài ràng wǔshí"]],
   notes:[{t:"有的是",p:"yǒudeshì",k:"expr",m:"얼마든지 있다",tip:"상대가 끼워 주는 물건의 값어치를 깎을 때 유용합니다. 时间有的是."},
          {t:"让",p:"ràng",k:"word",m:"(값을) 깎아 주다",tip:"让价 / 让五十. 흥정에서 가장 자주 쓰는 동사입니다."}]},
  {s:"B",zh:"您这是拿准了我急着出手。行，一百五，一分不能再少。",py:"Nín zhè shì názhǔn le wǒ jí zhe chūshǒu. Xíng, yìbǎi wǔ, yì fēn bù néng zài shǎo.",
   ko:"제가 빨리 처분하고 싶은 걸 정확히 읽으셨네요. 좋습니다, 150. 한 푼도 더는 못 깎습니다.",
   ck:[["您这是拿准了我急着出手","Nín zhè shì názhǔn le wǒ jí zhe chūshǒu"],["行，一百五","xíng, yìbǎi wǔ"],["一分不能再少","yì fēn bù néng zài shǎo"]],
   notes:[{t:"拿准",p:"názhǔn",k:"word",m:"속을 정확히 읽다",tip:"拿准了我的心思 = 내 속을 꿰뚫어 봤다."},
          {t:"一分不能再少",p:"yì fēn bù néng zài shǎo",k:"expr",m:"한 푼도 더는 못 깎는다",tip:"흥정을 닫는 정형화된 선언입니다."}]},
  {s:"A",zh:"成交。不过我得当面验机，快门、对焦、屏幕都得过一遍。",py:"Chéngjiāo. Búguò wǒ děi dāngmiàn yànjī, kuàimén, duìjiāo, píngmù dōu děi guò yí biàn.",
   ko:"거래 성사입니다. 다만 직접 점검은 해야겠어요. 셔터, 초점, 화면 다 한 번씩 봐야죠.",
   ck:[["成交","Chéngjiāo"],["不过我得当面验机","búguò wǒ děi dāngmiàn yànjī"],["快门、对焦、屏幕","kuàimén, duìjiāo, píngmù"],["都得过一遍","dōu děi guò yí biàn"]],
   notes:[{t:"当面",p:"dāngmiàn",k:"word",m:"직접 얼굴을 맞대고",tip:"当面说清楚 / 当面验货. 신뢰 확인의 핵심 부사입니다."},
          {t:"过一遍",p:"guò yí biàn",k:"expr",m:"한 차례 훑어보다",tip:"검수를 뜻합니다. 재무 자료에도 그대로 씁니다."}]},
  {s:"B",zh:"应该的。我也希望您验清楚，省得回头说我瞒着什么。",py:"Yīnggāi de. Wǒ yě xīwàng nín yàn qīngchu, shěngde huítóu shuō wǒ mán zhe shénme.",
   ko:"당연하죠. 저도 확실히 확인하시길 바랍니다. 나중에 제가 뭘 숨겼다는 말 안 나오게요.",
   ck:[["应该的","Yīnggāi de"],["我也希望您验清楚","wǒ yě xīwàng nín yàn qīngchu"],["省得回头说我瞒着什么","shěngde huítóu shuō wǒ mán zhe shénme"]],
   notes:[{t:"瞒着",p:"mán zhe",k:"word",m:"숨기고 있다",tip:"瞒着家里 / 瞒着不说. 고의로 감추는 것입니다."}]},
  {s:"A",zh:"那就这么定了。明天下午三点，地铁口那家咖啡店见。",py:"Nà jiù zhème dìng le. Míngtiān xiàwǔ sān diǎn, dìtiě kǒu nà jiā kāfēidiàn jiàn.",
   ko:"그럼 그렇게 정하죠. 내일 오후 3시, 지하철역 입구 그 카페에서 뵙겠습니다.",
   ck:[["那就这么定了","Nà jiù zhème dìng le"],["明天下午三点","míngtiān xiàwǔ sān diǎn"],["地铁口那家咖啡店见","dìtiě kǒu nà jiā kāfēidiàn jiàn"]],
   notes:[{t:"就这么定了",p:"jiù zhème dìng le",k:"expr",m:"그럼 그렇게 하기로 하죠",tip:"약속을 확정하는 마무리 문장입니다."}]},
  {s:"B",zh:"行。到时候我把发票和保修卡都一起带过去给您。",py:"Xíng. Dào shíhou wǒ bǎ fāpiào hé bǎoxiūkǎ dōu yìqǐ dài guòqù gěi nín.",
   ko:"좋습니다. 그때 영수증이랑 보증서도 다 같이 들고 나가겠습니다.",
   ck:[["行。到时候我把发票和保修卡","Xíng. Dào shíhou wǒ bǎ fāpiào hé bǎoxiūkǎ"],["都一起带过去给您","dōu yìqǐ dài guòqù gěi nín"]],
   notes:[{t:"把…带过去",p:"bǎ… dài guòqù",k:"grammar",m:"~ 를 가져가다",tip:"把자문입니다. 무엇을 어디로 옮기는지가 초점입니다."},
          {t:"到时候",p:"dào shíhou",k:"expr",m:"그때가 되면",tip:"약속한 시점을 가리킵니다. 到时候再说."}]},
  {s:"A",zh:"太好了。您这人痛快，我最怕的就是磨磨蹭蹭的卖家。",py:"Tài hǎo le. Nín zhè rén tòngkuài, wǒ zuì pà de jiù shì mómocèngcèng de màijiā.",
   ko:"잘됐네요. 시원시원하시네요. 제가 제일 싫어하는 게 꾸물거리는 판매자거든요.",
   ck:[["太好了","Tài hǎo le"],["您这人痛快","nín zhè rén tòngkuài"],["我最怕的就是","wǒ zuì pà de jiù shì"],["磨磨蹭蹭的卖家","mómocèngcèng de màijiā"]],
   notes:[{t:"痛快",p:"tòngkuài",k:"word",m:"시원시원하다",tip:"성격과 일처리 양쪽에 씁니다. 你真痛快."},
          {t:"磨磨蹭蹭",p:"mómocèngcèng",k:"expr",m:"꾸물거리다",tip:"첩어로 답답함을 강조합니다. 别磨蹭了，快走."}]},
  {s:"B",zh:"彼此彼此。买卖不成情义在，何况咱们这不是成了吗。",py:"Bǐcǐ bǐcǐ. Mǎimài bù chéng qíngyì zài, hékuàng zánmen zhè bú shì chéng le ma.",
   ko:"피차일반이죠. 거래가 안 돼도 정은 남는 법인데, 하물며 우린 성사됐잖습니까.",
   ck:[["彼此彼此","Bǐcǐ bǐcǐ"],["买卖不成情义在","mǎimài bù chéng qíngyì zài"],["何况咱们这不是成了吗","hékuàng zánmen zhè bú shì chéng le ma"]],
   notes:[{t:"彼此彼此",p:"bǐcǐ bǐcǐ",k:"expr",m:"피차일반입니다",tip:"칭찬을 되돌려 주는 겸양의 상투구입니다."},
          {t:"买卖不成情义在",p:"mǎimài bù chéng qíngyì zài",k:"idiom",m:"거래는 못 해도 정은 남는다",tip:"중국 상거래의 오랜 인사말입니다. 협상 결렬 때도 쓸 수 있습니다."}]}
 ],
 keys:[
  {zh:"压到底",py:"yā dào dǐ",ko:"바닥까지 값을 내리다",
   ex:"这个价我已经压到底了。",exPy:"Zhège jià wǒ yǐjīng yā dào dǐ le.",exKo:"이 값은 이미 바닥까지 내린 겁니다."},
  {zh:"两码事",py:"liǎng mǎ shì",ko:"전혀 별개의 문제",
   ex:"想做和做得到是两码事。",exPy:"Xiǎng zuò hé zuò de dào shì liǎng mǎ shì.",exKo:"하고 싶은 것과 해낼 수 있는 것은 별개입니다."},
  {zh:"A是A",py:"A shì A",ko:"A는 A지만",
   ex:"贵是贵，可这质量真找不着第二家。",exPy:"Guì shì guì, kě zhè zhìliàng zhēn zhǎo bu zháo dì èr jiā.",exKo:"비싼 건 비싼데, 이 품질은 정말 다른 데서 못 찾습니다."},
  {zh:"有的是",py:"yǒudeshì",ko:"얼마든지 있다",
   ex:"这种货市面上有的是，不着急。",exPy:"Zhè zhǒng huò shìmiàn shàng yǒudeshì, bù zháojí.",exKo:"이런 물건은 시중에 얼마든지 있으니 급할 것 없습니다."},
  {zh:"照单全收",py:"zhàodān quánshōu",ko:"제시한 대로 다 받다",
   ex:"您开的条件我照单全收。",exPy:"Nín kāi de tiáojiàn wǒ zhàodān quánshōu.",exKo:"제시하신 조건은 그대로 다 받겠습니다."},
  {zh:"一分不能再少",py:"yì fēn bù néng zài shǎo",ko:"한 푼도 더는 못 깎는다",
   ex:"一百五，一分不能再少了。",exPy:"Yìbǎi wǔ, yì fēn bù néng zài shǎo le.",exKo:"150입니다, 한 푼도 더는 못 깎습니다."},
  {zh:"磨磨蹭蹭",py:"mómocèngcèng",ko:"꾸물거리다",
   ex:"别磨磨蹭蹭的，人家等着呢。",exPy:"Bié mómocèngcèng de, rénjia děng zhe ne.",exKo:"꾸물거리지 마세요, 저쪽에서 기다리고 있습니다."},
  {zh:"买卖不成情义在",py:"mǎimài bù chéng qíngyì zài",ko:"거래는 못 해도 정은 남는다",
   ex:"这次谈不拢也没事，买卖不成情义在。",exPy:"Zhè cì tán bu lǒng yě méishì, mǎimài bù chéng qíngyì zài.",exKo:"이번에 합의가 안 돼도 괜찮습니다, 거래는 못 해도 정은 남으니까요."}
 ],
 out:[
  {q:"중고 물건을 사려 합니다. 살 마음이 있다는 걸 보이면서 값을 꺼내 보세요.",hint:"看了半天 / 诚心想要 / 能便宜点儿吗"},
  {q:"상대가 다른 곳 시세를 근거로 깎으려 합니다. 그 근거를 갈라 반박해 보세요.",hint:"挂的价和成交价是两码事 / 未必卖 / A是A"},
  {q:"값 차이가 좁혀지지 않습니다. 절충안을 내고 자리를 좋게 닫아 보세요.",hint:"折中一下 / 照单全收 / 买卖不成情义在"}
 ]
},
{
 id:"c3d5", day:20, cat:"사고·처리", level:"HSK 5~6",
 title:"剐蹭之后", titlePy:"guǎcèng zhīhòu", titleKo:"접촉사고 — 따지되 싸우지 않기",
 names:{A:"车主甲 (긁혔다고 주장하는 쪽)", B:"车主乙 (상대 차주)"},
 brief:[
  "주차장 접촉사고는 <b>손해액보다 감정이 먼저 커지는</b> 일입니다. 둘 다 자기가 조심했다고 믿고, 둘 다 상대가 먼저 움직였다고 기억합니다. 그래서 첫 세 마디가 그날의 결과를 거의 정합니다.",
  "중국에서 이런 일이 생기면 갈림길은 <b>私了(합의로 끝내기)</b>와 <b>报警(경찰 부르기)</b>입니다. 금액이 작으면 보험 처리가 오히려 손해라 합의로 가지만, 책임이 갈리면 경찰을 부르는 쪽이 <b>서로에게 안전</b>합니다.",
  "이 대화에서 눈여겨볼 것은 B의 태도입니다. 상대가 합의를 제안하자 <b>돈을 아끼려 하기보다 절차를 택합니다</b>. 나중에 번복당할 여지를 없애기 위해서입니다. 上哪儿说理去 한마디에 그 판단이 담겨 있습니다.",
  "마지막 네 줄은 <b>화해의 언어</b>입니다. 语气冲했던 것을 서로 사과하고, 새 차라서 그랬다고 이해해 주고, 다투던 두 사람이 谁也不欠谁로 자리를 닫습니다. 싸운 뒤 관계를 되돌리는 표현들입니다."
 ],
 vocab:[
  {w:"剐蹭",p:"guǎcèng",m:"차를 긁다, 접촉사고",lv:"구어"},
  {w:"倒车",p:"dàochē",m:"후진하다",lv:"HSK5"},
  {w:"划痕",p:"huáhén",m:"긁힌 자국",lv:"구어"},
  {w:"走保险",p:"zǒu bǎoxiǎn",m:"보험으로 처리하다",lv:"구어"},
  {w:"私了",p:"sīliǎo",m:"합의로 끝내다",lv:"구어"},
  {w:"全责",p:"quánzé",m:"전적인 책임",lv:"HSK6"},
  {w:"反悔",p:"fǎnhuǐ",m:"말을 번복하다",lv:"HSK6"},
  {w:"担待",p:"dāndài",m:"너그럽게 봐주다",lv:"구어"},
  {w:"上头",p:"shàngtóu",m:"욱하다, 열이 오르다",lv:"구어"},
  {w:"照实",p:"zhàoshí",m:"사실대로",lv:"HSK6"},
  {w:"带刺",p:"dài cì",m:"말에 가시가 있다",lv:"구어"},
  {w:"顺气",p:"shùn qì",m:"화가 가라앉다",lv:"구어"}
 ],
 lines:[
  {s:"A",zh:"师傅，您这车是不是刚才倒车的时候蹭到我了？",py:"Shīfu, nín zhè chē shì bu shì gāngcái dàochē de shíhou cèng dào wǒ le?",
   ko:"기사님, 이 차 아까 후진하실 때 제 차를 긁으신 거 아닌가요?",
   ck:[["师傅，您这车是不是","Shīfu, nín zhè chē shì bu shì"],["刚才倒车的时候","gāngcái dàochē de shíhou"],["蹭到我了","cèng dào wǒ le"]],
   notes:[{t:"师傅",p:"shīfu",k:"culture",m:"기사님, 아저씨",tip:"모르는 남성 운전자·기술자를 부르는 호칭입니다. 이름을 몰라도 실례가 아닙니다."},
          {t:"是不是…？",p:"shì bu shì…",k:"grammar",m:"~ 한 거 아닌가요",tip:"단정하지 않고 확인을 구하는 형태로, 첫마디를 부드럽게 만듭니다."}]},
  {s:"B",zh:"不能这么说吧。我倒的时候您也在往前挪，谁蹭谁还不一定。",py:"Bù néng zhème shuō ba. Wǒ dào de shíhou nín yě zài wǎng qián nuó, shéi cèng shéi hái bù yídìng.",
   ko:"그렇게 말씀하시면 안 되죠. 제가 후진할 때 그쪽도 앞으로 움직이고 있었어요. 누가 누굴 긁었는지는 아직 모릅니다.",
   ck:[["不能这么说吧","Bù néng zhème shuō ba"],["我倒的时候您也在往前挪","wǒ dào de shíhou nín yě zài wǎng qián nuó"],["谁蹭谁还不一定","shéi cèng shéi hái bù yídìng"]],
   notes:[{t:"不能这么说吧",p:"bù néng zhème shuō ba",k:"expr",m:"그렇게 말씀하시면 곤란하죠",tip:"단정을 되받는 표준 반박입니다. 吧가 붙어 날이 조금 무뎌집니다."},
          {t:"还不一定",p:"hái bù yídìng",k:"expr",m:"아직은 알 수 없다",tip:"결론을 유보시키는 말입니다. 谁赢还不一定."}]},
  {s:"A",zh:"那咱们别争了，先拍照。行车记录仪您有吧？",py:"Nà zánmen bié zhēng le, xiān pāizhào. Xíngchē jìlùyí nín yǒu ba?",
   ko:"그럼 다투지 말고 먼저 사진부터 찍죠. 블랙박스는 있으시죠?",
   ck:[["那咱们别争了，先拍照","Nà zánmen bié zhēng le, xiān pāizhào"],["行车记录仪您有吧","xíngchē jìlùyí nín yǒu ba"]],
   notes:[{t:"别争了",p:"bié zhēng le",k:"expr",m:"그만 다툽시다",tip:"감정이 올라간 자리를 절차로 되돌리는 한마디입니다."},
          {t:"行车记录仪",p:"xíngchē jìlùyí",k:"word",m:"블랙박스",tip:"한국어의 블랙박스는 중국어로 이 말입니다. 그대로 외워 두세요."}]},
  {s:"B",zh:"有是有，可我那个角度不一定拍得着。您先看看伤在哪儿。",py:"Yǒu shì yǒu, kě wǒ nàge jiǎodù bù yídìng pāi de zháo. Nín xiān kànkan shāng zài nǎr.",
   ko:"있긴 있는데, 제 각도에서는 안 찍혔을 수도 있어요. 먼저 어디가 상했는지 보시죠.",
   ck:[["有是有","Yǒu shì yǒu"],["可我那个角度不一定拍得着","kě wǒ nàge jiǎodù bù yídìng pāi de zháo"],["您先看看伤在哪儿","nín xiān kànkan shāng zài nǎr"]],
   notes:[{t:"有是有",p:"yǒu shì yǒu",k:"grammar",m:"있긴 있지만",tip:"A是A 골격입니다. 인정하면서 곧바로 단서를 답니다."},
          {t:"拍得着",p:"pāi de zháo",k:"grammar",m:"(사진에) 담을 수 있다",tip:"가능보어입니다. 着는 목적 달성을 뜻합니다. 买得着 / 找不着."}]},
  {s:"A",zh:"右后门下边一道划痕，不深，但漆肯定是破了。",py:"Yòu hòumén xiàbian yí dào huáhén, bù shēn, dàn qī kěndìng shì pò le.",
   ko:"오른쪽 뒷문 아래에 긁힌 자국 하나요. 깊진 않은데 도장은 확실히 까졌습니다.",
   ck:[["右后门下边一道划痕","Yòu hòumén xiàbian yí dào huáhén"],["不深","bù shēn"],["但漆肯定是破了","dàn qī kěndìng shì pò le"]],
   notes:[{t:"一道划痕",p:"yí dào huáhén",k:"measure",m:"긁힌 자국 하나",tip:"길게 난 자국에는 道를 씁니다. 一道疤 / 一道口子."}]},
  {s:"B",zh:"这么一点儿，走保险不划算，出险记录比修车费还贵。",py:"Zhème yìdiǎnr, zǒu bǎoxiǎn bù huásuàn, chūxiǎn jìlù bǐ xiūchēfèi hái guì.",
   ko:"이 정도로 보험 처리하면 손해예요. 사고 기록이 수리비보다 비싸게 먹힙니다.",
   ck:[["这么一点儿","Zhème yìdiǎnr"],["走保险不划算","zǒu bǎoxiǎn bù huásuàn"],["出险记录比修车费还贵","chūxiǎn jìlù bǐ xiūchēfèi hái guì"]],
   notes:[{t:"走保险",p:"zǒu bǎoxiǎn",k:"expr",m:"보험으로 처리하다",tip:"走는 「~ 경로로 가다」입니다. 走公账 / 走流程."},
          {t:"A比B还贵",p:"A bǐ B hái guì",k:"grammar",m:"A가 B보다 더 비싸다",tip:"还가 붙어 「의외로 더」라는 어감이 실립니다."}]},
  {s:"A",zh:"这个我同意。要不咱们私了吧，您看着给个数？",py:"Zhège wǒ tóngyì. Yàobù zánmen sīliǎo ba, nín kàn zhe gěi ge shù?",
   ko:"그건 동의합니다. 그럼 합의로 끝낼까요? 알아서 금액을 불러 보시겠어요?",
   ck:[["这个我同意","Zhège wǒ tóngyì"],["要不咱们私了吧","yàobù zánmen sīliǎo ba"],["您看着给个数","nín kàn zhe gěi ge shù"]],
   notes:[{t:"私了",p:"sīliǎo",k:"word",m:"합의로 끝내다",tip:"경찰이나 보험을 부르지 않고 당사자끼리 끝내는 것입니다. 了는 liǎo로 읽습니다."},
          {t:"给个数",p:"gěi ge shù",k:"expr",m:"금액을 제시하다",tip:"구체적 숫자를 요구하는 구어입니다. 你给个数吧."}]},
  {s:"B",zh:"我给数？这不合适。责任还没分清，凭什么我先出钱。",py:"Wǒ gěi shù? Zhè bù héshì. Zérèn hái méi fēnqīng, píng shénme wǒ xiān chū qián.",
   ko:"제가 금액을요? 그건 맞지 않죠. 책임이 아직 안 갈렸는데 무슨 근거로 제가 먼저 냅니까.",
   ck:[["我给数","Wǒ gěi shù"],["这不合适","zhè bù héshì"],["责任还没分清","zérèn hái méi fēnqīng"],["凭什么我先出钱","píng shénme wǒ xiān chū qián"]],
   notes:[{t:"凭什么",p:"píng shénme",k:"expr",m:"무슨 근거로",tip:"강한 항의입니다. 억울함을 드러내지만 욕은 아닙니다."},
          {t:"分清",p:"fēnqīng",k:"word",m:"분명히 가리다",tip:"责任分清 / 是非分清. 뒤에 결과보어 清이 붙은 형태입니다."}]},
  {s:"A",zh:"您别急。我不是说全算您的，我是想省了报警那道手续。",py:"Nín bié jí. Wǒ bú shì shuō quán suàn nín de, wǒ shì xiǎng shěng le bàojǐng nà dào shǒuxù.",
   ko:"흥분하지 마세요. 전부 그쪽 책임이라는 게 아니라, 신고 절차를 생략하자는 뜻이었어요.",
   ck:[["您别急","Nín bié jí"],["我不是说全算您的","wǒ bú shì shuō quán suàn nín de"],["我是想省了报警那道手续","wǒ shì xiǎng shěng le bàojǐng nà dào shǒuxù"]],
   notes:[{t:"不是A，是B",p:"bú shì A, shì B",k:"grammar",m:"A가 아니라 B다",tip:"오해를 즉시 바로잡는 가장 빠른 골격입니다."},
          {t:"那道手续",p:"nà dào shǒuxù",k:"measure",m:"그 절차 한 단계",tip:"절차의 단계를 道로 셉니다. 走一道手续."}]},
  {s:"B",zh:"报警反而最省事。交警一来，责任怎么分当场就定了。",py:"Bàojǐng fǎn'ér zuì shěngshì. Jiāojǐng yì lái, zérèn zěnme fēn dāngchǎng jiù dìng le.",
   ko:"신고하는 게 오히려 제일 간단해요. 교통경찰이 오면 책임 분담이 그 자리에서 정해지니까요.",
   ck:[["报警反而最省事","Bàojǐng fǎn'ér zuì shěngshì"],["交警一来","jiāojǐng yì lái"],["责任怎么分当场就定了","zérèn zěnme fēn dāngchǎng jiù dìng le"]],
   notes:[{t:"反而",p:"fǎn'ér",k:"word",m:"오히려",tip:"예상과 반대되는 결론을 이끕니다. 越解释反而越乱."},
          {t:"一…就…",p:"yì… jiù…",k:"grammar",m:"~ 하기만 하면 바로 ~",tip:"조건과 결과를 붙여 말하는 기본 골격입니다."}]},
  {s:"A",zh:"也行。不过等交警得半小时，我后面还有个约。",py:"Yě xíng. Búguò děng jiāojǐng děi bàn xiǎoshí, wǒ hòumian hái yǒu ge yuē.",
   ko:"그것도 좋죠. 다만 경찰 기다리는 데 30분은 걸리는데, 제가 뒤에 약속이 있어서요.",
   ck:[["也行","Yě xíng"],["不过等交警得半小时","búguò děng jiāojǐng děi bàn xiǎoshí"],["我后面还有个约","wǒ hòumian hái yǒu ge yuē"]],
   notes:[{t:"还有个约",p:"hái yǒu ge yuē",k:"expr",m:"뒤에 약속이 하나 더 있다",tip:"서두르는 이유를 대는 완곡한 표현입니다."}]},
  {s:"B",zh:"那您就更该报了。回头您要是反悔，我上哪儿说理去。",py:"Nà nín jiù gèng gāi bào le. Huítóu nín yàoshi fǎnhuǐ, wǒ shàng nǎr shuōlǐ qù.",
   ko:"그럼 더더욱 신고하셔야죠. 나중에 말을 바꾸시면 저는 어디 가서 따집니까.",
   ck:[["那您就更该报了","Nà nín jiù gèng gāi bào le"],["回头您要是反悔","huítóu nín yàoshi fǎnhuǐ"],["我上哪儿说理去","wǒ shàng nǎr shuōlǐ qù"]],
   notes:[{t:"反悔",p:"fǎnhuǐ",k:"word",m:"말을 번복하다",tip:"약속이나 합의를 되무르는 것입니다. 说好了别反悔."},
          {t:"上哪儿说理去",p:"shàng nǎr shuōlǐ qù",k:"idiom",m:"어디 가서 따지겠습니까",tip:"억울함을 호소할 데가 없다는 반문입니다."}]},
  {s:"A",zh:"说得也是。那这样，咱们先各自拍照，再一块儿等。",py:"Shuō de yě shì. Nà zhèyàng, zánmen xiān gèzì pāizhào, zài yíkuàir děng.",
   ko:"그 말도 맞네요. 그럼 이렇게 하죠, 각자 사진부터 찍고 같이 기다립시다.",
   ck:[["说得也是","Shuō de yě shì"],["那这样，咱们先各自拍照","nà zhèyàng, zánmen xiān gèzì pāizhào"],["再一块儿等","zài yíkuàir děng"]],
   notes:[{t:"说得也是",p:"shuō de yě shì",k:"expr",m:"그 말도 맞네요",tip:"상대에게 한 칸 물러서며 긴장을 푸는 말입니다."},
          {t:"那这样",p:"nà zhèyàng",k:"expr",m:"그럼 이렇게 하죠",tip:"해법을 제안하기 직전에 놓는 신호입니다."}]},
  {s:"B",zh:"这才是正办。我刚才语气有点冲，您多担待，别见怪。",py:"Zhè cái shì zhèngbàn. Wǒ gāngcái yǔqì yǒudiǎn chòng, nín duō dāndài, bié jiànguài.",
   ko:"그게 제대로 된 방법이죠. 아까 제 말투가 좀 셌습니다, 너그럽게 봐 주시고 언짢아 마세요.",
   ck:[["这才是正办","Zhè cái shì zhèngbàn"],["我刚才语气有点冲","wǒ gāngcái yǔqì yǒudiǎn chòng"],["您多担待，别见怪","nín duō dāndài, bié jiànguài"]],
   notes:[{t:"语气冲",p:"yǔqì chòng",k:"expr",m:"말투가 세다",tip:"冲은 chòng으로 읽어 「기세가 거칠다」는 뜻입니다."},
          {t:"多担待",p:"duō dāndài",k:"expr",m:"너그럽게 봐 주세요",tip:"사과와 부탁 사이의 표현입니다. 사과를 무겁지 않게 만듭니다."}]},
  {s:"A",zh:"我也一样。停车场里谁都紧张，说话就容易带刺。",py:"Wǒ yě yíyàng. Tíngchēchǎng lǐ shéi dōu jǐnzhāng, shuōhuà jiù róngyì dài cì.",
   ko:"저도 마찬가지입니다. 주차장에서는 다들 예민해서 말에 가시가 붙기 쉽죠.",
   ck:[["我也一样","Wǒ yě yíyàng"],["停车场里谁都紧张","tíngchēchǎng lǐ shéi dōu jǐnzhāng"],["说话就容易带刺","shuōhuà jiù róngyì dài cì"]],
   notes:[{t:"带刺",p:"dài cì",k:"expr",m:"말에 가시가 있다",tip:"说话带刺 = 가시 돋친 말을 하다. 비난을 부드럽게 일반화하고 있습니다."}]},
  {s:"B",zh:"说的是。我这车刚提三个月，一看划痕就上头了。",py:"Shuō de shì. Wǒ zhè chē gāng tí sān ge yuè, yí kàn huáhén jiù shàngtóu le.",
   ko:"맞는 말씀입니다. 이 차 뽑은 지 석 달밖에 안 됐는데, 긁힌 자국을 보니 확 올라오더군요.",
   ck:[["说的是","Shuō de shì"],["我这车刚提三个月","wǒ zhè chē gāng tí sān ge yuè"],["一看划痕就上头了","yí kàn huáhén jiù shàngtóu le"]],
   notes:[{t:"提车",p:"tí chē",k:"word",m:"차를 인도받다",tip:"刚提的车 = 막 뽑은 차. 자동차 이야기의 필수 동사입니다."},
          {t:"上头",p:"shàngtóu",k:"word",m:"욱하다, 열이 오르다",tip:"술기운이 오르는 것과 감정이 치미는 것 양쪽에 씁니다."}]},
  {s:"A",zh:"换我也一样。新车那点心疼，旁人真体会不了。",py:"Huàn wǒ yě yíyàng. Xīn chē nà diǎn xīnténg, pángrén zhēn tǐhuì bu liǎo.",
   ko:"저라도 똑같았을 겁니다. 새 차 아까운 그 마음은 남이 정말 못 헤아리죠.",
   ck:[["换我也一样","Huàn wǒ yě yíyàng"],["新车那点心疼","xīn chē nà diǎn xīnténg"],["旁人真体会不了","pángrén zhēn tǐhuì bu liǎo"]],
   notes:[{t:"体会不了",p:"tǐhuì bu liǎo",k:"grammar",m:"헤아릴 수 없다",tip:"가능보어입니다. 了는 liǎo로 읽습니다. 受不了 / 忘不了."}]},
  {s:"B",zh:"交警来了。咱们照实说，责任怎么定，我一句都不多说。",py:"Jiāojǐng lái le. Zánmen zhàoshí shuō, zérèn zěnme dìng, wǒ yí jù dōu bù duō shuō.",
   ko:"경찰 왔네요. 사실대로 말하죠. 책임이 어떻게 나오든 저는 한마디도 더 안 보태겠습니다.",
   ck:[["交警来了","Jiāojǐng lái le"],["咱们照实说","zánmen zhàoshí shuō"],["责任怎么定","zérèn zěnme dìng"],["我一句都不多说","wǒ yí jù dōu bù duō shuō"]],
   notes:[{t:"照实说",p:"zhàoshí shuō",k:"expr",m:"사실대로 말하다",tip:"照 + 명사로 「~ 에 따라」를 만듭니다. 照规定办 / 照原样."},
          {t:"一句都不…",p:"yí jù dōu bù…",k:"grammar",m:"한마디도 ~ 하지 않다",tip:"一 + 양사 + 都 + 부정으로 전면 부정을 만듭니다."}]},
  {s:"A",zh:"痛快。真要是判我全责，修车钱我一分不少给您。",py:"Tòngkuài. Zhēn yàoshi pàn wǒ quánzé, xiūchē qián wǒ yì fēn bù shǎo gěi nín.",
   ko:"시원시원하시네요. 정말 제 전적인 책임으로 나오면 수리비는 한 푼도 빠짐없이 드리겠습니다.",
   ck:[["痛快","Tòngkuài"],["真要是判我全责","zhēn yàoshi pàn wǒ quánzé"],["修车钱我一分不少给您","xiūchē qián wǒ yì fēn bù shǎo gěi nín"]],
   notes:[{t:"全责",p:"quánzé",k:"word",m:"전적인 책임",tip:"교통사고에서는 全责 / 主责 / 次责 / 同责로 나눕니다."},
          {t:"一分不少",p:"yì fēn bù shǎo",k:"expr",m:"한 푼도 빠짐없이",tip:"금액을 다 치르겠다는 약속입니다."}]},
  {s:"B",zh:"那就这么办。事儿说清楚了，气也就顺了，谁也不欠谁。",py:"Nà jiù zhème bàn. Shìr shuō qīngchu le, qì yě jiù shùn le, shéi yě bú qiàn shéi.",
   ko:"그럼 그렇게 합시다. 일이 분명해지면 화도 가라앉고, 서로 빚진 것도 없는 거죠.",
   ck:[["那就这么办","Nà jiù zhème bàn"],["事儿说清楚了","shìr shuō qīngchu le"],["气也就顺了","qì yě jiù shùn le"],["谁也不欠谁","shéi yě bú qiàn shéi"]],
   notes:[{t:"气顺了",p:"qì shùn le",k:"expr",m:"화가 가라앉다",tip:"气不顺 = 속이 불편하다. 감정의 상태를 기의 흐름으로 말합니다."},
          {t:"谁也不欠谁",p:"shéi yě bú qiàn shéi",k:"expr",m:"서로 빚진 것 없다",tip:"다툼을 깨끗이 닫는 마무리 문장입니다."}]}
 ],
 keys:[
  {zh:"还不一定",py:"hái bù yídìng",ko:"아직은 알 수 없다",
   ex:"谁对谁错还不一定呢。",exPy:"Shéi duì shéi cuò hái bù yídìng ne.",exKo:"누가 맞고 틀린지는 아직 알 수 없습니다."},
  {zh:"走保险",py:"zǒu bǎoxiǎn",ko:"보험으로 처리하다",
   ex:"这点小伤走保险不划算。",exPy:"Zhè diǎn xiǎo shāng zǒu bǎoxiǎn bù huásuàn.",exKo:"이 정도 작은 흠집은 보험 처리하면 손해입니다."},
  {zh:"私了",py:"sīliǎo",ko:"합의로 끝내다",
   ex:"要不咱们私了，别惊动保险公司。",exPy:"Yàobù zánmen sīliǎo, bié jīngdòng bǎoxiǎn gōngsī.",exKo:"그럼 합의로 끝내죠, 보험사까지 부르지 말고요."},
  {zh:"凭什么",py:"píng shénme",ko:"무슨 근거로",
   ex:"责任没分清，凭什么让我先出钱？",exPy:"Zérèn méi fēnqīng, píng shénme ràng wǒ xiān chū qián?",exKo:"책임도 안 갈렸는데 무슨 근거로 저더러 먼저 내라는 겁니까?"},
  {zh:"上哪儿说理去",py:"shàng nǎr shuōlǐ qù",ko:"어디 가서 따지겠습니까",
   ex:"合同没签，出了事我上哪儿说理去。",exPy:"Hétong méi qiān, chū le shì wǒ shàng nǎr shuōlǐ qù.",exKo:"계약서도 없는데 일이 터지면 저는 어디 가서 따집니까."},
  {zh:"多担待",py:"duō dāndài",ko:"너그럽게 봐 주세요",
   ex:"我刚才话说重了，您多担待。",exPy:"Wǒ gāngcái huà shuō zhòng le, nín duō dāndài.",exKo:"아까 말이 좀 심했습니다, 너그럽게 봐 주세요."},
  {zh:"上头",py:"shàngtóu",ko:"욱하다, 열이 오르다",
   ex:"当时我一上头，话就说出去了。",exPy:"Dāngshí wǒ yí shàngtóu, huà jiù shuō chūqù le.",exKo:"그때 욱해서 말이 그냥 튀어나가 버렸습니다."},
  {zh:"谁也不欠谁",py:"shéi yě bú qiàn shéi",ko:"서로 빚진 것 없다",
   ex:"账算清了，从此谁也不欠谁。",exPy:"Zhàng suàn qīng le, cóngcǐ shéi yě bú qiàn shéi.",exKo:"셈이 끝났으니 이제 서로 빚진 것 없습니다."}
 ],
 out:[
  {q:"주차장에서 상대 차가 내 차를 긁은 것 같습니다. 단정하지 않고 말을 꺼내 보세요.",hint:"是不是…？ / 刚才倒车的时候 / 先拍照"},
  {q:"상대가 합의로 끝내자고 합니다. 절차대로 가자고 설득해 보세요.",hint:"责任还没分清 / 报警反而最省事 / 上哪儿说理去"},
  {q:"언성이 높아졌던 것을 서로 풀고 자리를 닫아 보세요.",hint:"语气有点冲 / 多担待 / 谁也不欠谁"}
 ]
}
